### ISSUE TITLE
Wrong argument count in preferences.java

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/android#1000]
![2015-06-04_10-42-29](https://cloud.githubusercontent.com/assets/878997/7980279/77b83a1c-0aa6-11e5-8762-b45df16a722d.png)
![2015-06-04_10-44-03](https://cloud.githubusercontent.com/assets/878997/7980302/9ed7063c-0aa6-11e5-8ceb-d0be98b849e2.png)

**Comment by masensio** [comment]
Hi @LukasReschke,

yes, it is a bug.
I've fixed this bug in the navigationDrawer_basic branch (commit https://github.com/owncloud/android/commit/b6d7cd73c7cd18d5a58bcb983552ae94c4bf1bd4, line 257). So the fix in the Pull Request https://github.com/owncloud/android/pull/995.

Thanks for reporting the bug.

**Comment by masensio** [comment]
PR #995 is in develop. So I'll close this issue.
