### ISSUE TITLE
Share Links are broken

### ISSUE THREAD

**Issue by mrflow** [owncloud/android#1003]
When sharing Files from the ownCloud app and sending them with, i.e. WhatsApp, the Links are not working. The link look will look like this:

https://cloud.brainflush.org/public.php?service=files&t=7HlVzdrskwqCTT8

Looks to me like this is an outdated link format, or my server is incorrectly configured (nginx, php-fpm, centos7)

Through the web interface i get this link (works):
https://cloud.brainflush.org/index.php/s/7HlVzdrskwqCTT8

**Comment by RealRancor** [comment]
Hi,

just tested your server with:

> curl -I "https://yourcloud/public.php?service=files&t=7HlVzdrskwqCTT8"

which issues an "HTTP/1.1 304 Found" where my NginX on OC 8.0.3 and also https://demo.owncloud.org" with a request like:

> curl -I "https://demo.owncloud.org/public.php?service=files&t=FD3in89Z3Z6EnbA"

is issuing an "HTTP/1.1 307 Temporary Redirect" to the new service URL "/index.php/s/7HlVzdrskwqCTT8"

From my PoV this is an issue within your NginX config. Make sure that you're using the official one provided here:

https://doc.owncloud.org/server/8.0/admin_manual/installation/nginx_configuration.html

**Comment by mrflow** [comment]
Hi, thanks for the hint.

My problem seems to be caused by the https reverse proxy I use. It changes the 307 to 304. No idea why.
