### ISSUE TITLE
External Storage Errors Passed from Server to Mobile (Android)

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1004]
As an ownCloud administrator, I would like a mechanism to pass external storage credential errors to the mobile clients so that users on their devices can address any problems with external storage, and continue to use ownCloud even after an error (in conjunction with: owncloud/core#16306 )

Acceptance Criteria:
- The error needs to be able to identify a problem with external storage and pass an error that does not cause the client to delete the directory, rather a temporary error that notifies the user that the directory is not syncing
- All errors are assumed to be temporary network or credential issues, rather than permanent failures
  - If external storage is permanently affected, the admin will have to remove it (or the user, if it is a personal mount) to resolve the errors
- The error needs to specifically identify the kind of problem (such as a credentials error), server not found error, etc
- The error also needs to specify a path so that the error can be addressed by the clients (such as opening a browser to the appropriate URL) and then allowing the user to resolve the issue. The error cannot be assumed to be in the root directory, as external storage can be moved around inside owncloud

iOS Version: https://github.com/owncloud/ios/issues/382

Desktop Version: https://github.com/owncloud/client/issues/3308

LONGER TERM:
The desktop clients would provide a communications path for passing messages to and from ownCloud clients (such as a credentials error AND a built in login screen) - so a general class of error that can be reused would be a good concept here. Related: owncloud/core#16772

____

BUGS & IMPROVEMENTS

- [X] Incorrect error message uploads https://github.com/owncloud/android/issues/1004#issuecomment-278648662 [FIXED]
- [X] Incorrect error message downloads  https://github.com/owncloud/android/issues/1004#issuecomment-278649569  [FIXED]

**Comment by davivel** [comment]
@davigonz , let's try to keep this simple. 

The better place to catch an error in refresh without too much refactoring is this:

https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/activity/FileDisplayActivity.java#L974

Adding a new check in the block for a specific ResultCode should be enough. I would expect that the failed response from the server includes an error message in the body, similar to what you handled in firewall errors.

**Comment by davigonz** [comment]
Sure, I will check it, thx!

**Comment by jesmrec** [comment]
### Bug

Steps

1. Connect oC to a external storage
2. Change the password to access the external storage
3. Try to upload into the external storage folder

Current behaviour

`Server in maintenance mode`is shown in the notification and in uploads view

Expected behaviour

A descriptive message about the lack of connection. For example, the same as the one shown in snackbar `Storage not available`

Tested with Nexus5 v5.0.1
Server 8.2, connected to an oC v10.0

CC @davigonz

**Comment by jesmrec** [comment]
Same as previous message happens with downloaded. Notification message is `Server in maintenance mode`

**Comment by jesmrec** [comment]
Approved

**Comment by davigonz** [comment]
I've changed HEAD method for PROPFIND method before uploading a file in order to receive a response body with more information and improve error handling.
