### ISSUE TITLE
Can't build using gradle

### ISSUE THREAD

**Issue by BenoitDuffez** [owncloud/android#1007]
Here's what a get from a fresh `git clone`:

```
$ ./gradlew ass

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ownCloud'.
> Cannot evaluate module owncloud-android-library : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.54 secs
```

Is there any thing to do to make `owncloud-android-library` to work properly?

**Comment by BenoitDuffez** [comment]
Didn't read setup.md. sorry.

**Comment by lawimutuma** [comment]
Please share what you did to get rid of the error. I have read the setup.md but still keep getting the error from Android Studio

**Comment by BenoitDuffez** [comment]
You have tonexecute the `setup_env.sh` script and then everything works.

**Comment by lawimutuma** [comment]
Thanks. I missed that step. All good now

**Comment by seshagiri96** [comment]
But that file is present no more?. I am stuck at the same problem . Please help.

**Comment by AndyScherzinger** [comment]
@seshagiri96 you dont need that one anymore you just need to either do a recursive git checkout or you need to call git submodule update from the command line in the projects root folder. Else you are missing the android-lib project

**Comment by thakurmaneesha** [comment]
@AndyScherzinger  Hi please help  me out , i am not able to import this owncloud project , i want to customize this app . Can u help me !
Getting this following error:-
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'CloundGitup'.
> Cannot evaluate module owncloud-android-library : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.27 secs

**Comment by AndyScherzinger** [comment]
@thakurmaneesha before you import the project into Android Studio or try to build it from command line you first need to checkout the android-library. In the root folder of your checkout execute the following git commands:
```
git submodule init
git submodule update
```
