### ISSUE TITLE
Automatically descend into the newly-created directory in the upload pane

### ISSUE THREAD

**Issue by strugee** [owncloud/android#1010]
When the user creates a new directory in the upload pane, the app should automatically descend into that directory.

**Comment by masensio** [comment]
Hi @strugee,

I think this is a good point. We will into account for future enhacements. 

Thanks.

**Comment by davivel** [comment]
@jancborchardt , please, your opinion here? I'm not sure that's so cool.

**Comment by jancborchardt** [comment]
I think it’s a good point since it’s likely that you want to upload something into a new folder when you create it. @strugee did you test what Dropbox and Google Drive do? (If not, can you do that? :)

**Comment by tobiasKaminsky** [comment]
I am unsure if this is a good idea as I want to create multiple folders side by side. Then I would have to go always back to parent.
This occurs nearly as often as I want to descend into the new created folders.

**Comment by strugee** [comment]
To be clear, I'm not talking about any time the user creates a folder. _Just_ in the upload pane.

> @strugee did you test what Dropbox and Google Drive do? (If not, can you do that? :)

Will do.

**Comment by jancborchardt** [comment]
Ah, good distinction. @tobiasKaminsky do you still think it’s a bad idea in the upload dialog?

**Comment by tobiasKaminsky** [comment]
I always thought that we are talking about the upload pane. ;)
But there are two: upload from within the app and from another (e.g. gallery).
Uploader.java vs FilesUpload.java
We are talking about the later case?

But as I said, in my case both cases happen 50:50. So either way it is fine for me.
Beside that, if you have many folders and create a folder with e.g. z you have to scroll very long to get into the folder, whereas it is much more easier to get one folder back.

So...As I have thought about it, it is a good idea ;)

**Comment by jancborchardt** [comment]
Ok, great – then let’s do this. :)

**Comment by tobiasKaminsky** [comment]
PR #1045

**Comment by jesmrec** [comment]
Native upload pane is currently used. Closing.
