### ISSUE TITLE
Upload files: Select all files option

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/android#1015]
When uploading files it's tedious to have to select every single file - especially if you have 2-300 files.
It would help if there was a "select all" files option.

PR: #1342

**Comment by LukeOwncloud** [comment]
Duplicate of https://github.com/owncloud/android/issues/1005?

**Comment by pascalBokBok** [comment]
I had been messy and asked for two things in one issue. Now it is not about uploading directories since it is covered in #1005, but only about being able to select all files in a folder.
That is nice e.g. when wanting to upload your photos from DCIM into a folder in owncloud.

**Comment by masensio** [comment]
Hi @pascalBokBok,

Thanks for your ideas. 
I think this is an option into the multiselection of files. https://github.com/owncloud/android/issues/899
Maybe, we'll implement as a part of this feature.

I don't know when we will introduce this feature in the project, but I hope this option will be in our app in a near feature.

**Comment by tobiasKaminsky** [comment]
#1342 is the PR for this.

**Comment by tobiasKaminsky** [comment]
@LukeOwncloud this is no duplicate as the linked issue (which leads to #645) is about uploading one folder recursively and this one is about only selecting all files from one folder.

**Comment by davigonz** [comment]
> I will start work on this.

Great! Thanks

**Comment by sd1998** [comment]
@davigonz I the select inverse option also required?

**Comment by davigonz** [comment]
> Is the select inverse option also required?

It would be great to have it, yes, similar to we already have in the file list.

**Comment by jesmrec** [comment]
Done. Will be available in 2.10
