### ISSUE TITLE
problem connecting to the server.

### ISSUE THREAD

**Issue by dadorso90** [owncloud/android#1016]
we play in four people in my server. it's everything fine a part from when one of them try to log in and i see this message in the console
[14:00:07] [Server thread/INFO]: com.mojang.authlib.GameProfile@1d41db4[id=<null>,name=vnoi,properties={},legacy=false] (/93.146.149.240:51255) lost connection:Disconnected

**Comment by masensio** [comment]
Hi @dadorso90,

we need more information about your problem. Could you please give us more details using the template https://github.com/owncloud/android/blob/master/issue_template.md?

Thanks.

**Comment by davivel** [comment]
@dadorso90 , what do you exactly mean with "we play in" and "in the console" ?

**Comment by tobiasKaminsky** [comment]
http://www.minecraftforum.net/forums/support/server-support/2303639-com-mojang-authlib-gameprofile-1f917180-id-null

This seems to have nothing to do with our owncloud app.
So therefore closing it until @dadorso90 provides more infos.

**Comment by davivel** [comment]
Somebody missed the repository... 

Thanks, @tobiasKaminsky
