### ISSUE TITLE
Android connecting via http although "forced https" is set in setting

### ISSUE THREAD

**Issue by schnuddel** [owncloud/android#1018]
I have ownCloud 8.1 running on debian wheezy with self-signed SSL certificate.
Connecting from PC or mobile (Android 5.0.1) via https is working without issues.

I have now installed ownCloud on my tablet (Android 5.1.1) and get an unknown error "Ein unbekannter Fehler ist aufgetreten!" when entering the login credentials  (https://my-server/owncloud).
I have then tried using http (http://my-server/owncloud) on the tablet and the connection can be established.

In the admin settings I have set to "force https", but with tcpdump I still can see traffic going over port 80.

### Expected behaviour
Login credentials using https accepted and able to login

### Actual behaviour
https not accepted and only http accepted

### Steps to reproduce
1. Open ownCloud app. 
2. Enter server address https://my-server/owncloud
3. get error "unknown error"
4. change server address to http://my-server/owncloud
5. successfull login

### Environment data
Android version: 5.1.1

Device model: Nexus 10

Stock or customized system: Stock

ownCloud app version: v1.7.1

ownCloud server version: 8.1

#### Web server error log
none
Insert your webserver log here
none

#### ownCloud log (data/owncloud.log)
none
Insert your ownCloud log here
none

**Comment by purigarcia** [comment]
Thanks for reporting.
We are able to connect via https in several servers.
Could you send your server URL to apps@owncloud.com? So we can check what it is going on

**Comment by davivel** [comment]
@schnuddel , please include in the subject of the e-mail something like "Android issue #1018" ; we don't need credentials to access the server, only the URL. Thanks

**Comment by rperezb** [comment]
@schnuddel thanks for the server url info, from our end we have not been able to reproduce your error. We are pop up to accept the certificate, tested in a couple of devices.

**Comment by davivel** [comment]
@schnuddel , I can confirm that is working fine in 5.1.1. 

Did you update the certificate in the server side?

**Comment by davivel** [comment]
Do you suffer the same error with "force https" disabled?

**Comment by tobiasKaminsky** [comment]
Closing due to no response.
If it still occurs, please reopen and provide more feedback.
