### ISSUE TITLE
Media type icons used in the app are not the same as the ones used in the Web GUI

### ISSUE THREAD

**Issue by oparoz** [owncloud/android#1019]
I've just noticed that the app uses the old image media type icon, the black one, before getting a thumbnail.

I think it would be good if the app was to use the new one and stay in sync with what's happening in core (just track the icon folder).

**Comment by masensio** [comment]
Hi @oparoz,

Yes, we need to update some of our icons.

Thanks for your comments.

**Comment by davivel** [comment]
The image icon is updated in the incoming release, 1.7.2.

**Comment by oparoz** [comment]
:+1:

**Comment by rperezb** [comment]
Fixed via: https://github.com/owncloud/android/commit/36128298d477dadbc1dc88a3214d425596cd2a76

**Comment by oparoz** [comment]
Good job, thanks! :)
