### ISSUE TITLE
Media type icons are blurry on high DPI devices

### ISSUE THREAD

**Issue by oparoz** [owncloud/android#1020]
### Steps to reproduce

1. Use an empty enabledPreviewProviders array in your config
2. Upload a few files
3. Fire up the app on a high DPI device.

### Expected results

Icons should look good (crisp)

### Actual results

Icons are blurry

**Comment by masensio** [comment]
Hi @oparoz,

thanks for your feedback.
We need to review the size of the icons in the app.

Which device are you using? It is for checking in the same way as you, if it is possible.

Thanks in advance.

**Comment by oparoz** [comment]
I doubt you have the same device, it's a BlackBerry Passport, but any device from that list with a ratio above 2 can be used: http://devicepixelratio.com/

**Comment by masensio** [comment]
Ok, thanks for the info.

**Comment by davivel** [comment]
This will be fixed with the incoming release, 1.7.2

**Comment by oparoz** [comment]
Great! Will the assets also be updated so the the app's UI doesn't look blurry as well?

**Comment by davivel** [comment]
Mmmm, sorry, what assets exactly? 

Not sure we have time for reviewing all of them. Besides, we want to introduce Material Design ASAP, so maybe not all of them stay there after...

**Comment by oparoz** [comment]
The icons at the top of the app per example, including the `<`.

**Comment by davivel** [comment]
We removed ActionBarSherlock from the app. I guess the < would be from it before. Now it's from the Google Support Library, so now should be fine.

The rest of the icons in the top bar were not changed. Probably will have to review them with the update to Material Design, that implies a change in the look&feel of the top bar as a whole.

**Comment by AndyScherzinger** [comment]
The blurry effect on the action bar icons should be gone with #1076 since I added the according icons for the higher resolutions in hdpi, xhdpi, xxhdpi and some on xxxhdpi so this should fix the action bar :)

**Comment by AndyScherzinger** [comment]
This issue should be resolved with the upcoming release 1.8.0 since we added the icons for the different resolutions in #1076 for the action bar and in #1118 for the file icons. :)

So this issue can be assigned to 1.8-current imho, since that's the release fixing the issue.

**Comment by davivel** [comment]
True. No more blurriness.

Thanks, @AndyScherzinger
