### ISSUE TITLE
[Grid] As an OC Android user I want the grid mode to be shown only when the 100% of the files are images so that by default it will be used the file list view

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1021]
AC:
  - By default it is  shown the list view. Unless 100% of the files in the folder are images (not counting subfolders of course) – then the gallery (grid) view is used.

Note:
- This is the first step, then it will come other user stories where a button to switch between views will be included
- Related to: https://github.com/owncloud/android/issues/894

**Comment by davivel** [comment]
Ready to test in #1027

**Comment by davivel** [comment]
Ready to test in #1027

**Comment by masensio** [comment]
This feature is in our develop branch.
It would be released in the next release (1.7.2)

So, I'll close the issue.
