### ISSUE TITLE
[ANDROID][New version] As an Android user I want a new version 1.7.2 to be released so that the sync error is fixed and other bug fixing

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1022]
- This version will include
  + Lateral menu
  + https://github.com/owncloud/android/issues/900 OC-Total-Length header
  + Support to forbidden characters on the server side
  
- Bug fixing
  + https://github.com/owncloud/android/issues/940 1.7.1 sync issue  
  + https://github.com/owncloud/android/issues/947 crash when accessing to a folder with several images related to thumbnails
  + Fix when sending a file from the email to ownCloud

- A regression test will be ran so that any integration bug may be found

**Comment by davivel** [comment]
Extra ball: #1020

**Comment by jab416171** [comment]
Just curious, when will 1.7.2 be released? What's holding it up?

**Comment by tobiasKaminsky** [comment]
@davivel #1037 needs to get in this release! This is an important bugfix for the uploader dialog

**Comment by rperezb** [comment]
1.7.2 is already released.
