### ISSUE TITLE
Support the BPG image format

### ISSUE THREAD

**Issue by oparoz** [owncloud/android#1026]
BPG (Better Portable Graphics) is a new image format. Its purpose is to replace the JPEG image format when quality or file size is an issue. Its main advantages are:
- High compression ratio. Files are much smaller than JPEG for similar quality.
- Supported by most Web browsers with a small Javascript decoder (gzipped size: 56 KB).
- Based on a subset of the HEVC open video compression standard.
- Supports the same chroma formats as JPEG (grayscale, YCbCr 4:2:0, 4:2:2, 4:4:4) to reduce the losses during the conversion. An alpha channel is supported. The RGB, YCgCo and CMYK color spaces are also supported.
- Native support of 8 to 14 bits per channel for a higher dynamic range.
- Lossless compression is supported.
- Various metadata (such as EXIF, ICC profile, XMP) can be included.
- Animation support.

Source: http://bellard.org/bpg/

Some people have added it to Android apps already.
https://github.com/alexandruc/android-bpg

**Comment by davivel** [comment]
Nice. Estimated time of arrival:

**Comment by tobiasKaminsky** [comment]
As far as I have read this could affect some patents and therefore I think we should wait and use the dev power for something else right now.
(https://en.wikipedia.org/wiki/Better_Portable_Graphics)

**Comment by oparoz** [comment]
I agree, it would only cater for the needs of very few people at the moment. It's more like an experiment or something to think about if you ever implement SVG support in the app since the loading mechanism would probably be the same. The patents would only be valid in some countries, so not a big deal.

Let's see if more people voice their interest.

**Comment by LukasReschke** [comment]
> The patents would only be valid in some countries, so not a big deal.

You are kidding, right? :speak_no_evil:

**Comment by oparoz** [comment]
Software patents are not recognized everywhere and are usually enforced when you include them in software you make profit with, such as a commercial encoder.

**Comment by LukasReschke** [comment]
>  Software patents are not recognized everywhere 

Such as the US where ownCloud Inc. is located? :speak_no_evil: 

> when you include them in software you make profit with

Such as ownCloud? :speak_no_evil:  ;-)

**Comment by oparoz** [comment]
It could be a problem for US businesses using ownCloud, **if they don't acquire a license from MPEGLA**, but other users should be fine.

And I don't think ownCloud inc. would get in trouble for shipping the library in their OSS product, just like Linux distros aren't for shipping ffmpeg or ImageMagick. You just need a disclaimer.

MPEGLA will probably try to approach browser vendors to license their own decoder and software vendors so that officially licensed encoders are made available to both the general public and businesses.

**Comment by oparoz** [comment]
From the author:
> Bellard notes, however, that because BPG's bit format is a conforming implementation of HEVC's Still Picture profile, it could be encoded or decoded by a hardware module. That might provide a way out for hardware devices that include a licensed HEVC hardware codec module—a category that would, presumably, include a lot of commercial mobile devices.

Which means that there would be no problem on recently released mobiles which already come with the proper licenses.

**Comment by davivel** [comment]
OK, but now this sounds quite more complicated from the legal POV. 

So, for the moment...

**Comment by michaelstingl** [comment]
Seems BPG failed in getting the traction it needs and HEIF won the race to replace JPEG. (support in Android P, iOS 11, Win 10 1803+…)
