### ISSUE TITLE
InstantUpload not always working

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/android#1029]
On my new HUAWEI P8 LITE I noticed the problem that photos are not always automatically uploaded.

* HUAWEI P8 LITE (Modellnummer ALE-L21)
* Android 5.0
* Owncload Android Client 1.7.1

**Comment by masensio** [comment]
Hi @Wikinaut,

we have some issues related with the instant uploads, see here: https://github.com/owncloud/android/issues?q=is%3Aopen+label%3Abug+label%3Ainstant_uploads

For instant_uploads the app process the Android event "android.hardware.action.NEW_PICTURE". But maybe your device doesn't launch this event when taking a photo.
Sometimes the device manufacturer makes some changes in the device behaviour when taking a photo and the event is modified.
If it is the reason of the problem we need to change the instant uploads implementation. 

Thanks for your feedback.

**Comment by Wikinaut** [comment]
@masensio Thanks for your pointers, I studied the present reports before filing my issue here.

Because the P8 LITE is new (product selling started in May 2015), I wanted to tell you this as quickyl as I found the issue. I will also try to deinstall and reinstall OC and report back here later.

**Comment by Wikinaut** [comment]
@masensio just a point:

Currently, I use the smartphone without any SIM card. The setting for InstantUpload-via-WiFi-only was _not_ set. Perhaps the OC client has problem when detecting the correct channel (WiFi respectively UMTS/mobile), when UMTS is not available at all.

I now activated "WiFi only" for photos and videos, and will reported later here, if this changes anything. Currently, two new photos were uploaded as expected.

**Comment by davivel** [comment]
Thanks, @Wikinaut . We'll keep track of your reports. Probably it's just about not having network when the picture is taken, as you suggest. Something that would be repaired with the contribution in #919, currently in review.

**Comment by mgalushka** [comment]
I have noticed on google nexus 4, that sometimes when I make picture without wifi, this photo is actually never uploaded.

I have instant upload option on wifi only.

When wifi is available - this feature woks perfectly, also works fine if there is not long period passed between taking photo and getting back to wifi - this also works.

Maybe persistence mechanism for storing this event is not ideal.

**Comment by davivel** [comment]
@Wikinaut , @mgalushka , is this still an issue for you? There were some improvements in instant uploads from version 2.0.0 to the just released 2.1.1. 

Please, review the instant uploads settings in the app, in version 2.1.1 there is a new option "Camera folder" that you might need to update depending on what's your favorite camera app.

**Comment by Wikinaut** [comment]
I moved to Nextcloud.

**Comment by davivel** [comment]
Sorry to hear that :\ . But thanks for the feedback, hope everything goes fine for you :) .

**Comment by davivel** [comment]
@mgalushka , let me invite you to join #1795 in favor of this issue. Thanks.
