### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by jab416171** [owncloud/android#1030]
I know there's a couple of open issues about specific aspects of material design (like the FAB), but this is more geared towards a bigger overhaul. ownCloud's two biggest competitors, Dropbox and Google Drive, are both considered to be "Material Design" apps. Do we want ownCloud to stick with its current UI, which is closest to Dropbox, or should it move to a card layout, like Google Drive? Drive does let you switch between a list view and a grid view, so it's kind of the best of both worlds. Should ownCloud be cards by default, with the option to switch to a list view? I was thinking about doing a more formal poll, but I kind of want to get a feel for the community's opinion on the look and feel/UX of the future of the ownCloud app.

As a side note, I think that the app and the web interface should look similar/be cohesive, so there should probably be a parallel effort of moving the web interface to material as well.

**Comment by jab416171** [comment]
Check out the screenshots on the play store:
[Dropbox](https://play.google.com/store/apps/details?id=com.dropbox.android)
[Google Drive](https://play.google.com/store/apps/details?id=com.google.android.apps.docs)

**Comment by masensio** [comment]
Hi @jab416171,

thanks for your thoughts. 

We also think that it is important to adapt the Android OwnCloud to Material Design. Ad hoc we have opened three issues:
https://github.com/owncloud/android/issues/692
https://github.com/owncloud/android/issues/983
https://github.com/owncloud/android/issues/984

And this is in the top our priorities. :smiley: 
So we expect to get the app ready for material design soon.

**Comment by davivel** [comment]
cc @tobiasKaminsky due to his effort in the grid view.

**Comment by jab416171** [comment]
@masensio What can I do to help with this effort? I don't want to work on something that someone else is already working on. Is there a material design branch that I should be watching/contributing to for this?

**Comment by davivel** [comment]
We will create a new branch to start the work on it next week. We (@masensio and me) would like to make the first step, since it's necessary update the version of the Android Support Library (including the source code, necessary for working in Eclipse) and the API level of the build target, what may bring some unexpected problems.

After that we'll be very happy of getting contributions of anybody in updating the UI.

But we need to finish the tests and release version 1.7.2 first.

**Comment by AndyScherzinger** [comment]
Hi everybody, please have a look at #1076 for a first draft on a material design implementation #692 should be covered there already :)

**Comment by AndyScherzinger** [comment]
@rperezb this issue can imho be closed since we made the move to material design in general even though there might always be issues related to (material) design in the future and the possibility to switch list/grid view has also been implemented.

**Comment by rperezb** [comment]
@AndyScherzinger yes, you are right. 

The app has changed noticeable since this issue was open and will keep the same path due to the FAB one, expected wihin the next version.

@jab416171 if there is any changed that you expect, please, open a concrete issue

thanks!

**Comment by jab416171** [comment]
I really like where the ownCloud app is going, keep up the good work!
