### ISSUE TITLE
Cancel upload

### ISSUE THREAD

**Issue by felicitus** [owncloud/android#1031]
Sometimes, ownCloud 1.7.1 hangs when doing an upload. I have no way of cancel the upload. I need to stop the app via the App manager in order to make it working again.

In my case, those hanging uploads sit there forever (I had an upload hanging for 8 hours).

It would be good if there was an option to cancel an upload (i.e. tap on the upload notification then see all pending uploads, and a way to cancel the upload).

**Comment by davivel** [comment]
Clicking the notification should take to a view with information on the file and the upload progress. A button to cancel the upload is available there too.

Aren't you able to access that view? What is your device model and Android version?

Thanks.

**Comment by felicitus** [comment]
If I tap the notification, I'm being taken to the app without any file or upload progress. So no, I'm not able to access that view.

My device model is a Samsung Galaxy S3 GT-I9300, Android Version 5.1.1. ownCloud 1.7.1 (latest from Google Play).

**Comment by davivel** [comment]
Yeah, you're right, there is a bug there. In my test the click only fails when the progress is in 0% (file is being copied) , and works again when the upload really starts (progress > 0%). Can you cofirm this is the same for you? Or the files never goes after the 0%?

What is the size of your file(s)?

**Comment by felicitus** [comment]
When I encountered the issue, file progress was always > 0%. I guess the uploads fail when WiFi connectivity goes away. My files are mostly images, several MB.

**Comment by davivel** [comment]
OK, thanks. We'll take a look.

**Comment by stefan-niedermann** [comment]
references #1049

**Comment by AndyScherzinger** [comment]
@davivel is there a way to cancel an upload (in the code already, not necessarily accessible on the UI) to be able to implement the cancel an upload as descirbed by @stefan-niedermann in his issue?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger FileDownloader: Line277 
/**
         * Cancels a pending or current download of a remote file.
         *
         * @param account ownCloud account where the remote file is stored.
         * @param file    A file in the queue of pending downloads
         */
        public void cancel(Account account, OCFile file)

**Comment by davivel** [comment]
Hi, @felicitus.  The app has changed a bit since you opened this issue. In current version 2.3.0, if you tap the notification of an upload, the app will open showing the 'Uploads' view, with a list of all the uploads in progress. You can cancel any of these with the button shown on its right.

Even if the tap on the notification does not work, you still can access the 'Uploads' view opening the app and tapping on the menu icon on the top left to display the navigation bar, then tap un 'Uploads'.

That should help with your problem.

Sorry for responding so late :S
