### ISSUE TITLE
SVG files can not be viewed

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1033]
I’m greeted with this:
![screenshot_2015-06-26-16-59-45](https://cloud.githubusercontent.com/assets/925062/8380272/20edbc12-1c25-11e5-9418-242e5469eda5.png)

SVG is pretty standard nowadays so we should support it @davivel @tobiasKaminsky 

Also – that screen could say something useful like: »File type can not be viewed«

**Comment by tobiasKaminsky** [comment]
According to my comment https://github.com/owncloud/android/issues/585#issuecomment-60473635 this is only possible with third party apps.

**Comment by tobiasKaminsky** [comment]
See https://code.google.com/p/svg-android/
The main problem will be the performance issue on weak devices...

**Comment by tobiasKaminsky** [comment]
Or https://code.google.com/p/androidsvg/ which seems to be more recent. The latest stable is from 02-2014

**Comment by sd1998** [comment]
@davigonz I would like to work on this.

**Comment by sd1998** [comment]
@davigonz I would like to work on this.
