### ISSUE TITLE
Impossible to view black images with background transparency

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1034]
When viewing a PNG with a black graphic and background transparency, you will only see black.

Instead of that, the background should automatically be a checkerboard pattern so you can see whatever is on top. See how the Wikipedia viewer does it: https://en.wikipedia.org/wiki/Wikipedia#/media/File:Wikipedia-logo-v2.svg

Same for iOS as well of course, cc @rperezb @davivel @javiergonzper

**Comment by davivel** [comment]
Seen. Maybe we could add some PNG files with alpha channel to the set of files to test to make this more visible. Do you have that black image at hand, @jancborchardt ?

cc @purigarcia

**Comment by jancborchardt** [comment]
![foss-logo-512](https://cloud.githubusercontent.com/assets/925062/8406572/f4bfbad8-1e5d-11e5-8630-1a818041646c.png)
[SVG source for fixing & testing SVG as well …](https://cloud.jancborchardt.net/public.php?service=files&t=7ddf8530c3e97889e5a44c7290bbac24) #1033

**Comment by tobiasKaminsky** [comment]
I have tried it.
The current app displays the alpha/transparent part really fine.
We just need a background pattern that would be shown on every PNG file.

**Comment by jancborchardt** [comment]
We can use the one Wikipedia is using:

![](https://upload.wikimedia.org/wikipedia/commons/5/5d/Checker-16x16.png) https://upload.wikimedia.org/wikipedia/commons/5/5d/Checker-16x16.png

**Comment by tobiasKaminsky** [comment]
![svgtransparentbackground](https://cloud.githubusercontent.com/assets/5836855/8623059/7472f91e-272f-11e5-8c68-ead4f42f28eb.jpg)

@jancborchardt like this? :) :)

**Comment by tobiasKaminsky** [comment]
Can you confirm that the preview thumbnail in the list view is looking ugly?
At least for me this has a complete black background.

**Comment by jancborchardt** [comment]
@tobiasKaminsky yup on both! :)

**Comment by tobiasKaminsky** [comment]
This is both in #1056.
Crossing fingers that it will be merged soon ;)

**Comment by tobiasKaminsky** [comment]
Closing as related PR is merged.

**Comment by jancborchardt** [comment]
Awesome, thank you @tobiasKaminsky! :)
