### ISSUE TITLE
Photo upload issue and other ??

### ISSUE THREAD

**Issue by mediumbuddha** [owncloud/android#1040]
Hello all,

I have posted my issue first in the forum, as I was not sure if I am experiencing a bug or if I am too bad to use the app correctly. It seems to be some buggy behavior.

I am using the current Sync App on Samsung S6 (Android 5.0.2) and on server side it is the newest/current ownCloud Server running on Linux Ubuntu.

I have two major issues uploading photos to folders I have created.

* Via the ownCloud App, browsing to the folder and then using the upload function.
This is kind of pain in the ***. When browsing the folders, when I choose the Camera, first of all, the photo list is always chronological, I have to go pass thousands of photos before having the ability to select the pictures I want. Also before clicking on "Upload", I need to way for all thumbnails to be displayed, otherwise the app will break/stop. So uploading one picture can be a matter of 5 minutes just wainting that thumbnails are built up.. 

* Via the image library and adding images to albums
I am not sure if this is an ownCloud feature. But in the image library I can select "Add to album" after selecting one or more photos. I discovered this quite late ;-) As there is no recognition symbol to ownCloud, I never paid attention to it. Also what is "bizar", the album list matches only 50% of the folder I have created on ownCloud, the other half is missing.. Anyways, I have selected 4 pictures and associated them to one of the albums. Now the photos are gone from the image library but are not in the ownCloud folders. They seem to be gone, deleted..

Additional info: While I was looking for the disappered photos and browsing the storage space, I noticed that the owncloud folder has a /tmp folder and a folde named like my account login. Some folders I have created where in the account folder, some others in the /tmp folder. I couldn't find out the logic behind this segmentation...

I would be glad to know if the client was designed to be like that or if it is seen as bug and will be enhanced in some next release?

Best regards,
MW

**Comment by masensio** [comment]
Hi @mediumbuddha, 

About your issues:
- Via the ownCloud App, browsing to the folder and then using the upload function.
When you have a lot of images in the same folder, the loading of thumbnails needs a lot of resources to work. The next release has some improvements to avoid the crash when you have this situation.
On the other hand, you are right when you say that it is a pain in the *** to have to scroll a lot to search the photos. In this way, some improvements related with search and sort in the uploads filelist could be implemented. I'll open a new issue for this purpose. ( https://github.com/owncloud/android/issues/1041)

- Via the image library and adding images to albums
Do you use the Photos App of your device? In this case, I  don't know how this app works when share an image  with other app.
I've selected some images in this app and shared with OwnCloud and they are uploaded in OwnCloud without any problem.

Additional info: 
Owncloud needs some storage for some operations. In this way, you have a folder per account for storage the download files and the tmp folder to save temporal files.

I hope these answers solve your questions. 
I'll close this issue, feel free to reopen it if you need more information about this

Thanks for using ownCloud.
