### ISSUE TITLE
Sort in uploader

### ISSUE THREAD

**Issue by masensio** [owncloud/android#1041]
Add the feature to sort in the uploader, in order to avoid a long scroll  when selecting the most recent files for uploading.

Related with https://github.com/owncloud/android/issues/1040

**Comment by tobiasKaminsky** [comment]
You mean when adding files from within the app and selecting "files"?
(UploadFilesActivity class)

**Comment by masensio** [comment]
Yes. Maybe the title is some confused.
I mean to add sort feature when you are selecting files to upload, inside the app.

**Comment by purigarcia** [comment]
Hi @tobiasKaminsky, are you implementing this?

**Comment by tobiasKaminsky** [comment]
I will do it tomorrow.

**Comment by tobiasKaminsky** [comment]
Done.
I will upload it tomorrow.

**Comment by sd1998** [comment]
@davigonz I would like to work on this.

**Comment by michaelstingl** [comment]
@sd1998 sure, you're the sorting-expert now 👍

**Comment by davigonz** [comment]
Already implemented via https://github.com/owncloud/android/pull/2305
