### ISSUE TITLE
Move multiple files at once

### ISSUE THREAD

**Issue by sedrubal** [owncloud/android#1042]
Something like long click a file to select it and click on other files to select them (like in androids photos app) should be possible. And please remember the last folder one moved in a file.

**Comment by masensio** [comment]
Hi @sedrubal,

this is an special case of https://github.com/owncloud/android/issues/899 ( this issue is about selecting multiple files )

Thanks for using OwnCloud

**Comment by sedrubal** [comment]
Oh thanks, I didn't find this.

**Comment by tobiasKaminsky** [comment]
This will be covered by #899, therefore I close it.
As for the other wish, I have created #1167.
