### ISSUE TITLE
Uploader: Gives misleading »no content here« when there’s no offline files in a folder

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1043]
1. Use the share action from another app
2. Go into a folder with files in it, but none of them downloaded
3. You see »Nothing in here«

Instead, the files should correctly be shown. Otherwise people might think ownCloud deleted their stuff. ;)

@davivel @rperezb

**Comment by tobiasKaminsky** [comment]
There is another issue regarding this: #674, but also a discussion about security risk in #667.
Despite that it is done by me in #821 ;)

**Comment by jancborchardt** [comment]
Oops, dupe of https://github.com/owncloud/android/issues/674 then – sorry. ;)

**Comment by jancborchardt** [comment]
Also, @davivel @rperezb please review @tobiasKaminsky’s PR since this issue has come up a year ago and again now: https://github.com/owncloud/android/pull/821
