### ISSUE TITLE
Upload only on wifi with vpn connection

### ISSUE THREAD

**Issue by Chucrute** [owncloud/android#1047]
Hello all,
I use instant upload over wifi. It's working great since you expose your server to the internet.
I would like to have more security using vpn. But until I activate the vpn tunnel the sync is already starting and gives error messages about missing IP.
I would like to have a delay time after wifi connect for the sync. If possible adjustable. Let's say from 0 to 30 seconds.
This would help a lot.

Greetings
Chucrute

**Comment by MadDogTeam** [comment]
Hi, 

it would be nice, because of short connection of Wifi too ...

I can connect WiFi before my house when I arrive, but not in underground garage, so Instant Upload start before I park my car and then is disconnected and file corrupted. 

Please add some delay time option.

Thanx

Adam

**Comment by tobiasKaminsky** [comment]
Please see #643
