### ISSUE TITLE
Travis: This job is running on our legacy infrastructure. 

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1057]
On build https://travis-ci.org/owncloud/android/builds/70495123 I get:
 This job is running on our legacy infrastructure. Please read our docs on how to upgrade:
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by purigarcia** [comment]
@tobiasKaminsky , @AndyScherzinger , @LukeOwncloud and whoever feels like, contributions are wellcome here :)

**Comment by tobiasKaminsky** [comment]
So this seems to all end up to "sudo: false" in travis.
I will create a PR

**Comment by tobiasKaminsky** [comment]
Please see #1105

**Comment by davivel** [comment]
Seen & merged. Thanks!
