### ISSUE TITLE
logout when device is locked, or user choose log out

### ISSUE THREAD

**Issue by joszon** [owncloud/android#1060]
First to say, I like Owncloud.
But I am disappointed that there is no option to logout using the android app.
For security reasons, there should be a option to logout when the user choose so.
Also, there should be a option to automatically logout, when the device is entering locked mode. 

When user is logged out, remember server settings, and user name if the user choose this as a option.

**Comment by tobiasKaminsky** [comment]
For security purpose there is the pincode.
I think this is better than logging off and on every time. (My password is 16 characters with special chars and digits).

**Comment by joszon** [comment]
The pincode is a plus for security, but if I choose for a long and an difficult to guess password, I must given the option to force myself to enter this, if I think that a pin code is not enough for security.

**Comment by tobiasKaminsky** [comment]
So the best would be to enhance the pincode to also allow passphrases?
And have an option to use the password of the user account for it?

**Comment by joszon** [comment]
Yes, that's my opinion.

**Comment by tobiasKaminsky** [comment]
So I close this in favour of #1064
