### ISSUE TITLE
Publish new version to F-Droid

### ISSUE THREAD

**Issue by armaccloud** [owncloud/android#1061]
Hi.
Will the new version of the Owncloud Client be published to F-Droid as well? Seems it's only available through Google Play at this moment.

**Comment by strugee** [comment]
F-Droid apps are (in general) maintained by F-Droid community members, not the original app authors. (AFAIK this is the case for ownCloud.)

See also #1063

**Comment by davivel** [comment]
Exactly waht @strugee said.

Thanks.

**Comment by davivel** [comment]
FWIW: from other issue I remember they had a problem with the names of the release tags, but should be clarified now. I guess they will release the version sooner than later.

**Comment by armaccloud** [comment]
It is published now, thanks for the answers guys!

**Comment by guruz** [comment]
FYI @carlaschroder

**Comment by carlaschroder** [comment]
It's still 1.7.1: https://f-droid.org/repository/browse/?fdfilter=owncloud&fdid=com.owncloud.android

**Comment by carlaschroder** [comment]
Sorry, 1.7.2.

**Comment by carlaschroder** [comment]
Never mind, the desktop sync client is 1.8, not the Android app. OK then! We are good.

**Comment by LukeOwncloud** [comment]
2.0.0 is still not available at f-droid. Even though it was already detected. It seems as if auto update needs to enabled. Who is responsible for f-droid? 

Cc @tobiasKaminsky

**Comment by davivel** [comment]
The responsible for F-Droid are in F-Droid :) . This is an issue for https://f-droid.org/issues/ .

**Comment by LukeOwncloud** [comment]
2.0.0 is still not available at f-droid. Even though it was already detected. It seems as if auto update needs to enabled. Who is responsible for f-droid? 

Cc @to

**Comment by LukeOwncloud** [comment]
Sorry.

**Comment by davivel** [comment]
No problem :)

**Comment by LukeOwncloud** [comment]
I think, the responsible might be also here. @mvdan? @RealRancor? Version 2.0.0, please! :)

**Comment by mvdan** [comment]
Patches to update the app are welcome. We are not enabling automatic updates because the tag names are erratic (e.g. `1.9.0` vs `1.9`).

**Comment by RealRancor** [comment]
@LukeOwncloud Sorry, i'm not active in building / maintaining stuff in f-droid anymore
