### ISSUE TITLE
Tagging of stable releases

### ISSUE THREAD

**Issue by schiesbn** [owncloud/android#1063]
I had a look at how we tag our stable releases, it seems like there is no clear scheme behind it. Most of the time it is ````oc-android-<version>```` which I think is a good way, but sometimes we add a arbitrary string at the end like ````oc-android-1.7.1-oem```` or ````oc-android-1.7.1_signed````. This prevent alternative app stores to build the packages automatically as you can see here https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.owncloud.android.txt#L185

I think it would be great if you could decide on one default scheme and stick to it.

**Comment by cmonteroluque** [comment]
@schiesbn good point. @masensio @davivel thoughts?

**Comment by schiesbn** [comment]
BTW, I'm happy to coordinate with the f-droid developers to get the automated update running again. All we need to here is to agree on a common schema we stick to.

**Comment by danimo** [comment]
@schiesbn (I can't speak for the Android team, but I can perhaps clarify some of the issues) the `_signed` was when we introduced signed tags and didn't want to redo the original ones (also applies to the desktop client). The `_oem` tag usually means it contains fixes only relevant for OEMs (e.g. it's not a problem if it's not picked up automatically).

I do, however, not see why there is no `oc-android-1.7.1` (without the `_signed`) postfix. Probably an oversight.

**Comment by schiesbn** [comment]
Thanks @danimo for explaining the ````_signed```` and ````_oem```` tags. So can we agree that this are additional tags and every release will also be tagged as ````oc-android-<version>```` ?

**Comment by rperezb** [comment]
@schiesbn yes, @danimo has explained it, 
We used to use the format ````oc-android-<version>```` 
In the version, 1.7.1, we added  ````oc-android-1.7.1-oem```` this tag was only relevant for OEMS
Plus the signed, suffix due to the fact that we introduced signed tags.
Yes, @schiesbn we agree on following,````oc-android-<version>```` , indeed, the latest version followed this pattern: oc-android-1.7.2 https://github.com/owncloud/android/tree/oc-android-1.7.2

**Comment by schiesbn** [comment]
@rperezb Thanks for clarification

**Comment by schiesbn** [comment]
I just informed the fdroid developer that we will stick to ````oc-android-X.Y.Z```` in the future again. Thanks all for helping to clarify it.

https://gitlab.com/fdroid/fdroiddata/issues/270

**Comment by davivel** [comment]
In that case I think this may be closed.

Thanks to everybody.
