### ISSUE TITLE
No error messages when there are problems in the network connection

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/android#1071]
Currently owncloud for android does a TERRIBLE job showing what is happening when there are problems with the network connection.
I will show two examples:
Right now i "appear" to be connected to my 3g network, but somehow cant connect to anything.
If i open owncloud app, and try to refresh some file ( which i have sure it was modified on the server) owncloud will popup a progressbar with "Wait a moment"  and a few seconds later the progress will disappear and nothing is done, the file is not downloaded, there are no error messages , just nothing.
Even worse, if i try to enter any folder in this condition, i will get : "nothing uploaded here" which is clearly wrong !

**Comment by davivel** [comment]
Duplicates #688.
