### ISSUE TITLE
instant upload folder organization. 

### ISSUE THREAD

**Issue by Juvenciodas** [owncloud/android#1073]
It would be nice to have your uploaded pictures and videos, to be saved in to a folder with the date it was uploaded.

I now need to sort through everything in the instant upload folder to find what I'm after.

Getting it to read the date stamp of the picture and video and putting in to the date folder would be even better. But I will be happy with the uploaded date folder.

Thanks for a great app.

**Comment by davivel** [comment]
Thanks, @Juvenciodas . This is duplicating (mostly) the issue #520. Please, join that thread to discuss the details.
