### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by enoch85** [owncloud/android#1074]
#### Steps to reproduce
1. Take a photo with the Android client. 
2. See the output in owncloud.log
#### Expected behavior

No error
#### Actual behavior

```
Error   PHP Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58   2015-07-18T16:06:26+02:00
```
#### Configuration

**Browser:**
Chrome
**Operating system:**
Ubuntu Server 14.04
**Android Client**
1.7.2 
**Server**
8.1 (Also on 8.2.2 and 9.0)

Refs: #940 

Logs by @mhzawadi
https://owncloud.horwood.biz/index.php/s/tuYCjfUAET43izw - PW is apptest

**Comment by enoch85** [comment]
cc @davivel @tobiasKaminsky

**Comment by davivel** [comment]
@PVince81 , @DeepDiver1975 , could you give as a clue about what could generate that message in the server logs?

**Comment by PVince81** [comment]
It could be anything... In general it means that some PHP code is trying to set header values at a time where the body has already been started.

**Comment by dipenpatel235** [comment]
{"reqId":"OtkPaVZOvEx7bMCwYnUd","remoteAddr":"101.202.2.122","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-08-20T15:28:49+00:00"}
Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70

Same Error to me

**Comment by cdamken** [comment]
Same here
```
{"reqId":"ggBBmvW1TeuVgrizdPaC","remoteAddr":"93.202.89.149","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php#58","level":3,"time":"2015-09-17T11:25:19+00:00"}
{"reqId":"ONCmxp7Bvgzemn/AzXuR","remoteAddr":"93.202.89.149","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php#58","level":3,"time":"2015-09-17T11:26:04+00:00"}
{"reqId":"jNCImOs1e+Nwlf/h18OQ","remoteAddr":"93.202.89.149","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php#58","level":3,"time":"2015-09-17T11:26:37+00:00"}
{"reqId":"jJwXS5bLEyqtorDzrvhP","remoteAddr":"93.202.89.149","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/html/owncloud/3rdparty/sabre/http/lib/Sapi.php#58","level":3,"time":"2015-09-17T11:28:02+00:00"}
{"reqId":"JXjoobQmHTd0dBDU79ho","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/contacts/appinfo/app.php#35","level":3,"time":"2015-09-17T11:30:01+00:00"}
{"reqId":"0xkFFeiSTn8pILuRbQeq","remoteAddr":"93.202.89.149","app":"webdav","message":"Exception: {\"Message\":\"HTTP/1.1 400 expected filesize 1024000 got 749568\",\"Code\":0,\"Trace\":\"
n#0 /var/www/html/owncloud/lib/private/connector/sabre/file.php(100): OC\Connector\Sabre\File->createFileChunked(Resource id #35)\
n#1 /var/www/html/owncloud/lib/private/connector/sabre/directory.php(113): OC\Connector\Sabre\File->put(Resource id #35)\
n#2 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(1053): OC\Connector\Sabre\Directory->createFile('IMG_20150917_13...', Resource id #35)\
n#3 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(513): Sabre\DAV\Server->createFile('InstantUpload/I...', Resource id #35, NULL)\
n#4 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\
n#5 /var/www/html/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\
n#6 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)\
n#7 /var/www/html/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\
n#8 /var/www/html/owncloud/apps/files/appinfo/remote.php(83): Sabre\DAV\Server->exec()\
n#9 /var/www/html/owncloud/remote.php(132): require_once('/var/www/html/o...')\
n#10 {main}\",\"File\":\"/var/www/html/owncloud/lib/private/connector/sabre/file.php\",\"Line\":346}","level":4,"time":"2015-09-17T11:31:45+00:00"}
```

**Comment by AndyScherzinger** [comment]
Imho such a message occurs in PHP when one starts writing the output before sending the header and as such is a server side implementation bug.

**Comment by cdamken** [comment]
I think the problem happened when I try to upload the file:

![img_20150917_135911_960](https://cloud.githubusercontent.com/assets/7264495/9932718/61ddb3dc-5d46-11e5-907a-d024609f28bc.jpg)

**Comment by wolkenschieber** [comment]
Same here. Line number seems to vary.

```
{"reqId":"CAVS6zy9BNQRPZd5\/pMT","remoteAddr":"127.0.0.1","app":"PHP","message":
"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) 
at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"September 20, 2015 07:00:17"}

{"reqId":"CAVS6zy9BNQRPZd5\/pMT","remoteAddr":"127.0.0.1","app":"PHP","message":
"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) 
at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"September 20, 2015 07:00:17"}
```

**Comment by tobiasKaminsky** [comment]
@PVince81, @DeepDiver1975 Can this be related to upload as @cdamken thinks?
How can we try to track this down?

@all: server and app are working without problems except of this ominous error message?

**Comment by enoch85** [comment]
@tobiasKaminsky Yes, everything works except this error message.

**Comment by cdamken** [comment]
In my case it works too... they client just have to retry and works...

**Comment by MrEnderkiller** [comment]
I have the exact same problem.
**Browser:**
Chrome
**Operating system:**
Debian 8 (Jessie)
**Android Client:**
1.8.0 and latest beta
**Server:**
8.2

I have tried with both ownCloud mobile app version 1.8.0 and the latest beta. The error message in log is the same as the original issue : 
```
Error	PHP	Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58	2015-11-24T21:41:40+00:00
```
So, Instant Upload is unusable for me, as it always fails.

**Comment by AndyScherzinger** [comment]
Now the upload is also broken for me :(
I have the exact same problem.
**Android Client:**
latest beta
**Server:**
8.2.1

Android logcat:
11-25 14:16:29.235 10768-10768/com.owncloud.android.beta D/com.owncloud.android.files.InstantUploadBroadcastReceiver: Received: android.hardware.action.NEW_PICTURE
11-25 14:16:29.252 10768-10768/com.owncloud.android.beta W/com.owncloud.android.files.InstantUploadBroadcastReceiver: New photo received
11-25 14:16:29.272 10768-10768/com.owncloud.android.beta D/com.owncloud.android.files.InstantUploadBroadcastReceiver: /storage/emulated/0/DCIM/Camera/IMG_20151125_141625.jpg
11-25 14:16:29.287 10768-10768/com.owncloud.android.beta D/instant_upload: putFileForLater returns with: 8 for file: /storage/emulated/0/DCIM/Camera/IMG_20151125_141625.jpg
11-25 14:16:29.290 10768-10768/com.owncloud.android.beta D/com.owncloud.android.files.InstantUploadBroadcastReceiver: upload file and do nothing
11-25 14:16:29.294 10768-10768/com.owncloud.android.beta D/com.owncloud.android.files.InstantUploadBroadcastReceiver: OFFICIAL processed: android.hardware.action.NEW_PICTURE
11-25 14:16:29.302 10768-10768/com.owncloud.android.beta D/FileUploader: Starting command with id 14
11-25 14:16:29.309 10768-14822/com.owncloud.android.beta D/FileUploader: Account andy@removed.domain.net exists
11-25 14:16:29.333 10768-14822/com.owncloud.android.beta D/SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
11-25 14:16:29.337 10768-14822/com.owncloud.android.beta D/OwnCloudClient #5: Creating OwnCloudClient
11-25 14:16:29.342 10768-14822/com.owncloud.android.beta V/SimpleFactoryManager:     new client {andy@removed.domain.net, 112354287}
11-25 14:16:29.372 10768-14822/com.owncloud.android.beta D/OwnCloudClient #5: REQUEST HEAD /remote.php/webdav/Photos/
11-25 14:16:30.008 10768-14822/com.owncloud.android.beta D/ExistenceCheckRemoteOperation: Existence check for http://removed.domain.net/remote.php/webdav/Photos/ targeting for  existence finished with HTTP status 200
11-25 14:16:30.053 10768-14822/com.owncloud.android.beta D/OwnCloudClient #5: REQUEST HEAD /remote.php/webdav/Photos/IMG_20151125_141625.jpg
11-25 14:16:30.592 10768-14822/com.owncloud.android.beta D/ExistenceCheckRemoteOperation: Existence check for http://removed.domain.net/remote.php/webdav/Photos/IMG_20151125_141625.jpg targeting for  existence finished with HTTP status 404(FAIL)
11-25 14:16:30.677 10768-14822/com.owncloud.android.beta E/UploadFileOperation: Upload of /storage/emulated/0/DCIM/Camera/IMG_20151125_141625.jpg to /Photos/IMG_20151125_141625.jpg: Unexpected exception
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()' on a null object reference
                                                                                    at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:330)
                                                                                    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
                                                                                    at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:590)
                                                                                    at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:538)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
11-25 14:16:30.685 10768-14822/com.owncloud.android.beta D/FileUploader: NotifyUploadResult with resultCode: HOST_NOT_AVAILABLE
11-25 14:16:30.703 10768-14822/com.owncloud.android.beta E/FileUploader: Unexpected exception errorCode: HOST_NOT_AVAILABLE Http-Code: -1
11-25 14:16:30.719 10768-14822/com.owncloud.android.beta D/FileUploader: Stopping command after id 14
11-25 14:16:34.292 10768-10782/com.owncloud.android.beta W/art: Suspending all threads took: 22.561ms

The instant upload is activated and I also allowed uploads on the cellular network.

Server side is telling me:
Debug	webdav	Exception: {"Message":"HTTP\/1.1 404 File with name Photos\/IMG_20151125_141514.jpg could not be located","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(78): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('Photos\/IMG_2015...', 0)\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(253): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpHead(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:HEAD', Array)\n#8 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#10 \/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/remote.php(137): require_once('\/homepages\/13\/d...')\n#11 {main}","File":"\/homepages\/13\/xyzxyzxyzxyz\/htdocs\/myfolder\/ownCloud\/lib\/private\/connector\/sabre\/objecttree.php","Line":159}	2015-11-25T13:15:22+00:00
Error	PHP	Cannot modify header information - headers already sent by (output started at /homepages/13/xyzxyzxyzxyz/htdocs/myfolder/ownCloud/3rdparty/sabre/http/lib/Sapi.php:70) at /homepages/13/xyzxyzxyzxyz/htdocs/myfolder/ownCloud/3rdparty/sabre/http/lib/Sapi.php#58	2015-11-25T13:15:21+00:00

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger which version do you use? latest is 20151124, yesterday.
There it is working for me.

**Comment by AndyScherzinger** [comment]
Mine isn't from yesterday, so I'll check that again.

**Comment by MrEnderkiller** [comment]
That's pretty strange but after trying with the new latest beta (today, the 20151125) the problem didn't appear again for me.

**Comment by AndyScherzinger** [comment]
I tried both, latest beta 25th and actual master, both fail for instant upload but also simply hang for any kind of upload so it might be related to the Upgrade on the server side when I moved from 8.1 to 8.2.1.
Will probably reinstall oC on the server...

**Comment by AndyScherzinger** [comment]
I tried both, latest beta 25th and actual master, both fail for instant upload but also simply hang for any kind of upload so it might be related to the Upgrade on the server side when I moved from 8.1 to 8.2.1.

Reinstalled the server, so now I am running 8.2.0 with a lot of mayor problems:
* Upgrade doesn't work via updater since the replace fails all the time 
* iPhone uploads don't work
* Android Uploads do work again
* Most of my photo can't rendered as thumbnails neither in the folder view on in the gallery

Several tries to get the server side back to working probably frustrated my so much that I am going to take a break for now waiting for a newer oC version to be released and give the whole infrastructure another try then but for now it is to frustrating and time consuming. Sorry :disappointed: 
Hope to be back in a cuple of weeks. All my dev efforts are pushed to the respective feature branches / PRs

**Comment by AndyScherzinger** [comment]
So I now have 8.2.1 running again which works for instant uploads but doesn't for regular manual uploads. For some reason the execute method is called, the pre exceute method is called but the doInBackground isn't. Pretty weired not sure if this is due to the server or the new phone (N5X), most likely the server doesn't really work.

**Comment by AndyScherzinger** [comment]
I created a ticket in core for this matter: https://github.com/owncloud/core/issues/20762

**Comment by tobiasKaminsky** [comment]
Please do not give up! Your work here is so valuable that I/we do not wanna miss it! :+1: 
I am always using a "beta" server and a productive version, so that I always have my main cloud up and running.
If I can help you with something please let me know.
(Although I have a vServer with root and therefore probably less problems than you with 1&1)

**Comment by AndyScherzinger** [comment]
I gave und giving up :) So I will happily continue and hope that someone can figure out the thumbnail problem I opened an issue for. My guess is that it is related to the hosting constellation, meaning a memory issue since I don't have dedicated memory or maybe it is something else since I couldn't find a pattern for the thumbnailing failures since even for the Nexus5 photos some get thumbnails and some don't. It is very weird.

Anyways, I'll see that I can support @przybylski with UI stuff on optimizing the appearance of the what's new screen and than see what comes up next. For the app I just moved to the beta permanently to enjoy all the PRs out there in the wild :) :+1: Thanks for maintaining the beta releases and branch. I know this is a lot of work and I wouldn't want to miss it and the fwatures you are adding to the Android app.

**Comment by enoch85** [comment]
Thanks for your efforts @AndyScherzinger

**Comment by enoch85** [comment]
I can add and confirm that this happens on every time a picture is uploaded through InstantUpload.

**Comment by davivel** [comment]
@enoch85 , do you use Nginx?

**Comment by enoch85** [comment]
@davivel I use Nginx as a reverse Proxy with Apache backend, server version 8.2.2.

**Comment by plabong** [comment]
ownCloud Server 8.2.2 / Debian 8.3
---------------------------------------------
Installed desktop sync (Windows V2.1.0.5683) for 4 new users (these users never used desktop sync before) I've got the initially mentioned log entries in owncloud.log as follows:

[ownCloud.log entry]
-----------------------------------
Cannot modify header information
- headers already sent by (output started at <ocpath>/3rdparty/sabre/http/lib/Sapi.php:70)
at <ocpath>/3rdparty/sabre/http/lib/Sapi.php#58
-----------------------------------

These Apache (V2.4) actions triggered above mentioned log entry:

2016-01-27 12:39:42
apache: "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1358
--> [ownCloud.log entry]

2016-01-27 12:42:30
apache: "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1358
--> [ownCloud.log entry]

2016-01-27 13:25:42
apache: "HEAD /owncloud/remote.php/webdav/ HTTP/1.1" 200 142
--> [ownCloud.log entry]

2016-01-27 13:40:02
apache: "HEAD /owncloud/remote.php/webdav/ HTTP/1.1" 200 142
apache: "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1358
--> [ownCloud.log entry]

**Comment by CriticalNoob** [comment]
There is a fix there : 
https://github.com/fruux/sabre-dav/pull/577/files

**Comment by davivel** [comment]
@CriticalNoob , can you explain a bit more, please?

@all, did anybody test the solution proposed by @CarstenMeyer ?

@all, anybody else is using a reverse proxy , besides @enoch85 ?

**Comment by CriticalNoob** [comment]
@davivel 
Just look at the issue fixed by the pull.
https://github.com/fruux/sabre-dav/issues/572

Solution by @CarstenMeyer works for fixing auto upload but it doesn't have anything to do for "Cannot modify header information - headers already sent"

**Comment by davivel** [comment]
@PVince81 , maybe this SabreDav fix is relevant for core? I'm afraid I get lost trying to track this in the server repo.

**Comment by PVince81** [comment]
@CriticalNoob are you running the latest OC version, 8.2.2 ?
The fix might be in already. But I also saw this: https://github.com/owncloud/core/pull/21938
So in 8.2.3 it will be using Sabre 2.1.9

**Comment by CriticalNoob** [comment]
@PVince81 Yep  8.2.2

As if you check Sabre 2.1.9 code you won't find the fix, it might not be fixed in 8.2.3.

I guess we will have to wait until Sabre 3.1.1 (or manually apply the fix).

**Comment by CriticalNoob** [comment]
Just to add that for the picture auto upload not working, you have to be sure to change some value in php.ini as described here : https://doc.owncloud.org/server/7.0/admin_manual/configuration/big_file_upload_configuration.html

On ubuntu server 14.04 the post_max_size default is low (8M i think) and as my picture are usually around 10M, they wouldn't upload.

**Comment by TheKaban** [comment]
Hello!
I have this error:

`Can not modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at / var / www / owncloud / 3rdparty / sabre / http / lib / Sapi.php # 58`

OwnCloud: 8.2.2
OC: Linux Ubuntu Server 14.04.03
PHP: 5.5.9
Apahe: 2.4.7
Mysql: 5.5.47

[https://github.com/fruux/sabre-dav/pull/577/files](https://github.com/fruux/sabre-dav/pull/577/files)
This method will solve my problem?

Thank you!

**Comment by CriticalNoob** [comment]
I guess there is only way to know... But backup the file first.

**Comment by enoch85** [comment]
@davivel @tobiasKaminsky  When can we expect a fix for this?

**Comment by AndyScherzinger** [comment]
@enoch85 reading through the comment it seems to me this is a server side issue (sabre dav). So probably @DeepDiver1975 has an idea :)

**Comment by CriticalNoob** [comment]
@enoch85 
Options :
You manually fix it for your installation 
You wait until the fix is applied to Sabre 2.1.9 (if Owncloud devs decide to) 
You wait until there is a Owncloud version with Sabre 3.1.1 (Probably OC 9 but not sure)

**Comment by davivel** [comment]
As an alternative, since this seems triggered specifically by the HEAD method, we can replace it with a PROPFIND with depth=0 and minimum properties in the response; if a I recall correctly, the desktop client uses something like that from years ago.

Sounds like "sneakable"...

**Comment by malenki** [comment]
I have the same issue. The log sais
`Error 	PHP 	Cannot modify header information - headers already sent by (output started at /www/htdocs/w0125c67/malenki.ch/o/3rdparty/sabre/http/lib/Sapi.php:70) at /www/htdocs/w0125c67/malenki.ch/o/3rdparty/sabre/http/lib/Sapi.php#58 `

```
ownCloud client 1.9.1 from FDroid
ownCloud server 8.2.2
on a hosted server with 
PHP 5.5.31
MySQL 5.5.46
```

I als ran the ownCloud server with the two files from 
https://github.com/fruux/sabre-dav/pull/577/files – without success.

**Comment by RealRancor** [comment]
@CarstenMeyer 

Output buffering should be completely disabled as described at https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-php and normally also enforced in https://github.com/owncloud/core/blob/v8.2.2/.htaccess#L31

For the issue itself: Maybe some one should be ping upstream why https://github.com/fruux/sabre-dav/pull/577/files can't be found in SabreDAV 2.1 or 3.0.

**Comment by RealRancor** [comment]
Just some background info, the fix hasn't made it into 2.1 however the changelog of 2.1.x is stating that https://github.com/fruux/sabre-dav/blob/3.1.1/CHANGELOG.md#212-2014-12-10

However the fix is included in SabreDAV 3.0.7 used by oC9:

https://github.com/fruux/sabre-dav/blob/3.0.7/lib/DAV/Server.php#L441

so its probably just a matter of upgrading to the upcoming oC9.

**Comment by enoch85** [comment]
Some new output in the ownCloud 9 log:

```
Fatal  webdav  Exception: {"Message":"HTTP\/1.1 405 The resource you tried to create already exists","Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(590): Sabre\\DAV\\Server->createCollection('InstantUpload', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1121,"User":"Dario"}  2016-03-10T14:22:23+00:00  
Error no app in context Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"\/DirektUppladdning\/20160310_105138.jpg not found while trying to get owner","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php(913): OC\\Files\\View->getOwner('\/DirektUppladdn...')\n#1 \/var\/www\/owncloud\/apps\/activity\/lib\/fileshooks.php(191): OC\\Files\\Filesystem::getOwner('\/DirektUppladdn...')\n#2 \/var\/www\/owncloud\/apps\/activity\/lib\/fileshooks.php(145): OCA\\Activity\\FilesHooks->getSourcePathAndOwner('\/DirektUppladdn...')\n#3 \/var\/www\/owncloud\/apps\/activity\/lib\/fileshooks.php(101): OCA\\Activity\\FilesHooks->addNotificationsForFileAction('\/DirektUppladdn...', 'file_created', 'created_self', 'created_by')\n#4 \/var\/www\/owncloud\/apps\/activity\/lib\/fileshooksstatic.php(60): OCA\\Activity\\FilesHooks->fileCreate('\/DirektUppladdn...')\n#5 [internal function]: OCA\\Activity\\FilesHooksStatic::fileCreate(Array)\n#6 \/var\/www\/owncloud\/lib\/private\/hook.php(105): call_user_func(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/filechunking.php(224): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\n#8 \/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/file.php(436): OC_FileChunking->file_assemble(Object(OCA\\Files_Trashbin\\Storage), 'files\/DirektUpp...', '\/daniel@en0ch.s...')\n#9 \/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/file.php(103): OCA\\DAV\\Connector\\Sabre\\File->createFileChunked(Resource id #41)\n#10 \/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/directory.php(134): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #41)\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1036): OCA\\DAV\\Connector\\Sabre\\Directory->createFile('20160310_105138...', Resource id #41)\n#12 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(525): Sabre\\DAV\\Server->createFile('DirektUppladdni...', Resource id #41, NULL)\n#13 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#18 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#19 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/view.php","Line":1583} 2016-03-10T09:52:01+00: 
```

**Comment by moba** [comment]
This is still filling up my logs with Owncloud 9.0.1:

`{"reqId":"VwljNH8AAAEAAHQN6BsAAAAj","remoteAddr":"xxx","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:83) at \/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-04-09T20:16:53+00:00","method":"GET","url":"\/owncloud\/remote.php\/dav\/calendar\/demo","user":"demo"}
`

**Comment by marco-aa** [comment]
Hi all,

like malenki posted on 2nd of march - i added the patch from https://github.com/fruux/sabre-dav/pull/577/files by hand and the errors are gone :-)

Running CentOS Linux release 7.2.1511 (Core) in KVM, Owncloud 8.2.3 (stable)

My error had been like ::

Cannot modify header information - headers already sent by (output started at /host-data-store/www/html/3rdparty/sabre/http/lib/Sapi.php:70) at /host-data-store/www/html/3rdparty/sabre/http/lib/Sapi.php#63

**Comment by RealRancor** [comment]
Quoting from https://github.com/fruux/sabre-dav/pull/577#issuecomment-199444865:

> I'm not sure I understand your question. This ticket refers to a very specific issue. It got reverted later, but a new solution was added on the 2.1 branch. The more correct fix got added in 3.0, but afaik this should not be a problem in stock sabre/dav on the 2.1 branch.
>
> If this is causing a new problem, please just open a new ticket with a reproducible test case. "It causes an error on owncloud" is not enough information for me to figure out what's wrong. If it's an issue in owncloud, open a ticket on that project, not here.

and https://github.com/fruux/sabre-dav/pull/577#issuecomment-200879021

> Then you should report the issue at Owncloud. I'm locking this thread now.

oC 8.2.x has SabreDAV 2.1.x and oC 9.0.x has 3.0.x. If that issue is still happening create a new bugreport at https://github.com/owncloud/core/issues

**Comment by e-alfred** [comment]
One app that causes these problems is the Antivirus app:

https://github.com/owncloud/files_antivirus/issues/110

**Comment by marco-aa** [comment]
Dear e-alfred did you make a cross check with my posting here in this issue https://github.com/owncloud/android/issues/1074#issuecomment-211439064 and patched the file by hand - because the error from this issues is solved for me (by the way i use the 8.2.3 of OwnCloud, too) - because it's fixed by me i'm not sure if your problem has the same reason :)

**Comment by e-alfred** [comment]
@marco-aa I am not quite sure if this patch solves the problem me. The only thing to make it work was to disable the Antivirus app (and filing a bug there). I didn't apply the patch to make it work.

**Comment by davivel** [comment]
Hi all. Is this still a problem for any of you?

Could you test again with version 2.3.0 of the Android app? The check of existence now is done with a PROPFIND method instead of HEAD, that seemed the method triggering the error in your logs.

Thanks in advance.

**Comment by davivel** [comment]
Closing. Please, if anybody still notices it, just comment and I will reopen.

**Comment by malenki** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}This mail was sent to my brother

He died in Novembre in Spain

https://en.wikipedia.org/wiki/User:Malenki

 

David A. Velasco schrieb am 21.03.2017 12:42:


Hi all. Is this still a problem for any of you?

Could you test again with version 2.3.0 of the Android app? The check of existence now is done with a PROPFIND method instead of HEAD, that seemed the method triggering the error in your logs.

Thanks in advance.

**Comment by butonic** [comment]
😞

**Comment by davivel** [comment]
I'm very sorry to read that :( . My condolences.

**Comment by MarcioQuimbundo** [comment]
error_reporting(0) will not solve the problem, but it will clean the output error
