### ISSUE TITLE
Activity Stream View in Android

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1077]
As an ownCloud user, I want to be able to see a list of my recent activities on the mobile device so I can quickly find files and actions that occur on the device.

Acceptance Criteria:
- Mobile app should query the activity stream API from the server
- Should be a separate tab, where the activity stream is shown in reverse chronological order
- Interface should look similar to the activity stream app on the server, but updated/ adjusted slightly for Android

@karlitschek @jancborchardt @rperezb @javiergonzper @cmonteroluque
owncloud/activity#349

**Comment by karlitschek** [comment]
looks good. :-) 
The App should also trigger a local Android notification when a new activity appears on the server.

**Comment by jancborchardt** [comment]
Also here yep, as discussed before.

**Comment by jancborchardt** [comment]
Ref same iOS issue: https://github.com/owncloud/ios/issues/422

**Comment by davivel** [comment]
We need to be careful with the number of notification thrown to the user. Is the activity stream very verbose?

Besides, is the activity stream app installed and enabled by default with OC servers? Is it possible to through it's API check if it exists and is enabled?

Thanks.

**Comment by jancborchardt** [comment]
@davivel Activity stream and notifications is not the same thing. Activity stream is a view in the app. Which of those activities are shown as notifications is something different (and will mostly be actions on shared files by other users).

**Comment by rperezb** [comment]
as said on the iOS issue:
Another AC it could be to show this per account basis. 
- If you tab on a folder, you access to the folder content
- If you tab on a file
        + Being the file downloaded, you preview the file, being the previewd available if not access to the details view
        + If the file is not downloaded, it´s downloaded

About notifications, I would work on it on a different issue, I'd say that it would be needed to offer to users the possibility of switching them off, probably from settings.

**Comment by CaptionF** [comment]
@MTRichards @rperezb @jancborchardt  prospect waiting - what can we share about implementation?

**Comment by rperezb** [comment]
@CaptionF as @MTRichards said on the iOS issue:
"As of right now, it remains a roadmap item. Ideall by the end of Q2 we can put this in, but without more info on the prospect, we have to finish the sharing work first"

**Comment by MTRichards** [comment]
Returning to this issue again for the purposes of design and planning.

There is an activities view in the app
Activities include information from the server API, such as file activity, comments, shares
Activity window needs a size limit
Activity view needs a search bar / filter
Activity should show the name of file in large text, with smaller text showing the action taken and the name of the actor, as well as a thumbnail of the file that was affected

**Comment by jancborchardt** [comment]
Also, it should show the icon of the type of action. And if another person was involved (shared with, or changed by someone else etc), their profile image should be shown left of their name. Exactly like in the web interface.

**Comment by davivel** [comment]
> Exactly like in the web interface.

But native, right? This will be a lot of work.

Really crazy proposal: let's put a web view showing the activity view in the web interface.

**Comment by tobiasKaminsky** [comment]
Web view would never feel "right" as it will not show it natively.
So I would think that we do it either the right way or not.
And of course this is a lot of work as e.g. clicking on a mentioned file/folder should navigate the user to the correct place (which will not work for a webview).

**Comment by davivel** [comment]
> Web view would never feel "right" as it will not show it natively.

I agree.

> So I would think that we do it either the right way or not.

Makes sense, even though there is no real election then. We'll have to do it the right way then, the "or not" will not be a real option.

**Comment by tobiasKaminsky** [comment]
> will not be a real option
Not really, but it can be prioritized to be less important than other enhancements ;)

**Comment by davivel** [comment]
True, let's see :)

**Comment by jancborchardt** [comment]
Btw also important: The web view will not work offline, and the performance will be very bad on slow connections.
