### ISSUE TITLE
Grid view not shown if picasa.ini is present

### ISSUE THREAD

**Issue by etiess** [owncloud/android#1080]
I use Picasa on my Windows desktop: it creates a special file in each folder called ".picasa.ini". This file is used to store useful information (people in the pictures, modification, ...). So, IMO, it's useful that ownCloud syncs it.

Unfortunately, this prevents the Android app to consider the folder "full of pictures, and only pictures".

As a consequence, the grid view is not shown. Instead of that, we have a file list, with thumbnails and the name of the folders.

Would it be possible, for example, to exclude files starting with a point, when the app wants to know if there are only pictures in the folder?

Config : 
Ubuntu 15.04   3.19.0-25-generic
Server version: Apache/2.4.10 (Ubuntu)
PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28)
mysql  Ver 14.14 Distrib 5.6.25, for debian-linux-gnu (x86_64) using  EditLine wrapper
Android ownCloud app: 1.7.2
Android version : 4.2.1
ownCloud server: 8.1.0

**Comment by tobiasKaminsky** [comment]
On the first implementation the threshold was 80% pictures to switch to grid view.
Now it is 100% pictures.
But afair there should be a setting sooner or later.

But (again) you are right, that files starting with a dot should be ignored for computing the threshold.
@davivel Is this ok for you? Then I would implement this. Should be just one or two lines ;)

The customized threshold in the preferences we can discuss in a new issue.

**Comment by etiess** [comment]
Great! I agree with your 2 complementary solutions:
1. Best "straight to the point" solution: ignore files starting with a dot for computing the threshold
2. Wider solution with manually adjustable threshold: https://github.com/owncloud/android/issues/1081 

In order to complete solution 1, would it be possible to look at the files attributes? For example, I would propose to ignore the files with an attribute "hidden" in the threshold calculation.

Finally, I would make another proposal (which may have been already discussed: in this case, sorry!). What about putting a button to manually switch from list view to grid view? This button would be available on the web interface and in the android app. It would work like this:
- The user opens a folder
- Threshold calculation decides to show the folder in list or grid view
- The user can toggle the button to change the view

I think I would prefer this solution to the adjustable threshold (it is complementary though). As an improvement of this feature, ownCloud could remember the user's choice.

Do you want me to open a new issue to discuss this?

**Comment by masensio** [comment]
Hi @etiess,

Thanks for your feedback.

As @tobiasKaminsky said, now the gridview is shown when the folder only contains images. 

Maybe we can ignore hidden files like .picasa.ini for calculating the threshold for showing the gridview or put the adjustable threshold. But about showing the filelist in listview/gridview we have https://github.com/owncloud/android/issues/894. If you read this you can see that in the future we will add a button to select the view (list/grid) for showing the files. (I hope it will be available in a near future)

**Comment by etiess** [comment]
Thank you @masensio: indeed #894 is the answer to my button proposal.

If you need testing for implementing the hidden files feature, I'm available: unfortunately, I don't have any skills in programming.

**Comment by tobiasKaminsky** [comment]
PR is #1082

**Comment by masensio** [comment]
PR #1082 merged. So I'll close the issue.
