### ISSUE TITLE
Change list vs grid view

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1081]
> I don't know if it's stated in #894, but the grid setting, when enabled, should be propagated down the tree of files to all descendent folders.
If set in root fold, all the children will be shown in grid mode too.
Then, if list view is selected for a subfolder, it will applied (and remembered) to that subfolder and all its children.

>Think in a 3-valued property: "list", "grid" and "inherited"; the default value for every folder is "inherited", with the exception of the root folder, where "inherited" makes no sense and is promoted to "list". The user only can choose in the UI between "list" or "grid", "inherited" is for internal use.

OLD:
The threshold was 80%, now it is 100%.
I think this should be adjustable as each user may have a different wish.

@jancborchardt What do you think? A slider with value?
https://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider
--> With an editable numeric value

**Comment by davivel** [comment]
I wouldn't go this way. Sound like lots of noise about something that should be simple.

I'd just go for #894

**Comment by tobiasKaminsky** [comment]
I think both ideas are additional, not complementary.
Imagine that you always want to have grid view. With #894 you would have to switch the view for every single folder to grid view.
With the threshold you can manage this by setting it to 0%.
(But maybe it is just me that is using our app mainly as an image browser due to my very small internal disk space)

**Comment by davivel** [comment]
I don't know if it's stated in #894, but the grid setting, when enabled, should be propagated down the tree of files to all descendent folders.

If set in root fold, all the children will be shown in grid mode too.

if then, list view is selected for a subfolder, it will applied (and remembered) to that subfolder and all its children.

**Comment by jancborchardt** [comment]
@davivel yup!

**Comment by tobiasKaminsky** [comment]
This is a very good idea and would fit perfectly for my use case.
How can this be shown and explained to the user?

New folders would have automatically the setting of the parent folder?

**Comment by jancborchardt** [comment]
It doesn’t need to be shown/explained I’d say, at least not in the first iteration.

**Comment by davivel** [comment]
> It doesn’t need to be shown/explained I’d say, at least not in the first iteration.

Agreed.

Think in a 3-valued property: "list", "grid" and "inherited"; the default value for every folder is "inherited", with the exception of the root folder, where "inherited" makes no sense and is promoted to "list". The user only can choose in the UI between "list" or "grid", "inherited" is for internal use.

**Comment by jancborchardt** [comment]
Good call!

**Comment by tobiasKaminsky** [comment]
Then I will do it this way.

**Comment by tobiasKaminsky** [comment]
@davivel 
Here is my proposed way:
- create a new sqLite table with with mID, showGrid (boolean)
- on first start: add / with showGrid = false
- if changing via context menu: update table
- on entering an arbitrary folder:
 - try to find it in database -> show view according to entry
 - else identify parents id, try to find it in database
 - else continue until root directory is reached

Remaining problem would be that the entries always will be added or updated, but not getting deleted.
But I doubt that this is a problem...or?

Or do you have a better idea?

Thanks :)

**Comment by tobiasKaminsky** [comment]
Please see #1099 and let us discuss there.

**Comment by masensio** [comment]
Hi,
#1099 is merged on master branch. So, you can switch between  grid vs list in the next release.
I'll close this issue.
