### ISSUE TITLE
multiple ownCloud android app on the same device - INSTALL_FAILED_CONFLICTING_PROVIDER error

### ISSUE THREAD

**Issue by aplicret** [owncloud/android#1091]
I need to install two ownCloud android apps on the same device - suppose CloudA and CloudB (different UI for CloudB). After installing CloudA and running successfully on the device, when I try to install CloudB, Eclipse shows INSTALL_FAILED_CONFLICTING_PROVIDER error. I tried by changing 'authorities' name in the manifest but it does not work. What's wrong!!!

**Comment by masensio** [comment]
Hi @aplicret,

Do you change the package name? It is impossible to install two apps with the same package name on the Android device.

Please, tell me if this solves your problem

**Comment by hannesa2** [comment]
you have to set individual authority for provider

**Comment by tobiasKaminsky** [comment]
But why do you want to do this?
You have the possibility to add different accounts?

**Comment by aplicret** [comment]
I have changed the package name and authority but no result. Yes, I would like to run same owncloud android app two times on the same device with different accounts. Second one is the modified app (some UI and app name changes). What are the changes should I do to run both apps on the same device with different accounts?

**Comment by davivel** [comment]
See the file res/values/setup.xml. You will need to change the values of the parameters ```app_name```, ```account_type```, ```authority```, and ```data_folder```. Probably you will want to change also other parameters there, though not strictly needed to get both apps running.

**Comment by aplicret** [comment]
Hi @davivel thank you. It's working now :+1: 
Thanks to all.

**Comment by rperezb** [comment]
Hey @aplicret, it seems that this issues is fixed so that I close the ticket, being needed please reopen and add a comment

**Comment by supportreq** [comment]
@rperezb not sure if this is a bug, but i tried with owncloud app from the play store and tried installing a dev version with the application package name changed using : Android Studio -> android project -> Module Settings -> Flavours -> Application id -> com.ownclouddev.devinstall..

in the setup.xml modified the authority to com.ownclouddev.devinstall.provider

any idea?

**Comment by rperezb** [comment]
@supportreq please follow @davivel comment https://github.com/owncloud/android/issues/1091#issuecomment-129729348
I'd say that this is working fine, we do test daily with more than 1 ownCloud app installed on the same device
