### ISSUE TITLE
Share: Remember last action and show as icon

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1094]
Hi,

I would like to implement a function that remembers the last share action.
![screenshot_2015-08-13-19-28-44](https://cloud.githubusercontent.com/assets/5836855/9256762/b46a5062-41f1-11e5-907d-4cf2d5f427d6.png)
See it here in chrome.

What do you think @davivel @jancborchardt

**Comment by jancborchardt** [comment]
Yeeess please! :)

**Comment by tobiasKaminsky** [comment]
Isn't this better?
![actionbar-shareaction](https://cloud.githubusercontent.com/assets/5836855/9275855/69fea528-42a0-11e5-9f70-9695fdc81117.png)
Then the last action would automatically be remembered.
(ref: https://developer.android.com/training/sharing/shareaction.html)

**Comment by tobiasKaminsky** [comment]
This would be it :)
Currently only for ImageView.
(for overall context menu I do not know how to do it).

![send](https://cloud.githubusercontent.com/assets/5836855/9288336/ea089246-4341-11e5-9e14-546e72106dba.jpg)
![send1](https://cloud.githubusercontent.com/assets/5836855/9288338/fab36f44-4341-11e5-8a98-a37ebaba700f.jpg)

**Comment by jesmrec** [comment]
Using system menu.
