### ISSUE TITLE
Connect button can't be pushed

### ISSUE THREAD

**Issue by Ounnix** [owncloud/android#1096]
Connect button not working
I enter in all my info go to press connect and nothing happens.

**Comment by AndyScherzinger** [comment]
Does the problem still persist? How long did you wait?
The app checks the connection to the server address and if successful activates the connect button.

**Comment by Ounnix** [comment]
After disabling apache mod_security and mod-evasive it seems to work ok.  What can I do to use owncloud with these apache modules?

On August 19, 2015 5:45:42 AM MDT, Andy Scherzinger <notifications@github.com> wrote:
>Does the problem still persist? How long did you wait?
>The app checks the connection to the server address and if successful
>activates the connect button.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/android/issues/1096#issuecomment-132559124

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davivel** [comment]
Hi, @Ounnix . Is this still a problem for you?

**Comment by jesmrec** [comment]
Fixed today
