### ISSUE TITLE
Android App takes painfully too long to show thumbnails when folder opened for the first time 

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1097]
The thumbnails are seen in the web on the same account.

Can I give more information?

**Comment by tobiasKaminsky** [comment]
I have tried it on my local installation and an emulated nexus 5.
It is still working.

Please provide more informations via this template: https://raw.github.com/owncloud/android/master/issue_template.md

**Comment by AndyScherzinger** [comment]
Also tried it with my (non-emulated) nexus 5 and owncloud 8.1.1 and can confirm that it is still working.

**Comment by tobiasKaminsky** [comment]
@elpraga Can you please provide more infos by filling out the template?
https://raw.github.com/owncloud/android/master/issue_template.md
Thank you!

**Comment by elpraga** [comment]
I'm not on the computer now. I tried it again, and now it does show some thumbnails, but not all of them even though they are all seen in the web interface. The folder has some 100 photos.

I'll try to give more info when get back to the computer.

Note that if the pictures are downloaded locally on the android device, they do show all..

**Comment by Bugsbane** [comment]
I just tried with client version 1.7.2 and server 8.1.1 and a folder with 342 photos on a Moto E second generation running Android 5.1 and it works for me.

**Comment by tobiasKaminsky** [comment]
@elpraga Do you have any update on this issue?

**Comment by elpraga** [comment]
Hello Tobias!

I was watching the behavior of the app. Recently the thumbnails do appear,
but tremendly slowly. I have to enter and leave the folder several times in
order to see all the thumbnails. This is true even fit folders with just a
dozen of photos in them. The internet connection should not be the issue as
download of files  goes reasonably quickly.

Is there a way to speed up the process? Maybe some change in settings on
server side? I really don't understand why is it taking so painfully long..

Thanks for help!

**Comment by tobiasKaminsky** [comment]
@elpraga thanks for your feedback.
Are those folders shared with you? Or do they belong to a shared folder?
With my OC server, all thumbnails of folders that are not shared are very fast, but the folders I have shared with my wife, show exact the same behaviour as you described. But not for me, instead my wife has this problem.
I suspect that the one who was shared with (sharees) cannot reliable access these thumbnails...

**Comment by elpraga** [comment]
Hello Tobias!
No, the files are on my server. I just tested another folder on a different
server and it seemed like the first 7 is so thumbnails got there quickly,
and the rest took noticeably longer, though MUCH LESS then it used to take
when I first reported the issue.

This makes me wonder when are the thumbnails generated? Is it when I open
the folder for the first time in the app? Do they get stored on the server?
Wouldn't it be better to generate them when photos are uploaded? Or at
least make it an option? I certainly would prefer to choose to generate the
thumbnails when I upload the photos and save them on server if I could.
Normally I don't care do much about time when I upload the pictures, but I
do when I want to show a gallery to someone on my phone. If the thumbnails
take 4 minutes to load, it doesn't look good, it looks like something is
broken.

BTW. I updated the OC on server to 8.1.3, so I'm reporting against that
version now.

Have a great day!

Tomas

**Comment by tobiasKaminsky** [comment]
The thumbnails are generated on server side, but I do not know when and where. This is handled by /core.
We are just using the thumbnail system that are already shown on the web UI, though with a maybe different image size as our image size depends on the mobile display size.
Maybe @DeepDiver1975 can help us here (or give us an idea who we can contact for thumbnail generation questions?)

**Comment by elpraga** [comment]
That would be great! If we could find a way to improve the thumbnails
loading, it would be a great boast in usability of the Android app!

BTW.. Are there any plans to add sharing with users (like in the web) to
the Android app?

Regards.

Tomas

**Comment by tobiasKaminsky** [comment]
regarding share: there is: #880

**Comment by DeepDiver1975** [comment]
> The thumbnails are generated on server side, but I do not know when and where. This is handled by /core.
> We are just using the thumbnail system that are already shown on the web UI, though with a maybe different image size as our image size depends on the mobile display size.
> Maybe @DeepDiver1975 can help us here (or give us an idea who we can contact for thumbnail generation questions?)

Thumbnails are generated on request - which will generate some load on the server in case a folder with many files is entered the first time.

There have been lengthy discussions on changing this behavior ... the path to walk is not yet fully clear ... lets see

**Comment by elpraga** [comment]
Thank you for the answer!

I understand that both approaches have it's reasons.

Would it be too difficult to make it an option in the settings of the
owncloud's web interface? I guess that should not be that difficult.

I would certainly check the option: "Generate thumbnails on photo upload"

I use mainly the Linux client to upload the photos, but I rely on the
Android client to see some of them. The current setup is very difficult to
deal with in my usecase.

Is there a possibility for this change to happen? Can I vote for it
somewhere?

Tomas

**Comment by elpraga** [comment]
Hello Tobias!

I was looking into the issue more in those days. And it seems that the thumbnails are generated every time a device requests them. I accessed a folder with 90 pictures on my phone and waited until all the thumbnails were generated. Then I accessed the same folder from the tablet and again, it took painfully long to see the thumbnails.

Can we confirm if this is the behavior? It would mean that if you share the folder with 10 people, the thumbnails are generated 10 times.  It seems to me like a big waste of resources.

Is there a way to store the already generated thumbnails on the server and reuse them?

I love using owncloud but right now  it is almost unusable when trying to access remote photos.

I checked my download speed and it is roughly 500kB / s ( downloading a file from owncloud in the Android app)  but a folder with 90 photos takes 7 minutes to show me the thumbnails..

Is there some more information I can provide that would help us to make the app more usable in this user case?

Thanks a lot and let me know if I can help somehow..

Tomas

**Comment by tobiasKaminsky** [comment]
Are you using the same account or are these independent accounts and you share the files between them? 
Might be related to https://github.com/owncloud/core/issues/18417 or https://github.com/owncloud/core/issues/17186

Anyway: This seems to be more a server issue...

**Comment by elpraga** [comment]
The situation with the tablet and the phone I described regarded the same
folder under the same account on two different devices.

But I do use owncloud to share photos with my family, because I live
abroad. And they de have different accounts on the same server. 8 can't
give exact measures on their parts, because they are not too fond of
computers and they live thousands if kilometers away, but I suppose it is
similar..

Anything else I could provide?

Tomas

**Comment by elpraga** [comment]
Thank you for the links! Now i understand the thumbnail creation process a
little better.

Ifound this old ns ongoing discussion that addressed the matter:

https://github.com/owncloud/core/issues/11685

..ifyou areinterested..

**Comment by tobiasKaminsky** [comment]
@elpraga Thank you for pointing out this interesting discussion on /core.
BTW: What kind of server are you using? It must be some "low" hardware as you are facing this problem?

**Comment by elpraga** [comment]
Happy I could help! I was thinking to ask you about the thumbnails
generation process to point it out, but i noticed that You already did :-)

I tried to look into the thumnails i have at the server yesterday to check
if the thumbnails are being generated again for the tablet because of the
different density, but I'll need more time to find that out.

I'm using mele a2000 as a server. It is originally one of the chinese
android "media centers", but i installed ubuntu on it. it has 512 MB of RAM
and a SATA slot, it is absolutely silent and takes very little of energy,
so it is no problem to have it running all the time.

It works like a charm with owncloud, the only issue are the thumbnails on
my android devices.

It hosts two more static web pages, print server, MPD server y python para
jugar.

It usually runs at 30% of CPU. I know that it is not the greatest, but i
would guess that people run OC on even worse machines, as it is "own" and
many people must the in consideration the electricity bill.

I suppose that if I could trigger the thumbail creation upon upload or by a
cron at 4 am, it would work like a charm..

Tomas

**Comment by elpraga** [comment]
Tobias, 
permit me please one side question.. 
Are there any plans to add the grid view possibility in folders not entirely composed of photos? Right now there is no way to see larger thumbnails in folders with let's say 100 photos and 1 text file. The small thumnails are hard to see. It would be useful to be able to swith between grid and list views like in the web interface..

..sorry for asking here, if necessary, I will file a new post..

Tomas

**Comment by tobiasKaminsky** [comment]
Please open for such a different question a new issue as now all people involved into this issue are notified.
(to answer it: in the beta: https://github.com/owncloud/android/tree/beta there is the possibility to switch the view and this will be remembered)

**Comment by tobiasKaminsky** [comment]
@elpraga we have talked about this issue related to beta, or?
Is this still happening for you with the official client?

**Comment by Seferi** [comment]
I will test it again and get back to you asap..
