### ISSUE TITLE
Owncloud app should accept as many share content as possible 

### ISSUE THREAD

**Issue by torwag** [owncloud/android#1098]
The owncloud app is listed among the apps to share information whenever you choice to share something.  However,  most of the time the share fails,  since the owncloud app does not know how to handle the data.  This is really frustrating.  The most advantage purpose of having access to the owncloud server on an android device is the point that one is able to add very quickly content.. Owncloud on the go... 

The Owncloud app should therefore try to handle as much shared data as possible.  If there are multiple ways,  it could offer a selection.  E.g. saving as txt or odt. 
Furthermore,  the settings could define standard saving options.  E.g. Save in the folder notes/income/ save as $date-time-app-name.  
It should be possible to save text,  images,  videos, links,  html,  etc.  
An example how such a saving method could work would be the save dialogs of the firefox webbrowser, where one can simply save as default by a single click or allow customized saving settings.

**Comment by tobiasKaminsky** [comment]
Maybe you can a bit more specific as I do not know what you are sharing and what you expect that the app should do.
Currently the app accepts files and this should work.

Maybe we can collect it likes this:
- content -> desired option
- clipboard text -> save as txt with choosing folder

But of course this is a first brainstorming and does not mean that it can (and will) implemented this way.

**Comment by torwag** [comment]
Thanks for your quick reply.
 
> Currently the app accepts files and this should work.
That might be the "problem" already, since most other apps do not share a file but simply the content in some form. E.g. I would like to save a certain email from K9 as txt and it's attachments in owncloud. 
Others provide text, links, images (but maybe not in a file format). Not sure about the exact exchange formats, I would have to look this up. Basically this request comes from the fact that out of ten times I select owncloud to share some information, I get informed that owncloud can not deal with the data.

**Comment by tobiasKaminsky** [comment]
You are writing a lot of text, but it is still too unspecific. ;) ;)
It is also ok if yo give real examples with the apps you use and what you share.

For K9:
- I have an email with pdf attachement. The pdf just gets open by pdf reader, there is for me no chance to send it to owncloud. (I would have to save the pdf, open a file browser and then send it to owncloud. This is working as it is a file).
- How do you send a complete email as text? For me it is only possible to select a certain text and share this. And then it is the second bullet point I already had written.

**Comment by torwag** [comment]
Hi,

in K9. Select an email->click on the double arrow->select "Share"-> select "owncloud"
One will get the message: "Bo content was received. Nothing to upload"
I'm just looking if there is a way to get information about the intent-mime type of a sending program

**Comment by tobiasKaminsky** [comment]
Mainly for developers:
![k9-text](https://cloud.githubusercontent.com/assets/5836855/9293280/3c0ca3d2-4425-11e5-8a77-9ed9ea7adce5.jpg)

in Uploader: 450 (prepareStreamsToUpload())
It seems as it is just plain text directly copied to the clipBoard.

**Comment by torwag** [comment]
An other example would be firefox. I guess it sends the url as plain text as well.

**Comment by torwag** [comment]
Maybe we could close this ticket referring to #104  and I will  open a new ticket if I come across a specific mime type. 

BTW. I would love to have an app/owncloud feature, which allows me to create a photo, add some text resp. notes (maybe even scribble in the picture) and upload that to an owncloud server as e.g. html or pdf. Not sure this should be an feature of this application or an standalone app. Any thoughts?

**Comment by tobiasKaminsky** [comment]
Yeah.
I guess it just ends up that only text on the clipboard is missing.
But if you find a new use case / scenario, please feel free to open up a new issue.
--> closing.

Adressing your btw: As the owncloud app is mainly an app for sharing, uploading and managing files, I doubt that this is something a regular user wants. 
I guess that a "normal" image manipulation app is enough as this one should be able to send the resulting image to our owncloud app.
