### ISSUE TITLE
Share text when using public share includes username instead of the full name

### ISSUE THREAD

**Issue by godfuture** [owncloud/android#1106]
**Background**
I shared files on my Android device with Owncloud by public link sent over Whatsapp.

**Issue**
The name used to indicate the share action: "XXX shares yyy with you" is done with user name, not with full name. But how does the receiver of me know who this user is? Maybe user names were created with some cryptic pattern or appreviations. I guess using the full name to indicate a share text makes much more sense.

**Comment by masensio** [comment]
Hi @godfuture,

We are using the account username in the share message. 
When you say "full name", do you mean the full account name (like username@server)?

**Comment by tobiasKaminsky** [comment]
I think he means the real name with forename und surname.
Maybe something like that:
Username: mk83
Real name: Martin Klug

**Comment by masensio** [comment]
@tobiasKaminsky,

in that case, we need to access to the Display Name of the account. In the current implementation the app doesn't save this information into the Account.

I don't know if we can access to the Display Name with a GET USER request, maybe it is possible.

Any volunteer?

**Comment by davivel** [comment]
Display names are already available in the app; for example, navigation drawer shows it in the header. So, this should be doable.
