### ISSUE TITLE
make android app available in "ad supported zero cost edition" and "ad-free paid edition" both

### ISSUE THREAD

**Issue by zaxebo1** [owncloud/android#1108]
right now the Android app  of owncloud ( https://play.google.com/store/apps/details?id=com.owncloud.android&hl=en , https://play.google.com/store/apps/details?id=com.owncloud.android.workaround.accounts&hl=en ) 
is available at google play for some cost. This is a huge upfront problem for my friends,colleagues etc whom I want to encourage to swtich from proprietary dropbox to the open source owncloud platform.
Open source needs to make money, I strongly agree.

****

**But right now the android app is only available in paid form(which is an upfront cost)** 

**My suggestion is that please make it available in two editions:
   1) PRO edition = this is "no-advertisement" edition, but the app is "paid"
   2) Free edition = this is "advertisement supported" edition, but the app itself is "zero-cost"**

This advertisement supported edition will really boost your revenues  and popularise your android app very much.

**Comment by zaxebo1** [comment]
feature wise both the Pro edition and Free edition will be same, only the difference will be that in one case - we have to pay upfront cost, in another case -we support the development by viewing advertisements. Atleast the end-user will have some choice.

**Comment by Kernald** [comment]
While I'm not a huge fan of the free ad-based version, if this is done one day, the "good" way to do would be a free version, plus an in-app purchase to remove the ads, instead of two different applications. This way, the user can keep its configuration when removing the ads.

**Comment by zaxebo1** [comment]
@Kernald   :+1:

**Comment by Alexandero89** [comment]
You can just use the App-Store F-Droid. It is an Appstore for OpenSource-Apps.
There you can find a free OwnCloud App

**Comment by zaxebo1** [comment]
@Alexandero89: if i install it from F-Droid, then this app will not make money. I want to promote this app to my friends and family - by offering free installation, BUT i still want the open source to make money (through advertisements) , even in third world users.

**Comment by tobiasKaminsky** [comment]
Is there an overview how much money is generated by ads?

**Comment by Bugsbane** [comment]
Seems to me that having most users install an app that shows ads, which if we use the most standard ad networks (*cough* Adsense *cough*) also includes large privacy risks, that we're actually encouraging users to run counter to the actual founding spirit of ownCloud, that is to get people's privacy back by getting them off privacy destroying networks.

Personally, I would rather have an easy to follow guide for novices to allow apps from unknown sources, download and install the apk (not necessarily with the whole unnecessary installing of F-Droid) and then turning unknown sources back off again, than getting most of our users sending their private data off to ad networks.

If the argument against this is loss of income to ownCloud, then I humbly suggest that we would likely make far more than the ads would provide through improving commercial services and strengthening our reputation among sysadmins for being privacy and particularly security conscious. Neither is done by an app delivering ads from unknown advertisers to users.

**Comment by davivel** [comment]
Hi @all. Sorry, but as far as I know there is no plan to change the distribution conditions of the app. 

cc @rperezb @MTRichards

**Comment by rperezb** [comment]
hey, not, sorry, it is not planned to change the distribution conditions.

@zaxebo1 let me add another distribution point for the Android app besides the Google Play market and the github repo itself: droid.org https://f-droid.org/repository/browse/?fdid=com.owncloud.android

Hope this helps
