### ISSUE TITLE
Accentuated letter are not sorted alphabetically

### ISSUE THREAD

**Issue by etiess** [owncloud/android#1110]
In a folder list and in a file list, accentuated letter are not considered properly to sort the folders/files.

For example, the letter "e" with accent "é" should be considered as a normal "e". But a folder or a file starting with "é" is sent to the end of the list, after "z".

Example:
- Étudiant should be before Radio
- Fé should be before Fr

It's the same for other accentuated letters (I didn't test all of them): í, à, ô, ù, ñ, ...

**Comment by masensio** [comment]
Hi @etiess,

Thanks for your ideas.

The current method to sort the filenames is using an Alphanumeric Comparator, but it doesn't take into account the localization.
To improve the sorting method we can take into account the locale, in this way we can sort accentuated letter properly. 
I think it is a good improvement, but I can't say when it will be available.

**Comment by etiess** [comment]
I understand. I don't know if it can help, but I found a workaround here: http://stackoverflow.com/questions/16282083/how-to-ignore-accent-in-sqlite-query-android
I quote: 


Generally, string comparisons in SQL are controlled by column or expression COLLATE rules. In Android, only three collation sequences are pre-defined: BINARY (default), LOCALIZED and UNICODE. None of them is ideal for your use case, and the C API for installing new collation functions is unfortunately not exposed in the Java API.

To work around this:

    Add another column to your table, for example MOVIE_NAME_ASCII

    Store values into this column with the accent marks removed. You can remove accents by normalizing your strings to Unicode Normal Form D (NFD) and removing non-ASCII code points since NFD represents accented characters roughly as plain ASCII + combining accent markers:

    String asciiName = Normalizer.normalize(unicodeName, Normalizer.Form.NFD)
        .replaceAll("[^\\p{ASCII}]", "");

    Do your text searches on this ASCII-normalized column but display data from the original unicode column.

**Comment by tobiasKaminsky** [comment]
![locale](https://cloud.githubusercontent.com/assets/5836855/9467641/5c8d7ce8-4b3d-11e5-8e36-2e1f7361f077.jpg)

That was an easy one :)

**Comment by etiess** [comment]
Wao ;) Great!

**Comment by tobiasKaminsky** [comment]
PR is in #1117

**Comment by etiess** [comment]
@tobiasKaminsky I just installed the last version of the android app: looks great. (v. 1.8.0)

This issue is still present on my mobile: is your PR integrated in this version? Thank you

**Comment by AndyScherzinger** [comment]
Hi @etiess this issue is still open (see milestone on the right of this issue) but this might be something which could be integrated into 1.8.1 and thus released with the end of year release. What do you think @rperezb ?

**Comment by rperezb** [comment]
@AndyScherzinger yes, thanks for pointing out this one! 

Why don't we start taking care of this one by reviewing @tobiasKaminsky code? Can you have a look at it? and add +1 if you agree?

**Comment by AndyScherzinger** [comment]
did the code review, added +1 :+1:
