### ISSUE TITLE
png background is shown in the folder

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#1113]
- STEPS TO REPRODUCE IT
  There is an account which has two folder:
   -a (Inside folder a, there are two png without background)
   -Documents

   1. login
   2. Access to folder "a"
   3. Thumbnails without background is shown
   4. go back to root

- CURRENT BEHAVIOR
    -- The background for png are shown in the folder 

- EXPECTED BEHAVIOR
    -- background is only shown in png images, not in other icons

- DEVICE
      -- Motorola e v.4.4.4

This issue came from #1056

@tobiasKaminsky could you take a look? thanks

**Comment by purigarcia** [comment]
![background](https://cloud.githubusercontent.com/assets/4538201/9466401/ea57462a-4b34-11e5-8766-850853f46959.png)

**Comment by tobiasKaminsky** [comment]
@purigarcia Strange, this is not happening to me.
Can you try #1114 ?
