### ISSUE TITLE
Create folder button in uploader view move to ActionBar

### ISSUE THREAD

**Issue by masensio** [owncloud/android#1120]
To maintain a similar appereance in the whole app, the uploader should have the create folder button in the action bar not in the bottom as a simple bottom.
You can see in the next image:

![image](https://cloud.githubusercontent.com/assets/3862330/9566283/eecb71e4-4eff-11e5-9944-84e122b6a638.png)

**Comment by davivel** [comment]
This issue is solved in PR https://github.com/owncloud/android/pull/1122

**Comment by AndyScherzinger** [comment]
If #1122 fixes the issue shouldn't this issue be closed, since the PR has already been merged into master?

**Comment by davivel** [comment]
Right. Thanks, @AndyScherzinger

**Comment by AndyScherzinger** [comment]
you are welcome :)
