### ISSUE TITLE
Contacts and Calender syncing In-App

### ISSUE THREAD

**Issue by Crasha** [owncloud/android#1121]
This would be a great feature - Syncing the local Calender/Contacts with your OwnCloud account if the app is enabled on the server. This would be a great because I'm sure other people, and not just my self, don't like the idea of downloading third-party applications and would rather prefer an original app from OwnCloud for dealing with sensitive information like this.

I know Google use multiple applications, so I'm sure someone will come up with an idea whether to either have an application that does everything (aka OwnCloud), or split it into different apps from OwnCloud, e.g OwnCloud Contacts, OwnCloud Calender, etc.

**Comment by JasperWeiss** [comment]
contacts and calendar sync would be absolutely awesome! I've been using cyanogenmod without Gapps and my main problem is syncing things like these. Material design would also be a welcome change btw :)

**Comment by hitam4450** [comment]
Definitely a 'must have' feature for future (next ??) release!

regards, hitam4450

**Comment by masensio** [comment]
Hi @Crasha, @JasperWeiss, @hitam4450,

thanks for your suggestions. This issue is already in the repo: https://github.com/owncloud/android/issues/58

So I'll close this issue. Please track it there.
