### ISSUE TITLE
"Feature request: "Open [with default]" instead of only "Open with..."

### ISSUE THREAD

**Issue by WorldsEndless** [owncloud/android#1123]
I primarily use the android app to read PDFs that I store on ownCloud, but I have to select "Adobe Reader" every single time. The regular "open with... [Once] [Every Time]" should be supported.

**Comment by davivel** [comment]
Should be considered. Thanks.

**Comment by hodyroff** [comment]
@michaelstingl @rperezb makese sense. Doesn't seem too difficult.

**Comment by michaelstingl** [comment]
for reference: 00006595

**Comment by sd1998** [comment]
@davigonz I would like to work on this.

**Comment by jesmrec** [comment]
Handled by the system
