### ISSUE TITLE
[Clarification request] SETUP.md instructions. /setup_env.sh: line 7: android: command not found 

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/android#1125]
I do have the ```Android Studio``` installed (but not the stand-alone tools), working with it since a while. I wanted to start OC development and followed the instructions in https://github.com/owncloud/android/blob/master/SETUP.md .

However, when running  ```./setup_env.sh gradle``` this fails on my machine in line 7 
```
/setup_env.sh: line 7: android: command not found.
```
Pls. assist, perhaps something is missing in the instructions, or not present in the PATH. If both the Android Studio and the stand-alone tools are needed, then it may be wise to add such a hint in the SETUP.md.

**Comment by Wikinaut** [comment]
a symbolic link helped ( ln -s ~/Android/Sdk/tools/android /usr/bin/android ) so that the android tool could be found via the exec path.

**Comment by tobiasKaminsky** [comment]
Or just put the ~/Android/Sdk/tools folder in PATH as there are other files that are worth having them globally available, like fastboot.
