### ISSUE TITLE
Downloads fail when server enables chunked transfer encoding

### ISSUE THREAD

**Issue by cdamken** [owncloud/android#1128]
Android client is unable to download files via the client app.
It appears that the file is downloading, but there is an issue moving it to final storage cache area.
### Log files

```
2015/08/31 09:55:11
DownloadRemoteFileOperation : Download of /folder/File_Name.rtf to /storage/emulated/0/Folder-Storage/tmp/User@server.com/folder/File_Name.rtf: Operation finished with HTTP status code 200 (success)

2015/08/31 09:55:11
DownloadFileOperation : Download of /folder/File_Name.rtf to /storage/emulated/0/Folder-Storage/User@server.com/folder/File_Name.rtf: Error while moving file to final directory
```

@MorrisJobke 
@davivel 

00003751

**Comment by cdamken** [comment]
@davivel Client 1.7.2 in Android 4.4 and 5.02

**Comment by davivel** [comment]
@cdamken, what device models are reproducing the error?

**Comment by davivel** [comment]
OK, I debugged with the server and the problem is not related to the device. The error about but move is a side effect of cleaning up the temporary file.

The actual problem is caused because that server has enabled (or enforced) chunked transfer encoding. The Android app does not support chunked encoding in downloads.

If downloads were working before, that means that probably something was changed in the server configuration. Is it possible to revert it to the previous state?

**Comment by davivel** [comment]
So, they reverted the configuration change and everything keeps working.

But, we should support this header. Now with a more relaxed priority. Keeping open.

**Comment by cdamken** [comment]
@davivel Thanks a lot!

**Comment by felixboehm** [comment]
We have a workaround, but need to fix this sometime.
@MTRichards Please provide a milestone.

**Comment by AndyScherzinger** [comment]
@davivel junking should be something being part of HTTP 1.1 thus would need to be covered by the HTTP-Client in our case the apache lib (I think), which until the Android 23 branch is merges will be different on some Android versions, brands, etc. 
So not the urgent matter.

**Comment by MTRichards** [comment]
@davivel Something for the backlog.

Seems we can live without it for a while, but schedule it in a later sprint. No milestone in site.

**Comment by bboule** [comment]
@felixboehm maybe we can discuss the urgency from the filed?

**Comment by cdamken** [comment]
@MTRichards Can we add this in a milestone?

**Comment by MTRichards** [comment]
@davivel would like your input.

**Comment by davivel** [comment]
Sorry, I overlooked last comments. 

Requires some changes in the download operation, but it's well located and quite contained, probably will only affect the OC Android library. See no problem to add it to the next release (temptative: 2.0.1)

**Comment by asperon** [comment]
This is still a issue, will the fix be added in the next release?

**Comment by rperezb** [comment]
@davivel does it make to add this bug fixed to the next version, 2.0.1 ?

**Comment by davivel** [comment]
Sorry, this is not fixed yet. I'm afraid we overlooked it.

**Comment by rperezb** [comment]
@davivel no problem, we will include it within the next version, just added to the milestone so that we don't miss it

**Comment by davivel** [comment]
I'll move it into 'backlog' pipeline to increase its visibility

**Comment by davivel** [comment]
I'm very sorry to say this will have to be delayed one release. See more details in https://github.com/owncloud/android/issues/1750#issuecomment-236118517

**Comment by davivel** [comment]
Blocked again, test server is not compliant to HTTP 1.1 RFC; waiting feedback from owner.

**Comment by josh4trunks** [comment]
@davivel is there anything I could do to help? I have a nextcloud 10 instance where I can turn chunked encoding on/off and can create a test account for you.
Or I could create an owncloud 9.1 instance as well with chunked encoding enabled if that is needed.

**Comment by davivel** [comment]
@josh4trunks , that would be awesome :) . Please, send the test account to apps@owncloud.com, including in the subject the text "android#1128" .

An ownCloud 9.1 instance would be preferable to prevent that possible differences in the fork could interfere. 

We will upload an APK with the potential fix, if you wish, so that you can test also in any server you like :)

**Comment by josh4trunks** [comment]
@davivel I sent the test account for an owncloud 9.1.2 instance. It uses an apache24 server, with a varnish proxy in front of it that gzips objects with a content-type of **text** or **application**.

**Comment by davivel** [comment]
Thank you so much, @josh4trunks . I'll give it a try.

**Comment by davivel** [comment]
@josh4trunks , sorry, but it's not working as I would expect.  In my tests, the 'transfer-encoding:chunked' header is included, but then the stream is not really chunked. This makes the network library fail, when it tries to read the size of the first chunk, there is no size to read.

Would be possible to keep streaming enabled in your proxy but gzip disabled?

**Comment by davivel** [comment]
This could be a problem with Varnish configuration: http://stackoverflow.com/questions/23643233/how-do-i-disable-transfer-encoding-chunked-encoding-in-varnish

**Comment by josh4trunks** [comment]
@davivel That is what I mentioned at the end here https://github.com/owncloud/android/issues/1128#issuecomment-266317975
If I disable streaming whenever I enable streaming the android app works fine.
```
beresp.do_gzip = true
beresp.do_stream = false
```

When I have more time I can try finding a configuration that gives us `transfer-encoding:chunked` without gzip if you think that will lead us anywhere.
Another idea I have is to test large PDF/text files. Are these actually chunked?

**Comment by davivel** [comment]
OK, after thinking about it, I guess we can do the download really, really robust, even for the case of these proxys / servers "offending" HTTP. And probably add support for gzip mode at the same time.

But, not for the upcoming version.

So, I'll move this issue once again for the next release. I'm very sorry, but currently seem there is no a great hurry for getting this fixed in terms of number of people waiting for it. It's not easy at all to have a correct OC server configuration that results in chunked downloads.

But it's the top in my personal list for 2.3.0.

**Comment by josh4trunks** [comment]
sounds good thanks for the look. I can use the configuration above for now.

**Comment by davivel** [comment]
Sorry, but we need to drop issues from milestone 2.4.0 to get it out next to OC 10 server.

This time we'll move topics to ```backlog``` instead of directly to next release, so that we can schedule 2.5.0 properly.

**Comment by rpcameron** [comment]
Is there any activity on this? The HTTP spec requires support for chunked downloads, and until this is fixed the app is useless for many users. (OpenBSD httpd enables chunked-encoding and it cannot be disabled. On the Nextcloud/android repo there is a patch for httpd to disable chunked-encoding, but I'm not going to modify my system software to fix a bug that exists in third-party software.)

This bug has been around for seemingly forever, and postponed just as long. The HTTP spec requires support for chunked downloads, but it appears that the Android library used does not. Until the library is fixed I have to resort to other clients, but other users aren't savvy enough to understand why they can't use an Owncloud app to access their Owncloud files.

**Comment by guruz** [comment]
@rpcameron See the linked stackoverflow:

 _and adding Transfer-Encoding: chunked to the response. (Interestingly, the payload doesn't appear to have any chunks in it - it's one contiguous payload)._

Sounds quite bogus.

Or are you saying you have issues even when not using Varnish?

**Comment by rpcameron** [comment]
@guruz What linked stackoverflow?

And no, I am not using Varnish. OpenBSD httpd sets chunked encoding, but owncloud cannot handle it. The HTTP spec says that clients must parse and decode chunked encoding, and owncloud does not.

I am not using any additional software, except the occasional use of relayd for reverse proxy.

**Comment by rpcameron** [comment]
For those still following this issue, the latest dev build of the Nextcloud client seems to have finally addressed this issue to allow downloading of encoding=chunked files, just as the HTTP spec requires.

**Comment by michaelstingl** [comment]
@cdamken In version 2.9, the ownCloud Android app switched to a new networking library. I'd assume this issue is gone. Could you try again?

**Comment by cdamken** [comment]
Sorry, I didn't write before, I tested with the branded client and works perfectly.
