### ISSUE TITLE
Consider creating a more open review process

### ISSUE THREAD

**Issue by strugee** [owncloud/android#1130]
Obviously I'm not a core contributor, so feel free to disagree, but it seems like one of the biggest things holding this project back is lack of manpower. In particular, lack of manpower to review PRs.

I think that it might be a good idea for the Android team (which is mostly @davivel, AFAICT) to create a well-defined set of review guidelines that were clear to the point where a) some random contributor could self-review, thus reducing the cycles needed to get their PR merged, and b) community contributors like @tobiasKaminsky could review PRs, too.

If we had more people reviewing, it'd probably help a lot with the current "huge PR backlog" situation.

See also #1067

**Comment by tobiasKaminsky** [comment]
This is a very good idea I think.
At least code formatting review can be done by all.
So we could add a new label: "ready for community review"
And this community review should be done by at least 2 persons.
After this review the label can change to "ready for review".

With these new labels the workflow can be described by labels as followed:
0 - Backlog
1 - Working
2 - Ready for community review
3 - Ready for review
4 - Ready for QA
5 - Approved by QA
After that: Remove labels and close issue

If @davivel agree we can collect in this issue the review guidelines?

**Comment by rperezb** [comment]
Thanks for the suggestions.

I have created new labels, mostly following the ones that are used on the core repo

0 - Backlog
1 - To develop
2 - Developing
3 - To Review
4 - To release

We do have also the Ready To Test, this I would say that it would be great to be used once the code has been reviewed and then we have the QA approved, which it´s mostly the "To release" one, isn't it?

@cmonteroluque your input it´s appreciated

**Comment by tobiasKaminsky** [comment]
Although it is not the same as /core I would suggest to add the "ready to test" as 4 and when QA is finished go to "to release".
Then we would have an exact order and it is easier to find the labels as they are in the correct order on top of the list.

**Comment by tobiasKaminsky** [comment]
Great, someone added "4 - ready to test" :+1: 

Next step would be to collect guidelines for reviewing process, or? (maybe in a new issue)

**Comment by cmonteroluque** [comment]
@rperezb backlog should be a milestone, not a label, to match the other repositories.

**Comment by rperezb** [comment]
@tobiasKaminsky yes, I did it :), let´s leave open this issue till the reviewing process is updated, I will take care of in the following days
@cmonteroluque I have created the milestone as well as updated accordingly the iOS repo
