### ISSUE TITLE
Sync Account in Android

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1137]
As an ownCloud user, I want a sync now button so that I can quickly and easily ensure that my files are up to date on my mobile device for the entire account.

Acceptance Criteria:
- A sync now button is available at the top right (next to the +) - could look like a stick version of this:
  sync
- When pressed, sync now refreshes the cache and syncs the folders with the server
- Sync now button can be canceled once sync now is pressed
- Sync now button only syncs the current account, not all accounts
- If sync now blocks the client, a “working” icon appears so that the app is not blocked (like the current loading icon for the iOS app)

**Comment by MTRichards** [comment]
This mostly exists already, we just need to add the sync folder option.

**Comment by jesmrec** [comment]
Done
