### ISSUE TITLE
Folder Sync User Stories

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1138]
Prerequisite:
- Gracefully handle devices out of space situation - https://github.com/owncloud/android/issues/1135

Core Stories:
- Sync folder - https://github.com/owncloud/android/issues/1136
- Sync entire account - https://github.com/owncloud/android/issues/1137
- Sync folder on wifi only - https://github.com/owncloud/android/issues/41

**Comment by davivel** [comment]
More recent discussion in #1677
