### ISSUE TITLE
Master build broken

### ISSUE THREAD

**Issue by AndyScherzinger** [owncloud/android#1140]
After pulling the latest master to my branches I realized the code won't compile anymore and that this also applies for the master branch due to a missing string value: error_cant_bind_to_operations_service

ping to @davivel and @masensio since I don't know what value needs to be put in or put back in. For now I added a dummy to my material branch, see https://github.com/owncloud/android/commit/b1f6b5ec4a45ab1da3f50da940315ed99d4d8b75 to avoid the compile error, see 

/home/travis/build/owncloud/android/src/com/owncloud/android/authentication/AuthenticatorActivity.java:228: error: cannot find symbol -->             R.string.error_cant_bind_to_operations_service

in travis: https://travis-ci.org/owncloud/android/builds/79025877

**Comment by davivel** [comment]
Researching. Thanks, @AndyScherzinger

**Comment by davivel** [comment]
Fixed in https://github.com/owncloud/android/commit/1ff57e0665f138f6558750928012bc0809e52ed0

We overlooked some strings accidentally removed in the branch of the copy operation, but the build didn't fail until the translation strings were updated from Transifex.
