### ISSUE TITLE
Reduce the amount of exported activites

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/android#1145]
Would it be possible to limit the amount of exported activities? I do get a lot of reports about this though the security impact is arguably discussable.

```
dz> run app.activity.info -a com.owncloud.android
Package: com.owncloud.android
  com.owncloud.android.ui.activity.FileDisplayActivity
    Permission: null
  com.owncloud.android.ui.activity.Uploader
    Permission: null
  com.owncloud.android.authentication.AuthenticatorActivity
    Permission: null
```

**Comment by tobiasKaminsky** [comment]
May I ask what the purpose of the reduce can be?

**Comment by davivel** [comment]
Is that the full list of exported activities?

In that case, the naswer is "no". The three of them are valid entry points to the app:

 ```com.owncloud.android.ui.activity.FileDisplayActivity``` -> from the app icon or notification bar ;
 ```com.owncloud.android.ui.activity.Uploader``` -> from other apps sending files to upload ;
 ```com.owncloud.android.authentication.AuthenticatorActivity```-> from device settings > Accounts > Add account > ownCloud .

We could group the first two in a single one, and then redirect to the other depending on the received ```Intent```, but sounds tricky and artificial for an Android app.
