### ISSUE TITLE
Integrate server address

### ISSUE THREAD

**Issue by sniperkiki** [owncloud/android#1151]
Hello,

How would it be possible to integrate Server address already in application, so the client doesn't need to type address, he only needs to login?

Thanks

**Comment by masensio** [comment]
Hi @sniperkiki,

Thanks for using OwnCloud.

I have a doubt related with your question, are you trying to generate an APK form the project code or do you want to integrate Server address in  an app from the market?

If you are trying to integrate Server address directly in an installed app, the answer is no. You can't   integrate the Server address in an installed app.
But if you need to integrate the address and generate by yourself the apk, you can define de address in the setup.xml file and generate your apk.

I hope this answer helps you. :)

**Comment by sniperkiki** [comment]
That is exactly what I was looking for!

Thanks so much :)


Sent by Outlook for Android





On Mon, Sep 14, 2015 at 5:23 AM -0700, "masensio" <notifications@github.com> wrote:
Hi @sniperkiki,

Thanks for using OwnCloud.

I have a doubt related with your question, are you trying to generate an APK form the project code or do you want to integrate Server address in  an app from the market?

If you are trying to integrate Server address directly in an installed app, the answer is no. You can't   integrate the Server address in an installed app.
But if you need to integrate the address and generate by yourself the apk, you can define de address in the setup.xml file and generate your apk.

I hope this answer helps you. :)


---

**Comment by masensio** [comment]
You are welcome. 

I understand that this fix your problem, so I'll close the issue.
