### ISSUE TITLE
Setup Guide -  fatal: A branch named 'master' already exists.

### ISSUE THREAD

**Issue by sudhirkhanger** [owncloud/android#1152]
I am get `fatal: A branch named 'master' already exists.` when I run `git checkout -b master remotes/origin/master` from step 1 of [setup guide][1].

[1]: https://github.com/owncloud/android/blob/master/SETUP.md

**Comment by gallardo** [comment]
The
> Checkout the remote branch 'master' in your own local branch 'master': `git checkout -b master remotes/origin/master`.

step in the [SETUP.md]( https://github.com/owncloud/android/blob/master/SETUP.md#1-fork-and-download-the-owncloudandroid-repository) instructions seems definitely wrong: why `-b` (create new branch)? I guess `-t` (track) was meant.

**Comment by gallardo** [comment]
I'm sorry, I too fast deleted my previous suggestion thinking for a second that I was wrong. According to the instructions, you're cloning a repository that already has a `master` branch. You probably want to track (`-t`), instead of create (`-b`) the branch.

NB.- `-b` would be appropriate if you init your repository, add the remote, fetch the remote and want to checkout master.

**Comment by sudhirkhanger** [comment]
@tobiasKaminsky mentioned in the irc that I should try `git checkout master`.

**Comment by masensio** [comment]
Hi @sudhirkhanger,

Thank you for your warning about this line in the setup guide.
You can use directly ```git checkout master ``` (as @tobiasKaminsky  suggested)

I'll update the setup guide.

Sorry for the inconvenience.

**Comment by davivel** [comment]
Done.

Thanks, @sudhirkhanger , for the tip.

**Comment by sudhirkhanger** [comment]
@davivel `git checkout -b master remotes/origin/master` has been changed to `git checkout master remotes/origin/master` which gives an error `error: pathspec 'remotes/origin/master' did not match any file(s) known to git`. The correct command being `git checkout master `.

**Comment by masensio** [comment]
Hi @sudhirkhanger,

setup guide is updated with your fix (you can see https://github.com/owncloud/android/pull/1155)

Thanks for your tip :)

**Comment by sudhirkhanger** [comment]
@masensio I am seeing you have changed

`git checkout -b master remotes/origin/master`

to

`git checkout master remotes/origin/master`

which gives following error

`error: pathspec 'remotes/origin/master' did not match any file(s) known to git`

According to @tobiasKaminsky it should be changed to

`git checkout master`

**Comment by tobiasKaminsky** [comment]
As far as I understand 
git checkout master remotes/origin/master
can be omitted as the master is the same as origin/master:

$git branch -v -a
master                                                                  a8d55d0 Fixed range of valid versions to install
  remotes/origin/HEAD                                                     -> origin/master
  remotes/origin/master                                                   a8d55d0 Fixed range of valid versions to install

**Comment by sudhirkhanger** [comment]
@tobiasKaminsky Can you please reopen the issue so that it can get fixed?

**Comment by tobiasKaminsky** [comment]
@davivel please check and change it? :)

**Comment by sudhirkhanger** [comment]
Can we have the instructions updated?
