### ISSUE TITLE
Enhansment sugusstion (upload)

### ISSUE THREAD

**Issue by Jbeatie** [owncloud/android#1158]
I have been using owncloud for 9 months or so. Owncloud  uploads all pictures and video to my server from the /sdcard/DCIM. Other applications place pictures in /sdcard/DCIM  also like Tasker and some others. Would others users like the option to auto upload other directory on the phone or even include sub directories?

Thanks you  for considering.
-Jay

**Comment by tobiasKaminsky** [comment]
This is handled by #1059?
If so, please close this issue.

**Comment by Jbeatie** [comment]
Looks like it is. Thanks !
