### ISSUE TITLE
Notification bar: Show remaining time and speed

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1159]
During upload or download the file a progress bar is displayed in the notification area (pull down menu).
For big files a remaining time and the current speed should be displayed.

**Comment by davivel** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
I’d say remaining time should work for now. Current speed is very technical info and we do not have a lot of space for that.

**Comment by tobiasKaminsky** [comment]
Remaining time is really enough as you said :)

**Comment by davivel** [comment]
Closing as included in #1468
