### ISSUE TITLE
Refresh icon/action on URL textfield

### ISSUE THREAD

**Issue by AndyScherzinger** [owncloud/android#1160]
With the new (material design) implementation buttons can't simply bind java methods via configuration anymore but need to do this is the way we already did it except for one instance in the login screen, when you hit the refresh button (for example when you entered an invalid owncloud url).

Bug number 2 (I know this should be separated..) is a UI glitch, or rather two on the login screen:
* the refresh button is oversized in the landscape mode
* the hint text has a size glitch when you refresh on an invalid address (spinning icon Vs. warning icon)

Unfortunately I don't have the time now to fork/PR but I have the fix already on the other branches for #1090 and #1100 

e.g.
https://github.com/owncloud/android/commit/044c597e2bf81c40340a9e43bcb9c965d4792dbd
https://github.com/owncloud/android/commit/549284e4f97481b3bcffb2528925fc28525ff9cf
https://github.com/owncloud/android/commit/d78077de4da35f0104457c60675421c3f01ba396

hopefully I will find the time to open up a PR tomorrow. 

**Update**
The crash bug isn't present on 1.8/master just on my feature branches. The remaining two issues have been fixed on PR #1163

**Comment by AndyScherzinger** [comment]
imho closed since #1163 has been merged. @masensio @davivel

**Comment by davivel** [comment]
:+1:
