### ISSUE TITLE
Resume download if current download aborts

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1161]
Steps to reproduce:
- Download very big file over wlan
- toggle wlan
- download aborts 
- restart download manually -> download starts from beginning

instead the app should either
- try to download file again
- resume download and not begin with 0%

**Comment by davivel** [comment]
Please, don't start working on this for the moment. We will have time to provide more details on it after the release of https://github.com/owncloud/android/milestones

Thanks.

**Comment by jesmrec** [comment]
to do in https://github.com/owncloud/android/issues/3222
