### ISSUE TITLE
Comment negative ratings on play store

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1164]
There are a lot of "does not work for me" comments on the play store.
Maybe it would be a good idea to write those people and invite them to either
- use the forum
- report an issue here
- irc

As far as I see this, our app is working fine, but there can be a lot of problems as the user can manage their own server...

**Comment by rperezb** [comment]
@tobiasKaminsky thanks for your concern.

Yes, sometimes, the eror doesn't rely on the Android app itself but on the server configuration.  

First step, I'd suggest to add these ideas to the app description, what do you think?

@MTRichards @jospoortvliet would this work?

**Comment by MTRichards** [comment]
Good idea, as a lot of this is user configuration error. I would point them to github here for error reporting.

**Comment by jospoortvliet** [comment]
agreed.

**Comment by tobiasKaminsky** [comment]
Then we need to decide, when this "error reporting" dialog should be displayed.
First it should be shown in the navigation drawer to get it more aware by the user?
Then it should be shown if certain functions fail: log in, upload(?), download(?), empty directories(?)

@jancborchardt @davivel

**Comment by jancborchardt** [comment]
Yeah, good point to show an issue reporting link when functions fail. This is also done by Chrome, Firefox etc when the app crashes – you can send feedback there.

@rperezb @MTRichards but we should really actually go in there and write to these people, at least the ones rating 1 star only. Putting it in the app description is not going to help much because people do not read that.

**Comment by MTRichards** [comment]
I think we only can write to the Android ones. The iOS ones we can't, we don't get the details.

**Comment by tobiasKaminsky** [comment]
A good point would be #1165 to get better feedback without having experienced/advanced user.

**Comment by davivel** [comment]
> Yeah, good point to show an issue reporting link when functions fail. This is also done by Chrome, Firefox etc when the app crashes – you can send feedback there.

That's an automatic operation for apps installed from Play Store. It's already working for the OC app. When users decide to send a crash report, we can see it in the Play Store developer console. We already monitor from time to time those crashes, and fix those that grow in numbers in a meaningful way.

> Then we need to decide, when this "error reporting" dialog should be displayed.
First it should be shown in the navigation drawer to get it more aware by the user?
Then it should be shown if certain functions fail: log in, upload(?), download(?), empty directories(?)

None of them, in my opinion. Will be to intrusive. Many bugs appear several time on retries. Showing a dialog each time to send a report will be too annoying.

There are over 250 issues in this repository , 1 year ago it was around 100. There are 35 pending pull requests. There are over 100.000 installations of the app from Play Store. We are not going to improve the app inviting more people to file their individual problems in our system. 

There are already 60 bugs in this repository, most of them unattended (see https://github.com/owncloud/android/issues?q=is%3Aopen+is%3Aissue+label%3Abug). Let's put more time in fixing them, not more time in pruning new bugs.

We are few people. We won't improve the impression about the app for 100.000 users trying to fix their individual problems one at a time. We will do if we improve the overall quality of the app in its main features.

There will always be bugs, and there will always be bad reviews. Angry users tend to review much more than happy users. Watch the current rating of the app in the store, 3.7. It's the highest the app ever had. 

IMHO.

**Comment by tobiasKaminsky** [comment]
My intention for this was to get a better understanding what is not working and try to fix this.
Maybe it is most a misconfigured server and then this could be fixed by a better manual or a smarter config check.
But you are right that this would lead to much more user feedback, that needs to be handled.

**Comment by tobiasKaminsky** [comment]
Maybe it is a good idea to direct these users to the forum? And only if the user there confirm that it is a bug they should report it here.
With this approach the workload "here" is only a little higher, but the users get support.

**Comment by jospoortvliet** [comment]
@tobiasKaminsky yeah, that is something we could add to the description of the Android app - link to the forum for questions.

**Comment by rperezb** [comment]
Added this to the description:

Should you have any problem connecting or synchronizing with your ownCloud server, please contact us on github.com/owncloud/android/issues or check https://forum.owncloud.org/.

It will be available in some hours

**Comment by jospoortvliet** [comment]
Awesome!

Tobias, given this seems the best we can realistically do right now, you OK closing this issue?

**Comment by tobiasKaminsky** [comment]
As a lot of german users are around (I suppose so), it also should be in german:
Sollten Verbindungsprobleme oder Synchronisationsfehler mit Ihrem privaten Owncloud-Server auftreten, können Sie uns über http://github.com/owncloud/android/issues (englisch) oder 
https://forum.owncloud.org (deutsch & englisch) erreichen.

And the github.com should be a link, that it is easier to click.

**Comment by rperezb** [comment]
Thanks @tobiasKaminsky !
I asked for it to another ownCloud colleague, since, it has not arrived it yet, I have used yours.
Besides, I have updated the github link
Both will be available within hours,
I close it, if needed, please reopen
