### ISSUE TITLE
Implement functionality check

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1165]
Due to the fact that everyone can manage their own server, it is often hard to find why some things do not work.
Maybe it is a good idea to implement a functionality check with (not complete)
- login
- thumbnails
- upload dummy file
- move dummy file
- and so on

This could be done with a verbose log, which can then be posted directly here, if there is a problem.
(And of course present a link to github issue tracker)

**Comment by davivel** [comment]
The ownCloud Android app is not the best tool to validate server installations.

Sorry, will not go in.
