### ISSUE TITLE
problem with Error:Configuration with name 'default' not found in android std

### ISSUE THREAD

**Issue by sunftec** [owncloud/android#1170]
hi mR
tanks you for this,
i have a problem with 

Error:Configuration with name 'default' not found.

in grdl

**Comment by tobiasKaminsky** [comment]
Have you followed the guide correctly?
Do you run ./setup_env.sh gradle && ./gradlew clean build?

Please provide more infos.

**Comment by nawarhashem** [comment]
I did all the steps, the same problem is with me. I can't even run the program. The green play icon is grey and disabled.

**Comment by aario** [comment]
Hi,
Sorry if I'm out of sync with this project. I have the same problem. Here are my questions:
Where is the "guide"?
Where is setup_env.sh file?

**Comment by davivel** [comment]
@sunftec , @nawarhashem , @aario , is this still a problem for any of you?

Thanks.

**Comment by davivel** [comment]
Please, tell me if this needs to be reopened. Thanks.
