### ISSUE TITLE
Compile error using Eclipse

### ISSUE THREAD

**Issue by asyougo** [owncloud/android#1172]
When I try to set up the owncloud androud project, I failed to compile it.
I have following errors.
![image](https://cloud.githubusercontent.com/assets/7529885/10036390/be22b3bc-61d9-11e5-9899-0996491cc627.png)
![image](https://cloud.githubusercontent.com/assets/7529885/10036396/d3b4cf62-61d9-11e5-8305-ceafa7673e2b.png)
Hope for solution!

**Comment by tobiasKaminsky** [comment]
Eclipse is not maintained any longer by Google for building android apps.
Therefore I recommend Android Studio.

Beside that: the red exclamation mark indicates that there is a problem with the build path.
But I cannot identify the error in values-bal/strings.xml...

**Comment by MadWhale** [comment]
I have the same issue.

**Comment by asyougo** [comment]
I have solved this problem. My solution is deleting "values-bal" and “values-tzl" folders under "res". I speculate that some abbreviations of languages are not recognized by Eclipse for some reason.

**Comment by rperezb** [comment]
@MadWhale please, check @asyougo solution, if this didn't fix it, please reopen this issue and add further details
