### ISSUE TITLE
As an OC user I want to SHARE VIA LINK with password protection and expiration time using the new interface so that I can secure my shared files

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1178]
AC:
- New interface -> https://github.com/owncloud/ios/issues/425
- Keep the current options of Share link (apps to share and unshare)
- The interface should be updated with the server data
- Possibilities of enable/disable password protection.
- Possibilities of enable/disable and change the expiration time

NOTE:
This is related to: https://github.com/owncloud/ios/issues/425
This is the first step to be able to share with users since we are developing the new view

**Comment by godfuture** [comment]
Is it possible to provide options according the webinterface? There is for example "allow public upload" or "show gallery link" from galleryplus app.

**Comment by rperezb** [comment]
@godfuture thanks for the suggestion. Sure, the idea is to first add this two options and then other ones, can you please, open this requirement as a new issue so that it can be tracked?
thx

**Comment by davivel** [comment]
Work in progress in https://github.com/owncloud/android/tree/share_with_password_and_expiration_time

**Comment by davivel** [comment]
![share01](https://cloud.githubusercontent.com/assets/2225614/10968343/d1fcc36a-83c0-11e5-886f-f474a92858b7.jpg)
![share02](https://cloud.githubusercontent.com/assets/2225614/10968345/d3473c14-83c0-11e5-9b95-2b016c1293a9.png)

Screenshots of work in progress.

Password working now. Next: expiration time.

**Comment by davivel** [comment]
With the current schedule there is no way we can have this done for https://github.com/owncloud/android/milestones/1.9-current .

Moving to next release.

cc @rperezb , @MTRichards , @cmonteroluque

**Comment by tobiasKaminsky** [comment]
@davivel 
This is working in 1.9?
Great job! :+1:

**Comment by masensio** [comment]
This issue is included in 1.9 version of the app.
Next step: manage share with privileges :)

**Comment by AndyScherzinger** [comment]
@masensio shouldn't the milestone assigned be 1.9 instead of 1.9.1 ? Just asking :)

**Comment by rperezb** [comment]
Thanks @AndyScherzinger, fixed
