### ISSUE TITLE
Playing videos does not work

### ISSUE THREAD

**Issue by cdamken** [owncloud/android#1180]
### Expected behaivor
I trying .mkv, .mpg and .mp4 and they all work.

### Actual behavior
I trying .mkv, .mpg and .mp4 and they all don' t work.

### Device
Nexus 7 tablet with android 5.0.
For example: this video doesn't work.

### Client version
1.7.2

### Example video and Log files in:

S3-ownCloud\Shared\owncloud\support\github-issues\android\1180

### Questions

Which video's does the in app video player of the android app support?

Would it be possible to open files from the ownCloud app in the normal video player of a smartphone?

@MorrisJobke

00003861

**Comment by cdamken** [comment]
I tested in my phone with android 5 and works:

![screenshot_2015-09-28-19-03-35](https://cloud.githubusercontent.com/assets/7264495/10197715/3ab4d5c6-6799-11e5-9119-3d0c4047c013.png)

@davivel @rperezb Let me know if you need more info

**Comment by tobiasKaminsky** [comment]
Can you make the video public so that it can be tested on other devices?

**Comment by rperezb** [comment]
@cdamken is the video in question previewed by device? 
I mean, access to the file manager, browse to the ownCloud folder and to the path where the video is stored, open it, is it played?
thx

**Comment by cdamken** [comment]
I'll ask

**Comment by cdamken** [comment]
@tobiasKaminsky It does not work with any video, no need to have any special for testing

**Comment by cdamken** [comment]
@rperezb There is indeed a thumbnail when using ES file explorer.

**Comment by tobiasKaminsky** [comment]
@cdamken The question of @rperezb was, if any other video player on your device can play the file in question?
You can browse to the file in owncloud and do "open with" via long-press.

**Comment by cdamken** [comment]
@tobiasKaminsky 
> Can you make the video public so that it can be tested on other devices?

https://cloud.damken.com/index.php/s/NveX5BYVLjy8zkd
password: carlos

> if any other video player on your device can play the file in question?
> You can browse to the file in owncloud and do "open with" via long-press.


I will ask that question again. Thanks!

**Comment by tobiasKaminsky** [comment]
For my Nexus4 I cannot play it with the owncloud video player but with VLC.

```
10-07 22:54:34.443 11682-11682/com.owncloud.android E/PreviewMediaFragment: onCreateView
10-07 22:54:34.466 11682-11682/com.owncloud.android E/PreviewMediaFragment: onActivityCreated
10-07 22:54:34.470 11682-11682/com.owncloud.android E/PreviewMediaFragment: onStart
10-07 22:54:34.477 11682-11682/com.owncloud.android E/PreviewMediaFragment: onResume
10-07 22:54:34.533 11682-11682/com.owncloud.android I/VideoView: Open Video
10-07 22:54:34.538 11682-11682/com.owncloud.android E/ExtMediaPlayer-JNI: QCMediaPlayer could not be located....
10-07 22:54:34.538 11682-11682/com.owncloud.android E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
10-07 22:54:34.538 11682-11682/com.owncloud.android I/VideoView: SetDataSource
10-07 22:54:34.538 11682-11682/com.owncloud.android D/MediaPlayer: Couldn't open file on client side, trying server side
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView: Unable to open content: %2Fstorage%2Femulated%2F0%2Fowncloud%2Ftobi%40www.domain.de%252Fowncloud%2Ftemp%2FSample_512kb.mp4
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView: java.io.IOException: setDataSource failed.
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1105)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1079)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1033)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.widget.VideoView.openVideo(VideoView.java:360)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.widget.VideoView.access$2200(VideoView.java:72)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.widget.VideoView$7.surfaceCreated(VideoView.java:671)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.Choreographer.doFrame(Choreographer.java:550)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.os.Handler.handleCallback(Handler.java:739)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.os.Looper.loop(Looper.java:135)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at android.app.ActivityThread.main(ActivityThread.java:5294)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at java.lang.reflect.Method.invoke(Native Method)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at java.lang.reflect.Method.invoke(Method.java:372)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
10-07 22:54:34.540 11682-11682/com.owncloud.android W/VideoView:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
10-07 22:54:34.541 11682-11682/com.owncloud.android D/VideoView: Error: 1,0
```

**Comment by cdamken** [comment]
It is playing on a sony xperia z3
It is not playing on Nexus 7 tablet. 

Still waiting for the answers of the questions of @rperezb

**Comment by cdamken** [comment]
@tobiasKaminsky @rperezb About the video: Yes, I can view it through the regular player on the tablet.

**Comment by cdamken** [comment]
@rperezb Any news?

**Comment by rperezb** [comment]
@cdamken not yet, as @MTRichards said some weeks ago, we are fully focus on sharing and favorite folder, 
I have been able to reproduce this error too... as @tobiasKaminsky 

We will check this after finishing the compromissed features.

thx

**Comment by davivel** [comment]
This just came to top priority.

@tobiasKaminsky , did you make any work of it, apart of reproducing the bug? If you don't tell me otherwise, I'll start debugging it.

**Comment by rperezb** [comment]
@davivel you are on "developing" mode :smile:

**Comment by davivel** [comment]
Yes, in the tunnel ;-)

**Comment by tobiasKaminsky** [comment]
@davivel I have only reproduced it.
You are just trying to fix the playback of downloaded videos?
In #1236 I have added support of streaming videos/audio.

**Comment by davivel** [comment]
Just downloaded, strictly the bug reported. I'm really sorry, I'd wish to have the time to check all the work you are doing in your PRs, but I need to be fully focused in "my own stuff" for some more days. Mid November is the date to get.

**Comment by davivel** [comment]
Fixed in https://github.com/owncloud/android/pull/1269

**Comment by masensio** [comment]
https://github.com/owncloud/android/pull/1269 is merged in master branch.

**Comment by davivel** [comment]
cc @cdamken
