### ISSUE TITLE
[Grid View] Video should not show file name

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1181]
![video](https://cloud.githubusercontent.com/assets/5836855/10201028/1e94c458-67aa-11e5-984a-e2edcf9b2206.jpg)

Currently for the video the name is shown.
I think it is sufficient to see the play button to distinguish it from an image.

Can / should I remove it?

design gurus :)
@jancborchardt 
@AndyScherzinger

**Comment by AndyScherzinger** [comment]
Imho Video should be considered as media ;) 
Thus it should be rendered the same way so no file name.

**Comment by AndyScherzinger** [comment]
@jancborchardt are you fine with the proposal and change?

**Comment by jancborchardt** [comment]
Yep! :) Good call.

**Comment by davivel** [comment]
Closing in favor of https://github.com/owncloud/android/issues/897#issuecomment-285654902
