### ISSUE TITLE
Instant_upload and multiple accounts

### ISSUE THREAD

**Issue by r2evans** [owncloud/android#1185]
Request: please make instant upload a per-account configuration.

Background: I have a personal and a company cloud configured. I cannot use federated shares. I want my pictures to always sync with my personal account and never to my work account.

Expected behavior: even if I've recently been looking in my work folder structure, new pictures should be synced to my personal account.

Actual behavior: it is synced to whichever account had been most recently opened.

(Perhaps related: does this mean that sync events only deal with "current account" and not specific accounts?)

**Comment by tobiasKaminsky** [comment]
Please see #827 
Regarding your second question: I do not know, maybe you can try it and open a new issue if necessary?
