### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by JasperWeiss** [owncloud/android#1189]
For security, I think 2FA is a must, TOTP should be sufficient. So that a compromised password isn't too big of an issue.

Also, would it be possible for the Android and Desktop clients to check the SSL certificate fingerprint?
Bassically, in the settings menu it should have a little information about the SSL certificate including the fingerprint. The app should give a warning when anything changed, that way MIT attacks are nearly impossible.

**Comment by JasperWeiss** [comment]
Especially with self signed keys it is crucial that fingerprints are checked every time the app connects.

**Comment by LukeOwncloud** [comment]
Please separate your request. One per github issue. Please open new issues. 
My thoughts anyways:
This repository is just for the Android app. 
If I remember correctly, the app did check the server certificate and warned me. Are you sure this isn't done everytime? 
What second authentication channel are you proposing?
