### ISSUE TITLE
Uploader layout & sort order should be same as for app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1193]
When uploading content from another app (like the Gallery), the uploader view looks strangely different from the normal file list.

It should have the same layout, with file/folder info below the folder names, and also the same sort order if one chose to sort by modified date.

PR: #1277 

@davivel @masensio @tobiasKaminsky @AndyScherzinger @Kernald @stoyicker

**Comment by tobiasKaminsky** [comment]
This depends on the app you choose.
We can only change the behaviour of upload -> files.

**Comment by LukeOwncloud** [comment]
I think this is about opening the gallery app, then share photo, choose owncloud app.

**Comment by AndyScherzinger** [comment]
@jancborchardt any comment/clarification? It's like @tobiasKaminsky said, the layout depends on the originating app and can't be influenced by the ownCloud app. Or do you mean @LukeOwncloud's pov about what we display in case you share, choose owncloud, etc.. ?

**Comment by jancborchardt** [comment]
Yeah, what @LukeOwncloud said. I open the Gallery app and share from there.

**Comment by AndyScherzinger** [comment]
Which would be this one? https://play.google.com/store/apps/details?id=md.steuer.mobile.owncloud_gallery.free 

Just asking so I can try I out to see what you mean :)

**Comment by jancborchardt** [comment]
The standard Android Gallery: com.android.gallery3d

**Comment by AndyScherzinger** [comment]
Aaaah..... that'll be the Uploader implementation:
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/activity/Uploader.java#L398

Screenshot (how it is now, minus the primary action coloring since I am running my branch on my phone):
![device-2015-11-09-144001](https://cloud.githubusercontent.com/assets/1315170/11035097/79e65802-86f0-11e5-8adc-ea597f72427c.png)

**Comment by AndyScherzinger** [comment]
I am willing to implement this if it is fine with you guys: @jancborchardt @davivel @masensio @tobiasKaminsky @Kernald @stoyicker

**Comment by jancborchardt** [comment]
Yep, exactly! :) Also the small text »Choose upload folder« should be moved to the header instead and replace »ownCloud«.

**Comment by AndyScherzinger** [comment]
DONE and reviewed in PR #1277 waiting for merge

**Comment by davivel** [comment]
This was merged and release.
