### ISSUE TITLE
Only use one notification

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1194]
Currently when downloading multiple files, you often end up with 2 notifications: one for the download in progress, and one for the »success« notification of the previous download:
![screenshot_2015-10-11-14-47-09](https://cloud.githubusercontent.com/assets/925062/10416295/727ae18e-706e-11e5-88f5-5eccba5e28b2.png)

When there is another download coming right after, it is unnecessary to show the success notification. An error notification when something went wrong is enough, and a summary success notification at the end (which of course vanishes like the one currently does.)

cc @davivel @masensio @AndyScherzinger @tobiasKaminsky @stoyicker

**Comment by AndyScherzinger** [comment]
I think @tobiasKaminsky already took care of this in another PR :)

**Comment by tobiasKaminsky** [comment]
No, I think you mixed it with the "wait a moment". 
In #1168 I have removed the "wait a moment" dialog for removing files as I would otherwise have to keep track of the deleted files to remove the dialog with the last file.

**Comment by davivel** [comment]
Subsumed by #1468
