### ISSUE TITLE
Android App 1.8.0 Only shows "Nothing Here... Upload something" - OwnCloud 8.1.3

### ISSUE THREAD

**Issue by Circerus** [owncloud/android#1196]
Hello.
I am having issues regarding using the android app.
I have currently installed OwnCloud 8.1.3 and trying out the Android-App.

When logging into the webconsole all files are correctly shown, but when using the Android-App it only shows the message:
"Nothing here.... Upload something".
I can create folders and upload files, but files created at the web-console is not shown.

**Comment by rperezb** [comment]
Thanks for contacting us.
Let's open up the Android wiki, can you please check up: https://github.com/owncloud/android/wiki#data-is-not-shown-after-haved-login ?
thx

**Comment by tobiasKaminsky** [comment]
This should be done by the app and report on failure that the webdav service is not configured correctly...

**Comment by Circerus** [comment]
Thank you for your replies.
The strange thing is that when enabling WiFi-connection on the android-phone everything works as normal. When setting up 4G-connection nothing refreshes..
Seems strange, but that's what I am experiencing.

**Comment by rperezb** [comment]
@Circerus are you on the same network as your server? 
Perhaps the ip is not accesible out of the network, please check it.
@tobiasKaminsky yes, you are right, this is an enhancement for the app

**Comment by Circerus** [comment]
@rperezb No, I am not at the same network as my server.
The server is located at an external location and is fully accesible from outside the network.
@tobiasKaminsky Will do that. ;)

**Comment by tobiasKaminsky** [comment]
New issue in #1201

**Comment by tobiasKaminsky** [comment]
Can you try to look into logcat, to see if there is happening something suspicious?
http://forum.xda-developers.com/showthread.php?t=1726238

**Comment by davivel** [comment]
@Circerus , is this still an issue for you? Thanks in advance.

**Comment by Circerus** [comment]
Nop. This is not a issue for me any longer

10. mar. 2017 12:51 skrev "David A. Velasco" <notifications@github.com>:

**Comment by davivel** [comment]
Thank you so much :)
