### ISSUE TITLE
Show files in uploader

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1197]
Currently when uploading files from other Android apps (like Gallery), only folders of your ownCloud show in the upload popup. But it should also show files – otherwise you might think they are gone.

@davivel @masensio @AndyScherzinger @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Please see #674 and if it is the same, please close.
PR for this would then be #821

**Comment by jancborchardt** [comment]
Right, it's the same. @davivel @masensio @rperezb the pull request #821 for that is 10 months old – we need to do better here.

Please also review #821 @AndyScherzinger @Stoyicker @Kernald
