### ISSUE TITLE
Move file size next to date instead of floating right

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1198]
Currently in the list the file size floats on the right in free space (looks especially strange for short file names).

Instead, it should just be right next to the date, separated with a comma and space from it.

**Comment by AndyScherzinger** [comment]
This has already been done in #1090 weeks ago ;)

**Comment by jancborchardt** [comment]
Should get reviewed and pulled then … @davivel @rperezb @masensio @MTRichards

**Comment by MTRichards** [comment]
Concur, needs review. Wish I could do that part...

**Comment by AndyScherzinger** [comment]
pull request had to be re created and is now part of #1209 (successor of #1090)

**Comment by davivel** [comment]
This is in, will be released in 1.9.1
