### ISSUE TITLE
New label: resolved by PR

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1202]
There are many open issues that are only open as the corresponding  PR is not yet merged.
But it is hardly to see in the issue overview.
So I suggest a new label "resolved by PR/ PR exists" or something that indicates that the issue is only open as long as the PR is not merged.
For instance: #1181

**Comment by rperezb** [comment]
What about using one of the existing ones?
For instance the same used on the pr, in this case To review
Plus, as we used to do, it would be great to comment either on the pr or on the issue: "Fixes #xxx" so that they are linked

**Comment by davivel** [comment]
Not an issue right now.
