### ISSUE TITLE
Uploader: colorify primary action

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1204]
https://github.com/owncloud/android/pull/1168#issuecomment-147176140:
Colorify primary action (upload) after #1209 is merged.

File: Uploader.java / uploader_layout.xml
Depends on: #1209, #1168 
- [x] material buttons https://github.com/owncloud/android/pull/1209
- [x] avoid duplicates https://github.com/owncloud/android/pull/1168

**Comment by masensio** [comment]
#1209  is merged on master branch.

**Comment by AndyScherzinger** [comment]
IMHO still is still an open issue that needs to be done _after_ merging both branches thus the issue would remain open and could now be done since both referenced PRs have been merged. Right @tobiasKaminsky? Or am I missing something?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I guess so.
But you are the master of design code ;)
Maybe it is in one of your other design PRs?

**Comment by tobiasKaminsky** [comment]
Uh.
Reverting all.
I have installed latest master in the emulator and in both cases (upload from within app and upload from another app) both upload buttons are blue with white text.
So this can remain closed!
