### ISSUE TITLE
Android Studio import error

### ISSUE THREAD

**Issue by lide123** [owncloud/android#1212]
Android Studio import error

![qq 20151024071550](https://cloud.githubusercontent.com/assets/10562021/10710433/87daac9e-7a8c-11e5-9d65-d57b992df185.png)

**Comment by tobiasKaminsky** [comment]
For me there is "Before launch: Gradle-aware Make" and nothing about a JDK.
Normally gradle is being used as build system and this should manage everything correct.
Have you executed: $./setup_env.sh gradle && ./gradlew clean build

**Comment by lide123** [comment]
thanks for you help.it works now.
