### ISSUE TITLE
In-progress upload notification gets frozen and can't be dismissed

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/android#1215]
Owncloud's upload will sometimes freeze in the middle of an "Instant upload" if I'm on the edge of my wifi or leaving the house. Then the notification that the upload is 55% (or whatever) just stays there as it is still uploading and it is non-dismissable. It would be nice if this uploading notification was dismissable.
If owncloud has not actually sent any data for a minute it should  queue it for later.

**Comment by LukeOwncloud** [comment]
Related to https://github.com/owncloud/android/issues/1194 (about notifications)

**Comment by davivel** [comment]
@pascalBokBok , are you still suffering this  problem?

**Comment by pascalBokBok** [comment]
I don't think so... I'll reopen if I notice it happening.

**Comment by pascalBokBok** [comment]
I can confirm that it times out and changes to an error message stating "Upload failed" with message "An error occurred while waiting for the ser..." (Can't read rest) which is dismissable :-)
My only suggestion is that the error message clarified if the image will be uploaded later.
It can be easily tested by disabling the wifi while uploading after having taken an image.

**Comment by davivel** [comment]
Thanks, @pascalBokBok . We are making many improvements in uploads right now, though not specially in notifications. There are some specific issues labelled with 'notifications', maybe you'd like to have a look there to track any progress or comment your POV.
