### ISSUE TITLE
Instantupload doesn't work with camera360

### ISSUE THREAD

**Issue by xdmx** [owncloud/android#1217]
I've the last version of both owncloud and [camera360](https://play.google.com/store/apps/details?id=vStudio.Android.Camera360) and I've noticed that when I take a picture is not automatically uploaded to my owncloud server. Photos are saves in the same folder used by the stock android camera app and from which the upload works correctly. It's just from camera360 that doesn't work

**Comment by tobiasKaminsky** [comment]
Our app listens with a broadcast receiver on these events:
android.hardware.action.NEW_PICTURE
com.android.camera.NEW_PICTURE

They should usually be send after a new image was taken. 
If this is not the case, please contact the devs of camera360 and ask them to implement this broadcast event.
You can also link them to this issue, if they need some support.

**Comment by LukeOwncloud** [comment]
There are already some issue concerning instant uploads:
https://github.com/owncloud/android/issues?q=is%3Aopen+is%3Aissue+label%3Ainstant_uploads

There is also a suggestion how to solve the problem:
https://github.com/owncloud/android/issues/744

Unfortunately no quick, one-size-fit-all solution in sight. It might be quicker to convince the camera360 to send the mentioned broadcasts (which is an Android standard -> http://developer.android.com/reference/android/hardware/Camera.html#ACTION_NEW_PICTURE)

**Comment by xdmx** [comment]
I wrote to them and their answer is:

> Thanks for your feedback and sorry for late reply, already forward your suggestion to our product manager, hope he will take it and make it works as soon as possible, thank you.

**Comment by AndyScherzinger** [comment]
Sweet, would be nice to have another camera app being supported :)

**Comment by elpraga** [comment]
I'll check the cameras I have, I had no clue it was like this..

**Comment by davivel** [comment]
Hi @all. Let's track this kind of issues in #6. And hopefully provide a solution soon.

Thanks.
