### ISSUE TITLE
Beta: Crash: SecurityException

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1225]
@tobiasKaminsky 
I just installed the new beta version -> https://github.com/owncloud/android/blob/beta/apks/owncloud-beta-2015-10-29.apk and got following exception:

	V/FileDisplayActivity(31131): onCreate() start
	D/FileDisplayActivity(31131): onCreate(Bundle) starting
	W/AccountManagerService(  530): caller uid 10088 is different than the authenticator's uid
	D/AndroidRuntime(31131): Shutting down VM
	W/dalvikvm(31131): threadid=1: thread exiting with uncaught exception (group=0x42067930)
	E/AndroidRuntime(31131): FATAL EXCEPTION: main
	E/AndroidRuntime(31131): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.SecurityException: caller uid 10088 is different than the authenticator's uid
	E/AndroidRuntime(31131):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
	E/AndroidRuntime(31131):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
	E/AndroidRuntime(31131):        at android.app.ActivityThread.access$600(ActivityThread.java:141)
	E/AndroidRuntime(31131):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
	E/AndroidRuntime(31131):        at android.os.Handler.dispatchMessage(Handler.java:99)
	E/AndroidRuntime(31131):        at android.os.Looper.loop(Looper.java:137)
	E/AndroidRuntime(31131):        at android.app.ActivityThread.main(ActivityThread.java:5041)
	E/AndroidRuntime(31131):        at java.lang.reflect.Method.invokeNative(Native Method)
	E/AndroidRuntime(31131):        at java.lang.reflect.Method.invoke(Method.java:511)
	E/AndroidRuntime(31131):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	E/AndroidRuntime(31131):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	E/AndroidRuntime(31131):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	E/AndroidRuntime(31131):        at dalvik.system.NativeStart.main(Native Method)
	E/AndroidRuntime(31131): Caused by: java.lang.SecurityException: caller uid 10088 is different than the authenticator's uid
	E/AndroidRuntime(31131):        at android.os.Parcel.readException(Parcel.java:1425)
	E/AndroidRuntime(31131):        at android.os.Parcel.readException(Parcel.java:1379)
	E/AndroidRuntime(31131):        at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:487)
	E/AndroidRuntime(31131):        at android.accounts.AccountManager.getUserData(AccountManager.java:335)
	E/AndroidRuntime(31131):        at com.owncloud.android.authentication.AccountUtils.updateAccountVersion(AccountUtils.java:171)
	E/AndroidRuntime(31131):        at com.owncloud.android.ui.activity.FileActivity.onCreate(FileActivity.java:193)
	E/AndroidRuntime(31131):        at com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(FileDisplayActivity.java:167)
	E/AndroidRuntime(31131):        at android.app.Activity.performCreate(Activity.java:5104)
	E/AndroidRuntime(31131):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
	E/AndroidRuntime(31131):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
	E/AndroidRuntime(31131):        ... 12 more
	W/ActivityManager(  530):   Force finishing activity com.owncloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity

**Comment by LukeOwncloud** [comment]
I tried running it parallel to the origianl ownCloud app.

Apparently the beta tries to access the original account via http://developer.android.com/reference/android/accounts/AccountManager.html#getUserData%28android.accounts.Account,%20java.lang.String%29
`This method requires the caller to have a signature match with the authenticator that owns the specified account. `

Any idea what that means? :frowning:

**Comment by LukeOwncloud** [comment]
It should help to change the value of `account_type` in https://github.com/owncloud/android/blob/beta/res/values/setup.xml
Should `authority` also be changed?

**Comment by tobiasKaminsky** [comment]
Please try https://github.com/owncloud/android/blob/beta/apks/owncloud-beta-2015-10-30.apk

Thank you for your hint!

**Comment by LukeOwncloud** [comment]
Yes, that was it! Thanks.

Are you aware of any internationalization issues concerning the beta version?
Where it should say "Protect your ownCloud app with a pin", it just reads "@2131165531". It further mixes local and English languages. Should I open an issue?

**Comment by tobiasKaminsky** [comment]
Yes. Please always create a new issue with label "beta".
Then I can close this issue ;)
