### ISSUE TITLE
Owncloud Logo

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1227]
Create an owncloud logo with "BETA" in the lower right side to distinguish better between both version as the "owncloud beta" string maybe gets truncated.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger  :)

**Comment by AndyScherzinger** [comment]
sure thing :)

**Comment by rperezb** [comment]
@jancborchardt your input would be appreciated here, I guess

**Comment by jancborchardt** [comment]
I’d say maybe for the beta we use the dark icon:
![](https://raw.githubusercontent.com/owncloud/core/master/core/img/favicon-touch.png)
https://github.com/owncloud/core/blob/master/core/img/favicon-touch.svg

It’s similar to the Firefox »Nightly« concept. ;)

**Comment by tobiasKaminsky** [comment]
No "Beta" branding?

**Comment by jancborchardt** [comment]
In the app name I would say, and maybe in the title in the header if there’s enough space.

**Comment by tobiasKaminsky** [comment]
Can you help me with the icon @AndyScherzinger ?
I tried it but it never has the right size ... :/

**Comment by tobiasKaminsky** [comment]
![beta](https://cloud.githubusercontent.com/assets/5836855/10851609/62355c10-7f2c-11e5-93f4-e4fd1a061cca.jpg)

**Comment by jancborchardt** [comment]
»beta« should be lowercase. :) Otherwise it’s like an ownCloud app. It’s »ownCloud beta«.

**Comment by tobiasKaminsky** [comment]
Good point :+1: 
Changed, will be available tomorrow

**Comment by jancborchardt** [comment]
Oh right – the beta can be installed alongside the existing production app, right? I think this is very important so people can actually test this while still using ownCloud. For example, I only have 1 Android device (my phone) and use ownCloud of course, so it needs to be separate. ;)

**Comment by AndyScherzinger** [comment]
Logo has been pushed to the beta branch https://github.com/owncloud/android/commit/2afd2d6fb6171e94fd40a712cab9ee036b4c8058

**Comment by tobiasKaminsky** [comment]
@jancborchardt Yes, the beta app can be installed parallel to the official version.

**Comment by AndyScherzinger** [comment]
Logo has been committed to the beta branch thus closing this issue.

**Comment by jancborchardt** [comment]
You are some awesome folks! :) I really expect to see you at the next conf in Berlin so I can buy you a drink. (As @rperezb @davivel @masensio @MTRichards will probably too, so that’s 5 drinks. ;D)

**Comment by AndyScherzinger** [comment]
Love too, but like @tobiasKaminsky already mentioned end of August is a no-no for both of us :)

Glad I can help :)

**Comment by jancborchardt** [comment]
Ah damn, every year? I guess cause of vacation / holiday times or so?

cc @jospoortvliet just FYI and conf planning.

**Comment by jospoortvliet** [comment]
We're currently discussing moving the conf to Sept 16-22, would that work, guys?

**Comment by MTRichards** [comment]
>You are some awesome folks! :) I really expect to see you at the next conf in Berlin so I can buy you a drink. (As @rperezb @davivel @masensio @MTRichards will probably too, so that’s 5 drinks. ;D)

Yes! Maybe 2 from me...

**Comment by AndyScherzinger** [comment]
Sept 16-22 sound good to me, but I probably might only come in for Fri-Sun b/c else I would have to take vacation days. Besides that I might also ask for some travel cost support (which you offered this year anyways, so just mentioning it) ;)

End of August never works since it is @tobiasKaminsky's wedding anniversary and for my it is my birthday (so I am usually on vacation)

**Comment by tobiasKaminsky** [comment]
16-22 Sept is good :)
I will also attend at the weekend only.
Looking forward to see you all there!

**Comment by jancborchardt** [comment]
Ok, we still need to see if the dates work since the new semesters start there which would prevent lots of students to come – but we’ll see. Maybe it’s time that @DeepDiver1975 and me just organize a full-on spring conference in Munich :D

**Comment by jospoortvliet** [comment]
@jancborchardt we do usually have an April meetup in Nue, I think that that one should grow a bit ;-)
