### ISSUE TITLE
Beta: Internationalization issues

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1228]
Using owncloud-beta-2015-10-30.apk.

In settings menu, where it should say "Protect your ownCloud app with a pin", it just reads "@2131165531".

It further mixes local and English languages.

![photo_2015-10-30_08-47-17](https://cloud.githubusercontent.com/assets/2737900/10840758/d811f30c-7ee2-11e5-8b9e-5817925c429d.jpg)

**Comment by tobiasKaminsky** [comment]
Regarding the "Behaviour": As it is not in the official trunk, transifex does not know about it and therefore it is not translated. I think we just have live without a translation. Or we can add them by ourselves, at least for the common ones.

**Comment by tobiasKaminsky** [comment]
I have fixed the PinCode thing.
It will be in the next version.
Please confirm it then and close the issue.

**Comment by LukeOwncloud** [comment]
Solved.
