### ISSUE TITLE
f-droid repository for public beta

### ISSUE THREAD

**Issue by xylo** [owncloud/android#1229]
To reach more test user for the public beta and to provide a simple update mechanism to ensure they use the latest beta it would be good if the public beta is deployed through an f-droid repository.

**Comment by LukeOwncloud** [comment]
Good idea! Are you still willing to set it up?

**Comment by tobiasKaminsky** [comment]
Should be released after #1227 as this provides an separate owncloud beta logo.

**Comment by xylo** [comment]
Yes, I would try to set it up on the weekend.  I'm just wondering on which server it's finally hosted.  Of course I can use my own server for this, but maybe the official owncloud developers would prefer to host the repo themself.  In that case I could at least provide my f-droid server configuration to them.

**Comment by tobiasKaminsky** [comment]
I thought f-droid is building the apk from source and therefore hosts the resulting apk on itselfs?
Using a private server is not a good idea as it looks unprofessional...

**Comment by xylo** [comment]
@tobiasKaminsky So you would suggest to put the Public Beta directly into the official f-droid repository.  That's also an option.  In that case we just need to file a request on f-droid.org to integrate ownCloud Beta in their repository.  It's probably not much work for them, since they can mainly copy the configuration from the official owncloud app, I guess.

**Comment by tobiasKaminsky** [comment]
Yes. It should be as easy as  possible for the user to install it.
Otherwise they would have add a "simple binary repository" if I read and understood it correctly...?

**Comment by tobiasKaminsky** [comment]
And please give me a hint how to tell f-droid which version and when it should build a new apk :)

**Comment by xylo** [comment]
Yes, if we would host the repository f-droid users would need to add it in f-droid first.

Regarding the submission process of f-droid:
The following link describes how to add an app to the submission queue: https://f-droid.org/wiki/page/Inclusion_How-To

I would post the app submission in a style like this: https://f-droid.org/forums/topic/owncloud-notes/
But with an adapted version of https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.owncloud.android.txt

**Comment by tobiasKaminsky** [comment]
Can you maybe prepare this? And do a PR on the beta branch?
Then, after #1227 and figuring out how to to "release" we can post it f-droid

**Comment by xylo** [comment]
OK.

**Comment by xylo** [comment]
Is there a direct git link to the beta branch?

**Comment by tobiasKaminsky** [comment]
https://github.com/owncloud/android/tree/beta

**Comment by tobiasKaminsky** [comment]
@xylo Now the owncloud logo is included, thanks to @AndyScherzinger.
So we are ready for f-droid :)

**Comment by AndyScherzinger** [comment]
It might be obvious but just to make sure... The icon commit has only been done to the beta branch

**Comment by tobiasKaminsky** [comment]
@xylo If I can help you by providing you additional infos, please let me know!

**Comment by xylo** [comment]
@tobiasKaminsky Yes, I have one question: What is the URL for retrieving the latest available version of the ownCloud betas?

BTW, it might be good to set also the package name in the file AndroidManifest.xml to "com.owncloud.android.beta".  That was a bit confusing for me when I changed the branch.

**Comment by xylo** [comment]
@tobiasKaminsky Found it: https://raw.githubusercontent.com/owncloud/android/beta/apks/latest

**Comment by xylo** [comment]
I posted the app submission on https://f-droid.org/forums/topic/owncloud-beta/

**Comment by Taomyn** [comment]
@xylo could this not be added to the same entry in F-Droid as the production version? If you look at F-Droid's own listing https://f-droid.org/repository/browse/?fdfilter=f-droid&fdid=org.fdroid.fdroid it has only one yet it includes alphas/betas and they are never pushed and must be applied manually (unless you change a global setting I believe).

**Comment by xylo** [comment]
@Taomyn That would be also an option, yes. In that case @tobiasKaminsky only has to tag his beta versions with a special "beta" label in git. Then the build system of f-droid could detect this and build the beta versions automatically.

On the other hand, this solution conflicts with the different package IDs the official app and the beta app currently have. This separation regarding the package ID was done to allow the installation of the beta alongside the official app. If name the package IDs equally (which has to be done if you publish it as one f-droid app) you will lose this feature again. Moreover, having a separate beta app with a special description will make sure that only advanced users willing to test unstable features are using the beta.

**Comment by Taomyn** [comment]
@xylo understood. All I would add then is that Google's own beta process through Play Store for any app works in much the same way as F-Droid in that the ID is the same - you just have to apply for access usually through G+ - just saying ;-)

Also, and I know I wrote above "All I would add", but isn't running two versions of the app against a single version of the server just as likely to cause issues? Swings'n'roundabouts I suppose.

Still I look forward to a simple way to get to the beta - can hardly run the release on any of my Marshmallow devices.

**Comment by tobiasKaminsky** [comment]
Running both version parallel should be not problem unless you only use one instant upload and use keep-in-sync also only with one app...
All other operations are user-triggered one (download, upload, ...) and will not conflict.

**Comment by strugee** [comment]
@xylo you should consider directly sending a Merge Request on GitLab. See https://f-droid.org/forums/topic/read-this-before-posting/

**Comment by tobiasKaminsky** [comment]
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md
This seems the way to do it...

**Comment by tobiasKaminsky** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/1056
I have added a merge/pull request.
I hope this speeds up the process.
Thanks to @xylo for creating the metadata! I could used it nearly 1:1 :)

**Comment by xylo** [comment]
Oh, I didn't know that you can just add ",branches=beta" to the Repo property.  That's great.

Are you sure about the Auto Update Mode?
As I understood this seems to be complicated.  Every beta release needs to be tagged.  And if you tag it in the form "oc-android-beta-20151115" you need to set "Auto Update Mode" to "Version oc-android-beta-%v".  Moreover, I think fdroid checks also the package name and version specified in the AndroidManifest.xml which needs to be also the same, I think.

According to the CONTRIBUTING.md you also need at least one working build recipe.  That could be the reason for your "FDroidException: No apps to process".  I tried one build recipe but it failed since f-droid could not find the corresponding version (tag) in the owncloud repository.  So I think we have to tag the build first.

Moreover the build process of f-droid looks quite complicated.  Each binary dependency you might have in your project must be built from source when building the project.  But the build recipe of the official owncloud app looks quite short regarding this.  They reference the sources of the libs but I don't see how they are built and processed in the end.  I have the feeling that one has to dive deep into f-droids build process to be able to write such build recipes.  I'm sorry, but I think I don't have the time for that.

I hope we get some support form f-droid, especially from the maintainer of the owncloud app.

**Comment by xylo** [comment]
The current maintainer of the owncloud app is Daniel Martí, see https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/com.owncloud.android.txt.

**Comment by tobiasKaminsky** [comment]
Apparently it is not that easey. Although everything except the last step is working, the fdroid build command is not working (and seems to be a hard work getting it working...)

**Comment by tobiasKaminsky** [comment]
It is now in the git master branch of fdroid and should be soon in the repository browsable by the client :)

**Comment by xylo** [comment]
Nice!

**Comment by tobiasKaminsky** [comment]
And here we go: https://f-droid.org/repository/browse/?fdfilter=owncloud&fdid=com.owncloud.android.beta

**Comment by LukeOwncloud** [comment]
How difficult would it be to add the beta version? Currently f-droid just shows "owncloud beta" where it should say "v20151129".

**Comment by tobiasKaminsky** [comment]
Next build, maybe tomorrow ;), will have it.
