### ISSUE TITLE
Beta: Cannot open files

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1230]
Using owncloud-beta-2015-10-30.apk.

When clicking a file which is not an image and not already available on the device, nothing happens.

Work around: Long click the file, select "Details" from the menu, then click the download button, go back to list. Now clicking the file works.

**Comment by xylo** [comment]
Same behavior for me.

**Comment by tobiasKaminsky** [comment]
This is related to multi select. 
I will fix it soon.
Thanks for reporting

**Comment by tobiasKaminsky** [comment]
Ok. It was not related to multi select.
I have fixed it.
It will be available tomorrow.

So there is a faulty commit in any PR I have merged. Anybody an idea how I can figure out who to blame?  ;-) ;-)
The problem was the missing else branch in https://github.com/owncloud/android/blob/beta/src/com/owncloud/android/ui/fragment/OCFileListFragment.java#L495

**Comment by LukeOwncloud** [comment]
> So there is a faulty commit in any PR I have merged. 

Then creating "beta project" was already a success! :smile:

**Comment by tobiasKaminsky** [comment]
But not, if we cannot track it back to the PR or commit...

**Comment by LukeOwncloud** [comment]
If you already found the file, could this help? 
http://stackoverflow.com/questions/3701404/list-all-commits-for-a-specific-file

Alternatively, search by content:
http://stackoverflow.com/questions/2928584/how-to-grep-search-committed-code-in-the-git-history

I do not have git installed currently.

**Comment by tobiasKaminsky** [comment]
Latest beta is available, can you check and then close?

**Comment by tobiasKaminsky** [comment]
Hm. I cannot find the faulty commit.
Maybe someone else can help find me? Until this is found, please keep it open

**Comment by tobiasKaminsky** [comment]
Ok. Found it :)
@LukeOwncloud please close, if it is fixed in Beta.

**Comment by LukeOwncloud** [comment]
Solved in beta.
