### ISSUE TITLE
Side drawer: "On device" show empty folders

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1231]
Using owncloud-beta-2015-10-30.apk.

When choosing "On device" from the side drawer I expect all folders which do not contain any downloaded files to disappear. Instead I still see the whole folder structure. This is confusing to me as a user.

Further, there is no indication that currently only files "on device" are shown. Looking at a folder which I know has content but which says "Nothing in here. Upload something!" (string ``file_list_empty``), is even more confusing. Note: Also string `local_file_list_empty` "There are no files in this folder." would not help much, either.

**Comment by tobiasKaminsky** [comment]
I see your point.
I thought this should just "filter" files and show still all folders as they are needed to navigate.
Imagine this:
root -> folder1 (no files) -> folder2 (files)
Then we would have to check recursively if an any subfolder is a file and only display this "folder path".
Furthermore there is no possibility to go in an "empty" folder and upload files.

Do we want this? I do not know. I think both approaches are valid.
Please your opinion: @jancborchardt @AndyScherzinger 

Related PR: #1205 
Related issue: #407

**Comment by AndyScherzinger** [comment]
Well the most common way would be to display all offline files in one list. At least that is how dropbox and google drive do it. Point is they do is for the pinned ones so the view is not online/offline but rather all/starred. The later makes sense since you probably don't have that many files starred but thanks to your selfies quite the amount of pictures...

**Comment by tobiasKaminsky** [comment]
(side note: I am not quite sure about the handling of these "bugs" as this for example is related to a PR #1205. So maybe we should close this as soon as it is obviously that it belongs to a PR and track it there?)

@AndyScherzinger Putting all downloaded files into one singe list view is kind of strange... I suggest to 
- keep it the way it is
- hide folders with empty content and empty subfolders (which is indeed no real problem to figure out)

**Comment by tobiasKaminsky** [comment]
@jancborchardt

**Comment by LukeOwncloud** [comment]
You are right. This is not a bug, but rather about design. Let's keep this discussion where it belongs: https://github.com/owncloud/android/issues/407
