### ISSUE TITLE
Thumbnails gone after scroll down and up again

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1234]
Using owncloud-beta-2015-10-30.apk.

How to reproduce:
Open a folder containing many photos, choose grid view. At this moment there are still no thumbnails. Open a photo, go back to grid. Now some thumbnails are shown. Scroll down, scroll up. Thumbnails are gone.
Thumbnails are also gone after switching screen off and on again.

Note: It seems that after after thumbnails of a folder are loaded, they do not disappear anymore.

**Comment by tobiasKaminsky** [comment]
Latest beta is available, can you check and then close?

**Comment by LukeOwncloud** [comment]
Solved. 

Just one other thing: it seems to me that opening images while thumbnails are being generated is very slow. It might be the server. Could it also be the ordering? I. E.  That fullscreen opening is not prioritized? I am going to observe this behavior further...

**Comment by tobiasKaminsky** [comment]
Although I do not use a queue for downloading thumbnails or resized images I guess they are handled internally one after one.
Please also note that you do not download the full image, but instead only a resized version (adapted to your screen size --> #1044)
