### ISSUE TITLE
[beta] In the file view, the sync icon is invisible (visibility property problem?)

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/android#1237]
The synchronise icon is not shown (to be exact: when you know where it should be, you can click it). So it appears to be a problem with the visibility property.

**Comment by Wikinaut** [comment]
I cannot assign labels here. Pls. add ```beta``` (or set permissions that I can assign labels).

**Comment by tobiasKaminsky** [comment]
Can you try the latest beta from 1.11.15, 13pm?
If the issue is still valid, please post a screenshot as I do not know which icon you mean ;)

**Comment by Wikinaut** [comment]
@tobiasKaminsky is not visible (beta = 12dbd25ac9691faebd909322e9fa4662fa5cc1f8 ).

I mean the sync icon. I only see the sort icon and the gallery/folder-view icon in the header of the file view.

**Comment by Wikinaut** [comment]
<img src="http://i.imgur.com/xLcs6vn.png">

On my Tablet PC, the SYNC icon (pictured) is NOT visible. It is present, when I hover over the place.

**Comment by Wikinaut** [comment]
Ah, interestijg effect. On my other device, a small 4" phone Android 4.0.3, there is not even the SORT icon visible. In Portrait. When I rotate the device to landscape, I do see the SORT, and the GALLERY icon. No SYNC icon, my dear friends.

**Comment by Wikinaut** [comment]
UPDATE 04.11.2015 

The present beta f15c2f32ceea2f2e6abff36f828a37196db3040a shows the "3-dot-menu", and no longer icons. The three sub-menu items are working.

Why have you changed to the "three-dot-menu" ?

**Comment by Wikinaut** [comment]
I reported the issue and close it now, because the icons are not rendered any more and are replaced by a 3-dot-menu, which works for me.

**Comment by AndyScherzinger** [comment]
@Wikinaut This has been desided by the designers, namely @jancborchardt  - for details please see discussion https://github.com/owncloud/android/issues/1232#issuecomment-153020296 ff.

**Comment by Wikinaut** [comment]
my issue is related to #1232 .

**Comment by jancborchardt** [comment]
@Wikinaut cool that the new design works to fix the problem you experienced as well. :)
