### ISSUE TITLE
Settings: show if beta update is available

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1238]
In settings show if there is a new beta update available by adding "update available"

**Comment by LukeOwncloud** [comment]
That would be nice, but it involves some work (to get it right).
F-Droid already checks for updates and informs the user. Is that good enough for us?

**Comment by tobiasKaminsky** [comment]
I do not know. 
For my wife, for example, it would be not as she does not have f-droid installed. ;)

**Comment by LukeOwncloud** [comment]
Agreed, that would be nice. There are too many updates of the beta version. Waiting for an f-droid update is too slow.

**Comment by LukeOwncloud** [comment]
Option "Download latest beta version" is available. I thus close this issue. Okay?
