### ISSUE TITLE
InstantUpload not working for Android app in Owncloud 8.2

### ISSUE THREAD

**Issue by TheBR** [owncloud/android#1239]
Using the Owncloud 8.2 Virtual Machine image (unmodified) i get the following in the log files when uploading from the Android app.

"reqId":"szi7CHYbnMIrhfTVujzE","remoteAddr":"192.168.0.1","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-11-01T14:24:45+00:00"}
{"reqId":"1YB6Y\/DUttevgT871tKI","remoteAddr":"192.168.0.1","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-11-01T14:24:48+00:00"}
{"reqId":"QYfsnbQMvyFU8\/E9VcED","remoteAddr":"192.168.0.1","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-11-01T14:24:52+00:00"}
{"reqId":"QFWH6yLFx1P0nnvowonx","remoteAddr":"192.168.0.1","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2015-11-01T14:24:56+00:00"}

On the app i get a response of  Upload Failed "You dont have permission to upload to t.."

I've read of issues related to http headers with similar issues in 8.1 and wanted to mention that i am behind a reverse proxy here. I have no idea if its relevant but im mentioning it as i could be.

**Comment by piwats** [comment]
Same here.

**Comment by tobiasKaminsky** [comment]
@DeepDiver1975 can this "header not sent" be related to permission problems?

**Comment by DeepDiver1975** [comment]
We would need to see what is exact response of the PUT request would be.

@TheBR @piwats can you issue a curl to simulate a webdav PUT operation to your server?

**Comment by TheBR** [comment]
Hi,
  I think i am tracking this down to a permission issue, however, i think my permission's were set correctly on the folders in question, but, i needed to issue a

/var/www/owncloud/console.php files:scan --all

In order for owncloud to "update". Either way i am now able to upload but it wasn't that obvious what was wrong or why it got in that state in the first place. Sorry that i cant give a more detailed answer.

**Comment by LukeOwncloud** [comment]
Does/Did the problem only occur for instant uploads?

Same error log was reported already in other issues:
https://github.com/owncloud/android/issues/1074
https://github.com/owncloud/core/issues/17586
https://forum.owncloud.org/viewtopic.php?t=30436&p=96621

Are these related?

**Comment by elpraga** [comment]
I am using OC 8.2 and Android 6. Instant upload is working. Let me know if I can help You by sending some data.

**Comment by enoch85** [comment]
Dup of: https://github.com/owncloud/android/issues/1074

**Comment by davivel** [comment]
As @enoch85 said, this is a duplicated issue. Please, go to #1074 to check the updated state.

Hint: this could be fixed (for the client side) from ownCloud Android  app 2.3.0.
