### ISSUE TITLE
Showing thumbnails is slow + there are too many thumbnails versions

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1241]
In the old client clicking a photo starts its download, what is the action in beta?

I get just rotating circle both when clicking on already downloaded and non downloaded photos.

When I click on already downloaded photos they appear after a minute or so of seeing the rotating circle, as opposed to showing the photo instantly in for example QuickPic. Any reason why it takes so much longer?

I'm sorry, but I didn't figure out how to add the beta label to the issue.

Tomas

**Comment by tobiasKaminsky** [comment]
For now you need the owncloud app "gallery+" if <8.2 or at least 8.2 with enabled "gallery".
But from your experience, I see that we should have a fallback to the current way...

**Comment by elpraga** [comment]
Hello Tobias!
Thank You for the information! I was using Galery+ with ownCloud 8.2. I switched to Galery and did some testing.

Now I do know what it is supposed to do and I have to admit that I like the idea quite a bit. I will share my observations..

I have two android devices, a tablet 97 and Nexus 5 I regularly use with my account in ownCloud. To upload I (and other users) use an Ubuntu machine with the client. Sometimes I do open the web interface, but mainly for sharing that is currently impossible to achieve with the Android App.  

I like the idea to see a nice full-screen preview without downloading the whole photo. It takes between 4-10 seconds to show the preview. A problem aroused when I swiped forward and I wasn't sure what is going on. I was just seeing one rotating circle after another.

Suggestion:
Would it be possible to use enlarged small definition thumbnails instead of the circle until the big thumbnail is available? In the same way google does it when looking at searched images in Chrome on Android? It could be a nice usability improvement. 

Sidenote:
with my devices I have:
-rw-r--r--   1 www-data www-data  68613 Nov  4 00:10 1080-799-with-aspect.png
-rw-r--r--   1 www-data www-data   2977 Nov  3 23:24 128-128.png
-rw-r--r--   1 www-data www-data 236410 Aug 28 11:35 2048-1516-max.png
-rw-r--r--   1 www-data www-data   7270 Oct 23 01:15 270-200-with-aspect.png
-rw-r--r--   1 www-data www-data    922 Oct 25 01:55 32-32.png
-rw-r--r--   1 www-data www-data  14432 Aug 28 11:35 384-384.png
-rw-r--r--   1 www-data www-data  56607 Nov  4 00:08 973-720-with-aspect.png

That is 7 different thumbnails for one photo so far after seeing one picture on the two devices. (I used find /path/to/thumbnails/ -mmin 1 to locate the newly generated thumbs)

I was really thinking that generating the thumbnails with a cron job would be a good idea, but now I am asking myself, if it would be possible to somehow reuse the thumbnails and generate less of them.

What is Your opinion on the matter?

BTW.
I am using the latest beta from today..

And thank You for Your work on the android client..

Tomas

**Comment by LukeOwncloud** [comment]
I like the idea of resusing existing smaller versions. Seven version of the same image is really a lot. And it is only getting more... Could we use some default sizes? E.g. 384x384 as thumbnail (for list view), a small preview version (~1000px width) and a large version (~2500px width)?

I also like the cron job idea, as I have the same problem as Thomas: Showing a preview image (full screen) on my Android devices takes many seconds (~5-15). Most likely due to a slow server. For me (being at home) it would probably be faster to download and show the original version.

**Comment by LukeOwncloud** [comment]
This issue is about slow creation of too many thumbnails, right?
This is related to: https://github.com/owncloud/android/issues/921
I'll change the title of this issue accordingly.

**Comment by LukeOwncloud** [comment]
There is another circumstance that makes thumbnails slow. It seems there is no priorization queue. When scrolling all the way down to the last photo, before the thumbnail of the last photo is shown all other thumbnails are loaded first. Just checked the server log.

It get even worse when you open the last photo to show the scaled version. You have to wait until all thumbnails are loaded first.

**Comment by tobiasKaminsky** [comment]
What about using fix size:
256px for thumbnails
1920px for resized images
With these hardcoded values we have
- small overhead for phones with lesser display 
- small drawback on phones with higher displays as the resized images could be a little blurry
- only 2 thumbnails that may be can be auto-generated during upload/cron job or at least are available after first accessing them

What do you think?

**Comment by tobiasKaminsky** [comment]
@LukeOwncloud Regarding the wrong prioritization queue please open a new issue (or maybe search for an old one. I think I am remembering such an issue opened by @jancborchardt)

**Comment by elpraga** [comment]
> 256px for thumbnails
1920px for resized images

What about the traffic Tobias? Did you look at how big the files are? And also the default max preview size is 2048, pretty close to 1920..

Right now I'm experimenting with setting the max preview size to 1080 on my server (it is the largest I really use) to see if the application uses the max preview directly and thus doesn't generate a new preview.

Unfortunately I cannot look at the sizes of the previews right now, so I cannot tell how much traffic would we save by generating 1080 and 1920 (2048) sizes of previews.

It would still help because having the sizes defined, we could still create them by a cron job and we might save some traffic on mobile data.

What do you think?

And you decide to stick with just one big preview, the app will have to be able to cope with servers with lower max_preview_size

**Comment by tobiasKaminsky** [comment]
Just try it and resize images on your own and compare the sizes.
For me this is no real problem as my server is fast enough.
I think this is more a question for /core, at least the server generation part.
(Also the question what happens if the desired preview is bigger than the max_preview_size)

**Comment by tobiasKaminsky** [comment]
Just try it and resize images on your own and compare the sizes.
For me this is no real problem as my server is fast enough.
I think this is more a question for /core, at least the server generation part.
(Also the question what happens if the desired preview is bigger than the max_preview_size)

**Comment by elpraga** [comment]
I am looking into it, but I will need more time to get more useful info

**Comment by elpraga** [comment]
I have looked at quite some things so I will try to break it down:

##requesting larger previews then max_preview on server ##
Works without any problems. There should not be any problems if someone sets max_preview to lower resolutions then the app will ask for.

##file sizes / mobile network banwidth / speed of preview loading##
My Nexus5 384-384 thumbnails that look great when enlarged are usually between 10-20 kB, that would make 1-2MB traffic on a folder with 100 files

My Nexus previews 1080-something were aroung 100kB each which would generate some 10 MB of traffic on a folder with 100 files

The 2048-something previews that are default to OC were around 300kB each, resulting in 30MB of traffic on a folder with 100 files (1920-something would be somewhat smaller) (that is already more then the default cache on just one folder like InstantUploads)

###Conclusions###
I do think that the best would be to use 3 sizes of thumbnails/previews:
380-380 or something like this for thumbnails that can be nicely enlarged before the preview is loaded
1080-xxx-with aspect for phones and tablets

2048-max for nice tablets with a big display and resolution (close endough to 1920 and no new preview has to get generated by default)

####Benefits of such a solution####
* thumbnails that can be enlarged nicely without too much extra traffic
* good quality previews on all devices
* good speed ratio (I suppose that even on a fast server would downloading a large number of 1920-something previews take quite some time, especially on 4G)
* nice previews on big devices like goood tablets
* server would have to generate only 3 kinds of files for every photo

####Downsides of the proposal####
* cannot think of any because I don't have more devices to test on, can't speak for smaller phones or nice tablets, phablets..

__P.S.__
I managed to reduce the number of thumnails generated on my small server to 3 by fiddling with preview_max on the server. So I am quite fine now. I am just trying to make a suggestion that would make this great app more usable for others.

**Comment by przybylski** [comment]
My 2¢:
Downsides:
* Server would need to generate 3 kinds of files for every photo. If file is large then it needs to load the entire file to the memory, manipulate it (cache it?) and send to the user. Requesting for multiple previews will increase memory usage. Lets say that you can fit 10 images. Lets say that each photo is ~10MB which is reasonable for modern phones. This will generate memory usage by ~150MB (assuming 50% cost of preview image) for this single screen + php overhead. User can scroll, which would start multiple requests, which will be ran on sever anyway.
* This will produce a lot of data transfer from server to mobile. When not on WiFi in countries where data is expensive this will be overkill.

**Comment by elpraga** [comment]
>> Server would need to generate 3 kinds of files for every photo. If file is large then it needs to load the entire file to the memory, manipulate it (cache it?)

That is the reason why we are talking about it. Now you get 3 files for each file already. I use 2 devices and when I open the Gallery on the web, I get 7 files for one photo now.

My whole idea is to reduce the number of files and the server workload.

**Comment by elpraga** [comment]
>> This will generate memory usage by ~150MB

Only preview_max is generated from the original file. The rest of the previews is generated from this reduced file.

You can change the preview_max values s in config.php (as I did) and lower the server workload.

If you avoid the full-screen preview, only the smallest thumbnail will be downloaded to your device, and it is not that big..

**Comment by elpraga** [comment]
>> 10-20 kB, that would make 1-2MB traffic on a folder with 100 files

This would be roughly the traffic you would automatically get when you open the folder with 100photos (and assuming that you list through the whole folder) to download the larger preview you have to click on the file, which I suppose would would not do if you were concerned about data traffic.

I apologize for sending three messages, I'm in my phone..

**Comment by tobiasKaminsky** [comment]
As far as I recall my conversation with the /core devs the one step that really slows down the server is generating the preview_max_values from the original one. As @elpraga said all other previews are generated from the resized version.

**Comment by tobiasKaminsky** [comment]
So...Do we have here a conclusion?
Maybe https://github.com/owncloud/core/issues/11685 helps and we will just have to wait?

**Comment by TheManOfTheMAn** [comment]
Best solution would be to generate lower src image in general for every photo by async. generation if not existing and requested or continuously with a crone job. That files may just get something between 100x100 to 200x200 px per file with a little stronger compression to save file size.

Now new photos will be generated on the fly asynchronous if imitatively visited or in the background with the crone. So whenever you browse a file list in the app or in the web client you delivery the lowersrc first and get a preview immediately. So for little thumbs in the list or in the app directory listening you would'nt even mind a difference in quality. So may add a config option to main conf. to always load just lower source images in any directory listing (app/web) this will dramatically improve the delivery and user experience even on lower end servers.

For the detail view just load the lowersrc as attribue or regular sorce with a transparent hardly visible loader overlay and switch to the high quality image as soon as its onload got fired!

So you would have the look and feel of a very fast service even if bigger images need time for preparation. Also I would ad a general setting to the main conf for all preview sizes and a option if you would like to use the specifiy size and if the thumb should be stored or always processed on the fly! With a fallback to a minimum quantity of one or two thumbsizes (lowersrc and a better one) so that if specific images are not enabled a default size gets loaded even if that means that the quality might not be the best because the image gets scaled on the client side.

Indeed this is the behaviour most systems I know handle thumbnail creations and delivery :)

**Comment by elpraga** [comment]
I think we could just wait for now. The occ thumnail generation command should come out with OC 9.0 which should be out in early March if I am not mistaken.

We can see how much just the generatin of preview_max in cron helps.

I would suggest to put the minimal thumbnail bigger though. On my phone it is quite decent, and when it appears in the meantime when the bigger preview is being downloaded/generated, it looks pretty decent. On the other hand, on my tablet, where the small thumbnails is small, it looks very blurry when enlarged. In my opinion, using a bigger smallest thumbnail would improve the user experience.

**Comment by tobiasKaminsky** [comment]
@elpraga is it working better for you now with oc9?

**Comment by elpraga** [comment]
It seems to be working better, but it is not yet smooth.

The separate thumbnail creation was moved to 9.1, so I'd wait until then to provide additional info.

You were also speaking about generating the previews locally on the phone.

Is that why you ask for an update now?

**Comment by tobiasKaminsky** [comment]
I was just asking if it now good enough to close this issue ;)
Generating previews on the device should not affect this issue as it is completely independent.

**Comment by elpraga** [comment]
I still think it would have some advantages to use only several standardized sizes of thumbnails and previews as I mentioned earlier, but I have no new arguments, and I managed to find a workable solution for me by reducing the size of preview_max.

I leave it up to you. ;)

**Comment by tobiasKaminsky** [comment]
Then this is is something that we should discuss when the PR is getting verified by main developers.
So please take a look at #1044.
Therefore closing it for now.
