### ISSUE TITLE
current beta: Download menu item when does not start download

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1244]
When I click on the menu item "Download" while viewing the fullscreen thumbnail, the downloading of the file does not start.

**Comment by LukeOwncloud** [comment]
Confirmed.

**Comment by Wikinaut** [comment]
@LukeOwncloud here https://gerrit.wikimedia.org/r/#/c/248699/ is a code patch (fully tested!) which I recently developed for the Wikipedia App, it adds variant and build name, and git version hash to the apk name.

Perhaps you want me to formally send a Pull Request for oc/android, then let me know!.

**Comment by LukeOwncloud** [comment]
@Wikinaut Let's not hijack this discussion! -> https://github.com/owncloud/android/issues/1246

**Comment by tobiasKaminsky** [comment]
@elpraga the fix is in current beta (2015-11-05), please test and then close it.

**Comment by elpraga** [comment]
Confirmed. Download now works using the menu.

Thank You!
