### ISSUE TITLE
[1.8.0] [Transifex] [nl] First letter of menu item "verplaatsen" (Move) should be capitalized

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#1245]
All menu items begin with upper-case character, but "verplaatsen" (Move) starts with lower-case character.

![image006 2](https://cloud.githubusercontent.com/assets/214010/10925862/221adaba-8292-11e5-8492-1990901d9423.jpg)

This could be easily fixed in Transifex, but I haven't got permissions to help with the Dutch translation yet:

![owncloud___transifex_editor](https://cloud.githubusercontent.com/assets/214010/10925892/67fe6196-8292-11e5-9448-81a9e6da55c1.png)

https://www.transifex.com/owncloud_robot/owncloud/viewstrings/#nl/android/10926912?qt=verplaatsen

@MorrisJobke Who can help here? /cc @DeepDiver1975 @rperezb 

Please also see my suggestions for using hints about the context of a string in Transifex in https://github.com/owncloud/client/issues/3519#issuecomment-126695367 .

00004083

**Comment by MorrisJobke** [comment]
@rullzer @Xenopathic @jospoortvliet Is one of you in the dutch transfix team and can fix this quickly?

**Comment by MorrisJobke** [comment]
> @rullzer @Xenopathic @jospoortvliet Is one of you in the dutch transfix team and can fix this quickly?

cc @icewind1991

**Comment by davivel** [comment]
Fixed in Transifex, will be merged in next translation sync (tomorrow).

Let's keep it open until merged.

**Comment by rperezb** [comment]
fixed https://github.com/owncloud/android/commit/94b21ef5d933996b6a382e7474f0178950fc0f61
