### ISSUE TITLE
Add build date and git version to beta build

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1246]
@Wikinaut wrote:

> @LukeOwncloud here https://gerrit.wikimedia.org/r/#/c/248699/ is a code patch (fully tested!) which I recently developed for the Wikipedia App, it adds variant and build name, and git version hash to the apk name.
> 
> Perhaps you want me to formally send a Pull Request for oc/android, then let me know, and I will supply it very quickly.
> 
> Changes are required in two files see patch set 10 :
> 
> * https://gerrit.wikimedia.org/r/#/c/248699/10/app/build.gradle
> * https://gerrit.wikimedia.org/r/#/c/248699/10/app/src/main/res/values/strings_no_translate.xml

**Comment by LukeOwncloud** [comment]
That reminds me of: https://github.com/owncloud/android/issues/763 (show build date)
We decided not to include it as it is very technical (and the issue about reproducible builds (which I think now, is not valid.))

@tobiasKaminsky and @AndyScherzinger What do you think? Should we include @Wikinaut's patch? I'd say just showing the build date would be fine (https://github.com/owncloud/android/issues/763). Actually, just uniquely naming the apk would be fine with me as well.

**Comment by Wikinaut** [comment]
@LukeOwncloud thanks.

**Comment by Wikinaut** [comment]
by the way, I am now and then in the chat, but this appears seldomly be used by owncloud developers.

**Comment by AndyScherzinger** [comment]
I think it would be a good idea for the beta app but would rather like the version name (not the numeric number) to be used thus it would simply be displayed in the settings screen, kind of like the build number discussion in the referenced ticket so basically the baseline version 1.8.0 - builddate and I guess the date would be fine since that is probably enough to find out which build it is and if a bug has been fixed already. What do you think @tobiasKaminsky ?

**Comment by Wikinaut** [comment]
@AndyScherzinger can you come to the chat now?

**Comment by AndyScherzinger** [comment]
@Wikinaut Sorry, I can't, at least not during the regular work hours

**Comment by tobiasKaminsky** [comment]
The build date will be visible in Settings under "owncloud beta android app".
The filename is generated by me in this format: owncloud-android-20151106.apk.
This is required for the built-in update system.
So therefore I close it.

**Comment by LukeOwncloud** [comment]
Does not work with `owncloud-beta-20151105.apk`. Menu entry shows string "Version owncloud beta" where the actual version should appear.

**Comment by Wikinaut** [comment]
@LukeOwncloud Hi, can we chat about this ?

**Comment by LukeOwncloud** [comment]
I was impatient. Works just fine with version 20151109. Closing issue again.

@Wikinaut No need to chat then, right?
