### ISSUE TITLE
Menu action: "Set picture as" also for non-picture

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1248]
Open a non-picture file (e.g. mp3), click menu: It contains entry "Set picture as".

Clicking this action has no effect. However, it should not be there in the first place!

**Comment by LukeOwncloud** [comment]
Menu in file details view also shows "Switch to grid view".

**Comment by tobiasKaminsky** [comment]
This is changed in beta and will be available soon.
Please check it then.

**Comment by LukeOwncloud** [comment]
Confirmed. Fixed with version 20151109. Closing issue.
