### ISSUE TITLE
Files remain if deleting account

### ISSUE THREAD

**Issue by svenclemens** [owncloud/android#125]
### Expected behaviour

If deleting an account the files on the device associated to the account should get deleted.
### Actual behaviour

The account get deleted but the files will remain.
### Steps to reproduce
1. Download some files
2. Deleting your account (in owncloud app)
3. View downloaded files in file manager
### Environment data

Android version: 4.1.2

Device model: Samsung Galaxy S2

Stock or customized system: Stock

ownCloud app version: 1.3.20

ownCloud server version: 4.5.7

_____

EDIT (July 2021)

Check https://github.com/owncloud/android/issues/125#issuecomment-188351540

- App removal -> to do here

By removing account from oC app, remove the account folder from  app storage.

- Device Settings removal -> future feature (worker)

**Comment by tobiasKaminsky** [comment]
What about a dialog "Do you want to remove all files on device?" 
Easy and simple ;)

**Comment by AndyScherzinger** [comment]
I second @tobiasKaminsky suggestion, when deleting an account on the device the app should simply ask if the accounts data should be deleted on the device. :)

**Comment by jochenwezel** [comment]
The suggested dialog depends on the *user* - but this behaviour must be controlled by the organization/Company who "owns" the data and who has to ensure that some people can't access that data any more.

**Comment by tobiasKaminsky** [comment]
@jochenwezel 
I see your point but how can this be achieved?
The app then must verify that the account was deleted and that the option "force delete files on remote devices" is enabled and then delete the complete folder with all files?

@davivel Do you know how this is being handled by the desktop sync?

**Comment by jochenwezel** [comment]
@tobiasKaminsky yes, this would match approx. to the requirement. Only 1 additional point: "force delete files on remote devices" should be default setting (if you like, a General Switch for changing the Default to "disabled" could be provided in administration area)

**Comment by joeplus** [comment]
Just out of interest: How is it possible for an organization to administer the remote owncloud app and to ensure that when the user account is deleted (e.g. when the employee leaves the company) all files are deleted as well?

**Comment by jochenwezel** [comment]
1. the Client app must still sync with the Server "with a valid Login"  (for this, the Server must still allow (at least for a few weeks) to Login with the current Login data)
2. after successful Login: Client app recieves delete notifications for all files and Folders
3. cleanup done on 1 device - maybe other devices/sync Clients follow as soon as they sync next time

**Comment by joeplus** [comment]
Okay, that process makes sense. I didn't know that there is an admin functionality to send a "delete" command but I guess the admin would just manually delete the files associated with the user account?

**Comment by jochenwezel** [comment]
yes, the files on the Server have to be deleted as usual - just that the user account "keeps alive" as long as all known devices synced the many file deletions

**Comment by davivel** [comment]
The functionality that @jochenwezel talks about requires server side support. At this moment is not available, as far as I know, and I don't know what are the plans regarding.

About the deletion controlled by the user, it's a different functionality totally on the device side. I'm not sure what was the original intention of @svenclemens for this issue, maybe you can clarify it.

In any case, both could be implemented, or just one of them.

Thinking in only the device side, deleting the files when the user removes the account **from the OC app** is easy to do as @tobiasKaminsky points.

The big deal here is deleting the files when the user removes the account **from the 'Accounts' section in device settings** (see 'Settings' > 'Accounts' > 'ownCloud' in your phone). Would be ideal to receive a broadcast ```Intent``` from the system when an account is removed, but there is not ```Intent``` like that.

Right now ```FileDownloader``` and ```FileUploader``` implemenet the interface  http://developer.android.com/reference/android/accounts/OnAccountsUpdateListener.html```  to stop transfers of an account when it's removed. But this method requires an already live ```Context``` to register through the ```AccountManager``` (an open ```Activity```, a running ```Service```...). This means that if the app is completely off, there is no way to wake it up on an account removal from the device settings.

Anyway, removing from the OC app could be nice enough for most users.

**Comment by svenclemens** [comment]
@davivel My original intention for this issue was that (shared) files on the device should get deleted after the related account was removed from the device.

But as @jochenwezel idea is very close to my intention I would see it as an addition to my issue.
I would like to see both of this features implemented in the app.

In a business or large-scaled environment it would be useful to have both, the possibility to remove files with account deletion from the server and also the guarantee the files will be removed if an user blocks the deletion by removing the account from the device.

**Comment by jancborchardt** [comment]
This is not an enhancement but a bug. People expect all data of the app to be removed when they uninstall it.

**Comment by jancborchardt** [comment]
Same when uninstalling the app – all files remain, and this actually could be seen as a privacy issue because I expect my data to be gone.

cc @davivel @MTRichards @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
Remving local downloaded files when removing the corresponding account seems to be manageable, see @tobiasKaminsky' comments. Doing this when removing the app is a bit more complicated afaik since the app isn't called before deletion do do some cleanup. So as long as the data is within the app's installation directory it should get removed by Android automatically. If the data resides somewhere else than the apps directory it basically will stay there. So if I am not mistaken this is by platform design. Only bug possible imho could be that the data in the app directory isn't removed....

**Comment by jancborchardt** [comment]
> So as long as the data is within the app's installation directory it should get removed by Android automatically. If the data resides somewhere else than the apps directory it basically will stay there.

By default, the data is in the installation directory, right? If ppl change it (e.g. using external storage) then it’s fine if it stays there on uninstall. But by default it should work.

**Comment by AndyScherzinger** [comment]
Exactly, yes! Is there any occurrence of this not being the case with latest releases?

**Comment by davivel** [comment]
> By default, the data is in the installation directory, right?

Wrong. File contents always are in external storage from the very beginning of the app existence. That's why this is not a bug, but I'm not entering in a semantics discussion here.

> Removing local downloaded files when removing the corresponding account seems to be manageable.

When the account is removed from the app, easy, and I wouldn't ask to the user. When the account is removed from 'Device settings' , not easy at all, and the most important reason to not having this done yet, probably. 


> So as long as the data is within the app's installation directory it should get removed by Android automatically. If the data resides somewhere else than the apps directory it basically will stay there. So if I am not mistaken this is by platform design.

That.

**Comment by jancborchardt** [comment]
Sooo

>File contents always are in external storage from the very beginning of the app existence.

is this the right way to do it? Seems not, or what am I hearing from @AndyScherzinger's comment?

**Comment by hodyroff** [comment]
@Peter-Prochaska 
Nothing changed here with newer releases I assume?

**Comment by Peter-Prochaska** [comment]
Hi @hodyroff, i don't know this case

**Comment by theScrabi** [comment]
Maybe we can add a allert dialog when deleting an account, in order to ask the user weather he wants his files should be deleted or not.

**Comment by michaelstingl** [comment]
@theScrabi Okay, this would at least solve a part …

**Comment by theScrabi** [comment]
Well but as @davivel states, it is complicated to remove the files if the account was deleted from android settings, and its impossible to delete them if the app gets removed.

So if I'm writing such a dialog it would only work if a user removes an account from the app it self. @michaelstingl @davigonz what are your thoughts about this?

**Comment by jesmrec** [comment]
Done!
