### ISSUE TITLE
Playing MP3 fails / file not downloaded

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1250]
Open MP3 file. Toast appears: "Cannot read media file".
Clicking play shows toast: "File does not belong to valid account"
Switch screen off and on: Media player is gone, instead file details view is shown. I still expect to see the player.

Is this behavior beta specific? (I do not have the latest original version installed.)

**Comment by tobiasKaminsky** [comment]
This is the default behaviour of the normal app: After an error there is no possibility always this false message occurs

**Comment by LukeOwncloud** [comment]
An option would be to close the player if file cannot be played or disable the play button.

But the actual problem is that it does not play any MP3 files at all. Does it work for you?

**Comment by LukeOwncloud** [comment]
Got it. Clicking an MP3 file does not start the download. It just opens the player which can then of course not read the file.

**Comment by tobiasKaminsky** [comment]
It should stream the file...
Currently I do not know why this does not happen.

**Comment by tobiasKaminsky** [comment]
Can you stream the file with an external player like vlc or MX?

**Comment by LukeOwncloud** [comment]
How would I do that? Which URL? How to authenticate?

**Comment by LukeOwncloud** [comment]
Do I need to install the music app? I just see experimental version 0.3.4 which just broke everything (`HP Fatal error:  Class 'OC_Search' not found in ..../owncloud/apps/music/appinfo/app.php on line 69`)

**Comment by LukeOwncloud** [comment]
Oh, that is not nice. A more music app (0.3.8) is available in tab "multimedia" , whereas "not installed" only lists experimental version 0.3.4. Sounds like an issue to report, doesn't it? Do you have an idea where? Core? Music app? Updater app?

**Comment by LukeOwncloud** [comment]
What is more important. Also enabling that music app does not solve this issue.

**Comment by tobiasKaminsky** [comment]
The authentication is part of the url:
http(s)://user:pass@ownloud.server.de/path/to/file
In fact streaming is nothing else than a slow download (if we omit the seeking part).
Therefore the music app is not required.

So, basically go to an audio file, say "stream with external app" and choose vlc/mx player and it should work.

**Comment by tobiasKaminsky** [comment]
ping @LukeOwncloud 
The music app is not required at all for streaming/android app.

**Comment by LukeOwncloud** [comment]
@tobiasKaminsky 
Passing user name and password via URL has no effect. I am redirected to the login in screen.

I checked the server log:

    IP - - [23/Nov/2015:13:36:02 +0100] "GET /remote.php/webdav/path/my.mp3 HTTP/1.1" 401 2534 "-" "stagefright/1.2 (Linux;Android 4.2.2)"

Note that there is no user name (between first and second -). So it seems the music player inside the oC app tries to download the file without authentication.

**Comment by tobiasKaminsky** [comment]
https://test:test@demo.owncloud.org/remote.php/webdav/Demo%20MP3%20-%20E.J.%20-%20Blick%20Zur%C3%BCck.mp3

This is the URL of a test audio file in demo.owncloud.org
If I copy this link to vlc it works. Unfortunately vlc or mx player is not opened when selecting "stream with external app". but this is maybe related to android 6.0

**Comment by tobiasKaminsky** [comment]
Have you tried it again?

**Comment by LukeOwncloud** [comment]
Still does not work. 

What does work:

- Open https://user:pwd@myserver/remote.php/webdav/path/my.mp3 in browser (download begins)
- Open https://user:pwd@myserver/remote.php/webdav/path/my.mp3 with VLC (music plays) (only works if path does not include spaces because VLC replaces space with ``+``, whereas owncloud server requires `%20`. But this is another (server) issue.)

What does not work:

- Use owncloud beta to browse to file path/my.mp3 and tap it (toast: Cannot read media file). 

I found following difference in the apache log:

    Firefox - WORKS
    myserver - - [01/May/2016:21:25:09 +0200] "GET /remote.php/webdav/path/my.mp3 HTTP/1.1" 401 1267 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
    myserver - user [01/May/2016:21:25:10 +0200] "GET /remote.php/webdav/path/my.mp3 HTTP/1.1" 200 1191192 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"
    
    owncloud beta - FAILURE
    31.16.209.100 - - [01/May/2016:21:26:18 +0200] "GET /remote.php/webdav/path/my.mp3 HTTP/1.1" 401 2724 "-" "stagefright/1.2 (Linux;Android 4.2.2)"

So it seems that the problem is that the client does not send username and password.

**Comment by LukeOwncloud** [comment]
Same problem when trying to stream a file from demo.owncloud.org. Does it work for you you? 

Android 4.2.2
Beta version 20160427

**Comment by LukeOwncloud** [comment]
Option "stream with external app" does not do anything.

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)
