### ISSUE TITLE
Disable PIN without entering PIN

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1251]
It is possible to disable the app PIN without entering the PIN. 

When PIN is enabled, go to settings dialog, uncheck according checkbox. New activity is opened asking for pin. Ignore dialog and press Android's last apps key. Swipe out owncloud app (thus close it). Start owncloud app again. It does not ask for PIN anymore.

**Comment by przybylski** [comment]
fixed by https://github.com/owncloud/android/pull/1296

**Comment by davivel** [comment]
Will be released in version 1.9.1.
