### ISSUE TITLE
Beta: 2015-11-05 Share with users in the menu does not work

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1260]
When a file or folder is selected by long press, menu Share with users does not work.

As a consequence, folders cannot be shared.

But great work!! Just letting You know, I was missing this feature so much! It was one of the few reasons to enter the web interface..

**Comment by tobiasKaminsky** [comment]
This is resolved in the next beta.
Please test and comment it.

**Comment by LukeOwncloud** [comment]
Works for me with version 20151109. @elpraga please double check!

**Comment by elpraga** [comment]
Confirmed! Works in beta 20151109
