### ISSUE TITLE
Share with users menu is missing detailed options

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1261]
Thank You Tobias for bringing this possibility to share with ownCloud users!! 

I suppose that You plan to add the options of sharing for files and folders (can share, can edit,  access control - create, change, delete), as it is important to be able to set the folder readonly when sharing..

I just wanted to leave the mention that they are missing for now.

Thank You sooo muuuchh!!

**Comment by tobiasKaminsky** [comment]
Sharing with ownCloud users is developed by @davivel and @masensio. All credits belong to them :)
This feature is only in beta as it is also in master and will be in the next release.

Therefore I remove the beta label from the topic.

**Comment by elpraga** [comment]
Big thanks to @davivel  and @masensio ! That was one of the last reasons why I had to use the web interface. It would be great to have it in the app as it it difficult to use the web interface on mobile devices.
Do You plan to implement the full set of options?

BTW.
...y sería una coincidencia muy grande.. ¿No sois de Sevilla, por casualidad?

**Comment by rperezb** [comment]
@elpraga yes, we plan to release firstly the option to share with users and then to add further features such as being able to handle privileges.

BTW...hehee no, Valladolid :)

**Comment by elpraga** [comment]
That is good news! Many of my family members are not too tech savvy so many times I have to share the folders as "read only" so that they don't erase my files by accident :- D

.... Valladolid ... Still close enough! :+1:

**Comment by elpraga** [comment]
Great! all options landed in Beta 20160201!

Thanks so much! Great work!
