### ISSUE TITLE
Beta: add some kind of indication of which build I am using. 

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1264]
I thought that I could use the "View Changelog" menu entry to check which version am I using, but I just noticed that it opens: https://raw.githubcontent.com/owncloud/android/beta/CHANGELOG.mg , which I believe is the changelog for the whole branch.

I almost reported an issue using old build (I installed newer build on the phone yesterday, but not on the tablet, and I used the tablet today)

Adding some kind of indication to identify the build in the app would be nice. Especially for filtering dumb mistakes like the one I almost made.. :sweat:

**Comment by LukeOwncloud** [comment]
@elpraga I think you are looking for this: https://github.com/owncloud/android/issues/1246
So I close this issue. Please reopen if necessary.
