### ISSUE TITLE
Beta: 2015-11-05 Deleting a local copy when viewing in fullscreen throws me back to directory listing

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1266]
When I preview the photos in fullscreen and I decide to download the original, the preview gets replaced by the original when the download is finished. That is nice.

When I view an original in fullscreen and then decide to delete it, I think, I should be presented with the large preview and stay in fullscreen mode. Do You agree with me?

**Comment by LukeOwncloud** [comment]
Yes, I'd agree with you.

**Comment by tobiasKaminsky** [comment]
Then there would be no visual feedback that the file is removed, or?
So I would stay with the way it is as the user does not want to have the file...?
cc @jancborchardt

**Comment by elpraga** [comment]
Well, sometimes I just browse the photos in full-screen and if I don't want
the original I delete it and continue browsing the previews, but I would
expect to stay in the current view.

Much in the same way we stay in it when we download the original. We see
the resolution change and the change in the menu, it is our indicator.

I mention it because the full-screen viewing is great when you need to
clean you phone from some pictures. I can go over the previously downloaded
folder and easily erase the photos that are not so great to keep the
original.

I certainly use the full-screen as a third viewing mode (list, grid,
full-screen), not just to open one picture.

**Comment by jancborchardt** [comment]
As @tobiasKaminsky said, the current solution is good feedback. It’s normal that when you delete the current file, a viewer having it open is closed.

We could also move to the next file, but what is the »next« file? Next image, next document – older, or newer? All things which will be a bit confusing and people will come asking for settings to change which file is shown next.
