### ISSUE TITLE
Beta: 2015-11-05 Suggestion: Make the list / grid view a simple toggle

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1267]
I was very happy when You introduced the possibility of using the grid view for all folders as I have many forlders with both documents and pictures or scans. Sometimes I do switch between the views as both have its advantages.

When I was using the beta now, I found out that it is a little schizofrenic when EACH folder remembers the last viewing method.

Several times I switched to grid view to look for some picture quickly, and I went through several subdirectories. Later I was viewing some of the diretories in list view.

After some time I ended up with directories (seemingly) randomly switching between grid and list views as I was  going through them. It was kind of.. odd behaviour.

I think it would be better to have the grid/list as a mode switch like in other file managers. (When You use Nautilus or anything else, Your view also doesn’t switch from icon to list view as You go through the directory tree). 

Do You agree with me or do You have a different reason to have the view remembered for each folder?

**Comment by LukeOwncloud** [comment]
This was discussed here https://github.com/owncloud/android/issues/1081 and here https://github.com/owncloud/android/pull/1099. Please follow those disscussions.
