### ISSUE TITLE
When viewing the downloaded original with the app it seems to show less details then viewing the same picture with another  app

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1268]
I was really trying to make sure it is not an illusion, but I can confirm it now. When I view the original in OC app it has fewer details (and also allows less zooming in) then QuickPic on the very same picture.

It there any technical reason for this behaviour? I was using the app on my tablet with android 4.1.1.

Please, let me know if I can provide other information that would be useful to You.

**Comment by LukeOwncloud** [comment]
Are you saying the photo is of lesser quality? Or are you simply referring to the maximum zoom level?

**Comment by tobiasKaminsky** [comment]
I think this is independent from beta as beta only has resized images.
We would have to look into good, but I guess that the ImageView which handles the image displaying is somehow limited.
This happens also to the official version.

**Comment by elpraga** [comment]
@LukeOwncloud both. The original photo had less details in OC app compared with QuickPic using the same zoom level, and I couldn't zoom in as far.

Do you want me to try it on my other device as well?
