### ISSUE TITLE
ownCloud requires new permission READ_PHONE_STATE

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1272]
I just noticed that the beta version uses a new permission. I tracked the origin of the change down to the master branch: https://github.com/owncloud/android/commit/905b68b4ec886cff35799c0e0604383d9f1d245b#diff-a48d6def78e18cbabab3c95ae3c9fc49R44

I created a comment there but I wanted to create an official issue as well, since I deem this important.

``READ_PHONE_STATE`` allows to access a lot of information about the phone, including the IMEI of the phone and details about the SIM card. Is this really necessary? Was it added by accident? I do not find any usage of ``TelephonyManager`` which would require the permission.

**Comment by davivel** [comment]
Probably it's an accident. We'll double check.

Thanks, @LukeOwncloud

**Comment by davivel** [comment]
Fixed in https://github.com/owncloud/android/commit/d145bb16b71eb83304b78e6e1201b38b66bde03c  (release-1.9 branch).

**Comment by elpraga** [comment]
This bug is still present in Beta app, can it be fixed in there as well?

**Comment by elpraga** [comment]
@davivel I am sorry to notify You directly, but as the issue is marked as closed, I am not sure it my previous comment gets to You or not.

**Comment by AndyScherzinger** [comment]
@elpraga @davivel I just fixed this on the beta branch, so it will be in the next beta release - which is always done by @tobiasKaminsky (see commit https://github.com/owncloud/android/commit/77e72f24ecb2a15d4a4d381563b596a61c84e4c5)

**Comment by elpraga** [comment]
Thank You @AndyScherzinger ! I will check it out in the beta release.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger Thanks!
The next beta will be compiled today or tomorrow.
