### ISSUE TITLE
Temporarily showing "Nothing in here. Upload something!"

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#1273]
When browsing into a new folder it displays "loading...", then for a glimpse "Nothing in here. Upload something!" before it shows the actual content.

**Comment by tobiasKaminsky** [comment]
This happens also on the official client, therefore removing beta label.

**Comment by malkomich** [comment]
Yes, it could be confusing for eagle eyes, so we have to review this behaviour :smile:
