### ISSUE TITLE
Resized images: show small thumbnail while loading resized image

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1278]
@elpraga
> Would it be possible to use enlarged small definition thumbnails instead of the circle until the big thumbnail is available? In the same way google does it when looking at searched images in Chrome on Android? It could be a nice usability improvement. 
Related to #1044

**Comment by tobiasKaminsky** [comment]
@elpraga but we must keep the thumbnail to max twice the size to prevent it from being blurry.
The spinning wheel is needed below the thumbnail?
@jancborchardt for design ;)

**Comment by elpraga** [comment]
I think that showing a blurry thumbnail until the preview is loaded would be a step forward from showing a black background. At least we would have an idea what picture we are viewing.. And the spinning wheel would tell us that something is going on and we should wait..

**Comment by jancborchardt** [comment]
Yep, sounds like a great idea! Mich better than not knowing at all which image you are loading, especially when swiping through yet undownloaded files.

**Comment by tobiasKaminsky** [comment]
I have implemented it. But this will only work if there is already a thumbnail (which might be not there if swiping in preview mode through a very very big folder with images).
Please test it in latest beta :)

**Comment by elpraga** [comment]
Wow!
It is such a leap in usability Tobias! If there is no previous thumbnail there is nothing that can be done, but now we at least have a clue what we are looking at!

I tried it out with both my tablet and Nexus5. Nexus generates 384-384.png and the tablet 128-128.png. Enlarged thumbs on Nexus look great, on tablet they are blury, but I can at least recognize this picture I am viewing.

I am not sure if it would be useful to add the rotating circle before the preview is loaded - something like saying -- wait, it will get better in a moment. But I am really not sure about it now, as after doing it once, You will remember the behaviour. 

It is a huge leap forward!

**Comment by tobiasKaminsky** [comment]
Glad to hear that it works as excepted!
Regarding the rotating cicle: Let us wait what other people say.
(And it is a little tricky to have the spinning circle on top of the thumbnail...)

**Comment by elpraga** [comment]
I totally agree, I was just thinking to add that for no tech savy people, so there is an indication that something is coming up. I don' t have a strong opinion about this at all.

Thanks again!

**Comment by tobiasKaminsky** [comment]
So I close it for now. 
If needed we can reopen it or create a new issue.

**Comment by jancborchardt** [comment]
@elpraga thank you for the awesome suggestion! :) You are very welcome in our IRC channel #owncloud-design (on freenode IRC) and to open more issues with design suggestions.

**Comment by elpraga** [comment]
Thank You @jancborchardt ! I am glad I can be of little help. I think You guys are doing a great job. I do use OC on daily bases, and I will definitely share any ideas I might have..
