### ISSUE TITLE
Cannot unshare renamed file

### ISSUE THREAD

**Issue by liamdennehy** [owncloud/android#1280]
In Android client:
1. Share a link to a file
2. Rename file
Link still works
3. Unshare file
Error: cannot unshare file, make sure it exists
4. Rename file to original name
5. Unshare file 
Share is removed 

If the original name is unknown, file can never be unshared. Unknown if issue exists on Web interface.

UPDATE: Behaviour is inconsistent. Just unshared a renamed file a few minutes after test above and it worked. Now also able to unshare a file that was stuck for an hour. Retry of test procedure reproduces result.

**Comment by malkomich** [comment]
Please @liamdennehy , can you update to current version and check if it is currently fixed ?

It seems that now it is working fine. If it is, you can close this issue by yourself, otherwise, let me know :smiley:

**Comment by jesmrec** [comment]
Not reproducible anymore.
