### ISSUE TITLE
ownCloud beta name capitalization

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1288]
@tobiasKaminsky judging from the latest .apk, the current name is »Owncloud Beta«. The correct capitalization should be »ownCloud beta«. :)

**Comment by przybylski** [comment]
Close it maybe?

**Comment by tobiasKaminsky** [comment]
You are right :)
Thanks for your commit

**Comment by przybylski** [comment]
Anytime :) I would commit more if I just had contributor :)

**Comment by jancborchardt** [comment]
@karlitschek can you add @przybylski to the ownCloud organization and the Android team?

**Comment by karlitschek** [comment]
done :-) Wecome back!!!
