### ISSUE TITLE
InstantUploud does not upload raw photos

### ISSUE THREAD

**Issue by wolf12621** [owncloud/android#1294]
Since Android 5.0, Android has a new camera api with the ability to save the photos as *.dng. This is a raw format and very interesting for photographers. Apps like "Camera FV-5" support this feature.

### Expected behaviour
All Images/Photos will be uploaded into my owncloud, when a made a new one.

### Actual behaviour
The instantUpload is uploading the *.jpg and not the *.dng file. The files are in the same folder and the files are written in the same moment.

### Environment data
Android Version : 6.0
Device model : Google Nexus 5
Stock or customized system: Stock
ownCloud app version: 1.8.0
ownCloud server version: 8.2.0

**Comment by przybylski** [comment]
I am do not support nor oppose this feature, since *.dng might be very big files it would increase time and bandwidth spend on uploading a file. Instead I would introduce a switch in settings which would indicate the preferred upload image filetype.

**Comment by wolf12621** [comment]
I think it is a good suggestion. Your are right. The file sizes can be hugh and might not an ideal solution for everyone. An Entry Point in the settings would be a proper solution for me.

**Comment by tobiasKaminsky** [comment]
As we are using the broadcast NEW_PICTURE I doubt that we get anything else than a jpg:
http://developer.android.com/reference/android/hardware/Camera.html#ACTION_NEW_PICTURE

**Comment by wolf12621** [comment]
sure, with the old api. Has anyone experiences with the new api? Is there something similar? 
https://developer.android.com/reference/android/hardware/camera2/package-summary.html

I don't have luck with my quick google search. :-(

**Comment by przybylski** [comment]
I'm planning to acquire nexus 5x next month, then I can have a look ;)

**Comment by AndyScherzinger** [comment]
Can check next week when the USB cable arrives, N5X is already in my hands :)

**Comment by AndyScherzinger** [comment]
Besides that camera 2 is an 21 Api level feature thus should already be available on older phones :)

**Comment by tobiasKaminsky** [comment]
#744 can also solve this: Maybe we should go away from instant upload but go to "folder upload"?

**Comment by wolf12621** [comment]
sounds good for me

**Comment by przybylski** [comment]
Instant upload was designed to work with photos and OC gallery. But then I left OC community ;)
I would vote to leve Instant upload as it is but allow folder synchronizacion as additional feature

**Comment by Bugsbane** [comment]
From a UX perspective, it seems very strange to have the user specifically ask the app to upload all photos, but then have the app - by design - then not upload a specific set of photos without even warning the user.

**Comment by ids1024** [comment]
I think this would be good to have as an option if possible, and I would expect that the camera2 api can do this.

**Comment by davivel** [comment]
@wolf12621 , from the description you made, just-released version 2.1.1 should solve your problem. Would you like to try?

Please, remember to set your camera folder in the new option in the instant upload settings.

Could you also report your feedback in issue #760 instead of here? This issue is duplicating the target.

Thanks!
