### ISSUE TITLE
Beta 20151120 All pictures are shown in fullscreen even though on device is selected

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1297]
What happens:
I select "on device" from the sliding menu on the left. Both list and grid views show only files on device. Nevertheless when I list through the pinctures in fullscreen, I still list through all picutres in the directory.

What I expect to happen:
When I select "on device" I expect to see only the photos on device when I list through in fullscreen.

Hope I managed to explain myself :smile: I am not sure if current behaviour is intentional or not.

**Comment by tobiasKaminsky** [comment]
Thank you very much for testing!
Your bug reports are really a great help! :+1: 
This is fixed in beta. Please verify and then close.

**Comment by elpraga** [comment]
Fixed in Beta 20111121
