### ISSUE TITLE
Change storage path: folder already exists

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1299]
Due to playing with the changing storage path feature I managed to move the folder to a parent folder where "owncloud-beta" already exists. At this point it stops.
Maybe a question if the app should proceed and write into it (and maybe overwrite something) is a useful idea?

**Comment by przybylski** [comment]
I was trying to prevent overriding. The scenario which I was thinking about was:
User has Documents dir on his external card with a lot of dirs. He wants to move it there but he also have some important stuff for/about owncloud :) and he accidently overrides it.

If anything I would suggest to add dialog "Directory owncloud already exists" do you want to override it ?"
Then erase the directory and do proceed with migration.

I also noticed that dir selection activity got "move" or "copy" radio, I haven't add that and migration mechanism is not taking that into account (at least the one written be me). Did you implement that or is it just the stuff which is coming from UploadFilesActivity ?

**Comment by tobiasKaminsky** [comment]
You are right, as the owncloud dir needs to be in sync with the database it will not really work if the files are written in an existing directory.
So I think it is just fine the way it is.

"move" and "copy" is pulled in by another PR (avoidDuplicateFiles) that is merged in beta.
I do not know how to solve this is an sane way:
We cannot change it in one of the two PRs as they are on its own.
Maybe we need to create a new PR that is merged once the two PRs are in master?

**Comment by przybylski** [comment]
Yup, new PR after merges sounds fine.

**Comment by tobiasKaminsky** [comment]
The new PR is done in #1303, right?
As my initial question is solved I close the issue.
