### ISSUE TITLE
Some images cannot be shown in the Owncloud application

### ISSUE THREAD

**Issue by mathieupoussin** [owncloud/android#130]
### Expected behaviour
When I click on an syncronized image, it should opens

### Actual behaviour
When I click on a synchronized image, it shows "This image can not be shown" (on 15% of the images, maybe more)

### Steps to reproduce
1. Synchronize a remote image
2. Click on it
3. Confirm that the image is correctly downloaded and not corrupted by opening it in the Android File Browser

### Environment data
Android version: 4.1.1

Device model: Samsung Galaxty Tab 10.1

Stock or customized system: Stock

ownCloud app version: 1.4

ownCloud server version: 5.0.4

#### Web server error log
[Non, it's local]
Insert your webserver log here
[None, it's local]

#### ownCloud log (data/owncloud.log)
[None, it's local]
Insert your ownCloud log here
[None, it's local]

Attached here is the image that is impossible to open on the Android application, as it to have the same data than I do (Sorry it's a pretty big image)
![24 Place des Vosges 003](https://f.cloud.github.com/assets/359877/396288/b61ac9f2-a81d-11e2-9b08-49734ada66a2.jpg)

**Comment by davivel** [comment]
@mathieupoussin , is this still a problem for you? Thanks in advance.

**Comment by mathieupoussin** [comment]
I can't tell you.
I don't any Android device anymore to test this.

**Comment by tobiasKaminsky** [comment]
Then we can close it (although we cannot know if this will happen again)

**Comment by davivel** [comment]
Thanks anyway, @mathieupoussin .
