### ISSUE TITLE
Change storage path: files are only copied?

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1301]
I saw that the original folder remains after changing the storage path?
Is this intended? As the UI says "moving" I thought that the old folder will be removed after a successful copy?

**Comment by przybylski** [comment]
This is something which was coming from UploadFileActivity which I mention about in here:
https://github.com/owncloud/android/issues/1299
The original design was always to move (via coping) directory structure, perhaps something is altering the default behavior, I'll check that.

**Comment by przybylski** [comment]
Fixed in https://github.com/owncloud/android/commit/ce4a8bc47743c2c388c7cf6d1c676bbb75a0af2b
