### ISSUE TITLE
Share: unspecific error message

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1308]
Hi,

I wanted to use "share with users", but all I got was:
Sorry, your server version does not allow share with users within clients.
Please contact your administrator

Although I am the admin I was clueless ;)
After digging in the code the problem is that my server is 8.1.x and not 8.2.x.

So I suggest to change the error message to:
Sorry, your server version is 8.1.2 and sharing with users within clients is supported by at least 8.2.0. Please upgrade the server (or similar).

**Comment by alve89** [comment]
This is issued in Android. I got the same error message right now on iPhone iOS 9.1. So it is not os-specific.

**Comment by tobiasKaminsky** [comment]
This might be possible, but it is definitively an android issue as it android code that generates the error message and is not only a redirected server message.

**Comment by tobiasKaminsky** [comment]
cc @davivel @jancborchardt

**Comment by jancborchardt** [comment]
Agree. Let’s simplify the message a bit though:

> To use sharing with other users, your server needs to be at least version 8.2

Sounds a bit more understandable and something you would actually say. That’s a rule of thumb for any message: It needs to be something you would actually say to someone personally, not something technical.

**Comment by tobiasKaminsky** [comment]
:+1: Yeah, this is clearer and much easier to implement :)

**Comment by masensio** [comment]
Hi @all,
this message isn't provided by the server.
The app checks if the server version supports the searching of users and if this feature is available (it could be disabled by the administrator). The client shows this message if the feature isn't available because of any of these reasons. 
So if you say "To use sharing with other users, your server needs to be at least version 8.2" maybe it isn't your problem. You can have a 8.2 server and the share with users can be disabled.

**Comment by tobiasKaminsky** [comment]
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/authentication/AccountUtils.java#L292

This is used to check if the server supports sharing otherwise the error message is displayed.
I cannot see a check for enable/disabled sharing feature?

**Comment by davivel** [comment]
Hi, @tobiasKaminsky . 

There are other checks, but don't result in a message, they silently hide the share feature. I will double check this case.

**Comment by davivel** [comment]
This is what happens now if server version is lower than 8.2, and Share API is enabled:

![now_00](https://cloud.githubusercontent.com/assets/2225614/11722458/10a801ec-9f69-11e5-9fec-40ab23a3e7e4.png)

![now_01](https://cloud.githubusercontent.com/assets/2225614/11722461/14a64556-9f69-11e5-9216-2aa08c86dd82.png)


This is my proposal:

![proposal](https://cloud.githubusercontent.com/assets/2225614/11722470/1c6dc67e-9f69-11e5-8718-36724ac474a4.png)

**Comment by davivel** [comment]
And this is also other proposal...

**Comment by jancborchardt** [comment]
Yeah, good call on that @davivel – showing the message directly instead of the sharing elements is definitely the best.

**Comment by AndyScherzinger** [comment]
Nice one! I also think this would be the best way to deal with this :+1:

**Comment by tobiasKaminsky** [comment]
But this message can be wrong, or?
As @masensio said:
> So if you say "To use sharing with other users, your server needs to be at least version 8.2" maybe it isn't your problem. You can have a 8.2 server and the share with users can be disabled.

There must be a check if the version or the permission to share is the problem...

**Comment by ekeitho** [comment]
When I turn off the share api or exclude a group from sharing, there isn't an option to share from the settings nor from a long click. So is checking the share permission necessary?

**Comment by tobiasKaminsky** [comment]
Yes this is being checked at FileMenuFilter.java: capability.getFilesSharingApiEnabled().isTrue()

And this must be distinguished in the message:
- To use sharing with other users, your server needs to be at least version 8.2
- To use sharing with other users, your server needs to have share api enabled

**Comment by jancborchardt** [comment]
@tobiasKaminsky just a wording fix for the second sentence: »your server needs to have Sharing enabled«.

Also the first part: »To share with other users, …«

**Comment by jesmrec** [comment]
Approved

CC @davivel @davigonz
