### ISSUE TITLE
Beta: storage path setting too present

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1309]
In the current beta, the storage path setting is shown as first entry in the settings. That’s way too present since it’s a one-time setting, if anything.

It should be in the same section as the Cache size. cc @tobiasKaminsky @AndyScherzinger @davivel

**Comment by tobiasKaminsky** [comment]
This belongs to #1293 by @przybylski

**Comment by przybylski** [comment]
ok

**Comment by przybylski** [comment]
This question will be stupid but where is cache size preference? :)
I wanted to move storage path to other place but I'm not sure where :)

**Comment by tobiasKaminsky** [comment]
Cache size is in Category "Common".

**Comment by przybylski** [comment]
I think I need to rebase, I see no common category :)

**Comment by tobiasKaminsky** [comment]
Oh. This is introduced by me with #1195 
So put this <PreferenceCategory android:title="@string/common_category" android:key="common_category"> right after the instantUpload category.

This will produce a merge error, but as this is very obviously it should not be a problem.

**Comment by jancborchardt** [comment]
»Common« should also be renamed to »Details«.

And we should probably move the security code in there as well (as first entry) becaise currently it's just a single entry between the accounta and instant upload.

**Comment by tobiasKaminsky** [comment]
This should the be done in a new PR to keep the issues separated.

**Comment by tobiasKaminsky** [comment]
please see #1314 for renaming section

**Comment by przybylski** [comment]
There is still something which bothers me about the whole issue. In all places in code where storage is accessed ownCloud is using getExternalStoragePath which always returns path to external storage only if it exist. Otherwise it points to simulated storage. Did anyone actually tested that oc is using internal storage instead of external one?

**Comment by tobiasKaminsky** [comment]
I cannot test as I only have internal storage ;)
But is this not replaced by your code?

**Comment by przybylski** [comment]
I cannot test it as well because I also have nexus 4 :)

But using external storage was there since day one

**Comment by AndyScherzinger** [comment]
Can't test it either, also only having Nexus devices.

**Comment by jancborchardt** [comment]
Hehehe homies – I _do_ have an external storage so I guess I’m the authority for this and #1310 ;)

**Comment by przybylski** [comment]
@jancborchardt could you please check if owncloud is putting files on your external storage? IMO it should that from the very beginning

**Comment by jancborchardt** [comment]
No it doesn’t. There’s only an empty cache folder on the SD card in the `Android/data/com.owncloud.android` folder for both the normal and beta version.

I assumed we postponed that anyway. cc @davivel?

**Comment by tobiasKaminsky** [comment]
@jancborchardt @przybylski can you both try to solve this issue?

**Comment by przybylski** [comment]
I'll ask a friend with phone with SD card for some help. Currently I'm more guessing than developing ;)

**Comment by tobiasKaminsky** [comment]
:+1: 
I can test also, but I guess that it is more time consumption than helpful if you do a change and I test and report back to you...

**Comment by tobiasKaminsky** [comment]
Please have in mind that (at least in android 6) there are two different sdcard "types": formatted as internal storage / as external sd card

**Comment by przybylski** [comment]
Yeah, internal/external memory is generally a weird thing in android.
Version 6.0 also changes the way of handling sd cards so for now this feature is < 6.0

**Comment by tobiasKaminsky** [comment]
:+1: 
If you write code to support 6.0 please let me know as I can test it.

**Comment by przybylski** [comment]
I did another change, it works fine on old huawei, and should work on 6.0 as well.
@tobiasKaminsky please update beta when you'll fine a moment

**Comment by michaelstingl** [comment]
Beta feature never got released. Information is in the open PR (https://github.com/owncloud/android/pull/1293)
