### ISSUE TITLE
[Duplications] [1168] Wording not clear

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1311]
With the branch: https://github.com/owncloud/android/pull/1168
Access to settings:
 It's included a new option under the Instant upload section: "Behavior: Do nothing"

- This is not pretty clear to me its aim (without having the background of github discussions :smiley:  @MTRichards @jancborchardt any suggestion here?

![duplications](https://cloud.githubusercontent.com/assets/1846927/11418230/650404a8-941e-11e5-94eb-bb0e7f7095cc.png)

- On the other hand, when you tap on it, you may change the options
![settings](https://cloud.githubusercontent.com/assets/1846927/11418229/6502c73c-941e-11e5-8a1c-d4929be364c9.png)

@tobiasKaminsky not sure about the difference between:
- move file to OC folder and delete origin file 
- do nothing - probably, we should define a default mode which I'd say: copy file to OC folder
:question:

**Comment by tobiasKaminsky** [comment]
I am clueless about the wording ;)
I thought it is clear, but maybe only for me.
If our app has finished an upload it can either 
- duplicate the file by copying it to the owncloud folder
- "do nothing" and keep the file in its original place
- move the file from its original place to the owncloud folder.

Most user complain about the duplicating (which is by now the current behaviour).
And I guess most of them are fine with the behaviour "do nothing".
Maybe we can rename it to "simply upload"?

The wordings come from the first part of the dialog window: Upload file to server and ...
I thought that it is clear with this prequel...

(I think the "1 - to develop" is for PR only. so best way would be to set this on the #1168 PR).

**Comment by rperezb** [comment]
Ok, I'd say, let's wait for @MTRichards input, he has really good ideas.

suggestions:
- Instead of behavior: Storage options

![settings](https://cloud.githubusercontent.com/assets/1846927/11439301/cfded62c-94fa-11e5-9775-e6814c852677.png)

- For the options:

![options](https://cloud.githubusercontent.com/assets/1846927/11439296/ce430716-94fa-11e5-861a-e0fef2d1fa84.png)

**Comment by tobiasKaminsky** [comment]
"Storage options" sounds good.
The other suggestion is too technically I think (1 vs 2 copies)
Besides that: what is local folder? You mean origin folder?

**Comment by MTRichards** [comment]
I think this solves a long standing issue where an Android user had duplicated files when they were added to ownCloud - 1 copy in the origin folder, 1 in ownCloud on the mobile device - doubling storage usage - and of course, 1 copy on the server.

This in particular is only for instant uploads, and allows a user to decide what to do about storing more than 1 image copy.

Should this option be under Instant Video and Instant Picture enabling options so it is clearer that this is for those two cases?

I like something like under Instant Uploads such as:

Instant upload storage
XXX (selected option here)

Then the menu would say:

Instant uploads on this device will be:
- kept in the ownCloud folder
- left in the origin folder
- copied in the origin and ownCloud folder
- removed from this device

@jancborchardt your thoughts?

**Comment by tobiasKaminsky** [comment]
This option is the first item in the "instant upload" category.
Your wordings seem fine to me :+1:

**Comment by MTRichards** [comment]
>This option is the first item in the "instant upload" category.

Right - but is there a reason it is first, vs. third?

**Comment by tobiasKaminsky** [comment]
Ah...I have misunderstood you.
My intention was similar to your idea: show that this option is for both: pictures and videos and therefore I put it first.
But with the same argument we can put it behind picture/video.

Shall I also change the wordings to your proposal?

**Comment by MTRichards** [comment]
Now that I think about it, either position works - let's leave it.

Just want a nod from @jancborchardt and we can change it.

**Comment by jancborchardt** [comment]
Right, I wanted to open an issue about this too, as I find position and wording confusing. :) Here’s what we should do:

- [ ] Move it to the third position as @MTRichards proposed above. Now it’s too present
- [ ] Only show it when one of either Image upload or Video upload is enabled. When nothing of that is enabled, showing this option does not make sense.
- [ ] Change the wording:

> Original file will be
> - Kept in original folder
> - Copied to ownCloud folder
> - Moved to ownCloud folder
> - Deleted from device

The thing though here is that this is too much unnecessary choice. There are not 4 equally relevant usecases. I would only have:
1. Kept in original folder
2. Moved to ownCloud folder

Because 1 is like it is now and 2 takes care of the duplicate case.
There’s no reason at all to delete it from the device (and actually a slightly strange thing to do cause you suddenly don’t have it offline anymore). And copying is … duplicating directly.

**Comment by jancborchardt** [comment]
Oh and the default should probably be »Kept in original folder« to not mess with anything, right? Duplication will only happen when you tap on a picture and download it.

@tobiasKaminsky @AndyScherzinger?

**Comment by AndyScherzinger** [comment]
@jancborchardt sounds good to me, even though I have to say I only took care of materializing the list view anything else is the work and achievement of @tobiasKaminsky.

I am fine with reducing it to just the two options even tough I am unsure if 4 isn't a use case for people with limited storage on their device (not everyone has a 32+GB phone) and thus using the client to basically move their photos to the cloud and free the space on their phone automatically.

Maybe we need to start implementing an expert mode like Google (hot the version number in the settings five times... "you are an expert now" adding further options :grin: 
Downside: bigger codebase
Upside: very flexible for a some (power)user base 
...Just an idea though to support both kinds of users :)

**Comment by jancborchardt** [comment]
> sounds good to me, even though I have to say I only took care of materializing the list view anything else is the work and achievement of @tobiasKaminsky.

I know, but wanted to make sure I didn’t miss anything, and you folks know most about the code. :)

> Maybe we need to start implementing an expert mode like Google (hot the version number in the settings five times... "you are an expert now" adding further options

We can still do that in the future if we really see that it’s not enough. But we should take small steps now, not too much scaffolding.

**Comment by AndyScherzinger** [comment]
I am fine with keeping it simple but just wanted to point out that there might be options in the future to also hide but allow more complex scenarios for some users in case it is worth the effort in our eyes ;)

**Comment by tobiasKaminsky** [comment]
@jancborchardt @rperezb I have changed it.
Please test :)

**Comment by jancborchardt** [comment]
@AndyScherzinger yup! It’s just important that we start small and go from there. :) That’s way easier than noticing we added too much and then take it away – cause then people will start complaining that something was taken away. ;)

**Comment by masensio** [comment]
Thanks @tobiasKaminsky for your quick change. 
We are testing and everything works properly at the moment.

I have some comments in the code, related with the options for instant uploads. 
With the last changes they are only used LOCAL_BEHAVIOUR_FORGET and LOCAL_BEAHVIOUR_MOVE for instant uploads, so LOCAL_BEAHVIOUR_REMOVE option is never used.
Maybe the code related with this option should be removed to maintain the code cleaner. If we need this code in the future we will have it in the repo.

**Comment by tobiasKaminsky** [comment]
I have removed the code.
In order to have this PR validated quicker, please feel free to do this changes by yourself :)

**Comment by tobiasKaminsky** [comment]
@rperezb @masensio Can this be closed?

**Comment by masensio** [comment]
PR #1168 is in master. I'll close this issue.
