### ISSUE TITLE
Beta 20151128 - is Cache size setting remembered?

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1315]
The default cache size is 10 Mb. When I input a number, let's say 50, it gets set up to 50 MB. When I close and open Settings, it says 50 Mb. When I close the app and reopen it, it states 10 Mb.

It the change remembered? and that are the units? Mega bits or Mega Bytes?

**Comment by tobiasKaminsky** [comment]
Uh.
I have already fixed this in branch resizeCache.
Now it is also in beta 20151129.

**Comment by elpraga** [comment]
It seems that the number is remembered in 20151129 now, but when You open the settings, the units are Mb, when You enter a number the units change to MB. When You leave the settings and enter them again, the units are Mb again..

Is the cache size in Mega bits or Mega Bytes? I am sorry to repeat the question, but it is quite a big difference and I down know how to find out myself..

**Comment by tobiasKaminsky** [comment]
It is bytes, so it would be "MB".
I will change it.
