### ISSUE TITLE
Crash upon start: NPE on FileDataStorageManager.prepareInsertShares

### ISSUE THREAD

**Issue by pecuna** [owncloud/android#1317]
Hello! I installed the beta client from fdroid an after entering login details I receive folowing message and have to close the app. Happens all the time. I can see the dirs for a short time every time I open the client but crash is following.

************ CAUSE OF ERROR ************

java.lang.NullPointerException
	at com.owncloud.android.datamodel.FileDataStorageManager.prepareInsertShares(FileDataStorageManager.java:1529)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1490)
	at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:495)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:216)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
	at java.lang.Thread.run(Thread.java:841)

************ DEVICE INFORMATION ***********
Brand: Lenovo
Device: Kraft-A6000
Model: Lenovo A6000
Id: KTU84P
Product: Kraft-A6000

************ FIRMWARE ************
SDK: 19
Release: 4.4.4
Incremental: Kraft-A6000-m_S025_151016

**Comment by tobiasKaminsky** [comment]
@davivel This has something to do with sharing? 
Can you have a look?
Maybe I have messed something up on merging, but it seems as "share.getShareType().getValue()" gives a NPE.

**Comment by masensio** [comment]
Hi @tobiasKaminsky,

I don't know if you have missed something on merge or not, but I've installed the beta version from f-droid (20151130) on a Nexus 10 Android 5.0.2. 
I've done login and access to the files without problems.

**Comment by tobiasKaminsky** [comment]
Yeah, for me (with 2 devices), my wife and a co-worker it is also working, but not for @pecuna...

@pecuna Can you tell us which owncloud server you use?
Does this also happen after a reinstall with clean data of the beta app?

**Comment by pecuna** [comment]
Still continues to happen with the owncloud server with selfsigned certificate, but on other with free ssl certificate I tried everything is ok on first look. So I think there is something wrong with selfsigned certificates. I have imported mine through CAdroid.

**Comment by tobiasKaminsky** [comment]
@davivel Do you have an idea here?

**Comment by pecuna** [comment]
I have the same issue now on the new stable ( 1.9.0 ). When I open the client with account on server with self-signed certificate the app gives me  "Unfortunately Owncloud has stopped working". Other account with certificate from the net (startssl) has no problems.

**Comment by tobiasKaminsky** [comment]
@davivel pinging
(removing beta label as @pecuna says the problem also occurs on stable)

**Comment by iskaron** [comment]
same error on my 1.9.0 - since switching my certificates from cacert to letsencrypt.

**Comment by iskaron** [comment]
A little more detail: I debugged the app, and found, that in my case, the NPE on share.getShareType().getValue() occurs for a shared entry. It is shared with another local user, and with another oc instance.

After removing the federated sharing, the NPE does not occur anymore. When adding back the federated share, the NPE appears again. The second oc instance is using self signed certificates.

**Comment by tobiasKaminsky** [comment]
pinging @masensio @davivel

**Comment by modules** [comment]
Same here. App crashes shortly after starting. I got that error on stable and beta version. Attached are the logs from beta:

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.owncloud.android.lib.resources.shares.ShareType.getValue()' on a null object reference
at com.owncloud.android.datamodel.FileDataStorageManager.prepareInsertShares(FileDataStorageManager.java:1529)
at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder(FileDataStorageManager.java:1490)
at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder(RefreshFolderOperation.java:495)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:216)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
at java.lang.Thread.run(Thread.java:818)

************ DEVICE INFORMATION ***********
Brand: motorola
Device: titan_umtsds
Model: Moto G 2014
Id: MMB29M
Product: cm_titan

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: af3c37bd08
```

**Comment by tobiasKaminsky** [comment]
@davivel ping

**Comment by jkutterer** [comment]
The issue seems to be related Issue #1333

**Comment by jkutterer** [comment]
Bug seems to be fix in Version 1.9.1.

**Comment by davivel** [comment]
@pecuna , could you confirm if it's fixed in 1.9.1 ? 

Thanks to @all.

**Comment by pecuna** [comment]
Yes! I didn't see this bug for some long time now. Thank you all for resolving the issue!

**Comment by davivel** [comment]
:tada:
