### ISSUE TITLE
Remove support to build with Maven

### ISSUE THREAD

**Issue by przybylski** [owncloud/android#1320]

**Comment by AndyScherzinger** [comment]
As far as I know, there is none and besides that the maven build doesn't even work anymore...

**Comment by przybylski** [comment]
ok, removing ;)

**Comment by AndyScherzinger** [comment]
Hope that is fine with you @davivel

**Comment by davivel** [comment]
Totally fine. Kill it.

**Comment by tobiasKaminsky** [comment]
I think there is currently no PR for this, so this issue should remain open?

**Comment by davivel** [comment]
Fine for me, closed it since it's a question, and was answered. But this other way works too.

**Comment by AndyScherzinger** [comment]
Removal done in PR #1592

**Comment by davivel** [comment]
Done. Thanks!
