### ISSUE TITLE
Support for Nexus Imprint

### ISSUE THREAD

**Issue by Querschlag** [owncloud/android#1323]
Google introduced a new fingerprint authentification service with the release of the Nexus 5X and 6P called Nexus Imprint. Github user @afollestad created a library that wraps around the Google Api and provides fingerprint unlock with a passphrase fallback.
Would it be possible to implement this as another method to unlock the app (instead of a PIN code)?

Library: https://github.com/afollestad/digitus

**Comment by davivel** [comment]
Thanks for the reference, @Querschlag , seems feasable.

Let's track it in #1462.
