### ISSUE TITLE
User manual updates did not get published

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/android#1326]
Hey all, re https://github.com/owncloud/android/pull/1254 -- the changes did not get published to https://doc.owncloud.org/android/. I took a look at the Jenkins config, and do not understand it. Please I need someone to fix this so that the manual gets published correctly.

**Comment by carlaschroder** [comment]
I don't see a Jenkins job for the Android user manual, or the iOS user manual.

**Comment by carlaschroder** [comment]
Hurrah, all fixedby @danimo!

**Comment by tobiasKaminsky** [comment]
When and how? :)
I was just about to see where the problem is.

**Comment by carlaschroder** [comment]
@tobiasKaminsky Just now :) Look on Rotor, in the Documentation section.

**Comment by danimo** [comment]
@tobiasKaminsky the docs are built on an internal machine inside a docker environment. Not much to see I'm afraid.
