### ISSUE TITLE
owncloud 1.9 does not install while beta is installed and vice versa

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1327]
I get repeatedly the error 505 while

**Comment by elpraga** [comment]
Installing the app from the store.

Anyine having similar issue?

**Comment by tobiasKaminsky** [comment]
What android version do you have exactly?
Is this an owncloud upgrade or a fresh install?
It seems as this is a problem with the android version...
https://android.stackexchange.com/questions/88214/how-do-i-deal-with-unknown-installation-error-code-505

**Comment by Mickael-Martin** [comment]
Same issue on cm12.1 (Android 5.1 based). Fresh install or upgrade. 
Can I log this ?

**Comment by elpraga** [comment]
In my case it was first reinstall, then I uninstalled the app and tried to install it again with the same error.

I emptied the cache of play store and tried again. But with the same result.

I am afraid to uninstall the beta, because I do use the app on daily bases and I cannot be without it..

**Comment by elpraga** [comment]
Please note, that there is no problem in installing nor upgrading other apps on my phone. The only one I have problems with is the OC legacy one.

**Comment by elpraga** [comment]
I can confirm the issue now. I did uninstall the beta on my tablet and I could install the version from Google Store without any problems, but no I cannot install Beta 20151202 on the tablet.

Does this help?

**Comment by Mickael-Martin** [comment]
Ok. Uninstall beta works for me too. Thanks

**Comment by elpraga** [comment]
Can we confirm that it is the case? I can confirm it on my two devices, but I cannot be sure if it is the case in all occasions.

 Can something e done about it?

**Comment by przybylski** [comment]
beta and regular release have the same package name so they can't be installed without conflicts on a device

**Comment by przybylski** [comment]
simple fix is to change beta package name

**Comment by elpraga** [comment]
Something must have changed since 1.8; I used to have 1.8 and beta installed together without any problems, and I upgraded the beta many times.

I am not sure what do You mean by changing the package name, but if You mean changing the filename of the beta, that does not work.

If You mean changing something inside the package, could this be fixed in the next beta? (I suppose it would be easier to do this rather than changing the 1.9 in the Play Store..)

**Comment by tobiasKaminsky** [comment]
@przybylski 
$aapt dump badging owncloud-beta-20151202.apk 
package: name='com.owncloud.android.beta' versionCode='20151202' versionName='20151202' platformBuildVersionName='6.0-2166767'
sdkVersion:'14'
targetSdkVersion:'23'

Where do you see the same package name? In fdroid?

**Comment by tobiasKaminsky** [comment]
1.9 version downloaded from fdroid:
$aapt dump badging com.owncloud.android_10900000.apk |head
package: name='com.owncloud.android' versionCode='10900000' versionName='1.9.0' platformBuildVersionName='5.1.1-1819727'
sdkVersion:'14'
targetSdkVersion:'22'

**Comment by przybylski** [comment]
@tobiasKaminsky I was looking directly on beta branch, https://github.com/owncloud/android/blob/beta/AndroidManifest.xml but obviously I might be wrong

**Comment by tobiasKaminsky** [comment]
@przybylski AndroidManifest and gradle.build are adjusted by my betaBuild script (which is not public, but it can/should be...)

**Comment by tobiasKaminsky** [comment]
I hopefully have solved the problem in the latest beta.
Please try it again.

**Comment by elpraga** [comment]
Fixed  in  20151220 , I am able to install both versions again.  Tank you for fixing this.  

And Mary Christmas!
