### ISSUE TITLE
Limit download notifications

### ISSUE THREAD

**Issue by xephon2** [owncloud/android#1332]
When downloading a whole directory, the download task is not handled as a single job. All files are notified separately and trigger a notification icon in the header bar on Android. Therefore one or two icons appear and hide again and again and you get no real notification about the remaining time of the whole download job, because the displayed time is only related to the currently downloaded file.

**Comment by abelgardep** [comment]
Notifications have changed for the 3.0 release. It does not tingle the way it did. Feel free to check it on the 3.0 beta and let us know 👍
