### ISSUE TITLE
Sorting by recently modified should mix files and folders

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1334]
Currently when sorting by recently modified first shows folders and then files. Rather we should mix them, whichever item was modified most recently. This is the same we do in the web interface.

Because right now the sorting is very strange for folders with a lot of items and folders – you need to scroll down a lot to get to the relevant items.

**Comment by tobiasKaminsky** [comment]
But this is the way other file browser do this, oder?
(I can only verify this for dolphin [KDE file browser])

**Comment by jancborchardt** [comment]
Desktop file managers might do that, but on mobile it’s impractical. :)

**Comment by tobiasKaminsky** [comment]
Ok.
Then we do it :+1:

**Comment by tobiasKaminsky** [comment]
Done in #1369

**Comment by davivel** [comment]
Since there is a PR for this, let me remove the 'Junior Job' label.

**Comment by abelgardep** [comment]
Done, will be included in 2.14
