### ISSUE TITLE
Chromecast support?

### ISSUE THREAD

**Issue by jas4711** [owncloud/android#1337]
When viewing images using the built-in photo viewer, would it be possible to have a chromecast cast-button?  I don't know if it is possible to support chromecast without non-free libraries though -- if it isn't, I wouldn't want this implemented.

**Comment by przybylski** [comment]
Chromecast has support in Google API Library and is fairly easy to implement.
Could you provide 1-2 scenarios how ownCloud app could benefit from it?

**Comment by jas4711** [comment]
Simple scenario: cast one image to chromecast device. After downloading and viewing an image locally, have the cast icon appear to allow me to cast the image to the TV.

Actual scenario (this happened yesterday where we eventually resolved to uploading the images to Google and using Google Photos): Open up a directory with several images, click on an cast icon to start casting, and by selecting images that image is casted to the TV, swiping right/left changes between image, clicking back goes back to the directory with files but does NOT stop display of the current image on the TV, and you can select a new image from the directory, and when you click on that, that image gets casted to the TV.

Thank you!

**Comment by jimgoofy** [comment]
Another great feature would be too stream a video file directly from the owncloud server to the chromecast and control the playback from the owncloud android client.

**Comment by tlongren** [comment]
@jimgoofy that's exactly my use-case, too. Like [this put.io client](https://github.com/DSteve595/Put.io) from @DSteve595. Here it is [on Play Store](https://play.google.com/store/apps/details?id=com.stevenschoen.putionew).

**Comment by DSteve595** [comment]
For some reason I just saw this. Adding Cast functionality is super easy with Cast SDK v3, but it needs to be tied to a developer account (preferably the same one that owns the app on Google Play Developer Console). I can take a crack at adding the functionality if a Cast developer account is made.

**Comment by davivel** [comment]
Hi, @DSteve595 . Feel free to go for it.

I guess that the bind to the developer console will be done through some kind of private key, right? Just be sure of **not** including yours in any commit (I'm guessing you have one for testing while develop). We'll take a look to the process of creating one and update the build process to include it in the end, while keeping it private.

**Comment by DSteve595** [comment]
Sounds good.

**Comment by thilo-dual** [comment]
any news on this topic? :)

**Comment by butonic** [comment]
My use case is showing a video or picture on the tv. I don't know if the file needs to be available on the mobile, or if we can directly stream from the server. It really sucks having to install vlc just to be able to stream the video.

It would be great if our built in mediaviewer would show the cast icon.

**Comment by hannesa2** [comment]
I tried to start with this https://github.com/owncloud/android/issues/3532 and created some per-required pull requests (some are open or closed unmerged 👎)
In https://github.com/owncloud/android/issues/3532 it's working principal, but I observed that most of my videos are not able to play with Exoplayer

So I end up with this https://github.com/owncloud/android/issues/3532#issuecomment-1032431811

**Comment by hannesa2** [comment]
I did some implementations, but I run into several unsupported video formats and the fastest workaround is to download file and share it with VLC 
https://github.com/owncloud/android/issues/3532#issuecomment-1032431811

I would close this issue
