### ISSUE TITLE
ownCloud 1.9.0 constantly syncing

### ISSUE THREAD

**Issue by johnassel** [owncloud/android#1338]
Since 1.9.0 the Android OC client is constantly syncing and keeping the device awake when the auto-sync option under "Accounts" is checked. I've got it installed on two 5.1.1 devices and this behaviour occurs on both. Once it has finished scanning the whole folder structure it starts again after 30-60 seconds, keeping the device awake (it never goes do deep-sleep), draining the battery and generating permanent traffic.
This didn't occur with 1.8.0. Because of that I had to disable auto sync. 
Does anyone have this problem as well?

**Comment by xdmx** [comment]
I have this exact issue. I charged my phone 12 hours ago and never used it since then. My battery is at 56% with owncloud responsible for 70% of the draining + various mb of data used

I've now disabled the auto sync as well

**Comment by ondratu** [comment]
Hi, i have the same problem. I send feedback from android that ownCloud killing my battery on my Samsung S5 Mini. Now i try to start syncing and as I see on server log, syncing is still repeating.

**Comment by smu** [comment]
Same here, on a Nexus 7 running Cyanogenmod 12.

**Comment by ccoenen** [comment]
I have this on a nexus 10 (stock android) and a Galaxy S4 (cyanogenmod). Going back to 1.8.0 is a workaround for now.

**Comment by ccoenen** [comment]
Oh and i only noticed because of a dead battery and a warning from my ISP that i'm using too much data on my sorry 500MB/month plan.

**Comment by hypnotoad** [comment]
Exactly the same problem here.

Battery empty, 500MB in 2 days, server has higher load than usual (approx 1 query per second for 3 days)

**Comment by smu** [comment]
The current version from fdroid suffers from the same bug.

**Comment by tobiasKaminsky** [comment]
@davivel Do you have an idea which change can have such an deep impact?

**Comment by davivel** [comment]
Probably induced some way with the synchronization of full folders.

The point I don't fully understand is that the auto-sync is repeated once and again. That needs to be due to some wrong interaction with the system.

Could you all tell us your Android version, please?

@rperezb , @MTRichards , @cmonteroluque , we need to review tis.

**Comment by MTRichards** [comment]
Please do dig into this, or put it top for next sprint... we can discuss.

**Comment by davivel** [comment]
OK

**Comment by schaal** [comment]
I have the same issue. I'm on stock android 5.1.1 on a Moto X Play.

**Comment by johnassel** [comment]
Android 5.1.1 and 6.0.1 on Cyanogenmod 12/13.

**Comment by davivel** [comment]
Thanks, seems there is no need to keep reporting Android versions. 

@przybylski came in with a really good catch. This should be fixed really soon.

**Comment by davivel** [comment]
The fix for this problem is already merged. Will be included in next version 1.9.1, that should be available in the beginning of 2016.
