### ISSUE TITLE
Beta install fails

### ISSUE THREAD

**Issue by helmo** [owncloud/android#1339]
Hi,

I just tried to install the 20151202 beta on a Nexus 5 Android 6.0.1 via f-droid. 
The phone was cleanly installed today.

It fails at the end of the installation process with the not so helpful message "Failed to install due to an unknown error"

Other apps installed just fine via F-droid.
Please let me know if there's a way to get a more helpful message from this.

**Comment by helmo** [comment]
While officially not compatible(according to f-droid) the app did install just fine on an old android 4.1

**Comment by tobiasKaminsky** [comment]
For me it is working on a nexus 4 on android 6.
But I have no idea how to find the reason...

btw: why is it not compatible according to f-droid?

**Comment by helmo** [comment]
Strange ... I didn't find it before I check the "Incompatible versions" checkbox. But now I can still find it after the checkbox is unchecked. ... So sorry, must have been a typo or me not looking good enough.

**Comment by enoch85** [comment]
@helmo I just installed the latest beta today and faced the same issue. What I did whas to uninstall it, and then made a clean install again. 

Off topic: @tobiasKaminsky The latest beta is working very well! I love the fact that the files aren't duplicated. Great work!

**Comment by przybylski** [comment]
When I was working with beta branch today I notice that I got INSTALL_FAILED_CONFLICTING_PROVIDER error while running beta. I had to uninstall stable ownCloud to make it work. Perhaps some content provider is using incorrect authority?

**Comment by AndyScherzinger** [comment]
I get the same error as descibed by @przybylski that's why I basically only run the beta on my phone since then... :smile:

**Comment by tobiasKaminsky** [comment]
I will have a look on this weekend or maybe even at monday...

**Comment by tobiasKaminsky** [comment]
I have solved it hopefully, please test it.

**Comment by helmo** [comment]
![screenshot_20151221-103302](https://cloud.githubusercontent.com/assets/104120/11927652/5e54b968-a7ce-11e5-813d-abb92ee3a98a.png)

Sorry, still fails to install in parallel with the normal version via f-droid.

After uninstalling the 1.9 version I got one step further.

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.owncloud.android.files.services.FileUploaderUPLOAD_FINISH flg=0x10 (has extras) } in com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver@af18b01
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
at com.owncloud.android.ui.activity.FileDisplayActivity$UploadFinishReceiver.onReceive(FileDisplayActivity.java:1152)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
... 7 more

************ DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MMB29K
Product: hammerhead

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 2419427
```

After the app closed I opened it again and I could enter my login.... YAY it works.

**Comment by tobiasKaminsky** [comment]
I have installed fdroid on a fresh android 6 (nexus 4) and first installed the official owncloud and after that the beta 20151220 and had no problems...

**Comment by tobiasKaminsky** [comment]
@helmo please check again

**Comment by helmo** [comment]
I updated again today.
Also re-installed the play-store version and then the beta ... worked fine.
