### ISSUE TITLE
[BUG 1176][Beta 20151213] When deleting from server the app freezes

### ISSUE THREAD

**Issue by enoch85** [owncloud/android#1347]
When selecting several files for deletion in server side, the app freezes in the same mode. 

It says "successful deletion" and then the icon is just spinning and nothing happens. To fix it you have to kill the app.

**Phone**
OnePlus 2
Android 5.1.1

![screenshot_2015-12-13-17-17-49](https://cloud.githubusercontent.com/assets/4511254/11768052/6a0529d6-a1c1-11e5-86cd-3a06d7a2bb1b.png)

**Comment by tobiasKaminsky** [comment]
Please try it again

**Comment by rperezb** [comment]
@enoch85 is this bug still a bug?

**Comment by enoch85** [comment]
Sorry, I don't had the time to test yet. Much is happening around me right now. I will test when I have some time. Others could also test if this is still an issue ofc. :)

**Comment by rperezb** [comment]
@enoch85 no problem
certainly, yes, other could also test, indeed we have started workign actively in the multiple selection, the goal is to include it within 2.0.2 version

**Comment by jabarros** [comment]
I have checked in master branch and it is not happening

**Comment by jesmrec** [comment]
Fixed

**Comment by enoch85** [comment]
I guess this could be closed then. Haven't tried it myself though.
