### ISSUE TITLE
Implement a Document Provider

### ISSUE THREAD

**Issue by TJWeiten** [owncloud/android#1352]
One sorely lacking feature (unless it's already implemented in which case this is a bug report) is the lack of ownCloud's app acting as a document provider. A document provider essentially tells the Android operating system that it is an application that manages files. Google Drive is a document provider, and therefore whenever the OS-level file picker comes up (for example, when selecting a new image as a wallpaper), Google Drive is offered as one such service you can use to browse files.

Implementing this feature shouldn't be too terrible hard, all the documentation on it is provided here: http://developer.android.com/guide/topics/providers/document-provider.html

**Comment by przybylski** [comment]
Possible duplicate: https://github.com/owncloud/android/issues/296

**Comment by TJWeiten** [comment]
Definite duplicate. Closing the issue.
