### ISSUE TITLE
View Photos Temporarily without Downloading them to System

### ISSUE THREAD

**Issue by TJWeiten** [owncloud/android#1353]
One personal annoyance is that the ownCloud app downloads every image that I open on my devices to the internal storage. Sometimes, I want to view an image just temporarily and NOT have it automatically downloaded and stored to /sdcard/owncloud/.../.

Perhaps downloading them into a cache would be more proper, then if the user clicks the menu button, offer to let them download the image and then it would be appropriate to save it to /sdcard/owncloud/.../.

Otherwise every image I view from a different folder (and I have many, many folders) from the ownCloud app triggers Google Play Services to shoot me a notification asking if I want to backup that folder to Google Photos.

**Comment by AndyScherzinger** [comment]
please see  #1044 and close this issue in case the references PR is fulfilling this issue in your opinion. 
It does in mine :)

**Comment by TJWeiten** [comment]
Alright, that does look like it's mostly fulfilling what I'm looking for. Hopefully it gets merged soon.
