### ISSUE TITLE
Instant upload with 3rd Party  Camera App

### ISSUE THREAD

**Issue by rijudewan** [owncloud/android#1354]
Instant upload  with 3rd Party  Camera App does not work. Is there any way that i can use instant upload with 3rd party camera app .

**Comment by przybylski** [comment]
What sort of app you are talking about?
As long as that app sends `android.hardware.action.NEW_PICTURE` or `com.android.camera.NEW_PICTURE` intent after taking picture then we are uploading it.

**Comment by AndyScherzinger** [comment]
as mentioned, camera app would need to support the mentioned intends, seen also here #1217

**Comment by tobiasKaminsky** [comment]
Yeah, there is nothing we can do here (except developing and implementing #744)

**Comment by rijudewan** [comment]
i have created a sales and merchandiser app for Microsoft Dynamic AX 2012 it has a option to take photo of the product  after image is captured  i convert it to bitmap and paint  Date&Time ,GPS coordinate and customer ID and Name and save it back to Gallery.

sample code  look like this ..
private void captureImage() {
        Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        fileUri = getOutputMediaFileUri(MEDIA_TYPE_IMAGE);
        intent.putExtra(MediaStore.EXTRA_OUTPUT, fileUri);
        // start the image capture Intent
        startActivityForResult(intent, CAMERA_CAPTURE_IMAGE_REQUEST_CODE);
    }

@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        // if the result is capturing Image
        if (requestCode == CAMERA_CAPTURE_IMAGE_REQUEST_CODE) {
            if (resultCode == RESULT_OK) {
                // successfully captured the image               
                scanMedia(fileUri.getPath());
                String imageID=fileUri.getPath();
                sendBroadcast(new Intent(Camera.ACTION_NEW_PICTURE, Uri.parse(imageID)));
                //openInGallery(imageID);
                previewCapturedImage();

            } else if (resultCode == RESULT_CANCELED) {
                // user cancelled Image capture
                Toast.makeText(getApplicationContext(),
                        "User cancelled image capture", Toast.LENGTH_SHORT)
                        .show();
            } else {
                // failed to capture image
                Toast.makeText(getApplicationContext(),
                        "Sorry! Failed to capture image", Toast.LENGTH_SHORT)
                        .show();
            }
} 

how should i use 
android.hardware.action.NEW_PICTURE or com.android.camera.NEW_PICTURE
i  cant find any documentation on it ...

any one can give me sample code  on how to implement it ...

**Comment by tobiasKaminsky** [comment]
sendBroadcast(new Intent(Camera.ACTION_NEW_PICTURE, Uri.parse(imageID)));
you already have included it.
https://developer.android.com/reference/android/hardware/Camera.html#ACTION_NEW_PICTURE

**Comment by rijudewan** [comment]
hi  tobiasKaminsky,
sendBroadcast(new Intent(Camera.ACTION_NEW_PICTURE, Uri.parse(imageID)));
This code is not working  for me ....  any thing wrong my my code

**Comment by przybylski** [comment]
assuming fileUri is a correct Uri
```java
Intent intent = new Intent(Camera.ACTION_NEW_PICTURE);
intent.setData(fileUri);
sendBroadcast(intent);
```

**Comment by rijudewan** [comment]
hi przybylski ,
 thanks for your answer . I tried your code but its same.. it does not do any thing then code is actually triggered but nothing happens

**Comment by przybylski** [comment]
Make sure that your Uri is correct one and you have enabled instant upload in ownCloud app. The correct uri should be something like:
`content://media/external/images/media/<ID>`

**Comment by rijudewan** [comment]
thank you ... i need to look on it cause  now my file url is  .....
file:///storage/emulated/0/DCIM/Camera/%20_1220_1907.jpg

**Comment by przybylski** [comment]
Closing
