### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by rijudewan** [owncloud/android#1355]
Error:(57, 12) Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]
    public FileFragment(OCFile file) {
           ~~~~~~~~~~~~~~~~~~~~~~~~~
D:\AndroidProject\ownCloud-9.0\src\com\owncloud\android\ui\dialog\LoadingDialog.java:49: Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]
    public LoadingDialog(String message) {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\AndroidProject\ownCloud-9.0\src\com\owncloud\android\ui\preview\PreviewMediaFragment.java:107: Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]

**Comment by AndyScherzinger** [comment]
@rijudewan can you provide some more details on how you provoked this build error? Like are you using ant or gradle? Did you get this error in Android Studio and if so did you execute the setup command for gradle befor doing so? see https://github.com/owncloud/android/blob/master/SETUP.md

**Comment by rijudewan** [comment]
yes i followed the instruction .... when i build in debug  mode it does not give me error  but when i build in release mode  then there is error ....
Error:(58, 12) Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]
    public FileFragment(OCFile file) {
           ~~~~~~~~~~~~~~~~~~~~~~~~~
D:\AndroidProject\ownCloud-9.0\src\com\owncloud\android\ui\dialog\LoadingDialog.java:49: Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]
    public LoadingDialog(String message) {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\AndroidProject\ownCloud-9.0\src\com\owncloud\android\ui\preview\PreviewMediaFragment.java:107: Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]
![build error](https://cloud.githubusercontent.com/assets/13164167/11916132/71ea8d38-a704-11e5-82c4-aa9671d4ec47.jpg)

**Comment by przybylski** [comment]
There are 2 sides on those issues, first, ownCloud project was incorrectly setup.
Second, you had global variable (probably in your home dir) which was aborting of failure.
My commit will fix this

**Comment by davivel** [comment]
@rijudewan , could you check if its fixed now for you? Solution by @przybylski was just merged in master branch.

Thanks in advance.

**Comment by rijudewan** [comment]
android {
        lintOptions {
            abortOnError false
        }
    }

this did a trick for me  on Android Studio ....

**Comment by davivel** [comment]
OK, then this is done.

Thanks!
