### ISSUE TITLE
[Share with users, groups] Should not be accent sensitive

### ISSUE THREAD

**Issue by etiess** [owncloud/android#1356]
### Expected behaviour

As mentionned for the client (owncloud/client#4286) and for the server (https://github.com/owncloud/core/issues/21212), sharing a file/folder with users/groups is accent sensitive, while I think it should not.

In fact, you have to enter the name with the accent, in order it is proposed in the users list. Investigating a bit further, I noticed that "í" is considered as a normal "i", while "é" is not considered as an "e".

If it can help, Android issue with alphabetical sorting of accentuated letters was solved here: owncloud/android#1110
### Steps to reproduce

Share a file with a user called "frédéric" :
1. Long press on a file, chose Share
2. Share with a user or a group
3. In the box, start entering the name of this user: "fred..."
4. The name frédéric should be proposed, but it's not.
### Environment data

Android version: 5.1
Device model: LG G4
Stock or customized system: LG customized
ownCloud app version: 1.9.0
ownCloud server version: 8.1.2 on Ubuntu 15.04 (MySQL)

**Comment by jesmrec** [comment]
`frédéric` is not a valid username anymore. In any case this would not be an issue from Android, because all results are being retrieved via API. Android client shows what server sends in the response. Checked with iOS client, same behaviour.

Thanks for reporting, but this is a server improvement.
