### ISSUE TITLE
Result of 'String.replace()' is ignored

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1362]
In https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/activity/FileDisplayActivity.java#L739

androidStudio says: Result of 'String.replace()' is ignored

**Comment by przybylski** [comment]
and it's right. If it is suppose to update displayed name then result should be assigned to displayName.
Beside those two calls are doing the same thing

**Comment by tobiasKaminsky** [comment]
But now both calls are useless. 
So they can either be removed or should be assigned back to displayName...?

**Comment by przybylski** [comment]
author of those lines should say why he did it like this

**Comment by przybylski** [comment]
@davivel ??

**Comment by tobiasKaminsky** [comment]
https://github.com/owncloud/android/blob/382191d1f94c02475bdd607852e552b5621a7d9c/src/com/owncloud/android/ui/activity/FileDisplayActivity.java#L730
By https://github.com/Pro9

**Comment by tobiasKaminsky** [comment]
cc: @Pro9

**Comment by przybylski** [comment]
Blame is showing me this commit: https://github.com/owncloud/android/commit/703366c45970d051609fe5758948a5103f6e931c but maybe this was just merged by @davivel

**Comment by tobiasKaminsky** [comment]
Uh? How did you get this commit?
Android studio is showing me another commit as the "cause"?
https://github.com/owncloud/android/commit/382191d1f94c02475bdd607852e552b5621a7d9c#diff-845104e37d2ed427df8ae96910082d31R730

**Comment by przybylski** [comment]
on github, there is a blame button at the top of the file

**Comment by jesmrec** [comment]
Class was tranlated to kotlin.
