### ISSUE TITLE
Automatically create new issue on Github or send crash report via email

### ISSUE THREAD

**Issue by enoch85** [owncloud/android#1371]
Instead of that the user has to copy the crash report / Log, it would be nice it could be done automatically. Maybe by creating a new issue on GitHub with the label "crash report" and some other useful info, or by sending it by email.

**Comment by przybylski** [comment]
At some point we might be overflown with repeating crash issues.
In regular build crashes are visible in developer console.
There exists solution which can be built in into app but I am not sure how they would fit just into beta.
Also I hope that people who are using beta are clever enough to get log and provide it to us.

**Comment by enoch85** [comment]
Would this be feasible in the stable builds?

**Comment by davivel** [comment]
> At some point we might be overflown with repeating crash issues.

This problem would be still present in stable builds.

We would like to reactivate the usage of beta, improving it's integration with the app life cycle and the way to gather information from beta users. Stay tuned, I will update issues labelled with 'beta' in a while.

**Comment by davivel** [comment]
I would not consider Github issues, but send via e-mail... We can give it a thought.

**Comment by davivel** [comment]
By the way, new beta version of the app is available now in F-Droid: https://f-droid.org/packages/com.owncloud.android.beta/
