### ISSUE TITLE
Enhancement to disable sharing with user or groups using settings.xml

### ISSUE THREAD

**Issue by supportreq** [owncloud/android#1374]
Hey, the new sharing with user & group feature is really cool, but is it possible to somehow disable the same using a setting? Currently disabling sharing even disables public shares.. please advice..

**Comment by masensio** [comment]
Hi @supportreq,

at the moment we only have the option share_feature to enable/disable Share Feature on the app. This option enable/disable the share by link and share with users at the same time. 
We will have your suggestion into account for future improvements.

You can disable the share with user/group in the setup server admin panel.
