### ISSUE TITLE
Federated sharing support in mobile devices

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1376]
Sharing in mobile devices does not support federated sharing with other servers' users.

**Comment by cmonteroluque** [comment]
@MTRichards

**Comment by MTRichards** [comment]
Likely a server side issue, captured here:
https://github.com/owncloud/core/issues/21328

@rperezb will likely require some mobile work to understand an update to the sharing API.

**Comment by MTRichards** [comment]
I stand corrected, looks like we need to handle this entirely on mobile. Closed the server side issue.

**Comment by davivel** [comment]
Supported now thanks to #1492. Will be released in 1.9.2.
