### ISSUE TITLE
Incomplete size in list and details view (PR 1209)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1381]
PR: https://github.com/owncloud/android/pull/1209

In list view, uploads view and details view, the size of the file is shown without decimals. In server side is shown with at least one decimal when the size is greater than 1MB. For example, these two files:

Server:
343 KB (any decimal)
1,4 MB (one decimal when size > 1MB)

Mobile device:
343 KB (any decimal, right)
1 MB (any decimal, should be shown the first one, as in server side)

**Comment by davivel** [comment]
@AndyScherzinger , that's a gift for you ;)

**Comment by AndyScherzinger** [comment]
Thanks :)  Looping in @jancborchardt since this is contrary to what has been specified for mobile!

**Comment by AndyScherzinger** [comment]
I can fix or let's say change this but I would like to have Jan's Feedback first :)

**Comment by jancborchardt** [comment]
Sorry for any confusion! :) Should be like on the server.

**Comment by AndyScherzinger** [comment]
Do we have a specification for that or the server side code snippet to port, just to make sure that it will behave the exact same way.

**Comment by AndyScherzinger** [comment]
Code reference for the change that has been made which caused this: https://github.com/owncloud/android/commit/607fb6f5879245e2dd670e82be97e269a7d14a0b#diff-36e882c1d5231f769f0209395ecf63c4R58
the two lines basically. So the question is does it stand correct to have two decimals for peta byte and up? If so I can simply change the MB value in the digits array to 1 instead of zero and we are all set :)

Would that be fine with you @davivel and @jancborchardt ?

**Comment by AndyScherzinger** [comment]
The fix has been pushed to the ```material_buttons```branch :+1:

**Comment by jancborchardt** [comment]
@PVince81 do we have any spec here, or where is the relevant code of the server?

**Comment by jesmrec** [comment]
Fixed!

**Comment by AndyScherzinger** [comment]
@jesmrec yes - for mega byte. To make sure it is behaving the same way for peta bytes and up we need further info from @PVince81 and @jancborchardt - In case we needs to check it for peta bytes and up :grin:

**Comment by AndyScherzinger** [comment]
All changes up to know have been merged to master and thus I label the issue for release 1.9.1 :)
