### ISSUE TITLE
Quick Account-Switching in navigation drawer

### ISSUE THREAD

**Issue by stonerl** [owncloud/android#1383]
Currently when one has  multiple accounts in the app the only way to switch between these accounts is to open the settings and select the appropriate account.

Would it be possible to have a quicker way? e.g. from the sidebar?

**Comment by tobiasKaminsky** [comment]
Yes, this is something that was discussed at #757 if I remember correctly.
But we should keep this issue open and change the topic to a more detailed one.
I will dig into my old code to see what I already have done and will create a PR soon for it.
After that it will be first in beta and after a while in the official version.

**Comment by tobiasKaminsky** [comment]
> create a PR soon for it

:laughing: 
But now...#1537

**Comment by AndyScherzinger** [comment]
current implementation is done in PR #1559

**Comment by davivel** [comment]
Merged, will be released in version 2.2.0
