### ISSUE TITLE
Only leave application with open navigation drawer

### ISSUE THREAD

**Issue by stonerl** [owncloud/android#1384]
Maybe this is something I got used to by other apps and I really don't know whether this is an Android-UI-Guidline or not. Currently the ownCloud-Client closes when the back button is pressed in the root folder view. Other apps, e.g. the ownCloud Newsreader, first open the navigation drawer and when pressing back a second time with the open drawer it leaves the app.

**Comment by AndyScherzinger** [comment]
The UI pattern is actually the way this app is implementing it, meaning back closes the open drawer but a closed drawer doesn't get opened by the back button. Other app with this behavior for example are the Google Play store or  the Gmail app.

**Comment by stonerl** [comment]
You're right. I'm closing this issue, thank you for your feedback.

**Comment by AndyScherzinger** [comment]
You are welcome! Glad I could clarify on this matter :)
