### ISSUE TITLE
Owncloud client warns with valid letsencrypt HTTPS certificate

### ISSUE THREAD

**Issue by floe** [owncloud/android#1385]
I've just deployed a letsencrypt HTTPS certificate on my owncloud server. Firefox and Chrome are fine with the cert and can successfully validate it, however, the Owncloud Android app still issues a warning that the cert is signed by an unknown authority. A quick Google search tells me that this may be related to which Android URL API is in use, however, I can't give more details ATM. Issue occurs on Owncloud app 1.9.0.

**Comment by floe** [comment]
Apologies for the noise, it seems that I had setup lighttpd incorrectly. Closing.

**Comment by BlaShadow** [comment]
How did you solve this? I getting this issue.

**Comment by floe** [comment]
I've solved this according to https://github.com/letsencrypt/letsencrypt/issues/1201#issuecomment-153671647 and https://nwgat.ninja/setting-up-letsencrypt-with-lighttpd/ .
