### ISSUE TITLE
Instant photo upload: Cannot modify header information ... Sapi.php#58

### ISSUE THREAD

**Issue by localguru** [owncloud/android#1388]
Hi,

instant photo uploading with android client 1.9.0 produces this error:

Error   PHP     Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58

Photos were uploads successfully.

sudo -u www-data php ./occ app:list

Enabled:
    activity: 2.1.3
    calendar: 0.8.1
    contacts: 0.5.0.0
    direct_menu: 0.5
    files: 1.2.0
    files_external: 0.3.0
    files_pdfviewer: 0.7
    files_sharing: 0.7.0
    files_texteditor: 2.0
    files_trashbin: 0.7.0
    files_versions: 1.1.0
    files_videoviewer: 0.1.3
    firstrunwizard: 1.1
    gallery: 14.2.0
    provisioning_api: 0.3.0
    templateeditor: 0.1
    user_otp: 2.5

Disabled:
    documents
    encryption
    external
    notifications
    ownbackup
    storagecharts2
    user_external
    user_ldap

System:
Owncloud: 8.2.2 [ http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/ ]
System: Ubuntu 14.04 LTS
Webserver: apache2 2.4.7-1ubuntu4.8
PHP: php5 5.5.9+dfsg-1ubuntu4.14
Database: mysql 5.5.46-0ubuntu0.14.04.2

Ciao
Marcus

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by enoch85** [comment]
Duplicate: https://github.com/owncloud/android/issues/1074 @davivel please close.

**Comment by davivel** [comment]
As @enoch85 said, this is a duplicated issue. Please, see #1074 for updated state.

Hint: this could be fixed (for the client side) from ownCloud Android app 2.3.0
