### ISSUE TITLE
House keeping: add correct checkboxes after merges

### ISSUE THREAD

**Issue by AndyScherzinger** [owncloud/android#1389]
Reminder issue to commit and merge the following change https://github.com/owncloud/android/commit/2641996d3efe4517f83bc206e00c811e71f5ac3e (right now only on beta)

This can only be done after the material_buttons PR and the multi-select PR have been merged or to the respective PR the will be merged seconds. Thus looping in @tobiasKaminsky 

- [x]  #1209 
- [x]  #1176

**Comment by masensio** [comment]
#1209  is merged on master :)

**Comment by davivel** [comment]
@AndyScherzinger , at this point, could you ```git cherry-pick``` the commit into branch ```multiselect```?

**Comment by AndyScherzinger** [comment]
Hi @davivel sure thing, but it is (lucky me) not a pick, but some implementation that needs to be done, referencing the new, shipped icon work which wasn't possible before :)

**Comment by AndyScherzinger** [comment]
DONE, see https://github.com/owncloud/android/commit/b59d05bb49b218f3777cc136f192cbdb3fb19d00

**Comment by davivel** [comment]
:+1: :-)
