### ISSUE TITLE
Beta 20151226 - Some previews appear with white space added to photos

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1391]
Some previews appear with the original photo in the top left corner and the rest of the space filled by white. I checked the original preview on the server and it appears OK.

Maybe some glitch in the way the previews are displayed? 

Let me know if I should provide more info.

**Comment by tobiasKaminsky** [comment]
I think following infos are needed:
- screenshot
- original resolution of the photo
- display resolution
- does it happen on "official" version?

**Comment by elpraga** [comment]
Ok, 
here is the info requested:
screenshots:
![405-720-max](https://cloud.githubusercontent.com/assets/13814570/12038967/c608c088-ae5c-11e5-9cbb-96c6b440296a.png)
![screenshot_phone_preview](https://cloud.githubusercontent.com/assets/13814570/12038968/c60beb32-ae5c-11e5-9e16-2e7f21775e72.png)
![screenshot_tablet_original_image](https://cloud.githubusercontent.com/assets/13814570/12038969/c60c60bc-ae5c-11e5-85d9-8ab71dfed886.png)
![screenshot_tablet_preview](https://cloud.githubusercontent.com/assets/13814570/12038970/c6136fec-ae5c-11e5-931b-9cd5606cad93.png)

original resolution photo:
1080x1920

display resolution:
1080x1920 phone
1024x720 tablet

960-720-max.png - normal preview_max on my server I did not see issue with those
405-720-max.png - preview_max on the efected previews

does it happen on "official" version?
"official" version as at current 1.9 has no previews, so cannot be compared. This issue does not appear with the thumbs on either one.

Is that all You need?

**Comment by elpraga** [comment]
Could You reproduce this issue?

**Comment by tobiasKaminsky** [comment]
Can you give me a link to the mentioned images? 
Then I can test in my owncloud?

**Comment by elpraga** [comment]
https://tomaskaluza.ocloud.de/index.php/s/tQExdDYcjwLPfaj
https://tomaskaluza.ocloud.de/index.php/s/47C4KTQpcrAE8IA
https://tomaskaluza.ocloud.de/index.php/s/i0Mgpf8Iy2GSVBj

Here there are, I saw this issue only with screenshots of the phone and the tablet. You might try to upload a screenshot of your phone and see if You get the same results.

**Comment by elpraga** [comment]
@tobiasKaminsky were You able to reproduce this issue?

**Comment by tobiasKaminsky** [comment]
Yes, but only with your images.
Can you test plain jpg files?
I suspect that the png is causing the problems...?

**Comment by elpraga** [comment]
I am without a computer at the moment, so I try to convert the exact same pngs to jpegs and I will try again.

Yes, I only noticed this issue with .pngs

Did You try to take a screenshot on Your phone and upload it? Does Your screenshot on the phone saves as .png as well?

**Comment by tobiasKaminsky** [comment]
@elpraga sorry for coming back so late.
Does this problem still occur?

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)
