### ISSUE TITLE
[Share options] I want to decide whether share with users is shown or not

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1397]
AC:
- Include 2 independent branded options
 + Show share with users: yes/no
 + Show share with link: yes or not 

NOTE:
- this will imply to modify the current one https://github.com/owncloud/android/blob/master/res/values/setup.xml#L27

Related to: https://github.com/owncloud/client/issues/4325

**Comment by elpraga** [comment]
Should not this be decided globally in the settings?
I recall there is an option "Users are allowed to share with others" in the web interface.

**Comment by rperezb** [comment]
global setting -> not really in client basis, for instance, if you are using the web interface, you may decide individually the privileges to be used each time you share any data
The option that you are pointing out is global, in the sense of server basis, as an admin you may limit the sharing properties for every user on that server
![screen shot 2015-12-09 at 11 23 52](https://cloud.githubusercontent.com/assets/1846927/12232965/628de50e-b863-11e5-9367-998afa497291.png)

**Comment by davivel** [comment]
Sorry, but this needs to be moved to next release.

**Comment by rperezb** [comment]
Fixed via https://github.com/owncloud/android/pull/1631
