### ISSUE TITLE
Resized images/Thumbnails: load them while wlan on sync

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1398]
Thumbnails are loaded while entering a directory.
Resized images are loaded while browsing them.

As I use 200mb cache it would be great that "all" thumbnails and "all" resized images are loaded when on wlan so that I do not have to download them while I am without wlan.

So, how can we do this?
- have an entry in settings: what if all images are bigger than the cache? Then it is useless to download newer ones as older are immediately kicked out of the cache.
- have an entry per folder which recursively downloads them? Maybe same problem as above
- automatically do this? How and what to do if the cache is to small?

@jancborchardt @AndyScherzinger @davivel

**Comment by jancborchardt** [comment]
I’d say yes, we should do this, and automatically. Recently changed files are given priority, so if the cache is too small you still have the most likely relevant items.

**Comment by tobiasKaminsky** [comment]
The cache itself is deleting the least recently used entries, so I guess this can work.
But we will need to know which are the recently changed files.

And it still can happen that a directory which important images needs to be downloaded over and over again...
So the best would be that it is somehow synced with the cache...?
