### ISSUE TITLE
Resume broken up/download

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1400]
It would be nice if the app can resume broken uploads and downloads.
With this the app would not start over and over again if uploading a big video file via a buggy wlan.

**Comment by przybylski** [comment]
Resuming uploading would need to be supported on server side as well.
I don't know if webdav is able to support such thing.

**Comment by tobiasKaminsky** [comment]
I think that the desktop client can do this?
Do you know if this is true and if they use webdav?

**Comment by przybylski** [comment]
I don't know, but if they do and it is possible then it would be super valuable to investigate

**Comment by przybylski** [comment]
OK, it is possible using http options in webdav. Also client is using webdav.

**Comment by jesmrec** [comment]
To do as part of TUS and Range Request implementation
