### ISSUE TITLE
Thumbnail size is wrong in full screen

### ISSUE THREAD

**Issue by RoxasShadow** [owncloud/android#1403]
Considering the beta app, currently we create thumbnails that look great for both the list and the grid, but when we tap and open an image, what we see is the same thumbnail that is shown inside the grid.

I think the best way to handle this situation is to show a thumbnail that looks like the original one but it's smaller (we could compress PNGs to JPGs and resize them to the screen size, so that the image size is kept low and in the same time we can't really feel a compression+size).

The original image will be downloaded when requested explicitly.

P.S. I also think that showing a compress image (in terms of format and quality only) inside the web client would be great as well.
For example I keep a huge amount of images in my owncloud, and would be great surfing on them without have to wait even more than 10s to have some of them loaded. – **EDIT:** it actually works in this way :)

Another option would be loading images progressively.

**Comment by tobiasKaminsky** [comment]
Normally the app should load a resized version of the image and store it in the local cache.
Which owncloud version do you run?

**Comment by RoxasShadow** [comment]
@tobiasKaminsky v8.2.

[Original](https://cloud.githubusercontent.com/assets/805144/12150222/d827b9f2-b4a8-11e5-9f5a-ac84030bb714.jpg)
[Grid/Fullscreen](https://cloud.githubusercontent.com/assets/805144/12150223/d86e3a76-b4a8-11e5-98eb-88248c71b57f.jpg)

**Comment by tobiasKaminsky** [comment]
Can you give me a logcat of the app when trying to access a fullscreen image?
An useful app is catlog.

**Comment by RoxasShadow** [comment]
I used ADB since my phone is not rooted.

>D/PreviewImageActivity(13932): onCreate(Bundle) starting
W/ActionBarDrawerToggle(13932): DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
D/PreviewImageActivity(13932): onStart() starting
D/PreviewImageActivity(13932): onResume() starting
I/Choreographer(13932): Skipped 33 frames!  The application may be doing too much work on its main thread.
D/SimpleFactoryManager(13932): getClientFor(OwnCloudAccount ... : 
D/OwnCloudClient #64(13932): Creating OwnCloudClient
V/SimpleFactoryManager(13932):     new client {RoxasShadow@$MYOWNCLOUD, 225691586}
D/Thumbnail(13932): FileName: zz2ImC.png Download URI: https://$MYOWNCLOUD/index.php/apps/gallery/api/preview/42317/720/1184
D/OwnCloudClient #64(13932): REQUEST GET /index.php/apps/gallery/api/preview/42317/720/1184
D/AdvancedSslSocketFactory(13932): Creating SSL Socket with remote $MYOWNCLOUD:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@253c274c
D/AdvancedSslSocketFactory(13932):  ... with connection timeout 60000 and socket timeout 60000
I/ServerNameIndicator(13932): SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
I/ServerNameIndicator(13932): SNI done, hostname: $MYOWNCLOUD
D/FileActivity(13932): Operations service connected
D/PreviewImageActivity(13932): Simulating reselection of current page after connection of download binder
D/PreviewImageActivity(13932): Upload service connected
I/LaunchCheckinHandler(  869): Displayed com.owncloud.android.beta/com.owncloud.android.ui.preview.PreviewImageActivity,wp,ca,778
I/ActivityManager(  869): Displayed com.owncloud.android.beta/com.owncloud.android.ui.preview.PreviewImageActivity: +778ms
V/FileDisplayActivity(13932): onSaveInstanceState() start
D/FileDisplayActivity(13932): onSaveInstanceState(Bundle) starting
D/ExtendedListFragment(13932): onSaveInstanceState()
V/FileDisplayActivity(13932): onSaveInstanceState() end
V/FileDisplayActivity(13932): onStop() start
D/FileDisplayActivity(13932): onStop() ending
V/FileDisplayActivity(13932): onStop() end
D/OwnCloudClient #64(13932): Location to redirect: https://$MYOWNCLOUD/index.php/apps/files/
D/PhoneApp( 1754): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 3619): updateTelephonySignalStrength[1]: phoneId=1 is not DDS( DDS_phoneId=0 ) ( SubscriptionManager.getPhoneId returned 0=0x00000000 )
D/PhoneApp( 1754): getPhone phoneId:1
I/SBar.MotoNetworkCtrlr( 3619): updateDataNetType[1]: phoneId1 is not DDS( =phoneId0 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 0=0x00000000 )
D/skia    (13932): --- SkImageDecoder::Factory returned null
D/SimpleFactoryManager(13932): getClientFor(OwnCloudAccount ... : 
D/OwnCloudClient #65(13932): Creating OwnCloudClient
V/SimpleFactoryManager(13932):     new client {RoxasShadow@$MYOWNCLOUD, 409219147}
D/Thumbnail(13932): FileName: HalFTb.png Download URI: https://$MYOWNCLOUD/index.php/apps/gallery/api/preview/42444/720/1184
D/OwnCloudClient #65(13932): REQUEST GET /index.php/apps/gallery/api/preview/42444/720/1184
D/PhoneApp( 1754): getPhone phoneId:1
D/PhoneApp( 1754): getPhone phoneId:1
I/SBar.MotoNetworkCtrlr( 3619): updateTelephonySignalStrength[1]: phoneId=1 is not DDS( DDS_phoneId=0 ) ( SubscriptionManager.getPhoneId returned 0=0x00000000 )
D/PhoneApp( 1754): getPhone phoneId:1
I/SBar.MotoNetworkCtrlr( 3619): updateDataNetType[1]: phoneId1 is not DDS( =phoneId0 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 0=0x00000000 )
D/PhoneApp( 1754): getPhone phoneId:1
D/com.facebook.a.a( 1617): Got unexpected exception: java.io.WriteAbortedException: Read an exception; java.io.NotSerializableException: org.json.JSONObject
D/OwnCloudClient #65(13932): Location to redirect: https://$MYOWNCLOUD/index.php/apps/files/
D/skia    (13932): --- SkImageDecoder::Factory returned null
D/SimpleFactoryManager(13932): getClientFor(OwnCloudAccount ... : 
D/OwnCloudClient #66(13932): Creating OwnCloudClient
V/SimpleFactoryManager(13932):     new client {RoxasShadow@$MYOWNCLOUD, 241277480}
D/Thumbnail(13932): FileName: 5SxqKy7.jpg Download URI: https://$MYOWNCLOUD/index.php/apps/gallery/api/preview/42318/720/1184
D/OwnCloudClient #66(13932): REQUEST GET /index.php/apps/gallery/api/preview/42318/720/1184
I/SBar.MotoNetworkCtrlr( 3619): onReceive: WifiManager.RSSI_CHANGED_ACTION Received
I/SBar.MotoNetworkCtrlr( 3619): updateWifiState: RSSI_CHANGED_ACTION: mWifiConnected=true mWifiLevel=4 mWifiRssi=-46
D/PhoneApp( 1754): getPhone phoneId:0
I/SBar.MotoNetworkCtrlr( 3619): updateTelephonySignalStrength[1]: phoneId=1 is not DDS( DDS_phoneId=0 ) ( SubscriptionManager.getPhoneId returned 0=0x00000000 )
D/PhoneApp( 1754): getPhone phoneId:1
I/SBar.MotoNetworkCtrlr( 3619): updateDataNetType[1]: phoneId1 is not DDS( =phoneId0 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 0=0x00000000 )
D/OwnCloudClient #66(13932): Location to redirect: https://$MYOWNCLOUD/index.php/apps/files/
D/skia    (13932): --- SkImageDecoder::Factory returned null
V/AlarmManager(  869): send {1efdfce5, *alarm*:com.android.server.WifiManager.action.START_SCAN}
V/AlarmManager(  869): done {1efdfce5, *alarm*:com.android.server.WifiManager.action.START_SCAN} [3ms]
E/WifiStateMachine(  869): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=17,72 rxSuccessRate=41,48 targetRoamBSSID=any RSSI=-46

**Comment by tobiasKaminsky** [comment]
> D/Thumbnail(13932): FileName: zz2ImC.png Download URI: https://$MYOWNCLOUD/index.php/apps/gallery/api/preview/42317/720/1184
D/OwnCloudClient #64(13932): REQUEST GET /index.php/apps/gallery/api/preview/42317/720/1184

The app tries to download the image in a resized version with 720x1184.
I do not understand from the log what happens.
Can you give me an account to your owncloud? Please send it to owncloud@tobiaskaminsky.de
Then I can better have a look what happens.

**Comment by RoxasShadow** [comment]
Done, thank you.

**Comment by tobiasKaminsky** [comment]
The resized thumbnails is using the gallery app.
The used url is something like:  https://drive.URL.net/index.php/apps/gallery/api/preview/224777/1080/1776
But even in my browser this gives me: {"message":"CORS requires basic auth"}
So there seems something wrong with the auth and gallery app.
This is the reason why the download of the resized image is failing and therefore the (rectangle) thumbnail is shown.

**Comment by tobiasKaminsky** [comment]
@RoxasShadow is this still valid for you?

**Comment by tobiasKaminsky** [comment]
@RoxasShadow ping?

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)
