### ISSUE TITLE
Hide FAB on multi select

### ISSUE THREAD

**Issue by AndyScherzinger** [owncloud/android#1404]
following up on the discussion in #1346 I was thinking it makes sense to hide the FAB when the multi select is active and show it again when multi select has been done. 

Pro:
* it removed the then unnecessary FAB since it has no actions for a multi select and could be considered clutter at this very moment

Con:
* show/hide might be confusing since it doesn't add extra functionality and might feel jumpy

Since I am not a UI/UX expert looping in @jancborchardt and also @tobiasKaminsky since it relates to the multi select discussion. What do you think? Personally I would hide it during multi select simply to "see" a list and nothing else :)

**Comment by tobiasKaminsky** [comment]
Would be fine for me.

**Comment by AndyScherzinger** [comment]
Would we also want a mechanism like "hide on scroll down" and "show again on scroll up"? I am just asking since some apps do this and this should be not to hard to implement observing the scrolling I guess. Just an idea though and I haven't tried to implement it yet, so no idea if and how easy this could be implemented, but like I said, it shouldn't be to hard to do I guess.

@jancborchardt what do you think about the two ideas/proposals

**Comment by tobiasKaminsky** [comment]
No, I think this would result in a flickering show/hide of the FAB menu.
So we should stay just with your first idea.

**Comment by AndyScherzinger** [comment]
Okay, sounds fine to me. Any comment @jancborchardt?

**Comment by AndyScherzinger** [comment]
pinging @jancborchardt again for his 2 cents ;)

**Comment by jancborchardt** [comment]
Ah sorry – yeah I also think your first proposal of simply hiding the fab on multiselect is the best way to go.

**Comment by AndyScherzinger** [comment]
OK! Thanks for the Feedback. I'll change it accordingly then :)

**Comment by AndyScherzinger** [comment]
Implemented, see https://github.com/owncloud/android/commit/cca2e60e4932c1351883d358e36322a5f8514baa now part of the multi select issue / PR #899 / #1176
