### ISSUE TITLE
(optional) Delete of successful uploaded files e.g. images, videos

### ISSUE THREAD

**Issue by hitam4450** [owncloud/android#1406]
Hi,
I noticed, that images uploaded to OC, are copied to owncloud/OC-installation/SofortUpload and that they 
are remaining there - until forever, thus still blocking urgently needed storage space on the SD-CARD .
Selecting an Option like: Delete image (video) after successful upload will make better use of the 
limited resources on a handset.

Since the image is stored in the DCIM folder as well, there is still ONE local copy available and 
not TWO copies, whereas the copy in the OC folder is only required for upload purposes.

regards, hitam4450

**Comment by AndyScherzinger** [comment]
Not sure if this is already covered by features currently being developed so pinging @przybylski and @tobiasKaminsky. I guess this is already available in the beta, right?

**Comment by tobiasKaminsky** [comment]
This is handled by #1168 which is in master now and therefore in the next release.
It is also in current beta: settings -> instant upload -> "original file will be..."

**Comment by hitam4450** [comment]
:thumbsup:
