### ISSUE TITLE
Folder list is not updated when a file is uploaded

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1408]
and as a consequence it is impossible to upload a file to a folder that was created after the app updated the folder list.

I think it would be good if fresh folder list would be fetched withing upload file dialog (when shared from other application)

**Comment by tobiasKaminsky** [comment]
This should be resolved by #1038 
Please confirm and then close.

**Comment by elpraga** [comment]
Nope, it is something different. 

Please try:
create a Test_folder in OC web interface or a desktop ap.
create a Level1 folder inside Test_folder in OC web interface or a desktop app
create a Level2 folder inside Level1 folder in OC web interace or a desktop app

Open a gallery app and try to upload an image into Level2 folder (via the share option)
- You will not be able to do so, as the folder Level2 never appears to be able to be selected in the upload dialog, even though it does exist in OC

only after You navigate to Level2 folder in the android app, it appears in the upload dialog.

**Comment by malkomich** [comment]
This was fixed with PR https://github.com/owncloud/android/pull/1399 and published on release 2.0.0

Please, check if it's already working and you can close it by yourself ;)

**Comment by elpraga** [comment]
Correct! Thanks!
