### ISSUE TITLE
Subheaders of share view

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1413]
Currently the share popup has these dark blue header boxes. This is a tad jarring and should instead be done by whitespace and proper header text (darkblue text color). Just like in the settings.

(Also, the Share text at the very top of the box should be correctly left aligned with the rest of the text.)

**Comment by AndyScherzinger** [comment]
I can work on this and also work on the search pop up for user and groups regarding margins and padding.

**Comment by jancborchardt** [comment]
Awesome! :)

**Comment by AndyScherzinger** [comment]
Just FYI development has been started on a new branch https://github.com/owncloud/android/tree/1413_share_view_enhancement

**Comment by AndyScherzinger** [comment]
Thing I didn't change is the title (!) due to that being Material Standard, thus the content a bit more to the left.

**Comment by AndyScherzinger** [comment]
pinging @jancborchardt for feedback on #1416 - so I can push it to beta :)

**Comment by davivel** [comment]
This was merged into master, and will be released in version 1.9.2
