### ISSUE TITLE
Multiple files: improve copy/move dialog

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1414]
They appear exactly the same and there is no way of knowing which is which as they appear only as an icon without any text

**Comment by AndyScherzinger** [comment]
@elpraga can you check with the latest release (today) 20150109 since I have replaced the icons there and copy and move to be distinguishable :)

**Comment by elpraga** [comment]
I can confirm. @AndyScherzinger in 20150109 the icons can be distinguished.

Do You think it would be nice to add "copy to" and "move to" respectively to the select folder dialog? Maybe just left from the three dots menu on the top right? This is just an idea though, if You feel like it is not good idea or it would be too much work to implement it, we can close the issue

**Comment by tobiasKaminsky** [comment]
For me there are no icons? The list, which is opened after clicking the three dots, shows only text?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky there should be ;) - what @elpraga means are the following icons you can see in the screenshots in  #1411

**Comment by AndyScherzinger** [comment]
@elpraga can you provide some more details on the select folder comment? From what I understand you want to move/copy files from within a folder chooser. If so I would recommend against it since it mixed we the actions one would expect in the context of choosing. So imho when selecting a folder, selecting a folder should be the only action (except for creating a folder though)

**Comment by elpraga** [comment]
I will as soon as I get home in a little bit.  The chance in icons you made
in 20160109 was great.
My last suggestion was to add an informative text in the choose folder
dialog that appears after clicking on respective icon.

If you click on the copy icon for example,  the dialog that appears would
say "copy to" in the top part,  just informing what are we selecting the
folder for.

But as I mentioned before,  I don't see it crucially important.  I just
think It would be nice if it doesn't require almost any extra work.

**Comment by AndyScherzinger** [comment]
Ah, now I get what you mean, sorry! This shouldn't be to much work to be implemented imho and yes, this would totally make sense. But that is also just my opinion. @tobiasKaminsky @jancborchardt what do you think? I vote yes on implementing this. copy/move in the title to show this context information.

**Comment by tobiasKaminsky** [comment]
This is a good idea.
cc @jancborchardt for the exact wording

**Comment by jancborchardt** [comment]
Yeah, good call. »Copy file/foldername to« and »Move file/foldername to« in the header woulf be good wording.

Additionally if possible, it's always good to show the thumbnail of the file/folder to the left in that modal header. And have a relevant label for the button, like »Copy« / »Move«.

**Comment by AndyScherzinger** [comment]
@jancborchardt be aware that you can have a multiple selection and then hit move/copy so the (list of) files/folders wouldn't make sense the action bar title... :)

**Comment by tobiasKaminsky** [comment]
If there is more than one image we could show them stacked:
http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/3d-transparent-glass-icons-business/076001-3d-transparent-glass-icon-business-document1.png

**Comment by jancborchardt** [comment]
Good call – show the first 3 of them in this stacked way, and then in the title say »Move 21 files to …«

**Comment by tobiasKaminsky** [comment]
I have updated the title and removed the label as the latest idea by @jancborchardt is not related to beta any longer but a new idea for the dialogs.
