### ISSUE TITLE
Keep in sync additional folders

### ISSUE THREAD

**Issue by RoxasShadow** [owncloud/android#1417]
I'd like to keep in sync additional custom folders (WhatsApp Images, Screenshots...).

To keep things simple from a UI prospective we could store these folders inside the same paths selected for camera pictures.

**Comment by tobiasKaminsky** [comment]
There is already an approach doing this: #744 
If I find enough spare time I will implement it and then put it in beta.
If this is the same as you want, please close this issue and comment in the linked issue.

**Comment by RoxasShadow** [comment]
It is. I searched through the issues but I wasn't able to find that. Thank you.
