### ISSUE TITLE
User list for sharing contains signed in user

### ISSUE THREAD

**Issue by cwmke** [owncloud/android#1419]
Using fdroid's owncloud beta20160109 on a Nexus 6p with PureNexus rom, I perform the following steps,
1. Long press on a folder I would like to share with another user.
2. Press the share button in the top bar.
3. Click 'Add User Or Group'.
4. Type in user's name.
5. List pops up with all users including my own.

This isn't very major, but it seems like (from what I can tell) it's unnecessary.

**Comment by tobiasKaminsky** [comment]
Thank you for this report.
CC to responsible devs: @masensio @davivel

**Comment by davivel** [comment]
Yes, the web UI filters it out, we could do the same.
