### ISSUE TITLE
When server certificate has changed, always show certificate info. Certificate-untrusted info is not shown when syncing.

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/android#1420]
My OC server uses a CAcert.org certificate (which had to be manually "trusted" after checking the fingerprint when the oc client was setup initially).

I recently updated the certificate, because it was close to expire.

When upstarting the OC Android client, or when clicking "Konto aktualisieren" (account sync), no warning information was shown (that the certificate has changed).

But when actually performing a file action like "delete file on the server" (I only tried "delete" actions), the client shows the certificate-untrusted warning, so that I then could manually check the new fingerprint and set permanent trust to the renewed connection's certificate.

I regard the following as a bug:

* certificate is not tested during syncing (certificate-has-changed information is not shown during syncing; it _is_ however tested when actually performing a file action like delete.

**Comment by masensio** [comment]
Hi @Wikinaut,

thanks for your feedback.

We need to improve the way to manage the certificates. We will have into account this issue when improving the certificates management.

**Comment by rperezb** [comment]
@Wikinaut this has been reported previously, let's follow the status on: #609 thx
