### ISSUE TITLE
Feature request: Instant Upload to create year/month subfolders

### ISSUE THREAD

**Issue by stefanhoth** [owncloud/android#1421]
It would be great to customize the instant upload feature in a way that uploaded photos are stored in a subfolder per year/month so they will be easier to find and the InstantUpload folder stays manageable.

---

Right now users of the app can only choose one target folder and all files will be uploaded to that folder. This is obviously a very convenient thing but after a few months this folder is messed up with hundreds or thousands of images and videos - even owncloud it self has trouble loading this.

With an automatic optional subfolder `InstantUpload/<year>/<month` users would be enabled to find their files more easily and minimize the traffic when browsing images.

**Comment by masensio** [comment]
Hi @stefanhoth,

Thanks for your ideas for improving ownCloud App.
We will have your thoughts into account for future enhamencement into the instant uploads setup.

Thanks for using ownCloud.

**Comment by rstefko** [comment]
I would also appreciate this feature.

**Comment by tobiasKaminsky** [comment]
For me this is a nice feature but has a very low priority as the user can adjust this manually.
This requires three steps per month.

**Comment by davivel** [comment]
This is duplicating #520. Please, let's track any progress there. 

Thanks.

**Comment by davigonz** [comment]
As the comment just above says, this is duplicated, so closing it... please follow up #520.
