### ISSUE TITLE
»New folder« entry in top right 3-dot menu

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1425]
This seems to be duplicated from the FAB and we should remove it from that 3-dot-menu.

Also, when the sidebar is open, tapping the 3-dot menu _only_ shows the »New folder« entry, but not the other entries. Should show everything, no?

**Comment by AndyScherzinger** [comment]
Hey @jancborchardt so the first issue should target the FAB branch imho and about the second issue I am not sure of this is the best way to handle it. In my opinion when the drawer is opened no menu should be shown in the action bar at all :) Just my 2 cents :)

**Comment by jancborchardt** [comment]
Ok, showing no menu when the sidebar is open is fine for me as well – then the 3-dots should jist be hidden. :)

**Comment by AndyScherzinger** [comment]
Excatly, that is what I meant! Less distraction! :)

**Comment by jesmrec** [comment]
Done
