### ISSUE TITLE
Remove grey lines in sidebar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1428]
The whitespace is enough as separator, and the grey lines look a bit old-style. Removing them will look much better.

**Comment by AndyScherzinger** [comment]
DONE on https://github.com/owncloud/android/tree/drawer_enhancements

Will add further drawer related changed on the branch though

**Comment by AndyScherzinger** [comment]
@masensio would you be so kind as to delete this branch? Tried to rebase it to latest master, messed it up again :disappointed:

**Comment by AndyScherzinger** [comment]
new successor is #1559 therefore closing this issue.

**Comment by AndyScherzinger** [comment]
@davivel can you delete this branch? It is obsolete now https://github.com/owncloud/android/tree/drawer_enhancements

Thanks :smiley: :+1:

**Comment by AndyScherzinger** [comment]
besides that the change has been merged to master and will be released with v2.0.0 :) 
--> https://github.com/owncloud/android/commit/2d0fc03ef0d566337d82b61a77cb3ee19961a11f

**Comment by davivel** [comment]
Thanks, @AndyScherzinger
