### ISSUE TITLE
Settings and log should replace the content just like the files list instead of opening separate views

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1429]
Just as said in the title. Amy reasom we do not do this at the moment?

**Comment by AndyScherzinger** [comment]
Nope they should absolutely not and never ever! ;) Sorry for the wording but Settings and Logs and files are there different contexts with three totally different use cases and thus functionality thus they are three activities which end up in three different view by (Android platform design) design. This is basically how Android works and I don't see any reason whatsoever why we should change that...ever!

**Comment by jancborchardt** [comment]
Okidoke, thanks for the clarification in that case. :)

**Comment by AndyScherzinger** [comment]
Woohoo! Sorry, I really hope I wasn't rude in any way but this requirement really shocked me! :smiley:

**Comment by jancborchardt** [comment]
Nah, thanks for educating me about Android platform standards. :) It wasn't a requirement, just a though cause from a web app design perspective it seems simpler if it's just a sidebar and a content view.
