### ISSUE TITLE
Hide the extra instant upload settings if they are not enabled

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1430]
For some reason in the beta all the settings are shown. When instant upload is not enabled, none of the extra settings belonging to that should be shown though.

**Comment by AndyScherzinger** [comment]
Is think @tobiasKaminsky implemented it the way you described it. It seems this got broken at some point in time.

**Comment by jancborchardt** [comment]
Yup – in the current stable release it works.

**Comment by tobiasKaminsky** [comment]
Ok, this comes from me :)
https://github.com/owncloud/android/blame/beta/src/com/owncloud/android/ui/activity/Preferences.java#L634
But there must be a reason why I have disabled this on the other branch, so I just enable it on beta.
