### ISSUE TITLE
Secondary button text color

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1435]
Currently the secondary button is grey with the dark ownCloud blue as text. However that's a bit much use of the brand color.

Better would be to have the text color here black. Or if that's too intense compared to the primary button, a dark shade of grey.

**Comment by AndyScherzinger** [comment]
The actual style is defined in style.xml:
```
	<style name="Button" parent="Base.Widget.AppCompat.Button">
		<item name="colorButtonNormal">@color/secondary_button_background_color</item>
		<item name="android:textColor">@color/secondary_button_text_color</item>
	</style>

	<style name="Button.Primary" parent="Button">
		<item name="colorButtonNormal">@color/primary_button_background_color</item>
		<item name="android:textColor">@color/primary_button_text_color</item>
	</style>
```
but the colors are of course defined in setup.xml which is only touched by the core developers. 
@davivel can you take care of this issue. Imho just change the color reference:
```
<color name="secondary_button_text_color">@color/black</color>
```

**Comment by davivel** [comment]
Thanks, @AndyScherzinger , I'll take care.

Anybody may touch setup.xml . The point is, maybe I complain :P

**Comment by AndyScherzinger** [comment]
Sweet, thanks! :+1:

**Comment by rperezb** [comment]
Done via: https://github.com/owncloud/android/commit/3a5ce4838c12e4bfdd580c7a878b89a9c6044e38
