### ISSUE TITLE
Reduce visible information in progress screen 

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#144]
Some files like PDF and TXT don’t open directly yet, like images. Instead they still have the strange detail screen where you have to manually click »download«.

Instead, the default for everything (even unreadable file types) should be trying to show them, and having the »Details« only in the menu (if at all, but we’ll check that in the UX flow).

**Comment by tobiasKaminsky** [comment]
Is this issue still open? @jancborchardt

**Comment by jancborchardt** [comment]
Yes. Just click on a PDF which hasn’t been downloaded yet and watch the loading screen which has way too much info. Should just be the thumbnail and a loading bar.

**Comment by jesmrec** [comment]
Expected flow for the moment. Feel free to reopen if any other idea raises.
