### ISSUE TITLE
Bad wording "delete account" in Android app (scares user)

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/android#1440]
In the settings you’ll have to long press the username and then chose ‘delete account’ to remove a local account from the app. This is kind of a bad wording. It does remove the account from the ownCloud app but for the user this is just a ‘logout’ on this device, so that he has to type in the username/password again the next time he starts the app. This doesn't really delete the account on the server side. (which is good)

Please consider to rename this action to "logout" because ‘delete account’ sound pretty destructive.

cc @rperezb @jancborchardt @MTRichards @michaelstingl 

00004565

**Comment by MTRichards** [comment]
Wording change is pretty simple, but what is recommended? I would prefer a specific request, so we are not guessing on what they think is a non destructive name.

In truth, "logout" is what we are doing, but @rperezb are we doing anything else - such as removing cached data, for example?

**Comment by jancborchardt** [comment]
Removing cached data would also be fully ok and be expected. However I think »Log out« is not a fully correct wording for what we want to do.

Maybe »Delete account from device« fits better here? Or is the use of the word »Remove« a tad more fitting?

**Comment by MorrisJobke** [comment]
> In truth, "logout" is what we are doing, but @rperezb are we doing anything else - such as removing cached data, for example?

Doesn't seem to work yet: https://github.com/owncloud/android/issues/125

**Comment by AndyScherzinger** [comment]
Most Apps I know that don't delete any data on the server side (didn't check the client side) use "remove account", this seems to be a less scary and also a common wording.

**Comment by MTRichards** [comment]
@AndyScherzinger I like this wording.
@rperezb is there anything we are doing for which this doesn't work?

**Comment by tobiasKaminsky** [comment]
When #125 is implemented it should also inform the user that the local files are deleted as well.

**Comment by jancborchardt** [comment]
Good, »Remove account« works then.

**Comment by rperezb** [comment]
yes, agreed "Remove account", makes sense. Let´s add this as a requirement for the next version.
For the moment, when a user "delete the account", on Android, no data is removed.

On the other hand, taking advantage of this thread looking for parity on iOS, on iOS we use the wording "Delete", in this case, we are removing the downloaded data. Is "Delete" ok?

**Comment by marcobettoni** [comment]
Interesting discussion ... I am rather surprised: is this user-friendly?
I do not know of any other piece of software where in order to close the session you need to activate a function called "delete / remove account"!
I am "only" a user of this app, from my perspective, I miss there a simple, standard "logout" function;  I just whant to close my session, so that another person cannot operate by using my identity (and my data) and I am not interested in what developer do in the background or how the call the function in the code, but on the user interface you need to provide user-friendly interaction.
"Delete account" or "remove account" may make sense from a developer perspective (although it is strange also), but for a user it sounds like: your password, name and all other profile information will be removed/deleted.

**Comment by AndyScherzinger** [comment]
Hi @marcobettoni I see your point. From what I understood from the discussion the app's behavior would exactly be that: removing this account from the phone including the removal off all the data (while of course keeping it on the server). 
While you are right, the logout, would simply mean end the session keep everything on the phone.

@ all - am I right with the interpretation that with >remove account< everything related to the account, e.g. profile, downloaded files, etc. should be removed from the phone? Or do we simply want to do a logout?

**Comment by MorrisJobke** [comment]
> @ all - am I right with the interpretation that with >remove account< everything related to the account, e.g. profile, downloaded files, etc. should be removed from the phone?

I think that is what you sometimes what to do - remove that account (and maybe use a different one). And that is also what is already implemented (beside the local file deletion).

The logout is a rather different use case.

**Comment by jancborchardt** [comment]
@marcobettoni First off, a »Log out« function is a completely new feature request, so a different issue. :)

And secondly since this is about Android specifically, I would say there are 3 other measures in place already to prevent misuse by others:
- the app passcode you can set in the settings
- the lock mechanism of the operating system itself
- the user management and guest user functionality of the operating system which is intended for exactly this

**Comment by jancborchardt** [comment]
@AndyScherzinger yes, »Remove account« should remove everything of course. It was just not fully implemented yet it seems.

**Comment by davivel** [comment]
Hi @marcobettoni, 

> but for a user it sounds like: your password, name and all other profile information will be removed/deleted.

That's exactly what is happening.

>  I miss there a simple, standard "logout" function; I just want to close my session, so that another person cannot operate by using my identity (and my data) .

May I ask you in what situation you need this? Are you using the Android app in a device shared with other people? 

Thanks in advance.

**Comment by marcobettoni** [comment]
Hi @davivel ,
>May I ask you in what situation you need this? Are you using the Android app in a device shared with other people? 
Sometimes other people may use my device (in my family, or in classes with students, etc.)

**Comment by tobiasKaminsky** [comment]
@marcobettoni Then this is a perfect scenario for the pin system.
Besides that: If the files are downloaded they are accessible by all other apps (like file explorer), so you cannot prevent other people to see your private data.

**Comment by jancborchardt** [comment]
Exactly. Just use the passcode functionality in settings @marcobettoni. :)

**Comment by davivel** [comment]
Back with the wording: "remove account" sounds OK in English, but in **Spanish** probably the translation will be exactly the same as for "delete account". I guess this may happen in other languages too.

What about **"Forget account"**? 

"Forget" is not unknown for the users; may be found, for instance, in the Wifi options, in "Forget network" to remove saved network configurations.

**Comment by davivel** [comment]
@all, any thoughts?

**Comment by AndyScherzinger** [comment]
"Forget account" sounds fine to me too. I get the point that translation might end up with ending up with a "delete" meaning. :(
Remove was just the idea since I simply looked up Google's wording for this kind of action.

**Comment by jancborchardt** [comment]
Yep, »Forget account« sounds good too. At this point we just need to roll with one – either »Remove« or »Forget« is fine. We could first go with »Remove« since that seems to be used by other apps. When there are still complaints, we can change it further.

**Comment by rperezb** [comment]
@MorrisJobke @michaelstingl hope this is fine for you too

**Comment by MorrisJobke** [comment]
> @MorrisJobke @michaelstingl hope this is fine for you too

Yes

**Comment by tobiasKaminsky** [comment]
Or be a little bit more verbose to clarify what is meant: remove account from device.
Then the user is absolutely sure that the account on the server is not meant/touched.

**Comment by davivel** [comment]
"Remove account" applied in 1eb1a597dcab91fafad56a33e42c3171ef844e05 .

(Sorry, @tobiasKaminsky , I read your message after pushing the change)

**Comment by davivel** [comment]
Will be in version 1.9.1

**Comment by rperezb** [comment]
@carlaschroder not sure if this change affects documentation

**Comment by carlaschroder** [comment]
It does, thanks @rperezb.
