### ISSUE TITLE
App drains battery

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1442]
Not sure what exactly it’s caused by, but today has been the third instance of the ownCloud app eating my battery in a massive way. Even though I wasn’t really using it today so far.

System is a Moto G with Cyanogenmod 12.1, Android 5.1. I use 2 accounts, no instant upload, some favorites though.

Can anyone reproduce @tobiasKaminsky @AndyScherzinger @llucax @davivel @masensio 

![screenshot_2016-01-20-15-46-10](https://cloud.githubusercontent.com/assets/925062/12452373/635baf70-bf8e-11e5-8541-dd031ee470f1.png)
![screenshot_2016-01-10-02-18-30](https://cloud.githubusercontent.com/assets/925062/12452374/636ae03a-bf8e-11e5-973f-a632e4617761.png)
![screenshot_2016-01-04-08-35-24](https://cloud.githubusercontent.com/assets/925062/12452375/636e93ba-bf8e-11e5-9720-6f5db831460c.png)

**Comment by AndyScherzinger** [comment]
Probably fixed in 1.9.1, see #953 #1338 - resolving issue being #1359

**Comment by jancborchardt** [comment]
Ok, hope that release is being pushed out soon @MTRichards @davivel @rperezb, draining battery is a pretty grave issue.

**Comment by MTRichards** [comment]
Yep, next version will have it - planned shortly.

**Comment by rperezb** [comment]
Done, this will be included within the next version, 1.9.1

**Comment by jancborchardt** [comment]
Next time when something app-breaking like this happens, we need to push out a fix immediately. Otherwise people will uninstall the app and possibly not install it again because they lost trust.

**Comment by davivel** [comment]
@jancborchardt, thanks for your feedback. Your comment will be very useful to speed up future updates.
