### ISSUE TITLE
Synchronization has to be performed manually

### ISSUE THREAD

**Issue by bidinou** [owncloud/android#1443]
Hi ! 

When using the Android OwnCloud client, I have to manually select a file and click on "synchronize" otherwise, its content is not updated -- although the file properties are correctly updated in the Owncloud client.

STEPS TO PERFORM
1) perform the initial synchronization
2) for instance I have a file called todo.txt in Documents/ which is properly synced
3) I make a modification on my desktop client (KDE under Kubuntu). 
4) I make sure this is properly uploaded to the server : this is OK (checked from web interface)
5) the file is not synced on the Android device
6) I check the Owncloud client on the Android device : I can see the new filesize and new file date is displayed but when I click on the file, I can still see its former content
7) the only way to make the OC Android client sync it properly is to select "synchronize" in the file context menu

The problem is it has to be done manually each time. This is misleading as files attributes, in the OC client, are the right ones but the file content is not updated.

Using : 
- Server : Owncloud 8.1 (web4all.fr hosting)
- Desktop client : Kubuntu 14.04 LTS + Owncloud client v.2.1
- Android Phone : Samsung Galaxy Core Prime LTE ; Android 5.0.2
- Android Owncloud client : 1.9.0

Thanks to everyone involved ! Cheers !

**Comment by rperezb** [comment]
@bidinou can you please check the same but checking as a favorite the file?
If you check it as favorite, changes will not only be downloaded but also uploaded if they came from the device itself.
 If this didn't work, please reopen
