### ISSUE TITLE
Select and display image in Beta 20160120 broken?

### ISSUE THREAD

**Issue by cornzy** [owncloud/android#1444]
Just tested the latest Beta (20160120). When I open a image that is not already downloaded by the owncloud app, only the square preview is shown. Full scale image is only available after explecitly select "Download".

In addition with instant upload and "Original file will be ... kept in original folder" it is even worse because the image is downloaded again and is hence is again duplicated in the android galery.

**Comment by tobiasKaminsky** [comment]
This means that somehow the resized image generation is failing.
It needs gallery+ for oc <8.1 and gallery for oc >= 8.2.
Has it worked for you on previous betas?

Second problem: This is known and intended as the app has no infos where the file was coming from. So it will download the file from oc server.

**Comment by cornzy** [comment]
@tobiasKaminsky ok, I have oc 8.2.2 and gallery+ ... that's no good combination?
I am not sure if it ever worked on previous beta but it works with stable app.

Second problem: I thought the app knows when it was uploaded using the same app. Doesn't it has an internal database for such inforamation? That means: I need to set "Original file will be ... move to app folder" to fix this?

**Comment by tobiasKaminsky** [comment]
@cornzy is this still valid?

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)
