### ISSUE TITLE
Beta 20160120: Missing german translation for new setting options

### ISSUE THREAD

**Issue by cornzy** [owncloud/android#1446]
In the german version the new settings are not translate:

First level: "On device" --> "Lokal gespeichert"

In Settings (Einstellungen):
"Storage path" --> "Speicherort"
"Upload when charging only" --> "Upload nur beim aufladen" (absolut correct german would be: "Hochladen nur während des Aufladens" but "Upload" does not necessarily be translated and it would be too long)
"Original file will be..." --> "Original speichern ..."
... "kept in original folder" --> "im ursprünglichen Ordner"
... "moved to app folder" --> "in Owncloud Ordner verschieben"

"Common" --> Allgemein
"Cache size" --> Cache größe"

Beta specific settings (if needed):
"Download latest beta version" --> "Letzte Betaversion runter laden"
"Changelog beta version" --> Änderungsliste betaversion

And btw: I think the translation "Dies einem Freund empfehlen" should be called "Owncloud weiterempfehlen" or "Die App weiterempfehlen".

**Comment by tobiasKaminsky** [comment]
Translation is done with transifex.
As they are only using the strings from official version there is no possibility to translate it.
Of course it will be translated once the feature is in official repo.

**Comment by tobiasKaminsky** [comment]
If you have proposals for the existing translations please go to transifex and talk to the guys there.
