### ISSUE TITLE
Can't upload videos to OC from mobile

### ISSUE THREAD

**Issue by Zevleu** [owncloud/android#1448]
Hello,
I'm newbie in OC, but I'm stuck and cannot find any solution.
I'm running OC8.2 on headless Debian Server (Trusty) with MySQL. I am running OwnClient Android appli on Android 5.0.2/Samsung S5: I have Instant video upload and Inst enabled on Android App, with upload via Wifi only

Here is description of the issue and outcome of my investigations:
- If I'm connected on my Wifi home network with my mobile and I record a video, the video is immediately uploaded to OC. This is perfect.
- If I'm not connectd on wifi network and I record a video, this video will never be uploaded to my OC when I'm back at home, connected on my Wifi.

Additinal information  :idea: :
- I have also changed the OC folder for video upload several time (I have initially suspected that using same folder for images and videos could cause troubles), but it does not change anything.
- when a video is uploaded successfully (when I'm at home, recording and connected), I get the following error in the logs:
Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58

Your help will be appreciated.
Zevleu
Newbie
 
Message(s) : 2
Inscription : Dim Jan 03, 2016 7:46 pm
ownCloud version: 8.2.2
Webserver: nginx
Database: MySQL
OS: Linux
PHP version: 5.4.45
Haut
Re: Video upload does not work properly
Message par Zevleu » Lun Jan 04, 2016 8:32 am

I forgot to add that upload of images runs fine in all cases.
The issue occurs only with videos.
Zevleu
Newbie
 
Message(s) : 2
Inscription : Dim Jan 03, 2016 7:46 pm
ownCloud version: 8.2.2
Webserver: nginx
Database: MySQL
OS: Linux
PHP version: 5.4.45
Haut
Re: Video upload does not work properly
Message par tflidd » Lun Jan 04, 2016 11:04 am

For Android issues please see https://github.com/owncloud/android/issues

**Comment by davivel** [comment]
Duplicated in #1448
