### ISSUE TITLE
Video not uploaded to OC from mobile

### ISSUE THREAD

**Issue by Zevleu** [owncloud/android#1449]
### Actual behaviour
I'm running OC8.2 on headless Debian Server (Trusty) with MySQL. I am running OwnClient Android appli on Android 5.0.2/Samsung S5: I have Instant video upload enabled on Android App, with upload via Wifi only

Image upload runs perfectly. The issue is with video.
Here is description of the issue and outcome of my investigations:
- If I'm connected on my Wifi home network with my mobile and I record a video, the video is immediately uploaded to OC. This is perfect.
- If I'm not connectd on wifi network and I record a video, this video will never be uploaded to my OC when I'm back at home, connected on my Wifi.

Additinal information  :idea: :
- I have also changed the OC folder for video upload several time (I have initially suspected that using same folder for images and videos could cause troubles), but it does not change anything.
- when a video is uploaded successfully (when I'm at home, recording and connected), I get the following error in the logs:
Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58

### Environment data
Android version: 5.0.2

Device model: Samsung S5 SM-G901F

Stock or customized system:

ownCloud app version: 1.9.0

ownCloud server version: 8.2.2

### Logs
Error	PHP	Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58	2016-01-22T22:04:57+00:00
Error	PHP	Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58

#### ownCloud log (data/owncloud.log)
{"reqId":"1tjBrYjQLLFxJ55ma0ZR","remoteAddr":"192.168.0.14","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-01-22T22:04:43+00:00"}
{"reqId":"XA+ExzSWjJtMQlVkq7Ow","remoteAddr":"192.168.0.14","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-01-22T22:04:57+00:00"}

**Comment by davivel** [comment]
Hi, @Zevleu . I'm sorry, but automatic retry of instant videos was never implemented. Please, track its progress in #349

**Comment by Zevleu** [comment]
Hi
I would like to add that upload retry, when appropriate network is recovered, works properly for pictures.
The issue only happens for videos.

Kind regards 
Zevleu


----- Mail d'origine -----
De: David A. Velasco <notifications@github.com>
À: owncloud/android <android@noreply.github.com>
Cc: Zevleu <vincent.lescaut@free.fr>
Envoyé: Fri, 26 Feb 2016 21:44:05 +0100 (CET)
Objet: Re: [android] Video not uploaded to OC from mobile (#1449)

Hi, @Zevleu . I'm sorry, but automatic retry of instant videos was never implemented. Please, track its progress in #349 

---

**Comment by davivel** [comment]
Yes, sorry, I was not clear enough. The issue I redirected to will cover retry of videos also.
