### ISSUE TITLE
sdk componet not installed in android studio.

### ISSUE THREAD

**Issue by vaibhavshettar5** [owncloud/android#1456]
sdk componet not installed : build-tools-21.1.1
i f any know then provide me download link.

**Comment by przybylski** [comment]
In android studio preferences 
<img width="1039" alt="zrzut ekranu 2016-01-28 o 17 46 32" src="https://cloud.githubusercontent.com/assets/1734309/12651598/71f03f7e-c5e7-11e5-80cd-8deb6f94c703.png">

**Comment by tobiasKaminsky** [comment]
@vaibhavshettar5 Could you solve it? Otherwise please reopen.
