### ISSUE TITLE
Folder sync: future plan?

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1458]
What is the plan of integrating folder sync?
Will this be "only" for folders within owncloud? Or should this also work for every directory on the phone?
Example: I download lots of images with chrome. They all go to sdcard/downloads. To have these images synced I would now need #744, but maybe folder sync can also do this?

@davivel @rperezb

**Comment by proninyaroslav** [comment]
Whether there are any developments in terms of support for the synchronization of any selected folder/folders? I could help you with this.

**Comment by masensio** [comment]
Hi @tobiasKaminsky,

Nowadays the next step for folder sync is to habe Favourite Folders, as Favourite File. 
So in the future (I hope in a near future) we could select a folder as favourite and this folder will be automatically synchronized when the application detects some change on it.

For the moment folder sync process is only for owncloud folders. 
Sync of any other phone directory would be in another feature, which for now is not on our roadmap. In the future, who knows.

**Comment by proninyaroslav** [comment]
@masensio 
> Nowadays the next step for folder sync is to habe Favourite Folders, as Favourite File. 
How many folders can be add? I would not be limited to only one.

**Comment by rperezb** [comment]
@proninyaroslav certainly it won't be limited to a certain number, as it's not limited the number of files that you want to set us favorite neither this feature is limited on the iOS app, where it's already implemented

**Comment by davivel** [comment]
About synchronizing files & folders mapped into the local owncloud folder, next steps are summarized in #1677.

About synchronizing files created / updated in the mobile device out of the local owncloud folder, #744 is a good place to to keep going.

Let's track progress there, and in the issues linked in them.
