### ISSUE TITLE
Add Google analytics to the app

### ISSUE THREAD

**Issue by przybylski** [owncloud/android#1459]
So there is a feedback on which features are actually used

**Comment by LukasReschke** [comment]
Considering that ownCloud is a project that preaches data security I somehow have a small doubt that we're going in that direction :wink:

**Comment by przybylski** [comment]
Not interfering in user data and storing statistics for app improvement are two different things IMO

**Comment by przybylski** [comment]
Beside we can always ask: "Would you like to provide anonymous statistics to improve this app?"

**Comment by hitam4450** [comment]
Why adding a 'Spy' system to OwnCloud, which prays its '*privacy'* feature?

If that is going to happen, i certainly will terminate the use and any activity for OwnCloud!

**Comment by jospoortvliet** [comment]
@hitam4450 is probably a typical user. Many users use ownCloud to get away from Google storing all your data, adding it back seems a bad diea. Also, 'anonymous' it won't be.

Self-hosted piwik statistics makes sense, using services from a external provider won't happen.

**Comment by tobiasKaminsky** [comment]
@jospoortvliet So, maybe we can reopen this issue and replace "google app" with "self written statistic" app?
Or do you think it is not worth the man power?

**Comment by jospoortvliet** [comment]
@tobiasKaminsky well, I do think it would be ok if we'd control the data, people might trust us (not Google). The question then is if it is worth it - that's a though one and essentially something for @MTRichards and @rperezb as they have to decide if this information would be useful for setting the development direction of the app.

I think we're already providing ways for users to give feedback and have a huge todo list. This might help with hard questions like 'do users use X or should we remove it', of course, but it will be quite some work to add it I suppose. I wouldn't give it high priority, personally.

**Comment by tobiasKaminsky** [comment]
For me this is fine, I just wanted to open the discussion that we discuss the pro/cons of the self-hosted analytics and not just say that google is bad and therefore end the thinking of this feature.
