### ISSUE TITLE
[1.9.1] Release of the new version

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1460]
AC:
- [x] Freeze the code https://github.com/owncloud/android/tree/release-1.9.1
- [x] Regression test plan 
- [x] Release of the new version

- Minor changes included on the 1.9.1 branch:
   + Change "delete account" wording https://github.com/owncloud/android/issues/1440
  + Change secondary button color: https://github.com/owncloud/android/issues/1435

**Comment by davivel** [comment]
Release branch frozen.

Let the tests begin.

:beer:

**Comment by davivel** [comment]
Code corresponding to the version in https://github.com/owncloud/android/releases/tag/oc-android-1.9.1 .

Matching version of the OC client library for Andorid in https://github.com/owncloud/android-library/releases/tag/oc-android-library-0.9.10 . 

Enjoy!
