### ISSUE TITLE
(Self-signed) cerificate changes

### ISSUE THREAD

**Issue by t-h-e** [owncloud/android#1463]
When the server uses a different/new certificate, the client just does not update any files anymore. There is no warning or anything.

GoTo Settings -> Add account -> Type in server address -> Client is going to check the connection and asks if you trust the certificate. Accept and everything works again.

Probably only an issue with self signed certificates.

**Comment by masensio** [comment]
Hi @t-h-e,

thanks for your feedback.
This is an issue when server certificate changed. As a workaround you don't need to delete the account, if you go to Settings --> Select account --> Change Password, you can accept the certificate again.

We need to fix this issue. 

It is the same than #1480.

**Comment by t-h-e** [comment]
I didn't say you need to delete the account, just open the add account page and type in the server address. The existing account will work again, after accepting the certificate.

Thanks for the fast reply. Sorry for the duplicate.

**Comment by masensio** [comment]
Sorry, I thought to read "Delete Account" in your steps. If you select Change Password you don't need to type anything.

In any case, we need to fix it.

**Comment by rperezb** [comment]
@t-h-e this has been reported previously, let's follow the status on: https://github.com/owncloud/android/issues/609 thx
