### ISSUE TITLE
Getting clients for testing

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/android#1464]
Hellos! I need beta clients for testing & writing up docs for new releases. It would be lovely if I could have new docs completed by the release date :) Not sure how to get pre-releases; is there a daily build somewheres? I don't really want to get bogged down in learning to build them. Thanks!

@rperezb @davivel @masensio

**Comment by tobiasKaminsky** [comment]
There is a beta version managed by me, but there are more features than in the new release.

**Comment by carlaschroder** [comment]
I really need something that looks like the final release :)

**Comment by rperezb** [comment]
@carlaschroder I think this may be closed too!

@tobiasKaminsky very appreciated your help :+1:

**Comment by carlaschroder** [comment]
Thank you @tobiasKaminsky and @rperezb :)
