### ISSUE TITLE
No resource found: 'style/Theme.Sherlock.Light.Dialog'

### ISSUE THREAD

**Issue by dahan1999** [owncloud/android#1474]
Error:(727) Error retrieving parent for item: No resource found that matches the given name 'style/Theme.Sherlock.Light.Dialog'.

I clone the latest repos and in the first compile I run into this error.

Anyone know how to solve it?

**Comment by tobiasKaminsky** [comment]
Which branch do you use?
Sherlock should not be used any longer

**Comment by dahan1999** [comment]
I am using https://github.com/owncloud/android

**Comment by AndyScherzinger** [comment]
Did you follow the instructions in https://github.com/owncloud/android/blob/master/SETUP.md development is only supported for gradle and ANT at the moment.

**Comment by tobiasKaminsky** [comment]
@dahan1999 Yeah, but which branch? You should use master.
I think "develop" could be so old that you get these error messages...

**Comment by dahan1999** [comment]
I am sorry that I use an outdated branch. The issue is solved. Thank you for your help.

**Comment by tobiasKaminsky** [comment]
Glad it works!
