### ISSUE TITLE
Cant Download and Upload file from Android

### ISSUE THREAD

**Issue by rijudewan** [owncloud/android#1478]
cant download any file  i try 1kb file and 40MB file both same cant download  ...
error ..
Operation finished with HTTP status code 503(fail) in log file...

But from desktop client it does not have any issue

**Comment by tobiasKaminsky** [comment]
Is it working with demo.owncloud.org (user/pass: test)

**Comment by rijudewan** [comment]
yes its working .. with demo server ...
can any one give me the hint  .. y its not working in my server ...?

**Comment by strugee** [comment]
@rijudewan we have no idea. You need to provide logs and version numbers. Fill out the [issue template][1].

 [1]: https://raw.githubusercontent.com/owncloud/android/master/issue_template.md

**Comment by rijudewan** [comment]
thanks its working now .. it was encryption problem ...
