### ISSUE TITLE
Downloads fail on mobile clients after server changed ssl key (browsing works fine, iOS also affected)

### ISSUE THREAD

**Issue by pgroe** [owncloud/android#1480]
### Expected behaviour
Server changed SSL key after expiry (self signed certificate).
Clients should ask for accepting self signed certificate and then work fine

### Actual behaviour
Browsers and desktop clients correctly recognize new certificate, ask for overriding self signed and work fine after accepting.
Mobile clients (Android and iOS) continue browsing repository, but fail to download and upload files (without any error message in client or server - not sure about this but didn't find anything).

### Steps to reproduce
1. Use Server with self signed SSL certificate
2. Create profile on mobile clients
3. Let server certificate expire
4. Change server certificate to new self signed certificate
5. Browse files with mobile client and try to download or upload files

### Workaround
- delete profile on mobile client
- recreate profile on mobile client (offline data keeps present, but certificate is validated)

### Environment data
Android 4.1.2 and iOS 9.2.1

ownCloud app version:
current (1.9.1) on Android, current (17.02.2016) on iOS

ownCloud server version:
8.2.2

#### Web server error log
[Wed Feb 17 23:20:27.719478 2016] [authz_core:error] [pid 18301] [client x.x.x.x:47288] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
(only message since last apache restart)

#### ownCloud log (data/owncloud.log)
<empty>

**Comment by davivel** [comment]
In the case of Android, sure that browsing is working? If you add new files to a folder through the web UI, they appear in the list of files in the app?

This needs to be fixed. 

As a workaround: in the Android app go to ```Settings```, long press on the problematic account, select ```Modify password```. When the login view is shown, a dialog reporting about the new certificate should appear. Accept the certificate there and go back without changing the password.

**Comment by masensio** [comment]
It is duplicated by #1463, please track it there.
