### ISSUE TITLE
APK on Amazon Appstore is out of date

### ISSUE THREAD

**Issue by jknockaert** [owncloud/android#1481]
The Amazon App Store is still distributing version 1.8.0 of the ownCloud client app for Android. This has happened before: #423 and #561.

**Comment by rperezb** [comment]
@jknockaert  

We have been working with Amazon for several years without a problem. Recently they have made the app submission process increasingly difficult, the requirements for us to upload the app to the market has been changing over the time - this was the reason for the previous delays - and as a result we are no longer able to provide updates through Amazon. 

While we still provide updates in Google Play, we recognize this may not work out of the box for some Amazon devices. Therefore, we would like to point you to the ownCloud app available on f-droid.org for free for your continued use.

**Comment by jknockaert** [comment]
@rperezb Maybe the reference to the Amazon App Store should be removed here:
https://owncloud.com/download/

**Comment by rperezb** [comment]
@jknockaert yes, we will fix it, thx!

**Comment by rperezb** [comment]
fixed, thx
