### ISSUE TITLE
Feature request: multiple delete

### ISSUE THREAD

**Issue by raztud** [owncloud/android#1490]
### Expected behaviour
Would be very useful to be able to delete multiple files. 

### Actual behaviour
I have to press long on each file and delete one by one. If I want to delete 10 pictures it takes 30 clicks instead of 11 or 12.

### Steps to reproduce
1. Go to a folder with files
2. Try to delete multiple files

### Environment data
Android version: 5.1

**Comment by AndyScherzinger** [comment]
Hi @raztud thank you for suggesting this feature. It is already described in #899 and implemented in #1176 so I am closing this issue. Please track any progress there. :)
