### ISSUE TITLE
Doubled PROPFIND when pressing back in folder view

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#1491]
### Expected behaviour

I noticed that there are very many PROPFIND entries in my apache log. In particular there are two very similar entries when I browse up if the folder hierarchy.
### Actual behaviour

Only one PROPFIND per back press.
### Cause

On clicking back variable `ignoreETag` should be false:
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/activity/FileDisplayActivity.java#L1255

However, this value is "lost" here...

https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/fragment/ExtendedListFragment.java#L362

...because the `OnRefreshListener` does not allow parameters for `onRefresh()`.
### Environment data

ownCloud app version: 1.9.1 (master as of today)

**Comment by jesmrec** [comment]
Not reproducible any more. If back is pressed to a non-root, only one PROPFIND. If the back is pressed to root, there are two PROPFINDS with different properties, that is the expected behaviour. 

This is fixed, but feel free to reopen if is still reproducible on your side.

Closing!
