### ISSUE TITLE
Fix New Folder Alertdialog padding

### ISSUE THREAD

**Issue by sudhirkhanger** [owncloud/android#1495]
New Folder Alertdialog padding is not right. EditText expands to the both edges.

According to [Material Design guidelines][1], Alertdialog should have `24dp` padding on left and right sides and `20dp` between title and content.

**Here is how it currently looks.**
![4 march 2016 105454 pm ist](https://cloud.githubusercontent.com/assets/841656/13534840/1d1d2286-e25d-11e5-8d73-b550e8d55407.png)

**Here is the added padding according to Material Design guidelines.**
![4 march 2016 105522 pm ist](https://cloud.githubusercontent.com/assets/841656/13534850/2a1c0eac-e25d-11e5-86c7-b3e84bdd04e5.png)

[1]: https://www.google.com/design/spec/components/dialogs.html#dialogs-specs

**Comment by sudhirkhanger** [comment]
@jancborchardt @AndyScherzinger 

Another thing I noticed is that the keyboard is pulled with small letters. There are three following choices.

1. All words start with lowercase.
2. All words start with uppercase.
3. Only first word starts with uppercase.

ownCloud currently uses convention 1. Dolphin when creating a folder will create with a default name `New Folder` which is convention 2. ownCloud web uses convention 3 so `New folder`. I find convention 2 more appropriate and widely used.

Should I change to convention 2 or let it be?

PS:- Sorry for the mention. I am not sure who are the usability folks here.

**Comment by AndyScherzinger** [comment]
@jancborchardt is the design wizard of oC. :)

**Comment by jancborchardt** [comment]
@sudhirkhanger awesome on the eye for detail! :) You are very welcome in our IRC channel #owncloud-design!

As for the issues:

- Yes, totally agree on the padding issue on the input field. @AndyScherzinger or @sudhirkhanger you wanna take care of that?
- Regarding capitalization, we use »Only first word starts with uppercase«, and it should stay that way.

**Comment by AndyScherzinger** [comment]
Not sure @jancborchardt but I think @sudhirkhanger took care of it already, right?

**Comment by sudhirkhanger** [comment]
Yep the padding and first letter uppercase has already been submitted in the pull request.

https://github.com/owncloud/android/pull/1488

**Comment by malkomich** [comment]
@sudhirkhanger Please could you create another Pull Request with the changes you did to solve this issue about the padding.
After that, we'll have all your well received contributions merged in the repo :)

**Comment by sudhirkhanger** [comment]
@malkomich Thanks for taking care of the other pull request. I am thoroughly confused with git. I am reading [Atlassian git docs](https://www.atlassian.com/git/) and might do [Udacity's Github course](https://www.udacity.com/course/how-to-use-git-and-github--ud775) to make sense of it. Anything else you recommend to jump start my git learning?

**Comment by sudhirkhanger** [comment]
I am closing this one. I will send the PR for the padding fixes as soon as I can. Nothing to be done here.
