### ISSUE TITLE
Failed uploads can not be retried in another account

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1497]
### Steps to reproduce

1. Login with user1 and upload some files
2. Before the uploads have finished, switch the device connection off in order to send some of them to "Failed". Then, switch it again on.
3. Login with user2
4. Open uploads view and retry the failed uploads

### Current behaviour
The retries fail, due to a "folder error"

### Expected behaviour

The retries go on (not specified, open to discussion)

### Environment
Tested with Nexus5, v5.0.1

**Comment by davivel** [comment]
Solved now in #1493, ready to be tested, @jesmrec

**Comment by nasli** [comment]
:+1: Fixed!!
