### ISSUE TITLE
Failed uploads are not retried by the button

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1498]
### Expected behaviour
All the failed uploads go to Current queue

### Actual behaviour
Nothing happens

### Steps to reproduce
1. Upload some files
2. Before the uploads end, set the device in aeroplane mode (the uploads go to failed)
3. Disable the aeroplane mode to recover the connection
4. Tap on (...) on uploads view, and then tap in "retry" 

### Environment data
Android version: 5.0.1

Device model:  Nexus5 

ownCloud app version: 1.9.1

ownCloud server version: 9

**Comment by davivel** [comment]
This is now fixed in #1493, @jesmrec . After this fix, test cases about retry of uploads due to wrong password should be repeated.

**Comment by LukeOwncloud** [comment]
Looks good!

**Comment by nasli** [comment]
:+1: Works for me!
