### ISSUE TITLE
Deleting an account does not clear the current uploads

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1499]
### Steps to reproduce

1. Uploads some files
2. From server, delete the account before the uploads finish
3. Using another account in the app, open the uploads view

### Current behaviour

The uploads of the deleted user appears as failed, with UNKNOWN cause

### Exptected behaviour

The uploads of the deleted user are removed from uploads view

### Environment
Tested with: Nexus5 v5.0.1

**Comment by davivel** [comment]
As discussed offline, the current behaviour is the really expected behaviour, with the exception of the error cause, that needs to be "Credentials error". The client can't distinguish the deletion of the account in the server with from the modification of the password in the server.

**Comment by davivel** [comment]
Ready to test (regarding the error cause) in #1493.

**Comment by nasli** [comment]
Deleting the account from the server, set all pending uploads for this account to "Credential Error" except the current in progress that it is setting as "UNKNOWN"

**Comment by davivel** [comment]
Will check it

**Comment by davivel** [comment]
I debugged this, and there's no much we can do to improve it:
  - The upload interrupted with the deletion ends because the server responses with HTTP code 400 (unspecific client error) to the chunk in progress; from this error code we can't deduce nothing too specific, and definitely can't conclude that the user account was deleted.
 - The rest of the uploads fail with an HTTP code 401, as expected, since the user is not available anymore, so its credentials are not valid.
 - The message for unknown errors now is "Unknown error", that slightly improves "UNKNOWN" not shouting the user ;-) 

I think all this is reasonable for this case.

**Comment by davivel** [comment]
Of course, the app shouldn't just clear the failed uploads automatically, since the response received from the server is the same as changing the password from the web UI.

**Comment by nasli** [comment]
:+1: Ok works for me
