### ISSUE TITLE
Killing the app leaves uploads in an inconsistent state

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1500]
### Steps to reproduce

1. Upload some files
2. Kill the app
3. Open again the app and go to uploads view

### Current behaviour

The files are in "Current" list forever

### Expected behaviour

The files are uploaded and go to Uploaded list.

### Environment 

Tested with: Nexus5 v5.0.1

**Comment by davivel** [comment]
Now solved in #1493, ready to test @jesmrec

**Comment by LukeOwncloud** [comment]
Good: State is consistent now.

Bad: Uploads are listed in section `FAILED` with error `UNKNOWN`. They are thus not retried when oc app is launched again.

Bug? Or intended behavior?

**Comment by davivel** [comment]
For the moment automatic retries are only for instant uploads, when WiFi is recovered. We explicitly disabled that retry to limit the scope of this user story / pull request. So, that part is intended. 

The message "UNKNOWN" seems confusing, not just for you. so we'll change it.

Any proposal? "App was killed", "Unexpected interruption", "WTF" ?

**Comment by LukeOwncloud** [comment]
Lol! I like wtf! ;-) 
Bu

**Comment by LukeOwncloud** [comment]
But "app killed" is surely better!

**Comment by AndyScherzinger** [comment]
app was terminated

**Comment by davivel** [comment]
OK, let's update with one of those. Probably @AndyScherzinger's proposal is more formal.

**Comment by malkomich** [comment]
I have set just "Error uploading" as the error message because a more specific message would not be meaningful for a common user.
Also I have updated the failed section label in order to make clear the action for manually retry, while currently all failed uploads can be retried.

**Comment by LukeOwncloud** [comment]
I disagree. "App was terminated" is no technical speech and should thus be comprehensible by most users. Especially since apps are usually not killed without reason, rather the user (or an app which the user configured) killed it. On the other side "Error uploading" does not contain any additional information, if the upload is shown in the `FAILED` section.

**Comment by davivel** [comment]
OK. Let's add an specific value for app killed to UploadResult, and a message associated to it - "App was terminated".

Then, let's rollback the message for UNKOWN_ERROR result to "Unknown error".

Let's keep the additional (TAP TO RETRY) in the header and see what others think about it.

**Comment by nasli** [comment]
Ok, the new message shown: "App was terminated" :+1:
