### ISSUE TITLE
Wording issues in uploads view 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1501]
About the uploads view:

· "Retry current uploads" (in ... menu) should be replaced for  "Retry failed uploads"
· The three upload list are named:

 - Uploaded
 - Current
 - Failed Uploads

They should be more uniform like that:

 - Current Uploads
 - Failed Uploads
 - Finished Uploads (as they are named in "..." menu)

or

 - Current
 - Failed
 - Uploaded/Finished

Related to the lists, the padding in upload list is a little bit, so that all the uploads in the list are very close.

**Comment by davivel** [comment]
@jesmrec , I would go for the form "Current", "Failed", "Finished", **and** would replace the current title "ownCloud" with "Uploads".

**Comment by davivel** [comment]
Fixed now in #1493, @jesmrec

**Comment by LukeOwncloud** [comment]
Looks good!

**Comment by nasli** [comment]
:+1:

**Comment by davivel** [comment]
Thanks!
