### ISSUE TITLE
Manual retries are "delayed" 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1502]
### Expected behaviour
When a failed upload is tapped, is added to the "Current" queue to be upload.

### Actual behaviour
Until the current retried upload is ended, no files are added to "Current" queue.

### Steps to reproduce
1.- Set to upload some large files
2.- Before the uploads end, set the device in aeroplane mode (the uploads go to failed)
3.- Disable the aeroplane mode
4.- Tap on several files to retry the upload

### Environment data
Android version: 5.0.1

Device model: Nexus5

ownCloud app version: 1.9.1

ownCloud server version: 9

```

**Comment by davivel** [comment]
Fixed now in #1493.

cc @jesmrec

**Comment by LukeOwncloud** [comment]
Upload is added instantly to `CURRENT` section -> Good, issue solved.

However: It immediately says `Uploading...` (even though other upload is still in progress). Is this behavior wanted? I'd prefer something like `Waiting for upload...`

**Comment by nasli** [comment]
:+1: This issue fixed!!
I agree with @LukeOwncloud, "Uploading" should be using only for the one in progress, and the rest of pending uploads naming as "Waiting for upload", and that is how the iOS app works too.

**Comment by davivel** [comment]
OK, let's do that.

**Comment by nasli** [comment]
Sure! here https://github.com/owncloud/android/issues/1520
