### ISSUE TITLE
Uploads in SAML requests authentication twice

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1503]
### Expected behaviour
Session expires, and credentials are requested only once. The uploads go to "Failed" list with cause "Credentials error"

### Actual behaviour
Session expires, and credentials are requested twice. The uploads go to "Failed" list with cause "UNKNOWN"

### Steps to reproduce
1.- In a SAML server, select some files to upload without confirming them
2.- Wait a couple of minutes until the session expires
3.- Confirm to upload the files

### Environment data
Android version: 4.1.2

Device model: Samsung Galaxy S3

ownCloud app version: 1.9.1

ownCloud server version: 9RC1

**Comment by davivel** [comment]
@jesmrec , ready to test in #1493 now.

**Comment by nasli** [comment]
:+1: Fixed!

**Comment by davivel** [comment]
Thx
