### ISSUE TITLE
Beta 20160305 does not upload a file shared from anther app

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1506]
### Expected behaviour
Tell us what should happen
When I share a file from an app and send it to Owncloud beta, after selecting the folder and pressing upload, the file should be uploaded. 

### Actual behaviour
Tell us what happens instead
Nothing. At all. The upload doesn't even start. 
I'm able to upload files when I open owncloud beta app and press the + button and follow the steps.

### Steps to reproduce
1. Share a file from an app to Owncloud beta app
2. 
3. 

### Environment data
Android version:
6.0.1

Device model: 
Nexus 5

Stock or customized system:
Stock
ownCloud app version:
Beta 20160305

ownCloud server version:
OC 9.0 ( was happening with 8.2 as well)
#### Web server error log
Nothing at all

#### ownCloud log (data/owncloud.log)
```
Nothing at all
```

**Comment by sudhirkhanger** [comment]
Which app are you trying to upload from for an example? I just tried to share a picture with ownCloud app from Picktures app and it uploaded fine. I am running the latest `master`.

**Comment by elpraga** [comment]
That is strange. I tried it with QuickPic and with Xodo. Both work fine with 1.9.1 and none of them when 20160305.

Let me know what more information could I provide to find the cause.

**Comment by tobiasKaminsky** [comment]
I guess I have messed something up with the latest merge.
Till now there are 33 PR merged in the beta (some are now in master), so the chance is big that I can do a mistake ;)

**Comment by tobiasKaminsky** [comment]
There is now a new beta.
Please try it again :)

**Comment by elpraga** [comment]
No change in behavior. 20160313 still not working. The submit button gets pressed but nothing at all happens after the upload dialog disappears..

**Comment by tobiasKaminsky** [comment]
Please try to uninstall and reinstall it.
There seems to be a problem with an upgrade of the database.

**Comment by elpraga** [comment]
Ok.
That fixed it. It is wrong now.

Thanks!

**Comment by tobiasKaminsky** [comment]
@davivel Do you know if this is a general problem during upgrade (also for master)? Or is this a beta related problem?
