### ISSUE TITLE
Current upload should be in the top of uploads view

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1511]
### Steps to reproduce

1. Upload a huge amount of files

### Actual behaviour

The uploads are not set on the top on the current list, so that the user can not control what is being upload each moment

### Expected behaviour 

The current upload is set on the top on "Current" list

### Environment

Tested with Android Nexus5 v5.0.1

**Comment by davivel** [comment]
@jesmrec , @nasli , ready to test.

**Comment by LukeOwncloud** [comment]
Problem: When two failed uploads are retried immediately after another, second goes to top of list but other item is currently uploaded.

### Steps to reproduce:

1. Upload two large files
2. Kill oc.
3. Launch oc, go to `Uploads` (Files are listed as `FAILED`)
4. Tap ***second*** entry in `FAILED` section (Uploads starts)
5. Tap first (now: only) entry in `FAILED` section

**Comment by davivel** [comment]
Interesting case. I will review it.

Thanks for testing, @LukeOwncloud

**Comment by davivel** [comment]
Really fixed now in #1493.

**Comment by nasli** [comment]
:+1: Fixed!! Great work!
