### ISSUE TITLE
Clicking uploaded item in upload list has no effect

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#1512]
### Expected behaviour

Clicking an uploaded item should open the file.

Bug? Or missing feature?

**Comment by tobiasKaminsky** [comment]
Maybe also long-press: 
- open
- go to folder

**Comment by davivel** [comment]
This was removed out for 1.9.2 to limit the scope of the changes. May be added later.

**Comment by LukeOwncloud** [comment]
Okay. Add label "Junior Job"?

**Comment by jesmrec** [comment]
Duplicated. Let's keep the newer one: https://github.com/owncloud/android/issues/1876
