### ISSUE TITLE
Aborting current upload completely removes item from list

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1513]
### Expected behaviour
Item should be moved to `FAILED` section. 
Reason: Delete button can be pressed too easily by accident. There is no confirmation dialog. By still listing the item, users can easily correct their mistake.

Bug? Or just UI issue?

**Comment by LukeOwncloud** [comment]
Fixed. There is no deleted button any longer.

**Comment by davivel** [comment]
Happy you noticed it :)
