### ISSUE TITLE
Upload via "share with owncloud" from third party app does not work

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1514]
Open third party app (e.g. Gallery), open file/photo, choose "Share with" ... ownCloud. Nothing happens. 

Logcat:

    03-15 19:59:58.482 4911-4911/com.owncloud.android D/Uploader: Uploading file to dir /InstantUpload/
    03-15 19:59:58.652 4911-4911/com.owncloud.android D/Uploader: onPause() ending
    03-15 19:59:59.203 4911-4911/com.owncloud.android D/Uploader: onStop() ending
    03-15 19:59:59.213 4911-4911/com.owncloud.android D/Uploader: onDestroy() ending
    03-15 19:59:59.223 4911-4911/com.owncloud.android V/OperationsService: Destroying service

**Comment by LukeOwncloud** [comment]
Closing in favor of https://github.com/owncloud/android/issues/1529

**Comment by LukeOwncloud** [comment]
This issue is another matter after all. It is about sharing files from other apps to owncloud. Files should be uploaded, but they are not.

**Comment by LukeOwncloud** [comment]
@davivel @masensio @tobiasKaminsky 
How is upload supposed to work? And how can it work for anybody?

Please check here. Upload only takes place `if (data == null)`:
https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/activity/Uploader.java#L593

But in most of the above branches `data` is set. And whatismore, it seems that `data` is not used at all for the actual uploading process (only `uri` is passed).

:question: :question: :question:

**Comment by davivel** [comment]
Checking this.

**Comment by davivel** [comment]
OK, I changed this code recently in the branch for uploads view also. Try there if the functionality works better, please.

That block is really messy. The idea is that there are two paths to upload the file, one that copies it temporary in this block, and other that doesn't (though ```FileUploader```does later :S ) . This is probably the result of bad merges.

Let's just be sure that the function works well enough in #1493.

**Comment by LukeOwncloud** [comment]
No, unfortunately it doesn't. Same problem there: https://github.com/owncloud/android/blob/reliable_uploads_actions_uploads_view/src/com/owncloud/android/ui/activity/Uploader.java#L593

I think variable `data` can just be removed completely. Then it should work fine.

**Comment by davivel** [comment]
I applied a fast patch ignoring ```data``` (as @LukeOwncloud  suggested) in #1493. That should help, but I can't grant it's enough to fix all the problems detected for this feature  (receive files sent from other apps). We have reports of problems for certain apps in version 1.9.1, where there is an ```else``` path for the condition ```if (data == null)```, that is missed at this point. 

So, we need a well-thought code rewrite, and specific QA time for this feature, what is out the scope of #1493. 

But nevertheless, should be fixed for 1.9.2, or the feature could be really broken in the new release.

@LukeOwncloud , if you don't mind let's continue the tracking of this bug in #1529, where @jesmrec is considering more apps that will be important for the test cases.

**Comment by davivel** [comment]
With the current knowledge about #1529: the problems to send **files** (not text) to the OC app are better represented here; and this is being fixed for release 2.

cc @malkomich

**Comment by davivel** [comment]
Should be fixed in #1595

**Comment by davivel** [comment]
Ready to release now :)
