### ISSUE TITLE
Update via scroll down in Uploads view?

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1516]
In the Uploads view, on scroll down a refresh symbols appears for a glimpse. Is it intended? Does it have any effect?

**Comment by davivel** [comment]
With scroll down, do you mean like the pull 2 refresh in the list view? Data are loaded again from database.

**Comment by davivel** [comment]
@LukeOwncloud, I thought you explicitly enabled the gesture support in the original PR to reload from database. Am I wrong?

**Comment by LukeOwncloud** [comment]
Mmh. Did I? I don't remember. :-|
But shouldn't the view be up to date at all times anyway? Well, this options doesn't hurt. So just leave it?

**Comment by davivel** [comment]
> But shouldn't the view be up to date at all times anyway?

Yes, it should, but you know ... things happen. :)  IMHO it's fine there as a safe blanket. So let's move forward.
