### ISSUE TITLE
Naming just the current upload in progres with "Uploading" and the rest of uploads as "Waiting to upload"

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1520]
### Expected behaviour
Only the files in progress are setting as "Uploading" and the rest of files are naming as "Waiting to upload"

### Actual behaviour
All files in Current section are naming as "Uploading"

### Steps to reproduce
1. Upload some files

### Environment 
Nexus 10, v5

**Comment by davivel** [comment]
Fixed now in #1493.

**Comment by nasli** [comment]
:+1: Much cool now!!

**Comment by davivel** [comment]
Thx
