### ISSUE TITLE
Retry failed uploads button start uploads files by the bottom instead of the top

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1521]
### Expected behaviour
Current upload in progress is in the bottom

### Actual behaviour
Current upload is on the top. The list of current uploads are ordered in a contrary way that in the list of failed uploads.

### Steps to reproduce
1. Select to upload some files
2. Enabled aeroplane mode and disabled it
3. Select 'Retry failed uploads'

### Environment
Nexus 10, v5

**Comment by LukeOwncloud** [comment]
Related to https://github.com/owncloud/android/issues/1512

**Comment by davivel** [comment]
Really fixed now in #1493. Please, test again.

**Comment by nasli** [comment]
:+1: :+1: :+1:  :)
