### ISSUE TITLE
Credentials are requested on each failed uploads with credentials error

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1522]
### Expected behaviour
The file it is uploaded and not need to enter the credentials for each failed upload

### Actual behaviour
It is requested again enter the new credentials for each failed upload and the file it is not uploaded
(NOTE: Check reuse of cells,another step after a failed instant upload with waiting for wifi, if we tap on it, the file seems to start but if we tap on the progress it is requested credentials)

### Steps to reproduce
1.Upload some files
2. Change the credentials on server
3. Current uploads failed with credential error status
4. The app detect changes on credentials and request to enter new ones
5. Enter new credentials
6. Retry failed upload

### Environment 
Nexus 10, v5

**Comment by davivel** [comment]
Fixed now in #1493.

**Comment by nasli** [comment]
:+1: Great work!!

**Comment by davivel** [comment]
Yeah!
