### ISSUE TITLE
Uploaded files are possible to upload it again

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1523]
### Expected behaviour
Uploaded files are not sensitive to actions of retry upload

### Actual behaviour
The file it is uploaded but if you tap in the list of uploaded files, the file start uploading again

### Steps to reproduce
1. Upload two files to a folder and delete the folder from server before uploads end
2. The uploads remain with the status folder error
3. Create a folder with the same name
4. Retry the failed upload with "folder error" status

NOTE:  it seems that happens after any error and Failed sections appears
other steps:
1. Select to upload some files
2. Active aeroplane mode and desactive it
3. Tap to retry each failed upload
4. Wait all files are uploaded

### Environment 
Nexus 5, v5

**Comment by LukeOwncloud** [comment]
Related to https://github.com/owncloud/android/issues/1512

**Comment by malkomich** [comment]
Fixed in the PR  #1493, ready to test :)

**Comment by LukeOwncloud** [comment]
:+1:

**Comment by nasli** [comment]
:+1: Fixed!!
