### ISSUE TITLE
All pending uploads are setting as waiting for wifi connectivity after active "wifi only" for instant uploads of videos

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1525]
### Expected behaviour
Only the instant uploads are set as "Waiting for wifi connectivity"

### Actual behaviour
All failed uploads are set as "Waiting for wifi connectivity "
(NOTE: only the name is wrong, the action remains the previous failed error, ex: if tap on a file failed by credentials error request the credentials)

### Steps to reproduce
1. We have some failed uploads (ex: credentials error)
2. Set Instant uploads for images an video only with wifi
3. Take a video and an image
4. Go to uploads view

### Environment 
Nexus 5, v5

**Comment by davivel** [comment]
Fixed now in #1493.

**Comment by nasli** [comment]
:+1: Great work!!

**Comment by davivel** [comment]
Thx
