### ISSUE TITLE
Show account info while the file is uploading or waiting to upload 

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1526]
### Expected behaviour
Show the account info also in the uploading or waiting to upload files

### Actual behaviour
We can not distinguish where the files are uploading in Current section in Uploads View

### Steps to reproduce
1. Upload some files to account1
2. Upload some files to account2

### Environment
Nexus 10, v5

**Comment by davivel** [comment]
This is ready to test now in #1493.

**Comment by nasli** [comment]
I like the new info shown :+1:
