### ISSUE TITLE
Deleting photo during upload result in 'connection error' 

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1528]
It should rather say "file deleted locally" (note: this is also what the toast message says when clicking the failed upload item)

**Comment by davivel** [comment]
Will check it.

**Comment by davivel** [comment]
@LukeOwncloud , how do you reproduce it, deleting a picture that is uploading due to instant uploads?

**Comment by LukeOwncloud** [comment]
1. Enabled instant uploads and Internet connection. 
2. Take photo. Wait a few until photo is saved. 
3. Change to photo gallery and delete just taken photo (I use the swipe up gesture for deleting).

**Comment by davivel** [comment]
Thanks. Should be fixed now in #1493.

**Comment by jesmrec** [comment]
Fixed :+1:
