### ISSUE TITLE
Title of upload View show the name of the failed upload

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1530]
### Expected behaviour
Title remain as "Uploads"

### Actual behaviour
Title of the uploads view is the name of the failed file

### Steps to reproduce
1. Upload a file
2. Go to uploads view
3. Turn wifi off before the upload finished
4. Tap over notification of failed upload
5. Tap on the uploads view

### Environment 
Nexus 10, v5

**Comment by davivel** [comment]
This is fixed now in #1493

**Comment by nasli** [comment]
:+1:
