### ISSUE TITLE
Some Instant uploads images are naming as unknown error and are not retried

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1531]
### Expected behaviour
All photos are retried
File uploading is set as "Connection error" and when wifi came back it is uploaded
The rest of the photos waiting to upload are set as "Waiting wifi connectivity" and retried.

### Actual behaviour
File uploading is set as "Connection error" and when wifi came back it is uploaded
The rest of the photos waiting to upload are set as "Unknown error" and never retried.

### Steps to reproduce
1. Enabled instant uploads for images only with wifi
2. Wifi on
3. Take several photos
4. Turn Wifi Off

### Environment 
Nexux 10, v5

**Comment by davivel** [comment]
Fixed now in #1493

**Comment by nasli** [comment]
:+1: Fixed!!:)

**Comment by davivel** [comment]
Greeeat.
