### ISSUE TITLE
Uploads with status "Waiting wifi connectivity" are not retried

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1532]
### Expected behaviour
Failed uploads are setting as "Waiting wifi connectivity" but are not retried

### Actual behaviour
Failed uploads are setting as "Waiting wifi connectivity" but are not retried

### Steps to reproduce
1. Enabled instant uploads for video only with wifi
2. Wifi off
3. Take a video
4. Turn wifi on

### Environment 
Nexus 10, v5

**Comment by davivel** [comment]
Fixed now in #1493. Broken while fixing. Irony kills me!

**Comment by nasli** [comment]
:+1: Well done!!
