### ISSUE TITLE
Tap over "Clear all uploads" does not cancel all of the current uploads

### ISSUE THREAD

**Issue by nasli** [owncloud/android#1533]
### Expected behaviour
Uploads view is cleaned and the current uploads are all canceled

### Actual behaviour
Uploads view is cleaned but all the current uploads are not canceled

### Steps to reproduce
1. Select to upload some files
2. Tap on clear all uploads

### Environment 
Nexus 10, v5

**Comment by malkomich** [comment]
The clear options are not expected to cancel any uploads, just remove the historic of them.

Now the option logic has been changed for remove only failed and uploaded, refactoring the names of these options in the menu.

So this issue is ready to test right now ;)

**Comment by nasli** [comment]
Ok, now the current uploads remain on the view :+1:
