### ISSUE TITLE
Pause uploads

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1534]
As an enhancement/feature request it should be possible to pause the current upload in upload view  which stops the current and the queue. 
I do not know if this is possible or if the paused upload must be resumed, but pausing the upload queue is a very handy feature, I guess.

**Comment by LukeOwncloud** [comment]
I am sorry, I do not quite get it. Is it a feature request?

**Comment by tobiasKaminsky** [comment]
Yeah, I am sorry that this is not clear. 
I will change it :)

**Comment by pixolex** [comment]
One plus!

**Comment by jesmrec** [comment]
TUS feature
