### ISSUE TITLE
Current upload can't be cancelled in uploads view

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1535]
### Steps to reproduce 
1. Upload a big file (enough big for going to Uploads View before it finish)
2. Go to Uploads View and tap the cancel icon

### Expected behaviour
Upload is cancelled and moved to Failed section

### Current behaviour 
The upload keeps in Current section in an inconsistent state

### Environment
Tested in Samsung Galaxy S3 v4.1.2  <<<<<<  seems an important factor, not reproduced in other devices

**Comment by LukeOwncloud** [comment]
When I tried it was removed completely. https://github.com/owncloud/android/issues/1513

**Comment by LukeOwncloud** [comment]
I noticed the behavior. Nexus 4, Android 4.2.2
