### ISSUE TITLE
Upload: remember last position

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1538]
When uploading files from within the app the last chosen folder should be remembered.

**Comment by redwerk** [comment]
Hi, i am interesting in the implementation of this enhancement and could do the PR if no one develops this issue.

**Comment by AndyScherzinger** [comment]
@redwerk feel free, but first you should wait for some feedback from @rperezb @davivel @jancborchardt on the decision if this shall be implemented. If so than you will also have to sign the contributor agreement and send it to Frank, see https://owncloud.org/contribute/agreement for details. Else the PR can't be merged.

Hope that helps :)

**Comment by jancborchardt** [comment]
Yes, this is a great suggestion @tobiasKaminsky. It’s a pain to always navigate from the root folder. Same problem with the web interface actually where I recently opened an issue about this. ;)

**Comment by tobiasKaminsky** [comment]
Are there other situations where last folder should be remembered?
Then this could be done all at once...

**Comment by jancborchardt** [comment]
In the main app for sure yes – every time one starts the app, the last folder should be remembered.

**Comment by rperezb** [comment]
yes, there are other situations where the last folder should be remembered, for instance: https://github.com/owncloud/android/issues/1167

**Comment by jesmrec** [comment]
Native picker does this.
