### ISSUE TITLE
Progress bar not updated in uploads view when entering in uploads view (updated with next upload steps)

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#1541]
### Expected behaviour

When opening uploads view the progress of the current uploads should be shown immediately.
### Actual behaviour

Progress bar is at 0% (until next step occurs. Then progress bar is in sync again.)
### Steps to reproduce
1. Upload a file, switch to upload view.
2. Switch screen off and on again.
### Environment data

Android version: 4.2.2
Device model: Nexus 4

**Comment by davivel** [comment]
This is not immediate. We have no method right now to poll the current progress to the upload, just to be called back with progress updates.

**Comment by davivel** [comment]
After considering: the impact of this effect is not too uncomfortable, but the fix requires some work, and we need to put and end to #1493  ; let's keep it for further improvement of the uploads view after 1.9.2 is released. 

cc @rperezb

**Comment by michaelstingl** [comment]
Can no longer be reproduced. (probably fixed with https://github.com/owncloud/android/pull/1493) Also Android 4.2 is no longer supported.

In case this happens again, please open a new issue. (too many things changed)
