### ISSUE TITLE
Beta: using »download latest beta version« link in settings caused the app to crash

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1544]
At least for the version 20160124 I wanted to update from it didn’t work. Before I always used the direct download so this is the first time I experienced it.

cc @tobiasKaminsky @AndyScherzinger

**Comment by jancborchardt** [comment]
(Now the link was opened, but the app still crashed.)

**Comment by jancborchardt** [comment]
And the raw apk link does trigger a download, but no Android notification so it strangely enough is not obvious that it was downloaded.

**Comment by tobiasKaminsky** [comment]
Hmm. Crash is obviously not expected. If there is a new release the user should be pointed to the download url, which is downloaded by default with chrome and after opening the downloaded file it should be installed.
Do you have a log from the crash?

**Comment by jancborchardt** [comment]
Ah – I use Firefox. Maybe try with that one?

**Comment by tobiasKaminsky** [comment]
Does it happen with a recent version?
It should not matter if firefox or chrome is used as only an intent is sent to open an url with an app...

**Comment by jancborchardt** [comment]
The »latest« file says 20160427 but the latest one in the folder is 0416 – can you update?

**Comment by tobiasKaminsky** [comment]
Updated.
Someone set apk to .gitignore; which is fine for master, but obviously not for beta ;) ;)

**Comment by jancborchardt** [comment]
Ahh thanks! Will try now.

**Comment by jancborchardt** [comment]
And yep – works now! :)
