### ISSUE TITLE
Animation on changing section is confusing

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1545]
- Uploads view has a strange animation coming in from the bottom. That doesn’t make a lot of sense since it’s on the same level as »All files« and »On device«.
- Similar for Settings. The animation should be horizontal, if at all.

cc @tobiasKaminsky @AndyScherzinger @stoyicker @Kernald @LukeOwncloud @davivel :)

**Comment by tobiasKaminsky** [comment]
1+2: I think this is the default behaviour how new activities are shown. This can be changed with: http://www.mindfiresolutions.com/Animation-on-Switching-between-activities-1392.php, but should be a new issue as this is not beta related, or?
3 point will be working in next beta.
4 point: works for me: it shows only those files that are downloaded and all folders.

**Comment by davivel** [comment]
> should be a new issue as this is not beta related,
Yes.

**Comment by jancborchardt** [comment]
Ok, since 3 and 4 are solved, let’s just make this issue about the animation.

**Comment by tobiasKaminsky** [comment]
Next time opening a new issue would be better. Then other people can understand what we were talking about ;)

**Comment by tobiasKaminsky** [comment]
Is this still a bug or an enhancement?

**Comment by jesmrec** [comment]
Animations reworked. Not reproducible anymore.
