### ISSUE TITLE
Beta: security code header

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#1546]
The header of »Security code« says: »@2131165577« which seems like a strange bug. ;) cc @tobiasKaminsky @AndyScherzinger @davivel

**Comment by jancborchardt** [comment]
Also, the »More« header for the last section seems to be doubled, appearing twice.

**Comment by tobiasKaminsky** [comment]
Will be done in next beta.

**Comment by jancborchardt** [comment]
Thanks! :)
