### ISSUE TITLE
Autoupload - two or more accounts

### ISSUE THREAD

**Issue by Ninos** [owncloud/android#1547]
### Expected behaviour
I should be able to define for which owncloud account I want to activate automatic upload or configure automatic upload for both accounts seperately.

### Actual behaviour
Configuration for automatic upload will be used by all added owncloud accounts

### Steps to reproduce
1. Add two or more owncloud accounts
2. Activate automatic image and/or video upload
3. Create picture or video

### Environment data
Android version: 6.0

Device model: HTC One m8

Stock or customized system: CM13

ownCloud app version: 1.9.1

ownCloud server version: 9.0

**Comment by davivel** [comment]
Duplicating #827 . Please. track any progress on that issue. Thanks.
