### ISSUE TITLE
Same code style for AndroidStudio

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1548]
We should try to declare a code style which then should be enabled by default for every work on the app. With that there would not be commit blown up with code style changes again.

**Comment by tobiasKaminsky** [comment]
https://www.jetbrains.com/help/idea/2016.1/sharing-your-ide-settings.html?origin=old_help
-> Configuring a read-only source
might be a good way?

Or maybe it is just enough to declare that we use the default code style from android studio...

**Comment by sudhirkhanger** [comment]
I also want to know when working in Android Studio should I avoid `reformat code` command. (If we are talking about the same thing)

**Comment by AndyScherzinger** [comment]
At the moment I avoid reformatting the code to keep changes and thus potential merge conflicts at a minimum.

**Comment by tobiasKaminsky** [comment]
Right, currently we "just" do code changes, no code formatting.
If/when we decide to use one general code style, the best would be to apply this with one really big PR to all files and from that point every dev can apply the code styles automatically.

**Comment by MaximKulikov** [comment]
Hello. 
.editorconfig with lots of custom "ij_*" option force android studio use same code style for everyone.

**Comment by jesmrec** [comment]
Currently done
