### ISSUE TITLE
Upload the same file to different folder fails

### ISSUE THREAD

**Issue by malkomich** [owncloud/android#1549]
### Steps to reproduce 
1. Disable connection
2. Upload a file
3. Upload the same file again but in a different folder
4. Enable connection
5. Tap to retry in the last upload

### Expected behaviour 
The file uploads successfully

### Current behaviour 
The upload fail with "Unknown error"

### Environment
Tested in Samsung Galaxy S3 v4.1.2

**Comment by malkomich** [comment]
Fixed in PR #1493 :) 
Ready to test @jesmrec

**Comment by jesmrec** [comment]
:+1: Fixed
