### ISSUE TITLE
Continues Wifi-only upload when not on wifi

### ISSUE THREAD

**Issue by inducer** [owncloud/android#1550]
### Expected behaviour

The app is performing a long-running wifi-only upload (in my specific case, triggered by instant upload triggered by me being briefly near my home). I then leave wifi range within a few seconds of entering it. The app should suspend the ongoing upload (because I told it on its settings page that I only want it to upload on wifi).

### Actual behaviour

The app proceeded to drain my data allowance by continuing to upload on an (unfortunately very fast LTE-based) cell network.

### Steps to reproduce
1. Start wifi-only upload
2. Leave wifi range
3. Watch it drain your data allowance

### Environment data
Android version: 6.0.1r22

Device model: One plus One

Stock or customized system: Cyanogenmod nightly from Mar 21

ownCloud app version: 1.9.1 from FDroid

ownCloud server version: 8.2

**Comment by davivel** [comment]
hi, @inducer. This was recently fixed and will be released soon in 1.9.2. Was merged in #1191.

Thanks for your feedback
