### ISSUE TITLE
If the same file is uploaded twice, both uploads are removed from list

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1553]
### STEPS TO REPRODUCE

1.- Upload a large file (it is added to "Current view")
2.- Upload again the same file before the first upload finishes

### ACTUAL BEHAVIOUR

Both uploads do not appear in the uploads view. Only one of them is uploaded.

### EXPECTED BEHAVIOUR

Both uploads appears in the "Current" list. When both are finished, both files are stored in ownCloud, one of them renamed by adding "(2)" to the filename. Both files appear as "Uploaded" in uploads view.

Tested with Nexus9 v6 and Galaxy S3 v4

Server v9

App version 1.9.1

**Comment by malkomich** [comment]
Fixed :)

**Comment by jesmrec** [comment]
Fixed :+1:
