### ISSUE TITLE
Use toolbar instead of actionbar where applicable

### ISSUE THREAD

**Issue by AndyScherzinger** [owncloud/android#1556]
Like the title says use the toolbar - Google's new, to be used implementation of the top bar instead of the action bar which can be considered legacy. 

**Motivation**
The actionbar is simply a bar which can have a menu, search widget and in newer AppCompat versions also a drawer implementation but isn't as flexible as the toolbar.

**Reasons and benefits**
The toolbar can be customized on many ways like but not limited to:
  * adding any kind of views to it, like the progressbar which would be nice especially when 
    * we integrate the multi select branch (no dark blue line below the then grey bar)
    * no dark blue line below the bar when the drawer is opened
  * animate it, like scrolling it away on a list/recycler view which seems nice on the file browsing views
  * the material drawer can be full height, like mentioned in #1210 because this is only possible for the toolbar not the action bar (it can be done with hacks though)

I would like to work on this in case we agree this is worth implementing which I strongly suggest to make the bar future proof and also to be able to implement the above mentioned gimmicks.

So pinging @davivel @jancborchardt  @malkomich @tobiasKaminsky and @przybylski for feedback on this matter.

**Comment by davivel** [comment]
Great job here, and great presentation, @AndyScherzinger .

Just missed a section about "drawbacks" ;)

**Comment by davivel** [comment]
Merged, will be released with version 2.2.0

**Comment by AndyScherzinger** [comment]
:small_airplane:  **Awesome collab!**  :rocket:
