### ISSUE TITLE
Move file leaves 0-byte files behind

### ISSUE THREAD

**Issue by mcnesium** [owncloud/android#1558]
There is this option to either leave a picture at the original place or move it to the app folder. When set to move files to the app folder, the current v1.9.1 from F-Droid does not really move them but leave behind 0-byte files:

![screenshot](https://cloud.githubusercontent.com/assets/476060/13989651/a523c9ec-f111-11e5-8aac-f0d7874e4251.png)

This also happened to this very screenshot, that I had to upload manually, as it does not land in the default pictures  directory `/sdcard0/DCIM/Camera` but in `/sdcard0/Pictures/Screenshots`.

Samsung Galaxy Ace 2, Android 4.2.1

**Comment by LukeOwncloud** [comment]
Confirmed! This problem also occurs with PR https://github.com/owncloud/android/pull/1493.

### Steps to reproduce
0. Enable instant upload and set behavior to "move to app folder".
1. Take photo to invoke instant upload.

**Comment by tobiasKaminsky** [comment]
@LukeOwncloud what device do you have?
For now (2 reports) only Samsung devices are reported.
For me (Moto X Play) it is working.

**Comment by mcnesium** [comment]
It works fine as well on Sony Xperia V, CM12

**Comment by LukeOwncloud** [comment]
I have this issue on a Nexus 4 with Android version 4.2.2.
Could it be an android 4 issue?

**Comment by davivel** [comment]
Bug fix ready to test in release-2 branch.

**Comment by LukeOwncloud** [comment]
Confirmed: Fixed in branch `release-2`.

**Comment by jesmrec** [comment]
Fixed :+1:

closing...
