### ISSUE TITLE
Connect to ADFS 3.0 

### ISSUE THREAD

**Issue by cdamken** [owncloud/android#1560]
### Expected behaviour
Connect to ADFS 3.0 

### Actual behaviour
with ADFS 3.0 the user cannot connect at all, and more institutions move towards ADFS 3.0 so this issue is much higher priority

### Steps to reproduce
With an ADFS 3.0 institution of us states the android client isn't capable of "SNI (Server Name Indication)" -  a feature of SSL TLS and both Web Application Proxy and AD FS 2012 R2 use 
it to enable simpler deployment and remove networking prerequisites.

While the customer are trying to find a workaround, maybe engineering can have a look at your end if it is possible to cope with SNI.

### Environment data
Android version: 1.9.1

@MorrisJobke @rperezb 

[00005104](https://na25.salesforce.com/5003100000Z4xlh)

**Comment by cdamken** [comment]
login over the webUI and sync-client works without problems

**Comment by cdamken** [comment]
Added some screenshots:
S3\Shared\owncloud\support\github-issues\android\1560

**Comment by MorrisJobke** [comment]
ADFS is the shibboleth part in the windows environment? Then this is an issue in user_shibboleth or am I wrong? 



> Android version: 1.9.1

Interesting regarding SSL/TLS is the underlying Android version.

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/enterprise/issues/1181
