### ISSUE TITLE
Share link does not work properly

### ISSUE THREAD

**Issue by dva-re** [owncloud/android#1562]
### Expected behaviour

Shared link in clipboard
### Actual behaviour

Empty line in clipboard
### Steps to reproduce
1. Share file for user
2. Share file with public link
3. Relaunch owncloud app
4. Open share options, get share link for this file and past link in any textfield
### Environment data

Android version: 5.1.1

Device model: bacon

Stock or customized system: stock

ownCloud app version: 1.9.1

ownCloud server version: 9.0.0
### Additional info

Share link does not work properly when file already shared to any user on the server.
The problem is on 212 line of ShareActivity.java (v. 1.9.1)

`212 String link = ((OCShare) (result.getData().get(0))).getShareLink();`

In this case result data contains 2 shares. First - with type USER, and second - with type - PUBLIC_LINK, and in 0 index thats share does not contain sharelink, so link variable will be empty.

Little workaround, change this line to 

```
String link = "";
for(Object object :  result.getData()){
    OCShare shareLink = (OCShare) object;
    if(shareLink.getShareType().name().equalsIgnoreCase("PUBLIC_LINK")){
        link = shareLink.getShareLink();
        break;
    }
}
```

May be server must send public link share in first position, may be android client must check type for every shares, I don`t know. 
I'll wait for the official fix, as long as this solution works for me.

**Comment by malkomich** [comment]
I have just reproduced this issue, we'll have to fix it. Thanks for reporting it ;)

**Comment by dva-re** [comment]
OK, now this bug in /src/com/owncloud/android/ui/activity/ShareActivity.java
On Line 92
`String link = ((OCShare) (result.getData().get(0))).getShareLink();`

**Comment by sd1998** [comment]
@jesmrec This issue is no longer reproducible hence I think this should be closed.

**Comment by michaelstingl** [comment]
> I think this should be closed.

Thanks for checking 😍
