### ISSUE TITLE
[Android]: could not establish a connection

### ISSUE THREAD

**Issue by AndiB1234** [owncloud/android#1563]
Hi,

after a chrash I wiped my tablet. After that I installed ownloud app and tried to connect with my owncloud server. After I entered the server address I get an error: could not establish a connection.
(in German: Konnte keine Verbindung aufbauen)
The connect button is grey,I can't connect to the server. Before the crash everything works fine.
If I enter the url in a browser I get the login on my server and everything is fine. Sync client on my pc althoug works without problems.

I use a Galaxy Tab 2 10.1 with Cyanogen Mod 11, and current owncloud app (Ver 1.9.1).

Owncloud-Server ist 8.2.2 on BananaPi with Debian Wheezy an nginx. SSL enabled, SSL certificate from LetsEncrypt.
I connect to the server with an DynDns Domain name like https://myDynDns.com:40000

**Comment by LukeOwncloud** [comment]
There is currently no problem known with the connect dialog. Please try a different url. For example: https://Google . com (should result in message: Could not find owncloud installation). (There is also a public owncloud demo server. Can't find the url at the moment.) 

Do you use a firewall on your mobile device?

**Comment by KossaKo** [comment]
I ran into the very same problem (1.9.1 on Android 4.4.4 to Server with owncloud 8.2.3, Debian Jessie, apache and self-signed SSL certificate). The problem was that server and smartphone were in the same LAN. After changing from https://domain.tld/owncloud to https://servername/owncloud it works. If I use mobile data or am in another LAN I have of course to change back to the former. Strange enough that it works from the browser without any issues (on the mobile device as well as on all the other devices in the LAN) with the domain.tld address.

**Comment by AndiB1234** [comment]
You are right. If I change from DynDnsDomain to local IP I get a connect.
Cyanogem Mod 11 is Android 4.4.4

On my Smartphone with Android 5 I can also connect to DynDnsDomain when I'm in my local LAN.

**Comment by LukeOwncloud** [comment]
Sounds a lot like https://github.com/owncloud/android/issues/865, doesn't it? 
Does your router have ipv6 enabled? Can you try to disable it?

**Comment by AndiB1234** [comment]
Yes, ipv6 was enabled. Disabling ipv6 fixed the problem, I get a connect to my server. :-)
Thank you.

But what I don't understand, why does it work on my smartphone and with the desktop client with enabled ipv6?

**Comment by LukeOwncloud** [comment]
Great, that it worked for your. So we do have a ipv6 issue, which needs to be solved eventually. 

Don't know why smartphone and pc work. Maybe they don't support ipv6, so ipv4 is used even tough server could handle ipv6? Just a guess.

**Comment by AndiB1234** [comment]
Is there anything I can do to help?
Do you need log files, or should I test something?
