### ISSUE TITLE
Typo in the Android transifex XML

### ISSUE THREAD

**Issue by sveinki** [owncloud/android#1564]
String number 358:
"Settings, database and server certificates from %1$s's data will be deleted permanentlty. \n\nDownloaded files will be kept untouched.\n\nThis process can take some time."

permanentlty --> permanently

# Steps to reproduce
https://www.transifex.com/owncloud-org/owncloud/viewstrings/#is/android/74359823

There are some other; is this really the best place to announce typos?

**Comment by tobiasKaminsky** [comment]
For the english strings (values.xml) this is the right place as it is the source for transifex. 
All mistakes in other languages should be reported  on transifex.

**Comment by malkomich** [comment]
The string value has been already fixed for the new release 2.0.0, so we can close the issue ;)
