### ISSUE TITLE
StorageManager: Public share is not saved

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1565]
For #1561 I want to implement that a click on a shared link directly opens the "send link to ..." dialog. 
Therefore I need the link. This should be possible via the following function:
`OCShare publicShareLink = mStorageManager.getFirstShareByPathAndType(
                                        temp.getRemotePath(),
                                        ShareType.PUBLIC_LINK,
                                        ""
                                );`
This is in https://github.com/owncloud/android/blob/master/src/com/owncloud/android/datamodel/FileDataStorageManager.java#L1079.

But it is always empty. 

@davivel @masensio

**Comment by jesmrec** [comment]
New architecture makes this not posible.
