### ISSUE TITLE
Upload files: automatically create thumbnail

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1566]
When uploading an image the app should automatically generate a thumbnail.
This enhances the UX as the app has only to generate thumbnails for files on the server when entering a folder.

**Comment by elpraga** [comment]
That sounds nice! But it might also bake some small and underpowered servers (like mine) and make uploading several pictures to fail. 

In any case, I believe that I am a perfect test subject. I wouldn't mind if you tested it on my server yourself using the account I gave you, but please let me know before uploading a larger number of photos, just to make sure that the server doesn't become unresponsive when I need it for work..

What would happen if image is uploaded to a shared forlder? I suppose it would only triager thumbnail creation for the current user, right?

**Comment by tobiasKaminsky** [comment]
No, this is solely done on the client/android device.

**Comment by malkomich** [comment]
I guess this is already fixed in the recent uploads PR #1493, isn't it?

**Comment by tobiasKaminsky** [comment]
Seems you are right!
Great!
