### ISSUE TITLE
Can't open the file using android develpoer

### ISSUE THREAD

**Issue by nawarhashem** [owncloud/android#1571]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by LukeOwncloud** [comment]
Please clarify and re-open issue if necessary. Thanks! Closing for now...
