### ISSUE TITLE
When a lot of files is sent to uploads view, progress bar is not correctly managed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1573]
STEPS TO REPRODUCE

1.- Select to upload a huge amount of files (more than 30)

ACTUAL BEHAVIOUR

Sometimes, the progress bar of the bottom files is filled 

EXPECTED BEHAVIOUR

Only the progress bar of the top file is in progress. All the remaining are grey (pending)

Tested with Nexus5 v5, Nexus9 v6

**Comment by davivel** [comment]
@jesmrec , ready to test now in #1493

**Comment by davivel** [comment]
@jesmrec , try it now

**Comment by jesmrec** [comment]
:+1: Fixed
