### ISSUE TITLE
Feature request: Auto-refresh file/directory listing

### ISSUE THREAD

**Issue by ELTinos** [owncloud/android#1575]
At the moment I'm using owncloud android app 1.9.1 (via Stackstorage) but I'm missing out on a feature.

All folders I created and files I uploaded in the web/windows client are only visible when I manually refresh the directory (pull-down refresh) in app. For example, I create a directory structure like this in-browser:

Root
= Folder 1
== Folder 2
=== Folder 3

When I open my storage in the android app, I land up in root and there is no folder visible and the message "Nothing in here. Upload something!" is showing. I have to manually refresh the directory and then Folder 1 becomes visible. When I open Folder 1, it is empty again and I have to manually refresh to see Folder 2. The same for Folder 3.

A nice feature would be that the file/dir listing is automatically refreshed so I don't need to manually refresh the x.xxx folders I have in my storage. Not sure if it's a bug or a feature request, but I hope you guys can help out!

**Comment by tobiasKaminsky** [comment]
This should work: Every time you change a directory you should see horizontal moving bar beneath the blue header. This indicates that he current folder is being refreshed.

**Comment by tobiasKaminsky** [comment]
btw: please use the issue template to complete the questions related to the owncloud version and mobile phone type.

**Comment by ELTinos** [comment]
Thanks Tobias, that's what I expected too.

As of this morning it seems to work that way (they did work on the server last night), so maybe a server side setting? Solved anyway!

Ps. Next time I'll use the template
