### ISSUE TITLE
Upload path does not appear in "Uploaded"

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1576]
### STEPS TO REPRODUCE
Upload files

### ACTUAL BEHAVIOUR
Path does not appear in uploaded files

### EXPECTED BEHAVIOUR
Path appears

Tested with Nexus9 and Nexus5

**Comment by davivel** [comment]
Vertical spacing fixed, ready to test in #1493

**Comment by jesmrec** [comment]
Fixed :+1:
