### ISSUE TITLE
Crash after some actions with navigation drawer and FAB

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1578]
#### Steps to reproduce

1. With tablet in portrait, open the navigation drawer and tap on "Uploads" menu
2. Open again the navigation drawer and tap on "All files" menu
3. Tap on FAB, then on icon to create new folder
4. Rotate the tablet to landscape

#### Current behaviour

3. Dialog to name new folder appears, but ** software keyboard does not**
4. Device turns to a full black screen; if then click HOME,  app crashes

#### Expected behaviour

4. App is correctly redrawn, folder may be created after; if keyboard doesn't appear in 3., but appears with an extra tap on the name field, solution is acceptable.

#### Environment

TABLET (seems a key factor), Nexus 10, v5.0.2

#### Logs

3-18 10:33:00.103 22208-22208/com.owncloud.android I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
03-18 10:33:00.143 22208-22239/com.owncloud.android D/mali_winsys: new_window_surface returns 0x3000
03-18 10:33:00.364 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:33:05.559 22208-22208/com.owncloud.android D/FileUtils: fileName =======b
03-18 10:33:05.573 22208-22208/com.owncloud.android D/OperationsService: Starting command with id 2
03-18 10:33:05.584 22208-30329/com.owncloud.android D/SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
03-18 10:33:05.586 22208-30329/com.owncloud.android D/OwnCloudClient #46: Creating OwnCloudClient
03-18 10:33:05.588 22208-30329/com.owncloud.android V/SimpleFactoryManager:     new client {noe@[EDITED], 591943007}
03-18 10:33:05.608 22208-30329/com.owncloud.android D/FileUtils: path ....... /b/
03-18 10:33:05.621 22208-30329/com.owncloud.android D/OwnCloudClient #46: REQUEST MKCOL /remote.php/webdav/b/
03-18 10:33:05.637 22208-30329/com.owncloud.android D/AdvancedSslSocketFactory: Creating SSL Socket with remote [EDITED], local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@8791768
03-18 10:33:05.648 22208-30329/com.owncloud.android D/AdvancedSslSocketFactory:  ... with connection timeout 5000 and socket timeout 30000
03-18 10:33:05.655 22208-30329/com.owncloud.android I/ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
03-18 10:33:05.663 22208-30329/com.owncloud.android I/ServerNameIndicator: SNI done, hostname: [EDITED]
03-18 10:33:05.673 22208-22239/com.owncloud.android D/mali_winsys: new_window_surface returns 0x3000
03-18 10:33:05.776 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:33:06.140 22208-30329/com.owncloud.android D/CreateRemoteFolderOperation: Create directory /b/: Operation finished with HTTP status code 201 (success)
03-18 10:33:06.171 22208-30329/com.owncloud.android D/CreateFolderOperation: Create directory /b/ in Database
03-18 10:33:06.173 22208-30329/com.owncloud.android D/OperationsService: Called 1 listeners
03-18 10:33:06.177 22208-30329/com.owncloud.android D/OperationsService: Stopping after command with id 2
03-18 10:33:06.182 22208-22208/com.owncloud.android D/FileActivity: Received result of operation in FileActivity - common behaviour for all the FileActivities 
03-18 10:33:06.235 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:33:10.462 22208-22208/com.owncloud.android V/FileDisplayActivity: onPause() start
03-18 10:33:10.467 22208-22208/com.owncloud.android D/FileDisplayActivity: onPause() ending
03-18 10:33:10.471 22208-22208/com.owncloud.android V/FileDisplayActivity: onPause() end
03-18 10:33:10.507 22208-22208/com.owncloud.android D/UploadListActivity: onCreate(Bundle) starting
03-18 10:33:10.539 22208-22208/com.owncloud.android W/ActionBarDrawerToggle: DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
03-18 10:33:10.541 22208-22208/com.owncloud.android D/UploadListActivity: onStart() starting
03-18 10:33:10.545 22208-22208/com.owncloud.android E/ExpandableListFragment: onCreateView
03-18 10:33:10.558 22208-22208/com.owncloud.android D/UploadListFragment: onActivityCreated() start
03-18 10:33:10.560 22208-22208/com.owncloud.android D/UploadListFragment: onStart() start
03-18 10:33:10.564 22208-22208/com.owncloud.android D/ExpandableUploadListAdapter: ExpandableUploadListAdapter
03-18 10:33:10.566 22208-22208/com.owncloud.android D/ExpandableUploadListAdapter: loadUploadItemsFromDb
03-18 10:33:10.574 22208-22208/com.owncloud.android D/ExpandableUploadListAdapter: registerDataSetObserver
03-18 10:33:10.583 22208-22208/com.owncloud.android V/UploadListActivity: onResume() start
03-18 10:33:10.586 22208-22208/com.owncloud.android D/UploadListActivity: onResume() starting
03-18 10:33:10.590 22208-22208/com.owncloud.android V/UploadListActivity: onResume() end
03-18 10:33:10.637 22208-22239/com.owncloud.android D/mali_winsys: new_window_surface returns 0x3000
03-18 10:33:10.672 22208-22208/com.owncloud.android D/FileActivity: Operations service connected
03-18 10:33:10.674 22208-22208/com.owncloud.android D/UploadListActivity: UploadListActivity not connected to Upload service. component: ComponentInfo{com.owncloud.android/com.owncloud.android.files.services.FileDownloader} service: com.owncloud.android.files.services.FileDownloader$FileDownloaderBinder@1540f59e
03-18 10:33:10.678 22208-22208/com.owncloud.android D/UploadListActivity: UploadListActivity connected to Upload service. component: ComponentInfo{com.owncloud.android/com.owncloud.android.files.services.FileUploader} service: com.owncloud.android.files.services.FileUploader$FileUploaderBinder@2db2e87f
03-18 10:33:10.683 22208-22208/com.owncloud.android D/ExpandableUploadListAdapter: refreshView
03-18 10:33:10.686 22208-22208/com.owncloud.android D/ExpandableUploadListAdapter: loadUploadItemsFromDb
03-18 10:33:10.701 22208-22208/com.owncloud.android D/ExpandableUploadListAdapter: refreshView
03-18 10:33:10.704 22208-22208/com.owncloud.android D/ExpandableUploadListAdapter: loadUploadItemsFromDb
03-18 10:33:10.789 22208-22239/com.owncloud.android D/OpenGLRenderer: endAllStagingAnimators on 0xb7b15d08 (ListView) with handle 0xb7d879b8
03-18 10:33:11.113 22208-22208/com.owncloud.android V/FileDisplayActivity: onSaveInstanceState() start
03-18 10:33:11.116 22208-22208/com.owncloud.android D/FileDisplayActivity: onSaveInstanceState(Bundle) starting
03-18 10:33:11.118 22208-22208/com.owncloud.android D/ExtendedListFragment: onSaveInstanceState()
03-18 10:33:11.123 22208-22208/com.owncloud.android V/FileDisplayActivity: onSaveInstanceState() end
03-18 10:33:11.125 22208-22208/com.owncloud.android V/FileDisplayActivity: onStop() start
03-18 10:33:11.127 22208-22208/com.owncloud.android D/FileDisplayActivity: onStop() ending
03-18 10:33:11.130 22208-22208/com.owncloud.android V/FileDisplayActivity: onStop() end
03-18 10:33:13.028 22208-22208/com.owncloud.android V/UploadListActivity: onPause() start
03-18 10:33:13.033 22208-22208/com.owncloud.android D/UploadListActivity: onPause() ending
03-18 10:33:13.037 22208-22208/com.owncloud.android V/UploadListActivity: onPause() end
03-18 10:33:13.049 22208-22208/com.owncloud.android V/FileDisplayActivity: onDestroy() start
03-18 10:33:13.054 22208-22208/com.owncloud.android D/FileDisplayActivity: onDestroy() ending
03-18 10:33:13.063 22208-22208/com.owncloud.android V/FileDisplayActivity: onDestroy() end
03-18 10:33:13.082 22208-22208/com.owncloud.android V/FileDisplayActivity: onCreate() start
03-18 10:33:13.093 22208-22208/com.owncloud.android D/FileDisplayActivity: onCreate(Bundle) starting
03-18 10:33:13.099 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.100 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.101 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.113 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.115 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.117 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.121 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.122 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.124 22208-22219/com.owncloud.android W/CursorWrapperInner: Cursor finalized without prior close()
03-18 10:33:13.163 22208-22208/com.owncloud.android W/ActionBarDrawerToggle: DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
03-18 10:33:13.163 22208-22208/com.owncloud.android V/FileDisplayActivity: onCreate() end
03-18 10:33:13.166 22208-22208/com.owncloud.android V/FileDisplayActivity: onStart() start
03-18 10:33:13.168 22208-22208/com.owncloud.android D/FileDisplayActivity: onStart() starting
03-18 10:33:13.180 22208-22208/com.owncloud.android D/FileDisplayActivity: Initializing Fragments in onAccountChanged..
03-18 10:33:13.182 22208-22208/com.owncloud.android A/FileDisplayActivity: Access to unexisting list of files fragment!!
03-18 10:33:13.186 22208-22208/com.owncloud.android E/FileDisplayActivity: Still have a chance to lose the initializacion of list fragment >(
03-18 10:33:13.190 22208-22208/com.owncloud.android V/FileDisplayActivity: onStart() end
03-18 10:33:13.195 22208-22208/com.owncloud.android A/FileDisplayActivity: Access to unexisting list of files fragment!!
03-18 10:33:13.200 22208-22208/com.owncloud.android E/FileDisplayActivity: OCFileListFragment is null
03-18 10:33:13.208 22208-22208/com.owncloud.android V/FileDisplayActivity: onResume() start
03-18 10:33:13.210 22208-22208/com.owncloud.android D/FileDisplayActivity: onResume() starting
03-18 10:33:13.213 22208-22208/com.owncloud.android E/OCFileListFragment: onAttach
03-18 10:33:13.215 22208-22208/com.owncloud.android I/OCFileListFragment: onCreateView() start
03-18 10:33:13.217 22208-22208/com.owncloud.android D/ExtendedListFragment: onCreateView
03-18 10:33:13.242 22208-22208/com.owncloud.android I/OCFileListFragment: onCreateView() end
03-18 10:33:13.244 22208-22208/com.owncloud.android E/OCFileListFragment: onActivityCreated() start
03-18 10:33:13.268 22208-22208/com.owncloud.android V/FileDisplayActivity: onResume() end
03-18 10:33:13.306 22208-22239/com.owncloud.android D/mali_winsys: new_window_surface returns 0x3000
03-18 10:33:13.381 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:33:13.394 22208-22208/com.owncloud.android D/FileActivity: Operations service connected
03-18 10:33:13.397 22208-22208/com.owncloud.android D/FileDisplayActivity: Download service connected
03-18 10:33:13.407 22208-22208/com.owncloud.android D/FileDisplayActivity: Upload service connected
03-18 10:33:13.416 22208-22208/com.owncloud.android D/FileObserverService: Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.owncloud.android/.services.observer.FileObserverService }
03-18 10:33:13.417 22208-22208/com.owncloud.android D/FileObserverService: Loading all kept-in-sync files from database to start watching them
03-18 10:33:13.450 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:33:13.507 22208-31259/com.owncloud.android D/SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
03-18 10:33:13.510 22208-31259/com.owncloud.android D/OwnCloudClient #47: Creating OwnCloudClient
03-18 10:33:13.513 22208-31259/com.owncloud.android V/SimpleFactoryManager:     new client {noe@[EDITED], 657809830}
03-18 10:33:13.519 22208-31259/com.owncloud.android D/OwnCloudClient #47: REQUEST GET /status.php
03-18 10:33:13.531 22208-31259/com.owncloud.android D/AdvancedSslSocketFactory: Creating SSL Socket with remote [EDITED], local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@8791768
03-18 10:33:13.536 22208-31259/com.owncloud.android D/AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
03-18 10:33:13.542 22208-31259/com.owncloud.android I/ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
03-18 10:33:13.545 22208-31259/com.owncloud.android I/ServerNameIndicator: SNI done, hostname: [EDITED]
03-18 10:33:13.712 22208-31259/com.owncloud.android D/UpdateOCVersionOperation: Got new OC version 9.0.0.19
03-18 10:33:13.715 22208-31259/com.owncloud.android I/UpdateOCVersionOperation: Check for update of ownCloud server version at [EDITED]/remote.php/webdav: Operation finished with HTTP status code -1 (success)
03-18 10:33:13.719 22208-31259/com.owncloud.android D/SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
03-18 10:33:13.725 22208-31259/com.owncloud.android D/OwnCloudClient #48: Creating OwnCloudClient
03-18 10:33:13.729 22208-31259/com.owncloud.android V/SimpleFactoryManager:     new client {noe@[EDITED], 478871444}
03-18 10:33:13.734 22208-31259/com.owncloud.android D/OwnCloudClient #48: REQUEST GET /ocs/v1.php/cloud/capabilities
03-18 10:33:13.773 22208-22208/com.owncloud.android D/UploadListActivity: onStop() ending
03-18 10:33:13.778 22208-22208/com.owncloud.android D/UploadListActivity: onDestroy() ending
03-18 10:33:14.022 22208-31259/com.owncloud.android D/GetRemoteCapabilitiesOperation: Successful response: {"ocs":{"meta":{"status":"ok","statuscode":100,"message":null},"data":{"version":{"major":9,"minor":0,"micro":0,"string":"9.0.0","edition":""},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php\/webdav"},"files_sharing":{"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false},"expire_date":{"enabled":false},"send_mail":false,"upload":true},"user":{"send_mail":false},"resharing":true,"federation":{"outgoing":true,"incoming":true}},"files":{"bigfilechunking":true,"undelete":true,"versioning":true},"notifications":{"ocs-endpoints":["list","get","delete"]}}}}}
03-18 10:33:14.025 22208-31259/com.owncloud.android D/GetRemoteCapabilitiesOperation: *** Added version
03-18 10:33:14.029 22208-31259/com.owncloud.android D/GetRemoteCapabilitiesOperation: *** Added core
03-18 10:33:14.032 22208-31259/com.owncloud.android D/GetRemoteCapabilitiesOperation: *** Added files_sharing
03-18 10:33:14.034 22208-31259/com.owncloud.android D/GetRemoteCapabilitiesOperation: *** Added files
03-18 10:33:14.036 22208-31259/com.owncloud.android D/GetRemoteCapabilitiesOperation: *** Get Capabilities completed 
03-18 10:33:14.054 22208-31259/com.owncloud.android D/RefreshFolderOperation: Checking changes in noe@[EDITED]/
03-18 10:33:14.058 22208-31259/com.owncloud.android D/OwnCloudClient #47: REQUEST PROPFIND /remote.php/webdav/
03-18 10:33:14.305 22208-31259/com.owncloud.android I/RefreshFolderOperation: Checked noe@[EDITED]/ : changed
03-18 10:33:14.313 22208-31259/com.owncloud.android D/OwnCloudClient #47: REQUEST PROPFIND /remote.php/webdav/
03-18 10:33:14.584 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_USED_BYTES 101633503
03-18 10:33:14.587 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_AVAILABLE_BYTES -3
03-18 10:33:14.594 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_USED_BYTES 6139342
03-18 10:33:14.597 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_AVAILABLE_BYTES -3
03-18 10:33:14.602 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_USED_BYTES 678556
03-18 10:33:14.605 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_AVAILABLE_BYTES -3
03-18 10:33:14.613 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_USED_BYTES 43995517
03-18 10:33:14.616 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_AVAILABLE_BYTES -3
03-18 10:33:14.621 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_USED_BYTES 47587849
03-18 10:33:14.629 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_AVAILABLE_BYTES -3
03-18 10:33:14.635 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_USED_BYTES 0
03-18 10:33:14.638 22208-31259/com.owncloud.android D/WebdavEntry: QUOTA_AVAILABLE_BYTES -3
03-18 10:33:14.646 22208-31259/com.owncloud.android I/ReadRemoteFolderOperation: Synchronized /: Operation finished with HTTP status code 207 (success)
03-18 10:33:14.654 22208-31259/com.owncloud.android D/RefreshFolderOperation: Synchronizing noe@[EDITED]
03-18 10:33:14.672 22208-31259/com.owncloud.android D/RefreshFolderOperation: Remote folder / changed - starting update of local data 
03-18 10:33:14.697 22208-31259/com.owncloud.android D/FileDataStorageManager: Saving folder / with 6 children and 0 files to remove
03-18 10:33:14.752 22208-31259/com.owncloud.android D/FileDataStorageManager: Sending 7 operations to FileContentProvider
03-18 10:33:14.762 22208-31259/com.owncloud.android D/FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@1d2504c2 (temporary: false)
03-18 10:33:14.798 22208-31259/com.owncloud.android D/FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@1d2504c2
03-18 10:33:14.800 22208-31259/com.owncloud.android D/RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
03-18 10:33:14.813 22208-22208/com.owncloud.android D/FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
03-18 10:33:14.814 22208-31259/com.owncloud.android D/OwnCloudClient #47: REQUEST GET /ocs/v1.php/apps/files_sharing/api/v1/shares
03-18 10:33:14.837 22208-22208/com.owncloud.android D/FileDisplayActivity: Setting progress visibility to true
03-18 10:33:14.852 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:33:15.109 22208-31259/com.owncloud.android D/GetRemoteSharesForFileOperation: Got 0 shares
03-18 10:33:15.135 22208-31259/com.owncloud.android D/FileDataStorageManager: Sending 6 operations to FileContentProvider
03-18 10:33:15.140 22208-31259/com.owncloud.android D/FileContentProvider: applying batch in provider com.owncloud.android.providers.FileContentProvider@1d2504c2 (temporary: false)
03-18 10:33:15.156 22208-31259/com.owncloud.android D/FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@1d2504c2
03-18 10:33:15.163 22208-31259/com.owncloud.android D/RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
03-18 10:33:15.172 22208-22208/com.owncloud.android D/FileDisplayActivity: Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
03-18 10:33:15.202 22208-22208/com.owncloud.android D/FileDisplayActivity: Setting progress visibility to false
03-18 10:33:15.221 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:33:15.930 22208-22208/com.owncloud.android I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
03-18 10:33:15.967 22208-22239/com.owncloud.android D/mali_winsys: new_window_surface returns 0x3000
03-18 10:34:47.042 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:34:47.083 22208-22208/com.owncloud.android V/FileDisplayActivity: onSaveInstanceState() start
03-18 10:34:47.088 22208-22208/com.owncloud.android D/FileDisplayActivity: onSaveInstanceState(Bundle) starting
03-18 10:34:47.096 22208-22208/com.owncloud.android D/ExtendedListFragment: onSaveInstanceState()
03-18 10:34:47.099 22208-22208/com.owncloud.android V/FileDisplayActivity: onSaveInstanceState() end
03-18 10:34:47.103 22208-22208/com.owncloud.android V/FileDisplayActivity: onStop() start
03-18 10:34:47.107 22208-22208/com.owncloud.android D/FileDisplayActivity: onStop() ending
03-18 10:34:47.111 22208-22208/com.owncloud.android V/FileDisplayActivity: onStop() end
03-18 10:35:11.031 22208-22217/com.owncloud.android I/art: Debugger is no longer active
03-18 10:35:18.265 22208-22208/com.owncloud.android E/ActivityThread: Performing pause of activity that is not resumed: {com.owncloud.android/com.owncloud.android.ui.activity.FileDisplayActivity}
                                                                      java.lang.RuntimeException: Performing pause of activity that is not resumed: {com.owncloud.android/com.owncloud.android.ui.activity.FileDisplayActivity}
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3196)
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3184)
                                                                          at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3159)
                                                                          at android.app.ActivityThread.access$1000(ActivityThread.java:144)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
03-18 10:35:18.269 22208-22208/com.owncloud.android V/FileDisplayActivity: onPause() start
03-18 10:35:18.290 22208-22208/com.owncloud.android D/FileDisplayActivity: onPause() ending
03-18 10:35:18.297 22208-22208/com.owncloud.android V/FileDisplayActivity: onPause() end
03-18 10:35:18.312 22208-22208/com.owncloud.android W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
03-18 10:35:18.600 22208-22208/com.owncloud.android E/ActivityThread: Performing stop of activity that is not resumed: {com.owncloud.android/com.owncloud.android.ui.activity.FileDisplayActivity}
                                                                      java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.owncloud.android/com.owncloud.android.ui.activity.FileDisplayActivity}
                                                                          at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3309)
                                                                          at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3390)
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:144)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
03-18 10:35:19.368 22208-22239/com.owncloud.android D/mali_winsys: new_window_surface returns 0x3000
03-18 10:35:19.373 22208-22208/com.owncloud.android V/FileActivity: onRestart() start
03-18 10:35:19.379 22208-22208/com.owncloud.android V/FileActivity: onRestart() end
03-18 10:35:19.382 22208-22208/com.owncloud.android V/FileDisplayActivity: onStart() start
03-18 10:35:19.384 22208-22208/com.owncloud.android D/FileDisplayActivity: onStart() starting
03-18 10:35:19.397 22208-22208/com.owncloud.android D/FileDisplayActivity: Initializing Fragments in onAccountChanged..
03-18 10:35:19.412 22208-22208/com.owncloud.android V/FileDisplayActivity: onStart() end
03-18 10:35:19.416 22208-22208/com.owncloud.android V/FileDisplayActivity: onResume() start
03-18 10:35:19.419 22208-22208/com.owncloud.android D/FileDisplayActivity: onResume() starting
03-18 10:35:19.451 22208-22208/com.owncloud.android V/FileDisplayActivity: onResume() end
03-18 10:35:19.531 22208-22239/com.owncloud.android D/mali_winsys: new_window_surface returns 0x3000
03-18 10:35:19.561 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:35:19.872 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446
03-18 10:35:21.724 22208-22208/com.owncloud.android W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
03-18 10:35:21.727 22208-22208/com.owncloud.android W/ViewRootImpl: Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=489.45544, y[0]=717.9768, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=5139877, downTime=5139870, deviceId=1, source=0x1002 }
03-18 10:35:21.728 22208-22208/com.owncloud.android W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
03-18 10:35:21.823 22208-22208/com.owncloud.android D/cache_test_DISK_: image read from disk 770089446

**Comment by davivel** [comment]
@jesmrec , ready to test now in release-2

**Comment by jesmrec** [comment]
@davivel fixed 👍
