### ISSUE TITLE
App crashes when a link is copied (Av4.3)

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1579]
#### Steps to reproduce

1.- Share a folder by link, enabling the "allow editing" switch
2.- Tap on "Get Link" and select "Copy Link"

#### Current behaviour

App crashes

#### Expected behaviour

Link is copied and can be pasted in a browser to get the content

#### Environment

Tested with Nexus7 Android v4.3. 

Server version:
{"installed":true,"maintenance":false,"version":"9.0.0.15","versionstring":"9.0.0 beta 2","edition":""}

**Comment by davivel** [comment]
Fixed now in release-2 branch, ready to test @jesmrec

**Comment by jesmrec** [comment]
Fixed :+1:
