### ISSUE TITLE
Minor improvements in FAB

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1581]
Right now, the three buttons in FAB are (in order):
- [a] Upload (files)
- [b] New Folder
- [c] Content from other apps (Upload) 

[a] and [c] should appear together, since both are "upload" buttons. Let's say both together on the top, then [b] right over the FAB.

@jancborchardt , @AndyScherzinger , is it OK for you?

**Comment by jancborchardt** [comment]
Sounds good, yes!

**Comment by davivel** [comment]
No, sorry. I just want to change the order in vertical:
[a]
[c]
[b]
[FAB]

**Comment by jancborchardt** [comment]
@AndyScherzinger it’s just about switching the order of »New folder« and »Upload from other apps« in the expanded FAB. :)

**Comment by AndyScherzinger** [comment]
Ahhhh, :smile: now I get it :+1: 

This is a 10 seconds change :grin: :+1:

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger waiting for it, nearly an hour ;) ;) :tada: :laughing:

**Comment by AndyScherzinger** [comment]
Well, I didn't work on this, but can if @davivel hasn't already...

**Comment by AndyScherzinger** [comment]
DONE: #1583

**Comment by AndyScherzinger** [comment]
works on my phone as described by @davivel 

pinging @malkomich and @jesmrec

**Comment by jesmrec** [comment]
@AndyScherzinger 

it will be checked within the new version. Thanks!!!

**Comment by davivel** [comment]
Tested -> DONE
