### ISSUE TITLE
Beta 20160321 Thumbnails of photos sometimes disappear and have to be re-downloaded from the server

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1586]
### Expected behaviour

Once the thumbnails are generated they should not disappear.
### Actual behaviour

Sometimes they disappear and have to be re-downloaded.
### Steps to reproduce

So far I am unable to reproduce it consistently, I will keep trying. My cache is set to 100Mb (but that should be 100MB according to what @tobiasKaminsky said), and I have not cleared app cache manually. When using the system to view app data usage, it shows 1,3 MB used by apps data 1.6MB in cache. Nevertheless when I try to administer space (I have my phone set to spanish, I am not sure about the correct English translation), the settings app crashes every time. I am able to enter those settings without any problems in other apps. Maybe it might be related?
I enter those setiings via:  Settings-Free space and USB - Applications - ownCloud beta - Manage space - Settings app crashes every time 
### Environment data

Android version:
6.0
Device model: 

Stock or customized system:
stock
ownCloud app version:
Beta 20160321
ownCloud server version:
9.0
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Follow up: https://github.com/owncloud/android/issues/3525
