### ISSUE TITLE
Enhancement: Search option 

### ISSUE THREAD

**Issue by eifeoh** [owncloud/android#1589]
### Expected behaviour
It would be great to have the ability to search from within the app. This could be either folderwise (in the long press menu) or at the top right corner of the app - that's were I expected it to be.

### Possible Implementation
Search function could just call the serverside search function and display its results. 

### Environment data
Android version: Any

Device model: Any

ownCloud app version: 1.9.1

ownCloud server version: 9.0

**Comment by tobiasKaminsky** [comment]
There are already some discussions about that: #695 #896
