### ISSUE TITLE
App crashes when opening certain folder

### ISSUE THREAD

**Issue by deechte** [owncloud/android#1590]
### Expected behaviour

The app should show the contents of the folder. This doesn´t happen on all folders, but on the majority of them. Some folders have files in them, some only subfolders.
### Actual behaviour

Android says: "ownCloud has stopped" and gives me the choice between Report and OK. I haven't sent a report yet, not knowing if you monitor what comes in through Google's channel. Please advise if I should.
### Steps to reproduce
1. Open the app
2. Browse through the folder structure to the specific folder
### Environment data

Android version: 6.0
Device model: HTC One M8
Stock or customized system: stock HTC ROM
ownCloud app version: 1.9.1
ownCloud server version: both on 8.1.5-15.1 and 8.1.6-13.1
#### Web server error log

This triggers nothing in the server log. I checked by accessing my OwnCloud via the browser from a PC, which sets a line in the owncloud log. Opening the app and having this crash doesn't add anything to the log.
#### ownCloud log (data/owncloud.log)

No such file can be found, probably because I'm not rooted? Is there any place else I can look or anything else I can do to make a log?

**Comment by tobiasKaminsky** [comment]
data/owncloud.log is on the server.
I do not know if it is possible to save the report instead of sending and post it here?

**Comment by deechte** [comment]
Thanks Tobias.
> data/owncloud.log is on the server.

I assumed that "**ownCloud log (data/owncloud.log)**" meant the Android app's log, cause the server log question already came before that.

On the server I checked the file owncloud.log. About that file I wrote my conclusion under the title **Web server error log**, because I thought owncloud.log is the error log. 
Are they two different files on the server (owncloud.log and error log) and if so, in what folder can I find the other one (error log)?

I just sent the error logs from the Android application. It can only go through the Google Play system. I cannot save it or send it through e-mail or something. I did add the issue nr 1590 to the description, might it arrive in the good place.

**Comment by deechte** [comment]
What I can do is remove all files and cache from the application. But that might make it hard to find the bug, if doing so fixes the problem.

**Comment by tobiasKaminsky** [comment]
The first error log is from apache or your web server.
Maybe you can install the beta version via f-droid or from 
https://github.com/owncloud/android/tree/beta/apks
There you get an error log that you can send via mail or save as file.
Or you can try to log it via logcat.

**Comment by gpothier** [comment]
Not sure this is the same bug as quite a lot of time has passed, but these are the same symptoms: trying to open some folders make the app crash: Here is what appears in the log:

11-17 12:27:45.659 15012 15012 E AndroidRuntime: FATAL EXCEPTION: main
11-17 12:27:45.659 15012 15012 E AndroidRuntime: Process: com.owncloud.android, PID: 15012
11-17 12:27:45.659 15012 15012 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at java.util.TimSort.mergeHi(TimSort.java:899)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at java.util.TimSort.mergeAt(TimSort.java:516)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:254)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1450)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:243)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at com.owncloud.android.utils.FileStorageUtils.sortByDate(FileStorageUtils.java:214)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at com.owncloud.android.utils.FileStorageUtils.sortFolder(FileStorageUtils.java:192)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at com.owncloud.android.ui.adapter.FileListListAdapter.swapDirectory(FileListListAdapter.java:393)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:831)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClick(OCFileListFragment.java:630)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:339)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1695)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4171)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.widget.AbsListView$13.run(AbsListView.java:6772)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
11-17 12:27:45.659 15012 15012 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
11-17 12:27:45.662  3730  6936 D Debug   : !@DumpState : SHIP
11-17 12:27:45.662  3730  6936 D Debug   : !@DumpState : debug level:0x4f4c
11-17 12:27:45.662  3730  6936 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
11-17 12:27:45.665  3730  6936 W ActivityManager:   Force finishing activity com.owncloud.android/.ui.activity.FileDisplayActivity
1

**Comment by deechte** [comment]
@jesmrec after so much time, I don't even remember which folder it was. I'm three Android devices further in time. Nevertheless, I can't recall having seen a crash lately. Maybe it's fixed.

**Comment by jesmrec** [comment]
ok, please, if you notice again this behaviour, feel free to reopen or create a new issue. Thanks.

**Comment by mueller-ma** [comment]
I have this issue as well:
````
28868-28868/com.owncloud.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android, PID: 28868
    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:895)
        at java.util.TimSort.mergeAt(TimSort.java:512)
        at java.util.TimSort.mergeCollapse(TimSort.java:435)
        at java.util.TimSort.sort(TimSort.java:241)
        at java.util.Arrays.sort(Arrays.java:1450)
        at java.util.Collections.sort(Collections.java:243)
        at com.owncloud.android.utils.FileStorageUtils.sortByDate(FileStorageUtils.java:254)
        at com.owncloud.android.utils.FileStorageUtils.sortFolder(FileStorageUtils.java:231)
        at com.owncloud.android.ui.adapter.FileListListAdapter.swapDirectory(FileListListAdapter.java:411)
        at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1006)
        at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$listDirectoryWithAnimationDown$0$OCFileListFragment(OCFileListFragment.java:726)
        at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$rq4e7ET6yfX7EhcSGjPkMNc62tg.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
````

@jesmrec Please reopen this issue.

**Comment by mueller-ma** [comment]
Version 2.12 from F-Droid.

**Comment by jesmrec** [comment]
any steps or clue to reproduce it?

**Comment by mueller-ma** [comment]
Not really. The app crashes each time when I open one specific folder. I removed everything except two folders from that folder via the desktop client. I also removed the `owncloud` directory on the files partition on my phone. App still crashes.

**Comment by schwedenmut** [comment]
I am experiencing the same issue while enabling picture sync and trying to change the default remote Upload folder.
Version 2.12 fresh install.
I will so some debugging tomorrow to figure out whats going wrong exactly.

**Comment by davigonz** [comment]
Hi @mueller-ma , thanks for reporting this. Removing the owncloud directory from the internal storage on your phone might not be the best idea, it could trigger other errors in the app.

By watching your logs, the problem seems to be related to some kind of files or folders sorting by date. I would say that the files included in the folder that triggers the crash do not have a modification timestamp for some reason. Could you detail what did you exactly do with those files? Were they downloaded?

**Comment by mueller-ma** [comment]
The folder I wanted to open was shared by another account to mine. I removed the share and shared it again. Now the app doesn't crash anymore.

**Comment by jesmrec** [comment]
Follow up: https://github.com/owncloud/android/issues/3403
