### ISSUE TITLE
Needed: Automatic or manual retry of failed instant upload

### ISSUE THREAD

**Issue by farao** [owncloud/android#1591]
It happens pretty often that my instant upload fails. I'm not quite sure why that is the case, it then just displays "Upload failed".

1) Is there a way to find out why it fails?
2) Regarding that an upload can fail for any reason (e.g. networking), it would be nice if the owncloud client retried uploading by itself or from time to time synchronises the instant upload directory with not yet uploaded files from the phone (those that failed, "really new ones" are being tried to upload) either automatically or manually (synchronize folder or so).
The current state on my Owncloud Client 1.9.1 on Cyanogenmod 12.1 is that the images that failed on uploading just never appear on the server and that I don't even seem to have a manual way to do it (except finding out by myself which images weren't uploaded and then select and upload them manually).

**Comment by AndyScherzinger** [comment]
There will be an Uploads screen showing to files currently queued for upload, uploaded files and failed uploads (+reason) which can be restarted: #1493 

This upcoming release is scheduled for this month/April.

**Comment by farao** [comment]
Wonderful, thanks!
