### ISSUE TITLE
weird problem (only mine!)

### ISSUE THREAD

**Issue by dany250** [owncloud/android#1593]
please help me to solve this weird problem:
i've installed owncloud on alt f firmware on my nas and it works gr8 in local
i can use it via web or with the app on my android device.
so i've tested with external connections, i can use it via browser perfectly.. but i can log in with the app, without getting any file, the app writes "nothing is inside! upload something" if i try to upload or create a folder.. it gives me error, 
also i already tested other apps... nothing changed!! HELP ME PLEASE!

**Comment by tobiasKaminsky** [comment]
What error do you get when creating a folder?
Please also fill in the issue report completely.

**Comment by LukeOwncloud** [comment]
We need more input here. Blind guess: might be an ipv6 issue (use github search). Closing for now. Please reopen if necessary.
