### ISSUE TITLE
Change to external storage

### ISSUE THREAD

**Issue by rudi123** [owncloud/android#1600]
To switch the storage folder to external sd card you have to create the owncloud-beta folder BEFORE switching. It would be more convinient when the folder is created automatically or at least there would be a message to create the folder by your own.

**Comment by tobiasKaminsky** [comment]
@przybylski Can you have a look into this?

**Comment by tobiasKaminsky** [comment]
@przybylski can you help me here?

**Comment by przybylski** [comment]
Sure, I was away for some time. Gimme few more days and I'll be back on full speed ;)

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. Change to external storage is not available right now in the stable version, so this needs to be closed.

Thanks for reporting :)
