### ISSUE TITLE
Pin is always wrong

### ISSUE THREAD

**Issue by rudi123** [owncloud/android#1601]
Doesn't matter which pin you type in. It's always wrong.

**Comment by malkomich** [comment]
Hi @rudi123 , could you explain a bit more your issue, please?

**Comment by rudi123** [comment]
- I set up an pin: 0000
- exit the app
- reopen the app
- I am asked for the pin
- enter the pin: 0000
-> do not match

this happens for every pin i tried

**Comment by malkomich** [comment]
What are the version of the app and the server you are using?
And the version of Android could be helpful too.

**Comment by rudi123** [comment]
App version: 20160410
Server: 9.0.1
Android 5.1.1

**Comment by davivel** [comment]
Hi, @rudi123 . Sorry, I don't understand your app version 20160410. You can find the number we need at the end of the "Settings" Activity in the app, accessible from the side drawer. 

Where did you get the app from? Did you build it? Did you download it from Play Store, from F-Droid, from other store?

**Comment by rudi123** [comment]
See owncloud version

**Comment by tobiasKaminsky** [comment]
Is it possible that you are using the beta version?

**Comment by rudi123** [comment]
yes thats right, i thought this is the thread for the beta...
sorry for the misunderstandings :-(

**Comment by tobiasKaminsky** [comment]
Please try it with the 20160419

**Comment by AndyScherzinger** [comment]
@rudi123 is the issue still present with one of the newer releases?

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)
