### ISSUE TITLE
Manage storage is not possible

### ISSUE THREAD

**Issue by rudi123** [owncloud/android#1602]
When trying to manage storage in the app properties owncloud beta crashes

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger maybe you have an idea?
` FATAL EXCEPTION: main
                                                                    Process: com.android.settings, PID: 6435
                                                                    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.owncloud.android.beta/com.owncloud.android.beta.ui.activity.ManageSpaceActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1630)`

But it is in AndroidManifest...and it is the same as in master..?

**Comment by AndyScherzinger** [comment]
com.owncloud.android.beta.ui.activity.ManageSpaceActivity seems to be wrong I think, even in beta the package name should still be without beta I think.

**Comment by tobiasKaminsky** [comment]
Hmm.
Naming it explicit to com.owncloud.android.ui.activity.ManageSpaceActivity yielded to a DexClassNotFound...

**Comment by LukeOwncloud** [comment]
@tobiasKaminsky Where did you explicitly named the activity? I tried:

    android:manageSpaceActivity="com.owncloud.android.ui.activity.ManageSpaceActivity">

The rest of AndroidManifest.xml stays untouched. Works.

**Comment by tobiasKaminsky** [comment]
@LukeOwncloud great!
I changed all the time a wrong line.
Will be in next beta!
