### ISSUE TITLE
Log.wtf() should not be used unless an assertion fails

### ISSUE THREAD

**Issue by kruton** [owncloud/android#1603]
### Expected behaviour
ownCloud should not crash on any build for non-assertion failures

### Actual behaviour
ownCloud crashes when Log.wtf is called on userdebug devices.

### Steps to reproduce
1. Run ownCloud on userdebug build on Android
2. Log into demo.owncloud.org

This crashes either immediately or after you have signed in seemingly depending on the speed of your phone (if it can display the file list fragment before it switches to login activity)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes.

### Environment data
Android version: Android MHC19Q

Device model: Nexus 6P

Stock or customized system: Stock compiled as userdebug using instructions at https://source.android.com/source/building.html

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by tobiasKaminsky** [comment]
If @davivel says that are valid changes can you open a PR?
