### ISSUE TITLE
Uploads from google drive do not work

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1607]
### STEPS TO REPRODUCE
1.- Expand the FAB and tap on "Content from other apps"
2.- Select "Drive" and some content

### ACTUAL BEHAVIOUR
Nothing is uploaded

### EXPECTED BEHAVIOUR
Selected content is uploaded

Tested with Nexus 6P

Server
{"installed":true,"maintenance":false,"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"}

**Comment by malkomich** [comment]
A toast message has been set to inform that the upload process retrieves an error.
This is a pending issue to solve, but for the new release it won't be implemented.

This issue is related to this one: #1476

**Comment by jesmrec** [comment]
For the new version will be accepted the toast in this case.

Anyway, the focus on this issue should not be lost.

**Comment by davivel** [comment]
As already said, this is not a regression. The bug already exists in version 1.9.1, and it's not straightforward to fix. We need to leave it for the next version.

Please, notice that this bug is in a different workflow than #1514 and #1529.

cc @rperezb @MTRichards @cmonteroluque

**Comment by davivel** [comment]
Indeed, we are duplicating here #1476

**Comment by cmonteroluque** [comment]
ok with me

**Comment by malkomich** [comment]
We can track the current PR for this issue: https://github.com/owncloud/android/pull/1643

**Comment by rperezb** [comment]
Fixed via https://github.com/owncloud/android/pull/1643
