### ISSUE TITLE
Feature Request: Use Realm Database

### ISSUE THREAD

**Issue by bkerensa** [owncloud/android#1609]
Realm database is faster and better performing than other databases on Android and is
cross-platform which means OwnCloud for Android could share an identical scheme
across both Android and iOS.

This would be a big performance win for your users.

**Comment by tobiasKaminsky** [comment]
I doubt that we can share a database scheme with iOS as they will have a different approach I guess.
So, only the better performance is an argument for switching.
@davivel Do you think that the app can benefit from changing the database? Or are in relation to performance other improvements (like lazy loading very very big folders a bigger speed gain?)

**Comment by bkerensa** [comment]
Here are some benchmarks: https://realm.io/news/introducing-realm/

**Comment by davivel** [comment]
Sorry, but there are many performance improvements to do before we could consider this would have any impact in the app. 

Besides, it adds an extra external dependency to maintain. 

And, definitely, as @tobiasKaminsky said, considering at this point refactoring the storage layer to make it common for both Android and iOS app... that would be titanic.

Being realist, this will not be done.

@bkerensa , thanks for your suggestion.
