### ISSUE TITLE
Move photos does not remove the origin

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1610]
### STEPS TO REPRODUCE
1.- Tap on FAB to upload a photo
2.- Select "Move" and then, one photo to be uploaded

### ACTUAL BEHAVIOUR
The photo is uploaded to oC, but the origin one remains on device with size 0B

### EXPECTED BEHAVIOUR
The photo is move to oC, and not appears anymore in device storage
Tested with Samsung Galaxy s3. Server 9.0.1.
In Nexus device works fine

Device: Samsung Galaxy s3 

Android 4.1.2

Server

{"installed":true,"maintenance":false,"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"}

**Comment by AndyScherzinger** [comment]
related to or a duplicate of: #1558

**Comment by malkomich** [comment]
Ready to test @jesmrec  :)
We could close both issues #1610 #1558 when it becomes approved by QA

**Comment by jesmrec** [comment]
@malkomich 
👍  Fixed for the new version
