### ISSUE TITLE
Favorites need refresh to show the yellow star

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1611]
### STEPS TO REPRODUCE
1.- Set a downloaded picture as favourite

### ACTUAL BEHAVIOUR
A refresh is needed to set the yellow star

### EXPECTED BEHAVIOUR
Yellow star is set when the file becomes favourite

Tested with Nexus7, Samsung Galaxy S3

Server

{"installed":true,"maintenance":false,"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"}

**Comment by davivel** [comment]
Not a regression, old enemy there. To be fixed later.

**Comment by davivel** [comment]
This should be fixed with version 2.1.0. @jesmrec , probably you already noticed it.
