### ISSUE TITLE
Syncronizing conflict are not well solved if "Keep Both" is chosen

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1612]
### STEPS TO REPRODUCE
1.- Change a text file in mobile and in server (different changes)
2.- Long press in txt file to Synchronize
3.- The conflict is detected
4.- Solve the conflict with "Keep Both"

### ACTUAL BEHAVIOUR
The mobile version and the containing folder are marked with the red wheel forever

### EXPECTED BEHAVIOUR
Both versions are stored and downloaded
Tested with Nexus 7 and Samsung Galaxy S3

**Comment by davivel** [comment]
Fixed now in branch release-2, @jesmrec

**Comment by jesmrec** [comment]
Fixed 👍
