### ISSUE TITLE
External app can not upload if passcode is set

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1616]
### STEPS TO REPRODUCE

1.- Set a passcode
2.- Close the app
3.- Try to upload a file from a external app (drive, gmail, downloads..)

### ACTUAL BEHAVIOUR
Passcode is asked and file is not uploaded

### EXPECTED BEHAVIOUR

Passcode is asked, after that is asked the location to upload and the file is uploaded

Tested with Nexus6
Server {"installed":true,"maintenance":false,"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"}

**Comment by davivel** [comment]
Fixed now in release-2.

**Comment by jesmrec** [comment]
👍  Fixed!!
