### ISSUE TITLE
Unable to start UploadListActivity OwnCloud Beta

### ISSUE THREAD

**Issue by supportreq** [owncloud/android#1625]
Expected behaviour

The Upload Activity should open displaying the list of uploads
Actual behaviour

Instead it threw a cause of error activity
Steps to reproduce

    Open the OwnCloud Beta App
    Open the Drawer and tap Uploads

Server configuration

Operating system: CentOS 6
Web server: Apache
Database: MySQL
PHP version: 5.6
ownCloud version: 8.0.1
Storage backend: Files
Client configuration

Client version: Beta Android App 20160419

Operating system: Android 6.0.1 Oneplus One CM13
Logs

https://gist.github.com/supportreq/9e30031b84e55db7d47276c480ffd87f#file-owncloud-uploadactivity

**Comment by AndyScherzinger** [comment]
Thanks for reporting this @supportreq. Did you do any uploads since you installed the latest version and then navigated to the upload screen?

**Comment by AndyScherzinger** [comment]
Pinging @davivel just to make sure this isn't an issue in the 2.0.0 release also.

**Comment by AndyScherzinger** [comment]
@supportreq I works on my phone :( I looked through the code and it seems your installation didn't do a database update (for some unknown reason).

**Comment by supportreq** [comment]
@AndyScherzinger I uninstalled the app and removed the owncloud-beta folder.. yet getting the same error..

**Comment by AndyScherzinger** [comment]
Hmmm, does this also happen for you with the new version 2.0.0 which has been released some minutes ago? Since Uploads view is a features that has just been released.

**Comment by davivel** [comment]
Mmm, I'm not sure but this could be a problem in the upgrade process for beta users because the schema of the table storing uploads was changed in development, probably after the feature was merged in beta branch. I'm sorry, we didn't take this update into account :S 

@supportreq , try to clean the private space of the ownCloud app (device settings > apps > ownCloud > 'manage space' button > 'clear cache' button) ; the uninstall the app, and reinstall it again.

**Comment by davivel** [comment]
By the way, release 2.0.0 seems OK.

**Comment by tobiasKaminsky** [comment]
It is definetly a problem regarding the upgrade, just like @davivel described.

**Comment by tobiasKaminsky** [comment]
But I am not sure how to fix this.
One way would be to drop the scheme and recreate it, but then we would introduce a new database version number and would always be one step ahead of master.
So I think we will keep it just the way as it only affects those people who upgrade the beta, and ... it is beta ;)

**Comment by supportreq** [comment]
@tobiasKaminsky @davivel I cleaned my cache and uninstalled the app still the same issue.. Is the 2.0 release on fdroid? i will test it..

**Comment by davivel** [comment]
Seems it's not in F-Droid yet, probably will be in a couple of days.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky but if you do a clean install that should solve the db upgrade issue which does not seem to help ?! :disappointed:

**Comment by davivel** [comment]
Yes, that's very strange.

Maybe were the last changes from uploads view taken to beta? Merge? Rebase? There were conflicts? Maybe a conflict resolution could break something.

**Comment by tobiasKaminsky** [comment]
I know that this is not the best answer, but uninstall and then install the app just works for me out of the box.

**Comment by davivel** [comment]
@supportreq, is this still a problem for you?

**Comment by supportreq** [comment]
@davivel working now!! :)
