### ISSUE TITLE
Android: Share a File: Download under Android doesn't work

### ISSUE THREAD

**Issue by Marco-Total** [owncloud/android#1629]
### Expected behaviour

If I in the app share a file , an encrypted link will be generated , that I can send to another user . When they opens the link, they can download the file.
### Actual behaviour

When I open the link under Android , the download fails ( Message: " unknown error " )
### Steps to reproduce
1. Share File in the App, or in the Browser
2. Send the encryptet Link to an Andoid Phone
3. Click on the Link an Start Download (Browser = Chrome)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
### Environment data

Android version: 6.0

Device model: Motorola XT1072

Stock or customized system: Stock

ownCloud app version: 2.00

ownCloud server version: 8.1.6

**Comment by LukeOwncloud** [comment]
Can be link be opened with another browser on the same phone? On another device, maybe PC?
Does Android Chrome report message or is it a message from the owncloud server `unknown error`? Please provide a screenshot if possible.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

**Comment by RUDI-TERROR** [comment]
Hey,

on the official owncloud server I can download any files under android...

Now, I create a test account for you:
https://marcoh.myftp.org:4443/owncloud
user / password: test / hallowelt

Just login under android and try to download a file...

**Comment by LukeOwncloud** [comment]
Using our account for me everything about sharing files and downloading them works. What exactly does not work for you? Error message? Screenshot?

What do you mean with "encrypted link"? That step I wasn't sure how to reproduce.

**Comment by jesmrec** [comment]
@RUDI-TERROR is the problem still there?
