### ISSUE TITLE
Battery drain: sync scans for unchanged folders

### ISSUE THREAD

**Issue by llucax** [owncloud/android#1644]
### Expected behaviour

Minimal activity when syncing with a server with a lot of folders but no changes since las sync
### Actual behaviour

Many folders gets scanned, making the phone busy (awake) for a long time on each sync, and draining the battery.
### Steps to reproduce
1. Create a lot of folders and files in the server
2. Activate sync
3. Wait and check server logs and phone's battery
4. Maybe use external (local) storage? Most of the folders are in external (local) storage, so it might be relevant.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

I haven't tested.
### Environment data

Android version: 6.0.1

Device model: Samsung Galaxy S4 LTE

Stock or customized system: Cyanogenmod 13

ownCloud app version: 2.0.0

ownCloud server version: 9.0.1
#### Web server error log

Loads of... (two entries for each folder)

```
server:443 10.1.1.50 - - [27/Apr/2016:00:40:44 +0200] "PROPFIND /remote.php/webdav/folder/ HTTP/1.1" 207 2040 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.0"
server:443 10.1.1.50 - - [27/Apr/2016:00:40:44 +0200] "PROPFIND /remote.php/webdav/folder/ HTTP/1.1" 207 37653 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.0"
```
#### ownCloud log (data/owncloud.log)

```
```

**Comment by MTRichards** [comment]
If I understand this properly, this is the device keeps scanning directories looking for changes?

@davivel @rperezb @AndyScherzinger what do you guys think? Is it something in the file watcher?

**Comment by llucax** [comment]
> If I understand this properly, this is the device keeps scanning directories looking for changes?

Yes. The sync process ends eventually, but on the next sync it will scan a lot of folders (I don't know if all of them) even when nothing changed.

**Comment by rperezb** [comment]
@MTRichards @llucax we have to check it

regularly, folders scan (after the first scan) are only those which includes any changes, sync is based on the eTag modification.  

What it could happen is that any shared data has been modified

**Comment by llucax** [comment]
Just FYI, I have a single user server (I'm the only user), and I barely use the share feature. I'm basically using owncloud to have my own sync service for files, contacts and calendar between my phone and my notebook.

**Comment by rperezb** [comment]
@llucax thanks for the info

**Comment by jesmrec** [comment]
Not reproducible anymore
