### ISSUE TITLE
Auto-restart failed upload from InstantUpload

### ISSUE THREAD

**Issue by JanZorz** [owncloud/android#165]
Sometimes it happens, that instant uploads are not uploaded due to connection resets or some other errors like connecting to a wifi hot-spot that needs authentication in html client after you connect and so on.

I would like to see the client to automatically retry failed uploads for InstantUpload periodically until all images are synced...

I have a lot of images on my phone which were not uploaded to owncloud but should have been...

**Comment by Bugsbane** [comment]
Any progress on this? Not being able to rely on ownCloud uploading when asked (especially for InstantUpload) essentially makes attempting more than a handful of uploads at a time with the client useless, as when something fails, the failure notification is easily lost, and you then can't rely on files existing where you asked.

**Comment by tobiasKaminsky** [comment]
This should be done with the newest upload sidebar: on every connection chane it tries to upload the failed items agian.

**Comment by davivel** [comment]
Thanks a lot, @tobiasKaminsky . Definitely, this should work better now.
