### ISSUE TITLE
Share files with Facebook

### ISSUE THREAD

**Issue by malkomich** [owncloud/android#1653]
### Expected behaviour
1. The link has to be correctly handled by Facebook app
### Actual behaviour
1. The ownCloud app throws an uncaught exception
### Steps to reproduce
1. Open share view of any file/folder
2. Set share via link ON
3. Select Facebook in the list of apps to send the link
### Environment data

Tested in Android v4.3

**Comment by tobiasKaminsky** [comment]
Can you provide a stacktrace?
Currently I am surprised that owncloud app is crashing as the link should be sent as an intent and therefore the receiving app (facebook, etc.) should not matter.

**Comment by michaelstingl** [comment]
Can no longer be reproduced. In case this happens again, please open a new issue. (too many things changed)
