### ISSUE TITLE
"Only wifi" uploads notification errors

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1654]
Setting up the instant uploads to "only wifi": each pic you take with phone bandwidth, a notification "Failed Upload" is returned. 

If  it is setting up "only wifi" and you does not have wifi connection, the fact that the pic is not uploaded is the expected behaviour and not a failure, and perhaps the user/device should not be notified.

It would be different if the device has any kind of connectivity.

**Comment by LukeOwncloud** [comment]
Duplicate of https://github.com/owncloud/android/issues/1628

**Comment by jesmrec** [comment]
Closing then...
