### ISSUE TITLE
add "sort by name descending" (Z-A) option

### ISSUE THREAD

**Issue by David177** [owncloud/android#1656]
### Expected behaviour

The App should give me the possibility to sort files descending.
Option "Z-A" should be implemented.

Why? Because I InstantUpload my photos. Sometimes upload of single files failed probably due to unstable mobile data connection or so. This leads to (probably) correct sorting by 'server create date'/'upload time' at "Newest-Oldest" option But causes to irritating list view. (e.g. Dsc_2011, Dsc_2012, Dsc_2009, Dsc_2013,...) 
The "A-Z" option is not practically usable due to endlos list scrolling till I would reach newest uploads

<img src="https://cloud.githubusercontent.com/assets/16853760/15026587/5a4c7f28-123f-11e6-9de2-76aa1d9ba487.png" width=350px/>
.
### Actual behaviour

Only Option "A-Z" and "Newest-Oldest" are selectable. (see also issues/discussion in #895  and #624)
### Environment data

Android version: 5.1.1

Device model:  E5823 

Stock or customized system: Stock

ownCloud app version: 2.0.0

ownCloud server version: 8.2.2

**Comment by thebaldconvict** [comment]
Agreed, I was looking for exactly this last night, I just uploaded all of my photos from my mobile to OwnCloud and it was a real pain to get to the bottom of the list.

Same with Newest - Oldest, it would be nice if there was also Oldest - Newest.

**Comment by davigonz** [comment]
Done, it will be included in 2.8.0
