### ISSUE TITLE
Android 6 + ext Sdcard: no moving image after uploading

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1658]
### Expected behaviour

Taken image should be moved from ext sdcard to owncloud directory.
### Actual behaviour

Image is uploaded, but not moved to oc directory (only copied).
### Steps to reproduce
1. Enable "file will be moved to sdcard"
2. Use a camera app that stores the images on ext sdcard
3. take photo
4. verify that it is still on ext sdcard

This seems to be due to the new android 6 permission system:
https://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop

As this is kind of a regression this should be handled with priority!
@davivel
### Environment data

Android version: 6.0.1

Device model: Moto X Play

Stock or customized system: Cyanogenmod

ownCloud app version: 2.0.0

**Comment by rperezb** [comment]
thanks @tobiasKaminsky for reporting this, we will check it

**Comment by davivel** [comment]
Sorry, I don't understand. The option "file will be moved to sdcard", is in the OC app? Is this in beta only?

**Comment by davivel** [comment]
What camera app may we use to test that stored images on ext sdcard?

**Comment by tobiasKaminsky** [comment]
@davivel Settings -> enable instant picture uploads -> original file will be ... moved to app folder

Camera app that support storing pictures on external sdcard:
Snap from CyanogenMod, Moto X Play CyanogenMod
Motorola Kamera, Moto X Play stock Android 6.x

**Comment by davivel** [comment]
There is something I don't understand. You comment this is "kind of a regression" . Was it working in version 1.9.1 and not working in 2.0.0? I couldn't check it by myself yet, but I can't think of a reason why this was working before but not now.

**Comment by davivel** [comment]
> https://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop

That link doesn't seem to address this specific problem; it's pointing to a solution that starts a document-picker activity, but our workflow here is totally automated, no interaction with the user to move the file.

**Comment by tobiasKaminsky** [comment]
I have never tested it with 1.9.1 as I am using my beta version, but as this feature was introduced in 1.9.1 and tested there I assumed that it has worked back then.
I suspect the switch to SDK 23 being the reason that it does not work any longer.
Android has changed the way dealing with the external sdcard again :/
The link should show the problem why everything works <6.0 but fails in android 6.0

**Comment by PVince81** [comment]
Similar issue observed here by @dttpy on Samsung J6 with Android 8 and the latest ownCloud Android app. She doesn't use instant picture upload but manually uploads using the upload button, then selecting the pics from the SD card. The pictures are copied, not moved.

I also wonder if it could be some kind of permissions issues.

**Comment by michaelstingl** [comment]
@davigonz @jesmrec maybe have a quick look about the behaviour with the current `master` builds.
