### ISSUE TITLE
First image in queue fails to upload once the device connected to a WiFi network

### ISSUE THREAD

**Issue by s3b-** [owncloud/android#1662]
### Expected behaviour

All images I took while not connected to a WiFi network should be uploaded once I connect to a WiFi network.
### Actual behaviour

The upload of the first image in the queue fails. No problem with the other images.
### Steps to reproduce
1. Turn off WiFi
2. Snap 4 pictures
3. Turn on WiFi
4. Error message appears
### Can this problem be reproduced with the official owncloud server?

Yes
### Environment data

Android version: 5.1.1

Device model: Nexus 5

Stock or customized system: Cyanogenmod

ownCloud app version: 2.0.0

ownCloud server version: ownCloud 9.0.2 (stable)

**Comment by s3b-** [comment]
Log file from my phone
[owncloud.txt](https://github.com/owncloud/android/files/262173/owncloud.txt)

**Comment by kslaggs** [comment]
Same issue.  Nexus 5x.  OwnCloud 9.0.2

**Comment by davivel** [comment]
Seems the app is interpreting the Wifi is available too soon. We'll need to have a look.

**Comment by theScrabi** [comment]
Since version 2.6.0 got a complete refactoring of the image upload this issue might not be valid anymore.

**Comment by davigonz** [comment]
@s3b- , @kslaggs could you try with the latest version of ownCloud Android app? 2.6.0 version includes the new Camera uploads feature, replacing Instant Uploads, and will upload automatically your pictures and videos in 15 minutes at most.

**Comment by s3b-** [comment]
@davigonz Doesn't seem to happen anymore. It takes a while until the images are being uploaded, though. But no error messages. Thanks!

**Comment by davigonz** [comment]
Thanks for your feedback @s3b- , we will close this then
