### ISSUE TITLE
Auto upload new files in synced folder

### ISSUE THREAD

**Issue by helmo** [owncloud/android#1663]
### Expected behaviour

When I edit a file on android that was downloaded via Owncloud it uploads the changed file. But a new file created under an existing directory downloaded by Owncloud is not uploaded.
### Actual behaviour

The new file is ignored. It's not even visible in the owncloud client.
### Steps to reproduce
1. download a folder using the Owncloud android app
2. open some app to create a new file in the Owncloud managed directory
3. be disappointed that the file does not show up on the server.

I would have expected this to be covered by #3 but as that's closed....
Some discussion about this was in  #1136 ... but it was suggested to create a new issue for this specific feature.
### Environment data

Android version: 6.x

Device model: nexus 5

Stock or customized system: stock

ownCloud app version: 2.x beta 20160427

**Comment by tobiasKaminsky** [comment]
This would then be a real 2 way folder sync.

**Comment by jesmrec** [comment]
No way. Scoped Storage does not allow such things anymore
