### ISSUE TITLE
Android N Updates

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#1675]
Problem: Android N is coming out in October, and we need to prepare the ownCloud app to work with the expected changes.

In fact, we are expecting a few changes, many largely due to the concern of Android to conserve batteries.

The big issues we know of are:
- The current instant uploads approach will no longer work.

The alternative is the media store, so we need to switch to use it. BUT, it is not clear how immediate the notifications are so it might not be immediate instant uploads.
- The synchronization of the accounts will also not work because of the loss of the background

The DOZE subsystem from Android 6 continues with ownCloud (designed to save battery life), but gets worse in N from our perspective. When the phone is left alone, and even moving but the screen is dark, after a some period of time makes other systems not available, such as the network. This means uploads in progress will be killed. A user can then reactivate them manually in ownCloud, but we need to deal with the fact that at any moment the system can interrupt the network, and thus kill sync and uploads/downloads.

Users can disable Doze as well, but this is not ideal. However, a user can be asked this with a redirect to the system dialog about turning off Doze.

One alternative for instant uploads is to create a service that is watching the folder for changes, and then we know immediately when a photo appears (solves 1). But then the second problem with Doze happens, and we need to figure out how to deal with it.

Perhaps we can use the new chunking and add pause/resume capability, and chunk handling, so that when Doze interrupts the network, the app is able to resume rather than restart the upload.

Ideal dev end state:
1) Create a service that watches the file/folder for cnahges
2) Update the uploader to be able to work in the short active windows between when Doze is on
3) Add the ability for the pause and resume of uploads using the new 9.1 chunking, as well as older ownCloud instances. This likely means chunking and pause/resume will only be enabled on servers 9.1 or newer, and for older servers pause resume is not possible. (maybe)
4) We need to consider how we resume downloads or we have the same problem as well for a synced folder / favorites

Effort: This is a major effort when combined. Individually, this is also large individually.

Conceivably this could be just a little later than the release of Android N.

@davivel 

---

And @davivel was here:

Problems to fix:
- [x] Pictures / videos taken with the mobile need to be added automatically to OC if the user enable 'instant uploads : #6 ; related also: #744
- [x] Adapt to Doze; this will require some direct experimentation, "Doze mode" may be enforced with development tools: #1684

**Comment by tobiasKaminsky** [comment]
For 1) we can use #1059 which can observe any specified folders for changes.

**Comment by davivel** [comment]
@tobiasKaminsky , as you said, the current replacement is #1650. Going there.

**Comment by AndyScherzinger** [comment]
I am now running the Android N beta on my day to day device so I can help out testing stuff.

**Comment by davivel** [comment]
Support for Doze added. Further improvements will be added in new issues.
