### ISSUE TITLE
Cannot import into Android Studio

### ISSUE THREAD

**Issue by 11harveyj2** [owncloud/android#1678]
Not sure if I'm doing this correctly but,
I've read the SETUP.md file
I've imported the project into Android Studio
However I cannot do anything as it keeps giving me this error:
Error:A problem occurred configuring root project 'android-stable'.
> Cannot evaluate module owncloud-android-library : Configuration with name 'default' not found.
I've tried using different branches. I've ran the setup_env.bat file and still nothing

Any help?

**Comment by AndyScherzinger** [comment]
Hi there! Did you do a recursive git checkout? This is necessary in order to also checkout the lib project. If not you need to do a git init and update. 

Hope that helps. :)

**Comment by AndyScherzinger** [comment]
These are the commands you need to call on the command line
```
    git submodule init
    git submodule update
```

**Comment by 11harveyj2** [comment]
Ok. Didn't run those commands. Will do later on today. Cheers

**Comment by AndyScherzinger** [comment]
you're welcome :smiley:

**Comment by nedimhx** [comment]
@AndyScherzinger can you please explain how to do recursive git checkout?

**Comment by AndyScherzinger** [comment]
@nedimhx sure :smiley: basically add  --recursive while calling git clone

see
https://github.com/owncloud/android/commit/62dd4fa66bacbe3175710a70f3991eb39e93fb44#diff-550856cf67eb7260aaeb883550043af8R35

--> ```git clone --recursive git@github.com:YOURGITHUBNAME/android.git```

main repo:
--> ```git clone --recursive git@github.com:owncloud/android.git```

**Comment by nedimhx** [comment]
@AndyScherzinger How to open console in Android Studio 2.1, Im using Windows 10

**Comment by AndyScherzinger** [comment]
Hi @nedimhx no idea :( I do not use Android Studio for anything git-related :(

**Comment by nedimhx** [comment]
I use my ubuntu vps but I don't have access to this repository

git clone --recursive git@github.com:owncloud/android.git
Cloning into 'android'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by AndyScherzinger** [comment]
Hmm, okay.

Then maybe just fork it on Github and try
```git clone --recursive git@github.com:YOURGITHUBUSERNAME/android.git```

**Comment by nedimhx** [comment]
I done it by git clone --recursive https://github.com/owncloud/android.git

And now I can build app, but once when I want to rename package at first I need to click on com.owncloud.android package, then in settings to un check Compact empty middle package, and after  I click on owncloud --> refractor --> rename --> rename package rename it to "test" and click "Refractor" confirming with "Do refractor" after process finish with renaming, in AndroidManifest.xml I change package="com.owncloud.android" to package="com.test.android".
And when I try to rebuild project got some errors :/

**Comment by AndyScherzinger** [comment]
@nedimhx can you post the errors? :)

**Comment by nedimhx** [comment]
C:\Users\nedim\Desktop\android\src\com\test\android\files\FileOperationsHelper.java
Error:(37, 24) error: cannot find symbol class R

And lots of similar errors

**Comment by AndyScherzinger** [comment]
Did you run the app from within Android Studio or called compile from the gradle window within Android Studio? Because this is when Androids build tools will generate the call R!

**Comment by nedimhx** [comment]
After I rename package and modify androidmanifest, only thing what I did is Rebuild and get this errors.

**Comment by AndyScherzinger** [comment]
did you also change the package name in ```build.gradle``` ?

**Comment by nedimhx** [comment]
There is no any line in build.gradle where is typed package name com.owncloud.android, so I can change it to my package name

**Comment by AndyScherzinger** [comment]
right! Hmmm, did you check all package references within xml files? As there are probably some more e.g. in setup.xml.

**Comment by nedimhx** [comment]
Got it !!
I need to update not only package name in android manifest at root of project, need to update at oc_jb_workaround and owncloud-android-library too :)

Thank you fer everything !
