### ISSUE TITLE
"Copying file from private store" - file gets copied somewhere before uploading which drains storage and takes time

### ISSUE THREAD

**Issue by Nowaker** [owncloud/android#1679]
### Expected behaviour

File gets uploaded.
### Actual behaviour

File got copied somewhere (which took a minute) and then it was uploaded. Now I have the same file in two locations, one on my SD card and one on my phone storage, and that drains my phone storage.
### Steps to reproduce
1. Move file to SD storage.
2. Go to any gallery app and click Share, choose owncloud
3. Choose any target directory.

Can this problem be reproduced with the official owncloud server?
N/A
### Environment data

Android version: 4.4.4
Device model: Motorola Photon Q
Stock or customized system: Customized
ownCloud app version: 2.0.0
ownCloud server version: 9.0.2
### Logs

Not relevant

**Comment by jesmrec** [comment]
This is the expected behaviour to avoid data loss.
