### ISSUE TITLE
Feature Request: Delayed Instant Upload

### ISSUE THREAD

**Issue by jakob42** [owncloud/android#1680]
When I'm taking pictures, I usually take a couple and choose the best out of them afterwards. But by the time I've chosen my favorite and deleted the other copies, owncloud already uploaded all pictures. So now I have to delete 6 pictures in the client (which is tedious, because there doesn't seem to be multi select.)

I would love to have a setting where I can set a delay (5mins, 15mins or 30mins for example) to upload the pictures. If the photo is still there by then, upload it, if it isn't, delete the queue entry.

For everybody finding this on Google until it might be implemented: I solved this by using FolderSync (or any other sync app) I use anyways and upload the pictures every 30mins. Sometimes I take them right before an upload cycle, but most of the time it works just fine.

**Comment by jabarros** [comment]
It could be a good enhancement. We will discuss about this.
Contributions are welcome :-)

**Comment by tobiasKaminsky** [comment]
I also think is is a really good idea.
But before this, we have to discuss how and where this delay can be set.
Just as a new entry for each "instant picture" and "instant video"?
How to set: type value and set as seconds? What if it should be e.g. 30min?
@jancborchardt

**Comment by tobiasKaminsky** [comment]
And: I assume that this delayed upload is a countdown that starts for each taken image/video (opposite as folder sync that is using a "stupid" 30min interval")

**Comment by jakob42** [comment]
I would suggest it exactly like that. Best would be to make the delay length an user option.

**Comment by LukeOwncloud** [comment]
Already some discussion about this topic here: https://github.com/owncloud/android/issues/643

**Comment by utack** [comment]
You have to change the whole process for Android N anyways, as seen in 
https://github.com/owncloud/android/issues/1675

**Comment by davivel** [comment]
As @LukeOwncloud said, this is duplicating #643. Please, let's join and track any progress there.
