### ISSUE TITLE
Instant Upload failes  with wrong server address

### ISSUE THREAD

**Issue by hitam4450** [owncloud/android#1682]
### Expected behaviour
Tell us what should happen
Instant upload after taken picture
### Actual behaviour
Tell us what happens instead
Instant upload failes
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:
4.4.2, 5.0.,1
Device model: 
Galaxy Grand Tab S 8.4
Stock or customized system:
stock
ownCloud app version:
2.0
ownCloud server version:
9.0.2.2

The account info are as : https://ipocserver/owncloud, user and password logged in successful!
However the server address in the failed picture uploads reads like : user@ipocserver/owncloud/**ownCloud**/SofortVideo 
Error message: Zugangsdaten falsch!

I repeated the setup the account several times, double and triple checked all input info, however the error remains still the the same!

I do know where /**ownCloud** comes from!

However, the SofortUpload directory is shared with my OC 9.02 Backup server at a different Ip address!

After removing the share, the Error message remains the same!

regards, hitam4450

**Comment by tobiasKaminsky** [comment]
This looks for me like a wrong redirect of a virtual host on server?
Or do you use a weird htaccess?
Or maybe it is enough to choose the instant upload folder again? If this is somehow set to "ownCloud/SofortVideo" you will have this problem. Maybe try just a folder with is in the root directory?

**Comment by hitam4450** [comment]
Hi,

I do not see weird htaccess access. I use lighttpd 1.4.35 web server, all configuration is fine an Ok double checked everything, did not make any changes since several months!

**Comment by davivel** [comment]
Hi, @hitam4450 .

Are manual uploads working fine? What about downloads, and operations on files (delete, move, etc...)?

**Comment by hitam4450** [comment]
From my handset (galaxy Grand 4.4.2) nothing is working at all. With my Tablet (Galaxy TAB S 8.4 , 5.0.1) 
I am able to manually upload and move,delete files. Only Instant(FOTO)Uploads do not work.

OC 9.0.2 with client Android client 2.0

**Comment by davivel** [comment]
> OC 9.0.2 with OC Android client 2.0
> When I was using the OC 8.2.x branch, everything was working fine on both systems!

Well, that makes me think in the problem might be in the server side.

How did you make the switch from 8.2.x to 9.0.2? Changing branches in git?

**Comment by hitam4450** [comment]
No, clean install!

**Comment by davivel** [comment]
And nothing works in Galaxy Grand 4.4.2? 

Can you see how are written the accounts in the settings view in the app? Do they show the duplicated ```owncloud``` word too?

**Comment by davivel** [comment]
Where did you get the ownCloud app? Play Store, F-Droid, source code and built by yourself, other?

**Comment by hitam4450** [comment]
Play Store....

**Comment by hitam4450** [comment]
No the account settings in the Tab Einstellungen / settings are ok and show owncloud only once in the address!

**Comment by davivel** [comment]
This is really weird. 

- Did you update from version 1.9.1 to 2.0.0 in Play Store, or is it a fresh install also?
- Is it failing for instant videos, for instant pictures, for both? Do you have both options enabled?
- Did you set a custom path for instant uploads at any moment? Before or after upgrading the app? Before or after changing server version? Same path for videos and pictures?
- Do you have wifi-only option ebaled?
- What's your value for 'Original file will be...' ?

**Comment by hitam4450** [comment]
Well, thanks for your support solving this issue!

i upgraded the app from Play store.
Video Uploada failed as well, including the same weird error message.
No custom path, accepted the presets. Directories are available on the server (Worked before)
WIFI Only enabled (both)

value is: username@ipofserver/owncloud/ownCloud/SofortUpload
and
username@ipofserver/owncloud/ownCloud/SofortVideo

Please note the spelling of ownCloud with a capital C......never used anything like this ...nowhere!

**Comment by davivel** [comment]
What's your variant of German? I can't find the version of the app where ```SofortVideo``` was a default value...

**Comment by davivel** [comment]
I'm out of ideas...

Could you try to change the both folders where instant uploads will be saved and try some pictures and videos?

**Comment by hitam4450** [comment]
Well thanks for your efforts and support!

It is just plain german version ..... no variant!

**Comment by hitam4450** [comment]
I created a folder named Instant from the client, changed the Upload folder to instant,  took a picture  and it was uploaded without a glitch. Returning back to SofortUpload got me back the error message as described!

regards, hitam4450

**Comment by hitam4450** [comment]
Maybe an issue with the length (numbers of characters9 of the folder name SofortUpload  and SoofrtVideo ??

regards, hitam4450

**Comment by tobiasKaminsky** [comment]
Can you have a look on the SofortUpload folder on the server via the shell?
I suppose that somehow this folder is broken, if a new folder is working.

**Comment by hitam4450** [comment]
Hi,

the SofrtUpload and SofortVideo folder did not exist in the ...owncloud/data/user/files directory, however they  did show up in the web interface. After creating both of them, adding the correct user(www-data) permissions and ownerships, direct upload of pictures and videos work flawless!

regards, hitam4450

**Comment by tobiasKaminsky** [comment]
Strange, maybe someone deleted them without notifying this to owncloud...
