### ISSUE TITLE
Speed loading of pictures

### ISSUE THREAD

**Issue by Aohzan** [owncloud/android#1689]
Hello,

Is there a way to force the app to download a thumbnails of pictures, for juste download some KB instead of MB ?

Thank you

**Comment by tobiasKaminsky** [comment]
There is an approach to load bigger "thumbnails", screen adapted images into cache (~50kb) each to avoid having to download an entire image when just sharing via e.g. whatsapp:
#1599 
You can vote for it on: https://github.com/owncloud/core/issues/24684#issuecomment-221595646

**Comment by rperezb** [comment]
@Mati24 will this approach work for you? 
The full image won't be downloaded automatically
If so, feel free to close the issue and follow the status on #1599 its current status is backlog so in the pipeline for the very short term 🎉

**Comment by tobiasKaminsky** [comment]
> its current status is backlog so in the pipeline for the very short term :tada:

I hope so as my PR is quite really oooold...

**Comment by Mati24** [comment]
Sorry I didn't answer, this is just what I want, but does it concern just Android app ? Or iOS app and web browser too ? Thanks

**Comment by AndyScherzinger** [comment]
@Mati24 The implementation by @tobiasKaminsky cover Android only.

**Comment by Mati24** [comment]
ok thanks
