### ISSUE TITLE
legacy 2.0 and BETA-20160427 - Shared link does not get coppied when GET LINK is pressed

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1690]
### Expected behaviour

When I set on a file Share with link, and then press GET LINK the link should get coppied or sent to appropriate app.
### Actual behaviour

Setting share by link works, but when I press GET LINK (I have it set in Spanish)
### Steps to reproduce
1. Set share by link
2. Try to obtain the link via GET LINK
### Environment data

Android version:
Marchmallos 6
Device model: 
Nexus 5
Stock or customized system:

ownCloud server version:
9.0.3

**Comment by rperezb** [comment]
@elpraga this is how it's define the share link action

How do we know what action you want to follow? I mean, if you want to copy the link or sent to an app; in case you want to sent it to an app, which app?  as far as I see, it's needed the menu

we'd appreciate further details about your request

**Comment by elpraga** [comment]
Hello @rperezb! The menu does appear,  but none of the action I select gets executed.  If I select copy to clipboard,  nothing is copied, if I send it to a player, the player does not receive the link.  

I apologize for not making that clear the first time.

**Comment by elpraga** [comment]
Thank you for getting back to me so quickly Raquel! I tried different files and others do work as expected.
The two different things I can think of are that this file is on a local storage accessed through ownCloud and that it has international characters in the name. 

I'll investigate more when I get to the computer.
