### ISSUE TITLE
[2.0.0] Unclear German translation in Uploads view

### ISSUE THREAD

**Issue by johnripper1** [owncloud/android#1691]
### Steps to reproduce
1. Install ownCloud 2.0.0 on a Andoid device that runs German as language
2. Open the ownCloud application and goto "Uploads" view
3. Tab the "Option" Button in the right top
4. Try to understand what I can do in this menu:
![screenshot_20160529-163144](https://cloud.githubusercontent.com/assets/10068353/15634096/f5664aea-25bb-11e6-96fa-5ff9583f57f3.png)

Can some explain what the options in the Upload menu are good for? The German translation doesn't make sense at all in my eyes:
- I have no idea what the app should when I choose on of the four options
- I have no idea what the app actually does when I choose on of the four options
- The german translation doesn't make sense at all
- Manual doesn't help: https://doc.owncloud.org/android/android_app.html#managing-files

If someone can provide me with the English translation I'll be happy to translate into German. I saw more German participants here, so all are invited to discuss.

**Comment by LukeOwncloud** [comment]
Already fixed: https://github.com/owncloud/android/blob/master/res/values-de-rDE/strings.xml#L404-407

**Comment by tobiasKaminsky** [comment]
and it is also in beta, if you do not want to wait until next release
