### ISSUE TITLE
Upload: count uploads

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1692]
For pending, failed, etc. there should be the count shown: failed (5)

**Comment by rperezb** [comment]
@tobiasKaminsky nice, do you mean adding this counter within the uploads view? on the section tab name?

**Comment by tobiasKaminsky** [comment]
Exactly :+1:

**Comment by cinnamonsalt** [comment]
@tobiasKaminsky 

Just to be clear did u mean something like this?

![screenshot from 2017-04-04 18-35-13](https://cloud.githubusercontent.com/assets/8122102/24668021/b1ad788e-1965-11e7-8480-75e7127124f3.png)

**Comment by davivel** [comment]
I think this was about the titles of the sections, not the options in the menu. They are not shown if no upload was done, make some correct uploads, some failed uploads and see the view again.

**Comment by cinnamonsalt** [comment]
Added the section file count in PR #1937

![screenshot_1491577147](https://cloud.githubusercontent.com/assets/8122102/24806449/3a5c6504-1bb5-11e7-843f-0b3d20a2dfcd.png)

**Comment by davivel** [comment]
Ready to go with 2.4.0 thanks to @cinnamonsalt .
