### ISSUE TITLE
Refreshing icons in "available offline" feature

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1694]
### Steps to reproduce

Two possible scenarios:

scenario 1:  Set a downloaded file as "available offline"
scenario 2:  Unset a file as "available offline" 

### Expected behaviour
Icon is set/removed without refreshing

### Actual behaviour
A refresh is needed to set/remove the icon

App version: v2.0.0
Android versions: v4.3, v5.1
Server version: v9.0.2

**Comment by rperezb** [comment]
@jesmrec it will be great if you add the ownCloud Android version where you detect this bug

**Comment by jesmrec** [comment]
👍  right, i forget the versions somewhere. Added.

**Comment by davivel** [comment]
This is fixed as a "side effect" in #1736

**Comment by jesmrec** [comment]
fixed in #1736

Closing in 1...2...3
