### ISSUE TITLE
Enable Multi-Window mode

### ISSUE THREAD

**Issue by malkomich** [owncloud/android#1696]
The multi-window is a new interface design in Android devices available from Android N API (https://github.com/owncloud/android/issues/1675), to keep in the screen more than one application.

There are two different modes in mult-window interface: multiple app mode, and picture-in-picture.

I suggest to implement the compatibility as a first approach to adapt our interface, because I think the picture-in-picture may not gives much functionality to the ownCloud app.

https://developer.android.com/preview/features/multi-window.html

**Comment by jesmrec** [comment]
Already supported in the app. Thanks @malkomich
