### ISSUE TITLE
Suggestion on share files on phone (hear me out)

### ISSUE THREAD

**Issue by goopen** [owncloud/android#1697]
I often send screenshots and other non-camera pictures via xmpp clients such as conversations.im 
which supports communicating with gtalk and other protocols - however here you cant share pictures inline the chat - which sucks. But this might be alleviated by being able to send public link to the user without going into the trouble of first uploading a file to owncloud via the app and then copy the link and send to the user. 
### Expected behaviour
1. Select picture via gallery/file explorer app and "Share with owncloud via public link"
2. Public link is created and returned (this should just default to default expiration settings etc)
3. This will only return url in clipboard which user can be pasted into preferred app such as conversations.im.

Preferrably the images/files should be located in a "Public" folder perhaps? also configurable in the App as "default location for files shared via public link share". 

Maybe this is not feasible, and maybe there is better ways to do this or circumvent the problem.

What do you guys think?

Kind regards

**Comment by jesmrec** [comment]
Not expected ftm
