### ISSUE TITLE
[Bug] Renaming a file in other client or in server, makes the file lose the "av offline"

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1703]
### Steps to reproduce

1.- Set a file as "available offline"
2.- In server or in another client, rename the file
### Actual behaviour

File is not available offline
### Expected behaviour

File keeps on being available offline

Tested with Nexus7 v4.3, Nexus5 v5.0.1

**Comment by PVince81** [comment]
@davivel pointed out that the "av offline" mode was NOT linked to the file id, so not sure why this is happening.

I think I saw this happening on my env when I had conflicts in another client and resolved them, in which case I might have renamed one of the conflict files to overwrite the normal file.

In the case of fileid, if a file is moved/renamed they'd usually keep the fileid.
Maybe the mobile client should use the fileid instead for such options ?

The fileid should stay the same in most situations, see https://github.com/owncloud/core/issues/13310#issuecomment-92690030

**Comment by davivel** [comment]
This is too delicate to go in next release by this time. Moving to 2.2.0

cc @rperezb @jesmrec @nasli

**Comment by nasli** [comment]
👍 Agree @davivel, related issue in iOS https://github.com/owncloud/ios/issues/682

**Comment by davivel** [comment]
Sorry, but we need to drop issues from milestone 2.4.0 to get it out next to OC 10 server.

This time we'll move topics to ```backlog``` instead of directly to next release, so that we can schedule 2.5.0 properly.

**Comment by theScrabi** [comment]
So what I found out investigating this is that we drop the database entry of a file when it gets gets renamed, and then synchronized.
So all the information that is not stored on the server like local path to the file stored on the smarthphone, and the "available offline" flag get lost, and the actual renamed file is then handled like a new file.

**Comment by theScrabi** [comment]
There is a more common issue than this. https://github.com/owncloud/android/issues/2137
https://github.com/owncloud/android/issues/2137 also handles the deletion of a local file if a file gets renamed or moved. This is both related to this issue.

**Comment by davigonz** [comment]
It will be included in 2.8.0
