### ISSUE TITLE
Android app not able to upload photos manually

### ISSUE THREAD

**Issue by Caerdwyn** [owncloud/android#1707]
**EDIT:** I downloaded the latest beta .apk package and installed it, the issue below no longer exists, so whatever is causing this in v2.0.0, is no longer present. Going to stick to using the beta version of the app for now until this can be resolved.

### Actual behaviour
-Tell us what happens
When I try to manually trigger an upload from either the internal memory or the external microSD card of my phone, all I get is a notification of `Unknown Error` on the screen for a brief moment. If I capture a photo with the camera, the InstantUpload feature of the owncloud app works just fine, uploading anything I capture.

### Expected behaviour
-Tell us what should happen
When I try to manually upload files from my phone, they should upload without an error.

### Steps to reproduce
1. Open owncloud app on phone
2. Tap the + icon to upload a file
3. Select a photo

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes. Trying to upload any file, whether a photo, video, or .txt file, results in the same `Unknown Error` notification.

### Environment data
Android version: 5.1.1

Device model: Samsung Galaxy S5 - SM-G900A (AT&T)

Stock or customized system: Stock

ownCloud app version: 2.0.0

ownCloud server version:
(Output from `occ status` command)
  - installed: true
  - version: 8.2.5.2
  - versionstring: 8.2.5
  - edition: 

#### Web server error log
```
Insert your webserver log here <= I would, but there's nothing in nginx's error.log file that pertains to owncloud, just some 404 errors from bots scanning my server.
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"CxNTXFfyjbCRyhH\/rqcc","remoteAddr":"192.168.1.1","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-06-08T20:53:26+00:00","method":"HEAD","url":"\/remote.php\/webdav\/Galaxy%20Backup\/Pictures\/"}
{"reqId":"7HotrbLvuU2BLLZ2C7bM","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Galaxy Backup\\\/Pictures\\\/20160608_165322.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(78): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Galaxy Backup\\\/P...', 0)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":159}","level":0,"time":"2016-06-08T20:53:26+00:00","method":"HEAD","url":"\/remote.php\/webdav\/Galaxy%20Backup\/Pictures\/20160608_165322.jpg"}
```

The error above appears every time the InstantUpload feature of the app runs, but no other messages appear when I manually trigger an upload.

**Comment by AndyScherzinger** [comment]
Hi @Caerdwyn is still error still present with the freshly released 2.0.1?

**Comment by davivel** [comment]
Please, @Caerdwyn, test with 2.0.1 as @AndyScherzinger said. This bug corresponds to #1607, fixed in  #1643. We discovered during the fix that was not specific to Google Drive as described first.

Thanks.

**Comment by Caerdwyn** [comment]
@AndyScherzinger @davivel 2.0.1 Seems to have fixed the issue, thank you for your help!

**Comment by AndyScherzinger** [comment]
You are very welcome! Glad to hear to issue has been resolved :)
