### ISSUE TITLE
SAML session expires when share view is opened

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1710]
### Steps to reproduce
1. Open a session in a SAML server v9.1
2. Try to share a file/folder

### Expected behaviour
Usual behaviour of share view

### Actual behaviour
Session expires, no matter how long it was opened.

### Server configuration
{"installed":true,"maintenance":false,"version":"9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"}

Tested with Nexus5 v5.0.1

**Comment by davivel** [comment]
Having a first look...

**Comment by rperezb** [comment]
related to:https://github.com/owncloud/ios/issues/700
@jesmrec is this reproduable on the desktop client ?

**Comment by davivel** [comment]
Probably; seems in the server side, OCS routes are not accepting a right token.

Failing with capabilities API also, and other calls to share API, but errors are silently ignored in other flows.

**Comment by rperezb** [comment]
@davivel can you please open a ticket on the core repo, add current milestone + p1 severity 😁

**Comment by davivel** [comment]
core or enterprise?

**Comment by davivel** [comment]
Opened owncloud/core#25057

**Comment by jesmrec** [comment]
@rperezb, yes
https://github.com/owncloud/core/issues/25057#issuecomment-225178677

**Comment by rperezb** [comment]
Waiting for server info

**Comment by jesmrec** [comment]
Server problem fixed, working fine on mobile clients.
