### ISSUE TITLE
Can not decrypt file on mobile client

### ISSUE THREAD

**Issue by team-alpeinsoft** [owncloud/android#1711]
### Actual behaviour

Cannot download file from mobile client when using server side encryption
### Steps to reproduce
1. Install owncloud. 
2. Enable encryption. 
3. Share file with user.
4. Try download file from mobile client (Android/iOS)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes, we can, but demo version not have encryption App.
### Environment data

Android version: All version

Device model:  All models

ownCloud app version: All versions

ownCloud server version: 9.0.2
#### Web server error log

[10/Jun/2016:14:45:33 +0200] "GET /owncloud/remote.php/webdav/community.txt HTTP/1.1" 500 1630 "-" "Jakarta Commons-HttpClient/3.1"
#### ownCloud log (data/owncloud.log)

{"reqId":"m01\/psu9n5hlK1KbxI1\/","remoteAddr":"37.17.19.59","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-06-10T12:45:34+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/community.txt","user":"C96C88E4-9F71-4E45-9D6D-4FF46F01AEB6"}
{"reqId":"m01\/psu9n5hlK1KbxI1\/","remoteAddr":"37.17.19.59","app":"webdav","message":"Exception: {\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/files\\/stream\\/encryption.php(459): OCA\\Encryption\\Crypto\\Encryption->decrypt('NB2yToafXnn8ROy...', '0end')\n#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/files\\/stream\\/encryption.php(290): OC\\Files\\Stream\\Encryption->readCache()\n#2 [internal function]: OC\\Files\\Stream\\Encryption->stream_read(8192)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/icewind\\/streams\\/src\\/Wrapper.php(83): fread(Resource id #83, 8192)\n#4 \\/var\\/www\\/owncloud\\/3rdparty\\/icewind\\/streams\\/src\\/CallbackWrapper.php(91): Icewind\\Streams\\Wrapper->stream_read(8192)\n#5 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_read(8192)\n#6 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/http\\/lib\\/Sapi.php(78): stream_copy_to_stream(Resource id #86, Resource id #88, '861')\n#7 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(470): Sabre\\HTTP\\Sapi::sendResponse(Object(Sabre\\HTTP\\Response))\n#8 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \\/var\\/www\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#10 \\/var\\/www\\/owncloud\\/remote.php(138): require_once('\\/var\\/www\\/ownclo...')\n#11 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360,\"User\":\"C96C88E4-9F71-4E45-9D6D-4FF46F01AEB6\"}","level":4,"time":"2016-06-10T12:45:34+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/community.txt","user":"C96C88E4-9F71-4E45-9D6D-4FF46F01AEB6"}

**Comment by rperezb** [comment]
just for reference, @jesmrec checked both apps iOS and Android, on neither of them this issue has been reproduced
further details on https://github.com/owncloud/ios/issues/701

**Comment by team-alpeinsoft** [comment]
> just for reference, @jesmrec checked both apps iOS and Android, on neither of them this issue has been reproduced
further details on owncloud/ios#701

Thx!

**Comment by davivel** [comment]
After reading all the details in owncloud/ios#701, I'm afraid there is not much that can be done on the client side. The only specific difference I can think of about the Android app that could be related is that it sends user credentials in every request to the server (no session cookie). But if that was a factor here, the problem wouldn't appear in the iOS app too.

My estimation is that there was some problem in the server upgrade process.

**Comment by michaelstingl** [comment]
Should be fixed with oC server 9.1.1+. Please report if server upgrade don't solve the problem.
