### ISSUE TITLE
Distinguish between users with the same display name in share view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1716]
If two users have the same display name, can not be distinguished in share view. In this case, the username should be indicated to know who is who.

![screen shot 2016-06-16 at 09 28 37](https://cloud.githubusercontent.com/assets/14894746/16108758/68ee6aaa-33a5-11e6-8135-a388afd71a41.png)

![screen shot 2016-06-16 at 09 31 10](https://cloud.githubusercontent.com/assets/14894746/16108759/6a55f6e2-33a5-11e6-90ba-db22c8616f23.png)

To take in account: users in trusted federated servers with the same display name

**Comment by davivel** [comment]
Is this handled right now in iOS? How is it?

**Comment by jesmrec** [comment]
in iOS is already hadled:

- If two (or more) users in the same server have the same display name, is shown the username (search view, share view): 

![screen shot 2016-06-16 at 12 35 00](https://cloud.githubusercontent.com/assets/14894746/16113905/e7b0886e-33be-11e6-953f-3f13611d8811.png)
![screen shot 2016-06-16 at 12 36 16](https://cloud.githubusercontent.com/assets/14894746/16113921/f826e0b2-33be-11e6-8dc7-b9dd48b1216e.png)

- In there are users with the same display name in different (trusted) servers, is shown boy the user name and the server:

![screen shot_share1](https://cloud.githubusercontent.com/assets/14894746/16114753/39256986-33c3-11e6-92d0-752e7421a4e3.gif)

The additional info is only shown if there are matching display names. In any other case, the behaviour is the current one

**Comment by davivel** [comment]
OK, I remember now; thanks

**Comment by jesmrec** [comment]
issue moved to https://github.com/owncloud/android/issues/2284
