### ISSUE TITLE
Add welcom activity when user is first entered owncloud

### ISSUE THREAD

**Issue by payma** [owncloud/android#1717]
### Actual behaviour

 hello every body!
 I want to add welcome activity when user is first authorized and entered owncloud root folder, such as welcome of owncloud website. 
I found one function ( checkBasicAuthorization()) from AuthenticatorActivity which do authorization.  when user's authorization is done, direct user to his root folder  (accessRootFolder(credentials);) .
 but this function is very complex!   this function validate credentials accessing the root folder. this 
function doesn't have an implementation and is a final method of an abstract class AsyncTask<Params, Progress, Result>!! 
 I want to see where user's Authorization is OK and access to root folder. so I can add there
my activity   to welcome user at first.
### Expected behaviour

 I want to add welcome activity when user is first authorized and entered owncloud root folder, such as welcome of owncloud website.

**Comment by AndyScherzinger** [comment]
This is mostly covered in #1375 which would work for initial start and any app version update, cc @rperezb

**Comment by davigonz** [comment]
Closing as duplicated of https://github.com/owncloud/android/issues/1104, follow up there.
