### ISSUE TITLE
"Select all" files option in multiselection mode

### ISSUE THREAD

**Issue by jabarros** [owncloud/android#1727]
In #1176 multi select feature was developed and to avoid wasting time selecting all files in a folder one by one, an option to select all the files in a folder is necessary. This will let us select all files in a unique click.

**Comment by davivel** [comment]
An option in the overflow menu should be enough.

**Comment by sd1998** [comment]
Is anyone working on this?

**Comment by davigonz** [comment]
> Is anyone working on this?

@sd1998 No, contributions are welcome 😉

**Comment by sd1998** [comment]
@davigonz I would like to work on this.

**Comment by jesmrec** [comment]
@sd1998 for me it is ok, go on!! first of all, we should agree the way it is going to be displayed. I think in several options:

- Set a global checkbox in multiselection mode. By selecting it, all checkboxes will be selected 
- Set an option in tool bar or three-dot-menu to select all the stuff. 

Also, it would be cool to include an additional option to "deselect" all the stuff

If you are going to work on this, maybe is a good idea to create mock-ups before starting to be sure if all are on the same page, and we agree in the UI.

**Comment by sd1998** [comment]
@jesmrec I will add the mockups here is some time. I think the second options will be better and I think that the option in three-dot-menu should only be available if the user has already selected an item(i.e is already in multiselection mode).

**Comment by sd1998** [comment]
@jesmrec I have made the mockup. The mockup is not very good as I still learning to make these so Sorry for the inaccuracy to replicate the UI completely but the mockup still represents vaguely the option in tree-dot menu to select all the items and deselect all the items. Is this type of representation of the options ok?

![image](https://user-images.githubusercontent.com/22047421/41172486-a2b2282a-6b71-11e8-829c-afbca308b2a7.png)

**Comment by sd1998** [comment]
@jesmrec Is [this](https://github.com/owncloud/android/issues/1727#issuecomment-395836030) alright? If it is then I will start working on it.

**Comment by jesmrec** [comment]
looks good for me. Are he options "Select all" and "Deselect all" always in the three-dot-menu, and not in the toolbar (although there is room for this)? 

CC @davigonz @michaelstingl

**Comment by davigonz** [comment]
Thanks @sd1998 for the mockup, I have a couple of questions:
1. Does the option **select all** appear when the user has already selected one or more files or when there's no one selected? In my opinion it could appear in both cases.
2. Does the option **deselect all** make sense when there's no file selected? Think it should appear just when the **select all** option is being used.

What do you think?

**Comment by sd1998** [comment]
@davigonz Yes I agree with this. I will implement it this way.

**Comment by sd1998** [comment]
@jesmrec Yes I just checked there is enough space so I think it would be better to add the select all icon on the toolbar and the deselect option to be in the three dot menu. What do you think?

**Comment by jesmrec** [comment]
which icon will you use in the tool bar for "Select all"? I like the 1. approach of @davigonz

**Comment by sd1998** [comment]
I have though of using this 
![image](https://user-images.githubusercontent.com/22047421/41464573-7c031558-70b8-11e8-9d45-512b2bcf2969.png)

So the select all option should be visible even when the iser has not select a single file?

**Comment by theScrabi** [comment]
It's not bad since its the one that is listed when you search for an Icon corresponding to that option.
I somehow don't like it tho.

@sd1998 what do you think about this icon here? Do you like it?
![check-all 1](https://user-images.githubusercontent.com/1891273/41465025-ab45e578-709c-11e8-8b30-b54cb9927ff4.png) ![check-all 2](https://user-images.githubusercontent.com/1891273/41465051-bcc35cea-709c-11e8-8d0d-20d751cf4840.png)

**Comment by sd1998** [comment]
@theScrabi  Yes it is ok. I have another alternative.
![image](https://user-images.githubusercontent.com/22047421/41465894-9e1f6ee8-70bd-11e8-8770-46092b10ce2c.png)
I found this [here](https://material.io/tools/icons/?style=baseline)
What do you think about this? Or should I go with the one you have suggested.

**Comment by jesmrec** [comment]
this icon is very close to the "Move" icon. For deselecting... any idea? or will not be never placed in toolbar ?

**Comment by theScrabi** [comment]
The problem is that all these `select all` icons are verry abstract, and there is not a "commonly known" icon for select all, So I wouldn't recommend using only the icon. I'd recommend to put at least a text beside of it, so no toolbar.

**Comment by sd1998** [comment]
@theScrabi I agree. So I will be adding the option in the three dot menu.
