### ISSUE TITLE
No refresh when app starts

### ISSUE THREAD

**Issue by atsag** [owncloud/android#1729]
### Actual behaviour

Sometimes when the application starts the root folder is not refreshed, and a manual refresh is required. This is verified, because execution will not enter the if(hasWindowFocus()) statement in startSyncFolderOperation method in FileDisplayActivity.java. The issue cannot be reproduced every time. Increasing the delay applied to the runnable, for example to DELAY_TO_REQUEST_OPERATIONS_LATER + 500 fixes the problem. 
### Expected behaviour

The application should refresh the root folder when it is started.
### Steps to reproduce
1. Compile the application
2. Start the owncloud application a good number of times, at least 10.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
YES
### Environment data

Android version:
4.0.4
Device model: 
Xperia Arc
Stock or customized system:
Cyanogenmod 9.1.0
ownCloud app version:
2.0.1
ownCloud server version:
9.0.2 (irrelevant, can be reproduced with 8.2)
#### ownCloud log (data/owncloud.log)

...
07-01 13:36:31.699 2240-2240/com.owncloud.android I/ActivityThread: Pub com.owncloud.android.providers.UsersAndGroupsSearchProvider: com.owncloud.android.providers.UsersAndGroupsSearchProvider
07-01 13:36:31.699 2240-2240/com.owncloud.android I/ActivityThread: Pub org.owncloud: com.owncloud.android.providers.FileContentProvider
07-01 13:36:31.709 2240-2240/com.owncloud.android D/Debug: start logging
07-01 13:36:31.759 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.content.Intent.getClipData, referenced from method com.owncloud.android.ui.activity.FileDisplayActivity.requestUploadOfContentFromApps
07-01 13:36:31.759 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 404: Landroid/content/Intent;.getClipData ()Landroid/content/ClipData;
07-01 13:36:31.759 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x000d
07-01 13:36:31.759 2240-2240/com.owncloud.android E/dalvikvm: Could not find class 'android.content.SyncRequest$Builder', referenced from method com.owncloud.android.ui.activity.FileDisplayActivity.startSynchronization
07-01 13:36:31.769 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve new-instance 90 (Landroid/content/SyncRequest$Builder;) in Lcom/owncloud/android/ui/activity/FileDisplayActivity;
07-01 13:36:31.769 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x22 at 0x00ab
07-01 13:36:31.799 2240-2240/com.owncloud.android D/dalvikvm: DexOpt: unable to opt direct call 0x01d6 at 0xad in Lcom/owncloud/android/ui/activity/FileDisplayActivity;.startSynchronization
07-01 13:36:31.809 2240-2240/com.owncloud.android V/FileDisplayActivity: onCreate() start
07-01 13:36:31.809 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
07-01 13:36:31.809 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
07-01 13:36:31.809 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve interface method 18358: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
07-01 13:36:31.819 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
07-01 13:36:31.819 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
07-01 13:36:31.819 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve interface method 18362: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
07-01 13:36:31.819 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
07-01 13:36:31.829 2240-2240/com.owncloud.android D/FileDisplayActivity: onCreate(Bundle) starting
07-01 13:36:31.889 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.view.ViewGroup.onWindowSystemUiVisibilityChanged, referenced from method android.support.v7.widget.ActionBarOverlayLayout.onWindowSystemUiVisibilityChanged
07-01 13:36:31.889 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 18257: Landroid/view/ViewGroup;.onWindowSystemUiVisibilityChanged (I)V
07-01 13:36:31.889 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6f at 0x0008
07-01 13:36:31.939 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.view.ViewGroup.onRtlPropertiesChanged, referenced from method android.support.v7.widget.Toolbar.onRtlPropertiesChanged
07-01 13:36:31.939 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 18253: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
07-01 13:36:31.939 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6f at 0x0007
07-01 13:36:31.949 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
07-01 13:36:31.949 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 567: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
07-01 13:36:31.949 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
07-01 13:36:31.949 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
07-01 13:36:31.949 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 589: Landroid/content/res/TypedArray;.getType (I)I
07-01 13:36:31.949 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
07-01 13:36:32.069 2240-2240/com.owncloud.android W/ActionBarDrawerToggle: DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
07-01 13:36:32.079 2240-2240/com.owncloud.android V/FileDisplayActivity: onCreate() end
07-01 13:36:32.079 2240-2240/com.owncloud.android V/FileDisplayActivity: onStart() start
07-01 13:36:32.079 2240-2240/com.owncloud.android D/FileDisplayActivity: onStart() starting
07-01 13:36:32.119 2240-2240/com.owncloud.android D/FileDisplayActivity: Initializing Fragments in onAccountChanged..
07-01 13:36:32.119 2240-2240/com.owncloud.android A/FileDisplayActivity: Access to unexisting list of files fragment!!
07-01 13:36:32.129 2240-2240/com.owncloud.android E/FileDisplayActivity: Still have a chance to lose the initializacion of list fragment >(
07-01 13:36:32.159 2240-2240/com.owncloud.android V/FileDisplayActivity: onStart() end
07-01 13:36:32.159 2240-2240/com.owncloud.android A/FileDisplayActivity: Access to unexisting list of files fragment!!
07-01 13:36:32.169 2240-2240/com.owncloud.android E/FileDisplayActivity: OCFileListFragment is null
07-01 13:36:32.169 2240-2240/com.owncloud.android V/FileDisplayActivity: onResume() start
07-01 13:36:32.179 2240-2240/com.owncloud.android D/FileDisplayActivity: onResume() starting
07-01 13:36:32.189 2240-2240/com.owncloud.android E/OCFileListFragment: onAttach
07-01 13:36:32.189 2240-2240/com.owncloud.android I/OCFileListFragment: onCreateView() start
07-01 13:36:32.189 2240-2240/com.owncloud.android D/ExtendedListFragment: onCreateView
07-01 13:36:32.219 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.widget.GridView.getColumnWidth, referenced from method third_parties.in.srain.cube.GridViewWithHeaderAndFooter.getColumnWidthCompatible
07-01 13:36:32.219 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 18922: Landroid/widget/GridView;.getColumnWidth ()I
07-01 13:36:32.219 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6f at 0x0006
07-01 13:36:32.239 2240-2240/com.owncloud.android I/dalvikvm: Could not find method com.getbase.floatingactionbutton.FloatingActionButton.setBackground, referenced from method com.getbase.floatingactionbutton.FloatingActionButton.setBackgroundCompat
07-01 13:36:32.239 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 19450: Lcom/getbase/floatingactionbutton/FloatingActionButton;.setBackground (Landroid/graphics/drawable/Drawable;)V
07-01 13:36:32.239 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
07-01 13:36:32.289 2240-2240/com.owncloud.android I/OCFileListFragment: onCreateView() end
07-01 13:36:32.289 2240-2240/com.owncloud.android E/OCFileListFragment: onActivityCreated() start
07-01 13:36:32.369 2240-2240/com.owncloud.android V/FileDisplayActivity: onResume() end
07-01 13:36:32.379 2240-2240/com.owncloud.android D/HardwareRenderer: Disabling v-sync
07-01 13:36:32.379 2240-2240/com.owncloud.android D/OperationsService: Creating service
07-01 13:36:32.389 2240-2240/com.owncloud.android D/FileDownloader: Creating service
07-01 13:36:32.419 2240-2240/com.owncloud.android D/FileUploader: Creating service
07-01 13:36:32.419 2240-2240/com.owncloud.android V/UploadsStorageManager: Updating state of any killed upload
07-01 13:36:32.439 2240-2240/com.owncloud.android V/UploadsStorageManager: No upload was killed
07-01 13:36:32.439 2240-2240/com.owncloud.android D/FileObserverService: onCreate
07-01 13:36:32.449 2240-2240/com.owncloud.android D/FileObserverService: Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.owncloud.android/.services.observer.FileObserverService }
07-01 13:36:32.449 2240-2240/com.owncloud.android D/FileObserverService: Loading all kept-in-sync files from database to start watching them
07-01 13:36:32.529 2240-2240/com.owncloud.android D/libEGL: loaded /system/lib/egl/libGLES_android.so
07-01 13:36:32.539 2240-2240/com.owncloud.android D/libEGL: loaded /system/lib/egl/libEGL_adreno200.so
07-01 13:36:32.539 2240-2240/com.owncloud.android D/libEGL: loaded /system/lib/egl/libGLESv1_CM_adreno200.so
07-01 13:36:32.549 2240-2240/com.owncloud.android D/libEGL: loaded /system/lib/egl/libGLESv2_adreno200.so
07-01 13:36:32.589 2240-2240/com.owncloud.android D/OpenGLRenderer: Enabling debug mode 0
07-01 13:36:32.589 2240-2240/com.owncloud.android W/Adreno200-EGLSUB: SetSwapInterval() interval: 0 not set
07-01 13:36:32.639 2240-2240/com.owncloud.android I/dalvikvm: Could not find method android.widget.SeekBar.getThumb, referenced from method com.owncloud.android.utils.DisplayUtils.colorPreLollipopHorizontalSeekBar
07-01 13:36:32.639 2240-2240/com.owncloud.android W/dalvikvm: VFY: unable to resolve virtual method 19259: Landroid/widget/SeekBar;.getThumb ()Landroid/graphics/drawable/Drawable;
07-01 13:36:32.639 2240-2240/com.owncloud.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x001c
07-01 13:36:32.919 2240-2240/com.owncloud.android D/FileActivity: Operations service connected
07-01 13:36:32.919 2240-2240/com.owncloud.android D/FileDisplayActivity: Download service connected
07-01 13:36:32.999 2240-2240/com.owncloud.android D/FileDisplayActivity: Upload service connected
07-01 13:36:33.079 2240-2267/com.owncloud.android D/ThumbnailsCacheManager: create dir: /mnt/sdcard/Android/data/com.owncloud.android/cache/thumbnailCache

```
```

**Comment by davivel** [comment]
Hi, @atsag .

> Increasing the delay applied to the runnable, for example to DELAY_TO_REQUEST_OPERATIONS_LATER + 500 fixes the problem.

So, would you say that increasing 500 ms would be the right amount? Did you other amounts?

> Start the owncloud application a good number of times, at least 10.

How many times of those 10 is failing to refresh the app?

**Comment by atsag** [comment]
Well i just tried it in Android Studio once more, with an emulator. Of the 40 times that I chose 'ReRun Selected Configuration' I noticed that the problem appeared only twice. I tried it in my Xperia Arc and the problem appeared nine out of ten. So I set about finding the delay that would solve the problem for Arc as it was more reproducible. Adding various delays, to the runnable in startSyncFolderOperation of FileDisplayActivity the following table can be constructed:

Added Delay (ms)  |  Successful Refresh (dotted animation appearing on startup)
------------ | -------------
50           |                    0/10
100         |                    0/10  
150         |                    2/10  
200         |                    7/10  
250         |                    7/10  
300         |                    9/10  
350         |                    10/10

**Comment by davivel** [comment]
Really interesting, @atsag. Thanks for the detailed study.

Would you like to contribute a PR with the fix? :)

**Comment by atsag** [comment]
You are welcome @davivel. It is very fulfilling to aid this project. I added 350ms to the delay, which seems a minimum according to the above tests - but this can be edited. The pull request is https://github.com/owncloud/android/pull/1753 .

**Comment by davigonz** [comment]
Hi @atsag , is this already fixed after applying the https://github.com/owncloud/android/pull/1765 changes? Can we close this then?

**Comment by jesmrec** [comment]
@atsag still reproducible?

**Comment by atsag** [comment]
@jesmrec @davigonz  Sorry for the delay - no, the bug was fixed right after the #1765 changes.
