### ISSUE TITLE
Client not tolerant of file being deleted while it's uploading to InstantUpload 

### ISSUE THREAD

**Issue by nneul** [owncloud/android#1730]
Took a short video, and then deleted it. I believe I must have done the delete right after OC client started to auto-upload it.

Client right now in notification bar showing "-202776000% Uploading ...."

It's also not clear to me that it's even going to finish/terminate. It appears to have stopped crazily updating the percentage, but is also still just sitting there saying it's uploading.

**Comment by jesmrec** [comment]
@nneul i can reproduce it and the video finished to be updated and can be downloaded and played.

We will take it in account. Thanks!

**Comment by davivel** [comment]
Hi, @nneul .

> It's also not clear to me that it's even going to finish/terminate. ...  is also still just sitting there saying it's uploading.

As of today, what happened with the notification? Still in place? Did you / could you remove it?

What did you expect should have happened when you deleted the file? Thanks.

**Comment by nneul** [comment]
I think I cancelled it, but not sure at this point (was on vacation and not paying close attention), sorry.

I think the main thing I would have expected is for the size reporting to have a reasonable value, or switch to showing just bytes transferred if it can no longer calculate percentage. Since it appears to be tolerant of deletion (this is good I think) - at least the display should be corrected.  (There's also something to be said for having it only check size once -- does OC actually tolerate the file size increasing DURING the upload process?)

However, I can also see some justification for: If it's going to continuously check the size - it might be worthwhile to note the deletion and abort the transfer. (I can also see the opposite - OC could protect against an accidental deletion if the upload was already in progress...) No strong opinion on the behavior choice - but the UI shouldn't display a gibberish percentage when it doesn't know the file size any more. 

Another option - grab the file size continuously as you are now, but cache the last successful one. If you can no longer determine the size, use the cached value going forward, but highlight that it's out of date in the progress UI in some manner.

**Comment by nneul** [comment]
"does OC actually tolerate the file size increasing DURING the upload"

What I mean by that is - what's the end result - is it a corrupted upload that has to be repeated, or does it get the final file content fully uploaded in the first pass?

**Comment by davivel** [comment]
> What I mean by that is - what's the end result - is it a corrupted upload that has to be repeated, or does it get the final file content fully uploaded in the first pass?

I couldn't say from memory, probably the option selected for the behaviour after uploading (move to OC folder or leave alone) can change the result too.

Thanks a lot for you feedback :)

**Comment by michaelstingl** [comment]
I'd assume this issue is gone. (`InstantUpload` got replaced by `CameraUpload`) In case this happens again, please open a new issue. (too many things changed)
