### ISSUE TITLE
App crashes browsing with grid view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1731]
### Steps to reproduce
1. Create a new folder
2. Browse into the folder (do not upload anything)
3. Set Grid View
4. Tap on back arrow to browse parent folder

### Actual behaviour
App crashes

### Expected behaviour
App browses to parent folder
 
### Environment data
Android version: checked in 5 and 6

Device model: Nexus5 and Nexus 9

ownCloud app version: 2.0.1 and `master` branch

ownCloud server version: 9.0

**Comment by davivel** [comment]
Party time!

**Comment by TroyStopera** [comment]
Seems like it may be the same as #1447.

**Comment by davivel** [comment]
Yes, it's duplicated. Let's track it in the other, where there are more participants.
