### ISSUE TITLE
Unable to get three dots button on Samsung Galaxy Tab 3 and Android 4.4.2 on details view

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/android#1738]
### Actual behaviour
- We are not able to see three dots button on details view due to Samsung Galaxy tab 3 has an extra button for options that seems to be not working fine with 4.4.2 Android version
### Expected behaviour
- Three dots buttons should appear on details view on any device or android version possible.
### Steps to reproduce
1. On a file long press and select details view
### Environment data

Android version: 4.4.2

Device model: Samsung Galaxy Tab 3

ownCloud app version: 2.1.0

ownCloud server version: 9.1.0 RC1

**Comment by davivel** [comment]
Even further: three dots menu is not shown at all in the list of files in this device.

Relevant detail: the tablet has a hardware MENU button, that is unexpected in an Android 4.4.2 device.

**Comment by michaelstingl** [comment]
@jesmrec Could you have another look with current Android tablets?

**Comment by jesmrec** [comment]
4.4.2 not supported anymore. Nor reproducible nowadays
