### ISSUE TITLE
Error in res/values/strings.xml

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/android#1741]
Pushing translations for resource owncloud.android:
Pushing source file (res/values/strings.xml)
Exception: Could not import file: Bad '<plurals>' element in line number 459. The plurals element in the uploaded content has 3 plural forms but language 'English (en)' requires 2 plural forms.

**Comment by davivel** [comment]
So, this is an error in Transifex, right?

**Comment by DeepDiver1975** [comment]
> So, this is an error in Transifex, right?

at the end - yes

**Comment by davivel** [comment]
I tried to file an issue to Transifex, but didn't find where.
