### ISSUE TITLE
Update copyright 

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1751]
Update Copyright to 👍 
```
@copyright Copyright (c) 2016, ownCloud GmbH. 
```

Related to: https://github.com/owncloud/core/pull/25518

**Comment by davivel** [comment]
Seen. Should go in next release.

**Comment by davivel** [comment]
Moreover, should be done as part of the tasks preparing the release, once created the branch release-2.1.0

**Comment by davivel** [comment]
This is now done in release-2.1.0 branch; see #1750 to track the progress of the release
