### ISSUE TITLE
Edit options in federated sharing

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1758]
Android app does not handle the three edit options (create, change, delete) in federated sharing for folders.

Server v9.1 (not previous) already does it, so it is a needed improvement.

Related iOS issue: https://github.com/owncloud/ios/issues/751

edited by @jabarros
- [x] Create 'federated_sharing_edit_options' branch from master in android repository @jabarros
- [ ] Merge 'federated_sharing_edit_options' branch into master
- [x] Handle create, change and delete options in federated sharing in servers 9.1 or up @jabarros
- [X] Create test plan @jesmrec 
- [X] Validate test plan @jesmrec

**Comment by jabarros** [comment]
@jesmrec, it is available on #1813

**Comment by jesmrec** [comment]
Server issue https://github.com/owncloud/core/issues/26173 blocks the test related to individual subpermissions.

**Comment by jesmrec** [comment]
Server issue https://github.com/owncloud/core/issues/26173 is already fixed, so we can resume the work here.

**Comment by jesmrec** [comment]
approved.
