### ISSUE TITLE
Lock (Passcode required) delayed after closing the app.

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#1760]
### Actual behaviour
If I close the app and open it again after immediately, it isn't locked. (Passcode not required)

### Expected behaviour
The app should be locked immediately
 
### Steps to reproduce
1. set Passcode
2. close app
3. open app immediately after closing

### Environment data
Android version:
5.1.0

Device model:
Google Nexus 4

Stock or customized system:
Stock

ownCloud app version:
2.0.1

ownCloud server version:
9.1.0

@davivel Could this be improved? /cc @rperezb @dercorn 

00005936

**Comment by jesmrec** [comment]
i can reproduce it. Something to be reviewed ... thanks @michaelstingl

**Comment by LukeOwncloud** [comment]
Might be by design. https://github.com/owncloud/android/issues/257

**Comment by davivel** [comment]
As @LukeOwncloud said, there is an intended delay of 1 second between exit of the app an passcode activation. Was introduced to avoid annoying the user if "just left the app and forgot something".

What are the risks of leaving it as it is?

**Comment by davivel** [comment]
Another reason to keep that delay is preventing that the passcode is requested when the user rotates the device.

**Comment by jesmrec** [comment]
The point is that you can only reproduce the problem if you are in the app. In this case, you must know the passcode. Besides of that, avoiding the delay the usability of the app decreases with the asking of the passcode that @davivel mentioned. 

I would let it be.

**Comment by michaelstingl** [comment]
Thanks!

**Comment by davivel** [comment]
I think we can close then. :)
