### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by hansen0730** [owncloud/android#1762]
ExtendedListFragment.onCreateView()

mProgressBar = (ProgressBar) v.findViewById(R.id.syncProgressBar);

**mProgressBar is null,**

so setProgressBarAsIndeterminate method crash.

Need remove **merge** block in res/layout/top_progress_bar.xml.

**Comment by davivel** [comment]
This is already fixed in branch release_2.1.0

For future reports, please, set a meaningful title and give appropriate context. I only could guess what you are talking about because I fixed the problem last week.
