### ISSUE TITLE
Error message for Insufficient Storage error

### ISSUE THREAD

**Issue by ehannes** [owncloud/android#1767]
### Actual behaviour

I have enabled automatic image upload on my Android owncloud app. Suddenly I got `Unknown error` and the image could not be uploaded. When I looked at the server error log, I read the actual error message: `507 Insufficient Storage`.
### Expected behaviour

Why is not the server error used, which explains exactly what is going on. `Unknown error` is not very descriptive.
### Steps to reproduce
1. Enable automatic image upload on your Android app
2. Set a too low quota on the server
3. Take a picture with your phone and wait for the automatic image upload

I don't know if this problem is specific to the photo upload. Maybe it concerns all upload when there is no space available.
### Environment data

Android version: Android 5

Device model: Huawei Honor 7

Stock or customized system: Stock

ownCloud app version:2.0.1

ownCloud server version: 9.0.3
#### ownCloud log (data/owncloud.log)

```
Exception: {"Message":"HTTP\/1.1 507 Insufficient Storage","Exception":"Sabre\\DAV\\Exception\\InsufficientStorage","Code":0,"Trace":"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota('photos\/Honor 7\/...', Resource id #31, Object(OCA\\DAV\\Connector\\Sabre\\Directory), false)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('photos\/Honor 7\/...', Resource id #31, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#10 {main}","File":"\/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/quotaplugin.php","Line":108,"User":"filtered_user_name"}
```

**Comment by davivel** [comment]
> Why is not the server error used, which explains exactly what is going on. 

We don't show server errors as a general rule because HTTP error messages don't always explain in an user-understandable language what is going on, and because error messages are not internationalized.

We could consider using them just in the case of "Unknown error"s.

In any case, we need to improve this concrete error message, and some others.

**Comment by jesmrec** [comment]
Approved
