### ISSUE TITLE
View Images before downloading

### ISSUE THREAD

**Issue by Qhiliqq** [owncloud/android#1769]
Is it possible to live view images and docs on the app, like the browser version?

Images only can viewed with a green tick... 
That would be very nice :)

Regards :)

//EDIT:
Missing only the fullscreen view, middlebig view is already included...

**Comment by davivel** [comment]
Duplication of #714 
Work in progress in #1599, right now blocked due to work in progress in server.
Please, see any progress in those issues before.

**Comment by Qhiliqq** [comment]
Excuse me for the duplication.

Is this also for iOS in progress?

**Comment by davivel** [comment]
Nothing to excuse, it's pretty normal :)

About iOS, not that I am aware of.

**Comment by Qhiliqq** [comment]
Okay :)

My girlfriend is killing me :D I use OC on android and the app has more features than the ios app :crown: 

But thanks for your answer :+1:
