### ISSUE TITLE
No Photo/video upload for Android 7 (Android n preview 5)

### ISSUE THREAD

**Issue by mvletter** [owncloud/android#1773]
### Actual behaviour
Installed owncloud 2.1 for Android on Nexus 5X running Android 7 NPD90G build (beta 5). Set up the client and it connects and shows all the dirs. Gave the app permission to access the Photo's.  Enabled direct uploads, set it to a proper directory, but it won't start uploading.

### Expected behaviour
It should start uploading
 
### Steps to reproduce
1. Grab an Android 7 beta phone
2. Download Owncloud 2.1 for Android
3. Set up your account in the app 
4. Enable direct uploads
5. Snap a picture

Can this problem be reproduced with the official owncloud server?
YEs

### Environment data
Android version: NPD90G 

Device model: Nexus 5X

Stock or customized system: Stock

ownCloud app version: 2.1

ownCloud server version: Using the TransIP version called Stack. Version unknown.

#### Web server error log
Na

#### ownCloud log (data/owncloud.log)
Na

**Comment by davivel** [comment]
Duplicating #1675. Please, track any progress there or in #6, that with solve at the same time this issue and the lack of instant pictures with camera apps currently not supported.
