### ISSUE TITLE
Manual photo upload from DCIM folder broken on Android N

### ISSUE THREAD

**Issue by AndyScherzinger** [owncloud/android#1774]
Android N Preview 5 on a Nexus5X:
You can't upload photos from the camera (DCM folder) anymore manually. For some reason the images are detected as folders (which they are not). Images in other folders are detected as photos though.

![device-2016-08-17-190625](https://cloud.githubusercontent.com/assets/1315170/17745938/2d10dc68-64ae-11e6-920a-4b99bf62f7b6.png)

**Comment by davivel** [comment]
O_o

Checking. Thanks, @AndyScherzinger

**Comment by davivel** [comment]
?

I just checked with master. I see the pictures correctly.

Do you have any strange log?

**Comment by davivel** [comment]
Hey, it's with images taken with the Camera app **after** the upgrade to preview 5.

Google, what have you done...

**Comment by davivel** [comment]
Something smell broken. Fx File Explorer also shows them as folders.

**Comment by davivel** [comment]
And ```java.io.File#isDirectory()``` returns true. Besides, the name has no extension.

Something has changed in the ```MediaService```, or Google just introduced an awesome bug.

**Comment by davivel** [comment]
```OpenCamera``` pictures are fine. ```Google Camera``` error?

**Comment by davivel** [comment]
Hey! Could you scroll down, please? Pictures are also there. Google Camera is creating both an image file and a folder with the same name but no extension.

Could you confirm it's the same for you?

**Comment by AndyScherzinger** [comment]
Hi @davivel I can confirm your findings. There are pictures and folders. One idea seams Google creates them for HDR   processed photos. Not sure though. Still a very weird behavior...  :S

**Comment by davivel** [comment]
> Still a very weird behavior

It is, but one of Google Camera, not something that we should fix. 

I will close this. We can reopen if other issues related appear.
