### ISSUE TITLE
use correct emojs in repo description

### ISSUE THREAD

**Issue by treaki** [owncloud/android#1777]
![160821shot](https://cloud.githubusercontent.com/assets/1477872/17839575/320ba22a-67ec-11e6-8c3b-b1cab87f060f.png)

if you have to use this modern nonsense then you should at least use 
📱 (U+1F4F1 Mobile Phone) or 🖁 instead of this unbefitting fixed-line telephone

**Comment by treaki** [comment]
github incorrectly called that a iphone...

**Comment by davivel** [comment]
Sorry, but this is useless.
