### ISSUE TITLE
improve app pin function

### ISSUE THREAD

**Issue by treaki** [owncloud/android#1778]
Hi,

first of all you should separate the settings for if i can take screen shots and if i want to type in a pin when i open up the app. and secondly you shouldn't ask for pin whenever the user switches back into the app. thats not security, thats annoyance of the user. Have a look at Threema ( threema.ch ) they are doing it the right way. The possibility to use the system pin stead of a seperate one for this app is also nice.

regards

**Comment by davivel** [comment]
The current operation for the passcode has been deeply discussed and modified before. The change you propose goes against the requirements of other users, that expect it is shown no matter what other app one comes from.

In any case, we'll have a look at Threema when possible to see how they handle it, as you suggest.

**Comment by jesmrec** [comment]
Many improvements already done. To avoid annoyance, you can use the lock delay feature.
