### ISSUE TITLE
New OCS request and handler

### ISSUE THREAD

**Issue by daorte** [owncloud/android#1781]
### Actual behaviour
- Using Fiddler with new android 2.1.0, i can see there are new request to `/owncloud/index.php/ocs/cloud/user?format=json` with `index.php` acting as a handler of `/ocs/cloud/user` requests.

But, there are other requests to `ocs` like `/owncloud/ocs/v1.php/cloud/capabilities?format=json`  and `/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=/&reshares=true&subfiles=true` that does not uses `index.php` as handler, these old ones uses `v1.php`.

Why not to use the same `v1.php` to handle `/cloud/user` requests or create a new handler inside `ocs` folder and get in one place all the ocs controllers?

### Environment data
ownCloud app version: android 2.1.0

ownCloud server version: 9.1.0.15

**Comment by davivel** [comment]
Hey, good point. Could you please could you please close this issue and open it in the library repo at https://github.com/owncloud/android-library ? That's the affected component.

Thanks.

**Comment by daorte** [comment]
Done, the issue is  [https://github.com/owncloud/android-library/issues/132](url)
