### ISSUE TITLE
OC Android App on Android 7.0 - Instant Picture Upload Not Triggering

### ISSUE THREAD

**Issue by mrjester888** [owncloud/android#1784]
### Actual behaviour
After upgrading to Android 7.0 on my n5x, OC Android is no longer running Instant Picture Upload.  This was working prior to OS upgrade.

### Expected behaviour
Pictures taken by the camera and is uploaded automatically.
 
### Steps to reproduce
1. Install OC Android App
2. Configure Account
3. Enable Instant Picture Upload
4. Take a picture

Can this problem be reproduced with the official owncloud server?  Yes.  Connected to demo server, IPU did not trigger.

### Environment data
Android version: 7.0 NRD90M
Device model: Nexus 5x
Stock or customized system:  Stock
ownCloud app version: 2.1.0
ownCloud server version: ownCloud 9.1.0 (stable)

#### Web server error log
```
Set logs to info.  No web server logs during this testing.
```
#### ownCloud log (data/owncloud.log)
```
No data server logs during this testing.
```

**Comment by mrjester888** [comment]
Manual upload works fine.  Noticed that the camera app now creates a folder with the same name as the image.

**Comment by davivel** [comment]
Thanks, @mrjester888 . 

We are already tracking this in https://github.com/owncloud/android/issues/1675 (see first checkbox at the bottom of the first comments), so I will close this issue as a duplication.

The good new is we are right now testing the fix here: https://github.com/owncloud/android/pull/1783.

We expect to release this fix very, very soon.
