### ISSUE TITLE
Instant uploads in Samsung Galaxy Note4 with default camera

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1786]
### Steps to reproduce
1.  Enable instant uploads and set the camera folder with default google camera
2. Take some photos/videos

### Actual behaviour
Anything is uploaded

### Expected behaviour
All the content is uploaded
 

### Environment data
Android version: 6.0.1

Device model: 

Samsung Galaxy Note 4. 
Model number SM-N910F
Security Patch Level: 1 July 2016
Kernel version: 3.10.40-7733605

Camera app: default Samsung camera, version 3.0

ownCloud server version: 9.1

Checked in other Android versions, Samsung devices, camera apps and the problem does not happen.

It seems to be a problem related with the storage location from camera and photo/video taken

Notice this device doesn't have slot for SD Card; due to that, the app stores always files in main storage, and the option in the app to select storage volume is disabled.

**Comment by marmaro** [comment]
Hi,

same problem with Oneplus One. Android 6.0.1. Security patch level 1 september 2016.
It was working until version2.1

**Comment by davivel** [comment]
@marmaro, what camera app are you using? Could you please check that the new option "Camera folder" in ownCloud settings is pointing to the location where your camera app stores pictures?

Thanks.

**Comment by davivel** [comment]
Please, @marmaro , see https://github.com/owncloud/android/issues/1795#issuecomment-245196504 . 

@jesmrec , if you agree, this seems the same error as #1795. I would close this one, since the other has more info from more people.

**Comment by jesmrec** [comment]
i agree, the problem is the same. closing... we continue #1795
