### ISSUE TITLE
Moved files in instant uploads are removed locally in Nexus 5

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1787]
### Steps to reproduce
1.  Enable instant uploads
2. Select "move to app folder"
3. Take photos/videos
### Actual behaviour

Files are uploaded, marked as downloaded (green tick), but disappears immediatly after a refresh. Tapping on the file, is downloaded and not opened as it should.
### Expected behaviour

Moved files are uploaded to the server and remain downloaded in the device.
### Environment data

Android version: 6.0
Device model: Nexus 5  
Server version: 9.1

**Comment by davivel** [comment]
I think this is very closely related with #1658. Might have the same cause, but be different now due to slight changes in the way that files are copied/moved.

**Comment by davigonz** [comment]
@jesmrec could we check if this still happens with the new Camera uploads?

**Comment by jesmrec** [comment]
@davigonz currently i have not reproduced the problem in an Android 6 device. We can close here, and in the case the bug is reproducible again, reopen the issue.

Thanks
