### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by mase76** [owncloud/android#179]
Hi!
I cannot log in with the OC Android app.
I get an error with the url, that it is a bad server config.
I am using something like:
https://www.mydomain.org/owncloud/
The OC Web-IF and also the OC News app, caldav and carddav
sync on Android works as it should.

**Comment by davivel** [comment]
@mase76 , is this still a problem for you? Thanks in advance.

**Comment by mase76** [comment]
No, I still cannot log in.

**Comment by davivel** [comment]
Would you like to send the URL of your server (and a test account, if needed to reproduce the bug) to apps@owncloud.com ?

Thanks.

**Comment by mase76** [comment]
I have sent you a test account.

**Comment by davivel** [comment]
@mase76 , I just checked with version 1.6.2 of the Android app and the credentials you send, and the log in works fine.

Do you still have the same logs in Apache than before? Are you using non-ASCII characters in the password?

**Comment by mase76** [comment]
The login works, but the folder loading takes forever.
This in the apache log:
"HEAD /owncloud/remote.php/webdav/ HTTP/1.1" 200 -

**Comment by davivel** [comment]
What does exactly mean "takes forever"? Don't you ever see the list of files in the root folder, or it's just slower than you'd like?

In any case, that should be the target of a different issue. Thanks for closing.

**Comment by mase76** [comment]
The login seems to be successful. But then I only see the
loading circle. And that takes forever. The file list never
appears.
-- 
gpg: 383107c4
https://www.setho.org/people
