### ISSUE TITLE
Unable to connect via LAN (Mobile data works) to server with dynamic DNS

### ISSUE THREAD

**Issue by bolausson** [owncloud/android#1796]
### Actual behaviour
- The app is supposed to connect to https://home.domain.de/ which resolves to my home server (dynamic DNS). Instead of a connection I get "Couldn't establish connection". As soon as I turn off WLAN and use Mobile data, the connection is established and the client works flawless. https://home.domain.de/ works perfectly fine in a browser when using LAN or Mobile Data.

When I mistype the server name I get "Couldn't find host"

The Server https://home.domain.de/ is in the same networks as the mobile phone when WLAN is turned on.
### Expected behavior
- Client should connect to https://home.domain.de/ no matter if connected via LAN or Mobile Data
- Windows and Linux Clients connect flawlessly via LAN/WLAN/Elsewhere.
### Steps to reproduce
1. Enable WLAN on mobile phone
2. Try to connect to https://home.domain.de/ via owncloud client --> FAILS
3. Disable WLAN on mobile phone
4. Try to connect to https://home.domain.de/ via owncloud --> Success

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
- No
### Environment data

Android version:
- 5.0
- 6.0.1

Device model: 
- Samsung Galaxy Note 3
- Samsung Galaxy Note 7

Stock or customized system:
- Stock

ownCloud app version:
- 2.1.1
  ownCloud server version:
- 9.1.0
#### Web server error log

```
 Nothing, not even a connection attempt is shown in the logs
```
#### ownCloud log (data/owncloud.log)

```
Nothing :(
```

Any ideas why Linux/Windows clients can connect from outside my LAN and from within my LAN but not the ownCloud client on my mobile phone?

Greetings,
Bjoern

**Comment by 3c06d558-36fd-4740-913c-c4e11fc74b88** [comment]
Same here:
GSM-> working
WLAN-> not working 

But Firefox shows owncloud login, no matter if GSM ow WLAN. So it cannot be a misconfiguration. 

Then I deactivated IPv6 in the router (Fritz)
-> Tada: The owncloud app works with WLAN too.

So it's an IPv6 issue. And Firefox is connecting somehow different than the owncloud app.

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
