### ISSUE TITLE
Mobile clients should allow for auto sync of pre-existing pictures

### ISSUE THREAD

**Issue by rkarlsba** [owncloud/android#1797]
### Actual behaviour

-Tell us what happens

Connect a phone with a bunch of photos, and although new photos are uploaded, existing ones aren't and the only way to do so is manually choosing the lot, one by one, and upload them.
### Expected behaviour

-Tell us what should happen

Allow for automatic sync 
### Steps to reproduce
1. Connect phone with a lot of photos
2. Try to find a smart way to upload existing stuff
3. Give up and go back to dropbox

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
### Environment data

Android version: Irrelevant

Device model: Irrelevant

Stock or customized system: Irrelevant

ownCloud app version: Irrelevant

ownCloud server version: Irrelevant
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

**Comment by davivel** [comment]
Hi, @rhabbachi . If you don't mind, I will update the title of the issue according to your description.

**Comment by patrikkeller** [comment]
Yes, need that feature too. To handle all my photos fully automatic.

**Comment by rkarlsba** [comment]
Thanks. Works fine now with the official app :) 

Vennlig hilsen / Best regards 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Da mihi sis bubulae frustrum assae, solana tuberosa in modo Gallico fricta, ac quassum lactatum coagulatum crassum. Quod me nutrit me destruit.

**Comment by davigonz** [comment]
Hi @rkarlsba , I'm going to close this issue due to, as you said in the previous comment, it is working fine now.
