### ISSUE TITLE
App is still locked by passcode even after a full reinstall

### ISSUE THREAD

**Issue by zingmars** [owncloud/android#1798]
### Actual behaviour

After a full reinstall (Uninstall from Android's app list view and reinstall from Google Play Store) the passcode lock from the previous installation is still preset.
### Expected behaviour

Reinstall should wipe all data associated with the app, including settings such as the passcode.
### Steps to reproduce
1. Have the app installed with a passcode set up
2. Go to Settings -> Apps -> Owncloud
3. Press the Uninstall button
4. Go to play store -> OwnCloud -> Install
5. Open the app
6. Close the app (by pressing the home button for example)
7. Open the app again
8. It will now ask you for the passcode even though you are no longer logged in and your settings should've been wiped after the reinstall.
### Can this problem be reproduced with the official owncloud server? (url: https://demo.owncloud.org, user: test, password: test)

Yes, it's server independent.
### Environment data

Android version: 6.0.1

Device model: LG Nexus 5

Stock or customized system: Stock

ownCloud app version: 2.1.1

ownCloud server version: 8.2.7
### Logs

Not relevant as this is purely a client-side issue.

**Comment by zingmars** [comment]
I managed to "solve" this by reinstalling, logging in during the initial prompt, force closing the app, deleting the contents of /data/data/com.owncloud.android/databases and /data/data/com.owncloud.android/shared_prefs (which actually seems to contain the passcode in plain text, but it still didn't accept it for whatever reason) and starting the app again. Weird.

**Comment by zingmars** [comment]
Yes, that's exactly it.

**Comment by jesmrec** [comment]
Tested with three different devices, i can not reproduce this one (app version 2.21). Will close.

Please, feel free to reopen if you still reproduce it.
