### ISSUE TITLE
Feature Request: Provisioning Links

### ISSUE THREAD

**Issue by paraqles** [owncloud/android#1801]
I was trying to supply my family with access to our owncloud.
And to make this task easier I tried to supply them with "provisioning" links, like it is possible for the
"CalDav-Sync" and "CardDav-Sync" apps from Marten Gajda.

so i tried

`owncloud://user:password@cloud.example.net`

as a link in a mail and after klicking on them
the owncloud app was started but no fields was filled.
### Actual behaviour

Android owncloud app started, with empty fields for server, username and password.
### Expected behaviour

Android owncloud app start, with fields filled for server, username and password.
### Steps to reproduce
1. Install latest Owncloud App from Play Store
2. Open Link (for example from mail, this is just an example link [will not work without changes]) [owncloud://user:password@cloud.example.net](owncloud://user:password@cloud.example.net)
3. Owncloud App opens without filled fields
### Can this problem be reproduced with the official owncloud server?

(url: https://demo.owncloud.org, user: test, password: test)
Yes
### Environment data

Android version:
Cyanogenmod 12.1 based on 5.1.1

Device model: 
Sony Xperia Z2

Stock or customized system:
customized (Cyanogenmod 12.1)

ownCloud app version:
2.1.1

ownCloud server version:
9.0.3
### Logs

No Log entries because of no interaction with servers

**Comment by AndyScherzinger** [comment]
At the moment owncloud uses the to propagate oauth2 logins to the app as far as I can tell

**Comment by davivel** [comment]
Yes, the "hook" for the ```owncloud://``` scheme is a legacy of some experimentation with OAuth2 some time ago. Currently there is no support for provisioning links in the Android app.

Sure something to consider. @tcitworld, you were also interested something like in this, right?
