### ISSUE TITLE
OC displays "Folder is empty" or freezes, while folder contains big amount of files.

### ISSUE THREAD

**Issue by Fukurokudzu** [owncloud/android#1809]
### Actual behaviour

OC shows "Folder is empty" kind of message, or freezes for 30 seconds (or more, or forever), or stops answering to OS.
### Expected behaviour

OC should show the content of folder, or maybe first part of content, and it should not freeze.
### Steps to reproduce
1. Make a folder.
2. Put more than 2500 jpeg's in it.
3. Open folder, using slow wifi, 3g, or slow 4g connection.
4. Step in or out, untill it starts freezing.

[(link to video)](https://sync.fukurokudzu.ru/index.php/s/0SAWXn3V2uTAIoA)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
could'nt upload 2500 jpeg's there.
### Environment data

Android version: 
6
Device model: 
Huawei Honor 7
Stock or customized system:
Stock
ownCloud app version:
2.1.2
ownCloud server version:
8.2.7
### Logs

Everithing goes as usual on the server side

**Comment by davivel** [comment]
I'm curious, did you test this folder in the web UI? Did you have performance problems?

As far as I know, there is no way right now to ask only for part of the files to the server.

@PVince81 , nothing like paginated PROPFIND, am I wrong?

**Comment by Fukurokudzu** [comment]
I will test web service as soon as i find bad signal area. Using OC with a stable and fast connection looks pretty good, so i'don't think it has anything to do with perfomance problems. 
The point is: of course it can take a while to load the file list, but it shoud show the "loading" animation, or "pls wait" message, or "connection failed" message, instead of freezing and crashing.

**Comment by PVince81** [comment]
>  nothing like paginated PROPFIND, am I wrong?

unfortunately no. Maybe in the future with REPORT method.

**Comment by jesmrec** [comment]
@Fukurokudzu is this still reproducible?

**Comment by jesmrec** [comment]
closing. feel free to reopen if get the problem again
