### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by repsorp** [owncloud/android#1810]
### Actual behaviour
android client crashes on start

### Expected behaviour
no crash...
 
### Steps to reproduce
1. launch owncloud android client
2. crash
3. back to 1...

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
yes

### Environment data
Android version: 4.2.2

Device model: Google Nexus 5

Stock or customized system: Cyanogenmod 3.4.0

ownCloud app version: 2.1.1

ownCloud server version: 

### Logs

09-18 12:57:09.548 I/ActivityManager(1126): Timeline: Activity_launch_request id:com.owncloud.android time:62163215
09-18 12:57:09.548 I/ActivityManager(709): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.owncloud.android/.ui.activity.FileDisplayActivity bnds=[257,394][466,628]} from pid 1126
09-18 12:57:09.768 I/ActivityManager(709): Start proc com.owncloud.android for activity com.owncloud.android/.ui.activity.FileDisplayActivity: pid=20643 uid=10306 gids={50306, 1028, 1015, 3003}
09-18 12:57:09.858 D/ThumbnailsCacheManager(20643): create dir: /storage/emulated/0/Android/data/com.owncloud.android/cache/thumbnailCache
09-18 12:57:09.998 I/ActivityManager(20643): Timeline: Activity_launch_request id:com.owncloud.android time:62163670
09-18 12:57:09.998 I/ActivityManager(709): START u0 {act=ACTION_CHECK flg=0x20000 cmp=com.owncloud.android/.ui.activity.PassCodeActivity} from pid 20643
09-18 12:57:10.068 I/dalvikvm(20643): Could not find method android.view.Window.getStatusBarColor, referenced from method com.owncloud.android.ui.fragment.OCFileListFragment$7.onCreateActionMode
09-18 12:57:10.068 I/dalvikvm(20643): Could not find method android.view.Window.setStatusBarColor, referenced from method com.owncloud.android.ui.fragment.OCFileListFragment$7.onDestroyActionMode
09-18 12:57:10.118 E/AndroidRuntime(20643): Process: com.owncloud.android, PID: 20643
09-18 12:57:10.118 E/AndroidRuntime(20643): java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileDownloader@41e149e8 with null: java.lang.NullPointerException
09-18 12:57:10.118 E/AndroidRuntime(20643): 	at com.owncloud.android.files.services.FileDownloader.onStartCommand(FileDownloader.java:160)
09-18 12:57:10.508 W/ActivityManager(709): Activity pause timeout for ActivityRecord{42bcd2c8 u0 com.owncloud.android/.ui.activity.FileDisplayActivity t740}
09-18 12:57:11.938 I/ActivityManager(709): Process com.owncloud.android (pid 20643) has died.
09-18 12:57:11.938 I/WindowState(709): WIN DEATH: Window{4290e0c0 u0 com.owncloud.android/com.owncloud.android.ui.activity.FileDisplayActivity}
09-18 12:57:11.938 W/ActivityManager(709): Force removing ActivityRecord{42bcd2c8 u0 com.owncloud.android/.ui.activity.FileDisplayActivity t740}: app died, no saved state
09-18 12:57:11.948 I/ActivityManager(709): Start proc com.owncloud.android for activity com.owncloud.android/.ui.activity.PassCodeActivity: pid=20684 uid=10306 gids={50306, 1028, 1015, 3003}
09-18 12:57:12.048 D/ThumbnailsCacheManager(20684): create dir: /storage/emulated/0/Android/data/com.owncloud.android/cache/thumbnailCache
09-18 12:57:12.348 I/ActivityManager(709): Displayed com.owncloud.android/.ui.activity.PassCodeActivity: +1s850ms (total +2s604ms)
09-18 12:57:12.348 I/ActivityManager(709): Timeline: Activity_windows_visible id: ActivityRecord{42bdc448 u0 com.owncloud.android/.ui.activity.PassCodeActivity t740} time:62166028

**Comment by jabarros** [comment]
Hi @repsorp 
It is a strange behaviour... We can not reproduce it here. So, could you give us more details?
Did it happen after updating the app? or did it happen the first time you installed the app?
On the other hand, did you have any download in progress when you started the app?
With more details, we could be in a better position to try to reproduce it.

**Comment by repsorp** [comment]
Hi,

Sorry but can't reproduce either..
Everything's working fine now
it didn't happen after updating the app or first time install
It just happened like that
No download was in progress

**Comment by davivel** [comment]
@repsorp , please, reopen if appears again.

Thanks for reporting.
