### ISSUE TITLE
uploading directories

### ISSUE THREAD

**Issue by damdamce** [owncloud/android#1820]
### Actual behaviour
currently it's only possible to upload particular files

### Expected behaviour
it would be cool if one could upload whole directories (e.g. /blah/documents/private/) in addition.
 
### Steps to reproduce
1. Open ownCloud app on android (your ownCloud files are shown)
2. click on the round plus icon
3. click on upload
4. it's only possible to select files, but no directories.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
I didn't test, but i think it's safe to say that yes.

### Environment data
Android version: 5.1.1
Device model:  Sony Xperia Z1 (C6903)
Stock or customized system: stock
ownCloud app version: 2.1.2
ownCloud server version: 9.1

**Comment by Sermodi** [comment]
Some problem here.
When I try to upload some files, I can see nothing in my SDCard directory.

*Environtment data
Android version: 6.0.1
Device model: Sony Xperia S - nozomi
Owncloud app version: 2.1.2
Owncloud server version: 9

**Comment by damdamce** [comment]
to clarify: i am able to upload normal files. i don't think it's a bug on my side rather a feature request.

**Comment by davivel** [comment]
@sermodi, please, open a different issue for your problem.

@damdamce , your request it's already registered in #645 ; please, follow any update on it there.

Thanks.
