### ISSUE TITLE
Files appear as conflicting with the server even though they were not modified on server

### ISSUE THREAD

**Issue by djibux** [owncloud/android#1821]
### Actual behaviour

When a file is modified twice on the client within a few seconds and the first upload to the server didn't finish, I get a popup telling me the local version is in conflict with the distant version.
### Expected behaviour

A file should not be in conflict with the server version if the file hasn't been modified on the server…
### Steps to reproduce
1. Make a file available offline
2. Make a few quick changes and saves to that file, making sure that your saves happen before the previous version was uploaded to the server (I personally always trigger the error with a todo.txt file modified via an app called Simpletask)
3. The "conflict resolution" popup opens within owncloud client.

I have reproduced the issue with the official owncloud server.
### Environment data

Android version: 6.0.1

Device model: Zuk Z1

Stock or customized system: CyanogenMod, official nightly build

ownCloud app version: Owncloud 2.1.2 (f-droid)

ownCloud server version: 9.1.1 (current stable)

**Comment by davivel** [comment]
Mmm, messy. Need to fix this.

**Comment by michaelstingl** [comment]
Team will work on a solution in https://github.com/owncloud/android/issues/2026
