### ISSUE TITLE
What is ownCloud Development Process?

### ISSUE THREAD

**Issue by PauloSantos13** [owncloud/android#1822]
Hello! I'm a student of Computer Science at Faculty of Engineering of University of Porto, and at a Software Engineering course we have to choose between several open source projects and investigate about one of them.
My colleagues and I chose the ownCloud android app, and we would like to ask some questions to some developers, if possible.  We'll try to be as short as possible.

Here are some initial questions that we think that are relevant: 
- For how long has this project been on?
- How many contributors actually work on this project?
- How the project contributors were divided? In teams? Each team is responsible for a particular feature? If so, which one?
- Are there meetings?
- Do you have a main client? Who works with ownCloud? 
- Which development processes were used (Test-Driven Development? Waterfall? Incremental development and delivery? Software prototyping?)?
- What needs to be improved?

If you have more relevant informations we would be grateful. Thanks in advance.

Best regards,
Paulo Santos

@davivel @AndyScherzinger @jabarros

**Comment by davivel** [comment]
This is being solved privately with @PauloSantos13 for his concrete interest.

But, let's leave this open until we document it appropriately in public space.
