### ISSUE TITLE
Recent version is not usable for new account

### ISSUE THREAD

**Issue by Spielmops** [owncloud/android#1823]
### Actual behaviour

-Tell us what happens
I install owncloud 2.1.2 from F-droid on my Lollipop-smartphone. I start the app and fillout my server-address - my server is found. i fill the field name and password and tap on "connct" and "unknown error.
### Expected behaviour

-Tell us what should happen
 My server should let me in
### Steps to reproduce
1.  Every time the same with the versions 2.1.1 and 2.1.0
2. I can reproduce this behaviour endless with two other phones with lollipop
3. 

Workaround: I have an older Version of Owncloud here: 1.9.1 and this version works as expected.

Additional observation:
the new version works as an update. My other phone works with y Owncloud since version 1.3.1 and is fine with 2.1.2 as an update.

Additional knowledge: My Owncloud-server-version is 6.0
Spielmops

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
### Environment data

Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

**Comment by davivel** [comment]
@Spielmops , your server version is quite old, it's life cycle ended more than one year ago. It's very possible that log-in fails due to that.

Could you consider update your server to a maintained version? You can find the schedule of server life cycles in https://github.com/owncloud/android/issues/1799

**Comment by davivel** [comment]
I was wrong, that's not the problem; log-in to OC 6 still working.

About your smartphones: the one with the problem, what model is it? What model and Android version is the one working?

About your password, does it include non-alphanumeric characters, such as umlauts or others?

You didn't install the ownCloud Workaround Jelly Bean App in your devices, right? (Don't do it).

**Comment by davivel** [comment]
What's exactly the version of your server?

**Comment by jesmrec** [comment]
@Spielmops is this still reproducible?

**Comment by Spielmops** [comment]
I have an older version of owncloud and therefore I am using Owncloud-Client 1.9.1. That works. This next winter I will install Nextcloud on a new server.

Spielmops
