### ISSUE TITLE
Cannot click through "the identity of the site could not be verified" popup

### ISSUE THREAD

**Issue by KentShikama** [owncloud/android#1824]
### Actual behaviour

When using a site with an untrusted SSL certificate, I get a "the identity of the site could not be verified" pop up as expected. However, when I try to click the "Yes" button to dismiss the popup (or even "No"), the app doesn't dismiss the popup.

### Expected behaviour

The app should dismiss the popup when I press either "No" or "Yes".
 
### Steps to reproduce
1. Open up owncloud app
2. Type an server address with a self-signed certificate

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

Nope

### Environment data
Android version: 5.1

Device model: Motorola Moto X

Stock or customized system: Nope

ownCloud app version: 2.1.2

ownCloud server version: ownCloud 7.0.4+dfsg-4~deb8u4 (Debian) (stable)

**Comment by davivel** [comment]
So, you get stuck in that dialog and can't do anything else?

Is is possible that you have in your device an app like Lux or similar? See issue #1799, could this be the same problem?

**Comment by KentShikama** [comment]
@davivel It was indeed Twilight (similar to Lux).

**Comment by michaelstingl** [comment]
2.10 with config option to allow this got released in the Play Store:
https://central.owncloud.org/t/owncloud-2-10-for-android-released/18900
