### ISSUE TITLE
Blocking when an account is deleted in server side

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1825]
### Steps
1. In app, login in an account
2. In server, delete the account
3. In app, select the account in drawer or in account manager
4. Redirection to login view

The account does not exist anymore, so credentials will never work (username is non-editable). If you tap on "Go Back" button, the files view or settings view (depending whether the app has more accounts or not) is shown for a little while, but you are redirected again to login view. It is a bit annoying to switch to another account or tap on "new account".

Expected behaviour? Switch to another account, or to login view if the app has no accounts. The question is if server side answers in the same way if the credentials have changed and if the account is removed to detect these two different cases.

**Comment by jesmrec** [comment]
In the case of authentication (OAuth2 or whatever), if the user credentials are revoked, the side-effect is the same, making the app annoying to use.

**Comment by theScrabi** [comment]
So the idea was to redirect the user to the account select window instead of the login view. This way the user is still able to select another account or delete one if no other is there.

**Comment by michaelstingl** [comment]
Great teamwork. Go for it!

**Comment by davigonz** [comment]
> agreed with this new behaviour? 

Yes but just an improvement I came up with about the next thought

> If the account was removed, the user is redirected to account select view in case that more accounts are attached. Then, if the user selects again the server-removed account, he should be redirected again to account select view in a loop, until he selects a different account or remove the account from the device.

@michaelstingl @jesmrec @theScrabi  What about deleting the account when the app detects that the server account was removed? I mean, instead of keep showing it in the account select view in a loop, just delete it from the list if is not longer available in the server. IMHO, keep a loop for this doesn't make sense.

**Comment by jesmrec** [comment]
@theScrabi and me were discussing about that. Is there any way to detect a removed account in server-side?

**Comment by theScrabi** [comment]
> @theScrabi and me were discussing about that. Is there any way to detect a removed account in server-side?

One method that works the same for basic auth and oauth

**Comment by jesmrec** [comment]
The case of SAML behaves in same way. SAML session expires itself and the expected behaviour is asking credentials again, so it should be redirected to login view.
