### ISSUE TITLE
here is values-zh-rCN,all translated,add something below

### ISSUE THREAD

**Issue by mossane** [owncloud/android#1830]
here is values-zh-rCN,all translated,add something below

[values-zh-rCN.zip](https://github.com/owncloud/android/files/546398/values-zh-rCN.zip)

**Comment by davivel** [comment]
Thank you, @mossane, your help is very appreciated.

Unfortunately, we can't grab the translation and add it to the project this way. To contribute with the translations team, you need register in Transifex and request to join the translation of the ownCloud project here: https://www.transifex.com/owncloud-org/owncloud/.

Thanks in advance.
