### ISSUE TITLE
Android UI of Owncloud app not responding while automatic screen rotation disabled

### ISSUE THREAD

**Issue by croisez** [owncloud/android#1831]
### Reproduction of the problem

I got the UI not detecting my finger touch in the following situation:
- in notification tray, disable auto-rotation.
- start owncloud app in my bed ;-) with screen rotated in landscape, but app is still in portrait due to auto-rotation locked. In fact, in my bed, I have my phone rotated and I have to lock the auto-rotate feature to avoid it to go to landscape mode.
- enter a https address, which has a self-signed certificate which causes the apparition of a warning message.
  => at this point, impossible to push on any of the 3 options (no, details, yes). 
### Expected behaviour

My guess is that this issue is related to the screen rotation, because when I redo the whole process in the normal position, I can access and push on the 3 menu items.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
### Environment data

Android version: 6.0.1
Device model: Galaxy S6
Stock or customized system: Stock
ownCloud app version: 2.1.2
ownCloud server version: this is the latest version from apt repository in raspbian.

**Comment by davivel** [comment]
@jesmrec , could you try to reproduce it, please.?

**Comment by jesmrec** [comment]
I have tried to reproduce the issue with the following environment:

Android version 6.0.1
Galaxy Note 4
2.1.2 stable version 
server 9.1.1 (no matter for this issue)

unsuccesfully. With the device in landscape but the app in portrait (rotation locked), i can tap on the buttons of the certificate window. 

The only difference with @croisez environment is the device model, as i see.

Could it be related with https://github.com/owncloud/android/issues/1799 ?

CC @davivel

**Comment by davigonz** [comment]
@croisez can you please check if you have any app described in #1799 installed that might be blocking the touch events? Thanks

**Comment by jesmrec** [comment]
@croisez is this problem still there?

**Comment by jesmrec** [comment]
not reproducible. feel free to reopen if it is already there
