### ISSUE TITLE
Mini FAB labels bug

### ISSUE THREAD

**Issue by togglecode** [owncloud/android#1834]
### Actual behaviour
Mini FAB labels disappear due to a bug

### Expected behaviour
Mini FAB labels should always be visible
 
### Steps to reproduce

1. Open owncloud App
2. Click on "+" sign on bottom right of the screen (See screen shot)
3. Do not upload anything and just go back to the App
4. Close the application (without closing the application it works normal)
5. Open the app again
6. Click on the "+" sign again 
7- Mini FAB labels will not show

### Environment data
Android version: Marshmallow 

Device model: Moto G3

ownCloud app version: Master Branch Commit 1be7f1c66246f9ca85b7e619e3226432692f0b38

ownCloud server version: Owncloud Demo Server

P.S in the OCFileListFragment.java it says:

```
            if(prefs.getLong(KEY_FAB_EVER_CLICKED, 0) > 0) {
                miniFabClicked = true;
            }
```
And for some reason the `prefs.getLong(KEY_FAB_EVER_CLICKED, 0)`  returns 1 after you follow the steps that I mentioned so that should be fixed.

### Screenshots
![screenshot_20161024-132307](https://cloud.githubusercontent.com/assets/17141698/19645075/44962800-99f3-11e6-80c3-791f1753e52e.png)
![screenshot_20161024-132327](https://cloud.githubusercontent.com/assets/17141698/19645078/4702cdd2-99f3-11e6-9180-3a89cb597325.png)

**Comment by AndyScherzinger** [comment]
@togglecode this is actually by design. The labels get hidden after your actually clicked on the min fabs at least once. The labels then only get shown again on a long-click. cc @davivel

**Comment by togglecode** [comment]
Ah I see.. well... I mean that's a hidden feature right there I guess :)

**Comment by togglecode** [comment]
Closing this since it's not a bug, if you'd like my own user experience suggestion, I would recommend to exclude the long press (toast) option and always keep it like this.
