### ISSUE TITLE
share with users or groups 

### ISSUE THREAD

**Issue by maimalash** [owncloud/android#1837]
when share with users or groups the search function not working 

### Expected behaviour
when type text the list show with all filter users or groups that contains text 
 
### Steps to reproduce
1. select file
2. share 
3. select share with users or groups

### Environment data
Android version:
android studio 1.3.2
Device model: 
samsung not 3

**Comment by jesmrec** [comment]
do you mean that the sharee search is not returning any result?

**Comment by jesmrec** [comment]
no answer... closing.

if the problem persists, please reopen.
