### ISSUE TITLE
Android 7 account getAuthToken failure

### ISSUE THREAD

**Issue by jefftharris** [owncloud/android#1846]
On Android 7, my app is no longer able to retrieve the auth token for an ownCloud account.  Prior to Android 7, the app would request the app token via AccountManager.getAuthToken which would prompt the user to confirm permission for my app and grant access to the token.  The token would then be used with the ownCloud Android library to access the account.

The issue occurs with the latest ownCloud app, 2.1.2 and Android 7 or higher.

The exception that occurs:
11-06 10:10:50.521 ? W/Binder: Binder call failed.
java.lang.SecurityException: KEY_INTENT resolved to an Activity (android.accounts.GrantCredentialsPermissionActivity) in a package (android) that does not share a signature with the supplying authenticator (owncloud).
at com.android.server.accounts.AccountManagerService$Session.checkKeyIntent(AccountManagerService.java:3860)
at com.android.server.accounts.AccountManagerService$6.onResult(AccountManagerService.java:2336)
at com.android.server.accounts.AccountManagerService$6.onResult(AccountManagerService.java:2293)
at android.accounts.IAccountAuthenticatorResponse$Stub.onTransact(IAccountAuthenticatorResponse.java:59)
at android.os.Binder.execTransact(Binder.java:565)

**Comment by davivel** [comment]
Hi, @jefftharris .

With "my app" you mean you are accessing to the token from another app that is not the ownCloud Android app, right?

I see your intention, but I'm not sure if with the updates in Android permission this will be possible anymore. I'll have to research a bit.

**Comment by jefftharris** [comment]
"My app" is my own app, separate from the ownCloud app.  Until Android 7.1, I was able to gain access to the password stored for the account and use it with the ownCloud library to login to the account.  I have filed an issue with Android itself, and they were able to reproduce the issue.  I'm not sure if/when a fix would be incoming.

One item which would help would be to move the authentication dialog from the ownCloud app to the library.  That way other apps could use the nice dialog to get their own login tokens and not rely on the system account.

**Comment by davivel** [comment]
In the next weeks we will work in supporting OAuth2 authentication, and we'll have to update the login and authentication process accordingly. Maybe we can review this issue then, to allow other apps use the authentication token. Though I can't promise it.

About moving the login view to the library, I don't think we go that way, UI elements are far from the scope of the library.

**Comment by jefftharris** [comment]
Some mechanism to simplify the authentication process would make using the library much easier.  Either access via the system account or a library to use the authentication dialog would be much appreciated.  Other services like Dropbox provide a method to simplify integration into apps.
