### ISSUE TITLE
uppercase letter in server URL results in no connection 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/android#1852]
[00006805](https://na25.salesforce.com/5003100000ikkcw)

### Actual behaviour
app can't connect to server because of uppercase character in URL

### Expected behaviour
Should connect
 
### Steps to reproduce
1. Try to connect to server with uppercase char in url

**Comment by Kawohl** [comment]
@davivel 
shouldn't be a hard one to fix.

**Comment by cdamken** [comment]
@davivel any news?

**Comment by Kawohl** [comment]
@davivel any update or ETA?

**Comment by michaelstingl** [comment]
@davitol @davigonz Could a fix find it's way in the version after 2.3.0? What is the next version? 2.3.1 or 2.4.0?

**Comment by davivel** [comment]
What part of the URL is in uppercase? The domain part should not be case sensitive, but the path could be canse sensitive or not depending on the server, and we should not manipulate it.

**Comment by davivel** [comment]
>  What is the next version? 2.3.1 or 2.4.0?

By default, 2.4.0 . There is a milestone for it :)

**Comment by michaelstingl** [comment]
Original request from customer:

> There is a minor bug in the Android client (version 2.1.2): In case the server URL contains uppecase letters the app cannot establish a connection. However, the iOS version (v3.5.1) can handle uppercase letters in the URL.

<img width="608" alt="napkin 15-02-17 9 20 51 pm" src="https://cloud.githubusercontent.com/assets/214010/22993821/b21eb826-f3c4-11e6-8537-d1b56132cf0d.png">

It seems the domain part is case sensitive in the Android app. @davigonz Is this difficult to fix?

**Comment by davivel** [comment]
I'd really like to know what's the reason after this problem. Reformatting input, such as just making it lower case, might lead to unexpected problems.

**Comment by davigonz** [comment]
Sorry @michaelstingl , I've misplaced this issue. As @davivel says, solutions as making the input lower case could not be the proper ones. IMHO we should go deeper to get the main reason of this problem.

**Comment by michaelstingl** [comment]
I can explain every behaviour to my users, but I can't explain why it's inconsistent with Android, iOS and desktop.

Shouldn't this be specified somewhere? RFC? I think this isn't only a problem for ownCloud.

**Comment by ayushpateria** [comment]
I don't think making the domain part of the URL may lead to any unexpected problem. Even Google Chrome does this, type any URL with upper case letters in domain in the address bar and it will be converted to lower case by the browser.

**Comment by davivel** [comment]
@michaelstingl , this is a bug, it's a wrong behaviour of the app. I was not trying to defend otherwise, sorry is seemed so. You are right, domain names are case insensitive according to rfc4343: https://tools.ietf.org/html/rfc4343 .

@ayushpateria , I'm not worried about applying lowercases to access the server; I'm worried because the URL is also used to define the name of the account that is stored in the app, and we need to think always what will happen with current users of the app when they upgrade it with this change. In second thought, probably in this case it's not really dangerous, because the corner case is too tricky.  

Let me have a look to your PR and let's move forward.

**Comment by davivel** [comment]
@Kawohl, this was fixed by @ayushpateria . Will be included in next release, number 2.4.0 per the current planning.
