### ISSUE TITLE
Share dialog spinner stays `Loading ...`

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1860]
Changes in the device orientation can lead to an indefinite spinner in the share dialog. It's hard to isolate the specific condition that is triggering this, but it's happening often. 

## Steps to reproduce:
1. Select a file and choose to share it. 
2. Change the device orientation. Repeat and retry this 2 steps until the load spinner stays stuck. 
3. After this happening once, it's reproduced systematically. 

## Current behavior 
The `Loading...` spinner stays in focus forever. If you try to click the back button, the app doesn't respond, and a couple of minutes after closing it, crashes. 

## Expected behavior 
Spinner should be displayed while getting the share settings for that file and a timeout should be triggered if these settings cannot be pulled from the server. 

## Test environment 
Android 6.0.1 on a Samsung Galaxy Note 4

**Comment by davivel** [comment]
Atm this cannot be reproduced. 

cc @jesmrec

**Comment by jesmrec** [comment]
not reproducible.
