### ISSUE TITLE
A file cannot be uploaded in a federated shared folder with create permissions

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1861]
### Pre-requirements
Have 2 stable servers.

### Steps
1. Share a folder to a user (user1) of another server giving him only create permissions
2. Enter in the server of the user1 (web) and accept the folder
3. Enter in the folder in the app as user1 and upload a file

### Current behaviour
The upload is not done, an Unexpected error is shown in Uploads view.

### Expected behaviour
The upload should be done.

### Device & version
- Nexus 9 v6.0

**Comment by davivel** [comment]
Only reproducible in a concrete server instance, seems a configuration problem in that server. **Pending to confirm if uploads work in web UI**

**Comment by davigonz** [comment]
Tested in two servers (server1 and server2), with 9.1.2 stable version. 

When a user in a server (server2) accepts the folder shared by other user from other server (server1) and tries to upload a file in that folder, it fails, from the Android app and the web.

- APP

![app_1847](https://cloud.githubusercontent.com/assets/15261363/21424634/680e9af4-c844-11e6-8217-187fd661296f.png)

- Web UI

![server_1847](https://cloud.githubusercontent.com/assets/15261363/21424638/70d460f6-c844-11e6-9866-7e64bc7ba81a.png)

**Comment by davigonz** [comment]
Fix in https://github.com/owncloud/core/issues/26173. Closing...
