### ISSUE TITLE
Android app can not authenticate against server v9.2.0.3

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1863]
### Steps to reproduce

Try to login in a server 9.0.2.3 (server master branch). 

### Current behaviour

The URL is accepted, but the credentials are not: `Unknown error occurred`

### Expected behaviour

Login correct
 

### Tracestack from Android:

E/GetRemoteUserInfoOperation: Exception while getting OC user information
                              org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
                                  at org.json.JSON.typeMismatch(JSON.java:111)
                                  at org.json.JSONObject.<init>(JSONObject.java:160)
                                  at org.json.JSONObject.<init>(JSONObject.java:173)
                                  at com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation.run(GetRemoteUserInfoOperation.java:79)
                                  at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
                                  at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:95)
                                  at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:41)
                                  at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                  at java.lang.Thread.run(Thread.java:761)

### Server log:

{"reqId":"NkPAhjD3tTk5ZmvpzuDF","remoteAddr":"xx.xx.xx.xx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/opt\\\/owncloud\\\/remote.php(164): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#6 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}","level":0,"time":"2016-12-22T13:45:57+00:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"EsbGpDItcvgIsDEcQeXL","remoteAddr":"xx.xx.xx.xx","app":"admin_audit","message":"User user1 attempted to log into ownCloud from IP address: xx.xx.xx.xx [CLIENT_IP: xx.xx.xx.xx] [USER_AGENT: Mozilla\/5.0 (Android) ownCloud-android\/2.2.0]","level":1,"time":"2016-12-22T13:45:57+00:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"EsbGpDItcvgIsDEcQeXL","remoteAddr":"xx.xx.xx.xx","app":"admin_audit","message":"User user1 logged into ownCloud from IP address: xx.xx.xx.xx [CLIENT_IP: xx.xx.xx.xx] [USER_AGENT: Mozilla\/5.0 (Android) ownCloud-android\/2.2.0]","level":1,"time":"2016-12-22T13:45:58+00:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"user1"}

The problem does not happen neither in iOS app nor in desktop client.

Server info:

{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"9.2.0.3","versionstring":"9.2.0 pre alpha","edition":"Enterprise","productname":"ownCloud"}

Device: Nexus 5 v5.0.1. 
App version: 2.2.0

CC @davivel @davigonz

**Comment by davigonz** [comment]
After doing some tests, this is what the different servers return when user data in authentication is requested:

- Not PHP7

`{"oca":
 	{
	 "meta”:
		 {"status":"ok”,
	 	"statuscode":100,
	 	"message":null}
 	,"data”:
		 {"id":"admin”,
	 	"display-name":"admin”,
	 	"email":null}
	 }
 }
`
- PHP7
   
```html
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
<head data-requesttoken="XXXX">
    <meta charset="utf-8">
    <title>ownCloud</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="referrer" content="never">
</head>
</html> ...MORE HTML CODE...
```

May the server be involved?

**Comment by davivel** [comment]
@PVince81 , @DeepDiver1975 , any change in 9.2.0.3 about the access to "/index.php/ocs/cloud/user" ? Thanks.

**Comment by jesmrec** [comment]
I have noticed that the problem does not depend directly of PHP 7, so in server version 9.2.03 with PHP5.6 also happens in the Android side

The following chart shows up the scenario:

|Server|PHP version|Android|iOS|Desktop|Comments|
|:-----|:---------:|:-----:|:-:|:-----:|:-------|
|9.1.2|7.0|OK|OK|OK|
|9.1.3|7.0|OK|OK|OK|
|9.2.0.3|5.6|**NOK**|OK|OK|Unknown Error
|9.2.0.3|7.0|**NOK**|OK|OK|Unknown Error
|9.2.0.3|7.1|**NOK**|OK|OK|Unknown Error

CC @davivel @davigonz

**Comment by PVince81** [comment]
I think the Webdav auth code has changed a bit in https://github.com/owncloud/core/issues/26351 and other related tickets.

Also we upgraded Sabre.

@jesmrec are you able to bisect the server ?

**Comment by PVince81** [comment]
It would also help if you are able to provide a `curl` command that reproduces the issue on master and shows that it works on 9.1.

**Comment by davivel** [comment]
Taking this.

**Comment by davivel** [comment]
@PVince81 , don't worry, problem is in the Android app. No relation with auth code changes.

Thanks a lot.

**Comment by davivel** [comment]
@jesmrec , ready to test in #1891.

@davigonz , ready to review in #1891 and owncloud/android-library#148

**Comment by jesmrec** [comment]
Fixed
