### ISSUE TITLE
java.lang.SecurityException: uid ***** cannot get user data for accounts of type: bitfire.at.davdroid

### ISSUE THREAD

**Issue by nikolajsheller** [owncloud/android#1866]
### Actual behaviour
When starting app, it crashes immediately.

### Expected behaviour
I expect the app to start, and not crash immediately.
 
### Steps to reproduce
1. Upgrade to version 2.2.0
2. Click app icon
3. Crash

Can this problem be reproduced with the official owncloud server?
Unknown, cannot access UI to set this up.

### Environment data
Android version:
Android 7.1.1

Device model: 
Nexus 5X

Stock or customized system:
Stock

ownCloud app version:
2.2.0 (from F-Droid)

ownCloud server version:
9.1.3-1.1 (Ubuntu)

#### Web server error log
Not relevant

#### ownCloud log (data/owncloud.log)
12-26 15:31:52.374  4931  7656 I ActivityManager: Start proc 14814:com.owncloud.android/u0a89 for activity com.owncloud.android/.ui.activity.FileDisplayActivity
12-26 15:31:52.458 14814 14814 W System  : ClassLoader referenced unknown path: /data/app/com.owncloud.android-1/lib/arm64
12-26 15:31:52.586 14814 14829 D ThumbnailsCacheManager: create dir: /storage/emulated/0/Android/data/com.owncloud.android/cache/thumbnailCache
12-26 15:31:52.591 14814 14814 V FileDisplayActivity: onCreate() start
12-26 15:31:52.609 14814 14814 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-26 15:31:52.613 14814 14814 D FileDisplayActivity: onCreate(Bundle) starting
12-26 15:31:52.703 14814 14814 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
12-26 15:31:52.780 14814 14814 V FileDisplayActivity: onCreate() end
12-26 15:31:52.782 14814 14814 V FileDisplayActivity: onStart() start
12-26 15:31:52.782 14814 14814 D FileDisplayActivity: onStart() starting
12-26 15:31:52.900 14814 14814 D FileDisplayActivity: Initializing Fragments in onAccountChanged..
12-26 15:31:52.900 14814 14814 E FileDisplayActivity: Access to unexisting list of files fragment!!
12-26 15:31:52.900 14814 14814 E FileDisplayActivity: Still have a chance to lose the initializacion of list fragment >(
12-26 15:31:52.908 14814 14831 D NetworkUtils: Searching known-servers store at /data/user/0/com.owncloud.android/files/knownServers.bks
12-26 15:31:52.909 14814 14814 V FileDisplayActivity: onStart() end
12-26 15:31:52.910 14814 14831 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-26 15:31:52.920 14814 14814 E FileDisplayActivity: Access to unexisting list of files fragment!!
12-26 15:31:52.920 14814 14814 E FileDisplayActivity: OCFileListFragment is null
12-26 15:31:52.921 14814 14831 D OwnCloudClient #0: Creating OwnCloudClient
12-26 15:31:52.922 14814 14831 D AccountUtils: Restoring cookies for *************@*************
12-26 15:31:52.922 14814 14814 V FileDisplayActivity: onResume() start
12-26 15:31:52.923 14814 14814 D FileDisplayActivity: onResume() starting
12-26 15:31:52.923 14814 14814 E OCFileListFragment: onAttach
12-26 15:31:52.924 14814 14814 I OCFileListFragment: onCreateView() start
12-26 15:31:52.924 14814 14814 D ExtendedListFragment: onCreateView
12-26 15:31:52.936 14814 14831 D AccountUtils: Restoring cookies for *************@*************
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: Generation of avatar for null failed
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: java.lang.SecurityException: uid 10089 cannot get user data for accounts of type: bitfire.at.davdroid
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at android.os.Parcel.readException(Parcel.java:1684)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at android.os.Parcel.readException(Parcel.java:1637)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:887)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at android.accounts.AccountManager.getUserData(AccountManager.java:400)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies(AccountUtils.java:300)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies(AccountUtils.java:343)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.SingleSessionManager.getClientFor(SingleSessionManager.java:123)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.DynamicSessionManager.getClientFor(DynamicSessionManager.java:40)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at com.owncloud.android.datamodel.ThumbnailsCacheManager$GetAvatarTask.doInBackground(ThumbnailsCacheManager.java:443)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at com.owncloud.android.datamodel.ThumbnailsCacheManager$GetAvatarTask.doInBackground(ThumbnailsCacheManager.java:383)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-26 15:31:52.941 14814 14831 E ThumbnailsCacheManager: 	at java.lang.Thread.run(Thread.java:761)
12-26 15:31:52.947 14814 14832 D OwnCloudClient #1: Creating OwnCloudClient
12-26 15:31:52.947 14814 14832 D AccountUtils: Restoring cookies for *************@*************
12-26 15:31:52.948 14814 14832 D AccountUtils: Restoring cookies for *************@*************
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: Generation of avatar for null failed
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: java.lang.SecurityException: uid 10089 cannot get user data for accounts of type: bitfire.at.davdroid
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at android.os.Parcel.readException(Parcel.java:1684)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at android.os.Parcel.readException(Parcel.java:1637)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:887)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at android.accounts.AccountManager.getUserData(AccountManager.java:400)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies(AccountUtils.java:300)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies(AccountUtils.java:343)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.SingleSessionManager.getClientFor(SingleSessionManager.java:123)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at com.owncloud.android.lib.common.DynamicSessionManager.getClientFor(DynamicSessionManager.java:40)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at com.owncloud.android.datamodel.ThumbnailsCacheManager$GetAvatarTask.doInBackground(ThumbnailsCacheManager.java:443)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at com.owncloud.android.datamodel.ThumbnailsCacheManager$GetAvatarTask.doInBackground(ThumbnailsCacheManager.java:383)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-26 15:31:52.950 14814 14832 E ThumbnailsCacheManager: 	at java.lang.Thread.run(Thread.java:761)
12-26 15:31:52.995 14814 14814 I OCFileListFragment: onCreateView() end
12-26 15:31:52.996 14814 14814 E OCFileListFragment: onActivityCreated() start
12-26 15:31:53.137 14814 14814 V FileDisplayActivity: onResume() end
12-26 15:31:53.160 14814 14814 D OperationsService: Creating service
12-26 15:31:53.164 14814 14814 D FileDownloader: Creating service
12-26 15:31:53.170 14814 14814 D FileUploader: Creating service
12-26 15:31:53.173 14814 14814 V UploadsStorageManager: Updating state of any killed upload
12-26 15:31:53.183 14814 14814 V UploadsStorageManager: No upload was killed
12-26 15:31:53.185 14814 14814 D FileObserverService: onCreate
12-26 15:31:53.187 14814 14814 D FileObserverService: Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.owncloud.android/.services.observer.FileObserverService }
12-26 15:31:53.187 14814 14814 D FileObserverService: Loading all available offline files from database to start watching them
12-26 15:31:53.225 14814 14814 V FileObserverService: Adding a file to be watched
12-26 15:31:53.226 14814 14814 D FileObserverService: Observer added for folder /storage/emulated/0/owncloud/*************@*************/*************/*************
12-26 15:31:53.235 14814 14814 D AvailableOfflineObserver: Watching folder /storage/emulated/0/owncloud/*************@*************/*************/************* for changes in *************
12-26 15:31:53.235 14814 14814 D FileObserverService: Added /storage/emulated/0/owncloud/*************@*************/*************/*************/************* to list of observed children
12-26 15:31:53.237 14814 14814 V FileObserverService: Adding a file to be watched
12-26 15:31:53.238 14814 14814 D AvailableOfflineObserver: Watching folder /storage/emulated/0/owncloud/*************@*************/*************/************* for changes in *************
12-26 15:31:53.238 14814 14814 D FileObserverService: Added /storage/emulated/0/owncloud/*************@*************/*************/*************/************* to list of observed children
12-26 15:31:53.240 14814 14814 V FileObserverService: Adding a file to be watched
12-26 15:31:53.240 14814 14814 D FileObserverService: Observer added for folder /storage/emulated/0/owncloud/*************@*************/*************
12-26 15:31:53.241 14814 14814 D AvailableOfflineObserver: Watching folder /storage/emulated/0/owncloud/*************@*************/************* for changes in *************
12-26 15:31:53.241 14814 14814 D FileObserverService: Added /storage/emulated/0/owncloud/*************@*************/*************/************* to list of observed children
12-26 15:31:53.287 14814 14835 I Adreno  : QUALCOMM build                   : a5b4970, If5818605d9
12-26 15:31:53.287 14814 14835 I Adreno  : Build Date                       : 10/12/16
12-26 15:31:53.287 14814 14835 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
12-26 15:31:53.287 14814 14835 I Adreno  : Local Branch                     : N24D
12-26 15:31:53.287 14814 14835 I Adreno  : Remote Branch                    : 
12-26 15:31:53.287 14814 14835 I Adreno  : Remote Branch                    : 
12-26 15:31:53.287 14814 14835 I Adreno  : Reconstruct Branch               : 
12-26 15:31:53.293 14814 14835 I OpenGLRenderer: Initialized EGL, version 1.4
12-26 15:31:53.293 14814 14835 D OpenGLRenderer: Swap behavior 1
12-26 15:31:53.509 14814 14819 I art     : Do partial code cache collection, code=15KB, data=25KB
12-26 15:31:53.512 14814 14819 I art     : After code cache collection, code=14KB, data=25KB
12-26 15:31:53.512 14814 14819 I art     : Increasing code cache capacity to 128KB
12-26 15:31:53.573 14814 14814 D FileActivity: Operations service connected
12-26 15:31:53.574 14814 14814 D FileDisplayActivity: Download service connected
12-26 15:31:53.574 14814 14814 D FileDisplayActivity: Upload service connected
12-26 15:31:53.724  4931  5000 I ActivityManager: Displayed com.owncloud.android/.ui.activity.FileDisplayActivity: +1s364ms
12-26 15:31:53.728 14814 14814 D ExtendedListFragment: Setting progress visibility to true
12-26 15:31:53.735 14814 14842 D OwnCloudClient #2: Creating OwnCloudClient
12-26 15:31:53.735 14814 14842 D AccountUtils: Restoring cookies for *************@*************
12-26 15:31:53.737 14814 14842 D AccountUtils: Restoring cookies for *************@*************
12-26 15:31:53.739 14814 14842 E AndroidRuntime: FATAL EXCEPTION: Thread-2
12-26 15:31:53.739 14814 14842 E AndroidRuntime: Process: com.owncloud.android, PID: 14814
12-26 15:31:53.739 14814 14842 E AndroidRuntime: java.lang.SecurityException: uid 10089 cannot get user data for accounts of type: bitfire.at.davdroid
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1684)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1637)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:887)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at android.accounts.AccountManager.getUserData(AccountManager.java:400)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies(AccountUtils.java:300)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at com.owncloud.android.lib.common.accounts.AccountUtils.restoreCookies(AccountUtils.java:343)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at com.owncloud.android.lib.common.SingleSessionManager.getClientFor(SingleSessionManager.java:123)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at com.owncloud.android.lib.common.DynamicSessionManager.getClientFor(DynamicSessionManager.java:40)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:281)
12-26 15:31:53.739 14814 14842 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
12-26 15:31:53.744  4931 23330 W ActivityManager:   Force finishing activity com.owncloud.android/.ui.activity.FileDisplayActivity

**Comment by jesmrec** [comment]
@nikolajsheller from which version did you upgrade?

**Comment by nikolajsheller** [comment]
@jesmrec I upgraded from 2.1.2, also from F-Droid.

**Comment by davivel** [comment]
@nikolajsheller , this was fixed in version 2.3.0. Give it a try and tell us if I'm a wrong.

Thanks!
