### ISSUE TITLE
Deleting files reports failure despite success

### ISSUE THREAD

**Issue by filerun** [owncloud/android#1868]
### Actual behaviour
Deleting files reports failure despite success

### Expected behaviour
The app should report success, as the file is being removed from the remote server
 
### Steps to reproduce
1. Open app
2. Connect to server
3. Delete file

Can this problem be reproduced with the official owncloud server?
Yes. It can be reproduced with both Nextcloud and ownCloud server demos.

### Environment data
Android version: 6.0 & 4.4

Device model: various

Stock or customized system: stock

ownCloud app version: 1.4.0

ownCloud server version: 10.0.1

**Comment by jesmrec** [comment]
@filerun 

>ownCloud app version: 1.4.0

This version is too old, it would be interesting that you update to the latest one (2.2.0) in order to check if the problem persists.

**Comment by filerun** [comment]
The problem seems fixed in the newer version, thanks @jesmrec . To be honest, I avoided the official version because of the annoying payment process. I really don't understand what is the point of charging any money for the app, when it doesn't really bring anything more than the available free ones (including the Nextcloud app).
