### ISSUE TITLE
Need improvement UI of edit_box_dialog

### ISSUE THREAD

**Issue by AkshitKrNagpal** [owncloud/android#1872]
### Actual behaviour
The EditText in edit_box_dialog.xml has no margin, hence it doesn't look good.

![whatsapp image 2016-12-31 at 11 45 41 pm](https://cloud.githubusercontent.com/assets/15872348/21578791/8a4101a4-cfb3-11e6-9f60-1d5ea62404f8.jpeg)
 

### Expected behaviour
It should atleast have some marginLeft and marginRight having @dimen/standard_margin

![whatsapp image 2016-12-31 at 11 45 41 pm 1](https://cloud.githubusercontent.com/assets/15872348/21578801/1478d9c8-cfb4-11e6-8dd7-a55165da71dd.jpeg)

Thanks

**Comment by davivel** [comment]
Ready to go with 2.4.0. Thanks again, @cinnamonsalt
