### ISSUE TITLE
ownCloud Android login to NextCloud 11 servers fails - linked issue recorded below - NC Android has fixed this

### ISSUE THREAD

**Issue by ShamimIslam** [owncloud/android#1874]
### Actual behaviour
-"An unknown error occurred" response on login attempt

### Expected behaviour
-Login should take place like in the ownCloud 2.2.4 desktop application
 
### Steps to reproduce
1. Attempt to log into NextCloud 11 with ownCloud Android 2.2.0
2. Fail

https://github.com/nextcloud/android-library/issues/18
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: Marshmallow

Device model: S7 Galaxy

Stock or customized system: Stock

ownCloud app version:

ownCloud server version:

#### Web server error log : None
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log): Nothing reported
```
Insert your ownCloud log here
```

**Comment by davivel** [comment]
@ShamimIslam , thanks for the tip. This is a duplication of #1874. 

Will be ready in version 2.3.0 of the ownCloud for Android app.
