### ISSUE TITLE
[UX] Main/settings menu only accessible from root folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#1875]
### Steps

1. Navigate into a deep folder
1. From another app, upload some stuff using the "share" feature and picking ownCloud
1. Wait for upload to finish and all notifications to disappear
1. Now I want to go have a look at the upload list

### Expected
When inside a deep folder, I'd like to have a way to go to the main menu.

### Actual
No way to go to the main menu directly.
Need to click the "Back" button on the top left of the mobile app until I reach the root folder.
Only then can I access the upload list.

I'm not familiar with the regular Android app design, maybe the current approach is an existing and acceptable design pattern.

Now you might say that it's not a common use case to want to access the finished upload list and that it's ok to have that menu item there.

To be discussed.

@davivel @owncloud/design

**Comment by jesmrec** [comment]
It is possible by opening the drawer and tapping on "All files". You will be redirected to the account root folder (wording issue?)

Being a not common use case, this shortcut maybe enough :)

**Comment by AndyScherzinger** [comment]
@PVince81 @jesmrec it is a standard Android drawer implementation, so you can always swipe from the far left of the screen to the right 😉

**Comment by PVince81** [comment]
Argh... seems I haven't been using enough Android apps lately. Indeed, swiping from the far left of the screen brings in the menu with "Uploads" regardless of which folder I am in.

Feel free to close as user error 😉
