### ISSUE TITLE
App crash when entering a folder

### ISSUE THREAD

**Issue by chucklz1515** [owncloud/android#1878]
### Actual behaviour
The app will crash when trying to open a specific folder for any time after the first try (I can open the folder exactly once after I install the ownCloud app. After that if I try to open the folder it crashes). This only applies to one folder. All of the other folders work fine. The name isn't anything weird (name of folder is "pass"). The folder has worked fine since version 2.1.1 of the android app. The only contents of the folder are 2 files. The folder is remembered by another app, but like I said it was working fine before.

### Expected behaviour
The folder should open every time without crashing.
 
### Steps to reproduce
1. Install ownCloud Android app.
2. Sync to existing ownCloud server.
3. Open folder named "pass" once.
4. Close app, or navigate away and try to enter folder named "pass" again.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, the demo site was broken (kept redirecting to www site) at this time.

### Environment data
Android version: 6.0 (Android security patch level: 2016-07-01)

Device model: LG-H812

Stock or customized system: Stock Android 6.0 (Marshmallow)

ownCloud app version: 2.2.0

ownCloud server version: 9.1.2 (stable)

#### Web server error log
```
<None pertaining to that folder>
```

#### ownCloud log (data/owncloud.log)
```
<cannot find android app logs>
```

**Comment by heaven988** [comment]
I think i have the same problem. I install the 2.1.2 via F-Droid.

**Comment by davivel** [comment]
> The folder is remembered by another app

Could you explain a bit more what does that mean? What app is that? Why does it remember it?

Are the two files in that folder downloaded in your device?

Is the folder being used as the target of instant uploads in the settings of the ownCloud Android app?

**Comment by chucklz1515** [comment]
The app that remembers the folder is KeepPassDroid as my password db is in there.
The two files can be downloaded to the device only by choosing to keep the entire folder offline.
The folder is not being used for instant uploads.

I have now also noticed this bug in other folders that just hold music. There does not seem to be any pattern to which folders are inaccessible. There are no file locks on the ownCloud server.

**Comment by jesmrec** [comment]
@chucklz1515 is this problem still reproducible?

**Comment by chucklz1515** [comment]
@jesmrec unfortunately no.

I can no longer access this phone as it stopped turning on a year and a half ago prompting me to buy a Xiaomi.

I also switched to Nextcloud.

**Comment by jesmrec** [comment]
thanks for responsing.
