### ISSUE TITLE
Application crash at start

### ISSUE THREAD

**Issue by heaven988** [owncloud/android#1883]
### Actual behaviour
- I have an Owncloud 9.1.1 on my server and the latest release of Owncloud on Google Play. Since several weeks (maybe 4 ?!), i can't log with my account on Owncloud-Android (the App crash during the first load). I had uninstall, reinstall many times and i always have this behaviour. I made a test account on my server and try to log with it, and it work fine. It seems to be related to my account (who is also admin for all the owncloud server...). I have 40gb use, more than 2tb free, many external storage (i try to deactive them, no change). That's all...
i couldn't try yet with another android device (mine is a Xperia Z1 compact on Android 5.1.1, rom stock)
I can connect with my account on the web interface, with owncloud desktop for Windows, with Webdav FileManager, with Thunderbird for Windows,,...

### Expected behaviour
- It should work with my admin account like before, i don't know what is the problem here...
 
### Steps to reproduce
1. install owncloud after a cleanup (deinstall, delete all the files, clean the cache, reboot)
2. Use my admin account of my Owncloud 9.1.1 server
3. Start the application
4. Crash (always !)

Can this problem be reproduced with the official owncloud server? No
(url: https://demo.owncloud.org, user: test, password: test) 

### Environment data
Android version: 5.1.1

Device model: Z1 compact

Stock or customized system: Stock

ownCloud app version: 2.2.0

ownCloud server version: 9.1.1

#### Web server error log
```
Nothing to show and related with my try...
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by heaven988** [comment]
I have made many test : 
like a say in my previous post : with a test account (test ; test), it work on my personnal phone.
In another phone (android 6), it work fine with the test account and with the admin account).

But it can't work anymore with my admin account on my personnal phone. No idea why... Can someone help me in order to find the problem ?

**Comment by davivel** [comment]
@heaven988 , did you send the crash to Google App Store?

**Comment by davivel** [comment]
@jesmrec , @davigonz, @rperezb , this could be important. Seems the top 1 in Play Store. 

@heaven988 , do you have other apps that connect to your ownCloud server in the device? Calendar or contact apps, for instance?

**Comment by heaven988** [comment]
@davivel yes, i send many time the crash report !

You've got a interesting idea. Indeed, i am using calendar and contact on my admin account, and for using them i use Caldav Sync (https://play.google.com/store/apps/details?id=org.dmfs.caldav.lib) and Carddav Sync (https://play.google.com/store/apps/details?id=org.dmfs.carddav.sync) on my personnal phone.

If this can help, i can try this week-end to uninstall them and test owncloud 2.2.0 again.

**Comment by davivel** [comment]
@heaven988 , let's try something easier first.

Go to your device settings, select 'Apps', find and select 'ownCloud', and then tap 'Permissions'. If I'm not wrong, you will find the 'Contacts' permission enabled.

Disable it, and try to open the app again.

If there is no crash, just let the permission disabled. The app doesn't really need it. 

There is a real bug to fix, but this is a safe work around.

**Comment by davivel** [comment]
Wait, your device is 5.1. , it still doesn't have dynamic permissions.

In that case, check if Caldav Sync and Carddav Sync allow you to change the name of the accounts in them. Some apps allow to do so (sorry, ownCloud is not one of them).

**Comment by davivel** [comment]
@jesmrec , FYI: 

STEPS TO REPRODUCE:
 1. In the OC app, create an account to a server with version 9.1.0 or greater.
 2. Install an app that allows to create accounts with any name; I used https://f-droid.org/repository/browse/?fdfilter=davdroid&fdid=at.bitfire.davdroid .
 3. Create an account in that app; I created an account to connect to the contacts app of owncloud, using the URL https://[dowain]/[oc_path]/remote.php/dav . The account doesn't have to be in the same server or user than the OC account of step 1.
 4. Before finishing the account creation, DavDroid allows you to choose the name of the account. Enter the same name of the OC account in step 1, as shown in the navigation drawer under the user name.
5. If your device has Android 6.0 or later, open device settings, 'Apps' , 'ownCloud', 'Permissions' and enable 'Contacts' permission.
6. Tap the 'square' button and kill the OC app ,
7. Start the OC app. Change to the account created in step 1 if it's not shown by default.

EXPECTED BEHAVIOUR
- Root folder is refreshed and shown to the user

CURRENT BEHAVIOUR
 - CRASH.

**Comment by heaven988** [comment]
Hello,
i have some news.
First i try to restrict access to Calendar and Contact with XPrivacy (module of Xposed). It didn't work and owncloud still crash at start (should i try to restrict other things ?)

I wanted to know if there is a relation in order to follow your lead, so i uninstall Caldav and Carddav (hard way !), and now owncloud stop crashing !

So we can say that you find the problem, but not the solution for now...

**Comment by heaven988** [comment]
Okay this is weird, but just for information.
After reinstalling Caldav and Carddav-sync, configuring them with my account as before, everything work fine.
Caldav | Carddav | Owncloud 2.2.0 (not crashing anymore)

I hope all my feedback help.

**Comment by jesmrec** [comment]
Thank you @heaven988. A fix has been developed and it will be released in next version.

**Comment by neuhausjulian** [comment]
@heaven988 I had the same problem. Your solution with reinstalling Caldav and Carddav worked also for me. thanks a lot
