### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by akashdeepsingh9988** [owncloud/android#1887]
Gradle sync failed: Configuration with name 'default' not found error shows when i try to build the owncloud app. Every time i trying to build the error is shown.

**Comment by davivel** [comment]
Hi, @akashdeepsingh9988 . Are you using Android Studio or gradle in command line to build the app? What version of Android Studio? 

What version of Android Platform tools are you using? What version of Android build tools?

**Comment by whrwhr446** [comment]
I have problem too,how to solve?

**Comment by akashdeepsingh9988** [comment]
**whrwhr446**  Download or clone project using git desktop instead of downloading zip file. The exported  zip file cause errors while building project.

**Comment by Ettingshausen** [comment]
Try to execute `git submodule update --init`
It works for me

**Comment by davivel** [comment]
Yes, please, take a look to https://github.com/owncloud/android/blob/master/SETUP.md .

Thanks to everybody for share your self-advance with others. That's what makes community :)
