### ISSUE TITLE
instant upload,  camera directory not selectable in root

### ISSUE THREAD

**Issue by seisen** [owncloud/android#1888]
### Actual behaviour
go to instant upload abd change camera directory to /, you are stuck in ut,  no subdirectory is shown 
 
### Steps to reproduce
1.  change camera directory to /
2. now,  no subdirectory is shown,  you are stuck in /

### Environment data
Android version: 7.0

Device model: Sony XZ

Stock or customized system: stock

ownCloud app version: 2.2.0

**Comment by davivel** [comment]
Yeah, Android is making weird things with file system in Android 7... we'll have to give a look.

**Comment by kokangit** [comment]
I experience that same problem on ownCloud Android-app version 2.4.0 on Sony Xperia Z5. Android version 7.1.1.
Is there a work around to this?

**Comment by brianmichalk1** [comment]
I am also having the same problem.  Where is the configuration file with this path setting?  That should be a workaround.

**Comment by theScrabi** [comment]
This issue does not ocure to me in the current version 2.6.0. 
@seisen do you experience this still? Maybe this can be closed.

**Comment by theScrabi** [comment]
![gurken](https://user-images.githubusercontent.com/1891273/38493806-c203dcbc-3bf3-11e8-9b36-a9f7ed80f3ca.gif)

**Comment by peted2** [comment]
Android version: 7.1.2

Device model: Motorola Moto G 2014

Stock or customized system: LOS 14.1

ownCloud app version: 2.7.0


I experience the same issue.
Pretty annoying since the Phones internal storage is limited and i cannot use the preset internal Camera folder.
I need to select external storage. This is impossible due to this bug.

**Comment by peted2** [comment]
until the fix is implemented, would it be feasable to create a symlink in the root dir pointing to the camera folder? which permissions would have to be set to this symlink?

**Comment by theScrabi** [comment]
@peted2 my fix will only bring you back to home after you accesd root. You should already be able to access your sdcard. What is in your `/storage` folder?

**Comment by peted2** [comment]
when i access it with any file explorer app, i can see /storage/external-sd-card-number /storage/emulated and storage/self 

Unfortunately inside the app i am already stuck to /

@theScrabi is there any way to contact you more directly?

**Comment by jesmrec** [comment]
This fix will be released in 2.8.0
