### ISSUE TITLE
App is minimized with drawer button

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1889]
Only reproducible with a tablet

### Steps to reproduce
1.  Set the tablet in landscape.
2. Download a pdf file. Also happens with files not "openable" that shows the details view in the right fragment.
3. File is downloaded, and the options to open it (external apps) are displayed
4. Tap on "<-" to ellipsize those options 
5. Tap on drawer button

### Actual behaviour
App is minimized

### Expected behaviour
Drawer is opened
 
Here is the performance:

![jan-23-2017 14-29-10](https://cloud.githubusercontent.com/assets/14894746/22205914/3e7a68be-e179-11e6-9cd5-ca673f53846b.gif)

Checked in Android 5
Galaxy Tab S2

**Comment by davivel** [comment]
![wtf_jackie_chan](https://cloud.githubusercontent.com/assets/2225614/22518684/c8ae34d0-e8ad-11e6-915a-4cb2e2ec6a02.jpg)

**Comment by cinnamonsalt** [comment]
@jesmrec
Reason for this behavior: App checks if root folder is opened or file fragment is visible and then calls onBackPressed. The case where both are displayed on a tablet was not handled.
Fixed in PR #1938

**Comment by jesmrec** [comment]
@cinnamonsalt thanks a lot for the contribution!

**Comment by davivel** [comment]
Merged.
