### ISSUE TITLE
Disable preview on tablet in wide-screen.

### ISSUE THREAD

**Issue by mbrinkmann** [owncloud/android#1890]
### Actual behaviour
- ownCloud APP on tablet shows a preview-area if you hold the tablet vertically

### Expected behaviour
- I would like to have the possibility to disable this to see longer file-names.
 
### Steps to reproduce
1. Open ownCloud App
2. Browse any Folder
3. Turn the tablet

### Environment data
Android version:
Every tested (5.0 and upwards)

Device model: 
Acer Iconia A3-40

Stock or customized system:
Stock

ownCloud app version:
2.2.0

ownCloud server version:
9.1.2 (stable)

**Comment by davivel** [comment]
>  if you hold the tablet vertically

I guess that's a typo and you meant 'horizontally' :)

I know what you mean. We need a better, more flexible layout for tablets.

**Comment by mbrinkmann** [comment]
of course you are right, sorry ;p
Thanks for your understanding.

**Comment by fokkejacobi** [comment]
+1
Also when using raster view to review your images, the preview panel is useless.

**Comment by theScrabi** [comment]
> Also when using raster view to review your images, the preview panel is useless.

Absoloutly, and its also completely out of trend. No other files app does two panels anymore. So I remove it.

**Comment by theScrabi** [comment]
@michaelstingl Your opinion pls:
![screenshot_2018-04-05-12-33-59](https://user-images.githubusercontent.com/1891273/38361717-a21fdd6a-38ce-11e8-9d6d-c899543b1003.png)

**Comment by michaelstingl** [comment]
Sounds like a good approach. Go for it! 👍

**Comment by davigonz** [comment]
It will be included in 2.8.0
