### ISSUE TITLE
Can't download any file by Android application

### ISSUE THREAD

**Issue by dragu** [owncloud/android#1892]
### Actual behaviour
- I cant download any file using android app. I have checked official android client and Cirrus.
After selecting file I see this http://i64.tinypic.com/25sc5dt.png and notification: http://i65.tinypic.com/2vrx0ux.png about download failed.
Server logs looks OK (it is other fail but all looks the same, I just have checked multiple files).

I can download the files with curl requests and headers seems to be ok.

```

$ curl 'https://myhost/remote.php/webdav/Formularz%20rejestracji%20ZUS.odt ' --head --user ?:?
HTTP/1.1 200 OK
Date: Sun, 29 Jan 2017 11:27:14 GMT
Content-Type: application/vnd.oasis.opendocument.text
Content-Length: 18341
Connection: keep-alive
Set-Cookie: __cfduid=tasty; expires=Mon, 29-Jan-18 11:27:14 GMT; path=/; domain=.myhost; HttpOnly
Set-Cookie: oc701d8buhph=tasty; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=xyz; path=/; secure; httponly
Content-Security-Policy: default-src 'none';
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Set-Cookie: oc701d8buhph=tasty; path=/; secure; HttpOnly
Set-Cookie: cookie_test=test; expires=Sun, 29-Jan-2017 12:29:17 GMT; Max-Age=3600
Last-Modified: Tue, 12 Jul 2016 17:14:15 GMT
ETag: "7ac50d041a08f5a3cacf17b6454750b3"
Content-Disposition: attachment; filename*=UTF-8''Formularz%20rejestracji%20ZUS.odt; filename="Formularz%20rejestracji%20ZUS.odt"
Content-Disposition: attachment; filename*=UTF-8''Formularz%20rejestracji%20ZUS.odt; filename="Formularz%20rejestracji%20ZUS.odt"
OC-ETag: "7ac50d041a08f5a3cacf17b6454750b3"
X-Cacheable: NO
X-Varnish: 17269385
Age: 0
Via: 1.1 varnish-v4
X-Cache: MISS
Strict-Transport-Security: max-age=0
Server: cloudflare-nginx
CF-RAY: 328c5570bb5d6afb-WAW

```

### Expected behaviour
- File should be downloaded and opened
 
### Steps to reproduce
1. Open app
2. Tap any file

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

No because there is no demo installation.

### Environment data
Android version: 6.0.1

Device model: Note 4 SM-N910C

Stock or customized system: stock

ownCloud app version: 2.2.0

ownCloud server version: 9.1.3.1

#### Web server error log
```
> 127.0.0.1 - xdxd [29/Jan/2017:12:27:43 +0100] "GET /remote.php/webdav/Formularz%20rejestracji%20ZUS.odt HTTP/1.1" 200 19564 "-" "Mozilla/5.0 (Android) synox-android/1.0.7"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Er+DHckQ+kJSVB2a8RbN","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Data is not in a recognized format at \/var\/www\/owncloud\/lib\/private\/legacy\/image.php#574","level":3,"time":"2017-01-30T08:03:39+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/512\/512\/avatar2.jpg?modified=1462997243000&rid=00019435oc701d8buhph","user":"xdxd"}

(after deleting this file there is no new entries in log)

```

**Comment by davivel** [comment]
Hi, @dragu.

Did you notice this problem right after upgrading to version 2.2.0 of the app?

Did you make any recent change in your server configuration?

Are you using desktop client too? Downloads work fine there?

Did you check the free space in your device?

Did you check if the permissions of the app were changed without notice? Please, take a look to device settings > 'Apps' > ownCloud > 'Permissions' ; 'Storage' permission should be enabled.

**Comment by dragu** [comment]
> Did you notice this problem right after upgrading to version 2.2.0 of the app?

I don't know, didn't use this feature long time.

> Did you make any recent change in your server configuration?

Upgrades, adding Varnish http proxy

> Are you using desktop client too? Downloads work fine there?

Yes, downloading on ubuntu and windows works fine.

> Did you check the free space in your device?

~ 1 GB free

> Did you check if the permissions of the app were changed without notice? Please, take a look to device settings > 'Apps' > ownCloud > 'Permissions' ; 'Storage' permission should be enabled.

It is, only contacts permission is disabled

**Comment by davivel** [comment]
Contacts permission is not relevant, ignore it, please.

Could you test the downloads disabling Varnish? 

Thanks.

**Comment by daniell-balabit** [comment]
I have exactly the same problem (but not using eg. Varnish).

I just uploaded a file, it is on the server, I can download it via a web browser, but the Android application fails to do so.

The downloading progress bar (in the App) seems to reach the end, it seems it's finished, but I get a notification saying "Download failed. Download of $filename could not be completed.". And the app doesn't offer me another application at the bottom of the Activity to open it with (eg. a PDF viewer).

Meanwhile I get this in the server logs:
```
[31/May/2017:09:38:13 +0200] "GET /owncloud/remote.php/webdav/filename HTTP/1.1" 200 0
```
If I inject this path into my browser, after I provide the authentication information to the browser it downloads the file, and it's not corrupt or anything.

Everything else seems to work, eg. deleting:
```
[31/May/2017:09:40:54 +0200] "DELETE /owncloud/remote.php/webdav/DGP641-EU06.pdf HTTP/1.1" 204 0
[31/May/2017:09:40:55 +0200] "DELETE /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 204 0
```

For a full example, after uploading one of the same files I just deleted...:
```
[31/May/2017:09:42:42 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 0
[31/May/2017:09:42:42 +0200] "PROPFIND /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 404 0
[31/May/2017:09:42:43 +0200] "PUT /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 201 0
[31/May/2017:09:42:44 +0200] "PROPFIND /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 207 0
```
... when I try to download it in the Android app, it fails, and I get this in the server logs:
```
[31/May/2017:09:43:24 +0200] "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "GET /owncloud/status.php HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "GET /owncloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "GET /owncloud/index.php/avatar/daniell/448 HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 0
[31/May/2017:09:43:25 +0200] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%252F%26reshares=true%26subfiles=true HTTP/1.1" 200 0
[31/May/2017:09:43:26 +0200] "GET /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 200 0
```

**Comment by levaidaniel** [comment]
I have exactly the same problem (but not using eg. Varnish).

I just uploaded a file, it is on the server, I can download it via a web browser, but the Android application fails to do so.

The downloading progress bar (in the App) seems to reach the end, it seems it's finished, but I get a notification saying "Download failed. Download of $filename could not be completed.". And the app doesn't offer me another application at the bottom of the Activity to open it with (eg. a PDF viewer).

Meanwhile I get this in the server logs:
```
[31/May/2017:09:38:13 +0200] "GET /owncloud/remote.php/webdav/filename HTTP/1.1" 200 0
```
If I inject this path into my browser, after I provide the authentication information to the browser it downloads the file, and it's not corrupt or anything.

Everything else seems to work, eg. deleting:
```
[31/May/2017:09:40:54 +0200] "DELETE /owncloud/remote.php/webdav/DGP641-EU06.pdf HTTP/1.1" 204 0
[31/May/2017:09:40:55 +0200] "DELETE /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 204 0
```

For a full example, after uploading one of the same files I just deleted...:
```
[31/May/2017:09:42:42 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 0
[31/May/2017:09:42:42 +0200] "PROPFIND /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 404 0
[31/May/2017:09:42:43 +0200] "PUT /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 201 0
[31/May/2017:09:42:44 +0200] "PROPFIND /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 207 0
```
... when I try to download it in the Android app, it fails, and I get this in the server logs:
```
[31/May/2017:09:43:24 +0200] "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "GET /owncloud/status.php HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "GET /owncloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "GET /owncloud/index.php/avatar/daniell/448 HTTP/1.1" 200 0
[31/May/2017:09:43:24 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 0
[31/May/2017:09:43:25 +0200] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%252F%26reshares=true%26subfiles=true HTTP/1.1" 200 0
[31/May/2017:09:43:26 +0200] "GET /owncloud/remote.php/webdav/panel-5295.pdf HTTP/1.1" 200 0
```

**Comment by levaidaniel** [comment]
Still an issue with ownCloud Android app 2.5.0.

**Comment by levaidaniel** [comment]
Still an issue with ownCloud Android app 2.5.0.

**Comment by jesmrec** [comment]
Is this problem still reproducible?

**Comment by dragu** [comment]
I still have this issue with mobile client 2.6.0 and 9.1 server

**Comment by jesmrec** [comment]
could you send us a test account in your server? to check from here where the problem can be. You can ship it to apps@owncloud.com, pointing in the message to this issue.

**Comment by jesmrec** [comment]
I have checked your test account and the main differences i noticed with out test 9.1.6 server are:

- Your server returns a cookie:                     

>__cfduid=xxxxxx; expires=Wed, xx-xxx-xx xx:xx:xx  GMT; path=/; domain=.xxxxx; HttpOnly

that should not affect the fact the file is not downloaded. 

- The request returns a header `X-Cacheable NO`, not standard afaik.

Are there any noticeable setup in your environment that could affect?

**Comment by dragu** [comment]
Cookie comes from cloudflare, X-Cacheable is header from Varnish telling that page is not cached, what is wrong with this header?

**Comment by jesmrec** [comment]
nothing is wrong ftm, only checking differences between your server and other one with the same version and same app version, where downloads are correctly done.

**Comment by jesmrec** [comment]
No news from a long time. Feel free to reopen if the problem persists today

**Comment by JohnHardline** [comment]
sané problem here - cant download any files with the android app
