### ISSUE TITLE
Avoid unnecessary downloads when files are already present on the device

### ISSUE THREAD

**Issue by mvglasow** [owncloud/android#1899]
### Actual behaviour
-When files are available offline (green check mark) and are “set as available offline”, they are downloaded again even if they haven’t changed.

### Expected behaviour
-When files/folders are being made available offline and an up-to-date local copy already exists, skip those files
 
### Steps to reproduce
1. Create a folder on the server with a couple of files in it.
2. Select a few of those files to be available offline, let them sync and check for success.
3. Set the entire folder to be available offline.

Or:
1. Set a file to be available offline, let it sync and check status.
2. Unset “available offline” (this will clear the yellow arrow but the file will remain on the device, the green arrow still shows and the file is still present).
3. Set the file to be available offline again.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Not tested.

### Environment data
Android version: 7.1.1

Device model: OnePlus One

Stock or customized system: LineageOS 14.1-20170123-NIGHTLY-bacon

ownCloud app version: 2.2.0

ownCloud server version: 9.1.3

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by dhirajhimani** [comment]
I tried it with https://my.owndrive.com/ account and its not reproducable

**Comment by davigonz** [comment]
Hi @mvglasow , thank you for opening this issue with the detailed info. I've been carefully trying to reproduce the same scenario but the error "File contents already synchronized" is shown and the file is not downloaded again.

Could you please add some logs of the Android app which are included in the device folder data/owncloud.log? It would be very helpful.
