### ISSUE TITLE
Take a photo and upload directly to some ownCloud folder + sharing options + shortcut on the screen

### ISSUE THREAD

**Issue by mrow4a** [owncloud/android#1900]
I think very useful feature could be possibility of quickly doing some photo on the mobile and have a possibility of instantly sharing it by link or place in some sync folder. 

I would be very grateful for such a feature.

**Comment by michaelstingl** [comment]
@mrow4a Android app can be configured to upload every image to your ownCloud instantly. I use https://scanbot.io/ too which can save directly in a previously specified ownCloud folder.

**Comment by mrow4a** [comment]
@michaelstingl What about instant shared link generation or like sending as a message on facebook etc? After photo, it will take 5 minutes to create share in ownCloud app, and then sending back to messenger or whatever else you want.

**Comment by michaelstingl** [comment]
@mrow4a This sounds like a cool feature for a 3rd party camera app. Or how do you think this can be integrated in the oC Android app?

**Comment by mrow4a** [comment]
@michaelstingl I am just suggesting that something like that could be useful, if you will search for some Hackweek/whatever project for other students if not implemented as a feature :> I been programming on android already, but doubt will find a time.

**Comment by davivel** [comment]
I would like to more some more details about how you imagine it, @mrow4a .

If I take a picture with my camera app and it's automatically pushed to ownCloud and a share link generated, how I choose then the recipient of the link? After taking the picture I probably would take more pictures, or change to other app, or just stop using the mobile. A pop up from ownCloud app then would be too intrusive. A notification in the top bar to allow sharing? Isn't it too specific?

**Comment by davigonz** [comment]
Hi @mrow4a , the first idea of what you describe here is being currently implemented in https://github.com/owncloud/android/issues/2027

**Comment by jesmrec** [comment]
Already implemented and available from 2.7.0.
