### ISSUE TITLE
Include sorting method in file picker view when uploading

### ISSUE THREAD

**Issue by hutber** [owncloud/android#1911]
### Actual behaviour
When in the `Upload` file view all files are sorted `Oldest First`. This means a very long time to scrolling to the bottom of the view.

### Expected behaviour
Have the option to sort how desired
or simply sort by newest first
 
### Steps to reproduce
1. Select a folder
2. Click the `+`
3. Have to scroll down

### Environment data
Android version:
All
Device model: 
N/a

**Comment by davivel** [comment]
> When in the Upload file view all files are sorted Oldest First

Really? This could be a bug. 

Didn't we implement as 'Newest first', @jesmrec ?

**Comment by jesmrec** [comment]
@davivel i think that @jamiehutber means the folder picker view.

The uploads view is sorted by "Newest first".

**Comment by jamiehutber** [comment]
Ye, I was just going to say. You have updated the file view, but its when you are picking files as very often my instant upload fails the upload. I'd say around 40% of the time.

**Comment by davivel** [comment]
Oh, I see. Seems an interesting proposal. 

> very often my instant upload fails the upload. I'd say around 40% of the time.

Sorry to read that. What is the problem, they fail in the upload or they are not even detected by the app?

What's your model device and Android version? There are some issues open about instant uploads in the repository, maybe one of them is of your interest, just to track improvements in the instant uploads.

**Comment by jamiehutber** [comment]
Ye, its very `upsetting` :p when having to scroll for 40 seconds to get to the bottom and even then, I end up at the bottom of the videos when I want to manually upload the images that haven't sync'd properly.

ye :D I don't think those problems are in scope for this ticket. I will do some searching.

Just to say, they sometimes aren't detected, other times they fail mid way through upload I believe. All through wifi, `Nexus 5x` and latest version of android.

**Comment by jamiehutber** [comment]
`[Wed Mar 22 13:06:03.628470 2017] [:error] [pid 355] [client 77.103.45.148:62896] PHP Fatal error:  Uncaught RedisException: Redis server went away in /var/www/owncloud/lib/private/Memcache/Redis.php:51\nStack trace:\n#0 /var/www/owncloud/lib/private/Memcache/Redis.php(51): Redis->get('be9e4cc67e0e3a1...')\n#1 /var/www/owncloud/lib/autoloader.php(145): OC\\Memcache\\Redis->get('OC_User')\n#2 [internal function]: OC\\Autoloader->load('OC_User')\n#3 /var/www/owncloud/lib/private/Log/Owncloud.php(97): spl_autoload_call('OC_User')\n#4 [internal function]: OC\\Log\\Owncloud::write('PHP', 'Uncaught RedisE...', 3)\n#5 /var/www/owncloud/lib/private/Log.php(294): call_user_func(Array, 'PHP', 'Uncaught RedisE...', 3)\n#6 /var/www/owncloud/lib/private/Log.php(152): OC\\Log->log(3, 'Uncaught RedisE...', Array)\n#7 /var/www/owncloud/lib/private/Log/ErrorHandler.php(67): OC\\Log->critical('Uncaught RedisE...', Array)\n#8 [internal function]: OC\\Log\\ErrorHandler::onShutdown()\n#9 {main}\n  thrown in /var/www/owncloud/lib/private/Memcache/Redis.php on line 51
`

**Comment by sd1998** [comment]
@jesmrec Can I work on this?

**Comment by sd1998** [comment]
@jesmrec What are the different sorting criteria's should I use? For ex:- newest first, older first etc.

**Comment by jesmrec** [comment]
the same in the file list, if it is posible. Have a look at the option in three-dot-button menu.

**Comment by davigonz** [comment]
Just updated the name of this issue to avoid misunderstandings. So the files here should appear sorted by newest first at least. Additionally, more sorting options could be included.
