### ISSUE TITLE
Automatic upload not working under Nougat on Sony Xperia Z5 Compact

### ISSUE THREAD

**Issue by cschwarz007** [owncloud/android#1912]
### Actual behaviour
-Tell us what happens
The app (which used to work under 6.x) does not upload pictures taken by the camera anymore automatically after updating my Z5 Compact to Nougat...

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hi @cschwarz007, thank you for your comment. There is already an issue opened about this topic so I've just closed this one, please check: https://github.com/owncloud/android/issues/1829
