### ISSUE TITLE
Does not work with Android Nougat Samsung Galaxy S7

### ISSUE THREAD

**Issue by alkanbw** [owncloud/android#1918]
### 
When will be working version for Android Nougat 
On Dans7ng Galaxy S7 does not work upload photos and videos from camera.
### Expected behaviour
-Tell us what should happen
 I am using stock camera and from Android version 7.0 does not uploading making photos.
Now Owncloud apk is totaly useless.
On my smartphone there is no problem with Qnap apk qfile. It always send my photos into my owncloud server.
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
Hi @alkanbw, thank you for your valuable feedback. There is already an issue opened about this topic, so I will close this one. Please check: #1829
