### ISSUE TITLE
(As an ownCloud Android user I want) input elements to keep their size and position

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#192]
Currently the big refresh icon increases the size of the Server address input field, and hence also pushes everything else down.

Instead, the input field should keep its size. The icon could be a bit smaller (tappable area should still be big enough though!). It’s your call – maybe there’s a standard Android refresh-button-inside-of-input-field element?

**Comment by davivel** [comment]
Sorry, but this is not fixed yet. Checked with Nexus 5, Android 5.0.1. In case of doube, enable "Show layout bounds" in the developer settings of the device.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger maybe you can verify if this is still the problem after your fabulous material update?

**Comment by AndyScherzinger** [comment]
Problem still existed and has been fixed in PR #1163 (which I targeted for 1.8 now) - merge depends on @rperezb @davivel and @masensio I guess

**Comment by masensio** [comment]
PR #1163 merged so this issue is fixed
