### ISSUE TITLE
Does not work with Android Nougat Samsung Galaxy S7

### ISSUE THREAD

**Issue by alkanbw** [owncloud/android#1920]
### 
When will be working version for Android Nougat 
On Dans7ng Galaxy S7 does not work upload photos and videos from camera.
### Expected behaviour
-Tell us what should happen
 I am using stock camera and from Android version 7.0 does not uploading making photos.
Now Owncloud apk is totaly useless.
On my smartphone there is no problem with Qnap apk qfile. It always send my photos into my owncloud server.
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:
Android Nougat 7.0
Device model: 
Samsung Galaxy S7
Stock or customized system:
G930FXXU1DQB7
ownCloud app version:
Latest from market 2.3.0
ownCloud server version:
8.0.4
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
Hi @alkanbw ownCloud 8.0.x is EOL since 2016-10 (see [Maintenance and Release Schedule](https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule)), but your description sound very much like a known issue, so I will close this one. Please check: #1829

**Comment by davivel** [comment]
As @michaelstingl said, this issue is duplicating #1829. Please, @alkanbw , see any update there.

THanks,.
