### ISSUE TITLE
Instant upload does not work any longer

### ISSUE THREAD

**Issue by moulip** [owncloud/android#1924]
Hi,

## Actual behaviour
Since I have updated my S7 Edge to Nougat 7.0, the auto-instant upload does not work any longer.
I mean nothing happens not even the cloud icon appearing and throwing an error, nothing.
I have tried reinstalling the app, restoring the phone to factory settings, try to check on wifi only or no, nothing is working. That's a shame considering the role of a cloud application. But it works well on my other phone a Huawei P9 Lite running Android 6.0.1.

 
### Steps to reproduce
1. Setup the app to autoupload photos and videos
2. take a photo
3. check that nothing is happening

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

yes

### Environment data
Android version: 7

Device model:  Samsung S7 EDGE

Stock or customized system: STOCK 

ownCloud app version: 2.3.0

ownCloud server version: 8.2.10

**Comment by sastorsl** [comment]
Had the exact same issue on Samsung Galaxy S7.
Went into settings in Owncloud and updated the picture storage directory - it seems to have changed - and owncloud crashed immediately. After that I've been unable to open the app. I've tried to uninstall, delete settings, everything.
