### ISSUE TITLE
Owncloud GUI does not respond to touch

### ISSUE THREAD

**Issue by kimlid** [owncloud/android#1929]
### Actual behaviour
Happened on several different occasions that the GUI just stops responding to touch for a few hours or days. Happened when at Home on WiFi and outside on 4G. Reboot does not help.

Right now I'm not able to "click" on folders or settings menu in the Owncloud app.

### Expected behaviour
Just be able to browse folders and look at pictures or change settings. The app should respond to touch.
 
### Steps to reproduce
Not sure if its reproducable, it happens randomly.
It happened 4 weeks ago for a few days and today I had issues once again.
I didn't do anything special to solve it the last time.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

Not able to test since I can't change settings within the app at the moment.

### Environment data
Android version: 7.1.1 

Device model: Nexus 6p

Stock or customized system: Stock

ownCloud app version: 2.3.0

ownCloud server version: 9.1.3

#### Web server error log
```
Insert your webserver log here --- n/a
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here --- n/a
```

**Comment by davivel** [comment]
@kimlid, could you have a look to the apps pointed to by @michaelstingl ? Thanks.

**Comment by kimlid** [comment]
Hi, sorry for the delay, no Im not using lux.

**Comment by kimlid** [comment]
Not bluelight filter or any bluelight app.

**Comment by davivel** [comment]
Any other app that could set some kind of (semi)transparent overlay on the device?

Do you screen recorders, or screen casters, or do you share the screen of the app with some device similar to Chromecast?

**Comment by kimlid** [comment]
No, I do not. 

And the issue seems to come and go, I havent had the issue for a couple of weeks now, that has happened before and then it comes back. 

I rarely download new apps and therefore even more rarely remove apps, so it does not seem to be another app that interferences with the owncloud app.

**Comment by leafcutterant** [comment]
I had this behavior while using [Twilight](https://play.google.com/store/apps/details?id=com.urbandroid.lux). I have to pause the screen filter to be able to navigate in the OwnCloud app, but then it works.

**Comment by jesmrec** [comment]
Incoming version 2.10 will include a Setting option to skip obscuration from apps like Twilight

**Comment by michaelstingl** [comment]
2.10 with config option to allow this got released in the Play Store:
https://central.owncloud.org/t/owncloud-2-10-for-android-released/18900

**Comment by jesmrec** [comment]
I hope the new option fixed the problem. Otherwise, reopen.
