### ISSUE TITLE
OC Audio player crushes in long audio sessions

### ISSUE THREAD

**Issue by gophee** [owncloud/android#1930]
I have experienced this behaviour on a few different android devices. We play long instructions and lectures of around 1 hr 20 minutes, quite frequently the native OC player crushes and doesn't survive through the session, i then switched to another audio player that worked fully.

1. Is this a known issue ?
2. Is it possible to open the audio file with another player by simply clicking on the file without the need to "Open With" each time ?

* id be happy to attached device logs but don't know how to do it.

Thank you 
Ziv

**Comment by michaelstingl** [comment]
@gophee Thank you for reporting this issue. Is the app open all the time? Does your device go to sleep? Do you play the long audio in the background while you are using other apps?

Please write the details of at least one device that showed this issue:

```
### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:
```

**Comment by gophee** [comment]
Hi Michael 
Thank you for getting back to me.
Here is a screenshot of one of the devices. We use 8 different ones and crushing happens inconsistently on all models only on long audio sessions. All devices were installed with the latest Oc version. The app is on all the time with no other action on the background. As far as I see the device doesn't go to sleep, although the screen shuts after a minute or so.
By the way the app on iPod touch devices runs faultlessly.

Ziv

**Comment by gophee** [comment]
![whatsapp image 2017-03-29 at 10 21 44](https://cloud.githubusercontent.com/assets/6696708/24465640/6b93166e-14b6-11e7-97e3-4ae612a3f816.jpeg)

**Comment by davivel** [comment]
@gophee , is this solved, or did you closed it by mistake?

**Comment by gophee** [comment]
It's not solved
Probably closed it by mistake

**Comment by davigonz** [comment]
Hello @gophee , thank you for your report. 

`id be happy to attached device logs but don't know how to do it.`

Have a look to the next video for seeing device logs in the ownCloud app. 

![logs](https://cloud.githubusercontent.com/assets/15261363/24540947/96a054bc-15f5-11e7-8a0e-ec3d715618c4.gif)

Could you please attach an screenshot of the logs just in the moment when the audio player crashes? Or if you prefer, you can also use a file browser and go to the internal storage/ownCloud/log and attach here the content of currentLog.txt.

**Comment by gophee** [comment]
Thank you.
1. I don't see the logs option in the settings of my devices like in your video.
2. Another detail about our owncloud playing setup: playing audio always occurs while being disconnected from the network. i.e downloading media happens near the router and playing is far away.

Ziv

**Comment by gophee** [comment]
Here is the Device screenshot.
Can't find the Logs option like appears in your gif.

![img_3004](https://cloud.githubusercontent.com/assets/6696708/24588048/aa7ab3ee-17c9-11e7-9db4-8249e3a96b88.JPG)

**Comment by davigonz** [comment]
@gophee 

> Here is the Device screenshot.
> Can't find the Logs option like appears in your gif.

Sorry, I was wrong, logs option is only available for development. 

> 2. Another detail about our owncloud playing setup: playing audio always occurs while being disconnected from the network. i.e downloading media happens near the router and playing is far away.

Thank you for this info, but I don't think this is related to the crash you reported. Once the file is downloaded, you should be able to play it wherever, near or not the router. 

Let us do some tests and we will answer you when we have more info about the issue.

**Comment by gophee** [comment]
Thank you.
If there's any documentation you can direct me to, in order to fetch the
Logs for the Android device, let me know.

Ziv

**Comment by gophee** [comment]
Ok, i managed to extract a crash log of one of the devices. Hope it can help.
Thank you
Ziv

CrashLog 2.0.0(14)
Device : samsung amazing3gtrf
Build number : S738CWYAMJ1
CPU ABI : armeabi-v7a
Kernel version : 3.0.8-1251199
Firmware version : 4.0.4
Screen width : 320
Screen height : 480

13:25.199 V/LockPatternKeyguardView(  274): Gone=null
04-09 06:13:25.199 V/LockPatternKeyguardView(  274): Visible=com.android.internal.policy.impl.CircleLockScreen@4171f2d8
04-09 06:13:25.229 W/LockPatternKeyguardView(  274): no unlock screen when trying to enable fallback
04-09 06:13:25.249 D/ClockWidget(  274): isServiceEnable = false cityId = null
04-09 06:13:25.249 D/ClockWidget(  274): Weather Demon is not running, Set visibility to GONE
04-09 06:13:25.259 D/KeyguardViewMediator(  274): adjustUserActivityLocked mShowing: true mHidden: false
04-09 06:13:25.259 D/KeyguardViewMediator(  274): adjustStatusBarLocked: mShowing=true mHidden=false isSecure=false --> flags=0x1000000
04-09 06:13:25.259 D/PowerManagerService(  274): enableUserActivity false
04-09 06:13:25.259 D/PhoneStatusBar(  474): disable: < expand icons alerts ticker system_info back home RECENT* clock >
04-09 06:13:25.289 V/WindowManager(  274): rotationForOrientationLw(orient=5, last=0); user=0 USER_ROTATION_LOCKED mLidOpen=-1 mDockMode=0 mHdmiPlugged=false mAccelerometerDefault=0 sensorRotation=-1
04-09 06:13:25.299 D/LockPatternKeyguardView(  274): focused
04-09 06:13:25.299 D/memalloc(  110): /dev/pmem: Allocated buffer base:0x4165d000 size:614400 offset:2498560 fd:30
04-09 06:13:25.299 D/memalloc(  274): /dev/pmem: Mapped buffer base:0x554c5000 size:3112960 offset:2498560 fd:239
04-09 06:13:25.299 D/PhoneStatusBar(  474): disable: < expand icons alerts ticker system_info BACK* HOME* RECENT clock >
04-09 06:13:25.329 I/Adreno200-EGLSUB(  110): <CreateImage:896>: Android Image
04-09 06:13:25.329 I/Adreno200-EGLSUB(  110): <GetImageAttributes:1105>: RGBA_8888
04-09 06:13:25.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.869 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.869 V/MediaPlayer( 1586): getDuration
04-09 06:13:25.879 V/MediaPlayer( 1586): getDuration
04-09 06:13:26.709 E/SMD     (  106): DCD OFF
04-09 06:13:26.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:26.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:26.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:26.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:26.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:27.069 V/StatusBar.BatteryController(  474): status2batteryHealth 2
04-09 06:13:27.069 D/StatusBar.BatteryController(  474): mOldstatus2status 2
04-09 06:13:27.069 D/StatusBar.BatteryController(  474): now old status is 2
04-09 06:13:27.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:27.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:27.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.899 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.899 V/MediaPlayer( 1586): getDuration
04-09 06:13:28.909 V/MediaPlayer( 1586): getDuration
04-09 06:13:29.709 E/SMD     (  106): DCD OFF
04-09 06:13:29.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:29.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:29.879 V/MediaPlayer( 1586): getDuration
04-09 06:13:30.819 V/MediaPlayer( 1586): getDuration
04-09 06:13:30.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:30.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:30.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:30.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:30.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:31.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:31.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:31.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.269 W/PowerManagerService(  274): Timer 0x0->0x0|0x0
04-09 06:13:32.709 E/SMD     (  106): DCD OFF
04-09 06:13:32.819 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:32.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:33.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:33.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:33.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:34.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:34.829 V/MediaPlayer( 1586): getDuration
04-09 06:13:34.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:34.889 V/MediaPlayer( 1586): getDuration
04-09 06:13:34.889 V/MediaPlayer( 1586): getDuration
04-09 06:13:34.899 V/MediaPlayer( 1586): getDuration
04-09 06:13:35.719 E/SMD     (  106): DCD OFF
04-09 06:13:35.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:35.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:35.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:36.819 V/MediaPlayer( 1586): getDuration
04-09 06:13:36.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:36.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:36.849 V/MediaPlayer( 1586): getDuration
04-09 06:13:36.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:36.859 V/MediaPlayer( 1586): getDuration
04-09 06:13:37.089 V/StatusBar.BatteryController(  474): status2batteryHealth 2
04-09 06:13:37.089 D/StatusBar.BatteryController(  474): mOldstatus2status 2
04-09 06:13:37.089 D/StatusBar.BatteryController(  474): now old status is 2
04-09 06:13:37.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:37.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:37.839 V/MediaPlayer( 1586): getDuration
04-09 06:13:38.409 E/SqliteCursor.cpp( 1386): Bailing on database busy retry
04-09 06:13:38.409 E/SQLiteQuery( 1386): exception: database is locked: retrycount exceeded; query: SELECT _id, hash, play_logger_context, qos_tier FROM play_logger_context
04-09 06:13:38.409 W/dalvikvm( 1386): threadid=42: thread exiting with uncaught exception (group=0x40aac1f8)
04-09 06:13:38.519 I/GCore-Chimera-Crash( 1386): Cg8KCWNvbnRhaW5lchCo7T4=
04-09 06:13:38.519 I/GCore-Chimera-Crash( 1386): GCore-Chimera-Crash
04-09 06:13:38.559 I/DeviceDrDatabaseHelper( 1386): Cleaning stale data from database!
04-09 06:13:38.619 W/DeviceDoctorHandler( 1386): Crash Hash: da4967786ee5907f49b373161a54436b95885a0b
04-09 06:13:38.629 E/AndroidRuntime( 1386): FATAL EXCEPTION: gcm-task#1
04-09 06:13:38.629 E/AndroidRuntime( 1386): android.database.sqlite.SQLiteDatabaseLockedException: database is locked: retrycount exceeded
04-09 06:13:38.629 E/AndroidRuntime( 1386): at android.database.sqlite.SQLiteQuery.nativeFillWindow(Native Method)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:86)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:164)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:156)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:161)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at android.database.AbstractCursor.moveToNext(AbstractCursor.java:209)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at huf.a(:com.google.android.gms:292)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at hst.a(:com.google.android.gms:63)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at hst.<init>(:com.google.android.gms:21)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at com.google.android.gms.clearcut.uploader.QosUploaderChimeraService.a(:com.google.android.gms:93)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at pne.run(:com.google.android.gms:261)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
04-09 06:13:38.629 E/AndroidRuntime( 1386): at java.lang.Thread.run(Thread.java:856)
04-09 06:13:38.709 I/ActivityManager(  274): Process app.processName (pid 1386) has died.

**Comment by gophee** [comment]
Attached  please find crash log of other two incidents for the same device type.
The first one is while the OC player is just paused for some time..
The second one is normal playing.
Thank you
[Samsung.txt](https://github.com/owncloud/android/files/907394/Samsung.txt)

**Comment by gophee** [comment]
Last one - 3rd crash log of the audio player, after a few minutes of playing.
Thank you
[Samsung2.txt](https://github.com/owncloud/android/files/907415/Samsung2.txt)

**Comment by davivel** [comment]
Hi, @gophee .

Is the device plugged-in to power while the music is playing? 

Is it possible that somebody rotated the device right before the crashes?

Thanks.

**Comment by davivel** [comment]
With the crash logs, it's easy to protect the code to prevent the crash.

But I don't know if the playback will continue working correctly. I'm not sure what condition is triggering the crash.

**Comment by gophee** [comment]
Hello David, Thank you for getting back to me.

When it crashes:

1. The devices are usually not connected to a power supply.
2. The rotation is locked (portrait) on all devices. (should i maybe
release the lock ?)

Thank you
Ziv

**Comment by gophee** [comment]
If you like to send a modified app for testings I'd be happy to install it
and report the results.

Ziv

**Comment by davivel** [comment]
First, could you try if the crash happens too if device is connected to power supply? I suspect the system could be trying to safe resources, killing the process or lowering the priority of the media service, and the crash is a side effect of it.

**Comment by gophee** [comment]
it definitely happened when there was no power supply.
i'll check if it happens also while the power supply is connected

**Comment by gophee** [comment]
So far so good... I'm playing a long session with power supply connected a
few times already, and no crash.
Any direction for a solution there ? i'll keep on playing it and let you
know.

Ziv

**Comment by gophee** [comment]
Did many tests playing audio segments of 1.5 hours repeatedly. I can definitely say that when the device is not connected to power it crashes most of the time. Whats next ?

**Comment by gophee** [comment]
Following up the ticket. Any news ? I'd be happy for an update. I'd also be happy to test any fix you may come out with.

2. In the meantime, Is there a way that I can define another default player that will automatically play media that was downloaded with OC ?

Thanks
Ziv

**Comment by michaelstingl** [comment]
default play could be https://github.com/owncloud/android/issues/1123 ?

**Comment by gophee** [comment]
Dear Michael and David,

Another observation from today about this issue. sometimes the crush occurs
immediately after download of mp3 files has completed. I guess because it
tried to play it and then the player crushes etc..
I'm testing the app in 8 different android phones and it gives the same
inconsistent crushing. By the way, once it has crushed i can't play the
file again through OC, but only after a complete restart. I am able to play
it though through other players.

- Do you have any direction for a fix there ?
- In a previous message you wrote:

*"With the crash logs, it's easy to protect the code to prevent the
crash. But I don't know if the playback will continue working correctly."*

- Are you intend to try this ?

Let me know if i can help, id' be happy to run these tests on any release.
Would really love to work with OC alone with no hassle of switching to
another audio app.

Thank you

Ziv

**Comment by davivel** [comment]
Hi, @gophee .

I just added some protections that should prevent the crashes to the version 2.4.0 of the app, that will be released in the next days. Unfortunately, we don't have time enough to test it thoroughly and be sure that there are no side effects in audio playback (at first sight, should be fine).

I'll ping you again when 2.4.0 is in the store.

**Comment by gophee** [comment]
David that's awesome news!! Please ping me whenever you release the version 
Thanks a lot
Ziv

**Comment by davivel** [comment]
@gophee , version 2.4.0 is already in Play Store. Could you try again an tell us if fixed your problem?

Thanks!

**Comment by gophee** [comment]
Hi David,

I'm testing long audio files continuously for the past 1.5 days.

So far so good..... no crushing!!

Will let you know. Thanks!

Ziv

**Comment by davivel** [comment]
Hey! Great to know, @gophee, thank you so much for your feedback.

I will close this one, just write a new comment if the problem reappeared in the last month (sorry for coming back so late).
