### ISSUE TITLE
AuthenticatorActivity auto connect to server - question

### ISSUE THREAD

**Issue by lazarvgd** [owncloud/android#1932]
Hi, I am trying to hide editText for server URL I have tried to use `setText()` method on `mHostUrlInput` and set server address, so when user change focus to username it will automatically report **connection established** message. But unfortunately this is not working.

Can you please help me to achieve this?

**Comment by davivel** [comment]
You can get something like that setting without changing the Java code.

Edit the file ```res/values/setup.xml``` . Set your URL in the XML Element named ```"server_url"``` (by default it's empty), and set XML Element named ```"show_server_url"``` to ```false``` (by default it's true).

That should be enough.

**Comment by lazarvgd** [comment]
Thank you! You have saved the day :dancer:
