### ISSUE TITLE
Cannot sync gradle project due to failed to resolve :touch-image-view:

### ISSUE THREAD

**Issue by lazarvgd** [owncloud/android#1935]
App gradle cannot sync and it is reporting error:
`Failed to resolve: :touch-image-view:`

I have got this error after I have changed package name in AndroidManifest.xml, from `com.owncloud.android` to `com.lazarvgd.android`.

Please advice how to overcome this issue?
Thanks 

EDIT:

I have found that android studio cannot find this class:
`import com.ortiz.touch.ExtendedViewPager;` in `PreviewImageActivity.class`

**Comment by davivel** [comment]
Changing the package name in AndroidManifest will not work alone. You need to change also the package in the code - what it not trivial at all.

Try this other method to change the package name in gradle scripts:

https://developer.android.com/studio/build/application-id.html

**Comment by lazarvgd** [comment]
I have done it but still facing the issue.

If I comment `compile name: 'touch-image-view'`, then I am not able to use  `com.ortiz.touch.ExtendedViewPager; ` class.

I have tried to find way to import missing lib but without success.

**Comment by davivel** [comment]
Do not comment that line, the JAR is needed.

Could you check if the file touch-image-view.jar is in the folder libs/ ? You need to change the project browser in Android Studio from 'Android' to 'Project', or you will not be able to see the folder.

**Comment by lazarvgd** [comment]
Sir, that jar file is missing, also `disklrucache-2.0.2.jar` missing. I am not sure why gradle did not download them.

**Comment by davivel** [comment]
Gradle cannot get those JARs, they are included in the repository. From the moment you cloned it, at some point they were accidentally deleted. Download them again from Github and put them in place, and let's see what happens :)

**Comment by lazarvgd** [comment]
Sir, I need little help here. Folder libs is also missing from android studio, but I can find it from nautilus (linux file explorer). How to import libs now?

**Comment by davivel** [comment]
Here: https://github.com/owncloud/android/blob/master/libs/disklrucache-2.0.2.jar

And here: https://github.com/owncloud/android/blob/master/libs/touch-image-view.jar

Click the download button on the right side in each of them.

**Comment by lazarvgd** [comment]
Thank you sir! Now it is compiling. Thanks :)

**Comment by davivel** [comment]
You're welcome :)
