### ISSUE TITLE
Add "Go to Folder" action on tapping a completed upload 

### ISSUE THREAD

**Issue by liamdennehy** [owncloud/android#1942]
### Actual behaviour
- Tapping on an upload notification does nothing

### Expected behaviour
- Tapping on an upload notification does something :) 

 
### Steps to reproduce
1. Tap on a completed upload notification in the notification tray, or open the Uploads activity in the Android client 
2. Owncloud Android app lists all uploads
3. Tap a (completed) entry

I hoped this would do something, like open the folder, as I'd like to:
* Rename the file
* Share the file
Opening the file isn't necessarily useful by default as I likely already have the file locally, though maybe useful in a long-tail, but the default tap would definitely be if it from opening the target folder, hopefully even showing/selecting the new file. 

I've already navigated the tree once to upload the file, perhaps useful to not have to do that again to manipulate the uploaded file? 

Can this problem be reproduced with the official owncloud server?
Probably (client issue) 

### Environment data
Android version:
7.1.1
Device model: 
Nexus 9, Nexus 7
Stock or customized system:
Both
ownCloud app version:
Latest Play Store (2.3.0)
ownCloud server version:
9.1
### Logs
Skipped...

**Comment by jesmrec** [comment]
@liamdennehy there is an opened PR for the same aim:

https://github.com/owncloud/android/issues/1876

**Comment by liamdennehy** [comment]
Certainly, apologies for posting a duplicate item.
