### ISSUE TITLE
Failure when cloning owncloud/android repository

### ISSUE THREAD

**Issue by AigerimBazarbayeva** [owncloud/android#1943]
### Actual behaviour
"fatal read error: Connection reset by peer"
occurs when cloning owncloud/android repository

### Expected behaviour
successful cloning owncloud/android repository
 
### Steps to reproduce
1. In a web browser, go to https://github.com/owncloud/android, and click the 'Fork' button near the top right corner
2. Open a terminal and go on with the next steps in it
3. Clone your forked repository: git clone --recursive https://github.com/YOURGITHUBNAME/android.git

### Git version/OS version:

git version 2.7.4, ubuntu 16.04

**Comment by AigerimBazarbayeva** [comment]
#### Solution worked for me:

It was caused by .gitmodules file and can be solved 
by replacing following line:

url = git://github.com/owncloud/android-library.git
to 
url = https://github.com/owncloud/android-library.git

**Comment by michaelstingl** [comment]
@AigerimBazarbayeva Thank you for your feedback!

@DeepDiver1975 Is there something that can be improved in the GitHub repo or in the repo settings?

**Comment by davivel** [comment]
@michaelstingl , it's in a file in the project, I can take care.

**Comment by davivel** [comment]
Done. Thanks, @AigerimBazarbayeva
