### ISSUE TITLE
Uploads can get stuck when network access is lost while sending data

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1950]
### Actual behaviour
If network access is lost by the device while an upload is in progress, this upload could get blocked until the app is killed, preventing also that other uploads in the queue start. If the user tries to cancel this upload, there will be an ANR and the app will crash.

The problem occurs if the network is lost while one of the PUT operations is writing part of the file in the socket.

### Expected behaviour
The uploads fails after some time without connectivity. In Android 5 or later, it is retried automatically when Wifi network is available.
 
### Steps to reproduce
1. Upload some videos to a server using an HTTP connection (not in HTTPS).
2. Open uploads view.
2. When one of the videos is uploading (progress > 0%, < 100%), enable 'plane mode' in the device.
3. Wait around 20 seconds.
4. Disable 'plane mode'.

NOTE: it doesn't happen every time, the network has to be lost exactly while the app is writing to the socket. To improve the chances it occurs (and be able to fix it), increase the size of the buffer in https://github.com/owncloud/android-library/blob/20c9830922601f686606b0cb795ba56aab4dddee/src/com/owncloud/android/lib/common/network/ChunkFromFileChannelRequestEntity.java#L60 to ```com.owncloud.android.lib/resources.files.ChunkedUploadRemoteFileOperation.CHUNK_SIZE``` .

### Environment data
Android version: 5. Could happen in other versions, not sure.

Device model: Samsung Galaxy Tab S3

ownCloud app version: 2.3.0
 
ownCloud server version: any

NOTE2: the bug is fixed for HTTPS servers, a write timeout was enforced in ```xxxxx``` , and will be released in version 2.4.0. A similar solution for HTTP is not possible, since the socket implementation for HTTP has no method por write timeout.

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
