### ISSUE TITLE
Additional instant upload sources

### ISSUE THREAD

**Issue by mach-o** [owncloud/android#1955]
I'd like to be able to configure instant uploads from the "Screenshots" folder, in addition to Photos and Video. At that point it may make more sense just to allow arbitrarily many instant upload sources, rather than incorporating more and more specific use cases as they arise and polluting the configuration menu.

**Comment by davigonz** [comment]
Hi @mach-o , thank you for your input. There's already an opened issue about this topic so I will close the current issue. For more details, please follow up here: https://github.com/owncloud/android/issues/95
