### ISSUE TITLE
weird problems with ssl

### ISSUE THREAD

**Issue by alex9099** [owncloud/android#1956]
### Actual behaviour
-When inserting my https cloud URL when i'm on my home network (where the server is[it should not be relevant because i use cloudflare])it says "An error occured whilst connecting to the server", with http it says the same, but using my mobile data without https it says "Secure connection is redirected through an unsecure route" and with https it says "SSL initialization failed", the server works fine on my linux laptop and on mobile browser

### Expected behaviour
-It should work on every network with https
 
### Steps to reproduce
1. Open owncloud without any account configured
2. Insert URLs with and without https

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
yes, i can open that demo website on the browser but i get the very descritive error "An error occured whilst connecting to the server"

### Environment data
Android version: 5.1

Device model: vegetafhd (BQ aquaris e5 fhd)

Stock or customized system: stock

ownCloud app version: 2.3.0

ownCloud server version: 9.1.5

#### Web server error log
```
[Tue May 02 07:32:15.624032 2017] [proxy_fcgi:error] [pid 21191] (70008)Partial results are valid but processing is incomplete: [client 172.68.102.63:12601] AH01075: Error dispatching request to : (reading input brigade)
```
(not sure if relevant, i repeated the problem and no more errors occured)

#### ownCloud log (data/owncloud.log)
```
Nothing relevant, only things that happened in the past (database configuration failures that after were corrected)
```

**Comment by gaining** [comment]
Any update? I'm having the same exact issue

**Comment by alex9099** [comment]
I think i solved it with a header configuration on apache, but i can't remember, it was more than half a year ago :( 
Do you use cloudflare?

**Comment by gaining** [comment]
no I just use it on a personal server

**Comment by gaining** [comment]
I changed the owncloud https port on my server to a different number, maybe that caused the issue.

**Comment by davigonz** [comment]
> I changed the owncloud https port on my server to a different number, maybe that caused the issue.
Hi @gaining , with the default https port it is currently working for you?

**Comment by gaining** [comment]
8443

**Comment by jesmrec** [comment]
If no extra info, will close. Feel free to reopen if still happens
