### ISSUE TITLE
[2.4.0] Release new version

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1957]
PRs: #1969
_____

AC:

 - [x] [GIT] Create branch release_0.9.17 in owncloud/android-library from master  (almost feature-frozen) 
 - [x] [GIT] Create branch release_2.4.0 in owncloud/android from master (almost feature-frozen) 
 - [x] [DEV] Update version number and name in AndroidManifest.xml in android module
 - [x] [DEV] Update version number and name in AndroidManifest.xml in oc_jb_workaround module
 - [x] [DIS] Create changelog file (< 500 chars) and add to CHANGELOG.md in owncloud/android
 - [X] [QA] Design Test plan  @jesmrec
 - [X] [QA] Regression Test plan @jesmrec 
 - [x] [GIT] Merge branch release_0.9.17 in owncloud/android-library, into master
 - [x] [GIT] Merge branch release_2.4.0 in owncloud/android, into master
 - [x] [DIS] Generate test APKs and BAR files from branch master in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-2.4.0 in HEAD commit of master branch, in owncloud/android
 - [x] [GIT] Create and sign tag oc-android-library-0.9.17 in HEAD commit of master branch, in owncloud/android-library
 - [x] [DIS] Generate final APK files (including oc_jb_workaround) from signed commit in owncloud/android
- [ ] [DIS] Generate final BAR files from signed commit in owncloud/android
 - [x] [DIS] Upload & publish release APK and changelog in Play Store
 - [x] [DIS] Update screenshots and store listing, if needed, in Play Store
 - [ ] [DIS] Upload & publish release BAR and changelog in Blackberry World
 - [ ] [DIS] Update screenshots and store listing, if needed, in Blackberry World
 - [x] [GIT] merge master branch into stable, in owncloud/android-library
 - [x] [GIT] merge master branch into stable, in owncloud/android
 - [x] [DIS] push OC JB workaround app to Play Store

_____

BUGS & IMPROVEMENTS

- [X] (1) "Open with" option does not update non av-off files https://github.com/owncloud/android/issues/1957#issuecomment-303405614 [EXPECTED BEHAVIOR SO FAR] Check https://github.com/owncloud/android/issues/1683
- [X] (2) Crash in public link with special characters https://github.com/owncloud/android/issues/1957#issuecomment-303957972 [FIXED]

**Comment by jesmrec** [comment]
### (1) Bug 

Steps

1. Download a txt file
2. Open it with an external app (for example ES Note Editor)
3. Edit and save the file

Current behaviour

File is not uploaded

Expected behaviour

File is uploaded

Server v10 (with and without SAML)
Huawei 6P v7

**Comment by davivel** [comment]
@jesmrec , (1) is expected behaviour in the Android app right now; only av-off files should be uploaded immediately. This issue tracks the feature you are missing: https://github.com/owncloud/android/issues/1683

**Comment by davigonz** [comment]
@davivel @jesmrec In connection with the bug (1), I've tested with av-off files and several apps and here are the results I've obtained

- QuickEdit ✔️
- Text edit ✔️
- ES Note Editor ❌

**Comment by davivel** [comment]
Some editors do strange things to save files instead of just writing.

Please, test with release 2.3.0 to see if it's a real regression.

**Comment by davigonz** [comment]
@davivel @jesmrec tested with 2.3.0, the behavior is exactly the same as in 2.4.0 release, so is not a regression in the end

**Comment by jesmrec** [comment]
@davivel @davigonz i have noticed a dependency on the device and app that edit the file. There are apps/devices that can edit a file (non av. offline) and upload it to oC, but they do in 2.4.0 and 2.3.0 as well, so it would not be a bug. This is not a regression then, but we have different behaviours in any case.

**Comment by jesmrec** [comment]
### (2) Bug 

Steps

1. Create a folder called `(+-&_$éô`
2. Create two public links with default name -> OK
3. Create  another public link with default name

Current behaviour: crash
Expected behaviour: public link created

Huawei6P v7
server v10.0.2 SAML

**Comment by davivel** [comment]
@jesmrec , (2) is ready to be tested.

I'll create PRs to check that everything is OK in Travis

**Comment by jesmrec** [comment]
Version approved
