### ISSUE TITLE
Automatic upload?

### ISSUE THREAD

**Issue by janipewter** [owncloud/android#1960]
Hi all. I have just stumbled across this while looking for an alternative to Dropbox camera upload.

I have an owncloud server set up and working on Ubuntu 16.04 and I can connect to it find, add, download, delete files etc no problem.

I have tried using the "instant upload" option but I just can't seem to figure out how to get it to work. I set the path to my camera folder and take a photo and absolutely nothing happens in the app whatsoever. Nothing gets queued, nothing uploaded, no errors, nothing. Dropbox syncs the same photo fine.

I am pulling my hair out trying to figure this out and I can't find anything in the manual while would help.

I am using a Galaxy S7 and my camera is set to save to a 64GB microSD card. I tried changing back to phone storage and set that folder in the owncloud app but it makes no difference.

PLEASE can someone help?

**Comment by davigonz** [comment]
Hi @janipewter , thank you for reporting this problem. There are two issues opened about this topic, one for Android 6 and the other for Android 7. I'm going to close this, so please check your current Android version and follow up one of the links below. 

- **Android 6**: https://github.com/owncloud/android/issues/1870
- **Android 7**: https://github.com/owncloud/android/issues/1829
