### ISSUE TITLE
Shared folder doesn't show its content

### ISSUE THREAD

**Issue by duub** [owncloud/android#1962]
### Actual behaviour
-When I wan to see the content of a Shared folder with the Android App (the owner is another user) shows the message "Nothing here...."
- The parent view shows the total size of the folder and it's not empty.

### Expected behaviour
-I expect to see the content
 
### Steps to reproduce
1. Open the shared folder
2. See the message "Nothing here..."

### Environment data
Android version: 7.1.2

Device model: Nexus 5

Stock or customized system: LineageOS

ownCloud app version: 2.3.0

ownCloud server version: 9.1.5 (stable)

**Comment by michaelstingl** [comment]
@duub Could you check the owncloud.log and the webserver logs from the time of the incident? Any errors or anything suspicious?

**Comment by duub** [comment]
checked! and doesn't logs anything... I think it's going to be hard to solve... I've shared another folder from another user and works fine... so the thing of being a shared folder it's not the problem

**Comment by davigonz** [comment]
Hi @duub , thank you for reporting this problem, ¿could you please give us more information about the permissions (create, change, delete) set by the user with whom the issue appears? Is there any difference with the permission set in the second folder you've tested with?

Have you tried to refresh the view after opening the shared folder by swiping down?

**Comment by duub** [comment]
Hi @davigonz,
about permissions, the ones you specify are not defined in the interface I only have "can share" and "can edit" and both work fine, if you know the place in the database where check the permissions i can look there.

And the second question, yes, I've tried swiping down and still shows empty folder.

**Comment by duub** [comment]
I've tryed by myself... and I've found that the "permissions" value in the  "oc_share" table is 31 in both cases.

And I've seen that the folder that doesn't work properly has two rows, one to share with a group and another with a user. The user also belongs to the group. I hope it's not this issue... but you never know...

**Comment by davigonz** [comment]
> about permissions, the ones you specify are not defined in the interface I only have "can share" and "can edit" 

Hi @duub , if you are sharing a folder, you should be able to see **create, change, delete** below **Can edit** option , as you can see in the next gif in the right side.

| Share a file  | Share a folder | 
| ------------- |:-------------:| 
| ![share_file](https://cloud.githubusercontent.com/assets/15261363/26784312/43b28f04-49fd-11e7-8ae6-5750f9e3237e.gif) | ![share_folder](https://cloud.githubusercontent.com/assets/15261363/26784395/a47c53a6-49fd-11e7-9fdf-15b033eb026c.gif) |

> And I've seen that the folder that doesn't work properly has two rows, one to share with a group and another with a user. The user also belongs to the group. I hope it's not this issue... but you never know...

This is pretty interesting, if you create a folder and share it with a user and with a group to which that user belongs at the same time, the problem remains the same?

**Comment by duub** [comment]
from the point of view of the user that "receives" the shared folder the sharing options says something like: There's still no shared data with users" and i've no access to the user that shares the folder... but i can have acces to the database...

**Comment by duub** [comment]
from the user, says that is shared with a group of users with the permissions:
* can share
* can edit: create, change, delete

**Comment by davigonz** [comment]
Hi again @duub , I've been doing some tests trying to reproduce the problem but sharing is working well in the case you describe and I always manage to see the content of the shared folder.

@jesmrec @davivel Any additional idea here?

**Comment by duub** [comment]
thank you for your time, probably something very uncommon.
