### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by xavery92** [owncloud/android#1963]
### Actual behaviour
When uploading files is still error "broken server configuration"

Using web and windows client there is no problems.

Can this problem be reproduced with the official owncloud server?
No, on test server is okey.

### Environment data
Android version:
6.0.1
Device model: 
SM-N910C
Stock or customized system:
Stock
ownCloud app version:
2.3.0
ownCloud server version:
ownCloud 9.1.0 (stable)
#### Web server error log
[Thu May 11 21:27:45.647523 2017] [fcgid:warn] [pid 21634] (70008)Partial results are valid but processing is incomplete: [client 192.168.168.20:51975] mod_fcgid: can't get data from http clientInsert 

#### ownCloud log (data/owncloud.log)
{"reqId":"7mjI8wWJYmdFsiqDu+vb","remoteAddr":"192.168.168.20","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/cloud\\\/public_html\\\/remote.php(164): require_once('\\\/home\\\/cloud\\\/pub...')\\n#6 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"rafal\"}","level":0,"time":"2017-05-11T20:24:19+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Filmy_SGS5\/","user":"rafal"}
{"reqId":"FB8RxwEAk8D14pOk3TT8","remoteAddr":"192.168.168.20","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/cloud\\\/public_html\\\/remote.php(164): require_once('\\\/home\\\/cloud\\\/pub...')\\n#6 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"rafal\"}","level":0,"time":"2017-05-11T20:24:19+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Filmy_SGS5\/20170511_185529.mp4","user":"rafal"}
{"reqId":"ugNN5z3I0h6dZkZKp\/YM","remoteAddr":"192.168.168.20","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Filmy_SGS5\\\/20170511_185529.mp4 could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Filmy_SGS5\\\/2017...')\\n#1 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(334): Sabre\\\\DAV\\\\Server->getPropertiesForPath('Filmy_SGS5\\\/2017...', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/home\\\/cloud\\\/public_html\\\/remote.php(164): require_once('\\\/home\\\/cloud\\\/pub...')\\n#8 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"rafal\"}","level":0,"time":"2017-05-11T20:24:19+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Filmy_SGS5\/20170511_185529.mp4","user":"rafal"}
{"reqId":"2OV2HSS9Kq8o6B00XxNR","remoteAddr":"192.168.168.20","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/cloud\\\/public_html\\\/remote.php(164): require_once('\\\/home\\\/cloud\\\/pub...')\\n#6 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"rafal\"}","level":0,"time":"2017-05-11T20:24:20+00:00","method":"PUT","url":"\/remote.php\/webdav\/Filmy_SGS5\/20170511_185529.mp4-chunking-4097-55-0","user":"rafal"}

**Comment by jesmrec** [comment]
@xavery92 is this still reproducible with the newer versions?

**Comment by jesmrec** [comment]
@xavery92 still reproducible?
