### ISSUE TITLE
[Future] Ten years and multiple server versions later

### ISSUE THREAD

**Issue by Fruchuxs** [owncloud/android#1966]
At the moment you note in OwnCloudVersion the server versions with check methods for a specific feature. This is used in some parts of the code of the android app to decide what is todo if the server doesn't supports a specific feature:

```java
   public static final int MINIMUN_VERSION_FOR_CHUNKED_UPLOADS = 0x04050000; // 4.5
    public static final int MINIMUM_VERSION_FOR_SHARING_API = 0x05001B00; // 5.0.27
    public static final int MINIMUM_VERSION_WITH_FORBIDDEN_CHARS = 0x08010000; // 8.1
    public static final int MINIMUM_SERVER_VERSION_FOR_REMOTE_THUMBNAILS = 0x07080000; // 7.8.0
```

Now in the future - multiple server versions later - this can be end in a heavy bloated code. Maybe you decide to say, okay we just support the last two, three or so .. major server versions. This would be fine, but how do you plan to remove the old if-statements in the rest of the code which are not longer in use?  

I'm highly interested to hear your thoughts to this topic. 

If this is the wrong place, i'm sorry - close it, delete it.

Greetings!

**Comment by michaelstingl** [comment]
Newer features propagate their status with capabilities. This should be the way to go: https://github.com/owncloud/documentation/issues/2956

**Comment by Fruchuxs** [comment]
This is a great idea! I also tought on this. But what if with breaking changes withing a capability? Versioning?
And this means also that you have for every feature one if in the android logic code, right?

**Comment by davivel** [comment]
> And this means also that you have for every feature one if in the android logic code, right?

Right. And I don't know other way to do it.

How to handle deprecation of old versions? Just break what needs to be broken. Let's say that we want to ignore completely versions prior to 5. I would just delete constant ```MINIMUN_VERSION_FOR_CHUNKED_UPLOADS``` and follow compiler errors to find the points in the app that need to be updated. And would update them aggressively.

Recently I read a quote, I don't know the author, saying something like "write code that is easy to drop". Code is alive, we just need to embrace it and accept that to move forward we need to break previous stuff.

**Comment by Fruchuxs** [comment]
I also don't know an another way as if-else. Maybe u can put the stuff in comand-pattern-like instances and execute them for specific versions? But this restricts the code ... 
I thank you for your patience and the explanations. I'm searching for better solutions of this problem, but I can't find good sources or reasearches. I assume this is founded in that this "problem" only occurs in more bigger and evoluted code. So I decided to simply ask here for some informations. :)
