### ISSUE TITLE
Private link

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1970]
Add 'link' icon to share view, next to  the right border of the header (with file thumbnail and name), to copy to clipboard or share with other apps a permanent link to the file that can be shared with other users in the server.

On tap, show list of apps to share (including clipboard), as with public links

Related: https://github.com/owncloud/core/issues/11732, owncloud/enterprise#2015

**Comment by jesmrec** [comment]
Approved

**Comment by michaelstingl** [comment]
Name should be "private link" according to @pmaier1 in https://github.com/owncloud/documentation/issues/2986

**Comment by davigonz** [comment]
@michaelstingl We used "permalink" only for the issue name when we created it, I've just updated the name to "private link". BTW, I've been using private link in the code from the beginning, as expected.

**Comment by davivel** [comment]
Merged
