### ISSUE TITLE
Write-only share link for folders

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1971]
AC:
 - [x] Rename "allow uploads" option in public shares of folders as "allow editing"
 - [x] Add checkbox "show file listing" checked by default if '"allow editing" is checked
 - [x] Disable checkbox if "allow editing" is unckecked
- [x] Show option only if capability 'supports_upload_only' is set 
- [x] Create share in server according to new show file listing switch state
- [x] Update share in server according to new show file listing switch state
- [x] Design test plan @jesmrec
- [x] Validate test plan @jesmrec

**Comment by jesmrec** [comment]
This server bug affects directly the validation: https://github.com/owncloud/core/issues/28154

**Comment by jesmrec** [comment]
Approved. Great job, no bugs detected :)
