### ISSUE TITLE
(Android 7, BQ Aquaris U Lite) Autoload of images does not start

### ISSUE THREAD

**Issue by marcogaio** [owncloud/android#1974]
My daughter own the phone at subject, with Android 7.

I've the latest OwnClud official app,  2.3.0, with OC 9.1 (but it is not a OC trouble, there's not even the start of the upload, nor images in the upload queue).

Using filemanager i've verified that images got in correct folder (/storage/emulated/0/DCIM/Camera) that are specified in the OwnClud app as camera folder.

I've looked here, there's some bug opened similar to that, but all claimed to be fixed, or at least seems to me so.

Sorry if not. Thanks.

**Comment by davigonz** [comment]
Hi @marcogaio , thank you for reporting this problem. What you have described seems to be the same as other people with Android 7 has noticed and written down in https://github.com/owncloud/android/issues/1829 , so I will close this issue you've opened. If I'm wrong , please reopen again and give us more details. 😉
