### ISSUE TITLE
Application dies after sharing too many files to ownCloud

### ISSUE THREAD

**Issue by Nowaker** [owncloud/android#1980]
### Actual behaviour

Go to any Gallery app, select hundreds of files, share with OwnCloud. OwnCloud app immediately dies and won't upload that many files.

### Expected behaviour

Upload all files. Don't die.
 
### Steps to reproduce

Already specified in "Actual behaviour" section.

> Can this problem be reproduced with the official owncloud server?
> (url: https://demo.owncloud.org, user: test, password: test)

Can't tell. Got private data, won't upload it there.

### Environment data

Android version: 4.4.2

Device model: Samsung GT-I9292

Stock or customized system: Stock

ownCloud app version: 2.4.0

ownCloud server version: irrelevant

#### Web server error log

irrelevant

#### ownCloud log (data/owncloud.log)

irrelevant

**Comment by vikene** [comment]
@jesmrec  I would like to take this up 👍

**Comment by jesmrec** [comment]
@vikene if you want to work on it in order to fix, go ahead :)

**Comment by jesmrec** [comment]
Is this still reproducible?

**Comment by jesmrec** [comment]
Checked with an old device (Android7) and a newer one (Android12), Both of them set a limit to share (200 files). With 2.21 app version, 200 files correctly shared.

For me, this is fixed. Feel free to reopen in case is still reproducible on your side.
