### ISSUE TITLE
Unknown error occured on android app connexion

### ISSUE THREAD

**Issue by paul-mesnilgrente** [owncloud/android#1982]
### Actual behaviour

Hi, I have freshly installed the owncloud application (ocloud for OwnCloud) from the PlayStore. But when I enter my URL in the connexion screen, the configuration test is printing "Unknown error occured!" under the URL.

This is stranged because it works in the Web Browser. Here is the result of https://owncloud.paul-mesnilgrente.com/status.php : {"installed":true,"maintenance":false,"version":"9.1.6.2","versionstring":"9.1.6","edition":""}

DavDroid synchronizes Contacts and Calendar well, and Thunderbird too.

### Expected behaviour

The connection should work.
 
### Steps to reproduce
1. Install the ocloud for OwnCloud app from the PlayStore
2. Enter this URL : https://owncloud.paul-mesnilgrente.com
3. Wait for the test result
4. Normally, "Unknown error occured" is printed

Can this problem be reproduced with the official owncloud server?
No it works with https://demo.owncloud.org/

### Environment data
Android version: 7.1.2 LineageOS Condor

Device model: Moto E

Stock or customized system: Condor ?

ownCloud app version: The most updated on the Play Store

ownCloud server version: 9.1.6

#### Web server error log
```
I don't know why, but the logs are not written any more :/ Even when I am connecting with the web browser.
```

#### ownCloud log (data/owncloud.log)
```
I don't know why, but the logs are not written any more :/ Even when I am connecting with the web browser.
```

**Comment by davivel** [comment]
Sorry, but "ocloud for OwnCloud" is not related to us, as far as I know. For bugs in that app, you should contact with info@ocloud.de , as declared in the page in Google Play Store of the "ocloud for OwnCloud" app.

The official ownCloud app for Android is this one:  https://play.google.com/store/apps/details?id=com.owncloud.android
