### ISSUE TITLE
Unknown error occured on connection

### ISSUE THREAD

**Issue by paul-mesnilgrente** [owncloud/android#1983]
### Actual behaviour

Hi, I have freshly installed the owncloud application (ocloud for OwnCloud) from the PlayStore. But when I enter my URL in the connexion screen, the configuration test is printing "Unknown error occured!" under the URL.

This is stranged because it works in the Web Browser. Here is the result of https://owncloud.paul-mesnilgrente.com/status.php : {"installed":true,"maintenance":false,"version":"9.1.6.2","versionstring":"9.1.6","edition":""}

DavDroid synchronizes Contacts and Calendar well, and Thunderbird too.

### Expected behaviour

The connection should work.
 
### Steps to reproduce
1. Install the ocloud for OwnCloud app from the PlayStore
2. Enter this URL : https://owncloud.paul-mesnilgrente.com
3. Wait for the test result
4. Normally, "Unknown error occured" is printed

Can this problem be reproduced with the official owncloud server?
No it works with https://demo.owncloud.org/

### Environment data
Android version: 7.1.2 LineageOS Condor

Device model: Moto E

Stock or customized system: Condor ?

ownCloud app version: The most updated on the Play Store

ownCloud server version: 9.1.6

#### Web server error log
```
I don't know why, but the logs are not written any more :/ Even when I am connecting with the web browser.
```

#### ownCloud log (data/owncloud.log)
```
I don't know why, but the logs are not written any more :/ Even when I am connecting with the web browser.
```

**Comment by davivel** [comment]
Sorry, but "ocloud for OwnCloud" is not related to us, as far as I know. For bugs in that app, you should contact with info@ocloud.de , as declared in the page in Google Play Store of the "ocloud for OwnCloud" app.

The official ownCloud app for Android is this one: https://play.google.com/store/apps/details?id=com.owncloud.android

**Comment by paul-mesnilgrente** [comment]
I have just installed the official version of ownCloud for Android, the version 2.4.0 and it is not working neither.

**Comment by davivel** [comment]
Thanks for reporting back, @paul-mesnilgrente .

True bug here.

**Comment by davivel** [comment]
There is some kind of problem with the connection. The server just returns nothing when client tries to read data from the response to GET status.php. On the other hand, same request work perfectly from web browser.

@paul-mesnilgrente , were your server and your app working before? Did you change something in your server configuration recently? Did you upgrade the server recently?

**Comment by paul-mesnilgrente** [comment]
It was working before. Since, three things have changed in the same time:

1. I have placed my server behind a nginx reverse proxy
2. I have upgraded owncloud from 9.1.? to 9.1.6
3. Because of proxy configuration problems, I have moved my SSL certificates from the computer which contains owncloud to the computer which contains the reverse proxy.

**Comment by davivel** [comment]
The reverse proxy is a strong suspicious...

In any case, this seems a limitation in the network library used by the app. When I set mitmproxy in the middle everything goes fine.

Dropping our network library in favor of something more modern is a long-time wish we have, but I couldn't tell when it's going to happen, to be honest.

**Comment by paul-mesnilgrente** [comment]
`When I set mitmproxy in the middle everything goes fine.`

I don't know what it means, can you explain?

**Comment by davivel** [comment]
Sorry; ```mitmproxy``` is a debugging tool, a proxy that I set as a man-in-the-middle between my smartphone and the server, that logs all the requests between both so that I can inspect the details.

That means that my device thinks it is reading responses from your server, but indeed mitmproxy is reading from your server and my device from it.

With this configuration everything goes fine. When the devices access to your server without proxy in the middle, there is a transport exception in the exact moment when the app tries to read the first byte of the response from your server. Since mitmproxy, like the web browser, has no problem to read from your server, I'm suspecting that the problem is in our network library. It is quite old, it is deprecated indeed, and that could be the source of the exception.

**Comment by mark-orion** [comment]
I have the same problem running Lineage OS 14.1 (Android 7.1.2) on a Fairphone 2. However the app worked on the older FairphoneOpenOS (Android 5.1) and none of my systems has problems with my owncloud server. What puts me off is the "Unknown" bit. It would be much better if the app would provide useful information about the connection problem.

**Comment by neirbowj** [comment]
I had a problem matching this description. Moto G5 Plus, Android 7.0, ownCloud app 2.4.0, ownCloud server 9.1.5.

My TLS cert was issued by [CAcert](https://www.cacert.org/). The root CA is not in the system trust store, but I had added it to the user trust store on the Moto and verified by browsing to the web UI in Chrome.

On a hunch, I issued a replacement [Let's Encrypt](https://letsencrypt.org/) certificate. Having changed nothing else, the app now succeeds at that step, showing "Secure connection established" instead.

Does the app perform certificate checking based on the combination of system and user certificate stores, or just system?

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
