### ISSUE TITLE
Upload only capability is not being properly updated from server

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#1996]
### Actual behaviour
Upload only capability is not included when refreshing the capabilities from server

### Expected behaviour
Upload only capability is properly refreshed from server
 
Related with #1971

**Comment by jesmrec** [comment]
Checks performed:

**Behaviour in `master` branch:**

Depending of the value of  `multiple` and `supports_upload_only` capabilities, in DB is stored:

| . | supports\_upload\_only TRUE | supports\_upload\_only FALSE  | 
| :-: | :-----------------------: | :---------------------------: |
| **multiple TRUE**  |  `sharing_public_multiple = 1` <br>`supports_upload_only = 1` <br> :white\_check\_mark: |  `sharing_public_multiple = 1` <br>`supports_upload_only = 1` <br> :x: | 
| **multiple FALSE** | `sharing_public_multiple = 0` <br>`supports_upload_only = 0` <br> :x: |  `sharing_public_multiple = 0` <br>`supports_upload_only = 0` <br> :white\_check\_mark: |  

The capability `supports_upload_only` gets always the value of `sharing_public_multiple`, causing errors if they were different. Today, they are always set to true:

https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Capabilities.php#L71

but the behaviour is not the expected in those cases.

**After the fix:**

| . | supports\_upload\_only TRUE | supports\_upload\_only FALSE  | 
| :-: | :-----------------------: | :---------------------------: |
| **multiple TRUE**  | `sharing_public_multiple = 1` <br>`supports_upload_only = 1` <br> :white\_check\_mark:  | `sharing_public_multiple = 1` <br>`supports_upload_only = 0` <br> :white\_check\_mark:   | 
| **multiple FALSE** | `sharing_public_multiple = 0` <br>`supports_upload_only = 1` <br> :white\_check\_mark:   |  `sharing_public_multiple = 0` <br>`supports_upload_only = 0` <br> :white\_check\_mark:  |  

Approved.

@davigonz
