### ISSUE TITLE
Configure BETA program in Play Store

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#1998]
We are currently working on publishing the beta app in FDroid, so it would be a good moment to start to do the same in **Google Play Store**. 

There are two ways to set up beta tests in Play Store:
- **Closed beta**: to run a test with small groups or if **we know the exact users we want to test** the ownCloud app. Users in this test group can be managed by email address and only they will receive updates for the beta version (via link).
- **Open beta:** to run a test with a large group, **anyone can join the beta program** and submit private feedback. Since ownCloud app is in live production version, users can opt-in to the beta program from the app details in Play Store (It's possible to set a maximum number of beta testers)

In none of the options, testers can submit public reviews. 

## AC
- [x] Decide: closed or open beta // **Open beta**
- [x] Decide Feedback channel (let the users know how they can provide us with feedback): email address, private feedback through Play Store (only for open beta), github repository, central. // **Apps email**
- [x] Prepare beta release
- - [x] Create open release beta in Play Store.
- - [x] Upload a the beta signed apk. 
- - [x] Add beta release info in Play Store.
- [x] Send beta release to review.
- [x] Publish beta.

CC @michaelstingl @jesmrec @davivel

**Comment by michaelstingl** [comment]
I’d vote for the open option. Management overhead for the closed group seems very high and I don’t see the benefits. /cc @kawohl @lefherz

**Comment by Kawohl** [comment]
I'd vote for the open program aswell.

**Comment by jesmrec** [comment]
open + 1

**Comment by davigonz** [comment]
Ok, thank you for voting, I also think that the open program is the best option in our case.

What about the feedback channel? Do we choose one or two such as Github and central for instance or include email and whatever? The less we have, the easier could be to manage all the information.

@michaelstingl @Kawohl @jesmrec

**Comment by michaelstingl** [comment]
@davigonz what is the main feedback channel for the final Play Store app? I think https://central.owncloud.org is good. If we ask user in a issue to test and provide feedback, then it's clear.

**Comment by jesmrec** [comment]
i would rather not to use central as main channel for feedback, but something more specific for this aim. Apps mail could be a good option as well as an specific github issue.

**Comment by davigonz** [comment]
@michaelstingl The current main feedback channel for the final Play Store app is apps mail. We could use apps mail as channel in beta app also, apart from any other channel. I will check if it's possible to configure several feedback channels in the open beta.

**Comment by davigonz** [comment]
Since publishing the beta app is a release itself, It would be needed a new certificate to sign the apk. Who's the responsible for the certificate generation @michaelstingl? Thank you

**Comment by davivel** [comment]
This is not urgent. Moving to next release.

**Comment by davigonz** [comment]
We have finished our work here, @lefherz will spread the word by doing social media magic 🌟
