### ISSUE TITLE
[feature request] Implementation of client side certificates

### ISSUE THREAD

**Issue by sikgerar** [owncloud/android#2002]
### Actual behaviour
No Implementation of client side certificates. Server side certificates are working without an issue.

### Expected behaviour
Implementation of client side certificates on core and android app so clients may be forced to log in with password and certificate.
Implementation should allow to clients (or android app) to provide certificate for intermediate validation prior to login on owncloud.
 
### Steps to reproduce
N/A

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
N/A

### Environment data
Android version:
All
Device model: 
All
Stock or customized system:
N/A
ownCloud app version:
2.4.0
ownCloud server version:
N/A
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Thanks for your suggestion. We will study it.

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/android/issues/163
