### ISSUE TITLE
Forbidden reshare not reflected in the UI 

### ISSUE THREAD

**Issue by davivel** [owncloud/android#2004]
#I have disabled resharing in the oC server settings, but if I create a new share in the Android UI, it still shows the option "Can share enabled". In the web UI or desktop UI this option isn't shown in the same case.

- Web UI
<img width="726" alt="oc_sharing" src="https://user-images.githubusercontent.com/214010/27550141-dd8e5872-5a9e-11e7-8987-e0b73055f8b6.png">

- Android UI

<img width="726" alt="oc_sharing" src="https://user-images.githubusercontent.com/15261363/29159589-6365ca88-7daf-11e7-8eb4-8c86750b45d5.png">

### Steps to reproduce
1. Disable "Allow reshare" in Admin settings
2. Create share in iOS app

### Expected behaviour
"Can share" should be hidden if resharing has been disabled

### Actual behaviour
"Can share" is visible

### Server configuration

**ownCloud version:**
9.1.6, 10.0.2

### Client
**Android version:**
6.0.1

**ownCloud app version:**
2.4.0

**Device model:**
Samsung Galaxy Note 4

Sibling: https://github.com/owncloud/ios/issues/915

**Comment by jesmrec** [comment]
QA blocked, pending to check federated shares with SAML servers. Caused by:

https://github.com/owncloud/user_shibboleth/issues/195

**Comment by jesmrec** [comment]
Let's move on this issue. In spite of having the bug with SAML, i don't expect a bad behaviour in Android app. In the worse case, the behaviour will be isolated and will be faced easily.

@davigonz @davivel
