### ISSUE TITLE
Connection check failed (Unknown Error) with Lineage OS 14.1

### ISSUE THREAD

**Issue by mark-orion** [owncloud/android#2010]
### Actual behaviour
After I entered my server URL in the form https://servername.tld/owncloud the app shows "unknown error"
- The app used to work with Android 5.1
- Web access and desktop client work fine - its only the Android client that fails.
- Other Android apps like DavDroid can use the calendar and contacts store on ownCloud without problems.
- The server is using cacert as root.ca. The cacert root certificate is installed as user certificate on the phone.
- I tried the 2.5 beta version but encounter the same problem.

### Expected behaviour
- I can connect to my owncloud server (used to work under Android 5.1)
- I am getting prompted for any SSL problems and have the option to accept (self signed) certificates instead of the "Unknown Error".

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No this works, but connection test takes almost a minute

### Environment data
Android version: Lineage OS 14.1 / Android 7.1.2

Device model: Fairphone 2

Stock or customized system: customized system

ownCloud app version: 2.4.0

ownCloud server version: 9.1

#### Web server error log
The web server is not responding because the SSL handshake fails

I have attached a filtered logcat:

[owncloud_logcat.txt](https://github.com/owncloud/android/files/1180486/owncloud_logcat.txt)

**Comment by jesmrec** [comment]
@mark-orion still reproducible?
