### ISSUE TITLE
OC Audio player crashes when WIFI turned off

### ISSUE THREAD

**Issue by gophee** [owncloud/android#2011]
### Actual behaviour
OC crushes in different situation where WIFI turned of or unreachable.
In the following video you can find two scenarios: 
1. Wifi turned on - OC not crushes
2. Wifi is off - OC crushes
3. In both of the cases the OC web server is unreachable (server is deliberately down).
4. Video: 
https://s3-eu-west-1.amazonaws.com/mp.4/WhatsApp+Video+2017-07-29+at+14.22.23.mp4
4. Files in the OC app shown in the Video are mp3

### Expected behaviour
OC app should not crush at all.
 
### Steps to reproduce
1. Steps are given in the Video

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
In my example server should be temporarily down or unreachable. yet the app crushes.

### Environment data
Android version: 4.4.2

Device model: I9355A

ownCloud app version: 2.4.0

Logs:
[logcat.txt](https://github.com/owncloud/android/files/1184943/logcat.txt)

Thank you
Ziv

**Comment by jesmrec** [comment]
Checked with a couple of devices 4.4.2 and not reproducible with server down. I checked also with shared folders, so i noticed in your video the sharing icon in the folder you showed.

Could you check with the beta1 version released in F-Droid? 

https://f-droid.org/packages/com.owncloud.android.beta/

if you reproduce the problem, you can ship us the logs you will find in "Settings" to apps@owncloud.com

**Comment by gophee** [comment]
Thanks Jesus, will do it and let you know

**Comment by gophee** [comment]
i have downloaded and installed the f-droid, how do i apply the owncloud
repository ?

thanks
Ziv

On Thu, Aug 3, 2017 at 1:48 PM, Jesús Recio Rincón <notifications@github.com

**Comment by gophee** [comment]
i have managed to install the beta version through F-Droid, i also managed
to reproduced the bug.
where do i find the crash logs ?

Thanks
Ziv

**Comment by jesmrec** [comment]
in Settings view

**Comment by gophee** [comment]
Couldn't find it there, but managed to get the crash log through the crash
log app.

This is the crash log of the owncloud 2.5.0-beta.1

CrashLog 2.0.0(14)
Device : alps IPRO
Build number : eng.jessen.1438841807
CPU ABI : armeabi-v7a
Kernel version : 3.4.67
Firmware version : 4.4.2
Screen width : 320
Screen height : 480

ct(IoBridge.java:112)
08-03 19:32:04.294 E/SynchronizeFolderOperation( 2327): ... 23 more
08-03 19:32:04.573 E/WifiManager( 3273): mWifiServiceMessenger == null
08-03 19:32:04.747 W/dalvikvm( 2622): VFY: unable to resolve virtual method
21982: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/
Drawable;
08-03 19:32:04.749 W/dalvikvm( 2622): VFY: unable to resolve virtual method
22017: Landroid/content/Context;.startForegroundService
(Landroid/content/Intent;)Landroid/content/ComponentName;
08-03 19:32:04.749 W/dalvikvm( 2622): VFY: unable to resolve virtual method
21979: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/
ColorStateList;
08-03 19:32:04.750 W/dalvikvm( 2622): VFY: unable to resolve virtual method
22001: Landroid/content/Context;.isDeviceProtectedStorage ()Z
08-03 19:32:04.750 W/dalvikvm( 2622): VFY: unable to resolve virtual method
21978: Landroid/content/Context;.getColor (I)I
08-03 19:32:07.019 E/RemoteViews(  665): ANR Warning,RemoteViews can only
be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI.
keys for search <ANR Exception MSG   History>
08-03 19:32:07.021 E/RemoteViews(  665): ANR Warning,RemoteViews can only
be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI.
keys for search <ANR Exception MSG   History>
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): Download of
/DC3/D09_1910_Disc_German_10d.mp3 to /storage/sdcard0/owncloud Beta/tmp/
DC3@10.0.0.108%3A8001%2Fowncloud/DC3/D09_1910_Disc_German_10d.mp3: Socket
exception
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327):
java.net.ConnectException: failed to connect to /10.0.0.108 (port 8001)
after 60000ms: connect failed: ENETUNREACH (Network is unreachable)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
libcore.io.IoBridge.connect(IoBridge.java:114)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
java.net.PlainSocketImpl.connect(PlainSocketImpl.java:475)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
java.net.Socket.connect(Socket.java:861)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
java.lang.reflect.Method.invokeNative(Native Method)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
java.lang.reflect.Method.invoke(Method.java:515)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(
ReflectionSocketFactory.java:140)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.
createSocket(DefaultProtocolSocketFactory.java:125)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.MultiThreadedHttpConnectionMan
ager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionMan
ager.java:1361)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(
HttpMethodDirector.java:387)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.HttpMethodDirector.executeMethod(
HttpMethodDirector.java:171)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.
java:224)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.
downloadFile(DownloadRemoteFileOperation.java:112)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.run(
DownloadRemoteFileOperation.java:86)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.lib.common.operations.RemoteOperation.execute(
RemoteOperation.java:136)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.operations.DownloadFileOperation.run(
DownloadFileOperation.java:157)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.lib.common.operations.RemoteOperation.execute(
RemoteOperation.java:136)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.files.services.FileDownloader.
downloadFile(FileDownloader.java:436)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.files.services.FileDownloader.
access$500(FileDownloader.java:71)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
com.owncloud.android.files.services.FileDownloader$
ServiceHandler.handleMessage(FileDownloader.java:381)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
android.os.Handler.dispatchMessage(Handler.java:110)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
android.os.Looper.loop(Looper.java:193)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
android.os.HandlerThread.run(HandlerThread.java:61)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): Caused by:
libcore.io.ErrnoException: connect failed: ENETUNREACH (Network is
unreachable)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
libcore.io.Posix.connect(Native Method)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
libcore.io.IoBridge.connectErrno(IoBridge.java:159)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): at
libcore.io.IoBridge.connect(IoBridge.java:112)
08-03 19:32:07.127 E/DownloadRemoteFileOperation( 2327): ... 25 more
08-03 19:32:07.212 E/dalvikvm( 2327): Could not find class
'android.app.job.JobInfo$Builder', referenced from method
com.owncloud.android.files.services.TransferRequester.scheduleTransfer
08-03 19:32:07.212 W/dalvikvm( 2327): VFY: unable to resolve new-instance
64 (Landroid/app/job/JobInfo$Builder;) in Lcom/owncloud/android/files/
services/TransferRequester;
08-03 19:32:07.264 E/dalvikvm( 2327): Could not find class
'com.owncloud.android.files.services.RetryDownloadJobService', referenced
from method com.owncloud.android.files.services.TransferRequester.
scheduleDownload
08-03 19:32:07.264 W/dalvikvm( 2327): VFY: unable to resolve const-class
3399 (Lcom/owncloud/android/files/services/RetryDownloadJobService;) in
Lcom/owncloud/android/files/services/TransferRequester;
08-03 19:32:07.275 E/dalvikvm( 2327): Could not find class
'com.owncloud.android.files.services.RetryUploadJobService', referenced
from method com.owncloud.android.files.services.TransferRequester.
scheduleUpload
08-03 19:32:07.275 W/dalvikvm( 2327): VFY: unable to resolve const-class
3400 (Lcom/owncloud/android/files/services/RetryUploadJobService;) in
Lcom/owncloud/android/files/services/TransferRequester;
08-03 19:32:07.302 E/AndroidRuntime( 2327): FATAL EXCEPTION:
FileDownloaderThread
08-03 19:32:07.302 E/AndroidRuntime( 2327): Process:
com.owncloud.android.beta, PID: 2327
08-03 19:32:07.302 E/AndroidRuntime( 2327): java.lang.NoClassDefFoundError:
com.owncloud.android.files.services.RetryDownloadJobService
08-03 19:32:07.302 E/AndroidRuntime( 2327): at com.owncloud.android.files.
services.TransferRequester.scheduleDownload(TransferRequester.java:245)
08-03 19:32:07.302 E/AndroidRuntime( 2327): at com.owncloud.android.files.
services.FileDownloader.downloadFile(FileDownloader.java:461)
08-03 19:32:07.302 E/AndroidRuntime( 2327): at com.owncloud.android.files.
services.FileDownloader.access$500(FileDownloader.java:71)
08-03 19:32:07.302 E/AndroidRuntime( 2327): at com.owncloud.android.files.
services.FileDownloader$ServiceHandler.handleMessage(
FileDownloader.java:381)
08-03 19:32:07.302 E/AndroidRuntime( 2327): at android.os.Handler.
dispatchMessage(Handler.java:110)
08-03 19:32:07.302 E/AndroidRuntime( 2327): at
android.os.Looper.loop(Looper.java:193)
08-03 19:32:07.302 E/AndroidRuntime( 2327): at android.os.HandlerThread.run(
HandlerThread.java:61)
08-03 19:32:07.476 E/Crash Log( 2345): Crash

On Thu, Aug 3, 2017 at 6:46 PM, Jesús Recio Rincón <notifications@github.com

**Comment by gophee** [comment]
I have managed to access the OnwCloud logs as requested. I'm attaching the file here.
Please note that once the app crashes i can't get it working again until next "force stop" even if i turn wifi back on.

Thank You
Ziv
[currentLog.txt](https://github.com/owncloud/android/files/1202091/currentLog.txt)

**Comment by gophee** [comment]
Let me know if you need more logs or anything else to debug this problem. If you can't reproduce the bug i can send you one of the devices. LMK, Thanks Ziv

**Comment by jesmrec** [comment]
All info you can ship wlll be useful.

**Comment by gophee** [comment]
If you need more logs i can reproduce and send another examaple + video.
I'm also ready to send you the device itself for testing, would you like that ?
If so i need an address. you can contact me at: ziv@xyzet.me

**Comment by gophee** [comment]
Hello Jesús,
As requested i'm posting here another reproduction of the owncloud bug. 
The post contains:
1. A new [video](https://s3-eu-west-1.amazonaws.com/mp.4/owncloud_bug_aug26.mov) that shows the bug reproduction
2. Two crash log files, one from the ownCloudBeta, the other from the [crashlog app](https://play.google.com/store/apps/details?id=crashLog.cutebabyTW&hl=en)

**Bug Description and Circumstances**:
1. Android device is connected to WiFi
2. The owncloud web server is down or not in reach.
3. Attempt #1 to download an audio file (which will not happen due to server inavailability)
4. Disconnect device WiFi
5. Attempt #2 to download an audio file
6. ownCloud Crash

[CrashLog App.pdf](https://github.com/owncloud/android/files/1253804/CrashLog.App.pdf)
[Owncloud Beta crash log.txt](https://github.com/owncloud/android/files/1253805/Owncloud.Beta.crash.log.txt)
Video: https://s3-eu-west-1.amazonaws.com/mp.4/owncloud_bug_aug26.mov

Thanks you 
Ziv

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
