### ISSUE TITLE
issue after refactoring package name - urgent

### ISSUE THREAD

**Issue by lazarvgd** [owncloud/android#2014]
Hi I have refactored package of owncloud app. I have changed in manifest and folder names, but run into this problem:

`Error while executing: am start -n "com.owncloud.android/rs.test.cloudbox.ui.activity.FileDisplayActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER`

How can I solve this problem?

**Comment by davigonz** [comment]
Hi again @lazarvgd , have you already solved this problem?

**Comment by lazarvgd** [comment]
Hi, I have solved this problem by deleting build folder, rebuilding the project and restarting the studio.
Thnaks

**Comment by davigonz** [comment]
@lazarvgd I'm glad to know you've solved it by your own, well done!
