### ISSUE TITLE
wifi memory leak on devices with OS version < Android N

### ISSUE THREAD

**Issue by lazarvgd** [owncloud/android#2017]
Hi I have generated signed APK in order to upload app on store, but I got this message:

`Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing  to .getApplicationContext()  [WifiManagerLeak]`

I have googled and found the [solution](https://stackoverflow.com/questions/42621010/signed-apk-error-wifimanagerleak), but I got the another and warnings:
whole error you can find [here](http://pasted.co/cc7e525f)(it is too large to past in PasteBin, so I had to use pasted)

Does anybody know why this error is occurring?

**Comment by davigonz** [comment]
Hi @lazarvgd , try adding the next line in the build.gradle file in the app module:

`lintOptions { abortOnError false }`

**Comment by davigonz** [comment]
Hi again @lazarvgd , have you tried the solution I commented above?

**Comment by lazarvgd** [comment]
Hi @davigonz, Yes I did and it worked. Thanks!

p.s. sorry for delayed answer I was on vacation and completely forgot to update the thread.

**Comment by jesmrec** [comment]
We have a contribution to fix this problem:

https://github.com/owncloud/android/pull/2016

**Comment by davigonz** [comment]
No problem @lazarvgd , if you have more questions in the future, just ask us ☺️

**Comment by lazarvgd** [comment]
Sure, I will!

Thank you again @davigonz
