### ISSUE TITLE
[2.5.0 beta v2] Release new beta version in FDroid

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2020]
AC:

 - [x] [GIT] Merge oauth2_support branch into master in owncloud/android.
 - [x] [GIT] Create and sign tag oc-android-2.5.0-beta.2 in HEAD commit of master branch, in owncloud/android.
 - [x] [DEV] Create MR in FDroid repo https://gitlab.com/fdroid/fdroiddata/ @theScrabi
MR link: https://gitlab.com/fdroid/fdroiddata/merge_requests/2498
 - [ ] [DIS] Announce the new beta version in ownCloud blog/social media @lefherz

**Comment by davigonz** [comment]
Hi @theScrabi , we would like to update the beta app in FDroid, the commit to use would be **oc-android-2.5.0-beta.2** , could you please open the MR in FDroid repo? Thanks

**Comment by theScrabi** [comment]
I have several Issues.
The [version code](https://github.com/owncloud/android/blob/master/build.gradle#L191) is still the same as in the last beta version, and the version number seems to be the same as well. Fdroid rejects that.

**Comment by davigonz** [comment]
Hi @theScrabi , I've just updated the beta version code and version name, try it again using the **oc-android-2.5.0-beta.2** tag, thanks

**Comment by theScrabi** [comment]
pull request for fdroid released:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2498

**Comment by davigonz** [comment]
The beta is on fdroid since Saturday so we can close this
