### ISSUE TITLE
Cannot edit file using associated apps at Android Nougat / GalaxyTab S3 (but works on other Android version))

### ISSUE THREAD

**Issue by vals-productions** [owncloud/android#2022]
### Actual behaviour
Environment: Android Nougat, Samsung Galaxy Tab S3.

The user would like to edit a file from owncloud using associated application and have file updated in the owncloud after editing.

- navigate to the file to edit. let's say it is file.txt
- click on the text file that you'd like to edit (file.txt)
- after file opens in preview, pick "open with" menu
- select an application available to edit the file (in this example I am using WriterP editor)
- WriterP opens a new file - does not pick up file's content or file name.
- the file is not being saved back to the ownCloud when exiting WriterP.

the above behavior is true for any file types, not just for *.txt. I tried excel, word, etc.

### Expected behaviour

- WriterP should open file.txt picking up its content and file name in the title
- owncloud should update file.txt after editing in WriterP is finished.
 
this should work for other file types as well.

This works correctly at Galaxy Note 3, Android 5.0

### Steps to reproduce
- navigate to the file to edit. let's say it is file.txt
- click on the text file that you'd like to edit (file.txt)
- after file opens in preview, pick "open with" menu
- select an application available to edit the file (in this example I am using WriterP editor)
- WriterP opens a new file - does not pick up file's content or file name.
- the file is not being saved back to the ownCloud when exiting WriterP.

### Environment data
Android version: Android Nougat

Device model: Samsung Galaxy Tab 3

Stock or customized system: stock

ownCloud app version: 2.4.0

ownCloud server version: does not matter

**Comment by vals-productions** [comment]
Same applies to the phone with Android Nougat. So looks like this is Nougat specific issue.

**Comment by YMDH** [comment]
I can confirm having the same problem on a Galaxy Tab A which was recently upgraded to Android 7.

**Comment by jesmrec** [comment]
Already implemented and available in 2.20 version. After editing, browsing is required tu upload the new file version.
