### ISSUE TITLE
Feature Request - Camera Upload

### ISSUE THREAD

**Issue by gpullen** [owncloud/android#2027]
Under the 'Upload' button,  it would be great if we can immediately take a photo or series of photos that are saved directly to the cloud.

Many thanks

**Comment by jesmrec** [comment]
Thanks for your suggestion!!

**Comment by sd1998** [comment]
Is someone working on this issue?

**Comment by sd1998** [comment]
@davigonz Thanks I will be working in this Issue

**Comment by davigonz** [comment]
Great @sd1998 ! If you have any question, do not hesitate in asking me

**Comment by sd1998** [comment]
@davigonz Thanks :)

**Comment by sd1998** [comment]
@davigonz Should I also add the functionality to directly upload a video taken from the camera?

**Comment by gpullen** [comment]
@sd1998 Yes if possible, this would really help us!

Many thanks for working on this!

**Comment by sd1998** [comment]
@gpullen I will be sending the PR for the same by tomorrow

**Comment by sd1998** [comment]
@gpullen 
I am having this error while running this app on my device

<img width="409" alt="screen shot 2017-10-27 at 12 24 39 am" src="https://user-images.githubusercontent.com/22047421/32071627-79d4ea2a-baad-11e7-831f-e26f72ec8f56.png">

<img width="1340" alt="screen shot 2017-10-27 at 12 24 56 am" src="https://user-images.githubusercontent.com/22047421/32071633-7b71d910-baad-11e7-85d2-7a38559fb554.png">

Please help me with this so that I can test the initial changes that I have done.

**Comment by gpullen** [comment]
No idea, I'm afraid I'm not an android coder... Just an end user requesting a feature!  Good luck!

**Comment by sd1998** [comment]
@davigonz Can you help me with the same?

**Comment by davigonz** [comment]
> I am having this error while running this app on my device

> Can you help me with the same?

Follow up: https://github.com/owncloud/android/issues/2060

**Comment by davigonz** [comment]
> Should I also add the functionality to directly upload a video taken from the camera?

@sd1998 sorry I missed this question, that issue is being addressing in instant uploads feature https://github.com/owncloud/android/issues/2028. Do not worry about that.

**Comment by davigonz** [comment]
@gpullen @sd1998 I include here a mockup with a new button with the text "Take picture" that appears when pressing the floating action button, as @jesmrec suggests in https://github.com/owncloud/android/pull/2059#issuecomment-341375182

![screen shot 2017-11-03 at 09 24 30](https://user-images.githubusercontent.com/15261363/32365202-377adf78-c079-11e7-945b-59ebab075a20.png)

**Comment by jesmrec** [comment]
@davigonz i would call it "Upload picture", so you are taking a pic, and then it is uploaded.

**Comment by davigonz** [comment]
> I would call it "Upload picture", so you are taking a pic, and then it is uploaded.

The name you suggest could be used for another feature which is "Upload pictures or videos", that would open a new view with the images and videos stored in the device and user could select them to upload.

**Comment by jesmrec** [comment]
IMHO `Take picture` does not explain clearly what this feature does. The name of this feature should include `Upload` since uploading is the main feature we are offering (taking the pic is a task of the camera, not of the app). Other options... `Take & Upload` , `Content from Camera` (similar as the option below for external files), `Camera`(maybe little specific)... 

We could also call `Instant uploads`, so this kind of uploads will be performed instantly (you need the app mandatorily in foreground to perform the upload). But i know that this one would be confusing for the users, taking in account other alive discussions related with https://github.com/owncloud/android/issues/2028

do you have any thoughts @gpullen @sd1998 @michaelstingl

**Comment by davigonz** [comment]
> IMHO Take picture does not explain clearly what this feature does. The name of this feature should include Upload since uploading is the main feature we are offering (taking the pic is a task of the camera, not of the app).

@jesmrec Yes, that name can be confusing, what about "Upload from camera"?

**Comment by jesmrec** [comment]
> @jesmrec Yes, that name can be confusing, what about "Upload from camera"?

sounds good for me.

**Comment by davigonz** [comment]
Hi @sd1998 , have you progressed in this feature?

**Comment by sd1998** [comment]
@davigonz I am facing a exception which results in the application to crash.
<img width="1098" alt="screen shot 2017-12-13 at 4 04 51 pm" src="https://user-images.githubusercontent.com/22047421/33934619-73beb638-e01f-11e7-963a-09e50ffee824.png">
<img width="963" alt="screen shot 2017-12-13 at 4 05 06 pm" src="https://user-images.githubusercontent.com/22047421/33934622-7524ac4e-e01f-11e7-8561-73a4cbfb5744.png">
<img width="590" alt="screen shot 2017-12-13 at 4 05 15 pm" src="https://user-images.githubusercontent.com/22047421/33934625-79b3c1a0-e01f-11e7-9420-ebc15a29d95c.png">

**Comment by jesmrec** [comment]
@sd1998 it sounds like a lack of permissions in `AndroidManifest.xml`

did you add?:

`<uses-feature android:name="android.hardware.camera"
                           android:required="true" />`

**Comment by sd1998** [comment]
@davigonz  @jesmrec Yes I have fixed that and the feature is working. And could you tell me which file should I edit so that I can add the Upload from camera option in the Floating Action Button.

**Comment by davigonz** [comment]
> Yes I have fixed that and the feature is working. And could you tell me which file should I edit so that I can add the Upload from camera option in the Floating Action Button As shown in comment.

Hi @sd1998, I can give you some pointers:
1. In [ExtendedListFragment file](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/fragment/ExtendedListFragment.java#L76) you will found the different Floating Action buttons we currently have, so you have to include the new one there and initialize it.
2. In [OCFileListFragment file](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/fragment/OCFileListFragment.java#L81) we have several methods you need to use:
- One for setting the different Floating Action buttons labels.
- Other one for registering a new listener for each Floating Action button, and adding the functionality.

**Comment by sd1998** [comment]
@davigonz Thanks I will work on this and send a pull request.

**Comment by sd1998** [comment]
@davigonz Will this project be there for GSOC-18?

**Comment by jesmrec** [comment]
@sd1998 it is quite soon to talk about that.

**Comment by michaelstingl** [comment]
@sd1998 ==> https://central.owncloud.org/c/gsoc

**Comment by sd1998** [comment]
@jesmrec @michaelstingl  Thanks

**Comment by davigonz** [comment]
Deleting instant upload label, this feature is not related with that...

**Comment by davigonz** [comment]
It will release within next version 2.7.0
