### ISSUE TITLE
SSL initialization failed

### ISSUE THREAD

**Issue by elutz** [owncloud/android#2029]
### Actual behaviour
Working with the Owncloud app stops working suddenly, now I get the error "SSL initialization failed". I tried to delete my account in the app, now I'm not able to reconnect to my ouwncloud server with the same error: "SSL initialization failed".
The problem came up after an update of the phone's OS (at least I think so).
The device is a Blackberry Z10 which is able to run Android apps since there is an special Android layer within the OS called Android Player.
Using the web interface of the owncloud server from within the browser on the phone works.

I'm pretty sure the problem lies in the server's SSL configuration. But I'm not able to find the cause resp. to adjust the settings. And I haven't access to all config data since it is a shared server.
Test on https://www.ssllabs.com/ssltest/ gives A+

### Expected behaviour
Of course I would like to connect to the server using the app.
 
### Steps to reproduce
1. In the app try to add a new account
2. Type in the server address: https://....
3. The connection will be tested and the tests ends with the mentioned error message

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

No, I'm not able to reproduce the problem with demo.owncloud.org. It works fine.

### Environment data
Android version: Blackberry OS 10.3.3.2163 

Device model: Blackberry Z10

Stock or customized system: Stock system

ownCloud app version: 2.4.0

ownCloud server version: ownCloud 9.0.10 (stable)

#### Web server error log
(It's a snippet of Sep 04 because I've done on this day one connection test only) 
``` [Mon Sep 04 02:14:51.834733 2017] [core:info] [pid 23727:tid 139994846267136] [client 134.119.222.21:47304] AH00128: File does not exist: /usr/www/users/epperl/a2billing/admin/Public/index.php
[Mon Sep 04 09:14:06.393452 2017] [core:info] [pid 2434:tid 139994651911936] [client 114.215.149.183:55807] AH00128: File does not exist: /usr/www/users/epperl/phpMyAdmin/scripts/setup.php
[Mon Sep 04 09:14:16.372147 2017] [core:info] [pid 23727:tid 139995031238400] [client 114.215.149.183:56378] AH00128: File does not exist: /usr/www/users/epperl/pma/scripts/setup.php
[Mon Sep 04 09:14:26.348904 2017] [core:info] [pid 23727:tid 139994685482752] [client 114.215.149.183:56984] AH00128: File does not exist: /usr/www/users/epperl/myadmin/scripts/setup.php
[Mon Sep 04 14:30:50.206051 2017] [cgid:error] [pid 5214:tid 140154913056512] [client 186.207.19.19:60643] AH01262: Options ExecCGI is off in this directory: /usr/www/users/epperl/hndUnblock.cgi
[Mon Sep 04 14:30:53.226046 2017] [cgid:error] [pid 17409:tid 140154723337984] [client 186.207.19.19:60657] AH01262: Options ExecCGI is off in this directory: /usr/www/users/epperl/tmUnblock.cgi
[Mon Sep 04 14:30:56.232938 2017] [core:info] [pid 17565:tid 140154748516096] [client 186.207.19.19:60674] AH00128: File does not exist: /usr/www/users/epperl/moo
[Mon Sep 04 19:11:56.425481 2017] [core:info] [pid 17409:tid 140154756908800] [client 122.154.239.109:55604] AH00128: File does not exist: /usr/www/users/epperl/phpMyAdmin/scripts/setup.php
[Mon Sep 04 19:13:14.624921 2017] [core:info] [pid 17565:tid 140154913056512] [client 122.154.239.109:60436] AH00128: File does not exist: /usr/www/users/epperl/pma/scripts/setup.php
[Mon Sep 04 19:14:32.891888 2017] [core:info] [pid 17565:tid 140154871092992] [client 122.154.239.109:49344] AH00128: File does not exist: /usr/www/users/epperl/myadmin/scripts/setup.php
[Mon Sep 04 20:51:31.187401 2017] [core:info] [pid 17442:tid 140154773694208] [client 163.172.64.133:55514] AH00128: File does not exist: /usr/www/users/epperl/a2billing/admin/Public/index.php
[Mon Sep 04 21:22:53.983987 2017] [core:info] [pid 17442:tid 140154740123392] [client 163.172.64.133:47040] AH00128: File does not exist: /usr/www/users/epperl/a2billing/admin/Public/index.php
[Mon Sep 04 23:50:25.646046 2017] [core:info] [pid 14247:tid 140154862700288] [client 93.65.210.204:33160] AH00128: File does not exist: /usr/www/users/epperl/phpMyAdmin/scripts/setup.php
[Mon Sep 04 23:50:30.732396 2017] [core:info] [pid 14247:tid 140155039278848] [client 93.65.210.204:34045] AH00128: File does not exist: /usr/www/users/epperl/pma/scripts/setup.php
[Mon Sep 04 23:50:35.815685 2017] [core:info] [pid 19423:tid 140154913056512] [client 93.65.210.204:34943] AH00128: File does not exist: /usr/www/users/epperl/myadmin/scripts/setup.php
```
Insert your webserver log here
You can find it here: https://epperleinberlin.name/owncloud/index.php/s/lEOBBa8bKCcccsN
But there isn't any related content, I'm afraid.

#### ownCloud log (data/owncloud.log)
There aren't any entries for Sep 04 (see above). This here doesn't seem to be related:
```
{"reqId":"GViceHXQA+JWwOswSf62","remoteAddr":"87.164.xx.xx","app":"files_versions","message":"Mark to expire \/documents\/Heike\/xxxxxxxxxxxxxxx.odt next version should be 1503083250 or smaller. (prevTimestamp: 1503169650; step: 86400","level":1,"time":"2017-09-05T18:30:59+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GViceHXQA+JWwOswSf62","remoteAddr":"87.164.xx.xx","app":"files_versions","message":"Expire: \/documents\/Heike\/xxxxxxxxxxx.odt.v1503169495","level":1,"time":"2017-09-05T18:30:59+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"Q3MGKJVQALfyM4QRy\/bz","remoteAddr":"87.164.xx.xx","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-09-05T18:43:12+00:00","method":"POST","url":"\/owncloud\/index.php\/heartbeat","user":"xxxx"}
{"reqId":"Uh\/rOHJv5T7MPrOvQBGV","remoteAddr":"87.164.xx.xx","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-09-05T19:02:56+00:00","method":"POST","url":"\/owncloud\/index.php\/heartbeat","user":"xxxx"}
```

**Comment by MasterCassim** [comment]
I had the same problem; I got a new phone and switched from example.com/owncloud to owncloud.example.com; the problem was that the android client did not support SNI (at least that is what I expect) and the server answered with the certificate for example.com. After switching the default domain from example.com to owncloud.example.com it worked without a problem.

**Comment by jesmrec** [comment]
Blackberry is not currently supported by oC. Are you experiencing this problem only with blackberry or another kind of device?

**Comment by elutz** [comment]
Thanks for your answer. It reminds me to test the connection again. To be honest, after I posted the problem, I didn't try again, assuming it doesn't work anyway.

But the good news is, the app connects now and all is working fine.
I haven't any clue what the cause was. In the meantime there were updates of the app (2.5.0 now) and of the owncloud server (in the moment of writing 10.0.4.4). Maybe one of them fixed the issue.

Thanks for your effort and sorry for the noise ...
