### ISSUE TITLE
Adapt private link generation to core#28984

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#2032]
Related:
- https://github.com/owncloud/core/issues/28984
- https://github.com/owncloud/client/issues/6020
- https://github.com/owncloud/ios/issues/938

**Comment by davivel** [comment]
@michaelstingl , should be easy to do, I think it could be done for release 2.5.1

**Comment by jesmrec** [comment]
The private link will be displayed only if the property `<oc:privatelink>` is retrieved in the PROPFIND request. Othercase, private link will be neither shown nor available. 

This will be tested as expected behaviour for Android mobile client (and iOS later as well).

**Comment by jesmrec** [comment]
Approved

**Comment by jesmrec** [comment]
Already developed, tested and approved. 

Available in 2.5.1
