### ISSUE TITLE
custom Two provider app can not login from android application

### ISSUE THREAD

**Issue by nimahkh** [owncloud/android#2039]
### Actual behaviour
i have created two factor app , from this document  : https://doc.owncloud.org/server/10.0/developer_manual/app/two-factor-provider.html
on web browser , everything is ok , provider works like a charm , 
but on Android application , it says " wrong username or password " . 
i read about adding App password , but nothing change , maybe i do wrong , don't know , 

### Expected behaviour
i want to show my provider on android application too . 
user is coming to login , after checking username and  password , it shows an extra page , to verify authentication . 

### Environment data
Android version: 2.4.0

#### ownCloud log (data/owncloud.log)
```
HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

```

**Comment by michaelstingl** [comment]
You could use OAuth 2, then login and 2nd factor can be entered on the ownCloud website. (embedded in Android app)

**Comment by davigonz** [comment]
> You could use OAuth 2, then login and 2nd factor can be entered on the ownCloud website. (embedded in Android app)

+1 , @nimahkh you should be able to login with the next android app release (2.5.0)

**Comment by davigonz** [comment]
Hi again @nimahkh , have you tried it with the new 2.5.0 app? It is working for you now?

**Comment by nimahkh** [comment]
not yet . i'll try it . thanks a lot

**Comment by nimahkh** [comment]
@davigonz this version just have Oauth2 , owncloud can not support providers yet . :-( i have to write my web api to solve it ,

**Comment by davigonz** [comment]
Hi @nimahkh , glad to see that you have managed to fix the problem, I will close this issue then.
