### ISSUE TITLE
General project structure

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2044]
I see this in build.gradle

> This project was started in Eclipse and later moved to Android Studio. In the transition, both IDEs were supported.
> Due to this, the files layout is not the usual in new projects created with Android Studio / gradle. This file
> merges declarations usually split in two separates build.gradle file, one for global settings of the project in
> its root folder, another one for the app module in subfolder of root.

Guys, Eclipse and Android are no team any more, and this makes no sense since 2015 !
I would like to make an PR to change project structure with an `app` directory, like most Android apps are, but when I see how much open PR's are there I see no chance doing this.

Am I right ?

**Comment by davigonz** [comment]
Hi @hannesa2 , thank you for your suggestion, I agree with you, we should adapt the project structure to be similar to the current Android apps but it should be done carefully. 

You can try to do the needed changes and open a PR, contributions are always welcome 😉 . Don't worry about how many open PR's are opened, we will address it sooner or later and will be reviewed, tested and merged if everything is right.

**Comment by hannesa2** [comment]
Let's see if my PR will merged. Ticket points to PR #2046

**Comment by hannesa2** [comment]
Let's see how it is going in https://github.com/owncloud/android-library to see if a continue makes sense here
