### ISSUE TITLE
CookieSyncManager not needed from 21

### ISSUE THREAD

**Issue by frankFic** [owncloud/android#2052]
Hi, I found CookieSyncManager is instantiated in [WebviewDialog](https://github.com/owncloud/android/blob/f58114698b971365d4be0f9632cb58a0666b15c5/src/com/owncloud/android/ui/dialog/WebViewDialog.java#L154). I understand it was instantiated to avoid crashes when instantiating CookieManager. But from API 21, it is no longer needed and deprecated. CookieManager can work well by itself. (According to the [doc](https://developer.android.com/reference/android/webkit/CookieSyncManager.html))

**Comment by jesmrec** [comment]
Thanks for the tip @frankFic. You know, contributions are always welcome ;)
