### ISSUE TITLE
Send a unique X-Request-ID header to allow tracing requests in apache and owncloud logs

### ISSUE THREAD

**Issue by butonic** [owncloud/android#2055]
https://github.com/owncloud/core/pull/28144 has been merged. It will use the value of a `X-Request-ID` header as the request id in log files to allow linking events on the client to events in the apache and owncloud logs.

- [x] generate a string to use as unique id.
  - 20-200 chars
  - only `[a-zA-Z0-9-+/_=.:]` allowed
- [ ] use it in the client log
- [x] send it as `X-Request-ID` header on every request

**Comment by michaelstingl** [comment]
Client log only works if Android app is built with debug option, for example the beta builds in Play Store ad F-Droid (available in ownBrander too).

**Comment by davigonz** [comment]
I've just implemented this in the network library replacement branch, chttps://github.com/owncloud/android/pull/2236/commits/cd60d63ab445d5bcb89705d2855b81aeb8b5c152b5c152

**Comment by michaelstingl** [comment]
cool, awesome!

**Comment by jesmrec** [comment]
i'd use UUID notation (as in new iOS app) for each request (32 hexadecimal digits: 8 + 4 + 4 + 4 + 12). I think it is a bit cleaner than using any character and any length between 20 and 200. 

For logs in debug, including the id + method is enough info from my pov to debug-track issues
