### ISSUE TITLE
Unable to build app on android studio

### ISSUE THREAD

**Issue by sd1998** [owncloud/android#2057]
### Actual behaviour
Unable to build the app on Android Studio

### Expected behaviour
There should be no error while building the app
 
### Steps to reproduce
1. Import the project in android studio

**Screenshot of the issue**

<img width="1401" alt="screen shot 2017-10-26 at 12 35 39 pm" src="https://user-images.githubusercontent.com/22047421/32039155-aa27da38-ba4a-11e7-88b0-802f64ffcdf4.png">

**Comment by davigonz** [comment]
Hi @sd1998 , what is the command you've used to clone the repo? **owncloud-android-library** is a submodule of the app and is needed to build the app properly. 

To include submodules when cloning a repo you should add the **--recursive** flag, e.g:

`git clone --recursive git@github.com:owncloud/android.git`

**Comment by sd1998** [comment]
@davigonz Thanks
