### ISSUE TITLE
As DevOps I'd like a complete guide on building the Android OC client so that we can perform automated builds in Jenkins

### ISSUE THREAD

**Issue by grantc** [owncloud/android#206]
SETUP.md is rather light on details on setting up a new environment for building the OC Android app. I'd like to setup an environment under Jenkins to be able to build and test every commit to develop. What I feel is missing:

* List of 3rd party libraries the app uses and links to how to build and install them
* List of software dependencies needed to build the app, specifying versions there are version dependencies
* Steps needed to build the app from the command line and for different environments (i.e. Eclipse).

IMNSHO, without these details it makes it difficult for someone new to the project to get up an running quickly.

**Comment by tobiasKaminsky** [comment]
@davivel this can be closed now, or?

**Comment by tobiasKaminsky** [comment]
@grantc setup.md should be detailed enough.
If not please reopen.
