### ISSUE TITLE
Error while trying to run the app on my device using android studio

### ISSUE THREAD

**Issue by sd1998** [owncloud/android#2060]
### Actual behaviour
Unable to run the app on my device using android studio.

### Expected behaviour
The app should run on my device
 
### Steps to reproduce
1. Open Android Studio
2. Click the run button
3. Select their device from the list of available devices

### Environment data
Android version: 7.1.1

Device model: OnePlus 3T

<img width="408" alt="screen shot 2017-10-29 at 3 25 00 pm" src="https://user-images.githubusercontent.com/22047421/32142479-ede53d2c-bcbd-11e7-95e0-7c97a78d83d4.png">
<img width="1402" alt="screen shot 2017-10-29 at 3 25 21 pm" src="https://user-images.githubusercontent.com/22047421/32142480-eea2c2ac-bcbd-11e7-838e-29a67dd75e9b.png">

**Comment by davigonz** [comment]
This error may appear because you have the ownCloud release app installed and when you try to install the apk generated during development, which is different to the release one and not signed,  a conflict is triggered when Android tries to update the release app with the debug app.

**Comment by sd1998** [comment]
@davigonz  I tried that but still I am getting the same error.

**Comment by davigonz** [comment]
Hi again @sd1998 , try the next steps in Android Studio: 
1. Open "Build" menu in the top bar and click "Clean project" option.
2. Open "Build" menu again and click "Rebuild project" option.
3. Click the run button and select the device/emulator.

**Comment by sd1998** [comment]
@davigonz I tried that also but I am still getting the same error.

**Comment by davigonz** [comment]
Hi @sd1998 , are you using the code just downloaded from the github repo or have you included any change? With which branch are you working?

**Comment by sd1998** [comment]
@davigonz I add the camera upload feature and I am working on the master branch should I work on the beta?

**Comment by davigonz** [comment]
@sd1998 I meant if you were having the same error before applying your changes. It doesn't matter the branch you are using in your repo, as long as it has been created from master branch.

**Comment by sd1998** [comment]
@davigonz  Yes I was getting the same error before making the changes.

**Comment by davigonz** [comment]
@sd1998 hmm, could you attach here the details when clicking Binder-java:580? Thanks

<img width="1402" alt="32142480-eea2c2ac-bcbd-11e7-838e-29a67dd75e9b" src="https://user-images.githubusercontent.com/15261363/32366886-6137d0a8-c080-11e7-85eb-611b45477f7a.png">

**Comment by sd1998** [comment]
@davigonz On clicking  android studio opens the Binder.java class
and the following is shown:-

<img width="1402" alt="screen shot 2017-11-03 at 6 13 29 pm" src="https://user-images.githubusercontent.com/22047421/32374247-d9472c14-c0c2-11e7-855b-d339c5add412.png">

And here is the Binder.java file:-

[Binder.zip](https://github.com/owncloud/android/files/1441046/Binder.zip)


I downloaded the Android API 24 Platform but still it is showing the same message.
Can there be a problem if I have JAVA9?

**Comment by davigonz** [comment]
@sd1998 Try to generate the apk file and install it manually in the device. It's possible that once the app is installed, the next time you press the run button in Android Studio, it will work.

Follow the next steps: 
1. Press Build menu.
2. Option Build Apk.
3. A dialog will appear pointing you to the folder in which the apk has been saved.
4. Copy the apk to your device and install it.

**Comment by sd1998** [comment]
@davigonz I tried it and it did not work I am receiving the same error.

**Comment by jesmrec** [comment]
> Can there be a problem if I have JAVA9?

@sd1998 did you check with java8?

**Comment by sd1998** [comment]
@jesmrec Yes I tried but it does not work.

**Comment by jesmrec** [comment]
very weird behaviour... you does not have any previous installation in the device so it should work. Could you check over a new created emulator? Other option is clearing Android Studio cache, not only the project's one (File > Invalidate Caches/Restart) and build again.

Do you have Instant Run enabled?

**Comment by jesmrec** [comment]
@sd1998  did you upgrade Android Studio to 3.x?

**Comment by sd1998** [comment]
@jesmrec Yes I have the upgraded version.

**Comment by jesmrec** [comment]
@sd1998 did you check https://github.com/owncloud/android/issues/2060#issuecomment-342481296

**Comment by sd1998** [comment]
@jesmrec Sorry I missed it
I will try out what you suggested.

**Comment by jesmrec** [comment]
@sd1998 did you have time to check? if you need help, don't hesitate...

**Comment by davigonz** [comment]
Hi @sd1998 , I've just noticed the same problem while using a different computer and I have fixed by disabling the Instant Run feature. To do that, go into File > Settings > Build, Execution, Deployment > Instant Run and disable it.

**Comment by sd1998** [comment]
@davigonz Thanks I will try it now

**Comment by sd1998** [comment]
@davigonz It is working now thanks for the help Now I will work on #2060

**Comment by davigonz** [comment]
> It is working now thanks for the help Now I will work on #2060

@sd1998 Awesome! I will close this, since it's already fixed.

**Comment by jesmrec** [comment]
did you check https://github.com/owncloud/android/blob/master/SETUP.md#2-working-with-android-studio @prabhashibuddhima ?

**Comment by nidasajjad** [comment]
I have the issue when I install tha app on my android phone. It install but it closed imdedgtely, without showing any error. Can anyone help me.
Thanks

**Comment by jesmrec** [comment]
@nidasajjad which server version and app version? how do you install the app?

**Comment by nidasajjad** [comment]
@jesmrec the server version and app version is same and that is 29. And I install app by both method. Build apk and directly install to android mobile but it shows same error
