### ISSUE TITLE
still cannot login

### ISSUE THREAD

**Issue by unalignedcoder** [owncloud/android#2068]
### Actual behaviour
-Cannot login with app. After testing the connection and entering credentials, I am taken back to the login screen.

### Environment data
Android version: 4.3
Device model: Samsung Note 3
ownCloud app version: ownCloud beta 2.5.1-beta-1
ownCloud server version: latest, cannot check now
I don't have the logs, anyway this behavior is repeated both with the ownCloud server they set up at work and with my personal one. 
Notice that in both instances Solid Explorer can login and access the files without a problem, though it doesn't have a sync function. 
The Windows client also works without a problem on both servers.

p.s. I'm using the beta version because it seems that you have to pay for the regular one... I don't want to pay only because this app never really worked for me, every time I go back to it to check, I just cannot login. Although in a previous version it would crash on the attempt, so that's somewhat of an improvement.

**Comment by davigonz** [comment]
Hi @unalignedcoder , thank you for your feedback, are you able to see the list of files? Does any error message appear when you are redirected to login view?

**Comment by unalignedcoder** [comment]
No, no list of files. The login screen disappears and reappears a split second later. No error messages.

**Comment by jesmrec** [comment]
Not reproducible with Android 4.3 and 10.0.4 in server with 2.5.1-beta1

**Comment by investigatronica** [comment]
Same issue here.
Android version: 7.1.2
Device model: Xiaomi Mi A1
ownCloud app version: ownCloud 2.5.0 and ownCloud beta 2.5.1-beta-1 and nextcloud 2.0.1 and nextcloud  dev 20171212
ownCloud server version: 10.0.4-1.1 on ubuntu desktop 16.04

**Comment by jesmrec** [comment]
This bug seems to be the same reported in https://github.com/owncloud/android/issues/2030

If not, please reopen. All info you find helpful, report in https://github.com/owncloud/android/issues/2030

Thanks all.

**Comment by unalignedcoder** [comment]
NOT the same bug. My username is "admin". No spaces. When I get redirected to the login screen, the fields are empty and editable.
