### ISSUE TITLE
Resume upload after reconnecting to network

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#2069]
### Steps

1. Prepare a huge video file
2. Upload video file
3. Disconnect wifi
4. Wait for error
5. Reconnect wifi
6. Wait

### Expected
Video file uploaded again

### Actual
Video file not uploaded

### Versions
Android 5.1.1
ownCloud Android App 2.5.0

Note that if I have a series of small files it seems to resume the upload list.
Maybe it does continune with the next item but does not resume failed ones ?

@davigonz

**Comment by theScrabi** [comment]
The problem is that we use an old endpoint for junk uploading. Since there are more issues related to this old junk upload such as https://github.com/owncloud/android/issues/2127, we may want to consider upgrading to the new endpoint.

**Comment by PVince81** [comment]
It works now with 2.7.0. It will reupload the full file automatically after wifi is back.

Next up is to have it resume on chunk level: https://github.com/owncloud/android/issues/2070
