### ISSUE TITLE
Include new dialog to encourage users to add a new app review in PlayStore

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2071]
It would be great to increase the number of app reviews in Play Store so that we can receive more feedback from our users.

The idea is to create a new dialog that would appear from time to time (we will think about the exact frequency), asking the users for a new review and redirect them to the PlayStore.

Mockup:

![rate_dialog](https://user-images.githubusercontent.com/15261363/33764566-2db0c1d0-dc15-11e7-9a40-820ee074fcd6.png)

**Comment by davigonz** [comment]
Rate dialog mockup: 
![rate_dialog](https://user-images.githubusercontent.com/15261363/33764566-2db0c1d0-dc15-11e7-9a40-820ee074fcd6.png)

**Comment by harshitbansal05** [comment]
@davigonz can i work on this issue?

**Comment by harshitbansal05** [comment]
@davigonz should I use a library for this purpose(there are some present)? Also, the design should be the same as in the screenshot?

**Comment by harshitbansal05** [comment]
@davigonz @PVince81 do i need to set up a server or is there a demo server url so I can login into app.

**Comment by michaelstingl** [comment]
https://demo.owncloud.org/
user: demo
pw: demo:

**Comment by davigonz** [comment]
> should I use a library for this purpose(there are some present)? Also, the design should be the same as in the screenshot?

Hi @harshitbansal05 , you don't need a new library, dialog fragments can be used for that purpose, we already have many of them implemented in our code, see [this](https://github.com/owncloud/android/tree/master/src/com/owncloud/android/ui/dialog). 

If you need more information. here you have the official documentation about Android dialogs: https://developer.android.com/guide/topics/ui/dialogs.html?hl=en

**Comment by davigonz** [comment]
@harshitbansal05 

> Also, the design should be the same as in the screenshot?

That was a initial mockup but you can propose a new one if you want.

> do i need to set up a server or is there a demo server url so I can login into app.

You can use our demo site: https://demo.owncloud.org/login with the next credentials: 

- admin/admin
- test/test

**Comment by jesmrec** [comment]
Ready to be released in 2.7.0

**Comment by michaelstingl** [comment]
Related blog post:
https://owncloud.org/news/owncloud-app-in-review-heaven/
