### ISSUE TITLE
Activity screen: same info displayed twice

### ISSUE THREAD

**Issue by ldmpub** [owncloud/android#2072]
Hi,

See screen shot => the layout can be optimized without repeating twice the timestamp ...
![same info displayed twice](https://user-images.githubusercontent.com/1452146/33803680-768274ae-dd95-11e7-8cfc-79e001a12c02.png)

**Comment by davigonz** [comment]
Hi @ldmpub , thank you for reporting this problem but I think that it should be opened in a different repository since it has nothing to do with our app. Sorry for the inconvenience but I will close this issue.

**Comment by ldmpub** [comment]
Hi,

@davigonz , does it mean I need to report this to the "server team"? because obviously this layout may come 50% from the server side (which provides datas) and 50% from the Android client side (which displays these datas in "Activities" screen).

Thanks for your answer,

**Comment by AndyScherzinger** [comment]
@ldmpub what @davigonz means is that you need to report it to the Nextcloud Android client issue tracker, not ownCloud.

**Comment by ldmpub** [comment]
OK sorry, I made a mistake,
I have understood that desktop client is here (because Nextcloud currently only rebrands the client) but it was not clear regarding the Android client ... now it is => there are 2 differents Android clients.

Sorry again for the annoyance.
