### ISSUE TITLE
Update PlayStore video

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2073]
The video we currently have in PlayStore is pretty old, we should update it with the latest features included in our app, so that users know how to use some of them, such as multiaccount, new side menu with avatar, available offline, multiple share links, video streaming and so on...

Keeping this video during long time might give the feeling that the app is no longer maintained

Current video:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/0lfnjhYy9uY/0.jpg)](https://www.youtube.com/watch?v=0lfnjhYy9uY)

**Comment by abelgardep** [comment]
The video was removed from google play. We will add an updated one when the redesign is completed.
