### ISSUE TITLE
Feature Request - Pattern Lock

### ISSUE THREAD

**Issue by sd1998** [owncloud/android#2077]
Similar to Passcode Lock there should be another option to provide the user to setup a Pattern Lock.

### Steps to reproduce
1. Open the App
2. Open the Navigation Drawer and select settings

**Comment by jesmrec** [comment]
Any suggestion about pattern locks?

**Comment by sd1998** [comment]
@jesmrec [This dependency can be used](https://github.com/aritraroy/PatternLockView)

**Comment by jesmrec** [comment]
Thanks for contributing @sd1998 !! i have check a bit this feature and i suggest a couple of improvements:

- The section "Details" of the settings view should be renamed to "Security"
- The word "Lock" is uppercase in Pattern and lowercase in Passcode
- Pattern Lock can only be set if the passcode if not set. But if both are enabled, the pattern lock can not be disabled. Which priorities did you set for both security methods? 

CC @davigonz

**Comment by jesmrec** [comment]
This will be included en 2.7.0
