### ISSUE TITLE
share feature does not recognise server version

### ISSUE THREAD

**Issue by kerlerm** [owncloud/android#2078]
App version 2.5.0 does not recognise the 10.x server version. Server is 10.0.3 while app says "min. 8.2 version has to installed on server to share".

Therefore no _additional_ sharing is possible. 
Usernames which were added to the share list earlier are listed and can be deleted. Creating a share link works, too. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Not possible to test because there are no other local users on this test installation to share with.

### Environment data
Android version: 13.0

Device model: maguro

Stock or customized system: lineageos

ownCloud app version: 2.5.0

ownCloud server version: 10.0.3

**Comment by michaelstingl** [comment]
@kerlerm use admin:admin and create more users: https://demo.owncloud.org/settings/users

**Comment by kerlerm** [comment]
*banging my head*
I created several users and it works on demo.owncloud.org

What could cause the app to misinterpret my server version string? Or how can I check which version string is sent by my server manually?

**Comment by michaelstingl** [comment]
@kerlerm What does your `status.php` says? (https://demo.owncloud.org/status.php)

Anything suspicious in your `config/config.php`? Here you can find all parameters: https://doc.owncloud.org/server/latest/admin_manual/configuration/server/config_sample_php_parameters.html

**Comment by kerlerm** [comment]
config.php:
`'version' => '10.0.3.3',`

status.php:
`
version: "10.0.3.3"
`
`
versionstring: "10.0.3"
`

The version strings were never manipulated - only regular updates happened (8.x->9.x->10.x).

**Comment by davigonz** [comment]
@kerlerm could you provide us a test account to reproduce the problem? If so, please send it to [apps@owncloud.com ](url) , thanks

**Comment by kerlerm** [comment]
Done. Please check your mails.

**Comment by davigonz** [comment]
> Done. Please check your mails.

@kerlerm sure! thank you

**Comment by kerlerm** [comment]
Any news on this? May I close the provided test account?

**Comment by kerlerm** [comment]
Test account closed. Comment here if you need access again.

**Comment by kerlerm** [comment]
Problem persists with latest app version 2.7.0 and OC 10.0.7

**Comment by jesmrec** [comment]
yes please. If you can open the test account we will check asap

**Comment by jesmrec** [comment]
your server is

`{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.6.1","versionstring":"10.0.6","edition":"Community","productname":"ownCloud"}`

and the problem is the lack of `versioning` capability, that makes crash the capabilities retrieval and set the rest of capabilities with defaults, in case of sharing, with the oldest version supported (8.1).

Your server returns:

```
"files": {' 
                    "bigfilechunking": true, 
                    "blacklisted_files": [
                        ".htaccess"
                    ], 
                    "privateLinks": true, 
                    "undelete": true
                }, 
```


and out testing environment with the same version as yours:

```
"files": {
                    "bigfilechunking": true, 
                    "blacklisted_files": [
                        ".htaccess"
                    ], 
                    "privateLinks": true, 
                    "undelete": true, 
                    "versioning": true
                }, 
```

i have checked such capability and it is present in earlier 10.x versions and in 9.1 as well. 

as @davigonz suggested, any changes in your server? did you notice any problem during any upgrade?

**Comment by kerlerm** [comment]
No changes and no upgrade problems I'm aware of. I used the normal upgrade path with "productive" versions. 

But I must have missed something. Is this capability tied to some special module? Or module version?

**Comment by kerlerm** [comment]
So this is a server issue on my side. Should I close the bug report?

**Comment by jesmrec** [comment]
yes, the problem is not in Android side. Anyway, you can reopen if it is necessary. 

You can ask in core repo, or in central.owncloud.org

Thanks for reporting.
