### ISSUE TITLE
Can't login with Andoid Beta app

### ISSUE THREAD

**Issue by joaopompeu** [owncloud/android#2079]
### Actual behaviour
When I insert my IP for login in the Android app an error message appears. Something like this: An error occurs when connecting to server. "Ocorreu um erro durante a conexão com o servidor"

### Expected behaviour
After inserting the IP it should open the tabs for username and password
 
### Steps to reproduce
1. insert my IP to the specific box in the app and see the error
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

I can login with this server

### Environment data
Android version: 4.4.2

Device model: S4

Stock or customized system:

ownCloud app version: beta

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hi @joaopompeu , is your server working properly? Have you tried it out from the browser?
