### ISSUE TITLE
Display file size during upload

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#2080]
### Steps

1. Select multiple files for upload
1. Go to uploads section

### Expected
File sizes displayed for all files

### Actual
size only displayed for files not currently uploading. For any file currently uploading or waiting for upload, the size is hidden. Why ?

My use case is that I'm uploading on a slow network and would like to be able to estimate how long I need to wait until I can stop forcing the phone to leave WiFi on by using the phone (because wifi auto disconnects and resuming loses progress, there's another ticket for that).

Even better would be to show how much was already uploaded vs bytes total. I believe the desktop client does that. Optional is a speed measurement.

### Version
2.5.0

**Comment by PVince81** [comment]
#2070 is the one about resuming

**Comment by harshitbansal05** [comment]
@davigonz may I work on this?

**Comment by davigonz** [comment]
HI @harshitbansal05 , I would start with this issue or with #2071 , since #2070 might be a bit difficult as starting point.

**Comment by harshitbansal05** [comment]
Thanks for the response @davigonz, i would start working on those two issues..

**Comment by jesmrec** [comment]
It will release within 2.7.0.
