### ISSUE TITLE
Confusing download buttons when mixed

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#2081]
### Steps

1. Enter folder with multiple files where **none** of the files were ever synced
2. Touch and hold on each file to select them
3. Find the option for "available offline" in the top bar

### Expected result
Easy to distinguish icons with no ambiguity

### Actual result
There are two icons there: an arrow down and another arrow down with an underline. I suspect that many people would not know which one to pick.

Maybe find a better icon for available offline.

### Version
2.5.0

**Comment by davigonz** [comment]
Hi @PVince81 , thank you for your feedback, the iOS app is going to update some icons in coming versions and it will use a new icon for available offline feature (see below). We can try to use a similar one in the Android app and avoid the confusion with download icon. 

![screen shot 2017-12-28 at 12 00 31](https://user-images.githubusercontent.com/15261363/34408888-c357bebc-ebc6-11e7-92b6-fd995709909c.png)

iOS new design issue (if you want to have a look at it for more details): https://github.com/owncloud/ios/issues/927

**Comment by davigonz** [comment]
This is fixed in https://github.com/owncloud/android/pull/2152 and it will be included in 2.8.0, please follow up https://github.com/owncloud/android/issues/2145
