### ISSUE TITLE
[UI] Hide loading bar gap when no syncing action is being performed

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2089]
### Actual behaviour
- When the user scrolls down in the list of files, the loading bar gap appears always.  

<img src="https://user-images.githubusercontent.com/15261363/34787839-fe837f36-f638-11e7-9bf5-d008db248d90.png" width="60%">.

### Expected behaviour
- Loading bar disappears if the user is not syncing the files and show a color gradiant instead. 
 
### Steps to reproduce
1. Have a list of files that don't fit completely in the screen. 
2. Scroll down.
3. Have a look at the bottom of the list, just below the top bar. 

### Environment data
Android version: 6.0

Device model: Nexus 5

Stock or customized system: Stock

ownCloud app version: 2.5.0

ownCloud server version: it doesn't matter.

**Comment by sd1998** [comment]
@davigonz I would like to work on this.

**Comment by davigonz** [comment]
> I would like to work on this

@sd1998 Great! If you need some pointers, ping me

**Comment by sd1998** [comment]
@davigonz what do you mean by color gradiant here?

**Comment by davigonz** [comment]
> what do you mean by color gradiant here?

@sd1998 Something like this

![test](https://user-images.githubusercontent.com/15261363/36088677-7d09e6e8-0fd8-11e8-96cd-5f52b331637c.png)
