### ISSUE TITLE
Include new wizard to guide the user through the app features

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2090]
It would be great to include a wizard with several steps to explain to the user not only the app main features but the new features we are including in the app. 

In a first phase, this wizard could appear the first time the app is installed and later, we can show it with new features added in every app update, if any. 

Have a look at the next gif got from [this project](https://github.com/matrixxun/ProductTour) that includes a wizard example we can use:

![run3](https://user-images.githubusercontent.com/15261363/34817675-dc77059a-f6b8-11e7-896f-5b000291c7d4.gif)

**Comment by mario** [comment]
Yay for inspirations!

**Comment by davigonz** [comment]
> Yay for inspirations!

Sorry @mario but if you think I need some kind of inspiration in your code or characteristics to implement a feature that a great bunch of apps already include, you are wrong. 

My task here is to improve this app as far as I can and make it work fine so that our users are happy. Sincerely, I prefer to invest my time in that instead of paying attention to your code or features to find something interesting.

**Comment by mario** [comment]
This would be so sweet if it wasn't an obvious lie :)

**Comment by jesmrec** [comment]
The welcome wizard is a feature that the ownCloud iOS app included from many years ago. It is not anything new for the ownCloud mobile team.

**Comment by nasli** [comment]
Closed as duplicated of https://github.com/owncloud/android/issues/1104, this was already in our backlog for a long time. 
Please add more details you consider and keep up to date in the other issue, thank you

**Comment by AndyScherzinger** [comment]
Well, the funny part is rather that there is #1375 since Dec 21, 2015 ;)

**Comment by davigonz** [comment]
> Well, the funny part is rather that there is #1375 since Dec 21, 2015 ;)

@AndyScherzinger Thank you for pointing us to that PR, I will try to revive it then... 😄
