### ISSUE TITLE
OwnCloud-Android setup throws Error

### ISSUE THREAD

**Issue by codedsun** [owncloud/android#2100]
### Actual behaviour
Cloning the repo and opening in Android studio, it throws error

### Expected behaviour
It should work fine
 
### Steps to reproduce
1. Cloned the repo
2. Gradle sync starts and then error is shown
 

## Logs:
Error:Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :owncloud-android-library.

**Comment by codedsun** [comment]
I missed that little part :( was stucked in this problem since 2 days, skimmed over the setup more than every time I opened the project.Thanks a lot!

**Comment by codedsun** [comment]
@davigonz I am facing this issue again, while opening the project in Android studio.
Gradle build fails and throws

`Error:Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

Consult IDE log for more details (Help | Show Log)`

at line 
`    variant.outputs[0].outputFile = new File(originalFile.parent, newName)` of file build.gradle app level

**Comment by codedsun** [comment]
@davigonz 
I was facing with this issue multiple time, 
`Failed to finalize session : INSTALL_FAILED_INVALID_APK: /data/app/vmdl2030466577.tmp/11_android-_______-debug version code 20600000 inconsistent with 0`

For Android studio 3.0. Can it be added to the documentation?, if needed.

**Comment by davigonz** [comment]
@codedsun Have you managed to fix this finally?

**Comment by codedsun** [comment]
@davigonz Yes, the instant run has to be disabled for running this app. I think it might help for future devs hence can be included in the documentation.

These days I am setting up the owncloud-server to get started with android project, is there any way I can get help for setting up the server and is there any demo (dev) owncloud server link to go through the app>?

**Comment by davigonz** [comment]
> These days I am setting up the owncloud-server to get started with android project, is there any way I can get help for setting up the server and is there any demo (dev) owncloud server link to go through the app>?

You can use our demo site: https://demo.owncloud.org/login with the next credentials:

admin/admin
test/test

**Comment by codedsun** [comment]
@davigonz Saved my day! thanks a lot 👍

**Comment by codedsun** [comment]
@davigonz Is there any time limit for the demo server?

**Comment by michaelstingl** [comment]
> @davigonz Is there any time limit for the demo server?

It resets every 1h which causes a little downtime.

**Comment by codedsun** [comment]
@michaelstingl How can i setup on my own pc? I read through the guide but I am stuck :(

**Comment by michaelstingl** [comment]
I prefer Docker (requires installation of [Docker](https://docs.docker.com/install/) and (maybe) [docker-compose](https://docs.docker.com/compose/install/)):

```
$ mkdir mylocalowncloud
$ cd mylocalowncloud
$ git clone https://github.com/owncloud-docker/server.git
$ cd server
$ docker-compose up -d
```

==> http://localhost/

With `docker-compose down` you shut it down.

**Comment by codedsun** [comment]
@michaelstingl  I am facing some issues when I type docker-compose up -d.
It gives me some error of Compose file and says that unsupported config option for services.db, services.owncloud.

**Comment by davigonz** [comment]
@codedsun You can also use something like this, without using docker-compose:

1. Execute `docker run -d -p 11181:80 owncloud:latest` (You can use 11181 or other one, up to you)
This command will download the latest owncloud image, create a docker container and start it automatically. Besides, it will export the 80 port from docker container to your 11181 port. 
2. Open a browser and write localhost:11181, and there it will be your ownCloud running in your computer.

**Comment by codedsun** [comment]
@davigonz That above method works, now for the app how can I use this address

**Comment by davigonz** [comment]
> That above method works, now for the app how can I use this address to login ?
> How can I use this address(local) for android app?

You need to know your local IP by typing `ifconfig` in a terminal if your OS is linux based. Once you have your local IP, open a browser and type `IP_ADDRESS:11181`

**Comment by codedsun** [comment]
and is it necessary to have the devices connected to the same network?

**Comment by davigonz** [comment]
> and is it necessary to have the devices connected to the same network?

No, there's options like port forwarding to access from a different network, but I would recommend you to work in the same network.

**Comment by codedsun** [comment]
Thankyou so much for the help.Will try as soon as I reach my home.And for
today the list of organizations are to be declared.Hoping the best and will
contact you further for android project ideas.


Thankyou.
