### ISSUE TITLE
file deletion snackbar hiding the fab

### ISSUE THREAD

**Issue by harshitbansal05** [owncloud/android#2104]
### Actual behaviour
When a single item is deleted, the ***removed successful*** snackbar partially hides the floating action button.

### Expected behaviour
The floating action button should actually move up when the snackbar is shown. 
### Steps to reproduce
1. Delete a item from the **File Display Activity**.
2. On deletion, the snackbar hides the fab.

### Environment data
Android version:5.1

Device model: Redmi Note 3

Stock or customized system:Stock

ownCloud app version:2.5.1-beta.1

**Comment by harshitbansal05** [comment]
@davigonz can you please look into this?

**Comment by jesmrec** [comment]
it will be released in 2.8.0

**Comment by davigonz** [comment]
Not merged yet, see #2203
