### ISSUE TITLE
Feature-Request - "Select All" button in launcher activity.

### ISSUE THREAD

**Issue by harshitbansal05** [owncloud/android#2106]
### Actual behaviour
There is no **Select All** feature in the main activity. 
### Expected behaviour
There should be a such option to select all items in one go. It can be done by adding a **Select All** button in menu of File Display Activity.

**Comment by davigonz** [comment]
Hi @harshitbansal05 , thank you for requesting this feature but we already have an issue about it, so I will close this since is duplicated and you can follow up https://github.com/owncloud/android/issues/1727
