### ISSUE TITLE
The source can't complied successfully.

### ISSUE THREAD

**Issue by tigerjiang** [owncloud/android#2107]
### Actual behaviour
-Tell us what happens
I execute the command in terminal " ./gradlew clean build" in the source root path.
The error occur!

See the below log
tiger@:android-1$ ./gradlew clean build
File /home/tiger/.android/repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android-1'.
> Could not resolve all dependencies for configuration ':_debugApk'.
   > A problem occurred configuring project ':touchImageView'.
      > Could not resolve all dependencies for configuration ':touchImageView:_debugPublishCopy'.
         > Could not resolve com.android.support:support-v4:26.1.0.
           Required by:
               project :touchImageView
            > Could not resolve com.android.support:support-v4:26.1.0.
               > Could not get resource 'https://maven.google.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.pom'.
                  > Could not GET 'https://maven.google.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.pom'.
                     > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by tigerjiang** [comment]
And I can't understand the settings.gradle config.
`include ':owncloud-android-library'
include ':'`
I havn't find the project owncloud-android-library .

**Comment by tigerjiang** [comment]
Sorry to my wrong environment config

**Comment by davigonz** [comment]
@tigerjiang No problem, glad to see you've fixed the issue 👍
