### ISSUE TITLE
Migrate to Gradle 3.1.2 and add Java 8 support

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2109]
We are currently using Android plugin for Gradle 2.3.3, but there is a newer Android plugin for Gradle with version 3.1.2 that could be used along with 4.4 gradle distribution.

Following [Migrate to Android Plugin for Gradle 3.0.0](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#manifestOutputFile) and [Use Java 8 Language Features](https://developer.android.com/studio/write/java8-support.html)

Some errors:
- [x] `Cannot set the value of read-only property 'outputFile'` -> Use `outputFileName`
- [x] `InstrumentTest deprecated` -> Use `androidTest`
- [x] `Error:(161, 5) error: invalid parent reference 'style/Widget.AppCompat.ButtonBar.AlertDialog'.` -> Use `@style` instead of `style`
- [x] `Could not find com.android.tools.lint:lint-gradle Android Studio 3`-> Include `google()` repository
- [x] Some styles not found -> remove @ before android
- [x] app_name / other setup.xml variable is not translated -> `disable 'MissingTranslation'`

Some warnings:
- [x] `Warning:Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
- [x] `Warning:Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.`
- [x] `Warning:The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.2.` -> remove "buildToolsVersion '26.0.0'" from your build.gradle file, as **each version of the Android Gradle Plugin now has a default version of the build tools.**

**Comment by jindalAnuj** [comment]
@davigonz i want to work on this

**Comment by hannesa2** [comment]
Here it's already included https://github.com/owncloud/android/pull/2076 and ready to merge

**Comment by jindalAnuj** [comment]
@hannesa2 it's ok  👍

**Comment by davigonz** [comment]
Resuming the work here...

**Comment by theScrabi** [comment]
@davigonz you could try to add java 8 support while you upgrade gradle:
https://developer.android.com/studio/write/java8-support.html

**Comment by davigonz** [comment]
> you could try to add java 8 support while you upgrade gradle:
https://developer.android.com/studio/write/java8-support.html

Yes, done and rewritten the PR issue name
