### ISSUE TITLE
Soft keyboard not hiding on going back from select user/group activity

### ISSUE THREAD

**Issue by harshitbansal05** [owncloud/android#2111]
### Actual behaviour
In Share activity, if no user or group is selected, after pressing the back navigation, the soft keyboard still persists. 

### Expected behaviour
The soft keyboard should hide after the user/group selection activity is closed.
 
### Steps to reproduce
1. Long tap on a file and click the share icon.
2. Click on add a user or group.
3. Go back pressing the back navigation.

Can this problem be reproduced with the official owncloud server?
Yes

### Environment data
Android version: 5.1.1

Device model: Redmi Note 3 API Level: 22

Stock or customized system: Stock

ownCloud app version: 2.5.1-beta.1

**Comment by jesmrec** [comment]
Thanks for reporting!!!

**Comment by jesmrec** [comment]
@harshitbansal05 yes, you can. thanks!!!

**Comment by davigonz** [comment]
Hi @harshitbansal05 , I am not able to reproduce this problem, when I press the back navigation button or even the Android back button, the soft keyboard always disappear, am I missing something? Thanks

![mar-06-2018 17-58-36](https://user-images.githubusercontent.com/15261363/37046208-1348ff04-2168-11e8-8341-03537e5285a3.gif)

**Comment by jesmrec** [comment]
@davigonz check it with Android 5. Also reproducible with Android 4.

**Comment by davigonz** [comment]
> check it with Android 5. Also reproducible with Android 4.

I see, thanks @jesmrec

**Comment by jesmrec** [comment]
Fixed and ready to 2.7.0
