### ISSUE TITLE
No password visibility toggle feature in Create link share dialog

### ISSUE THREAD

**Issue by harshitbansal05** [owncloud/android#2112]
### Actual behaviour
There is no password toggle feature in **Create Link Share** dialog.
### Expected behaviour
A password toggle feature should be added to the  dialog.
 
### Steps to reproduce
1. Long tap on a file and click share icon.
2. Click on create a link option.

Can this problem be reproduced with the official owncloud server?
Yes

### Environment data
Android version: 5.1.1

Device model: Redmi Note 3

Stock or customized system: Stock

ownCloud app version: 2.5.1-beta.1

**Comment by jesmrec** [comment]
do you mean  the password to protect the public link? i can not reproduce with version 2.6.0

![screen shot 2018-02-07 at 08 29 10](https://user-images.githubusercontent.com/14894746/35903814-04c918e8-0be1-11e8-94e1-58e01792bf0b.png)

**Comment by harshitbansal05** [comment]
After we switch on the password feature, while entering the password, there is no option to toggle visibility of the password.

**Comment by jesmrec** [comment]
do you mean to set the password as visible (not hidden behind asterisks), like the password in login view?

**Comment by jesmrec** [comment]
yep, i meant that. The eye icon, for example?

**Comment by harshitbansal05** [comment]
Yes, should it be implemented?

**Comment by harshitbansal05** [comment]
@jesmrec i would start working on it...
