### ISSUE TITLE
As an user, I would like to create a new text file or edit an existing one and upload it directly to my ownCloud

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2118]
The Android app has already an option to create a folder, but it would be great to have a new one to create a new text file with some content or edit an existing one and upload it directly to ownCloud. This option is already implemented in iOS app. 

Possible design with the "New text file" floating button:

<img src="https://user-images.githubusercontent.com/15261363/36375093-2f97975c-156e-11e8-9ccf-fa4d82cb1078.png" width="55%">

**Comment by mudit9** [comment]
Hi, I am working on this issue. I would just like to know how the create folder module is working. 
Can you please explain this line of code?
**((ComponentsGetter)getActivity()).getFileOperationsHelper().createFolder(path, false);**
This is in the CreateFolderOperationFragment.java file.
Right now, I have used similar dialogues that are being used to create a folder, to create a new file. I just want to know how is it being uploaded to the database directly. 
Thank you

**Comment by davigonz** [comment]
Hi @mudit9 , glad to see you are working on this. Let's answer your different questions:

> Can you please explain this line of code?
((ComponentsGetter)getActivity()).getFileOperationsHelper().createFolder(path, false);

When executing that line, we are calling `createFolder()` method in FileOperationsHelper which, as its name says, is a class responsible for handling operations related to files, such as opening, renaming, removing files and to folders, which are like files in our code. 

> Right now, I have used similar dialogues that are being used to create a folder, to create a new file. I just want to know how is it being uploaded to the database directly.

createFolder() method [creates an intent](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/helpers/FileOperationsHelper.java#L558) for [OperationsService](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/services/OperationsService.java#L84) with an action to create a new folder and puts it in the OperationService queue. When OperationsService takes a look at its queue and [decides to execute that action](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/services/OperationsService.java#L684), it will call CreateFolderOperation, which in turn will call CreateRemoteFolderOperation - placed in our library - and will create the folder locally if success. 

Looking forward to see a PR with your implementation 😉 

Hope to be helpful, if you have any other question, ping me.

**Comment by davigonz** [comment]
Moving the discussion opened in https://github.com/owncloud/android/issues/2120#issuecomment-366660896 to this issue, which is the proper one.

> I researched a bit about the "create new file" features, and I found out that other apps basically create an empty file, and than call another app to handle that file.

@theScrabi yes, this is what other apps do and we could do the same with the ownCloud Android app as well.

> However for this to implement we'd have to put empty office files into our app assets.
Also if we want to support MSO i would love to also be able to support odf files.

I do not understand exactly what you mean with using the assets folder, saving the empty files in the ownCloud folder would be enough, wouldn't it? 

> Better MSO integration for android was also requested by CERN.
> Empty *.docx files are probably not what was requested from them.
> The alternative would be the approach we discussed in owncloud/enterprise#1948 (private repo, maybe open new issue in public repo)

Agree with @michaelstingl , I think that's a different use case to the one described in this topic since it talks about opening and saving a doc file from the MSO app while this is about creating and empty file and open it from the ownCloud Android app by using an external app.

**Comment by theScrabi** [comment]
> I do not understand exactly what you mean with using the assets folder, saving the empty files in the ownCloud folder would be enough, wouldn't it?

Yes but those empty files needed to build into our app. I meant the android project assets folder which is part of its resources.

**Comment by michaelstingl** [comment]
@davigonz @jesmrec New iOS app doesn't have a feature to create or edit text files inside the app. We always had encoding problems. I'd rather prefer to improve the document provider features for frictionless editing with 3rd party "real" text editors..

**Comment by jesmrec** [comment]
Documents provider + sharing text file cover completely these needs

**Comment by hman2** [comment]
It's another tap required. For each note! It'd call this unnecessary complicated. And: It's a different behaviour compared to the Web representation, where you can simply click on a note in the folder's listing - and you can directly edit the text in there. Other issue: To my knowledge there is no standalone notes app for Android and Owncloud. Nextcloud has one directly from the manufacturer, Owncloud not. There is a plugin for handlings Notes server-side, but no app for smartphones.

Most links point to MyOwnNotes, which I have used previously, but MyOwnNotes says that it uses the OwnCloud client to access the cloud, but it won't do that since we have 2FA here. Before that it worked. So currently there is no standalone app...
