### ISSUE TITLE
FR: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/android#2121]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by theScrabi** [comment]
This is also useful because on android 8+ the icon does not blend in well.
![screenshot_1523272529](https://user-images.githubusercontent.com/1891273/38495040-6f9f3d04-3bf8-11e8-8544-79277413af1e.png)
