### ISSUE TITLE
[2.6.0] Automatically uploads settings are removed after the upgrade.

### ISSUE THREAD

**Issue by cdamken** [owncloud/android#2130]
I upgraded from 2.5.0 to 2.6.0  and I had activated automatically upload pictures and video.

after the upgrade (over Playstore) the settings are removed and I have to add it manually again.

Tested with branded app (damken-cloud)

@michaelstingl @davigonz

**Comment by davigonz** [comment]
Thanks @cdamken , we replaced the "Instant upload" preference with "Camera uploads" one, so the behaviour you describe is what we expect, if you want to use Camera uploads feature you will need to enable the feature to initialize and configure it properly.

I know it wasn't the best solution, we included a note about this topic in central and in PlayStore description. 

If something like this happens again in the feature, we will show a specific message directly in the app with the new wizard, https://github.com/owncloud/android/issues/1104#issuecomment-364125332
