### ISSUE TITLE
OCFileListFragment uses ListView instead of RecyclerView

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2131]
[OCFileListFragment](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/fragment/OCFileListFragment.java), and all the other fragments that derive from [ExtendedListFragment](https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/fragment/ExtendedListFragment.java) are still based on ListView instead of [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html). This may cause issues with huge file lists.

@cdamken Could you test this on a cloud with many files in one folder?

**Comment by jesmrec** [comment]
Related with https://github.com/owncloud/android/pull/1636

**Comment by davigonz** [comment]
This is duplicated of https://github.com/owncloud/android/issues/984, follow up there.
