### ISSUE TITLE
Upload pictures directly from devices camera, uploads the thumbnail of the image.

### ISSUE THREAD

**Issue by sd1998** [owncloud/android#2141]
### Actual behaviour
When using the upload from camera feature the thumbnail of the picture is being uploaded.

### Expected behaviour
The actual picture file should be uploaded instead of the thumbnail.
 
### Steps to reproduce
1. Open the main FAB.
2. Select  Upload FAB
3. Select "Picture from camera" option in the Bottom Sheet

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes

### Environment data
Android version: 8.0.0

Device model:  Oneplus 3T

Stock or customized system:

ownCloud app version: 2.6.0

**Comment by sd1998** [comment]
@davigonz while I working on this feature I did not notice this mistake. But I just saw it when I ws working on #2119. And I have fixed it will be sending a PR in some time.

**Comment by davigonz** [comment]
Great @sd1998, thanks for reporting it, we will include it in the next 2.7 release
