### ISSUE TITLE
Camera Upload (2.6.0) does not work on Android 5.1.1

### ISSUE THREAD

**Issue by moscicki** [owncloud/android#2146]
### Actual behaviour

After updating from 2.2 to 2.6 CERNBox branded Android App (Alpha testing channel) the photo upload functionality got broken for me on Android version 5.1.1

However, I have a report from another tester that Camera Upload works for them on Android version 8.0.0.

### Expected behaviour

I expect the photo to be uploaded. I also expect to see it in the "Uploads" list. 

Related: I read that you are polling every 15 minutes - is there a way of uploading a selected photo faster? Very often you want to share or use it from the server immediately.

**Comment by jesmrec** [comment]
Currently, the Android system is cutting off background services, so we do not have another option to upload automatically pics directly from the camera. I will check with Android 5 again in any case if the is any weird behaviour. 

To upload automatically faster, we will release in next version the feature `upload from camera` to take a pic from the app.

**Comment by moscicki** [comment]
@jesmrec: ok, but 2.2.0 was working fine. why? it looks like a 2.6.0 regression to me.

**Comment by jesmrec** [comment]
2.2.0 implemented instant uploads, different from camera uploads

**Comment by jesmrec** [comment]
with 2.6.0 is not reproducible in my side with Android 5, pics are being uploaded. Which device/model are you using?

**Comment by moscicki** [comment]
It's 5.1.1 Samsung SM-G388F

**Comment by michaelstingl** [comment]
@moscicki could you check with [2.7.0 beta version](https://central.owncloud.org/t/owncloud-android-2-7-0-beta-app-released/12528) or 2.6.0 *-debug.apk from ownBrander? There you can get logs from the settings screen.

**Comment by jesmrec** [comment]
5.1.1 with  Nexus device works fine... maybe an issue related with Samsung devices.

**Comment by constrictor** [comment]
Camera uploads don't work at all for me with Samsung Galaxy S9+ using Android 8.0.0. The same on both latest stable and 2.8.0-beta.1.

**Comment by michaelstingl** [comment]
@constrictor with the 2.8.0-beta1, you can capture logs on the settings screen. You could send them to apps@owncloud.com .

**Comment by jesmrec** [comment]
Not active from a long time. Feel free to reopen or create new issue if the problem persists
