### ISSUE TITLE
FR: Upload Speed Limit

### ISSUE THREAD

**Issue by lefherz** [owncloud/android#2148]
A user review on GooglePlayStore requested a feature:

"Great app. Just missing upload speed limit, every time I make a video it kills my internet for several minutes."

Could this be implemented into the app?

**Comment by jesmrec** [comment]
Not sure if it is worthy. We can not lose the focus in the app main features (storage and sync are the priorities), and the speed should not be something to be controlled in this kind of app. All feedback is welcome in any case.

**Comment by michaelstingl** [comment]
A quick Google search brought up various 3rd party apps for bandwidth control and traffic shaping. Did you tried these? Why should this be implemented in the oC app?

**Comment by lefherz** [comment]
It's implemented in the desktop client, so... I recommended such an app to him, though :)

**Comment by jesmrec** [comment]
Not intended in our roadmap ftm. oC app to share and store files, bandwidth should be handled externally. Feel free to reopen if new ideas come.
