### ISSUE TITLE
App crashes when trying to access settings

### ISSUE THREAD

**Issue by billie80** [owncloud/android#2159]
# Actual behaviour

After the update to 2.7.0-beta.1 the App crashes when trying to access settings. The App closes and a popup window appears stating "Owncloud stopped"

# Expected behaviour

Settings should be accessible.

# Steps to reproduce

1. Open the app
2. Go to settings
3. App stops

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
N/A

# Environment data

Android version: 6.0.1

Device model: Samsung Galaxy S5 mini

ownCloud app version: 2.7.0-beta.1

**Comment by jesmrec** [comment]
Thanks for reporting, we will check and let you know.

**Comment by michaelstingl** [comment]
Couldn't reproduce with 2.7.0-beta.1 from Play Store Beta running with Android 8.1 on my Pixel 2

**Comment by billie80** [comment]
F-Droid version here. If this makes a difference.

**Comment by jesmrec** [comment]
the store you install the app from should not make any difference. I installed the FDroid 2.7.0-beta1 and i can not reproduce (Android 4.4). Were you be able to perform any setup before you started to receive crashes? reinstalling keep the app crashing?

**Comment by billie80** [comment]
Up to now I only wiped all App data without deleting the accounts I have set up with a previous version.
I will delete the accounts and reinstall the App. Will report back here!

**Comment by billie80** [comment]
Okay I did remove all accounts, uninstalled and reinstalled Owncloud-2.70-beta.1. I had to add an account to be able to access the settings. The result is the same, it still crashes when trying to open the settings.

**Comment by billie80** [comment]
I captured the crash with logcat:

03-24 20:14:14.007 22731 22731 I Timeline: Timeline: Activity_launch_request id:com.owncloud.android time:175139776
03-24 03-24 20:14:14.042 22731 22731 V FileDisplayActivity: onPause() start
03-24 20:14:14.042 22731 22731 D FileDisplayActivity: onPause() ending
03-24 20:14:14.047 22731 22731 V FileDisplayActivity: onPause() end
03-24 03-24 20:14:14.067 22731 22731 W ResourceType: Failure getting entry for 0x01080a8c (t=7 e=2700) (error -75)
03-24 20:14:14.072 22731 22731 D Preferences: onCreate(Bundle) starting
03-24 20:14:14.102 22731 22731 D TextView: setTypeface with style : 0
03-24 20:14:14.102 22731 22731 D TextView: setTypeface with style : 0
03-24 20:14:14.102 22731 22731 W ResourceType: Failure getting entry for 0x01080a8c (t=7 e=2700) (error -75)
03-24 20:14:14.107 22731 22731 W ResourceType: Failure getting entry for 0x01080a8c (t=7 e=2700) (error -75)
03-24 20:14:14.107 22731 22731 D AbsListView: Get MotionRecognitionManager
03-24 20:14:14.107 22731 22731 E MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@2b4f69b
03-24 20:14:14.107 22731 22731 E MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@1126a38
03-24 20:14:14.107 22731 22731 E MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@1126a38
03-24 03-24 20:14:14.122 22731 22731 D TextView: setTypeface with style : 0
03-24 20:14:14.127 22731 22731 D TextView: setTypeface with style : 0
03-24 20:14:14.127 22731 22731 D TextView: setTypeface with style : 0
03-24 20:14:14.132 22731 22731 W ResourceType: Failure getting entry for 0x01080a8c (t=7 e=2700) (error -75)
03-24 20:14:14.132 22731 22731 W ResourceType: Failure getting entry for 0x01080a8c (t=7 e=2700) (error -75)
03-24 20:14:14.132 22731 22731 D AbsListView: Get MotionRecognitionManager
03-24 20:14:14.137 22731 22731 D TextView: setTypeface with style : 0
03-24 20:14:14.137 22731 22731 D TextView: setTypeface with style : 0
03-24 20:14:14.142 22731 22731 D TextView: setTypeface with style : 0
03-24 03-24 20:14:14.167 22731 22731 D Preferences: onStart() starting
03-24 20:14:14.167 22731 22731 D Preferences: onResume() starting
03-24 03-24 20:14:14.172 22731 22731 D AndroidRuntime: Shutting down VM
03-24 20:14:14.172 22731 22731 E AndroidRuntime: FATAL EXCEPTION: main
03-24 20:14:14.172 22731 22731 E AndroidRuntime: Process: com.owncloud.android, PID: 22731
03-24 20:14:14.172 22731 22731 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.owncloud.android/com.owncloud.android.ui.activity.Preferences}: java.lang.SecurityException: Permission Denial: getCurrentUser() from pid=22731, uid=10309 requires android.permission.INTERACT_ACROSS_USERS
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4225)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4327)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7331)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: getCurrentUser() from pid=22731, uid=10309 requires android.permission.INTERACT_ACROSS_USERS
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1621)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1574)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.hardware.fingerprint.IFingerprintService$Stub$Proxy.hasEnrolledFingerprints(IFingerprintService.java:503)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.hardware.fingerprint.FingerprintManager.hasEnrolledFingerprints(FingerprintManager.java:776)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at com.owncloud.android.authentication.FingerprintManager.hasEnrolledFingerprints(FingerprintManager.java:150)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at com.owncloud.android.ui.activity.Preferences.onResume(Preferences.java:623)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1287)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7015)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4214)
03-24 20:14:14.172 22731 22731 E AndroidRuntime: 	... 10 more

**Comment by jesmrec** [comment]
are you using different Google accounts which shares the same ownCloud account?

**Comment by billie80** [comment]
I do not completely understand your question. What do you mean by different Google accounts sharing the same ownClowd account? 
However there is only one Google account for this device.

**Comment by jesmrec** [comment]
@theScrabi could you have a look to the logs?

**Comment by jesmrec** [comment]
I have reproduce the problem with a Samsung Galaxy Tab S (ST1), with 6.0.1. We will take care to fix the problem for the 2.7.0.

**Comment by billie80** [comment]
Perfect, thanks a lot for your effort!

**Comment by theScrabi** [comment]
Apparently there are some android 6 devices where the vendor of the device locked down finger print support for all applications. Only some apps that are signed from the vendor can access the finger print sensor. I had to deactivate fingerprint for these devices.

@billie80 I'm sorry about that. My personal advice: Try device modding with [LineageOS](https://lineageos.org/), because Samsung firmware is ... meh.

**Comment by theScrabi** [comment]
Aparently there are some android 6 devices where fingerprint access is locked down for common apps. Only vendor signed apps can access the fingerprint sensor. This however caused the crash for these devices. By deactivating fingerprint for these made settings available again.

**Comment by billie80** [comment]
Well, LineageOS has its own problems which, at the moment, would affect me more than missing fingerprint authentication when using the stock rom.
Thanks for taking care of this issue!
