### ISSUE TITLE
icon/logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [owncloud/android#2163]
Hi @owncloud , I am a designer and I have an icon/logo design proposal to contribute. If you like and will use it, I am happy to give it to you as a gift.. :) 
![idea](https://user-images.githubusercontent.com/36028424/37905558-d420267a-3131-11e8-8860-e47ae54c5e5e.png)

orig color
![orig color owncloud-02](https://user-images.githubusercontent.com/36028424/37905741-68b437a4-3132-11e8-86a0-a9a37235bac6.png)
![orig color owncloud-01](https://user-images.githubusercontent.com/36028424/37905748-6be808f6-3132-11e8-847a-f416e719744f.png)

b&w
![icon-02](https://user-images.githubusercontent.com/36028424/37905539-c703ae1c-3131-11e8-9b6e-3302c5c82f17.png)
![icon-01](https://user-images.githubusercontent.com/36028424/37905547-cf0bf89e-3131-11e8-9d5b-c6c28f349691.png)

simplier
![owncloud 5 6-03](https://user-images.githubusercontent.com/36028424/37906226-f08421b6-3133-11e8-9e86-94b56916bb30.png)
![owncloud 5 6-04](https://user-images.githubusercontent.com/36028424/37906230-f4556804-3133-11e8-80f4-0540b609aaca.png)

Best regards,

Tobaloidee

**Comment by theScrabi** [comment]
:D @Tobaloidee nice work, but I think a new logo would require a process of reworking our whole cooperate identity, and that would affect the whole owncloud project. I don't think we need to do this right now :D

**Comment by Tobaloidee** [comment]
No problem Sir.. thanks for the feedback..best regards!
