### ISSUE TITLE
Improve file select/upload UI

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2165]
I wan't a clear and consistent UI for file upload so that I don't get confused which button is the import and with is the upload form files button.
@michaelstingl @jesmrec please tell me what you think about that.

This is my suggestion:
![screenshot_1522239691](https://user-images.githubusercontent.com/1891273/38030605-5b3d29ba-3299-11e8-95a7-d74e25fc2ce1.png)
![asdf](https://user-images.githubusercontent.com/1891273/38030609-5e11b17e-3299-11e8-8a19-78547b4b089b.png)

**Comment by michaelstingl** [comment]
Please also add screenshots of existing solution and maybe us Markdown tables for side by side comparison.

**Comment by jesmrec** [comment]
Duplicated from https://github.com/owncloud/android/issues/2120.  Put your thoughts there.

Thanks!
