### ISSUE TITLE
returning form share result in reenter credentials 

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2170]
returning form share result in reenter credentials

@jesmrec pointed out that you had to enter your patterncode/passcode/fingerprint again after returning from sharing data to other apps.

For regular shares I could not reproduce this
![s1](https://user-images.githubusercontent.com/1891273/38246367-d89dbee0-3741-11e8-990f-1105cf939111.gif)

However if I brake up the process of sharing I had to enter the credentials
![s2](https://user-images.githubusercontent.com/1891273/38246406-fa2bc4f8-3741-11e8-9448-4d1c08007881.gif)

**Comment by erfanmoradi** [comment]
vnk

**Comment by jesmrec** [comment]
There is a small "time window" in which the security access is not asked, to avoid being asked in rotations. For that reason, breaking up the process makes the passcode to raise up.

Not a bug, a feature.

For the moment, this specific one is not an issue, unless the global security management in the code is changed somehow.

Feel free to reopen if disagree.
