### ISSUE TITLE
 ownCloud upload failed you do not have permission to upload to this folder

### ISSUE THREAD

**Issue by Calimero33** [owncloud/android#2189]
**Actual behaviour**

Cant upload to the server over Android either manual either auto
(But I can Over Win desktop...)

**Expected behaviour**
Upload on to the connected and logged in server

**Steps to reproduce**
1.Select a photo on the Android Oreo (S8)
2. Select Share and Owncloud
3. upload to the 30-40% after what error message: own cloud upload failed you do not have permission to upload

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
(Cant login)
#
Environment data
#
Android version:
Oreo
Device model:
Samsung S8
Stock or customized system:

ownCloud app version:
2.7.0.
ownCloud server version:
10.0.7

Found one solution here (https://github.com/owncloud/core/issues/11449 ) but dont know how (where to) enter command: ./occ files:scan username

**Comment by Calimero33** [comment]
Just reinstalled all over again (deactivated cphulk and all other server security) and the we go the very same same message near try to upload the file: You dont have permission... (Permission error). Other than that this NEW error came from the ownCloud installation:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/doc/admin/_static/img/note_pencil.svg
		- core/doc/admin/_static/img/warning.svg
		- core/fonts/LICENSE.txt
		- core/vendor/clipboard/dist/clipboard.js
		- core/vendor/jsTimezoneDetect/jstz.js
		- core/vendor/showdown/dist/showdown.js
		- core/vendor/showdown/dist/showdown.min.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/doc/admin/_static/img/note_pencil.svg] => Array
                        (
                            [expected] => 78b9df57afe9468145e6e375cd1f61274b269b9c3019726a99e043ae952367acf53cf471cbc5b3dcca2e68367c2c4422d4a9f9a9fdbb11f9b962845ac77857de
                            [current] => 97117ce2827cc1b742678b52fc100de1e7d3fdb1adeea04a301c012e7f95b66e10a369c6a83ba89a707c4232b5e31fba3d5e58b0e0d970f22031d0704eebb5a9
                        )

                    [core/doc/admin/_static/img/warning.svg] => Array
                        (
                            [expected] => e8647b47ef1531b8c2fcdd51f76996fe85476467fc694540f3dcf8ce7e7da489e99edae5a158742da71c07dc09ccfaf721f01c1c4bda3f5bae9b711981b71a1b
                            [current] => 85687f19cf204716e9b1c608682aa22c045b6f8284a3496db07f13200952491bfea54deee7ef11115c0dedfd87443c7022ef05792892a8a984866752c8ec5726
                        )

                    [core/fonts/LICENSE.txt] => Array
                        (
                            [expected] => 4cc5a12bfe984c0a50bf7943e2d70a948d520ef423677c77629707aace3a95aa378d205de929105d644680679e70ef2449479b360ad44896b75bafed66613272
                            [current] => 98f6b79b778f7b0a15415bd750c3a8a097d650511cb4ec8115188e115c47053fe700f578895c097051c9bc3dfb6197c2b13a15de203273e1a3218884f86e90e8
                        )

                    [core/vendor/clipboard/dist/clipboard.js] => Array
                        (
                            [expected] => 0b118c979e7f7500e22f3849ec4bf13fe84663093400036007550047c99486585753675ad30f486410d9380ffdb5afb30003a5f89e7cb7520a9ceda5d0b3d477
                            [current] => acb0d6f535722770a0e3fb3e34dd2007423517c8364e09cb40a8a29832e0bd7be305d16b4cf94853fb386cc391664796b7382a22ed4739b178813a17f8f6fa2e
                        )

                    [core/vendor/jsTimezoneDetect/jstz.js] => Array
                        (
                            [expected] => 8cb5b1df4cc7cb0ccc58e4283a705684c3790f23aff6f61554ace2f75ea7d5a017952fdeeecdc287a7d534bdc77502315a88cdd6dc2a5385ab53d92d4bfa802f
                            [current] => 14c2327f24d56511147b723f8e7281b32c79cd86995357f96f759bf0cfdd69cc18cacd0e9f1ac00c4bb8f5adc89e73bf991eb9f8dccdfb0201fdac69f489fc88
                        )

                    [core/vendor/showdown/dist/showdown.js] => Array
                        (
                            [expected] => 859749899997555fa2a062308658182601377305dedbc09e8842353083f5e19111e3af75e48ac35020e5ae475abf512a53970248d593fd683f46df6e31a5b573
                            [current] => d5ea0b7a395f9f1829425c8e007fbf823214b536c3c015ce8d2de43abe68e1ed4ca7f721ce697501f04089a5294866e137458a21d5341c90678dcc1a5964ea8b
                        )

                    [core/vendor/showdown/dist/showdown.min.js] => Array
                        (
                            [expected] => 21600e3f9417e1dd5603c65229726d3167405bc7ce89fc01d0bc9914a6aad9672fb1617f5e683c690c3130e5290a349a618fd5f8d0129517950fab824830ef1e
                            [current] => 7accc15a79545c9b54a3b17e74018453e2ecc3619c734f980b251a9d4502444c3cb4aff4b561c5245e1620a5ec89c3feab5a873ba1c9ed60f10ea60951d144a6
                        )

                )

**Comment by theScrabi** [comment]
I'm testing this.

**Comment by theScrabi** [comment]
I could not reproduce the bug neither with the domo.owncloud.com nor with our own owncloud test instance.

**Comment by Calimero33** [comment]
https://ljubo.si/cld/cloud/index.php/login


user: test
Pass: testtest

**Comment by jesmrec** [comment]
I have checked your test account. Did you try to upload something using the web UI? i am not allowed either. I can not upload anything. Maybe you have any misconfigured in the server side?

**Comment by Calimero33** [comment]
try upload over pc… works for me, just android wont… 

⁣Sent from Blue ​

**Comment by Calimero33** [comment]
OK, build thins environment: 
- Install Wordpress in the Public_html folder and instal WP Cereb Security plug in
- Create folder in Public_html folder and install ownCloud in there (public_html/folder/ownCloud)

No test it on such environment!

**Comment by michaelstingl** [comment]
@Calimero33 Better open issue at `WP Cereb Security plug in` and asks why they break the ownCloud instance that's placed in a subfolder. Maybe `WP Cereb Security plug in` has a config option to exclude the ownCloud directory. (public_html/folder/ownCloud)

I'm sorry, but ownCloud team can't help you debug issues with `Wordpress` and `WP Cereb Security plug in`

Please consult ownCloud documentation for a proper setup:
https://doc.owncloud.org/

**Comment by Calimero33** [comment]
I am saying you should test and research it for your self... I can´t use it and soon or later you may get more users with same problem... Do whatever you like...

**Comment by Calimero33** [comment]
I Presume the Cereb lockout there are yours: 
 
![screenshot-2018-4-18 cerber dashboard](https://user-images.githubusercontent.com/38414044/38910771-4dc97a12-42cb-11e8-9385-7a55bc831728.png)
