### ISSUE TITLE
Change Icons for edit shares

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2194]
Currently the icon for editing shares is just an arrow, however I think its more meaningful if it was a pen.

### Currently
![screenshot_20180418-100215](https://user-images.githubusercontent.com/1891273/38919557-321ee13c-42f1-11e8-8b0f-473b109d2302.png)

### Pruposal
![pruposal](https://user-images.githubusercontent.com/1891273/38919576-39b299d4-42f1-11e8-981f-827202a42474.png)

**Comment by rezaiyan** [comment]
@theScrabi 
Can you share directory of this page to anyone want to do it : )

**Comment by michaelstingl** [comment]
@rezaiyan this is the current state (app version 2.7.0):

| ![01](https://user-images.githubusercontent.com/214010/42133514-0528bc3c-7d2c-11e8-93e5-b8c4598f448d.png) | ![02](https://user-images.githubusercontent.com/214010/42133515-05596512-7d2c-11e8-8ec3-0737da09685d.png) | ![03](https://user-images.githubusercontent.com/214010/42133516-0575138e-7d2c-11e8-9f04-69a0da98cf0a.png) | ![04-2](https://user-images.githubusercontent.com/214010/42133517-058f89ee-7d2c-11e8-9044-28f9042ebf27.png) |
|---|---|---|---|
