### ISSUE TITLE
Better looking sidebar

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2204]
Our sidebar gives the impression as if the app is not yet ready, this is because of the huge white space in the middle.

[<img src="https://user-images.githubusercontent.com/1891273/39521421-b70e3ac8-4e0e-11e8-8b59-18c67d9f8e61.png" width="350px"/>](https://user-images.githubusercontent.com/1891273/39521421-b70e3ac8-4e0e-11e8-8b59-18c67d9f8e61.png)

So I suggest something like this here. It can also be combinded with #737 . However it does not have to be like this, but we should get rid of that white area.
[<img src="https://user-images.githubusercontent.com/1891273/39521459-dfad4a6e-4e0e-11e8-9100-c141ba96f8b3.png" width="350px" />](https://user-images.githubusercontent.com/1891273/39521459-dfad4a6e-4e0e-11e8-9100-c141ba96f8b3.png)

**Comment by davigonz** [comment]
@theScrabi Great! I like the new design and I have a question, what is expected to be shown when pressing the arrow located on the right of the account? The list of accounts? If so, we might have too much space there if there's just a couple of accounts configured.

**Comment by michaelstingl** [comment]
@theScrabi What a beauty! 😍 

P.S. Don't forget branded clients. /cc @ChrisEdS

**Comment by theScrabi** [comment]
@jvillafanez do we already feature such an icon like the gray cloud for the branded clients?

**Comment by ChrisEdS** [comment]
Love the idea! I think best practise is to set two more options in ownBrander for the new sidebar. 
One for the background image and one for the logo. Maybe we can implement a option for transparency as well. With our grey ownCloud logo everything is looking fine, but this works not for every customer.
 @michaelstingl What do you think?

**Comment by theScrabi** [comment]
We could maybe show the name of the app instead of a logo if a customer does not add a gray logo.
And for the the header just show a color if header is not set.

**Comment by jesmrec** [comment]
Things to be branded:

- Background image in the top of the drawer
- ownCloud logo on background
- (n2h) background color on the main drawer section.

Question:

The white triangle at the right of the URL. Right now it opens the account options, but in your suggestion such options are in the main. What will i see when i tap on the triangle?

**Comment by davigonz** [comment]
> (n2h) background color on the main drawer section.

That color is already brandeable

> The white triangle at the right of the URL. Right now it opens the account options, but in your suggestion such options are in the main. What will i see when i tap on the triangle?

+1, I have the same question

**Comment by theScrabi** [comment]
After having a discussion about UX and UI here is our second iteration:

#### Not enlarged
[<img src="https://user-images.githubusercontent.com/1891273/39620700-49fe9412-4f8c-11e8-8b63-c27bac9cf4ec.png" width=350px/>](https://user-images.githubusercontent.com/1891273/39620700-49fe9412-4f8c-11e8-8b63-c27bac9cf4ec.png)

#### Enlarged
[<img src="https://user-images.githubusercontent.com/1891273/39620705-4f3d1b42-4f8c-11e8-93bc-730921c7b91b.png" width=350px/>](https://user-images.githubusercontent.com/1891273/39620705-4f3d1b42-4f8c-11e8-93bc-730921c7b91b.png)

**Comment by jesmrec** [comment]
i guess `Feedback` and `Help` are the same in settings view, and the visibility have to be branded as well. 

Other option to include (only an idea if there is enough room, or for future), is adding a link to the rate dialog.

**Comment by theScrabi** [comment]
So I've re based with the quota changes. However I have several problems now.
1. quota does not show up in landscape mode.
2. quota shows a not resolved template string if no quota was yet detected.

**Comment by davigonz** [comment]
> 1. quota does not show up in landscape mode.
> 2. quota shows a not resolved template string if no quota was yet detected.

I will have a look at it
