### ISSUE TITLE
Android App successfully tests SSL connection but fails to log in 'Unknown error'

### ISSUE THREAD

**Issue by Chillstice** [owncloud/android#2206]
### Actual behaviour
When trying to log in using the android application (version 2.7.0) entering `https://cloud.chillstice.com` yields the message: `Secure connection established`; however, when logging in with the correct credentials it tries to log in for 3 seconds and fails with the message: `Unknown error`. The desktop client works fine and the ownCloud panel accessible at cloud.chillstice.com works properly.

### Expected behaviour
The application should log in like I was able to do many times before moving to a subdomain.
 
### Steps to reproduce
1. Create a subdomain redirect to the directory ownCloud is installed in.
2. Try to connect using the new address with the android application.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
NO :C 

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7 Verizon (SM-G930V)

Stock or customized system: Stock

ownCloud app version: 2.7.0

ownCloud server version: 10.0.7.2

#### Web server error log
No relevant errors

#### ownCloud log (data/owncloud.log)
No relevant errors

### More Info
Today I finally figured out how to properly create subdomains and how to set ownCloud to be accessible under the 'cloud' subdomain. I changed the config.php to include the following:
```
  'trusted_domains' => 
  array (
    0 => 'chillstice.com',
    1 => 'cloud.chillstice.com',
  ),
'overwrite.cli.url' => 'https://cloud.chillstice.com/',
'htaccess.RewriteBase' => '/',

```
Then I ran 'occ maintenance:update:htaccess'
The SSL certificates for the subdomain have also successfully been updated and are live.
I only started having this problem after setting up the subdomain.

**Comment by davigonz** [comment]
Hi @Chillstice , thanks for your feedback, could you create a test account and send us the credentials to [apps@owncloud.com](apps@owncloud.com) so we can try to reproduce your problem?

**Comment by Chillstice** [comment]
I sent the message 2 days ago, but here's the credentials anyway:
username: test
password: test
:o 
The server is secure and I'll just delete the account once we're done with it.

**Comment by jesmrec** [comment]
A couple of issues:

- I recommend you not to make public neither your server URL nor the credentials, so anyone can read this and make a wrong use of the account.
- Regarding the issue, do you hace any kind of redirection in your server? the requests after authentication are returning 301 and 302

**Comment by Chillstice** [comment]
- I'm forcing https, but it shouldn't be redirecting since we're working with https in the first place.
- The `cloud` subdomain redirects to /cloud technically since that's the folder that it's installed in. 
- I've had some other rewrite rules for unrelated situations on the server back when it was working. I haven't changed much besides setting it up with the subdomain.

I guess I could reinstall ownCloud and set it up again. That won't be too difficult since I'm waiting to get it all set up before I start using it.

**Comment by Chillstice** [comment]
**WAIT**

I just started messing around with toggling redirects. Apparently my redirect for:
`RedirectMatch 301 /cloud https://cloud.chillstice.com/`
Was causing the problem...

My intention was to keep the url consistent and force requests to the /cloud directory to the subdomain. That probably causes some weird redirect when the mobile version tries to log in.

It's working now. I can't believe that's what the problem was. 

Perhaps if there was a more-verbose error, I could have figured this out sooner. `Unknown Error` is the cause of my nightmares.
