### ISSUE TITLE
Fix acessebility for login view

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#2211]
For people with bad eyesight it is important to have a big font size. OC app seems to work fine with it except the description in the login view:

![photo_2018-05-04_11-57-39](https://user-images.githubusercontent.com/1891273/39622547-f59ea072-4f92-11e8-9a27-4d46e6066441.jpg)

**Comment by sd1998** [comment]
@theScrabi I would like to work on this.

**Comment by sd1998** [comment]
@jesmrec Could you tell me what is required in this?

**Comment by jesmrec** [comment]
i guess that higher-size fonts in login view. @theScrabi could you clarify/confirm?

**Comment by jesmrec** [comment]
Working fine. Feel free to reopen if something is missing regarding fort size.
