### ISSUE TITLE
DetectAuthenticationMethodOperation:run() assumes one WWW-Authenticate header per auth. method

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/android#2216]
_This comes from @guimaluf's report on central: https://central.owncloud.org/t/www-authenticate-response-header-issues-when-authenticating-mobiles-apps-with-oauth2-on-apache-php5-6-fpm/13308/_

---

> When accessing `/remote.php/webdav` with php-fpm and without I get distinct results for WWW-Authenticate header, which fail to auth with mobile clients

> With php5.6-fpm

```
curl -i -X GET https://.../remote.php/webdav
WWW-Authenticate: Basic realm="ownCloud", Bearer realm="ownCloud"
```

> Without php5.6-fpm, with mod_php

```
curl -i -X GET https://.../remote.php/webdav
WWW-Authenticate: Basic realm="ownCloud"
WWW-Authenticate: Bearer realm="ownCloud"
```

--- 

According to [HTTP's Message Syntax and Routing RFC](https://tools.ietf.org/html/rfc7230#section-3.2.2): 

> A sender MUST NOT generate multiple header fields with the same field
>   name in a message unless either **the entire field value for that
>  header field is defined as a comma-separated list** [i.e., #(values)]
>   or the header field is a well-known exception (as noted below).

**This read together with message (header) syntax BNF tells that both forms are absolutely right.** 

Issue here lies in: 

https://github.com/owncloud/android/blob/5b334c075d0c0320b049e30ba5d0624a9390b632/src/com/owncloud/android/operations/DetectAuthenticationMethodOperation.java#L101-L115

... where the app assumes there's always one `WWW-Authenticate` header per authentication method. When a comma-separated list of methods can be provided inside just one `authHeader`. **Actually, one would expect this to be all be determined at a library-level for a clean, portable solution.**

**Comment by jesmrec** [comment]
Thanks for reporting!! we will face a fix.
