### ISSUE TITLE
Feature Request: Select account for instant upload

### ISSUE THREAD

**Issue by lefherz** [owncloud/android#2217]
### Actual behaviour
In https://central.owncloud.org/t/android-instant-upload-with-multiple-accounts-select-target-account/7427 a user reports that in a multi-account setup they can not select the account to which photos shall be instantly uploaded.

The photos are currently only going to the last account which was used. This means that they end up in the wrong folder sometimes. In nextcloud it seems to show the same behavior: https://github.com/nextcloud/android/issues/440

### Expected behaviour
Users should be able to select to which account they want to upload, either after taking a photo or in general.
 
### Steps to reproduce
1. Take a photo
2. Go to the ownCloud app and select another account
3. Take another photo
4. look where they have been uploaded to

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: Android 7.1

Device model: Samsung Galaxy S3 Mini (i8190)

Stock or customized system: Lineage OS 14.1

ownCloud app version: 2.7.0

ownCloud server version: one of them 10.0.7, the other 10.0.6

**Comment by jesmrec** [comment]
Some considerations to take in account and discuss before implementing.

- If only one account is attached in the moment of enabling the feature (or multiaccount disabled): account selected automatically?
- Account by default, or force the user to select one account at the time the feature is enabled.
- If the account selected to upload automatically is removed from device, which one should be set?
- Separate account for videos and pics? or same for both? (we can iterate)
- If the account to upload automatically is switched, the folder to upload to should be as well.

**Comment by davigonz** [comment]
Thanks for opening this issue and attach useful information but this is a duplicated of #827, I will close this issue and paste there what you have commented here.
