### ISSUE TITLE
New login view

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2219]
Our login view is not consistent with the most recent ownCloud versions, so I suggest to update it with something like this.

[<img src="https://user-images.githubusercontent.com/15261363/39826067-ce0e1694-53b3-11e8-8b0b-93f355874c15.png" width="400px"/>](https://user-images.githubusercontent.com/15261363/39826067-ce0e1694-53b3-11e8-8b0b-93f355874c15.png)

In comparison with the previous design:

| Old login view design | New login view design |
| ------------- | ------------- |
| ![old_login_device](https://user-images.githubusercontent.com/15261363/39826089-e0c1c402-53b3-11e8-8bda-74ded0c2b8db.png) | ![login_device](https://user-images.githubusercontent.com/15261363/39826067-ce0e1694-53b3-11e8-8b0b-93f355874c15.png) | 

The **background image** should be customizable of course 

CC / @michaelstingl @jesmrec @ChrisEdS @theScrabi

**Comment by priyanktyagi89** [comment]
@davigonz : Can I pick this task?

**Comment by jesmrec** [comment]
@pmaier1 do you agree to use the mentioned look for the login view? i think is congruent with the current web UI in the product.

The point is, that this pic changes in different versions of the product, so it should be maintained. 

About branding, the pic is the same used in https://github.com/owncloud/android/issues/2204, so a combined option with the current one for branding the color of the drawer fits (maybe) better.

CC @theScrabi  @michaelstingl

**Comment by michaelstingl** [comment]
@jesmrec sounds cool 👍

**Comment by pmaier1** [comment]
I kind of dislike the headline "Server address https://...". Would rather like to have it as a placeholder in the input field. Apart from that it's only the background/colors that has changed, right?

**Comment by pmaier1** [comment]
> @pmaier1 the issue about the android design is that the place holder turns into the headline once you tap into the input field.

Ah ok, I see, thanks :+1:

**Comment by davigonz** [comment]
> Apart from that it's only the background/colors that has changed, right?

@pmaier1 Colors, background and a better handling of white spaces.

**Comment by cdamken** [comment]
Question: Now is not necessary to type `http://` or `https://` in front of the URL, will be that autodetect?

**Comment by theScrabi** [comment]
no its not automated.

**Comment by theScrabi** [comment]
good point :D

**Comment by davigonz** [comment]
> ;( then you have to still write it? in the screenshots at the top is now written.

Do you mean the `Server address https://` message? That's just the placeholder and will turns into the headline once you tap the inputfield

**Comment by theScrabi** [comment]
no I think he mans this part:
![screen shot 2018-06-28 at 09 38 51](https://user-images.githubusercontent.com/1891273/42020057-16fdf4d0-7ab7-11e8-81fe-39f2e7367069.png)

you can't see a http:// or https:// written here. Which is not correct, because our login does not accept an address without the scheme.

**Comment by davigonz** [comment]
> you can't see a http:// or https:// written here. Which is not correct, because our login does not accept an address without the scheme.

Yes, our login accepts it, you can put the address without the scheme

[<img src="https://user-images.githubusercontent.com/15261363/42020856-64601788-7ab9-11e8-9514-c831aec45f88.gif" width="400px"/>](https://user-images.githubusercontent.com/15261363/42020856-64601788-7ab9-11e8-9514-c831aec45f88.gif)

**Comment by theScrabi** [comment]
O.o uff ... didn't know

**Comment by cdamken** [comment]
> Yes, our login accepts it, you can put the address without the scheme and it will be automatically set by the app.

Nice!, I hate to write `damken.cloud` and then I have to go back and write the `https://`
