### ISSUE TITLE
No such property: name for class: java.lang.String

### ISSUE THREAD

**Issue by ainnazrah95** [owncloud/android#2225]
### Actual behaviour
def setOutputFileName(variant, appName, callerProject) {
    logger.info("Setting new name for output of variant $variant.name")

    def originalFile = variant.outputs[0].outputFileName
    **def originalName = originalFile.name**
    logger.info("$variant.name: originalName is $originalName")

    def newName = ""

    if (appName) {
        newName += appName
    } else {
        newName += callerProject.archivesBaseName
    }

    def versionName = "$variant.mergedFlavor.versionName"
    if (variant.mergedFlavor.manifestPlaceholders.versionName != null) {
        versionName = "$variant.mergedFlavor.manifestPlaceholders.versionName"
    }
    if (variant.buildType.manifestPlaceholders.versionName != null) {
        versionName = "$variant.buildType.manifestPlaceholders.versionName"
    }
    newName += "_$versionName"

    def buildNumber = System.env.OC_BUILD_NUMBER
    if (buildNumber) {
        newName += ".$buildNumber"
    }

    newName += originalName.substring(callerProject.archivesBaseName.length())

    logger.info("$variant.name: newName is $newName")
    variant.outputs[0].outputFileName = new File(originalFile.parent, newName)
}

### Expected behaviour
The code should be run but error at part where the error is the code that I bold above when I click on the link Open File.
I got an error message: No such property: name for class: java.lang.String

### Environment data
Android version:3.1.2

Device model: Xiaomi Redmi Note 5A Prime

ownCloud server version:10.0.6
`

**Comment by davigonz** [comment]
> when I click on the link Open File.

Hi @ainnazrah95 , I don't know what you mean with _clicking on the link Open File_, that method is being used to set the apk name when building the app.

**Comment by ainnazrah95** [comment]
ok sorry Mr @davigonz . I attach the screenshot of my Android Studio to understand the situation.
![capture](https://user-images.githubusercontent.com/38446031/40210714-21d0b98c-5a79-11e8-8b76-62857c35373a.PNG)

**Comment by ainnazrah95** [comment]
And I try to delete the owncloud android repository from my github and fork again the repo but I got an error as I open the file in Android Studio. Error seems from the outputFile
![capture](https://user-images.githubusercontent.com/38446031/40217618-496d7d6e-5aa0-11e8-82bd-34065f98ec0a.PNG)

**Comment by davigonz** [comment]
Hi @ainnazrah95 , have you upgraded the gradle version? This error is likely due to a gradle upgrade. 
Replace `variant.outputs[0].outputFile = new File(originalFile.parent, newName)` with: `variant.outputs.all {
    outputFileName = new File(".", newName)
}` and try to build the project again. 

We will upgrade gradle and fix this in the next version anyway.

**Comment by ainnazrah95** [comment]
Hi @davigonz , yes I was upgrading the gradle version 3.1.2. After I replace the code, rebuild the project and just left the errors for obsolete configuration for androidTestCompile, compile and testCompile. Thanks for your help.

**Comment by ainnazrah95** [comment]
Now I'm stuck at this error Could not find com.android.tools.lint:lint-gradle:26.1.2.
Do you have any idea Mr @davigonz ?

![capture](https://user-images.githubusercontent.com/38446031/40232587-fa1f31d0-5ad1-11e8-8fc5-35ff7d98347a.PNG)

**Comment by davigonz** [comment]
@ainnazrah95 we have merged the gradle upgrade into master this morning, I would recommend you to `fetch` and `rebase` the changes in your branch. All the problems you are facing are already fixed in master.

**Comment by ainnazrah95** [comment]
I'm still new in using Git and so much new things I learnt so far. But how to fetch and rebase the changes? Can you check the commands below is it true or not?
my forked repository named: androidOwncloud
to fetch:
git fetch android
to rebase:

$ git clone https://github.com/my-username/androidOwncloud.git
$ cd androidOwncloud
$ git checkout -b my-branch

Sorry I'm asking too much questions @davigonz

**Comment by davigonz** [comment]
> Sorry I'm asking too much questions @davigonz

No worries, glad to know you are playing with our project and you can even contribute with some features someday 😊

To understand better how a rebase works, you can follow the instructions I posted [here](https://github.com/owncloud/android/pull/2075#issuecomment-359428847) about how to perform a rebase with master and ask me if there's any additional question.

**Comment by ainnazrah95** [comment]
I think I'm mistaken for any command parts. Can you check @davigonz ?
![capture](https://user-images.githubusercontent.com/38446031/40244155-a9de427e-5af4-11e8-9e20-da36b550f688.PNG)
![capture](https://user-images.githubusercontent.com/38446031/40244234-ebd6c534-5af4-11e8-9b36-2925739bbcf1.PNG)

**Comment by theScrabi** [comment]
You where trying to rebase even though git clearly says that you have stashed changes.

@ainnazrah95 If you want to contribute to this project you need to be aware of how git works. I highly recommand trying this: https://learngitbranching.js.org/

**Comment by ainnazrah95** [comment]
ok, thank you for your advice Mr @theScrabi 👍
