### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [owncloud/android#2229]
Sorry for not having the template
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs if you are needing it. Hoping for your positive response Thank You!

**Comment by michaelstingl** [comment]
@jbeguna04 Thanks for your kind offer. I checked some of your contributions to other projects – amazing!

The [ownCloud logo is a registered trademark](https://owncloud.org/trademark/) and widely used across the platform. Changing the logo itself in the ownCloud Android app would cause some confusion. But help from skilled designers would be definitely beneficial. @davigonz @theScrabi What do you think? Ideas?

**Comment by jbeguna04** [comment]
Thank You for your response. I understand, thank you for viewing my issue, Good luck in your application

**Comment by ChemWater** [comment]
Hello,

I've been trying to use the app to see how I can contribute to the project.
But I've never used an application that prompts you to use a server address
to use the service. Can someone instruct me on how to attain and implement
a personal server address for the initial prompt?

Thanks in advance

**Comment by theScrabi** [comment]
an easy way would be to get a test account at [blaucloud.de](https://blaucloud.de).

**Comment by davigonz** [comment]
> But help from skilled designers would be definitely beneficial. @davigonz @theScrabi What do you think? Ideas?

As @michaelstingl said, changing the ownCloud Android icon would be weird if we don't update the global ownCloud logo but of course, any help is welcome so @jbeguna04 maybe you are interested in contributing with some UI mockups for different new features. 

For example, we are planning to update our login view and we would appreciate more designers feedback, have a look at https://github.com/owncloud/android/issues/2219, you might have something to suggest.

**Comment by davigonz** [comment]
> Can someone instruct me on how to attain and implement
a personal server address for the initial prompt?

Hi @ChemWater , glad to see you want to install your first ownCloud server, I would highly recommend you to read our [ownCloud administrator manual](https://doc.owncloud.org/server/10.0/admin_manual/) about the installation and create new topics in [https://central.owncloud.org/c/server](https://central.owncloud.org/c/server) if you have any question, we and our community will help you with the process. 

One of the fastest way to have your ownCloud server is using docker, [here](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/) you have the steps to do that, have a look at it.

**Comment by jesmrec** [comment]
This issue about the login/icon will not be moved forward due to the already explained reasons. For contributing, please check the links that @davigonz pasted, and for any question please open new issue here or in https://central.owncloud.org.

Thanks for your interest!
