### ISSUE TITLE
OAuth2 + multiaccount

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2240]
Currently it's not quite an easy task to do if you want to login into 2 or more accounts at the same server.

Because after accessing the first account you are still loged  in your browser, and you get directly redirected to the authorise view:
![screenshot_1528803133](https://user-images.githubusercontent.com/1891273/41288133-8a939ebe-6e45-11e8-9d36-9936269105c6.png)

If you now want to login into a different account now, you have to open your browser, and log out manually.

Currently is posible in server side to send the user you want to authenticate in the authorization request, thanks to the fix in https://github.com/owncloud/oauth2/pull/60

**Comment by michaelstingl** [comment]
works with https://github.com/owncloud/oauth2/pull/188
