### ISSUE TITLE
New install of ver 2.8 andriod not working

### ISSUE THREAD

**Issue by cgpgh** [owncloud/android#2245]
### Actual behaviour
-Tell us what happens
I have used a free version for long time and it worked like a charm. I recently installed OC 10.0.8 and purchased this app to show support. But after I enter my OC server details and user name/passwd. It just sits there. Never connects. The mac desktop client works fine. What could be the problem. I uninstalled and reinstalled. Pls help.

### Expected behaviour
-Tell us what should happen
 See my files and upload new files

### Steps to reproduce
1. Install the app
2. Configure 
3. Try to use it

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes. I tried the app is not able ro connect 

### Environment data
Android version:

Device model: 
Samsung SM-G925A S6 EDGE

Stock or customized system:AT&T

ownCloud app version:
2.8
ownCloud server version:
10.0.8

#### Web server error log
[root@macoc1 httpd]# pwd
/var/log/httpd
[root@macoc1 httpd]# tail -f ssl_request_log 
[21/Jun/2018:22:39:42 -0400] 67.xx.xx.185 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "PROPFIND /owncloud/remote.php/dav/files/xxccx/ HTTP/1.1" 342
[21/Jun/2018:22:39:44 -0400] 67.xx.xx185 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 899
[21/Jun/2018:22:39:44 -0400] 67.169.172.185 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /owncloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 160

```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```the log file is empty
-rw-r-----. 1 apache apache  0 Jun 21 22:33 owncloud.log

**Comment by davigonz** [comment]
Hi @cgpgh , first of all, thank you for reporting this issue, can you please tell us the error message you see after entering the credentials? 

I guess you are a beta tester since as you say above, you bought the official app and there's no 2.8 final version yet but 2.8 beta v1. 

> Can this problem be reproduced with the official owncloud server?
> (url: https://demo.owncloud.org, user: test, password: test)

> Yes. I tried the app is not able to connect

Are you sure the app is not working with the demo server? I've just downloaded the beta version from PlayStore and is working properly. This demo server is restarted from time to time, can you try it again and if is still not working paste here the error message? Thanks in advance

**Comment by cgpgh** [comment]
David,


Thank you for the reply.


I purchased ver 2.7 that did not work. so I signed up for beta to see that helps but no.

Demo server login with both versions did not work, I feel it's isolated to my device, but don't know how to fix it.


It save  the user name and password and after shows loading and stays there. I am unable to take screenshots on the phone it's prevented due to security.


Regards

Cyril


________________________________

**Comment by cgpgh** [comment]
I was able to get a screenshot of the loading page where it stays there.

[cid:7973db1c-b738-438b-8655-7386c685ee9f]




Regards

Cyril


________________________________

**Comment by michaelstingl** [comment]
@cgpgh Your screenshot didn't made it to your comment.

In the beta version, you can access the logs on the settings screen. Could you send them to apps@owncloud.com ?

**Comment by cgpgh** [comment]
Michael,


The logs are empty, see screenshot attached.


Regards

Cyril


________________________________

**Comment by theScrabi** [comment]
I think we can not see the attached file here in the github issue page. @cgpgh please take a look at the web version of this issue.

**Comment by ChrisEdS** [comment]
// Update from ownCloud Support-Team
## Missing screenshot

![screenshot_20180622-125741](https://user-images.githubusercontent.com/33026403/42626962-ee221968-85cb-11e8-9b9b-93e339bbf57f.png)

**Comment by cgpgh** [comment]
All,


The app is now working fine. There was another conflicting app that was preventing it from working.


Regards

Cyril


________________________________

**Comment by ChrisEdS** [comment]
@cgpgh Good news!
