### ISSUE TITLE
Inappropriate Message when creating a folder with an existing folder name

### ISSUE THREAD

**Issue by sd1998** [owncloud/android#2247]
### Actual behaviour
When trying to create a folder with the same name as one that has already been created. The snackbar message states "Method not allowed". 

### Expected behaviour
I think the message should be a bit more informative like "Folder with same name exists" of another forlder should be created with suffix "<folder name> + 1".

### Steps to reproduce
1. Create a folder named "xyz" by selecting option from the FAB in FileDisplayActivity.
2. Create another folder with the name "xyz" following the similar procedure.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes.

![41779120-6f65b99a-764e-11e8-9eaf-2eaa7eb93e5c](https://user-images.githubusercontent.com/1891273/41834718-8217ef50-7855-11e8-891e-79c32fe2b65d.png)

**Comment by sd1998** [comment]
@davigonz @jesmrec  I think this is an issue and if you agree with this then I would like to make the change its just a minor one.

**Comment by jesmrec** [comment]
go ahead

**Comment by sd1998** [comment]
@jesmrec Which one of the following should it be? The message should be a bit more informative like "Folder with same name exists"? or another folder should be created with suffix " + 1".?

**Comment by michaelstingl** [comment]
What error does the server send in the response? Could you post it here?

**Comment by jesmrec** [comment]
The response of the MKCOL request is a 405 error with:

`<s:message>The resource you tried to create already exists</s:message>`
