### ISSUE TITLE
Camera uploads problems

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2249]
There are different devices which are having problems with camera uploads. 

We will use this issue to gather all the info related to find which the  problem could be, and needed fixes as well.

**Comment by jesmrec** [comment]
A user has reported us that the problem happens with the following info:

Device: Xiaomi 5S (32GB version)
Android version: 7.0 NRD90M
Xiaomi MIUI ver: Global 9.5.2.0
App version 2.7.0
Camera folder: /storage/emulated/0/DCIM/OpenCamera (have tried Camera aswell)
Camera App: OpenCamera, previously in-built Xiaimi MIUI camera app

**Comment by lefherz** [comment]
Version 2.7.0 reports with upload errors have following devices & Android versions:

* phhgsi_arm64_a - Android 5.0.2
* flo - Android 6.0 (Works fairly well, aside from very unreliable photo upload. The instant 
upload occasionally works automatically, but usually you have to go into 
settings and re-choose the source directory. Then it will realize there are 
files there and start to upload. Probably.)
* OnePlus3 - Android 8.0
* bullhead - Android 8.1
* OnePlus5 - Android 8.1 & 8.0
* j7popltevzw - Android 7.0
* HWVTR - Android 8.0
* greatqlte - Android 8.0
* dreamlte - Android 8.0
* walleye - Android 8.1
* hero2lte - Android 7.0 (sometime cannot upload video if the file size is too large)
* HNKIW-Q - Android 6.0
* natrium - Android 7.0
* zeroflte - Android 7.0
* taimen - Android 8.1
* markw - Android 6.0
* a5y17lte - Android 7.0
*

**Comment by michaelstingl** [comment]
bullhead ==> Nexus 5X
dreamlte ==> Samsung Galaxy S8
greatqlte ==> Samsung Galaxy Note8
natrium ==> Xiaomi Mi 5s Plus
taimen ==> Google Pixel 2 XL
walleye ==> Google Pixel 2
zeroflte ==> Samsung Galaxy S6

**Comment by michaelstingl** [comment]
Most devices look very common. Nothing suspicious.

**Comment by michaelstingl** [comment]
Okay, if my Google Pixel 2 with Android P is locked and placed on my desk without touching it, it doesn't upload new photos after 15 Minutes. As soon as I press the power button, it starts uploading. I don't need to unlock it.

**Comment by michaelstingl** [comment]
Hm, not everything smooth…

![2018-06-27_21_50_03](https://user-images.githubusercontent.com/214010/41996262-a2bea22a-7a54-11e8-997b-8b3831603bbd.png)

**Comment by jesmrec** [comment]
I have the feeling that there are still many users that does not understand correctly how this feature works. Of course, this is not his/her fault. By reviewing all the feedback stuff i guess:

- Users that keeps expecting uploads to be performed instantly
- Users that don't use the `Camera folder` field to select the camera app they use to take pics/videos
- Users that take pics with the app closed, and expect the pics to be synced directly to the backend with no further actions

That does not mean the fact we have some kind of incorrect behaviour to fix, but we have to be sure that the user who reports a camera uploads problem is getting the correct performance of the feature.

@michaelstingl @lefherz @davigonz @theScrabi if you agree, i will elaborate a template in which we ask the most relevant information about the environment (device model, camera app etc..), explaining the expected behaviour (https://doc.owncloud.org/android/android_app.html#camera-uploads), checks to perform... the idea is using such template to ask users for feedback in the same way in all available channels (GitHub, otrs, GooglePlay, central) in order to have all relevant info together.

**Comment by theScrabi** [comment]
Maybe if the users don't understand what is going on here, we might ask how can we make the user understand, or better why does the user not understand.

**Comment by jesmrec** [comment]
we did it, by including it in ownCloud manual, blog posts... but you can not force users to read such stuff.

**Comment by theScrabi** [comment]
> but you can not force users to read such stuff.

That's the point, so how can we make the user understand this even if he is to lazy for reading the posts.

**Comment by theScrabi** [comment]
Maybe by showing a notice (AlertDialog) when enabling image uploads?

**Comment by theScrabi** [comment]
> you mean, pointing to the docs o explaining directly the behaviour?

Explaining it directly.

**Comment by davigonz** [comment]
> we did it, by including it in ownCloud manual, blog posts... but you can not force users to read such stuff.

And we included a specific step in our wizard as well.

> Maybe by showing a notice (AlertDialog) when enabling image uploads?

Something like this could help, I can understand they might skip the wizard but if a user decides to enable camera uploads, it's more likely he read the dialog we show there.

**Comment by jesmrec** [comment]
the point is that such alert will be triggered when the option is enabled. Those users who has the option already enabled will never read this.

**Comment by nzjc** [comment]
I was the user who reported a problem with Device: Xiaomi 5S (32GB version) (June 26th report). I have now shifted to the beta version of Owncloud and camera upload (from OpenCamera folder) seems to be working automatically as I would expect. 

The version that is displayed in the App is 2.8.0

**Comment by sbourdette** [comment]
I'm on Galasy S8 owncloud client 2.8.0.

I have the same behaviour as @michaelstingl screenshot.
Next I have a alert message saying Owncloud has crashed

**Comment by roman65536** [comment]
On a Galaxy A5 (2016) had to put owncloud to unmonitored apps. Otherwise app monitor would stop owncloud on longer upload, consequently stopping uploading with 404 from server. 

Now it works perfect, even on large (+100M) uploads.

**Comment by MegaBrutal** [comment]
I have a problem with Camera uploads which I've not seen mentioned here. My Camera uploads feature only works sporadically. I noticed it is connected to how much free space I have on the device. Since I'm always in a low space condition with my device, Camera uploads usually doesn't work. But when I occasionally manage to free up a larger amount of storage space, ownCloud starts to upload all the files it missed before.

I suspect there is a fail-safe to not perform Camera uploads while the free space is below a certain minimum, but currently I have 761 MB free space and ownCloud still won't upload my files. I think this is well enough space to not worry about uploading. I don't even know why this fail-safe would be necessary, since Camera uploads doesn't even take more space (as it doesn't copy files into the ownCloud folder); maybe there are upload buffers and ownCloud App doesn't want to risk suffocating the entire device, but I don't think uploading with more than ~700 MB free space would be dangerous. So if there is a fail-safe, I'd lower the threshold.

Manual uploads work, only automatic Camera uploads are affected.

**Comment by davigonz** [comment]
Hi @MegaBrutal , thanks for the information, I have a couple of questions:

1. Are you waiting 15 minutes to have your pictures uploaded? Maybe is not a problem with the free storage space and all the pictures are uploaded after waiting a certain amount of time.

2. Do you see any error when there's no enough storage space? I mean, within the camera upload notifications, or are they not even triggered?

Thanks

**Comment by MegaBrutal** [comment]
Hi @davigonz,

1. I waited several weeks/months with the application open in the background. (I suppose I don't have to keep it in the foreground for 15 minutes.)
2. The ownCloud app doesn't show me any notifications about storage space. Android sometimes shows me low space warning (with suggestion to run the cleanup tool), but now with ~504 MB free space, I don't have that warning. I only get that when I get really low.

I also tried the „Refresh account” button, it still doesn't start to upload files.

**Comment by McGeifer** [comment]
After getting my new Xiaomi MI 9T I ran into problems aswell. I only allow the upload via Wi-Fi and it is not working at all (there is no error message or something else).

After a bit of playing around with the settings in the App I could reproduce a very strange behaviour. If I deselect the "Only upload via Wi-Fi" it instantly starts to upload all the pictures that are new for the server. My Wi-Fi connection is always enabled and even if I disable it and re-enable it by hand it won't upload files. So I have to disable the Wi-Fi only option always by hand to make sure it does not use my mobile Internet connection which is kind of annoying.

**Comment by jesmrec** [comment]
Camera uploads were totally reworked, so these reports makes no longer sense. Please, feel free to reopen or address new ticket in case camera uploads run into trouble
