### ISSUE TITLE
"Local copy could not be renamed; try a different name" when connecting for first time

### ISSUE THREAD

**Issue by herrjon** [owncloud/android#2257]
### Actual behaviour
When setting up owncloud on Android phone for the first time the message "Local copy could not be renamed; try a different name" appears after accepting the server certificate (in my case I have a self generated ssl certificate)

### Expected behaviour
Configuration should complete without errors.
 
### Steps to reproduce
1. Install owncloud for Android
2. Open, enter configuration information for server.   Mine is a "https://xxxx.dyndns.org" 
3. Observe error message (can't take a screenshot either)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No - connects okay.   Can I delete a local file on the phone that is corrupted?

### Environment data
Android version:
8.0.0
Device model: 
LG G7 ThinQ

Stock or customized system:
N/A
ownCloud app version:
2.8.0
ownCloud server version:
10.0.0.8

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
i can not reproduce here the problem with a self-signed server. The issue (maybe) can be related with some kind of redirection that the dyndns service performs. Could you send us a test account in your server to test which the problem could be? you can send it to apps@owncloud.com (please, include a link the current issue in the mail)

**Comment by herrjon** [comment]
I apologize - problem was at my end.
I didn't enter the complete url which had to include "/owncloud"
 "https://xxxx.dyndns.org/owncloud"

Where I had only entered:
""https://xxxx.dyndns.org"
