### ISSUE TITLE
Re-shares not shown in Android app UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#2264]
### Actual behaviour
Re-shares not shown in Android app UI.

### Expected behaviour
Owner of a share should also see recipients of re-shares, same as in web UI.
 
### Steps to reproduce
1. User A shares folder with User B
2. User B shares received folder with User C

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
yes

### Server UI

| User A | User B | User C |
|---|---|---|
| ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43005844-5480580a-8c34-11e8-966f-b4919a4ce127.png) | ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43006035-f13fce96-8c34-11e8-904c-4dc63e00516a.png) | ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43006098-1d726a50-8c35-11e8-9ea0-d2ff65cd7f71.png) |

### Android app UI

| User A | User B | User C |
|---|---|---|
| ![screenshot-2018-07-20_16 51 22 29](https://user-images.githubusercontent.com/214010/43010811-d24a89ce-8c41-11e8-80de-a5ef79b1303b.png) | ![screenshot-2018-07-20_17 00 07 272](https://user-images.githubusercontent.com/214010/43010813-d46f97c6-8c41-11e8-945a-333ff64bf895.png) | ![screenshot-2018-07-20_17 05 32 298](https://user-images.githubusercontent.com/214010/43010815-d5f6ff4e-8c41-11e8-89a7-929daf05f3ff.png) |

### Environment data
Android version:
5.1.0

Device model:
Google Nexus 5 (simulated)

Stock or customized system:
Genymotion VM

ownCloud app version:
2.8.0

ownCloud server version:
10.0.9

## Solution

@jnweiger PR for the desktop client: https://github.com/owncloud/client/pull/6665

related: https://github.com/owncloud/enterprise/issues/2505

@davigonz Could you add this to the 2.9.0 ?

**Comment by davigonz** [comment]
> Could you add this to the 2.9.0 ?

Yes, I will check the complexity of this

**Comment by michaelstingl** [comment]
I hope complexity isn't that high:

![visibility_of_shared_folders_ _issue__2505_ _owncloud_enterprise](https://user-images.githubusercontent.com/214010/43068836-d0cfe6c6-8e6b-11e8-8050-64761d9ed460.png)

**Comment by davigonz** [comment]
So, we should switch to v2.php

**Comment by michaelstingl** [comment]
`v2.php` and `v1.php` are identical. @PVince81 is there a recommendation to use `v2.php` or `v1.php`? @davigonz key is, to add the `reshare=true` parameter to the request.

**Comment by PVince81** [comment]
use v2.php if you like sane HTTP return codes.
if you love OCS 100 return codes you can keep using v1.php...
