### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by Seriousitchy** [owncloud/android#2265]
### Actual behaviour
-Tell us what happens
After entering all credentials, the screen doesn't proceed to the files view. It simply refreshes the login screen. No message whatsoever.
This behavior applies to my tablet, but on my Smartphone the APP is working as it should.
Also, the login is working with the nextcloud APP on my tablet (with the same owncloud Server).

### Expected behaviour
-Tell us what should happen
 The APP should proceed to the files view.

### Steps to reproduce
1. Start app
2. type in URL, username and pw
3. push login button

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

The APP logs into the test server successfully.

### Environment data
Android version:
LineageOS 14.1
Device model: 
Sony xperia Tablet Z
Stock or customized system:
Custom
ownCloud app version:
2.8.0 and previous
ownCloud server version:
10.0.9
#### Web server error log
```
{"reqId":"W1hm3D5sIIcAAAkV0YEAAAAE","level":3,"time":"2018-07-25T12:02:37+00:00","remoteAddr":"88.67.115.108","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"unlink(\/tmp\/oc_tmp_67feDP): Operation not permitted at \/var\/www\/vhosts\/xxxxx.com\/httpdocs\/owncloud\/lib\/private\/legacy\/helper.php#224"}
{"reqId":"W1hm3D5sIIcAAAkV0YEAAAAE","level":2,"time":"2018-07-25T12:02:37+00:00","remoteAddr":"88.67.115.108","user":"--","app":"no app in context","method":"GET","url":"\/cron.php","message":"Error deleting temporary file\/folder: \/tmp\/oc_tmp_67feDP-folder - Reason: RecursiveDirectoryIterator::__construct(\/tmp\/oc_tmp_67feDP-folder): failed to open dir: Permission denied"}
{"reqId":"W1hm3D5sIIcAAAkV0YEAAAAE","level":3,"time":"2018-07-25T12:02:37+00:00","remoteAddr":"88.67.115.108","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"unlink(\/tmp\/oc_tmp_w2gMzn): Operation not permitted at \/var\/www\/vhosts\/xxxxx.com\/httpdocs\/owncloud\/lib\/private\/legacy\/helper.php#224"}
{"reqId":"W1hm3D5sIIcAAAkV0YEAAAAE","level":3,"time":"2018-07-25T12:02:37+00:00","remoteAddr":"88.67.115.108","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"unlink(\/tmp\/oc_tmp_w2gMzn-.tar.gz): Operation not permitted at \/var\/www\/vhosts\/xxxxx.com\/httpdocs\/owncloud\/lib\/private\/legacy\/helper.php#224"}
{"reqId":"W1hm3D5sIIcAAAkV0YEAAAAE","level":3,"time":"2018-07-25T12:02:37+00:00","remoteAddr":"88.67.115.108","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"RecursiveDirectoryIterator::__construct(\/tmp\/oc_tmp_67feDP-folder): failed to open dir: Permission denied at \/var\/www\/vhosts\/xxxxx.com\/httpdocs\/owncloud\/lib\/private\/legacy\/helper.php#205"}
```

#### ownCloud log (data/owncloud.log)
```
No log
```

**Comment by davigonz** [comment]
Hi @Seriousitchy , thanks for reporting this, do you have a customized system in your smartphone as well? Is it the first time you are using the app in your tablet or it worked with previous app and server versions?

**Comment by Seriousitchy** [comment]
Hi @davigonz, my Smartphone has the stock Rom installed and unlike the tablet its not rooted. I remember that it used to work once, I cant remember which versions I had back then though.

**Comment by theScrabi** [comment]
@Seriousitchy you could use the latest [beta release](https://f-droid.org/repo/com.owncloud.android_20700100.apk) of our application. It has log functionality. You could send us the log. Optionally you could use logcat to gather logs of the app.

**Comment by Seriousitchy** [comment]
@theScrabi thank you, but I still cant find a log.
Am I looking in the wrong folder? Thats the path I found: Android/data/com.owncloud.android/

**Comment by Seriousitchy** [comment]
@theScrabi thank you! I attached the log file here:
[currentLog.txt](https://github.com/owncloud/android/files/2233653/currentLog.txt)

**Comment by theScrabi** [comment]
@davigonz 
So there are two parts in the log I don't like first is line 14-24:
```

2018/07/26 23:16:39
FeatureList : Version string is incorrect 0

2018/07/26 23:16:39
FeatureList : Version string is incorrect 0

2018/07/26 23:16:39
FeatureList : Version string is incorrect 0

2018/07/26 23:16:39
FeatureList : Version string is incorrect 0

2018/07/26 23:16:39
FeatureList : Version string is incorrect 0
```

Here the cause of our error in line 359-363:
```
2018/07/26 23:18:22
FileDisplayActivity : Access to unexisting list of files fragment!!

2018/07/26 23:18:22
FileDisplayActivity : OCFileListFragment is null
```

**Comment by theScrabi** [comment]
@Seriousitchy you could try to replace basic auth with oauth, by installing this app:
https://marketplace.owncloud.com/apps/oauth2

However if you do this (on apache2) make sure to enable the modes `rewrite` and `headers`.

**Comment by davigonz** [comment]
> thank you! I attached the log file here:

Hi again @Seriousitchy , I have tried the 2.8 app and the logs that @theScrabi comments above also appear, so nothing strange from my point of view. 

Could you create a test account and send us the credentials to apps@owncloud.com so we can try to reproduce the problem directly on your server? Thanks

**Comment by jesmrec** [comment]
@Seriousitchy are you still having this problem?

**Comment by jesmrec** [comment]
After releasing new versions, there is no further problems in the auth process. 

If the problem persists, please reopen to continue the researching.
