### ISSUE TITLE
Please add to 3-bar navigation pane links to "Favorites" and "Shared by link" files.

### ISSUE THREAD

**Issue by BDMN** [owncloud/android#2276]
In continue to Ticket#201808107002029.
### Actual behaviour
- 3-bar menu contains only "All files" and "Uploads" links
### Expected behaviour
- By analogy with web-interface please add links: "Favorites" and "Shared by link"
### Why this should be added
This features are very useful. Especially with such scenarios:
- Very deep directory-subdirectory structure (3 and more subs).
- Very large amount of shared files (50+).
- Especially, when two above combined.

It improves operational efficiency by an order of magnitude, saves a lot of time.

![web version](https://user-images.githubusercontent.com/2332799/43989992-68f0a10c-9d5d-11e8-8f92-2a7759666696.png)
![android version](https://user-images.githubusercontent.com/2332799/43989993-6c9ffa00-9d5d-11e8-940a-868623768b40.png)

### PR

- App: https://github.com/owncloud/android/pull/2705

**Comment by michaelstingl** [comment]
@BDMN thanks for opening this issue!

**Comment by jesmrec** [comment]
Favorites is not developed yet as feature in mobile side. It is in our roadmap, and a shortcut will be included. Share links, you have a link in the bottom bar. We can discuss if including it in the drawer menu.

**Comment by michaelstingl** [comment]
Issue for Favorites: https://github.com/owncloud/android/issues/867

**Comment by michaelstingl** [comment]
> Share links, you have a link in the bottom bar

@jesmrec in iOS. In Android there is no bottom bar.

**Comment by jesmrec** [comment]
you are right...

**Comment by BDMN** [comment]
Hello team,

Is there any updates here about share links?

**Comment by michaelstingl** [comment]
@BDMN The Android team was busy with the exchange of the networking library and working on a new WebDAV library. The old libraries are deprecated for a long time. Also on the roadmap for the next months are more refactoring and architectural changes to make the app future-proof and stable with good performance. This means on the other hand, that some requested features will be delayed for quite some time.

Here you can find more information about the latest changes in yesterdays 2.9.0 release:
https://central.owncloud.org/t/owncloud-2-9-for-android-released/16634

**Comment by sd1998** [comment]
@jesmrec is this still required? I would like to work on this.

**Comment by jesmrec** [comment]
yes, it would be nice to get, but only for the "Shared by links". We will set more options there at the time are developed

**Comment by davigonz** [comment]
@sd1998 @hannesa2 moving it to 2.11
