### ISSUE TITLE
App asks users to rate it with every new version

### ISSUE THREAD

**Issue by lefherz** [owncloud/android#2277]
### Actual behaviour
- After the app was upgraded, users are asked to rate it.

### Expected behaviour
- users who purchased the app on GooglePlay should be asked to rate it.
- everyone should only be asked once.
 
### Steps to reproduce
unfortunately I can't reproduce it myself, but users have reported that they are asked too often.

### Environment data (picking one of the more angry users)
Android version: 8.0

Device model: Galaxy S7 (heroqltevzw)

Stock or customized system: stock I think

ownCloud app version: 2.8.0

ownCloud server version: ¯\\\_(ツ)_/¯

**Comment by jesmrec** [comment]
we have to review these parameters:

https://github.com/owncloud/android/pull/2102#issuecomment-369931339
