### ISSUE TITLE
LDAP Auth fails on upload from Android client

### ISSUE THREAD

**Issue by bluesbro1982** [owncloud/android#2279]
### Actual behaviour
When trying tou upload a large-ish file to owncloud from a Galaxy s9+ running Android 8.0, uploading appears to start, but hangs. Server side error message reads:

### Expected behaviour
Should let a file be uploaded
 
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No. This appears related to LDAP authentication in the android client.

### Environment data
Android version: 8.0.0

Device model: Galaxy s9+

Stock or customized system:Stock

ownCloud app version:2.8

ownCloud server version: 10.0.9 Stable

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"9a859125-51c7-4311-8a85-9e8139e12316","level":2,"time":"2018-08-14T17:20:21-07:00","remoteAddr":"12.xx.xx.xx","user":"xxxx","app":"user_ldap","method":"PROPFIND","url":"\/remote.php\/dav\/files\/xxxx\/","message":"Configuration Error (prefix s01): login filter does not contain %uid place holder."}
```

**Comment by jesmrec** [comment]
i will check if the behaviour is reprodicible and how LDAP affects. Thanks for reporting!!

**Comment by jesmrec** [comment]
@bluesbro1982 could you check if the latest version fix the problem?
