### ISSUE TITLE
Change orientation in welcome wizard

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2281]
### Steps to reproduce
1.  Install the app from scratch
2. When welcome wizard appears, change orientation

### Current behaviour

Welcome Wizard empty

### Expected behaviour

Maybe welcome wizard should only be available in portrait.

**Comment by davigonz** [comment]
Can you please include the device in which you have noticed this? I have seen the welcome wizard in other devices in landscape mode, in tablets for example, and it works as expected.

**Comment by jesmrec** [comment]
Nexus 5X v8.1

**Comment by funthomasz** [comment]
Hello, I´ve installed the app and I´m also having this issue on Galaxy S8 with 8.0 Oreo.
Can I work on this?

**Comment by davigonz** [comment]
> Hello, I´ve installed the app and I´m also having this issue on Galaxy S8 with 8.0 Oreo.
Can I work on this?

Sure, go for it! If you have any blocker, ping us 😉

**Comment by sd1998** [comment]
@jesmrec @davigonz  @funthomasz This bug also exists on Samsung Galaxy S9+ with 8.0 Oreo.

**Comment by funthomasz** [comment]
OK, I will try to solve this and test it both on a tablet and a phone.

**Comment by funthomasz** [comment]
OK guys, solved it, now when you turn the device, the wizard doesn´t disappear and stays at the same screen. I have tested it and it works fine on both phones and tablets. I have also created a pull request.

**Comment by davigonz** [comment]
Great @funthomasz , thank you so much!!

**Comment by jesmrec** [comment]
Fixed in #2369
