### ISSUE TITLE
Android P

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2283]
Using this issue to report all stuff, comments and bugs related with Android 9 (P) to optimize oC app running over it.

Some documentation about migration to Android 9: https://developer.android.com/about/versions/pie/android-9.0-migration

**Comment by hannesa2** [comment]
my experience/comment concerning this: I did several upgrades on several apps, but the only painful was `Andorid O` with the background tasks, to P was almost compile issues and some flaky tests.
I guess apply [material components](https://github.com/material-components/material-components-android) and AndroidX causes more afford. If it's ever done here

**Comment by davigonz** [comment]
Thanks @hannesa2 for your feedback, I agree with you, Android O seemed to be harder that P, we dealt with background tasks as well.

**Comment by hannesa2** [comment]
This is the attempt to Android P as well https://github.com/owncloud/android/pull/2402
