### ISSUE TITLE
User/group share: Show <shareWithAdditionalInfo> in autocompletion of shares

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#2284]
oC users can have same displayname, only username or email is different:

![users_-_owncloud_enterprise_edition](https://user-images.githubusercontent.com/214010/44736144-bcb95100-aaee-11e8-83a4-35e4d9d97a6b.png)

This make sharing UI difficult, but oC server got a solution for this:

![settings_-_owncloud_enterprise_edition](https://user-images.githubusercontent.com/214010/44736170-d65a9880-aaee-11e8-8af8-3764900a3624.png)

![com_bjango_istatmenus_network_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0](https://user-images.githubusercontent.com/214010/44736184-dd81a680-aaee-11e8-8303-205bdfb9f499.png)

### Expected behaviour
Users with same displayname should be easier to distinguish. oC server can add `User ID` or `Email address` in brackets after the displayname

### Actual behaviour
Users with same displayname can't be distinguished

### Server configuration
ownCloud version:
10.0.9

### API

Here you can find the API responses if this feature is enabled on the oC server:
https://github.com/owncloud/client/issues/6749

**Comment by michaelstingl** [comment]
@davigonz @jesmrec Is this something easy for the 2.8.0, or better schedule for 2.8.1 or 2.9.0 ?

**Comment by jesmrec** [comment]
i would add it to 2.10.0, so current milestone is pretty full.

**Comment by davigonz** [comment]
@michaelstingl the web UI shows the additional info even after saving the share, not only when searching.

<img width="283" alt="screenshot 2019-01-22 at 19 01 29" src="https://user-images.githubusercontent.com/15261363/51555589-3bd16c00-1e78-11e9-9873-dc6940edc40d.png">

But I would say that the code included in https://github.com/owncloud/client/pull/6837/files only shows the additional info when searching, not in the list of shares after saving it.

Guess the Android app should follow the web UI approach
