### ISSUE TITLE
InstantUpload and 2 accounts: upload to a random account

### ISSUE THREAD

**Issue by Haabster** [owncloud/android#2287]
### Actual behaviour
I have two accounts setup on my phone. This works great. I also have InstantUpload enabled, which works. Only when uploading my pictures and videos, the app does upload two a "random" account (probably the one I used last). 

### Expected behaviour
Select the account to which InstantUpload should upload, so it always uploads to the same, desired account. 
 
### Steps to reproduce
1. Enable two owncloud-accounts in the app;
2. Enable instant upload;
3. Upload some pictures;
4. Change account, take some new pictures. 

Can this problem be reproduced with the official owncloud server?
Have not tried. 

### Environment data
Android version: 
8.0.0

Device model: 
OnePlus 3 (A3003)

Stock or customized system:
Stock (OxygenOS 5.0.5)

ownCloud app version:
2.8.0

ownCloud server version:
? 

### Logs
Will post when requested, does not appear relevant to me (not being a developer).

**Comment by davigonz** [comment]
Hi @Haabster, thanks for reporting this, camera uploads for each account is not implemented yet so the behaviour you describe is what we expect taking into account the current implementation. 

Anyway, we will implement this in the future, not sure exactly when, but is in our mind.

**Comment by abelgardep** [comment]
Fixed: https://github.com/owncloud/android/issues/3166

You can check some screenshots about it here: https://github.com/owncloud/android/pull/3226

Feel free to reopen if it does not fit your requirements 👍
