### ISSUE TITLE
Commit hash in settings

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2292]
Including the commit hash in the settings, near to the version number would be very useful in terms of testing, so you know exactly which the installed version is. 

This is something already available in both ios and ios-neo apps.

**Comment by sd1998** [comment]
@jesmrec I would like to work on this.

**Comment by sd1998** [comment]
@jesmrec Here the commit hash is the Github commit hash? And that has to bee added near the version no. on the android app. But the hash would keep on changing as and when more commits will be made so how will the hash get updated in the app?

**Comment by jesmrec** [comment]
yes, this is the github commit hash. The hash commit goes together with the installed version. So, when you install a new version, the commit is updated to the new one (only in this case afaik). The commit should be added in building time.
