### ISSUE TITLE
Pattern lock asked very often after disabling fingerprint lock

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2293]
Steps to reproduce

1. Enable pattern lock & fingerprint
2. Close the app and open it again, in order to be asked the fingerprint
3. Enter correct finger to unlock the app
4. Go to Settings and disable fingerprint, keeping pattern lock enabled

Current: If you open again the settings view, or go back to the file list, or download a file and go back (maybe more actions), the pattern lock is always asked, sometimes twice

Expected: pattern lock is only asked when you leave the app and open it again

Device: Nexus 6P v7
Server: 10.0.9

@sd1998 you developed the feature, maybe you can have a look.

**Comment by sd1998** [comment]
@jesmrec Yes, I will look into it.
