### ISSUE TITLE
Buld failed - Android Studio

### ISSUE THREAD

**Issue by stupidly-logical** [owncloud/android#2299]
### Actual behaviour
-Build fails with message : Failed to find byte code for android/hardware/fingerprint/FingerprintManager$AuthenticationCallback

### Expected behaviour
-Build must be successful and should install apk on connected device
 
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Not sure.

### Environment data
Android version: 5.1.1

Device model: 
SM-E700H
Stock or customized system:
Stock
ownCloud app version:
20800000
ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hi @stupidly-logical , thanks for reporting this, please try to disable Instant run by going into Preferences > Build, Execution, Deployment > Instant Run and disable it.

**Comment by stupidly-logical** [comment]
Thanks. It worked. Closing.
