### ISSUE TITLE
Log in button only enabled when credentials are typed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2302]
Currently, the login button is enabled in the momento the URL is typed. The point is that we can avoid error messages like this one: 

![oct-02-2018 13-34-30](https://user-images.githubusercontent.com/14894746/46346324-f0d0e600-c647-11e8-92d8-95d8f1069477.gif)

only is enabled in the moment both username and password are not empty, for basic auth. Other auth methods (OAuth2, saml) enables the button in the moment the URL is validated.

**Comment by sd1998** [comment]
@jesmrec I would like to work on this.
