### ISSUE TITLE
Existing image files clutter logfile

### ISSUE THREAD

**Issue by sciurius** [owncloud/android#2310]
I have a vast amount of pictures in the storage/emulated/0/DCIM/Camera/ folder.

For each of them, a log entry (3 lines) is written every couple of minutes.
This quickly fills the log file, and makes it hard to spot other problems.

**Comment by sciurius** [comment]
Yes, exactly. Thanks for looking into this!

**Comment by jesmrec** [comment]
Logs have been reduced to avoid log flooding (2.21).

Feel free to reopen in case you disagree
