### ISSUE TITLE
Open xls-files or doc-files with Docs to Go

### ISSUE THREAD

**Issue by alexanderbruns** [owncloud/android#2319]
### Actual behaviour
- I open a file with owncloud-client and it is opened in "Doc to Go". I have an non-root device Samsung Galaxy S7 with Android 8. When I want to safe the file, it is locally safed to a folder. It is not sofed to a folder of owncloud so the file in owncloud is not uploaded and updated.

### Expected behaviour
-I want to open the file in "Doc to Go" and then the changes should be automatically recognized by Owncloud Client and Uploaded to Owncloud-Server,
 
### Steps to reproduce
1. Open Owncloud-client on Android Smartphone
2. select an office-document like an xls-file
3. open it. and try to get the changes saved automatically to owncloud.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

Yes, it does not belong to the server, its an client-issue

### Environment data
Android version: 8.0.0

Device model: Samsung Galaxy S7

Stock or customized system: Samsung Expereince Version 9.0, Kernel 3.18.91

ownCloud app version: 2.8.0

ownCloud server version: 10.0.9

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hi @alexanderbruns , what you describe here is the **available offline** feature and is already implemented, can you try the same steps after setting that file as available offline, is the next option to download file and you will see the next icon after pressing it.

<img src="https://user-images.githubusercontent.com/15261363/47155988-5bd81900-d2e6-11e8-8289-052f79f09d4f.png" width=50%>

**Comment by davigonz** [comment]
> It is not saved to a folder of owncloud so the file in owncloud is not uploaded and updated.

This is the point, the files to synchronize should be in the ownCloud folder, the changes can not be automatically recognized by the ownCloud Android app if you save the files in any folder in internal storage.

**Comment by alexanderbruns** [comment]
But the folder in that owncloud temporary downloads the file for opening by Docs to go is not readeable by Docs to go on a non-root device. In my old Phone runnin cyanogenmod that was no problem. But on a stock-rom it is no longer possible for me to open files downloaded temp by owncloud-client with docs to go to edit and safe back to owncloudclient automatic upload.

In Dropbox this is no problem, because  Docs to go supports naturally dropbox itself. But for Owncloud and docs to go is no longer working together on a non-root-phone. Same with owncloud and microsoft excel mobile.

**Comment by alexanderbruns** [comment]
Hi exact the same problem still exists. Does nobody else use owncloaud to edit xls-files with an office-tool on an android smartphone?

**Comment by michaelstingl** [comment]
@alexanderbruns with version 2.11.0. the ownCloud Android app supports the Document provider (**Downloads** in Android 7 and 8 or **Files** in Android 9+):
https://owncloud.org/news/owncloud-android-2-11-0/

Document provider is the recommended way, could you give it a try? In case you encounter any issues, please open a new issue.
