### ISSUE TITLE
App crashes creating private link

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2322]
### Steps to reproduce
1. Install the app
2. Create a private share

### Actual behaviour
App crashes. When app restarts, there is an authentication error and user needs to enter credentials again

### Expected behaviour
Private link created and life goes on

Reproducible in `master` branch (2.9.0-beta2) 
Not reproducible in 2.8.0

**Comment by PVince81** [comment]
it seems the private link was created already, it just did not appear in the app.

**Comment by jesmrec** [comment]
Fixed. Will be released in 2.9.0
