### ISSUE TITLE
Re-enter password while creating share link

### ISSUE THREAD

**Issue by sd1998** [owncloud/android#2329]
### Actual behaviour
The password option in the create share link options request the user to enter the password once.

### Expected behaviour
The user should be asked to re-enter the password while creating the share link which happens in case of setting a pattern lock or passcode lock on the app.
 
### Steps to reproduce
1. Select a file or a directory
2. Select the share option from the toolbar
3. Select the option to create a share link
4. Enable the password option in the dialog

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes.

### Environment data
Android version: 8.0

ownCloud app version: Version 2.9.0-beta.2

**Comment by davigonz** [comment]
It won't be implemented, reasons in https://github.com/owncloud/android/pull/2352
