### ISSUE TITLE
Wrong apk name with version 2.9.0

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2342]
I'm on master with commit https://github.com/owncloud/android/commit/bd07b13db15e2c59f3694749c98ff39e9bc08b2e and I see during build release apk a wrong filename

> find . -name *.apk
> ./owncloud-android_2.7.0-release.apk

Because PR are not merged (see https://github.com/owncloud/android-library/pulls) I change to mode to just create issues and not solve the problems with PR to save my time

**Comment by jesmrec** [comment]
i'm not sure what you mean. apk files are filtered in `.gitignore`, so this kind of files are not allowed to be synced via git.

**Comment by hannesa2** [comment]
Sorry my fault, in project root, there was an old artifact, and when you search 
`find . -name *.apk` it doesn't search subdir, so it only finds only one, and I assumed it's currently created apk

`find . -name "*.apk"` brings light into the darkness and I found the other, currently created, apk's
