### ISSUE TITLE
Cannot login to owncloud account

### ISSUE THREAD

**Issue by frankaschmitt** [owncloud/android#2344]
### Actual behaviour
- android owncloud client suddenly empty owncloud folders (on three different android devices since yesterday 07.11.18) therefore deinstalled and re-installed owncloud on one of them
- type in owncloud-address (https://mycloudname.myqnapcloud.com/owncloud) 
- one time asking if self-signed certificate is okay (yes)
- then getting error message "Die lokale Kopie konnte nicht umbenannt werden. Versuchen Sie es mit einem anderen neuen Namen."
- no way out of this.
- the window to grant permission for owncloud to access the file system is in the background!! (but even with access granted no other result)

### Expected behaviour
- after connection is established, user should be prompted for username and password
 
### Steps to reproduce
1.  install owncloud (via google play Store or via F-Droid, same result)
2.  start owncloud
3. type in address and press arrow-button
4. get error message

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

No. With this account the login is working without error message, files and folders are shown

### Environment data
Android version:
Android 7.0 and EMUI-Version 5.0.3

Device model: 
Huawei P9 lite 

Stock or customized system:
stock

ownCloud app version:
2.9.0

ownCloud server version:
8.0.4 (stable)

### Logs

no errors logged on the owncloud server

**Comment by jesmrec** [comment]
@frankaschmitt  Could you upgrade to 2.9.1?

**Comment by jesmrec** [comment]
i also noticed you are using a server version 8.0.4. From ownCloud 10, new endpoints were developed to make the dialog with mobile and desktop clients. From 2.9, this newer endpoints are the ones we are going to support, so, i would recommend and encourage you to upgrade your server to such version, so older ones are deprecated and not supported from the Android app.

**Comment by frankaschmitt** [comment]
thanks from quick response. 

QNAP provides only version 8.0.4 for their NAS in their App-Store. I am not sure if I can install a newer version.

2.9.1 - how to get that version?   I can install from playstore (2.9.0) or from F-Droid (2.9.0 with beta 1 + 2)

**Comment by jesmrec** [comment]
2.9.1 is already available in Play Store

i edited my comment above. oC 9 is also supported

**Comment by hanibalp** [comment]
Hello,
with new version 2.9.1 I still have the same problem 
"The local copy couldnt be renamed. Try it with a different new name."

**Comment by michaelstingl** [comment]
> with new version 2.9.1 I still have the same problem

@hanibalp what version of ownCloud server version are you using?

**Comment by jesmrec** [comment]
could you send us a test account in your server to apps@owncloud.com?

**Comment by hanibalp** [comment]
I don't know :( I'm only user. I don't understand anything of this 
tings. I see this on my desktop ownCwould

Поздрави,

Ани

------ Original Message ------

**Comment by jesmrec** [comment]
@hanibalp you can send us the URL of your server

**Comment by hanibalp** [comment]
https://78.154.6.77/pkg/ownCloud/

User:test
Pass:test

Поздрави,

Ани

------ Original Message ------

**Comment by jesmrec** [comment]
@hanibalp thanks, but it is better to send to the mail i posted above (apps@owncloud.com). This is an open forum and it is not a good idea to put credentials. You should delete them 

I checked your server, you are using ownCloud 7, a very very old one. You have to update to 9.1 or newer

**Comment by hanibalp** [comment]
does not allow me to make upgrades to a higher version :(

**Comment by jesmrec** [comment]
@hanibalp , if you can not upgrade your server version, your option is using Android app version 2.8.0.

Check the following steps: https://github.com/owncloud/android/issues/2348#issuecomment-437841784. If you have any problem, question or whatever, reopen this issue, or send us an email to apps@owncloud.com

**Comment by heppel** [comment]
Just waiting a few hours fixed the issue for me. Probably something expired from some cache. Or some cleanup task finally did it's work. Or ...

**Comment by DEvil0000** [comment]
same issue for me. Have a QNAP and can not update to owncloud newer then v8. The new android app however (which was even unfree) does not work with the old server version.

**Comment by michaelstingl** [comment]
@DEvil0000 I explained the background here:
https://github.com/owncloud/android/issues/2433#issuecomment-460041199

You'll also find steps how to go back to the old app version using F-Droid.

**Comment by DEvil0000** [comment]
@michaelstingl I would be fine with installing older versions but f-droid does not have older ones then 2.9.3 anymore.
So where can I get a old version?

**Comment by jesmrec** [comment]
To get older versions:

1. Install F-droid app from http://f-droid.org
2. In F-droid app, tap on “Settings”, placed in the bottom bar.
3. Tap on “Repositories”
4. Enable the option “F-Droid Archive”
5. Go back to the F-Droid main screen, and search for ownCloud by using the lens icon on the floating button
6. Scroll down, and in “versions”, get the 2.8.0 version

**Comment by DEvil0000** [comment]
Thanks. Thats working.
The archive was missing and you can not access the archive properly on the website anymore.
