### ISSUE TITLE
point to obsolte way to handle version

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2346]
During rebase I found this obsolete way to handle version. But I recommend first remove this Eclipse  
stuff https://github.com/owncloud/android/pull/2076 (this PR is on hold)
https://github.com/owncloud/android/blob/57a37e79093b54f62219a1afc77fe074c7e84297/build.gradle#L100

This is just a informer to not forget

**Comment by jesmrec** [comment]
Done
