### ISSUE TITLE
after latest update app stopped working.

### ISSUE THREAD

**Issue by dirkbroekstra** [owncloud/android#2348]
### Actual behaviour
-Tell us what happens

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by dirkbroekstra** [comment]
> -Tell us what happens

after deleting and reinstalling app and entering owncloud URL message from app reads:  ¨Lokaal kopie kon niet worden hernoemt¨ in English:  ¨Local copy could not be renamed¨

I tested with url: https://demo.owncloud.org it works fine.

I checked the version on my server. It appears to be 7.04 I cannot change this version as it is embedded in a clearOS  seversystem

**Comment by dirkbroekstra** [comment]
Is it possible to receive a link to download the old version apk?

**Comment by ap0n** [comment]
Same problem here. It's very frustrating not being able to access my data.

**Comment by davigonz** [comment]
Hi @dirkbroekstra , @ap0n , first of all sorry for the inconvenience. As you already probably know, ownCloud doesn't give support to server versions lower than 10.x and with the recent update of the ownCloud app for Android, we are not giving support to server versions lower than 9.x.

Therefore, we strongly recommend you to update to most recent versions since you will might find more compatibility issues from now on and new versions includes a bunch of interesting features. 

> I checked the version on my server. It appears to be 7.04 I cannot change this version as it is embedded in a clearOS seversystem

For your case @dirkbroekstra , I would get in touch with clearOS support to ask for more information about how to update your server.

If what I suggested above is not finally working for you, please write to apps@owncloud.com and we will look for another solution.

**Comment by ap0n** [comment]
Hi @davigonz . It is very difficult for me to upgrade my owncloud server as it is also embedded in my NAS system; I don't have the time to dig into it anyway.
Unfortunately I had to switch to other apps that provide the same functionality as yours and still support older server versions (and webdav).
In any case, thanks for your reply.

**Comment by dirkbroekstra** [comment]
I found this as a temperature solution: https://m.apksum.com/app/owncloud/com.owncloud.android

**Comment by dirkbroekstra** [comment]
@davigons
Thanx for your reply .

I will need to upgrade my clearOS system somewhere in the future. So the problem will be solved then, hopefully.

Best regards.

**Comment by jesmrec** [comment]
Version 2.9 of Android app only supports server version 9.x and newer. I encourage you to upgrade your server version, and any question or problem about it, check it in the open forum or post there whatever you need: https://central.owncloud.org/

If you don’t have the choice to upgrade your server, you can get the 2.8.0 version (the latest Android version that supports old server versions) from F-Droid. To get it, follow these steps:

1. Install F-droid app from http://f-droid.org
2. In F-droid app, tap on “Settings”, placed in the bottom bar.
3. Tap on “Repositories”
4. Enable the option “F-Droid Archive”
5. Go back to the F-Droid main screen, and search for `ownCloud` by using the lens icon on the floating button
6. Scroll down, and in “versions”, get the 2.8.0 version

Let us know any problem or suggestion you have.

**Comment by tpluscode** [comment]
@jesmrec I'm pretty sure the problem goes beyond jus the server version.

I've been happily using ownCloud app with two providers:

1. https://my.owndrive.com/ - running version OwnCloud 12
2. https://cloud.woelkli.com/ - running Nextcloud 13

Here's what happened to me after latest update:

1. I noticed I am unable to upload to OwnDrive. Notification simply says `Folder error`
1. I refreshed this account and all folders disappeared from the app
1. I tried uploading to Woelkli - same problem
1. I cannot log in to either of them, saying `Precondition failed`

Please do something about it. Would you like me to open a new issue. I guess you have a few already for this release 😠

**Comment by michaelstingl** [comment]
> 1. https://my.owndrive.com/ - running OwnCloud 12

@tpluscode seems https://my.owndrive.com/ is also not an ownCloud server. The ownCloud Android app got tested only with supported ownCloud servers.

**Comment by jesmrec** [comment]
that's it... latest ownCloud version is 10. ownCloud12 comes not from official sources.

**Comment by ap0n** [comment]
@jesmrec you saved the day, thanks! I downgraded owncloud app via (F-droid) and it works perfectly.

**Comment by jesmrec** [comment]
2.9.3 version released, fixing this problem. If the problem persists, feel free to reopen.

**Comment by jonas740** [comment]
I have this issue with a fresh install. latest version of everything.

Set it all up today and not working. A cloud service that isnt reliable ?

**Comment by jonas740** [comment]
@jesmrec owncloud 10.0.10 (stable)

Tried latest owncloud app and also the owncloud.de app. 

Same problem on both. Cant really figure out why this error comes up. The owncloud server is a fresh install.

**Comment by jesmrec** [comment]
is it posible to send us a test account to apps@owncloud.com? so, we can test directly what's going on.

**Comment by jonas740** [comment]
@jesmrec Sure.

You mean that you want me to create a user for you to my owncloud page? Or what is it that you want. 

I think its what you want so ill fix that and mail you this evening.

**Comment by jesmrec** [comment]
this is, a user so i can login in your server and check what happens

**Comment by jonas740** [comment]
@jesmrec

I sent you a mail to apps@owncloud.com with log in details.

**Comment by jesmrec** [comment]
i check your server test account, from my side is working: i was able to login and perform basic actions (create folder, upload, download, browse, share).

Maybe database became corrupt or internal error happens. If you can try to remove the account, or event, reinstall the app and check, we can discard the problem is that one.

Just for clarification:

- Which Android version does your device use?
- Is app version 2.9.3?

**Comment by jonas740** [comment]
@jesmrec haha what did you do? Because now it worked for me to log in with my account.

How strange is this? 

And yes it is version 2.9.3

**Comment by jonas740** [comment]
Very very strange that it all of a sudden just works. Could something have happened after i created that user for you or something like that.

**Comment by jesmrec** [comment]
diffucult to say... i will close again. If you notice something weird, please reopen o send a mail to apps@owncloud.com
