### ISSUE TITLE
"Nothing in here. Upload something!" after app update

### ISSUE THREAD

**Issue by Teasydlp** [owncloud/android#2358]
### Actual behaviour
- After app update, my android app is loading for about 10 seconds and reports after that "Alles leer. Laden Sie etwas hoch!" (Nothing in here. Upload something!). There were no changes to the server for weeks. The app worked fine before the update.

Close/restart app does not help.
Restart smartphone does not help.
An android tablet shows the same behavior.

### Expected behaviour
- Showing my folders.
 
### Steps to reproduce
1. start app
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

No. The testserver shows folders the way it should be.

### Environment data
Android version: 8.0.0, patch 1. Oct. 18

Device model: Samsung S7 edge

Stock or customized system: Samsung Experience V9.0

ownCloud app version: 2.9.1

ownCloud server version: 10.0.10.4

**Comment by davigonz** [comment]
Hi @Teasydlp , thanks for reporting this, are you using a username with spaces?

**Comment by Teasydlp** [comment]
> Hi @Teasydlp , thanks for reporting this, are you using a username with spaces?

Yes, I do.

**Comment by davigonz** [comment]
> Yes, I do.
This is a duplicated of https://github.com/owncloud/android/issues/2347 then, we have already fixed this issue and will be out in a new version (2.9.2) next week, I will close this, stay tuned.
