### ISSUE TITLE
After update no files are shown

### ISSUE THREAD

**Issue by RomanKarwacik** [owncloud/android#2367]
### Actual behaviour
-Tell us what happens
In the "Alle Dateien" (All files) Tab, no files are shown, and the message "Alles leer. Laden Sie etwas hoch!" (All empty. Upload something!) is shown. I can upload files, but after reopening the app, the file also disappears (But is uploaded succesfully, as can be verified on other platforms).

### Expected behaviour
-Tell us what should happen
All my files should be shown and accessible, like in Version 2.9.1.

### Steps to reproduce
1. Update from Version 2.9.1 to 2.9.2 (Or completely wipe the app)
2. Open app and update account.

###Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No.

### Environment data
Android version: 7.1.2

Device model: Motorola G4

Stock or customized system: LineageOS 14.1

ownCloud app version: 2.9.2

ownCloud server version: sciebo 10.0.10

**Comment by RomanKarwacik** [comment]
Probably due to https://github.com/owncloud/android/issues/2365 , as the accounts have @ signs in the username.

**Comment by davigonz** [comment]
> Probably due to #2365 , as the accounts have @ signs in the username, though it works on 2.9.1 and not on 2.9.2.

Thanks @RomanKarwacik for reporting this issue. In 2.9.2 we fixed some bugs with usernames containing spaces and due to that fix, accounts with @ character stop working, we have already developed the solution for all the cases and should be out at the beginning of next week within 2.9.3, stay tuned. 

I will close this as duplicated of #2365, please follow up there.

**Comment by davigonz** [comment]
Hi @RomanKarwacik , we've just released 2.9.3 to fix the problem you describe, please [download it via PlayStore](https://play.google.com/store/apps/details?id=com.owncloud.android), try it out and give us your feedback, thanks!

**Comment by RomanKarwacik** [comment]
It works now again, thank you!

**Comment by moshpirit** [comment]
It doesn't work with 2.9.3 (F-droid) on my Android 8.0.0

**Comment by moshpirit** [comment]
Yes, a space

**Comment by davigonz** [comment]
> Yes, a space

Hmmm, weird... where do you have the space in the username? Middle, at the beginning, at the end?

**Comment by moshpirit** [comment]
in the middle.

**Comment by moshpirit** [comment]
It works with Nextcloud if it helps

**Comment by davigonz** [comment]
> in the middle.

Could you write here your username or a similar one with the same format? Thanks

**Comment by moshpirit** [comment]
Alberto Aru

**Comment by davigonz** [comment]
> Alberto Aru

@moshpirit I have downloaded ownCloud 2.9.3 for Android from F-Droid as you did and tried with the user `Alberto Aru`. The login works properly and folder browsing as well. 

[<img src="https://user-images.githubusercontent.com/15261363/50898786-7bc43800-1410-11e9-9d10-da8549d3c3f5.gif" width="400px"/>](https://user-images.githubusercontent.com/15261363/50898786-7bc43800-1410-11e9-9d10-da8549d3c3f5.gif)
