### ISSUE TITLE
UI glitch in eye icon used to show/hide the password when sharing a file publicly

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2374]
### Actual behaviour
The eye icon used to show/hide the password of a public link  is almost not visible due to the white color used. This eye icon is the same resource that we use in the login view and it needs to be white, so changing the color here will not solve the problem, use new resource maybe?

[<img src="https://user-images.githubusercontent.com/15261363/49168190-48818a00-f337-11e8-9b82-477bb388ddba.png" width="300px"/>](https://user-images.githubusercontent.com/15261363/49168190-48818a00-f337-11e8-9b82-477bb388ddba.png)

### Expected behaviour
Eye icon should appear in grey color. 

[<img src="https://user-images.githubusercontent.com/15261363/49168488-e2e1cd80-f337-11e8-8040-8d2bab4d668e.png" width="300px"/>](https://user-images.githubusercontent.com/15261363/49168488-e2e1cd80-f337-11e8-8040-8d2bab4d668e.png)
 
### Steps to reproduce
1. Long press a file
2. Press share option
3. Create new public link
4. Toggle Password option 

Can this problem be reproduced with the official owncloud server? Yes
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 7.0

Device model: Nexus 5

Stock or customized system: Stock

ownCloud app version: 2.9.3

ownCloud server version: 10.0.10

**Comment by sd1998** [comment]
@davigonz I will implement this instead of #2329

**Comment by sd1998** [comment]
@davigonz I have fixed the issue.
