### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by sebascasti** [owncloud/android#2378]
Hi, i've reinstalled my phone and now i can't login into the app. It show "Precondition failed". For two years i was using this app on this phone just perfect.

Can this problem be reproduced with the official owncloud server? Your demo server works Ok.
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 7.0

Device model: Moto X Pure

Stock or customized system: stock

ownCloud app version: latest, it was intalled today

ownCloud server version: no idea, i'm using https://my.owndrive.com
The server is a free server. I cannot give you a server-side log. Is there any way i can give you an app-side log?
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
```
$ curl https://my.owndrive.com/status.php
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"11.0.2.7","versionstring":"11.0.2","edition":"","productname":"OwnDrive"}
```

11.0.2.7 isn't a legit ownCloud server version and seems to be not supported by the latest versions of the ownCloud iOS app.
