### ISSUE TITLE
Wrong preview images

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2389]
I'm not sure if this is the right repo, anyway at least I get the hint where to post it.

I use Owncloud X and I see in 
* website _wrong_ preview images with **wrong** big images 
* Android _wrong_ preview images but **right** big images 

so I tried to rebuild it but to be honest I don't know how.

I tried this but without success
```
files
 files:checksums:verify 
 files:cleanup           
 files:scan   
``` 

any clue how to get rid of it ?

**Comment by hannesa2** [comment]
Should I make a video to see the non working behavior. I see no purpose to go ahead here, except a afford on my side.
You should simply believe me.

The only way I see is to solve it by my own, and I don't want to disturb my installed prod version. So I need a debug version. Cool https://github.com/owncloud/android/blob/84c03ba109171e2c558dc5818225bdeac1a5534a/build.gradle#L189 at least there is a debug version packagename, but to differ from prod version on GUI I want a special icon, but unfortunately I can't specify a debug icon, because I can't use `debug` directory to specify it.
Why ? https://github.com/owncloud/android/pull/2076 (open since one year) has no measurable progress, this PR would enable this nice-to-have feature

![image](https://user-images.githubusercontent.com/3314607/49674563-b4b86800-fa72-11e8-9448-aba310cdb3d5.png)

btw I will rename my picture folder by shell command and want to do a `files:scan` maybe it will do the job

**Comment by hannesa2** [comment]
the most afford in this repo is to point all of you to non-merged PR's and do rebase on non-merged PR's. -sad-

But all depends on an update of project structure. I see a deficit on the amount of merger and a blocking git workflow.
You should never block volunteers who invest there lifetime in this repo

**Comment by michaelstingl** [comment]
> Should I make a video to see the non working behavior.

I just don't understand the issue enough yet. Easiest would be you know the instructions how to reproduce (using screenshots, video and example images), and I could try to debug server and app. If it's not easy to reproduce we'd need to find other ways.

**Comment by hannesa2** [comment]
If you find it helpful, here it is.
you see the wrong preview and a click opens real image
![wrongpreview](https://user-images.githubusercontent.com/3314607/49683736-da249080-fac9-11e8-91fe-b81385537f4f.gif)

**Comment by michaelstingl** [comment]
Sounds a little bit like https://github.com/owncloud/core/issues/23193

Workaround could be to remove `data/<username>/thumbnails` (from https://github.com/owncloud/core/issues/23193#issuecomment-223416964)

@DeepDiver1975 any idea why previews (probably on the server) doesn't match the original images? What would be your recommendation to clean them up? occ command?

**Comment by hannesa2** [comment]
great `Workaround could be to remove data/<username>/thumbnails` did the job !
But in my prod version, I've to clean data to get rid of woing thumbnails.
What's about a menu in preferences to delete cached data ?
The advance is, I've not to relogin and search for my damn password again
