### ISSUE TITLE
Feature Request: flickr style thumbnail view of images

### ISSUE THREAD

**Issue by PartisanEntity** [owncloud/android#239]
It would be great if there could be a choice of various "views" for images/image folders.

A flickr style view for example, showing thumbnails of images.

**Comment by davivel** [comment]
This is scheduled in the current sprint, as also tagged in the PR #731

**Comment by MTRichards** [comment]
We need some way to see that the file is downloaded. Can we bring back the green arrow? If not the green arrow, something similar - this information is important for the end user to see.

**Comment by tobiasKaminsky** [comment]
@MTRichards There is a long discussion in this issue here. And @jancborchardt said that it is not needed as there (soon will) be a thumbnail no matter if the file is downloaded (then it is generated) or not downloaded (then only the thumbnail will be fetched).
As you can see in https://github.com/owncloud/android/issues/239#issuecomment-55918599 I already had the green arrow.

**Comment by MTRichards** [comment]
Thanks @tobiasKaminsky . By the way, great work here I really like the improvements you have been making to the app. Just wanted to say that to you, sometimes thumbs up gets lost as we focus on the issues.

As for the download state - knowing if a file is local on the device or not is really important - think getting on an airplane to make some changes to a file. Does this change also remove the download arrow from non-images, or just from images?

**Comment by tobiasKaminsky** [comment]
@MTRichards Thank you for your positive feedback, which I really appreciate  :)

You are right, that this is an important information. But please talk to @jancborchardt as he decided to remove this green arrow.
In "grid view" there is no arrow both for images and no images.
Sooner or later there will be a navigation drawer which lets you switch between offline and "all files" view. Would this be sufficient for your case?

**Comment by MTRichards** [comment]
Lets wait until Jan is back, and then I will discuss with him.
@jancborchardt

**Comment by jancborchardt** [comment]
As far as I remember we removed the green arrow because the thumbnail showing up was indicator enough. Now that images can have thumbnails regardless if they are on the device or not, we need the indicator back. Sorry for the confusion. :)

**Comment by rperezb** [comment]
thanks @jancborchardt !
Just to be clear, in the case that a file is downloaded and favorite, both indicators will be shown, at least, for the moment.

**Comment by purigarcia** [comment]
what about files share by link?
And when there are files downloading inside a folder? In android, there is a yellow arrow when that it's happening
@jancborchardt ?

**Comment by jancborchardt** [comment]
Everything should behave the same way as in the list view.

**Comment by masensio** [comment]
@jancborchardt 
I've activated the status icons in grid view.
I have two options:
![screenshot_2015-01-27-11-41-48](https://cloud.githubusercontent.com/assets/3862330/5918312/9e1cc4ae-a627-11e4-8a10-86a49bfd0034.png)
![screenshot_2015-01-27-13-19-49](https://cloud.githubusercontent.com/assets/3862330/5918311/9dfc788e-a627-11e4-85ff-bde99c7c6fd9.png)

Which of them do you prefer? or Do you have in mind other different option?

**Comment by jancborchardt** [comment]
Having them all on the right (second solution) is way nicer. :) Otherwise the icons are all over the place. Thanks!

**Comment by tobiasKaminsky** [comment]
The only problem could be that the chain icon (shared) is hardly visible on dark images.

**Comment by enoch85** [comment]
Make the icons gray?

**Comment by joeplus** [comment]
Adding a white-semi transparent overlay on the right or bottom side?

![white_overlay](https://cloud.githubusercontent.com/assets/7793652/5942843/a508afbe-a71a-11e4-8c08-10617c4857a9.png)

**Comment by jancborchardt** [comment]
Just give the Sharing icon a white outline, like the star and download icon.

**Comment by tobiasKaminsky** [comment]
@jancborchardt that is exactly the same I wanted to suggest since ~20 hours, but I was too busy :/

**Comment by davivel** [comment]
This is finally merged in ```develop```, and will be available soon in the release 1.7.0.

Thanks everybody for the hard work in this feature, including all the ideas and comments, and specially to @tobiasKaminsky for doing most of the programming. This is an a

Please, use new issues for proposals to improve still farther the feature. This issue is already long enough.

**Comment by jancborchardt** [comment]
@tobiasKaminsky rocks! :rocket: :guitar: :)
