### ISSUE TITLE
Android X

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2399]
https://github.com/owncloud/android/blob/ef2ccbea0ee76c8b0b99d21c4225e9b9607dc9fe/build.gradle#L21
I would not update here to 28, immediate to AndroidX is the way to go

**Comment by davigonz** [comment]
Yes @hannesa2 , we will start to migrate to Android X dependencies via #2351

**Comment by hannesa2** [comment]
Android X needs Android P https://github.com/owncloud/android/issues/2283
I've to update 

<img width="209" alt="image" src="https://user-images.githubusercontent.com/3314607/50204270-808f5200-0364-11e9-8274-7715a606226b.png">

**Comment by hannesa2** [comment]
PR https://github.com/owncloud/android/pull/2402
