### ISSUE TITLE
security/snyk tool makes all PR red

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2401]
This `security/snyk` tool makes all PR red when we remove a module, please can someone fix it or remove it ?

<img width="160" alt="image" src="https://user-images.githubusercontent.com/3314607/50137702-49ee0480-029c-11e9-9df0-6e34526f9ea7.png">

@DeepDiver1975 @davigonz

**Comment by DeepDiver1975** [comment]
> This `security/snyk` tool makes all PR red when we remove a module, please can someone fix it or remove it ?

in which PR? Please post a link. THX

**Comment by michaelstingl** [comment]
@DeepDiver1975 please check this one 
https://github.com/owncloud/android/pull/2076

**Comment by DeepDiver1975** [comment]
Okay - once merged please ping me again and I'll remove that from snyk.

## Background - Why not remove right away?
This can leave the master/develop branch with vulnerabilities until the merge.

**Comment by DeepDiver1975** [comment]
I guess we can close this - objections?

**Comment by hannesa2** [comment]
The lib repo has the same issue
https://github.com/owncloud/android-library/pull/224
https://github.com/owncloud/android-library/pull/203

**Comment by hannesa2** [comment]
@DeepDiver1975
Ok, this repo has this issue any more, but it still exists in https://github.com/owncloud/android-library/pull

**Comment by DeepDiver1975** [comment]
Ping me on each PR individually after merge and I take care. THX a  lot
