### ISSUE TITLE
Travis deterministic release build

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2413]
With this line, I mentioned you don't use Travis to build release version
https://github.com/owncloud/android/blob/415f88f79051aeb9d36f1fc4217ae65a8d2527f5/owncloudApp/build.gradle#L105

I would be nice to have a deterministic build chain.
This means :

- add a tag builds automatic a release version  
- uploaded to PlayStore Alpha
- in app you can see the Travis build with commit in preferences

In my fork https://github.com/hannesa2/owncloud-android/releases I already did this
- add a tag builds automatic a release version 
- upload to Github ~~uploaded to PlayStore Alpha~~ (I'm not interested to publish an additional Owncloud app)
- in app you can see the Travis build with commit in preferences

![owncloudtravis 2](https://user-images.githubusercontent.com/3314607/50536110-49355800-0b51-11e9-809c-8f8f6ff7e0b3.gif)

I can't make a complete PR because for preparation of Travis I've not the permission.  
Here you can have an inspiration:

- Signing release on Travis  https://github.com/hannesa2/owncloud-android/commit/08edaa39c02e2e7e6a913f11e94a3684b4bf4fa5
- Show CI build https://github.com/hannesa2/owncloud-android/commit/87095414f3fc8297e3879869b6950f272c17a60c
- Upload to PlayStore with https://github.com/Triple-T/gradle-play-publisher some preparation has to be done by someone with access to Playstore to require *.p12 file and get ServiceAccountEmail

eg 

```
    play {
        track = 'alpha'
        serviceAccountEmail = System.getenv("PLAY_SERVICE_MAIL")
        pk12File = file('../signing/GooglePlay.p12')
    }
```

I could help/assist if someone is interested in complete story

**Comment by davigonz** [comment]
Thanks a lot @hannesa2 for the detailed explanation though we are thinking in using Bitrise, let's see

**Comment by michaelstingl** [comment]
We plan to use Bitrise for CI to auto-build every commit in every PR. Release builds for Play Store distribution shouldn't be build in a SaaS black box.

**Comment by hannesa2** [comment]
If it reflect in a deterministic release build Bitrise is perfect.

Btw, I read 'plan'. The (interim) Travis solution could be live in 30 minutes, if someone provides necessary files and provide variables in Travis
