### ISSUE TITLE
Display width isn't fully used on tablets

### ISSUE THREAD

**Issue by Centzilius** [owncloud/android#242]
### Expected behaviour

Item list uses full width
### Actual behaviour

Item list doesn't uses full width
### Steps to reproduce
1. Open Owncloud on a Nexus 7/Tablet
### Environment data

Android version: 4.3

Device model: Nexus 7 (2013)

Stock or customized system: Stock

ownCloud app version: 1.4 

ownCloud server version: --

![Images](https://cloud.w1r3.org/public.php?service=files&t=783b36bf8c5478355a514c805dfe56d6&download)

**Comment by davivel** [comment]
Preview of images is shown in full screen. Preview of videos and music is shown in the right panel. I don't consider a bug because that's the way it was requested in the past.

Anyway, it's the same if bug or not. If the design is not cool, it can be changed.

**Comment by rperezb** [comment]
a client has contacted us through the apps@owncloud.com mail asking us to improve the design for tablets.
It pointed out the same issue, on landcape mode on tablets it's not used the whole screen. 
The thing is that the current idea is to divide the screen on 2: list and details view; however, yes, most of the times the details view is empty (you have to select manually the details view from a file)
so....ideas?

@AndyScherzinger @owncloud/designers community?
thx!

**Comment by jancborchardt** [comment]
Well, this problem should only appear on first start of the app. On any subsequent use, the last opened folder and file should be remembered and shown.

**Comment by tobiasKaminsky** [comment]
@jancborchardt this is a new feature request by you? Then we should open a new issue for this.
(I doubt that this is useful as (at least for me) it is 50:50 between
- browsing the latest folder
- changing to another folder, which is better reachable from root folder

**Comment by michaelstingl** [comment]
no longer relevant with https://github.com/owncloud/android/issues/1890
