### ISSUE TITLE
Rename in PR#2405 broke daily transifex job

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#2420]
Rename in PR #2405 broke daily transifex job:
https://github.com/owncloud/android/blob/master/.tx/config

@davigonz please adjust to fix. (ping @tboerger to test after merge)

**Comment by davigonz** [comment]
> Rename in PR #2405 broke daily transifex job:

Thanks @michaelstingl for reporting this, the fix is already in #2421 , we will merge it asap.

**Comment by tboerger** [comment]
Solved, you can check it out at https://drone.owncloud.com/owncloud/translation-sync/342/21
