### ISSUE TITLE
Download progress bar is still visible after successfully download

### ISSUE THREAD

**Issue by hosy** [owncloud/android#2422]
### Actual behaviour
I click on a file, which is locally not available. Download view does appear and file will be downloaded.

### Expected behaviour
Progress bar should be hidden, after file was successfully downloaded (progress 100%)
 
### Steps to reproduce
1. Click on a file which is not downloaded on device
2. Download view is opened and shows download progress
3. After file was downloaded, progress bar is still visible

### Environment data
Android version:
9
Device model: 
Mi A2
Stock or customized system:
Stock
ownCloud app version:
2.9.3
ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by hosy** [comment]
![screenshot_20190110-115407](https://user-images.githubusercontent.com/736109/50970415-93b7bc80-14e1-11e9-9dcb-79f94f91c565.png)

**Comment by vikene** [comment]
Hey @hosy and @jesmrec , Can I look into this issue ?
