### ISSUE TITLE
Unable to replace a new sync url(owncloud server address) on my phone

### ISSUE THREAD

**Issue by daxiong0513** [owncloud/android#2425]
### Actual behaviour
- I get owncloud client app from Google Play, the latest one,2.9.3 (2018.Nov updated)
before that, I created an owncloud server url monthes ago,it is a local network url. Just for testing some server feature.
Now, I would like to use an official server url/address to replace old one. 
It is failed. Now it shows the first page ("please type your server address________"),
and once I type the correct url, it will shows the error message "rename local fail msg"

### Expected behaviour
- I expected if the new server url is connected successfully, and app will show next pages to guide me type user name and password, and create new sync folder.
 
### Steps to reproduce
I am not sure the details steps to duplicate that. But I do remember, before that, there is a local network test url, it works fine, and I would like to replace new url in that sync pages(it has folders, account info, user name, server url info), but it seems failed that moment, so I tried to uninstall app and re-install app, clear caches etc. They didn't help on this. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, I can access that official owncloud server url via browser-webpage, and Mac OS app.
Only failed on Android app. (I didn't use WinOS and iOS clients)

### Environment data
Android version: Android 9.0

Device model: Mi - Mix 2S

Stock or customized system: MiUi 10

ownCloud app version: 2.9.3

ownCloud server version: 8.0.2

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by davigonz** [comment]
Hi @daxiong0513 , thanks for reporting this, is the official server url/address you are using accessible via web for example? Thanks

**Comment by daxiong0513** [comment]
> Hi @daxiong0513 , thanks for reporting this, is the official server url/address you are using accessible via web for example? Thanks

Hi Davigonz,
Thank you for help. 
Yes, that link can be accessed via web. I can use chrome browser to open that url/address anywhere.

**Comment by davigonz** [comment]
@daxiong0513 are you using special characters in your username?
