### ISSUE TITLE
Notch support

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2426]
### Actual behaviour
- Notch appears over additional account icon,  making it not show well.

[<img src="https://user-images.githubusercontent.com/15261363/51530449-3dc90a00-1e3b-11e9-82d7-01d87c671683.png" width="300px"/>](https://user-images.githubusercontent.com/15261363/51530449-3dc90a00-1e3b-11e9-82d7-01d87c671683.png)

### Expected behaviour
- Icons for additional accounts should not be covered by notch.
 
### Steps to reproduce
1. Login in the app
2. Include additional account
3. Open side menu

### Environment data
Android version: 9

Device model: Google Pixel 3 XL

Stock or customized system: Stock

ownCloud app version: 2.9.3

**Comment by jesmrec** [comment]
Done!
