### ISSUE TITLE
Can not sync shared  group calendars with mobile device. 

### ISSUE THREAD

**Issue by freestate** [owncloud/android#2427]
### Actual behaviour
- I don't get appointments on my mobile device. Icsx5 works for my web calandar. Appointments that are from a Group on my OwnCloud do not show up. 

### Expected behaviour
- A new Calandar in davx5 that syncs with my mobile device. 
 
### Steps to reproduce
1. Add Group on your OwnCloud and add users
2. Make some calandar entrys
3. Sync cal of some user from group

### Not tested 
Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 8.0.0

Device model:  Huawai RNE-L21

Stock or customized system: Stock

ownCloud app version: 2.9.3

**Comment by davigonz** [comment]
Guess this is duplicated of https://github.com/owncloud/android/issues/1871, please follow up there.
