### ISSUE TITLE
Upgrade min version (currently API 14 - Android 4.0)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2431]
Currently, the min version supported by the app is 4.0:

https://github.com/owncloud/android/blob/980d9c73a953e708a6798aa5dc0164a21897c17a/owncloudApp/build.gradle#L66

Android 4.0 (and older) are used by a residual amount of users:

https://developer.android.com/about/dashboards/

We can not forget that there are also some features not supported for such version, f.ex. the ones that take advantage of the Jobs (available from API 21).

Since Android 4.4 keeps ~7% , it is a possibility of `minSdkVersion`.  Other option is going directly to 5.0

Your ideas are welcome

**Comment by hannesa2** [comment]
Without wasting any second I would go to 19. You loose 3 % of users, and yes that's true, they will stay at Owncloud 2.9.3 for ever (till they buy a new device)

Switching to 21 is a step, which I would do, if in development an annoying issue appears and an easier solution is going to 21 helps a lot. It's a trade off between afford and advantage
Then the next 7% stay at Owncloud 2.x.x for ever (till they buy a new device)

Sorry to all owner of an old devices, sometimes you stay with old hardware and stay with software version too. Even WindowsNT 4.0 doesn't got USB support :-)

**Comment by jesmrec** [comment]
Already done as part of #2466
