### ISSUE TITLE
Replace the ownCloud file picker with the Android one when uploading files

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2436]
We could replace our current file picker with the Android one based on [Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider), making simple for users to browse and upload documents, images, and other files.

This is what we currently have to upload files from the Android internal storage. 

| Tap upload button | Select  files | oC custom file picker |
| ------------- | ------------- | ------------- |
| ![device-2019-02-07-123248](https://user-images.githubusercontent.com/15261363/52409101-c058f700-2ad4-11e9-9aa7-cc37b08f90fa.png) | ![device-2019-02-07-123317](https://user-images.githubusercontent.com/15261363/52409104-c2bb5100-2ad4-11e9-8f7e-a268eca1e4a1.png) | ![device-2019-02-07-122748](https://user-images.githubusercontent.com/15261363/52408884-3315a280-2ad4-11e9-94b4-d33e5e88c28e.png) | 

On the right we have our custom file picker, which has made sense for several years but **Android 4.4 (API level 19) introduced the storage access framework**, which makes the life easy to the Android developers, being the responsible of showing files to perform actions with them. 

Fortunately, we have this already when using the content from other apps button.

| Tap content from other apps button | Storage access framework |
| ------------- | ------------- | 
| ![device-2019-02-07-123659](https://user-images.githubusercontent.com/15261363/52409380-a4a22080-2ad5-11e9-9b59-1b262ad57d0a.png) | ![device-2019-02-07-124014](https://user-images.githubusercontent.com/15261363/52410059-8806e800-2ad7-11e9-8c88-1c35afaa9aa2.png) | 

As you can see above, in the screenshot on the right, we can upload files images, videos, recent, internal storage and other apps files from there so **our custom file picker would not be needed anymore and we would save time spent in fixing known and coming issues on it since Android picker takes care of that and also includes additional sorting, select all, search features and more.**

So this is what I propose:

1. Get rid of _Content from other apps_ button and our custom file picker implementation.
2. Use the already implemented SAF for _Content from other apps_ option in _Upload files_ option.

This would be the **UI result**:

| Tap upload button | Select  files | Storage access framework |
| ------------- | ------------- | ------------- |
| ![device-2019-02-07-123248](https://user-images.githubusercontent.com/15261363/52409982-50983b80-2ad7-11e9-97ca-3cf918eb18c0.png) | ![device-2019-02-07-123317](https://user-images.githubusercontent.com/15261363/52409104-c2bb5100-2ad4-11e9-8f7e-a268eca1e4a1.png) | ![device-2019-02-07-124014](https://user-images.githubusercontent.com/15261363/52410059-8806e800-2ad7-11e9-8c88-1c35afaa9aa2.png) | 

What's your opinion on this? @hosy @michaelstingl @jesmrec 

### PRs
- App: https://github.com/owncloud/android/pull/2479

**Comment by jesmrec** [comment]
this is a step forward since we get rid of features that are already supported by the framework. By placing the `Uploads from Camera` in other small button from the FAB we will not lose features and will have an straighforward way to upload files from other locations. Works for me.

**Comment by davigonz** [comment]
> By placing the `Uploads from Camera` in other small button from the FAB we will not lose features and will have an straighforward way to upload files from other locations. Works for me.

Yes, that was my first approach but I discarded it because if we include the _Uploads from Camera_ button in FAB, then there will not be enough room for coming features, specially when using the app in landscape mode. Keeping the bottom sheet is better imho since is more flexible and can be scrollable.

![filelist](https://user-images.githubusercontent.com/15261363/34608939-0468458e-f21b-11e7-8594-360ef0ddd4f2.png)

![upload bottom sheets](https://user-images.githubusercontent.com/15261363/34608940-07466376-f21b-11e7-95b2-dd43e7323332.png)

**Comment by michaelstingl** [comment]
Yeah, I always vote for the more native implementation and simplification 👍

**Comment by sd1998** [comment]
@jesmrec I would like to work on this.

**Comment by hosy** [comment]
Would be great if you implemente this. Looking forward to see your PR!

**Comment by hosy** [comment]
@sd1998 if you start working, please add a `Work in Progress` Label

**Comment by jesmrec** [comment]
Done!! will be available in 2.11
