### ISSUE TITLE
Lint check during PR ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2441]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/3314607/52521092-2a5ad300-2c72-11e9-961e-c25df0ba666c.png">

Ok, it needs a PR, but I vote for lint error check during PR

### PRs: 

https://github.com/owncloud/android/pull/2736

**Comment by hannesa2** [comment]
Android Studio has not only this bug. Reopen Android Studio solves it.

But I vote for lint error check during PR

**Comment by hannesa2** [comment]
at least the errors should be removed 
<img width="513" alt="image" src="https://user-images.githubusercontent.com/3314607/52522811-9ea17080-2c8a-11e9-818d-0f2a4ec2f894.png">

**Comment by hannesa2** [comment]
https://github.com/owncloud/android/pull/2736

**Comment by jesmrec** [comment]
Done
