### ISSUE TITLE
Login fails with "§" in password

### ISSUE THREAD

**Issue by Citrodata** [owncloud/android#2451]
### Actual behaviour
- We can login with a User

### Expected behaviour
-Login in with a User
 
### Steps to reproduce
1.  Set the Password of a User to QWERTZqwert123456!"§$%&
2. Login with App

### Error
Wrong User
We are using LDAP

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

No only if the Password is QWERTZqwert123456!"§$%&

### Environment data
Android version:
8
Device model: 
All
Stock or customized system:
Stock Version
ownCloud app version:
2.9.3
ownCloud server version:
10.1.0

### PR

- App https://github.com/owncloud/android/pull/2542
- Library (if needed) https://github.com/owncloud/android-library/pull/249

**Comment by michaelstingl** [comment]
> Can this problem be reproduced with the official owncloud server?
> (url: https://demo.owncloud.org, user: test, password: test)

@Citrodata You can login with admin:admin, and create a new user.

I played with it a bit, and it seems the length isn't a problem. This Password worked too:
`QWERTZqwert123456!"$%&evenlonger`
^ I removed the "`§`" character

On the other hand, short passwords with "`§`" character don't work:
`123§`

ownCloud 2.9.3 on Pixel 3 XL running Android 9

**Comment by jesmrec** [comment]
Regression? https://github.com/owncloud/ios/issues/273

**Comment by jesmrec** [comment]
I have checked the request sent to the server, and the character is not sent in the base64 encoded header. We will have to check if the current password management supports (or not) unicode characters.
