### ISSUE TITLE
Name conflicting in some actions is not consistent

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2470]
The policy in case of name conflicts is not consistent with these actions:

- Copy: If you copy an item inside the same directory, nothing happens. 

- Upload: If you download twice the same file inside the same folder, file is uploaded twice with a serial increment number (`file.txt`and `file(2).txt`)

- Rename/Move: if you rename or move an item in any folder that contains another item with the same name, it is not allowed and shown as an error.

We should unify criteria and put the same policy in every action.

CC @michaelstingl @davigonz @abelgardep

**Comment by sd1998** [comment]
@jesmrec I would like to work on this.

**Comment by jesmrec** [comment]
@sd1998 it is ok, but first, we have to decide and discuss which one is the behaviour we want to implement for the actions along the described cases. Once we remove the `discussion` label with the final decision, we can ping you. Of course, your opinion is also welcome about the way to proceed.

**Comment by sd1998** [comment]
@jesmrec I think it would be better if on copying and pasting a file in the same directory would copy the file twice with a serial incremented just as in case of uploads. 

Thus applying the same ploicy accross both the actions.
