### ISSUE TITLE
Batched permission errors when deleting if you are not granted

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2471]
This is something like: https://github.com/owncloud/android/issues/2335

Here the steps are:

1. Share a folder with another user. Do not grant to delete
2. Sharee opens the folder  in the account and try to remove several files by multiselecting

Current: an snackbar appears from each file that is not allowed to be removed
Expected: only one snackbar 

### PRs
App: https://github.com/owncloud/android/pull/2564

**Comment by sd1998** [comment]
@jesmrec I would like to work on this.
