### ISSUE TITLE
UI glitch in warning icon used to show errors when sharing a file publicly

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2473]
### Actual behaviour
The warning icon used to show errors when sharing a file publicly is almost not visible due to the white color used. This warning icon is the same resource that we use in the login view and it needs to be white, so changing the color here will not solve the problem, use new resource maybe?

[<img src="https://user-images.githubusercontent.com/15261363/54031539-543ee100-41af-11e9-9c04-a75b6c5b8900.png" width="300px"/>](https://user-images.githubusercontent.com/15261363/54031539-543ee100-41af-11e9-9c04-a75b6c5b8900.png)

### Expected behaviour
Warning icon should appear in grey color. 

[<img src="https://user-images.githubusercontent.com/15261363/54032086-e85d7800-41b0-11e9-8632-ba5c5d01e4ea.png" width="300px"/>](https://user-images.githubusercontent.com/15261363/54032086-e85d7800-41b0-11e9-8632-ba5c5d01e4ea.png)

### Steps to reproduce
1. Disable wifi
2. Long press a file
3. Press share option
4. Create new public link
5. Save share

Can this problem be reproduced with the official owncloud server? Yes
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 9.0

Device model: Google Pixel

Stock or customized system: Stock

ownCloud app version: 2.10.0

ownCloud server version: 10.0.10

**Comment by sd1998** [comment]
@davigonz I would like to work on this.

**Comment by davigonz** [comment]
> I would like to work on this.

Sure! Go for it

**Comment by jesmrec** [comment]
Done. Ready for 2.11
