### ISSUE TITLE
Canceling dialog in settings turns on setting

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/android#2478]
### Steps to reproduce
1. Open settings
2. Click on "Touches with other visible windows"
3. Cancel the dialog by clicking somewhere outside the dialog
4. Touches with other visible windows is now turned on

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
This is most likely a client-only issue.

### Environment data
Android version: 7.1.2

Device model: Oneplus X

Stock or customized system: Lineage 14

ownCloud app version: 2.1.0

ownCloud server version: 10

### PR
https://github.com/owncloud/android/pull/2492
https://github.com/owncloud/android/pull/2491

**Comment by jesmrec** [comment]
Got it. Same effect in disabling camera uploads

**Comment by sd1998** [comment]
@jesmrec I would like to work on this.
