### ISSUE TITLE
Make brandable the option to click in commit hash

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2480]
After https://github.com/owncloud/android/pull/2408, commit hash is shown in `Setting` to track the exact installed version. By clicking on it, you can go directly to github to get the commit.

We need the clicking option to be brandable, with a default of `yes`

**Comment by hannesa2** [comment]
> We need the clicking option to be brandable, with a default of yes

I don't understand exactly, but maybe it's already done ? https://github.com/owncloud/android/blob/master/owncloudApp/build.gradle#L188-L194 Here you `origin remote` is used

Btw, maybe you can merge https://github.com/owncloud/android/pull/2439 first ?

**Comment by jesmrec** [comment]
Already implemented
