### ISSUE TITLE
After deleting log history, no extra logs are printed 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2483]
In debug mode

### Steps to reproduce

1. Go to Settings
2. Open Logs and delete history
3. Perform some actions in the app, so new logs will be made up
4. Open logs in Settings again

### Current behaviour

Logs empty

### Expected behaviour

Logs not empty

Reproduced with Android 9 and Android 8.

NOTE: By rebooting the device, logs are there again.

**Comment by sd1998** [comment]
@jesmrec This cannot be replicated on Samsung Galaxy S9+. Running Android Pie

**Comment by jesmrec** [comment]
i have re-checked and it does not happen always... i will need to check a bit more.

**Comment by jesmrec** [comment]
Moved to Timber. No longer needed.
