### ISSUE TITLE
[Document Provider] Rename Document

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2484]
New improvement to Document Provider : [Rename Document](https://developer.android.com/reference/android/provider/DocumentsContract.html#renameDocument(android.content.ContentResolver,%20android.net.Uri,%20java.lang.String))

| Actual behaviour | Expected behaviour | 
| ------------- |-------------| 
| ![ActualBehaviour](https://user-images.githubusercontent.com/47524927/54682482-55590200-4b0f-11e9-8c86-a2d038cd4125.png) | ![DocProviderRenameOption](https://user-images.githubusercontent.com/47524927/54682204-8e44a700-4b0e-11e9-8821-a8f6dbb49ee5.gif) |

### TASKS

- [x] Migrate current Document Provider and related files to Kotlin
- [x] Add rename functionality to Document Provider

### PR

https://github.com/owncloud/android/pull/2506

**Comment by michaelstingl** [comment]
@abelgardep I don't get it. How does it work in other apps? Could you post a screenshot?

**Comment by abelgardep** [comment]
> @abelgardep I don't get it. How does it work in other apps? Could you post a screenshot?

Of course, i updated this issue.

**Comment by abelgardep** [comment]
@michaelstingl Of course, i edited this issue.

**Comment by jesmrec** [comment]
Done!
