### ISSUE TITLE
App crashes when sharing files with ownCloud and creating new folder

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2485]
### Actual behaviour
- App crashes.

### Expected behaviour
- Folder creation properly performed.
 
### Steps to reproduce
1. Open a file browser.
2. Select a file and share with ownCloud.
3. Tap three dots and New Folder option.

### Environment data
Android version: 9

Device model: Google Pixel 3 XL

Stock or customized system: Stock

ownCloud app version: 2.10.0

ownCloud server version: not relevant 

### PR
https://github.com/owncloud/android/pull/2490

**Comment by sd1998** [comment]
@davigonz I have fixed this issue.

**Comment by jesmrec** [comment]
Fixed. Looking forward to 2.11.
