### ISSUE TITLE
Select all and select inverse appear in the app bar

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2493]
### Actual behaviour
- _Select all_ and _Select inverse_ options appear in the top of the file actions menu with no icon.

[<img src="https://user-images.githubusercontent.com/15261363/54595826-b1e6ef00-4a33-11e9-8603-ebcba37b5f7e.png" width="350px"/>](https://user-images.githubusercontent.com/15261363/54595826-b1e6ef00-4a33-11e9-8603-ebcba37b5f7e.png)

### Expected behaviour
- _Select all_ and _Select inverse_ options should not appear in the app bar but in the the app bar's overflow menu, after tapping the three dots icon.

[<img src="https://user-images.githubusercontent.com/15261363/54596043-27eb5600-4a34-11e9-94da-5d29c3890c82.png" width="350px"/>](https://user-images.githubusercontent.com/15261363/54596043-27eb5600-4a34-11e9-94da-5d29c3890c82.png)
 
### Steps to reproduce
1. Long press a file.
2. Have a look at the top bar.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 7

Device model: Nexus 6P

Stock or customized system: Stock

ownCloud app version: master branch

### Some clues

This UI bug was introduced via https://github.com/owncloud/android/pull/2442 when changing:

![Screenshot 2019-03-19 at 10 47 24](https://user-images.githubusercontent.com/15261363/54596200-726cd280-4a34-11e9-93e2-4b1f5eec9ff1.png)

### PR
https://github.com/owncloud/android/pull/2514

**Comment by sd1998** [comment]
@davigonz I will fix this.

**Comment by davigonz** [comment]
> I will fix this.

Sure, go ahead!

**Comment by sd1998** [comment]
@davigonz I am unable to determine the reason why the "Select-all" and "Select inverse options are appearing in the top of the file actions menu as everything seems to be fine. One way to fix this would be to shift back to `android:showAsAction` from `app:showAsAction` should  do that?

**Comment by deandreamatias** [comment]
I have tried to solve this problem but I have encountered a bug.
Apparently, there is an error in logic. When you press the "select all" option in the menu, it option appears again in the TopBar. From what I've seen, the ActionMode update and the mEnableSelectAll variable are not setting well.

**Comment by davigonz** [comment]
>  I am unable to determine the reason why the "Select-all" and "Select inverse options are appearing in the top of the file actions menu as everything seems to be fine. One way to fix this would be to shift back to android:showAsAction from app:showAsAction should I do that?

Yes, let's solve it by doing that.

**Comment by davigonz** [comment]
> I have tried to solve this problem but I have encountered a bug.
Apparently, there is an error in logic. When you press the "select all" option in the menu, it option appears again in the TopBar. From what I've seen, the ActionMode update and the mEnableSelectAll variable are not setting well.
I think this is the first step to fix this issue.

Thanks @deandreamatias for your report, I was able to solve this locally by replacing `app:showAsAction` with `android:showAsAction` so I guess that what you refer to is a different bug, could you open a new issue and give us more details?

**Comment by sd1998** [comment]
@davigonz I have also been able to replicate [this comment](https://github.com/owncloud/android/issues/2493#issuecomment-478576439) should I change it back to `android:showAsAction`?

**Comment by davigonz** [comment]
Yes, try to use `android:showAsAction`, I answered you in https://github.com/owncloud/android/issues/2493#issuecomment-478575429

**Comment by jesmrec** [comment]
Approved. Thanks for the fix @sd1998 !!

**Comment by jesmrec** [comment]
Fixed!
