### ISSUE TITLE
Automation code cleaning 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2494]
Old tests are not being used, so they should be either removed from the repo or moved to another place for legacy code:

https://github.com/owncloud/android/tree/master/automationTest

Additionally, we need to remove the following check (@DeepDiver1975)

![Screen Shot 2019-03-20 at 13 03 13](https://user-images.githubusercontent.com/14894746/54682943-9bfb2c00-4b10-11e9-8dba-b63e64e69e95.png)

**Comment by davigonz** [comment]
I would remove it if is not being used. If are needed in the future, we can bring them back from git history.
