### ISSUE TITLE
[Document Provider] Move files or folders

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2496]
New improvement to Document Provider : Move Files or Folders -> [Doc](https://developer.android.com/reference/android/provider/DocumentsProvider.html#moveDocument(java.lang.String,%20java.lang.String,%20java.lang.String)) API 24

Moves a file or folder including all child files to another location including OwnCloud server.

Current status:
- Option disabled in OwnCloud Provider
- Disabled option to move files or folders to OwnCloud from others providers

### TASKS

- [x] Add 'Move to' functionality to Document Provider

### PRs

- App: https://github.com/owncloud/android/pull/2641

**Comment by jesmrec** [comment]
Through this issue will keep the moving option described here: https://github.com/owncloud/android/issues/2575
