### ISSUE TITLE
[Document Provider] Delete Files or Folders

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2499]
New improvement to Document Provider : Delete Files or Folders -> [Doc](https://developer.android.com/reference/android/provider/DocumentsProvider.html#deleteDocument(java.lang.String)) API 19

Delete a file or folder including all child files.

Current status:
- Option disabled in OwnCloud Provider

### TASKS

- [x] Add 'Delete Document' functionality to Document Provider

### PR
#2511 

### Test plan: 
https://github.com/owncloud/QA/blob/master/Mobile/Android/Release_2.11.0/2511-document_provider_delete.md

**Comment by sd1998** [comment]
@abelgardep I would like to work on this.

**Comment by abelgardep** [comment]
@sd1998 I'm migrating DocumentsProvider to kotlin. This way, new functionality related with DocumentsProvider will be developed in kotlin. When i finish the migration i can ping you if you want to work on this 👍

**Comment by abelgardep** [comment]
Hi @sd1998 , i will work on this because i have been working on the Document Provider for the last two weeks. Thanks anyway
