### ISSUE TITLE
Code of conduct to be included 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2505]
Currently, ownCloud has the following code of conduct:

https://owncloud.org/community/code-of-conduct/

We should include it in the current repository, somewhere referring the community. 

Different options:

1.- Include the code of conduct as a separate link in the root (such as `CONTRIBUTING.md`, `README.md`...) 
2.- Integrate it in the `CONTRIBUTING.md` as new entry, including some guidelines about the procedure to handle the repo, like the reasons we are using `rebase` instead of `merge `etc...
3.- other approaches like this one from WWDC: https://github.com/insidegui/WWDC/blob/master/CODE_OF_CONDUCT.md  suggested by @michaelstingl 

CC @davigonz @abelgardep

**Comment by ThinkHattke** [comment]
Can I add this?

**Comment by jesmrec** [comment]
It was already added

https://github.com/owncloud/android/blob/master/CONTRIBUTING.md#code-of-conduct

so, this one can be closed. Thanks anyway for the offering @ThinkHattke!!. If you are interested in contributing, you can check the issues labeleld with "contributions are welcome", or any other thing you are interested in.

**Comment by ThinkHattke** [comment]
sure will check for other issues @jesmrec
