### ISSUE TITLE
Picture upload fails with HTC Sensation/HTC One SV/HTC One SV LTE

### ISSUE THREAD

**Issue by FStrohmeier** [owncloud/android#251]
Hi,

may I draw your attention to the following posting http://forum.owncloud.org/viewtopic.php?f=24&t=12828 which describes in more detail my attempts to upload pictures, especially jpg, to my ownCloud using either an HTC Sensation, HTC One SV and HTC One SV LTE.

The topic of not working immediate uploads is already discussed in some issues. 

What faszinates me most is the fact, that upload works after renaming pictures form *.jpg to *.txt for example.

I put a ZIP-File with tests I made and a conversation with ownCloud.org (anonymized) on Skydrive: http://sdrv.ms/17meKLI

Kind regards,

Franz

**Comment by davivel** [comment]
@FStrohmeier , is this still a problem for you?

Thanks in advance.

**Comment by FStrohmeier** [comment]
@davivel 
Hello, 
unfortunately, it still fails (in most cases) and shows some very interesting and strange (new) behaviour. 

I just installed the latest ownCloud app to my smartphone (I reset the smartphone to factory settings a few weeks ago).

After the first tries, I was happy, but then I found out the things being explained in the screenshot enclosed.

The error occured as follows: Upload finishes with 100 % but immediately afterwards it says (retranslated to English!): You have no authorization for that folder.

I also have to repeat that to my opinion, the reason unfortunately is HTC because I had a problem with another app (my most important one). Discussions in the produder's forum showed that others had the similar problem and with the exception of one, all were HTC users. Since I reset the factory settings of the phone, also this app works again. The HTC helpdesk was of no help, no real solution and when I sent a link to the discussion, I got the answer: We don't read forum postings concerning our products...

May I also repeat my offer: If you would like an account on my server again, please give me an info. Also if you want me to install some "developer version" of the ownCloud app that provides you with more detailled information in a log file, don't hesitate to contact me.

Kind regards,

Franz

**Comment by davivel** [comment]
Hi, @FStrohmeier . Could you give another try with the just-released version 2.1.1 of the ownCloud app? You will need to go into "Settings" to select your camera folder in the "Instant uploads" section, that seems to be in "DCIM/100MEDIA" instead of our default "DCIM/Camera".

Thanks!

**Comment by davigonz** [comment]
Hi @FStrohmeier , could you give a new try with the 2.6.0 app we released yesterday? It includes the new Camera uploads feature, which will replace Instant Uploads and will upload automatically your pictures and videos in 15 minutes at most.

**Comment by FStrohmeier** [comment]
Hello,

Sorry for the late reply. As I do not use this smartphone anymore for now about a year, I can only give the app a try on my new one (Huawei P9). I will do so and give a feedback in a few days.

Kind regards,

Franz

Am 02.02.2018 um 15:42 schrieb David González Verdugo <notifications@github.com<mailto:notifications@github.com>>:


Hi @FStrohmeier<https://github.com/fstrohmeier> , could you give a new try with the 2.6.0 app we released yesterday? It includes the new Camera uploads feature, which will replace Instant Uploads and will upload automatically your pictures and videos in 15 minutes at most.

**Comment by davigonz** [comment]
Hi @FStrohmeier , any update on this?

**Comment by FStrohmeier** [comment]
Hi, @davigonz, sorry no update as I am not using the app anymore.

Kind regards,
Franz

**Comment by davigonz** [comment]
Let's close this then, if there's any other issue about that topic, please reopen
