### ISSUE TITLE
[New arch] App modularization and decoupling

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2523]
The status of the app and its code is a recurrent topic that's been discussed several times. A couple of months ago we started to work on a [new architecture](https://github.com/owncloud/android/issues/2351) that is transforming the app to be more testable, robust and future proof. 

Thanks to this new architecture, we should manage to have an app with much less dependencies but sometimes it's not easy to know and control, even less in an app as huge as ownCloud for Android.

So let's go through several solutions to modularize and decouple the app

### **Modularization with layers approach**

- Diagram
![2 3  oC app modules diagram_resized](https://user-images.githubusercontent.com/15261363/61300732-d33dc900-a7e2-11e9-8ecc-b956219d59ad.png)

- Advantages:
  - Scalability: several developers working independently in different modules.
  - Maintainability: gradle can build modules faster since the classes and resources are separated in different modules. CI builds will be accelerated too.
  - Less tests to run when there's a new change: we need to run the tests in the module affected by that change and anything else that depends on it. We do not need to run all the tests if other modules are not impacted by the changes.
  - Reduce dependencies => less coupled code.
  - SWITCH MODULES: if in the future we want an app with a different UI and a different way to handle the information to show, we would just need to replace the :ownCloudApp module. And the same for the rest of modules, if one day we want to handle data differently to the current implementation, replacing the :ownCloudData module should be enough.

- Video: https://youtu.be/PZBg5DIzNww

-----------------------------------------------

### OTHER TOOLS

I've found an open source tool called [Apk dependency graph](https://github.com/alexzaitsev/apk-dependency-graph) that could help us a lot on this matter.

This is how the **dependency graph for the ownCloud Android app** looks like, based on [New arch - capabilities branch](https://github.com/owncloud/android/pull/2508) (I put it live in https://davigonz.github.io/oCAndroidDependencyGraph/ so everyone can play with it) :

![Screenshot 2019-04-24 at 18 31 14](https://user-images.githubusercontent.com/15261363/56676690-29590f80-66bf-11e9-9a45-32b18ce15a3a.png)

Above we can notice some parts of new architecture (OCShareRepository, OCShareViewModel, OCCapabilityRepository, OCCapabilityViewModel...) along with old code.

And below there's an example of a **good architecture with low class coupling**:

![Screenshot 2019-04-24 at 18 33 25](https://user-images.githubusercontent.com/15261363/56676844-776e1300-66bf-11e9-99f4-709ee75b9901.png)

Taking into account [this diagram](https://davigonz.github.io/oCAndroidDependencyGraph/) while working on the new architecture would be great and will allow us to have a higher level vision and complete the whole app transformation process. 

So we could use this issue as an epic and create possible changes that come to our mind after having a look at the diagram.

Note: the diagram is currently hosted as a webpage in https://davigonz.github.io/oCAndroidDependencyGraph/ and it uses [this repo](https://github.com/davigonz/oCAndroidDependencyGraph) but we could move it with the rest of ownCloud repositories and even update the diagram via some kind of script included in bitrise (not sure if is possible, need to be checked) and have it updated with new arch changes. 

CC / @michaelstingl @jesmrec @abelgardep @hosy 

@owncloud/ios-core-developers you have something similar for iOS as well => https://github.com/PaulTaykalo/objc-dependency-visualizer

**Comment by michaelstingl** [comment]
@davigonz branch with [first steps in new architecture](https://github.com/owncloud/android/issues?q=label%3AArchitecture) isn't merged yet. What does the top image show? Last stable release build? Current master branch? Or the branch with the new architecture?

**Comment by davigonz** [comment]
> branch with first steps in new architecture isn't merged yet. What does the top image show? Last stable release build? Current master branch? Or the branch with the new architecture?

I generated the graph from new arch - capabilities branch to start seeing how the dependencies of the new architecture look like there, along with old code.

**Comment by davigonz** [comment]
In order to not duplicate information and have the generic architecture details in only one issue, I've just moved what I wrote here to the epic architecture issue. I will close this, please follow up the epic in https://github.com/owncloud/android/issues/2351
