### ISSUE TITLE
WiFi login page causes Android client to fail silently

### ISSUE THREAD

**Issue by duncan-bayne** [owncloud/android#253]
I am using my own installation of OwnCloud 5.0.10, and the Android client 1.4.4.

My WiFi network at work redirects all traffic to a login page. Once you've logged in it remembers your device (presumably by MAC address?) and stops redirecting traffic.

If I attempt to browse my server using the Android client before I log in, no error is displayed. Instead, I'm presented with an empty / folder.

If I exit the client, browse to a website, log in to WiFi, then return to the client, then I can see my files.

I'd expect that if the client receives a nonsensical response (e.g. a WiFi login page) it'd display some sort of error message instead of just an empty file list.

**Comment by masensio** [comment]
Hi @duncan-bayne,

We have done many changes since you reported this problem. Have you updated your server and client?

Do you still have the same problem?

**Comment by duncan-bayne** [comment]
I'm afraid I no longer use Owncloud for file management; I've replaced it with Unison which works well for my particular requirements.  If someone else wants to test the newest version, an easy way would be to:

 - set up an HTTP proxy on a development machine
 - use the proxy to log in to an Owncloud instance
 - change the proxy to redirect all traffic to a static URL

That should repro the behaviour for testing.

**Comment by hodyroff** [comment]
Old version, not using ownCloud anymore. Closing.
