### ISSUE TITLE
Export to device

### ISSUE THREAD

**Issue by Remich** [owncloud/android#2535]
Add option to export a file/multiple files/folders to your Android Device.

**Comment by jesmrec** [comment]
Thanks for the suggestion. We will study it in order to schedule a solution.

**Comment by sd1998** [comment]
@jesmrec Can I work on this?

**Comment by jesmrec** [comment]
for the moment this i not a priority. For this one, we should discuss before some acceptance criteria and think about security regards. CC @michaelstingl

**Comment by michaelstingl** [comment]
> @jesmrec Can I work on this?

@sd1998 What would be your proposal for an improvement?

**Comment by michaelstingl** [comment]
This can already be done using the ownCloud document provider in the File Explorer App on your device.
