### ISSUE TITLE
[BUG] Just created folder disappears when synchronizing parent folder

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2536]
### Actual behaviour
Just created folder disappears when synchronizing parent folder and reappears during the next synchronization

### Expected behaviour
Just created folder should not disappear
 
### Steps to reproduce
1. Create new folder
2. Just created folder is shown successfully
3. Pull down to sync the parent folder
4. Just created folder disappears
5. Pull down again to sync the parent folder
6. Just created folder reappears

[<img src="https://user-images.githubusercontent.com/15261363/57215733-16630b00-6fee-11e9-8a98-6fa8099117ec.gif" width="350px"/>](https://user-images.githubusercontent.com/15261363/57215733-16630b00-6fee-11e9-8a98-6fa8099117ec.gif)

### Environment data
Android version: 8.1

Device model: Nexus 5X

Stock or customized system: Stock

ownCloud app version: 2.10

ownCloud server version: 10.0.10 (stable)

### PR
App: https://github.com/owncloud/android/pull/2559

**Comment by sd1998** [comment]
@jesmrec Can I work on this?

**Comment by jesmrec** [comment]
of course!! we have scheduled this one into 2.11, do you think you can finish it within the next 2-3 weeks?

**Comment by sd1998** [comment]
@jesmrec Yes, I have already started working on it.

**Comment by sd1998** [comment]
@davigonz @jesmrec I have an issue. As you can see from the attached screenshot:-
<img width="1094" alt="Screenshot 2019-05-17 at 5 23 16 PM" src="https://user-images.githubusercontent.com/22047421/57926549-3685aa80-78c9-11e9-9c3b-5213ad684dbd.png">
(The screenshot is the debugger output at [this line](https://github.com/owncloud/android/blob/294ba33e86656a30007d4503b2a43cb14bed08a7/owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L1016) I have just added an additional line(No. 1017):- 
![image](https://user-images.githubusercontent.com/22047421/57926706-9419f700-78c9-11e9-84e0-f180ae0fe109.png)
to check the contents of FileDataStorageManager)
The RefreshFolderOperation result shows that there are 7 files(counting the parent directory) but just after receiving the result if we fetch the folder content using FileDataStorageManager the no. of files is 5 (it should ideally be 6 as we the FileDataStorageManager  does not return the parent directory). I am unable to understand why the FileDataStorageManager does not provide the same response even when the new directory being created is being saved in the local db as can be seen [here](https://github.com/owncloud/android/blob/294ba33e86656a30007d4503b2a43cb14bed08a7/owncloudApp/src/main/java/com/owncloud/android/operations/CreateFolderOperation.java#L110). Please advise.

**Comment by davigonz** [comment]
> @davigonz @jesmrec I have an issue. As you can see from the attached screenshot:-
Screenshot 2019-05-17 at 5 23 16 PM
(The screenshot is the debugger output at this line I have just added an additional line(No. 1017):-
image
to check the contents of FileDataStorageManager)
The RefreshFolderOperation result shows that there are 7 files(counting the parent directory) but just after receiving the result if we fetch the folder content using FileDataStorageManager the no. of files is 5 (it should ideally be 6 as we the FileDataStorageManager does not return the parent directory). I am unable to understand why the FileDataStorageManager does not provide the same response even when the new directory being created is being saved in the local db as can be seen here. Please advise.

Yes, that's what you need to find out 😉 , try to research a bit more and if you do not progress anything, I will help you

**Comment by jesmrec** [comment]
@sd1998 did you get any finding? do you need some help with the issue?

**Comment by davigonz** [comment]
@sd1998 In the end I'll take care of this since it should be included for 2.11 version, please continue with other features, thanks
