### ISSUE TITLE
If ssl is enabled and i download a big file the server gets busy to 100%

### ISSUE THREAD

**Issue by hschraep** [owncloud/android#255]
I' running the owncloud app version 1.4.4 on a 4.3 android phone.  If i have enable ssl via the webinterface and download a file up to 97MB, the server gets busy up to 100%. The only thing what i can do, is reset the server, no input are possible. Smaler files are no problems if ssl is enabled. If it is disabled i can also download bigger files without problems. 
Owncloud server is 5.0.10

Is this a problem of the ssl certificate or is this a problem of android 4.3 or a problem of the owncloud app?

**Comment by masensio** [comment]
Hi @hschraep,

Sorry for the delay.

This is an old issue.
I suppose you have updated your OwnCloud versions (Server, Desktop and Android app). 
Have you still got this problem?

**Comment by hschraep** [comment]
Hi @masensio,
in the meanwile I have replaced the hole server withe a new one. And installed onencloud new. After that I have no more problems with that. Thanks for asking. 
Am 18.06.2015 11:50 vorm. schrieb masensio <notifications@github.com>:Hi @hschraep,

Sorry for the delay.

This is an old issue.
I suppose you have updated your OwnCloud versions (Server, Desktop and Android app). 
Have you still got this problem?

**Comment by masensio** [comment]
Thanks for your fast answer.
I'm happy for reading this.
So, I'll close the issue.
