### ISSUE TITLE
[BUG] Directories with '[' and ']' don't display content in app

### ISSUE THREAD

**Issue by Benzyme93** [owncloud/android#2552]
### Actual behaviour
- Enter directory with '[' or ']' in its name (e.g. "My Folder [2019]")
- Displays empty directory message (doesn't show content)

### Expected behaviour
- Directory content should be displayed
 
### Steps to reproduce
1. Create directory with the above name format (e.g. "My Folder [2019]") in OwnCloud desktop or web interface
2. Navigate to the new directory in the android app
3. Directory content is not displayed

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

Cannot create directory in android app using the test server.

### Environment data
Android version:

Device model: 
Samsung Galaxy S10+
Stock or customized system:
Stock
ownCloud app version:
2.10.1
ownCloud server version:
10.1.1

**Comment by jesmrec** [comment]
We were reported this bug: https://github.com/owncloud/android/issues/2481

Fix will be available in 2.11 to be released withind the next weeks.
