### ISSUE TITLE
[DOCS] add troubleshooting advice to docs

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#2554]
similar to
- [`ios-app/doc/TROUBLESHOOTING.md`](https://github.com/owncloud/ios-app/blob/master/doc/TROUBLESHOOTING.md)
- [`client/docs/modules/ROOT/pages/troubleshooting.adoc`](https://github.com/owncloud/client/blob/master/docs/modules/ROOT/pages/troubleshooting.adoc)

### PRs

- App: https://github.com/owncloud/android/pull/2652

**Comment by michaelstingl** [comment]
Add link to information about X-REQUEST-ID (see https://github.com/owncloud/ios-app/pull/479 as example)

**Comment by davigonz** [comment]
Done, to be included in 2.13
