### ISSUE TITLE
[BUG] Infinite loading when trying to connect with OAuth2

### ISSUE THREAD

**Issue by baptisteArnaud** [owncloud/android#2570]
### Actual behaviour
After enbabling OAuth2.0 plugin, It connects using an external browser. After I click on "Authorize", It goes back to the app with an infinite loading popup message "Requesting authorization..." (I'm not sure if it's the exact translation since my app is in French).

### Expected behaviour
Goes back to the app logged in
 
### Steps to reproduce
1. Enable OAuth 2.0, Enable TOTP Second-factor Auth in server
2. Try to log in on the application

### Environment data
Android version: 9

Device model: OnePlus 5T

Stock or customized system: Stock

ownCloud app version: 2.10.1

ownCloud server version: 10.0.10 (stable)

### Logs
No interesting logs

**Comment by jesmrec** [comment]
i will try to reproduce, and let you know. Which OAuth2 app version have you installed?

**Comment by baptisteArnaud** [comment]
[OAuth2](https://github.com/owncloud/oauth2) version 0.4.1
2-Factor Authentication version 0.5.3

**Comment by jesmrec** [comment]
All authentication engine was reworked and released in 2.15.1. Is this problem still reproducible on your side?

**Comment by baptisteArnaud** [comment]
> All authentication engine was reworked and released in 2.15.1. Is this problem still reproducible on your side?

I'm not using owncloud anymore so I can't test it out.
Cheers!
