### ISSUE TITLE
Beta version destroys all settings

### ISSUE THREAD

**Issue by jnweiger** [owncloud/android#2572]
I've joined the beta program, following the instructions in  README.md . I got stuck where it says "... end your final app will be replaced with the beta one." -- After waiting a while and reopening google play after reboot, nothing happened. Finally I uninstalled the app to get a chance for a re-install.
That works, I now have "Version 2.11.0-beta.1 release f280dd0a5" on my Samsung S4 with Adroid 5.0.1

The start screen asks me to enter a serve URL. 
All settings (3 server connections, camerasync, etc.) were lost.

I'd expect the beta version to pick up the settings of the normal version.

**Comment by jesmrec** [comment]
Not reproducible anymore. Feel free to reopen if happens again
