### ISSUE TITLE
[BUG] Project Does not Build

### ISSUE THREAD

**Issue by ozata** [owncloud/android#2589]
### Actual behaviour
Project does not build.

### Expected behaviour
 Project should be built.

### Steps to reproduce
1.  Clone the project
2.  Build
3.  Fail

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: Android 3.4.1

Device model: 

Stock or customized system:

ownCloud app version: Android v 2.11.1

ERROR: Unable to resolve dependency for ':owncloudApp@debug/compileClasspath': Could not resolve project :owncloud-android-library:owncloudComLibrary.
Show Details
Affected Modules: owncloudApp
![androiderror1](https://user-images.githubusercontent.com/33320778/59855051-d6c56800-937c-11e9-9198-6744ec02ef61.PNG)
![androiderror2](https://user-images.githubusercontent.com/33320778/59855054-d7f69500-937c-11e9-8dee-b407a0f8061d.PNG)

**Comment by michaelstingl** [comment]
I answered în https://central.owncloud.org/t/android-app-does-not-build/20595
