### ISSUE TITLE
[BUG] clear all finished in upload view clears failed alse

### ISSUE THREAD

**Issue by mstojanovic** [owncloud/android#2596]
### Actual behaviour
-when clicking on clear all finished in the upload view all streams are cleared

### Expected behaviour
-only uploaded streams should be cleared from the view
 
### Steps to reproduce
1. upload a few files
2. make some fail and let some upload
3. go to the upload view
4. select clear all finished from the dot menu

Can this problem be reproduced with the official owncloud server?
did not try, but not relevant

### Environment data
Android version: 9

Device model: samsung s9

Stock or customized system: stock

ownCloud app version: 2.11.1 release f5c5096a7

ownCloud server version: not relevant

#### Web server error log
not relevant

#### ownCloud log (data/owncloud.log)
not present on at given location

**Comment by jesmrec** [comment]
Thanks for reporting!

My suggestion is: the options to clear should match the sections in the list. So, the following options should be available:

- Clear successful
- Clear failed
- Clear pending 
- Clear all (current will not be removed)
- Retry failed

clear all finished leads to confusion, i'd get rid of it. Open to new ideas.

**Comment by mstojanovic** [comment]
i could live with that as long as the actions are what they say

**Comment by jesmrec** [comment]
Next release 2.17, a new option to clear will be included for every list:

https://github.com/owncloud/android/issues/2847#issuecomment-749696480

So, this ticked is solved with such fix. 

Thanks for reporting and fell free to reopen in case something is missing.
