### ISSUE TITLE
[BUG] Local copy could not be renamed, try a different name

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/android#2614]
### Actual behaviour
I installed your app on a Samsung S9 for the first time. When I entered the server URL I did get an error. I forgot the subfolder "/owncloud". I accepted my server certificate. After I entered the correct server URL with /owncloud I always get the error:
```
"Die lokale Kopie konnte nicht umbenannt werden. Versuchen Sie es mit
einem anderen neuen Namen."

In English: Local copy could not be renamed, try a different name
```

I always get the same error. In my WLAN with the local URL incl. SSL it
works. I think there is an entry in the file system of the phone which
could't be overwritten. With other smartphones and tablets, my ownCloud
installation works without errors.

I also found an entry on GitHub but I could find any solution there:
https://github.com/owncloud/android/issues/2257

### Expected behaviour
I could log-in to my ownCloud server
 
### Environment data
**Android version:**  Android 9
**Smartphone:** Samsung S9
**ownCloud server:** 10.0.6
**ownCloud app version:** 2.11, 2.9, 2.8

**Comment by michaelstingl** [comment]
@ChrisEdS log available?

**Comment by ChrisEdS** [comment]
You have to log-in first in order to take logs, right?

**Comment by michaelstingl** [comment]
> You have to log-in first in order to take logs, right?

Hm, good point. `mitmproxy` as an alternative?

**Comment by michaelstingl** [comment]
> You have to log-in first in order to take logs, right?

Log into a working server first (demo.owncloud.com), then connect the broken server as a 2nd account)

**Comment by ChrisEdS** [comment]
I saw this error a few times when going through OTRS tickets. I can ask the users If they can provide some more information. 

> Log into a working server first (demo.owncloud.com), then connect the broken server as a 2nd account?

This should work.

**Comment by michaelstingl** [comment]
> I saw this error a few times when going through OTRS tickets.

I've seen this multiple times too, but it was always caused by older ownCloud servers with the legacy WebDAV endpoint.

**Comment by ChrisEdS** [comment]
Which version should be used at least? The problem here is that the user explains that he tried with ownCloud for Android 2.0.8 as well.

**Comment by michaelstingl** [comment]
@ChrisEdS Please don't waste time with the 2.8, let us focus on 2.9.3+ and current ownCloud servers.

**Comment by ChrisEdS** [comment]
You're absolutely right. I will handle differently in the future. New is always better. :)
