### ISSUE TITLE
[FEATURE REQUEST] As a user I want to be able to see bigger thumbnails and more condensed pictures

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/android#2615]
### Problem
Since many users use the app to store pictures and photos, it would be very neat to have a display option, just like on the windows explorer, to be able to see bigger thumbnails and more condensed pictures. Indeed, when searching for specific ones, or just occasionally browsing is not that easy considering the very small thumbnail size. 

### Solution
The possibility to scale the preview of the images using a slider.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by ChrisEdS** [comment]
Seems like another good solution: https://github.com/owncloud/android/issues/1402

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/android/issues/1402
