### ISSUE TITLE
[FEATURE REQUEST] Logging coverage

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2620]
Several issues are not easy to reproduce like crash reports from Google Play, or other similar which steps are not specific.

Some examples:

- https://github.com/owncloud/android/issues/2562
- https://github.com/owncloud/android/issues/2561
- https://github.com/owncloud/android/issues/2605

In these specific cases, related with services. The aim will be increasing the logging reports to get more info about the problems, so they can be fixed.

### PR

- App: https://github.com/owncloud/android/pull/2646

**Comment by davigonz** [comment]
Done, it will be included in 2.13
