### ISSUE TITLE
[FEATURE REQUEST] New permission in public links

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2624]
Public link folder has splitted up the `Download/View/Upload`permission in two:

- Download / View / Upload
- Download / View / Edit

This is the look in the web UI:

![Screenshot 2019-08-12 at 09 52 01](https://user-images.githubusercontent.com/14894746/62851840-cb8d1980-bce7-11e9-8acc-37d673ff7456.png)

Before, the  `Download / View / Upload` was a 15, now it is a 5.
`Download / View / Edit` is 15.

Other permissions did not change.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by pmaier1** [comment]
https://github.com/owncloud/android/issues/2667
