### ISSUE TITLE
[SPIKE] Authentication check

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2625]
The target of the current issue is checking the architectural/structural status of the authentication feature in order to split it up in several tasks that can be dealt in the Authentication epic: https://github.com/owncloud/android/issues/2608

Final results can be posted here, so we will create issues to have a cleaner epic

Issues created:

- Get rid of SAML implementation: https://github.com/owncloud/android/issues/2632
- Login flow: https://github.com/owncloud/android/issues/2634
- Unravel ownCloud Client + ownCloud Account mess: https://github.com/owncloud/android/issues/2635
- Open ID implementation: https://github.com/owncloud/android/issues/2633
- Stop supporting <10 servers: https://github.com/owncloud/android/issues/2636

**Comment by davigonz** [comment]
Spike finished, have a look at the issues posted in the first comment
