### ISSUE TITLE
[BUG] owncloud Android not sync all files

### ISSUE THREAD

**Issue by hafteto** [owncloud/android#2628]
### Actual behaviour

Not all files from server are synced to android. Manual or with Available Offline
Issues are with some *.js files that report error downloading.

Error: Download of xxx.js could not be completed.

Using Nextcloud Android client sync all files properly. 

### Expected behaviour
All files and extensions to be synced and downloaded to device.
 
### Steps to reproduce
Files are uploaded on server and synced with windows clients properly. The issues is only with android app. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No.

### Environment data
Android version: 9
Device model: Huawei P20
Stock or customized system: Stock 9.0.1
ownCloud app version: Ownloud Andoriid 2.11.1 and also next beta
ownCloud server version: ownCloud 10.2.1 (stable)
### Logs
No errors in log file.
#### Web server error log
No errors in log file.
#### ownCloud log (data/owncloud.log)
No errors in log file.
![Screenshot_20190817_084209_com nextcloud client](https://user-images.githubusercontent.com/54189100/63207474-d244d380-c0cf-11e9-9ea4-c9c0d432e7bd.jpg)
![Screenshot_20190817_091244_com owncloud android](https://user-images.githubusercontent.com/54189100/63207475-d2dd6a00-c0cf-11e9-92f2-9b87a7b626e7.jpg)

**Comment by hafteto** [comment]
Actualy found error in server log

{"reqId":"XVeSfrn8QFDIMrYMXPAw3wAAAAM","level":3,"time":"2019-08-17T05:37:02+00:00","remoteAddr":"10.10.10.1","user":"user","app":"index","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/256\/256\/folder\/band_1.js","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/user\\\/files\\\/folder\\\/band_1.js\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(130): OC\\\\Files\\\\Node\\\\Root->get('\\\/user\\\/files\\\/1P...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/PreviewManager.php(143): OC\\\\Files\\\\Node\\\\Folder->get('files\\\/folder...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ApiController.php(102): OC\\\\PreviewManager->createPreview('files\\\/folder...', 256, 256, true)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files\\\\Controller\\\\ApiController->getThumbnail(256, 256, 'folder\\\/band_...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ApiController), 'getThumbnail')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ApiController), 'getThumbnail')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('APIController', 'getThumbnail', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(911): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":192}"}

**Comment by hafteto** [comment]
Sophos Web Server Protection caused the issues.

**Comment by davigonz** [comment]
> Sophos Web Server Protection caused the issues.

Ok, glad to see it works for you now
