### ISSUE TITLE
[FEATURE REQUEST] Increase test coverage in SAF implementation

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2630]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
At the moment, i could not find any official documentation about how to test a document provider. So i close this issue for the moment. If there is any news about it, we could reopen it, and implement it.
