### ISSUE TITLE
Get rid of Travis

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2631]
Since new architecture sharing is merged into `master` branch, Bitrise is the CI system in which the app is built and tests are triggered.

So, at this point, we can get rid from Travis

### PR

- App: https://github.com/owncloud/android/pull/2642
- Library (if needed): https://github.com/owncloud/android-library/pull/261

**Comment by hannesa2** [comment]
> Since new architecture sharing is merged into `master` branch, Bitrise is the CI system in which the app is built and tests are triggered.

@jesmrec Please explain what are the 
* pro for Bitrise and 
* con for Travis 

for this decision.

**Comment by davigonz** [comment]
> I just want to know about the motivation doing so. Please explain what are the

> - pro for Bitrise and
> - con for Travis

> for this decision.

With Bitrise we can create workflows in an easier way as well as allowing us to execute UI tests while with Travis was practically impossible because Android emulators did not work properly.
