### ISSUE TITLE
[New arch] Unravel ownCloud Client + ownCloud Account mess (Session handling)

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2635]
The owncloud clients are objects used by the library to execute remote operations and contain credentials. These objects would be pretty easy to maintain if it weren't for the multiaccount support, which forces us to have a dependency between accounts and clients, reusing clients for an account.

Nowadays the creation of ownCloud Client is handled by different classes:
- OwnCloudClientFactory
- OwnCloudClientManagerFactory
- OwnCloudClientManager
- SimpleFactoryManager
- SingleSessionManager
- DynamicSessionManager

Thanks to [Get rid of saml implementation issue](https://github.com/owncloud/android/issues/2632) , we could:
- Get rid of `SINGLE_SESSION_PER_ACCOUNT` case in _OwnCloudClientManagerFactory_.

Thanks to https://github.com/owncloud/android/issues/2636, we could:
- Get rid of `SINGLE_SESSION_PER_ACCOUNT_IF_SERVER_SUPPORTS_SERVER_MONITORING` case in _OwnCloudClientManagerFactory_ since server monitoring is supported by default on >=10 servers. Therefore, _DynamicSessionManager_ would be no longer needed.

Once we clean up the way to handle ownCloud Clients we could create a factory of clients from accounts by using dependency injection with Koin (https://insert-koin.io/docs/2.0/documentation/reference/index.html#_declaring_injection_parameters)

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

### Related issues

- https://github.com/owncloud/android/issues/2626

**Comment by abelgardep** [comment]
I think we can close this. We are using koin to inject clients directly in the services.
