### ISSUE TITLE
Keep losing my settings 

### ISSUE THREAD

**Issue by swetoast** [owncloud/android#265]
Hi recently installed this wonder sync server and clients for all my devices although i come across a problem with the android client it keeps loosing my settings so i have to redo em one or twice a week

**Comment by marcin-gryszkalis** [comment]
Same here on Samsung S5, android 4.4.2

**Comment by davivel** [comment]
@radiofreekruzr , @marcin-gryszkalis , did you try to install the JB work around app I refered in https://github.com/owncloud/android/issues/265#issuecomment-26241524 ?

**Comment by wtwomey** [comment]
Should you have to do the JB work around on Lollipop? (Galaxy S4 5.0.1)

Same issue here, very annoying since it breaks instant upload which is the reason for using this app...

**Comment by radiofreekruzr** [comment]
I am now on an S6 and have no problems with the current build of the application.
