### ISSUE TITLE
[BUG] ownCloud icon doesn't appear in the list of opened apps

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2660]
### Actual behaviour
- ownCloud icon doesn't appear

[<img src="https://user-images.githubusercontent.com/15261363/64864830-39ef2f80-d638-11e9-8773-838b932568b2.png" width="350px"/>](https://user-images.githubusercontent.com/15261363/64864830-39ef2f80-d638-11e9-8773-838b932568b2.png)

### Expected behaviour
- ownCloud icon appears
 
### Steps to reproduce
1. Open the ownCloud app.
2. Open the list of opened apps by swiping down from the bottom of the screen

### Environment data
Android version: 10

Device model: Pixel 3 XL

Stock or customized system: Stock

ownCloud app version: - master

**Comment by donky106** [comment]
Hi, I would like to work on this issue

**Comment by michaelstingl** [comment]
I was just checking the 2.15-beta2 on my Pixel 4, and it seems it‘s no longer an issue.

![2020-05-25 23 39 42](https://user-images.githubusercontent.com/214010/82844622-6fdff580-9ee1-11ea-998b-22ea07d333b8.png)

**Comment by abelgardep** [comment]
I have not reproduced this glitch for a long time. So, I guess we can close this.
