### ISSUE TITLE
App doesn't react when iBlue is activated

### ISSUE THREAD

**Issue by shang001** [owncloud/android#2661]
### Actual behaviour
I have the app iBlue installed to diminish the impact of the blue light on the eyes. When it's activated, OwnCloud doesn't react: impossible to navigate to folders, to scroll, etc... It took me a long time to understand that when I disable iBlue, ownCloud can now react.

### Expected behaviour
When iBlue is activated, owncloud should continue to react to user actions.
 
### Steps to reproduce
1. Launch iBlue and activate it
2. Launch Owncloud
3. Attempt to navigate in folders

Can this problem be reproduced with the official owncloud server?
maybe
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:9

Device model: Samsung J3 2017

Stock or customized system:

ownCloud app version:2.12 release 4d954d50b

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/android/issues/1929

Please check docs:
https://doc.owncloud.com/android/#allow-light-filtering-apps
