### ISSUE TITLE
[BUG] Crash when only starting the app (OnePlus One, LineageOS, F-Droid)

### ISSUE THREAD

**Issue by magicbrothers** [owncloud/android#2684]
### Actual behaviour
- App crashes instantly after opening it. No interaction possible

### Expected behaviour
- Show a loginscreen or something (I dont know, because its the first time I (try to) use the app.)
 
### Steps to reproduce
1. Download from F-Droid
2. Install
3. Try to launch

### Environment data
Android version: 9

Device model: A001 (OnePlus One)

Stock or customized system: Custom (LineageOS 16.0)

ownCloud app version: 2.13.1 (F-Droid)

### Hopefully helpful logs (via ADB):

10-13 08:54:28.180  1503  4246 W ActivityManager:   Force finishing activity com.owncloud.android/.ui.activity.WhatsNewActivity
10-13 08:54:28.181  1503  4246 W ActivityManager:   Force finishing activity com.owncloud.android/.authentication.AuthenticatorActivity
10-13 08:54:28.203  1503  4246 W ActivityManager:   Force finishing activity com.owncloud.android/.ui.activity.FileDisplayActivity
10-13 08:54:28.224  1503  4246 E ActivityManager: Found activity ActivityRecord{b7da106 u0 com.owncloud.android/.ui.activity.FileDisplayActivity t-1 f} in proc activity list using null instead of expected ProcessRecord{24c3bbc 21231:com.owncloud.android/u0a141}
10-13 08:54:28.227   284   327 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - mAboveAppWindowsContainers#0
10-13 08:54:28.227   284   327 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - mAboveAppWindowsContainers#0
10-13 08:54:28.230  1503  2448 E AppOps  : Operation not started: uid=1000 pkg=android op=SYSTEM_ALERT_WINDOW
10-13 08:54:28.234   284  2621 W SurfaceFlinger: Attempting to destroy on removed layer: d648881 Application Error: com.owncloud.android#0
10-13 08:54:28.265  1503  4246 I ActivityManager: Killing 21231:com.owncloud.android/u0a141 (adj 0): crash
10-13 08:54:28.265  3561  3695 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
10-13 08:54:28.266  3561  3695 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
10-13 08:54:28.272  1503  1551 W libprocessgroup: kill(-21231, 9) failed: No such process
10-13 08:54:28.283   284   328 W SurfaceFlinger: Attempting to destroy on removed layer: a90103e com.owncloud.android/com.owncloud.android.ui.activity.FileDisplayActivity#0

**Comment by davigonz** [comment]
Hi @magicbrothers , thanks for reporting this, the logs you attach are pretty weird in my opinion so I suspect the problem is related with your custom OS, LineageOS 16. Do you have a different device to try the same steps? I've just downloaded 2.13.1 from F-Droid in a Android 10 device and it works like a charm, thanks!

**Comment by magicbrothers** [comment]
I tried it now on a Samsung Galaxy S4, also with LineageOS 16 and it crashed.
As you said, it's probably related to LineageOS, not the OnePlus One.
I dont know a lot about logs but if you can tell me, what you need, I can hopefully find it.
Thank you the answer! :)

**Comment by jesmrec** [comment]
@magicbrothers you will find here how to get logs:

https://github.com/owncloud/android/blob/master/TROUBLESHOOTING.md

**Comment by magicbrothers** [comment]
Now everything works fine :)
The newest version, but also the previously non-working version 2.13.1.
Probably the issue was something of my system.
