### ISSUE TITLE
[BUG] Apk file handling

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2691]
### Steps to reproduce
1. Store a correct apk inside an oC account
2. Tap to Download / Select "Open with"

### Actual behaviour
Nothing happens, neither downloading, nor "opening" with

### Expected behaviour
App must react to the user event. Options:

- If feasible, trigger the system installation wizard, so the apk started to install in case it is trusted and the system settings allow it
- Show an error, in case it is not posible to open. Specific formats like xsl or tar.gz implement also such behaviour
 

### Environment data
Android version: Reproducible with Android 9. Not reproducible with Android 7.

Device model:  Reproducible with MiA2 (v9), Huawei P20 (v9). Not reproducible with Nexus6P (v7)

ownCloud app version: 2.13.1

ownCloud server version: 10.3

CC @PVince81

**Comment by jesmrec** [comment]
brave enough to send a PR? :D

**Comment by armnotstrong** [comment]
> brave enough to send a PR? :D

[#3156](https://github.com/owncloud/android/pull/3156) Seems we only need the `android.permission.REQUEST_INSTALL_PACKAGES` permission

**Comment by jesmrec** [comment]
Done!! Ready to release in 2.18
