### ISSUE TITLE
AsyncTask to Kotlin Coroutines

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2714]
Asynctask will be [deprecated](https://www.xda-developers.com/asynctask-deprecate-android-11/), so it could be a good option to start moving current asynctasks to Kotlin Coroutines.

**Comment by farhazulMullick** [comment]
I installed this project on my local machine but Terminal window prompt "> Could not resolve project :owncloud-android-library:owncloudComLibrary."

 Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about its usage (required an API)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')

**Comment by michaelstingl** [comment]
> What can i do for a clean build

@farhazulMullick please use search to find previous issues:
https://github.com/owncloud/android/issues?q=is%3Aissue+%22could+not+resolve%22

You comment is unrelated to this issue. I'll hide it.

**Comment by abelgardep** [comment]
> I installed this project on my local machine but Terminal window prompt "> Could not resolve project :owncloud-android-library:owncloudComLibrary."
> 
> Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
> - Doesn't say anything about its usage (required an API)
> - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
> What can i do for a clean build

Hi @farhazulMullick, check this issue: https://github.com/owncloud/android/issues/3196

Probably you missed the `--recursive` clause when cloning the repo.

Follow the [setup guide](https://github.com/owncloud/android/blob/master/SETUP.md#1-fork-and-download-the-owncloudandroid-repository) and tell us if something is still wrong.

**Comment by abelgardep** [comment]
Related to this issue about Asynctasks and kotlin coroutines, we are replacing async tasks with coroutines along the way. So I think that we can close this issue.

**Comment by farhazulMullick** [comment]
@ablegardep are you working on this
issue if not i can work on this
