### ISSUE TITLE
Resize cloud image from drawer menu

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2715]
Some time ago we decided to include a cloud image in the side menu, starting with 2.8. As we detailed in https://github.com/owncloud/android/issues/2204 we made this to avoid the impression as if the app is not ready yet.

Since then, we have added to the drawer menu an Available offline option and a new one, Shared by link, is coming. So the cloud image doesn't look that good now and it could be removed in my opinion.

[<img src="https://user-images.githubusercontent.com/15261363/68774021-c87a3000-062c-11ea-9630-7a83185bdd29.png" width="350px"/>](https://user-images.githubusercontent.com/15261363/68774021-c87a3000-062c-11ea-9630-7a83185bdd29.png)

### PRs:
- App: https://github.com/owncloud/android/pull/2739

**Comment by ChrisEdS** [comment]
What about making it smaller and put it in the bottom right?

**Comment by davigonz** [comment]
> What about making it smaller and put it in the bottom right?

Well, we could give it a try
