### ISSUE TITLE
[New arch] Use Moshi to parse capabilities and get rid of RemoteCapability in library?

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2716]
[`GetRemoteCapabilitiesOperation.kt`](https://github.com/owncloud/android-library/blob/master/owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt) takes care of parsing the capabilities retrieved from the server in JSON format and transform them into RemoteCapability object.

Similarly to what we detailed in https://github.com/owncloud/android/issues/2704, we could use Moshi to make the parsing of capabilities.

#### IN ADDITION

Since RemoteCapability object and OCCapability (domain model)  objects are going to represent basically the same (when [modularization](https://github.com/owncloud/android/issues/2607) is finished), we could get rid of `RemoteCapability` and parse the JSON directly to `OCCapability` from the data layer.

Parsing JSON and transforming it to domain models in data layer is the most common scenario when connecting with external APIs but ownCloud for Android is a special case, we have an intermediate layer between the oC server and our app, which is the ownCloud Android Library. This library is meant to make the life easier to those interested in communicate an Android app with ownCloud servers. 

If we remove `RemoteCapability` from the ownCloud Android Library, the apps using it will receive just JSON and would need to parse it, so maybe is not the best idea if the aim of the library is "integrating your Android application with ownCloud seamlessly." 🤔 

Tasks:

- [ ] Move capabilities parsing from library to data layer, that will parse the JSON and transform it into OCCapability object. This OCCapability object is the domain model that will be retrieved from the data layer.
- [ ] Get rid of RemoteCapability class in library since is basically the same as OCCapability

### PR
- App: #2860 
- Library: https://github.com/owncloud/android-library/pull/298

**Comment by abelgardep** [comment]
### Capabilities
It would be good to know which capabilities are mandatory and are always sent to the client, and which are optional.

### Unused capabilities
There are two capabilities that are not being used anywhere. Remove them?
filesSharingPublicSendMail
filesSharingUserSendMail

### RemoteCapability
It is a simple facade of OCCapability inside Library. From my point of view, it can be removed. This way, the operation would return a CapabilityResponse which would be mapped to model(OCCapability) at OCRemoteCapabilitiesDataSource

**Comment by davigonz** [comment]
@jesmrec ready to test

**Comment by abelgardep** [comment]
> ### Unused capabilities
> 
> There are two capabilities that are not being used anywhere. Should we remove them?
> filesSharingPublicSendMail
> filesSharingUserSendMail

What should we do with those capabilities? @michaelstingl @jesmrec @davigonz

**Comment by jesmrec** [comment]
> What should we do with those capabilities? @michaelstingl @jesmrec @davigonz

Remove them (and any other) if they are not useful, please. Afaik, those capabilites are used to send a mail to the recipient when something is shared. This is nothing we are handling in the mobile apps.

**Comment by abelgardep** [comment]
Unused capabilities removed and tests updated.

**Comment by abelgardep** [comment]
I have split the issue into two separated PR:

Use moshi to parse capabilities:
- App: #2860 Library: https://github.com/owncloud/android-library/pull/298

Remove unused capabilities:
- App: #2874 Library: https://github.com/owncloud/android-library/pull/318

**Comment by jesmrec** [comment]
Done. Will continue in #2874
