### ISSUE TITLE
Support opentelemetry.io 

### ISSUE THREAD

**Issue by butonic** [owncloud/android#2723]
https://opentelemetry.io/ allow tracing requests from client to server.

**Comment by michaelstingl** [comment]
Hm, they have Java SDK, but no Kotlin 😢 : 
https://github.com/open-telemetry/opentelemetry-java

**Comment by tboerger** [comment]
IMHO this doesn't really make sense for clients, this only makes sense for complex micro service architectures where it's hard to debug the flow of requests.

**Comment by davigonz** [comment]
Thanks a lot for the suggestion @butonic , is it something similar to the [request ids](https://github.com/owncloud/android/issues/2055) we put some time ago on the headers or is completely different?
