### ISSUE TITLE
[BUG] ANR when uploading several pics from the camera

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2724]
### Steps to reproduce
1. In Settings, enable camera uploads for pics
2. Take many pics 
3. Wait till the pics start to upload (app open)

### Actual behaviour
Pics start to upload. Initially, everything goes OK. After some seconds, app shows the ANR dialog (bad use of UI thread?)

### Expected behaviour
Pics uploaded with no blockers 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 9.0

Device model: Huawei P20 Lite & Xiaomi MiA2

Stock or customized system: Stock

ownCloud app version: 2.13.1

ownCloud server version: 10.1

NOTE: versions newer than Android 9, reproduced as well.

**Comment by abelgardep** [comment]
Unable to reproduce it on Pixel 2 v10

**Comment by jesmrec** [comment]
After some rechecks performed with the current `master` (`348c201`) and the tag `oc-android-2.13.1` , i was not able to reproduce either. Some other unknown reasons made the problem to reproduce, but under the basics mentioned in the first message in Android 9, Android 10 aun current stable of the server, it is not.

I will close ftm, in case it becomes reproducible again, will reopen.
