### ISSUE TITLE
Android App failes to login with "§" in password on Nexus 4

### ISSUE THREAD

**Issue by mr-gosh** [owncloud/android#273]
In the Android App of owncloud the login failes when an "§" is in the password.

On the same device the login succeeds with caldavsync - carddavsync etc.

**Comment by davivel** [comment]
@mr-gosh, is this still a problem for you?

Thanks

**Comment by mr-gosh** [comment]
yes - i just created a user in my owncloud 7.0.3 installation....
passwords like "&%$üäö" or yust "äöü" didnt work out...

"test123" worked... ;-)

**Comment by davivel** [comment]
Thanks for the update! :)

**Comment by tobiasKaminsky** [comment]
Seems to be still a problem with core 8.1 and current app

**Comment by rperezb** [comment]
This is related to: https://github.com/owncloud/core/issues/7894

**Comment by davivel** [comment]
Please. let's track this issue in #1135. Thanks.

**Comment by davivel** [comment]
Sorry, I mean #1322
