### ISSUE TITLE
[FEATURE REQUEST] Logging with Timber

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2730]
Contribution by @hannesa2 

It's about to change logging from self-made to [Timber](https://github.com/JakeWharton/timber).

It removes the logic to display log and simply uses a Fragment from logging-lib.

It keeps all previous functions like 
* searching

![image](https://user-images.githubusercontent.com/3314607/68044868-82da7080-fcd8-11e9-9049-b6f6e338c685.png)

and adds 
* a tab for ownCloud Filelogging view
* a tab for Logcat view 
    * to see what happens on other processes too
    * to log what ownCloud forgot to log
    * within `release` build type !
* share log
* adds filter for `Verbose`, `Debug`, `Info`, `Warning`, `Error` 

Eg, when you select `Info` you will see only `Info`, `Warning`, `Error` entries and filters out `Verbose`, `Debug`

![image](https://user-images.githubusercontent.com/3314607/68045008-d77deb80-fcd8-11e9-8b6d-76e3bf6f2aeb.png)

So it helps to investigate, what's wrong with ownCloud.

All is encapsulated with a logging lib which I use in several places.
**I kept to old Log_OC** , to easy migrate and do not touch all files. Especially when you do a huge refactoring

One major advantage for developers:
Before:

![image](https://user-images.githubusercontent.com/3314607/68023509-94575480-fca7-11e9-8a48-ea105420bd25.png)

**NEW**:  you can **click log log line** and jump direct to code ! You see the linenumber as well

![image](https://user-images.githubusercontent.com/3314607/68023537-b2bd5000-fca7-11e9-96c2-d5d10739731b.png)

### PR

- App #2725 (Previously #2694)
- Library https://github.com/owncloud/android-library/pull/283 (Previously https://github.com/owncloud/android-library/pull/275)

**Comment by abelgardep** [comment]
I have created this issue to keep track of every change in the same place and have a better organization @hannesa2 . BTW, thanks for pushing to oC repo 👍

**Comment by davigonz** [comment]
Merged, to be included in 2.14, thanks @hannesa2 for the contribution
