### ISSUE TITLE
[TESTING] Setting tests flakiness 

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2732]
I was working on #2728 and at some point, I executed all the tests to check that are working as expected and noticed that some of the tests related to settings seem to be a bit flaky. I switched to master branch and try it there again but the result is pretty similar, could you check them @jesmrec ? 

- 1st execution, 5 tests failing:

![Screenshot 2019-11-20 at 13 02 03](https://user-images.githubusercontent.com/15261363/69237495-1eebef00-0b96-11ea-94a6-8b2662d68229.png)

- 2nd execution, 3 tests failing

![Screenshot 2019-11-20 at 13 03 51](https://user-images.githubusercontent.com/15261363/69237552-388d3680-0b96-11ea-8003-1a5188df13e5.png)

- 3rd execution, 4 tests failing

![Screenshot 2019-11-20 at 13 05 48](https://user-images.githubusercontent.com/15261363/69237685-80ac5900-0b96-11ea-90cd-8968368604ce.png)

- 4th execution, 5 tests failing

![Screenshot 2019-11-20 at 13 07 58](https://user-images.githubusercontent.com/15261363/69237820-cec15c80-0b96-11ea-9085-d613af482b9b.png)

Device: Samsung Galaxy S9
Android Version: Android 9

PR: https://github.com/owncloud/android/pull/2737

**Comment by davigonz** [comment]
@jesmrec the setting tests are not being executed on Bitrise for now, in order to move forward pending PRs without relaunching the tests multiple times. Please ping me as soon as they work fine on your local (emulator or Samsung Galaxy S9) and I will put them back

**Comment by jesmrec** [comment]
> @jesmrec the setting tests are not being executed on Bitrise for now, in order to move forward pending PRs without relaunching the tests multiple times. Please ping me as soon as they work fine on your local (emulator or Samsung Galaxy S9) and I will put them back

@davigonz with the PR https://github.com/owncloud/android/pull/2737, tests are not failing anymore in the real device. But, before merging, we can give a try in the PR branch to know what happens under CI.
