### ISSUE TITLE
Make OwnCloud a source of files to other apps in the device through regular ACTION Intents 

### ISSUE THREAD

**Issue by malexmave** [owncloud/android#274]
Dropbox has done this already. If an application asks you what (generic) file to open, Dropbox is one of the options (like OI File Manager and friends), but OwnCloud is not.

Ideally, it would be like Dropbox: Allow me to pick a file from inside OwnCloud, download it to a temporary location and pass it back to the calling application.

**Comment by jesmrec** [comment]
Done as Android document provider
