### ISSUE TITLE
Reduce logging in ChunkFromFileRequestBody

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/android#2743]
**Is your feature request related to a problem? Please describe.**
I wanted to track down a bug while uploading a video (The video upload was canceled with "Unknown error". Now it doesn't appear again), but I only see the following three messages over a dozen of times per second. This makes the log viewer in Android Studio unusable.
````
2019-11-30 11:53:51.628 22964-16558/com.owncloud.android D/ChunkFromFileRequestBody: Read 4096 bytes from file channel to java.nio.HeapByteBuffer[pos=4096 lim=4096 cap=4096]
2019-11-30 11:53:51.631 22964-16558/com.owncloud.android D/ChunkFromFileRequestBody: Write 4096 bytes to sink buffer with size 0
2019-11-30 11:53:51.631 22964-16558/com.owncloud.android D/ChunkFromFileRequestBody: Sink buffer size: 0
````

**Describe the solution you'd like**
Remove the logging from there.

**Describe alternatives you've considered**
Make the logging debug version only.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App: https://github.com/owncloud/android/pull/2764
- Library (if needed): https://github.com/owncloud/android-library/pull/284

**Comment by hannesa2** [comment]
I agree, there is sometime a lot of noise in log and I would see this as an verbose log entry.
Btw, to be able to handle such noise, I introduced a filter function https://github.com/owncloud/android/pull/2725#issuecomment-554977209

**Comment by hannesa2** [comment]
I made a fix for this https://github.com/owncloud/android-library/pull/284

**Comment by davigonz** [comment]
Merged, thanks @hannesa2 for the contribution
