### ISSUE TITLE
[BUG] Authentication info lost. Authentication failed. Auth retry does not end

### ISSUE THREAD

**Issue by Klausthorn** [owncloud/android#2745]
### Actual behaviour
I see that file edits on my android do not get synced any more (they do not appear on my Windows Desktop). I open the android app on the phone to see what is going on. The app shows: authentication failed. I touch the provided "edit account"(my own translation from German app) and enter my password again. App shows that it it tries to log in... and does not get to an end for minutes. Neither success nor fail, just spinning...  I close the app and try again. Problem repeats. Stays that way for a few days. I even lose a file that I created on my android and that is gone now.

Now during bug reporting I try again several times. After trying like 5 times and turning the phone down for several minutes and then picking it up it suddenly authenticated.

In the months prior: (history of the problem, may not be relevant) the app already did ask to authenticate again, but succeeded. Like every few days or several times a day. In fact it seemed to be the behavior as in https://github.com/owncloud/android/issues/2356 , but that is just my impression. And then in worsened for me so that I could not log in any more. hence the bug report.

### Expected behaviour
- app does not lose my auth info
- app, if it loses my auth info, is able to log me in again after I re-enter my password (I tried via laptop browser successfully, so server seems to be fine. using same wifi as android, so internet connection seems fine)
- app, if not able to log me in again, does not keep on spinning for minutes but tells me what the problem is

### Steps to reproduce
Those would be nice, but it does not happen consistently. suddenly the app cannot log in.

### Can this problem be reproduced with the official owncloud server?
Good idea, but right now it works anyway.

### Environment data
Android version: 10

Device model: google pixel 3a

Stock or customized system: stock. bought it, accepted the upgrade to android 10 that the phone offered me.

ownCloud app version: v2.13.1 release 6a5f775cf ... found this after a long time in settings. Why settings! the version is not a setting, is it!

ownCloud server version: version.php has ...

$OC_Version = array(10,0,10,4);
$OC_VersionString = '10.0.10';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = [[8,2,11],[9,0,9],[9,1]];
$OC_Build = '2018-09-17T11:07:09+00:00 097d4d22e0cf3341c4923e26453efb32ddedfb24';

#### Web server error log
I would give it to you, but how can I be sure that it does not include security tokens? It does contain strings like "requesttoken" and strings that are part of so many lines that they could be a validation that the browser sends with most request.

#### ownCloud log (data/owncloud.log)
After quite some time I realized that you do not refer to a URL path but a file path. I suggest that you make that clearer in the instructions.

I would give it to you, but how can I be sure that it does not include some security token?

**Comment by michaelstingl** [comment]
@Klausthorn could you verify if this issue still exists after upgrading the server to 10.3.1 ? 10.3 got some improvements regarding auth tokens etc…

You can enable a debug log inside the app. Here you can find more information:
https://github.com/owncloud/android/blob/master/TROUBLESHOOTING.md

You don't need send the full log, just find the few lines with the error, and redact the sensitive parts.

**Comment by maxim-kukushkin** [comment]
In my case the behavior is even more weird - after losing authentication and re-entering login/password, the app accepts them, but then immediately fails on any actual operation (like directory listing), showing the same popup about failed authentication.

Adding another account on the same phone works fine. The same account also works fine in iOS app, 2 Linux PC apps and in all browsers (including the browsers on the same Android phone). So it's definitely Android App entering some unrecoverable state for one single account.

OC Server: 10.4.1.3
Server logs on authentication failure:
```
[16/Jul/2020:00:00:44 +0100] "PROPFIND /owncloud/remote.php/dav/files/myuser/ HTTP/1.1" 207 344
[16/Jul/2020:00:00:45 +0100] "GET /owncloud/ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 401 123
[16/Jul/2020:00:00:45 +0100] "GET /owncloud/status.php HTTP/1.1" 200 154
[16/Jul/2020:00:00:45 +0100] "GET /owncloud/ocs/v2.php/cloud/user?format=json HTTP/1.1" 401 123
[16/Jul/2020:00:00:45 +0100] "PROPFIND /owncloud/remote.php/dav/files/myuser/ HTTP/1.1" 401 306
```
I have lots of files and lots of cherry-picked folders synced and doing re-sync to re-create the account is just a nightmare! I've already done this several times cause OC client doesn't support simple URL change

**Comment by maxim-kukushkin** [comment]
One more detail - I can't say for sure but it seems like it entered such a state during a bulk downloading of a large number of files for offline availability. It was quickly downloading files one after another (files were about 2-3MB and the connection was LAN) and then suddenly authentication failures notification appeared in Android notifications

Android App version: 2.15 release 4984a047c

**Comment by crackmonkey** [comment]
I'm seeing the same behavior when trying to sync 9G of music. It was working for a while then at some point, possibly when switching from work to home WiFi, it flipped out and started failing every download, but still moving onto the next file. I'd tried the sync a few weeks ago with the same result, plus draining my battery lower than I think I've ever had it. 
I had to delete the account and re-add it before it would start syncing today. Reauthenticating just resulted in the same "Authentication Failed Change Account" message popping up over the app toolbar and '"message":"Login failed:' in the owncloud.log

Pixel 3a, Android 10 July 5 security patch level.
Android App 2.1.5
OwnCloud 10.4.1
Debian Buster
Apache 2.4.38-3+deb10u3 + libapache2-mod-php7.3 7.3.19-1~deb10u1

Hmm, from logcat in Android Studio:
2020-07-27 18:35:21.977 30584-30681/? E/AndroidRuntime: FATAL EXCEPTION: FileDownloaderThread
    Process: com.owncloud.android, PID: 30584
    java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs

**Comment by jesmrec** [comment]
Could you confirm that the issue is gone with the recent released 2.15.3?

**Comment by KlausThornProgrammfabrik** [comment]
> @Klausthorn could you verify if this issue still exists after upgrading the server to 10.3.1 ?

I upgraded my owncloud server softare to ...

$OC_Version = array(10,5,0,10);
$OC_VersionString = '10.5.0';
$OC_Channel = 'stable';
$OC_Edition = 'community';
$OC_Build = '2020-08-03T07:20:02+00:00 dc16af58beb6050976fd62bf683da0232034e1c6';

... and since then (6 weeks) the problem did not appear again. Thanks for your contributions!

**Comment by KlausThornProgrammfabrik** [comment]
> Could you confirm that the issue is gone with the recent released 2.15.3?

I indeed have owncloud Android App 2.15.3 release 13511f58e and the problem ist gone. However, it is unclear wether the app or the server software upgrade (see above) did solve it.

Thanks for your contributions!

**Comment by maxim-kukushkin** [comment]
To me the Android App update solved the problem as I haven't updated the server in a while (my bad, should do so for security patches...)

**Comment by jesmrec** [comment]
Ok, problem seems to be fixed! Feel free to reopen (or open new tickets) if you detect it again.

Thanks all for your reports and contributions, helping the product to improve!
