### ISSUE TITLE
Short user names / group names are not found as recipients

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2747]
### Steps to reproduce
1.  In `config.php` set  `user.search_min_length' => 4`,
2. Create a user called `123` and a group called `456`
3. Try to share an item with them 

### Actual behaviour
Not posible, so they do not reach the 4 characters needed to start searching

### Expected behaviour
They should be posible to share with.

After checking the web UI and desktop client, they follow the value of `user.search_min_length` but in case there is a shorter-name recipient that matches the typed pattern, they show it. This is, repeating the steps 1. and 2. above:

3. Type `123`  (or `456`)

Current: `123` (or `456`) is shown in the list, even when its length does not reach the minimum in `config.php`.

Xiaomi MiA2 , Android 9
oC 10.3

**Comment by michaelstingl** [comment]
@jesmrec @davigonz clients should ignore the capability and fire every request after every keystroke to the server (maybe min.delay). Server will decide if there are results…

**Comment by jesmrec** [comment]
Will do for the next release

**Comment by abelgardep** [comment]
> @jesmrec @davigonz clients should ignore the capability and fire every request after every keystroke to the server (maybe min.delay). Server will decide if there are results…

Should we remove this capability completely from app and library? Or just ignore it?

**Comment by michaelstingl** [comment]
From my understanding, capability doesn’t solve any problem in the mobile apps. Up to you if you want to remove it or keep it unused.

**Comment by abelgardep** [comment]
I will remove it then.
