### ISSUE TITLE
[BUG] Open xls-files or doc-files with Docs to Go

### ISSUE THREAD

**Issue by alexanderbruns** [owncloud/android#2749]
### Actual behaviour
- I open a file with owncloud-client and it is opened in "Doc to Go". I have a non-root device Samsung Galaxy S7 with Android 8. When I want to safe the file, it is not saved in the owncloud area. Doc to Go asks for giving another location, I can only save it to a local directory on the android device. If I then again open the file in owncloud it is the status before the save in Doc to Go. It is not saved to a folder of owncloud so the file in owncloud is not uploaded.

### Expected behaviour
- If I press save in Doc to Go the data should be in owncloud and synced to the owncloud-server.
 
### Steps to reproduce
1. Open Owncloud-client on Android Smartphone
2. select an office-document like an xls-file
3. open it. and try to get the changes saved automatically to owncloud.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

yes

### Environment data
Android version: 8.0.0

Device model: Galaxy S7 SM-G930F

Stock or customized system: custom system from samsung

ownCloud app version: 2.13.1 release 6a5f775cf

ownCloud server version: 10.3.0

#### ownCloud log (data/owncloud.log)
{"reqId":"4fa428cb-bbc9-4a01-abe4-e394d6c75059","level":0,"time":"2019-12-04T00:04:02+00:00","remoteAddr":"192.168.154.254","user":"boerns","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/boerns\/","message":"updating token 2585, last check is now 1575410130"}
{"reqId":"4fa428cb-bbc9-4a01-abe4-e394d6c75059","level":0,"time":"2019-12-04T00:04:02+00:00","remoteAddr":"192.168.154.254","user":"boerns","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/boerns\/","message":"token 1f7863e4796a31554aa8a29e4951629c94f8d36756aa620df6bcef2c9cec4af45ea4972c6b9512e12e3df9dc18168c862a2985061fdae49c89028e1ff81da394 does not exist"}
{"reqId":"39c9a8d6-da52-4b6c-898b-8c212130f374","level":0,"time":"2019-12-04T00:04:09+00:00","remoteAddr":"192.168.158.169","user":"boerns","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/boerns\/Ausgaben.xls","message":"updating token 2595, last check is now 1575417722"}
{"reqId":"39c9a8d6-da52-4b6c-898b-8c212130f374","level":0,"time":"2019-12-04T00:04:09+00:00","remoteAddr":"192.168.158.169","user":"boerns","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/boerns\/Ausgaben.xls","message":"token 1f7863e4796a31554aa8a29e4951629c94f8d36756aa620df6bcef2c9cec4af45ea4972c6b9512e12e3df9dc18168c862a2985061fdae49c89028e1ff81da394 does not exist"}

Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/android/issues/2319 ? I recommended to use the new document provider integration. This would mean, opening the file FROM you document editing app via the document provider integration. If you save your changes, the original file gets updated automatically. 

Could you check if Docs to Go support the document provider integration?

Direct storage access won't have a bright future on the Android platform: https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html

**Comment by alexanderbruns** [comment]
Hi, yes it is a dublicate as the other issue is closed. The App has a provider integration for Dropbox or google-drive but not for owncloud.

If not working, why owncloud-app offers me to open the xls-files with Docs to Go?

**Comment by abelgardep** [comment]
> Could you check if Docs to Go support the document provider integration?

No, Docs to Go does not support Document Provider (SAF) integration yet. 

You can try apps like MS Word or Excel that support this integration.

**Comment by michaelstingl** [comment]
> No, Docs to Go does not support Document Provider (SAF) integration yet.

Meh. That's not good. But thanks for checking @abelgardep !

Changes in local storage / file system can't be synced back to the ownCloud server. ==> Works as designed

**Comment by jesmrec** [comment]
Scoped storage together with Document provider make this posible.

Fixed inside 2.21
