### ISSUE TITLE
[BUG][Xodo] Changed pdf file uploaded, but seemingly not changed on server

### ISSUE THREAD

**Issue by tutebatti** [owncloud/android#2752]
### Actual behaviour
When downloading a pdf within the android app and changing it with Xodo reader, then pressing the sync button, an upload bar will display as usual, but at the end, the time stamp of the file is still the same and on other devices, where no syncing happens. When opening the file from within owncloud app, the changes made in Xodo do appear. When file is deleted locally and downloaded again, the changes made do not appear in the "new" file from the server.

### Expected behaviour
(a) Either there is a bug with Xodo, which saves the altered file in a different folder. However, if the actual file within the owncloud-folder wasn't changed, I'd expect a message, though, right?
or
(b) If Xodo does in fact apply the changes to the right file, the timestamp should change after the upload and the syncing should effect the other devices.

### Environment data
Android version: 7.1.2

Device model: Samsung Note 8

Stock or customized system: Lineage 14.1

ownCloud app version: 2.13.1 release 6a5f775cf [via FDroid]

ownCloud server version: 10.3.0.4

-----
App PR: https://github.com/owncloud/android/pull/3220
Library PR: https://github.com/owncloud/android-library/pull/396

**Comment by michaelstingl** [comment]
@tutebatti Changes in local storage / file system can't be synced back to the ownCloud server. Please access data from 3rd party apps via Document Provider (SAF, **Downloads** in Android 7 and 8 or **Files** in Android 9+):
https://owncloud.org/news/owncloud-android-2-11-0/

Direct storage access won't have a bright future on the Android platform: https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html

**Comment by tutebatti** [comment]
@michaelstingl Thank you for your reply. However, I'm facing the same issue. The file is uploaded after alteration, no error message displayed, but effectively does not change on the server.

**Comment by michaelstingl** [comment]
Performed quick tests in Xodo and Word, both via Document Provider. Works in Word, but fails in Xodo. I need to have a closer look…

**Comment by jesmrec** [comment]
I perform the same test in Xodo, taking a PDF file form ownCloud. Modified file is in the device (you can check the changes correctly) but not synced to the server. This is what i have seen, i hope it can help:

1. File is modified in Xodo
2. File starts to sync (notification is there)
3. In my case, i used a 7MB file, so it is chunked-upload (1MB chunks). Several `PUT` operations are sent and all of them finish correctly.
4. The assembled file in server fails when it is moved to the target

![Screenshot 2020-01-10 at 10 38 54](https://user-images.githubusercontent.com/14894746/72142650-6d975780-3395-11ea-9962-1d92034280aa.png)

5. So, the following `PROPFIND` over the moved file, returns the same information than before the modification (dates displayed in the app are fetched from server, not from the date in the file itself). I've made the changes today but the retrieved last modified date is:

![Screenshot 2020-01-10 at 10 43 42](https://user-images.githubusercontent.com/14894746/72142963-265d9680-3396-11ea-91b6-296135500c9f.png)

Why is it failing in step 4.? Server logs are telling us this:

`{"reqId":"66886dab-2359-4b7d-b88c-53ed2dfc483a","level":4,"time":"2020-01-10T09:48:55+00:00","remoteAddr":"172.17.0.1","user":"user1","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/user1\/94a230fea29fce20ed8420e0e2a032a31578649726818\/.file","message":"Exception: HTTP\/1.1 400 Chunks on server do not sum up to 2652399 but to 2658115: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"Chunks on server do not sum up to 2652399 but to 2658115\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php(57) ... `

so, the server expects a file of 2652399b, but 2658115 are there (6K extra).  

I've seen several issues regarding this problem in server, but all of them appears as fixed. Apart of that, as @michaelstingl said, is not reproducible with other file editors. Maybe someone in server side can put some light here? @PVince81?

**Comment by davigonz** [comment]
Maybe xodo generates a file with an unexpected file size, after modifying it? Need to check it

**Comment by PVince81** [comment]
or one of the sent chunks is bigger. can you check the exact size of each chunk and see which of the sizes match the total ?

At the beginning of the upload, there's also a header "OC-Total-length" that a client can send. See if the client is sending it maybe with the wrong value ?

**Comment by jesmrec** [comment]
I repeated the scenario with the skeleton file `ownCloud Manual.pdf` 

Initially, the origin file's size: 5097180 B

After modifying it (adding a new page) , the size in local is 5112704 B 

There are 5 PUT operations (`Content-Length` header)

1024000 B
1024000 B
1024000 B
1024000 B
1016704 B

summing up 5112704 B, matching the size.

and the server exception:

`Chunks on server do not sum up to 5083143 but to 5112704` 

so... it is expecting a smaller size (5083143) than the original (5097180) even when the file is bigger. 

Keep researching.

**Comment by PVince81** [comment]
@jesmrec I believe that the server is comparing that announced total size that the client sends with the "OC-Total-Length" header. Please check what value the client is sending, if at all. If none then it's a different mechanism.

**Comment by jesmrec** [comment]
you are right @PVince81. In case on the client, the header is included in the final `MOVE` (the one that fails):

`OC-Total-Length:  5083143 `

this field is read from the `OCFile` object as parameter of the `ChunkedUploadFileOperation` that's being executed by the `OwncloudClient` (this is all Android stuff).

Checking where exactly is this value coming from.

**Comment by vtwebguy** [comment]
I appear to be having the same issue. The android client is thinks the upload was successful, but the server shows 400: Chunks on server do not sum up ... A small text file change worked, so seems to be limited to larger files. In this case the binary I'm having issue with is 8.9 MB. Please let me know if I may be of assistance in providing more data.

**Comment by michaelstingl** [comment]
@vtwebguy Xodo only?

We only can reproduce this with Xodo, no other app. No more information needed. The team is busy with other tasks, didn't start deeper investigation.

**Comment by vtwebguy** [comment]
@michaelstingl In my case I am saving changes with keepassdroid. The owncloud client sees the change and attempts to push it and even thinks its successful, but the server throws 400 with issues around the chunking. I can reopen the local keepass file and see the changes have persisted on my device. Should I move to new issue?

**Comment by michaelstingl** [comment]
> Should I move to new issue?

We can have a look to decide if it's the same problem or different problem. Thanks for your feedback!

**Comment by rashato** [comment]
Experiencing the same issue with the latest download of Xodo 5.0.22 Edition 75808. Any turn around?

**Comment by abelgardep** [comment]
Not yet. In upcoming release 2.16, we will include network logs that may help us to identify where the problem is.

Apps that use the Documents Provider should not have this problem. In medium-long term apps should use this approach to interact with files from other apps due to Scoped Storage.

**Comment by rashato** [comment]
I've reported the bug related to the wrong file size in: http://feedback.xodo.com/forums/241992-suggest-a-new-feature/suggestions/42269266-bug-report-wrong-file-size 
by pointing out the link to this discussion.

**Comment by retodomax** [comment]
I can reproduce the same issue when opening the pdf with [pdf viewer/editor of the Onedrive app](https://play.google.com/store/apps/details?id=com.microsoft.skydrive&hl=en&gl=US). It is again the same behavior. Files below 1MB are updated on owncloud, files above 2MB not.

**Comment by theScrabi** [comment]
Ok I could reproduce this with any file bigger than 1MB. This means all bigger files using the `/dav/uploads` endpoint for chunked syncing is broken. Apparently uploading chunks uses a different endpoint when syncing. When normally uploading a file a `<path/to/file>/<filehash>/` endpoint is used. This works fine.

**Comment by theScrabi** [comment]
After uploading the chunks to the server we need to tell the server to concat the chunks and move the file to its final destination. The issue here is that the move command has a filesize in its header. We take this size from the local database representation of the file. However If xodo or any other app changed the filesize of the actual file on disk, the size in the database differs. In the case of our MOVE method we send the filesize of the file before the modification. So how should we progress here?
Should we update the filesize in the local database before uploading, or should we send the size of the local file and update the size in the DB after upload?
https://github.com/owncloud/android/blob/2d496fcfa8a70e186e0773d58899b1fcbbefcf15/owncloudApp/src/main/java/com/owncloud/android/operations/ChunkedUploadFileOperation.java#L82

**Comment by theScrabi** [comment]
However when uploading the chunks there appeared another issue to me: The etag send by the client differs from the one in the server. The client tells the server via `If-Match` header in the PUT method for uploading a chunk to not accept another etag. Therfore chunking fails already at the PUT method without ever reaching the MOVE method described above.

**Comment by jesmrec** [comment]
> Should we update the filesize in the local database before uploading, or should we send the size of the local file and update the size in the DB after upload?

That's a good question. If the user modifies the file (stored in oC) by using an external app and submit the changes, he/she implicitly accepts the modification. If feasible, we should use the new size to work with. What do you think?

**Comment by theScrabi** [comment]
> If feasible, we should use the new size to work with. What do you think?

So you say we should modify the filesize in the db before upload then?

**Comment by jesmrec** [comment]
yes, this is my opinion. File has changed by user's willing and it is still an item in the account. Does it make sense that after changing, we keep having wrong info in the database about it?

**Comment by theScrabi** [comment]
I don't know if the database at all atm. I assumed it was maybe updated after the upload.

**Comment by jesmrec** [comment]
cc @abelgardep

**Comment by abelgardep** [comment]
You need to check `SynchronizeFileOperation`. There, we check if there were local changes and request the upload in that case.

**Comment by felix-schwarz** [comment]
An `If-Match` header should only be part of a `PUT` request if the goal is to avoid overwriting an existing file version other than the version whose `ETag` is sent in the `If-Match` header.

If there is no previous version of a file in that place, there is no `ETag` to compare against, so the condition is not met. Therefore, I'd expect a `PUT` with `If-Match` to be rejected by the server if it is the initial upload of the file.

If the upload replaces an existing file, it could make sense to include an `If-Match` header in the `MOVE` request, to make sure the upload will only replace the version of the file last known by the client. There's only a brief mention of this in the comments of https://dragotin.wordpress.com/2015/06/22/owncloud-chunking-ng/ though.

**Comment by felix-schwarz** [comment]
Here's the logic for whether to set `If-Match` (when replacing) or `If-None-Match: *` (on initial upload) in the iOS SDK:
https://github.com/owncloud/ios-sdk/blob/2a17e752847e269bafcde12e7c50a4e60d646545/ownCloudSDK/Connection/OCConnection%2BUpload.m#L634

**Comment by theScrabi** [comment]
> An `If-Match` header should only be part of a `PUT` request if the goal is to avoid overwriting an existing file version other than the version whose `ETag` is sent in the `If-Match` header.
> 
> If there is no previous version of a file in that place, there is no `ETag` to compare against, so the condition is not met. Therefore, I'd expect a `PUT` with `If-Match` to be rejected by the server if it is the initial upload of the file.
> 
> If the upload replaces an existing file, it could make sense to include an `If-Match` header in the `MOVE` request, to make sure the upload will only replace the version of the file last known by the client. There's only a brief mention of this in the comments of https://dragotin.wordpress.com/2015/06/22/owncloud-chunking-ng/ though.

All right if I read this correct we should not add the `If-Match` header in the `PUT` methods of a chunked upload, but only in the final `MOVE` method.

**Comment by TheOneRing** [comment]
The desktop does set "If-Match" if the upload is an update of an existing file, if its a new file the header is not set.
In addition the ng implementation only sets the header for the destination the header is not set on the partial puts.
https://github.com/owncloud/client/blob/master/src/libsync/propagateuploadng.cpp#L335-L339
