### ISSUE TITLE
Cannot invoke method replace() on null object

### ISSUE THREAD

**Issue by ashfaqahmed** [owncloud/android#2753]
Hello, i just have tried to import this latest repository via android studio using option `'Import Project (Eclipse ADT, Gradle, etc)'` as per the documentation, but i am having issue with it it says.

`ERROR: Cannot invoke method replace() on null object` and error looks on file build.gradle on method `getGitOriginRemote()`

Please let me know if anyone can help in this or having same kind of issue ?

Android studio version : 3.5.3
Mac OSX Catalina.

**Comment by michaelstingl** [comment]
@ashfaqahmed this is the issue tracker of the ownCloud Android app, not a help forum. Please use https://central.owncloud.org/ instead.
