### ISSUE TITLE
Remove "Delete merged branch" bot

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/android#2760]
From its [Readme](https://github.com/SvanBoxel/delete-merged-branch):

> You may not need this app as GitHub recently added this feature natively to their platform. It allows you to automatically delete the head branch after a merge. If you need more advanced controls and configuration settings, this app is still well suited for the job.

Since you don't have a `.github/delete-merged-branch-config.yml` file in the repo, there's no advanced config.

https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by michaelstingl** [comment]
I activated the "Automatically delete head branches" setting in this repo, but I didn't delete the GitHub App "Delete merged branch" yet, because it's enabled for all `org:owncloud`.

**Comment by tboerger** [comment]
I dislike to remove the bot as this can be centrally controlled instead of the need to configure this on every repository.

**Comment by mueller-ma** [comment]
I prefer to give permissions to as less parties as possible, but of course, it's up to you to decide.

**Comment by jesmrec** [comment]
Useful bot. Not intended to remove
