### ISSUE TITLE
[BUG] crash in Room concerning wrong version

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2778]
Of course, I can increase the db version, but this is not he root cause. 
In my point of view, any db migration should work from any version to another following up version. 
Currently I'm on `DB_VERSION = 28`

Any ideas what's wrong here ?

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/3314607/71678060-7d56e080-2d84-11ea-93ac-73874d1e16c7.png">

**Comment by hannesa2** [comment]
I found only one migration `MIGRATION_27_28` and I miss the other ones.

**Comment by hannesa2** [comment]
I fixed it with https://github.com/owncloud/android/pull/2780 and https://github.com/owncloud/android/pull/2779 to have at least a version. But I was forced to 
1. install new version (to have the chance to complete remove old database)
2. deinstall new version (remove old database)
3. install new version again to have a new database

**Comment by hannesa2** [comment]
I tested it on my wife phone and these 3 steps were not necessary, only 

3. install new version again to have a new database 

was required.
So, #2779 fixes it and #2780 is not really required

**Comment by davigonz** [comment]
If #2779 fixes it and is already merged, I guess we can close this.
