### ISSUE TITLE
[BUG] App crashes when trying to connect to server secured with self signed certificate

### ISSUE THREAD

**Issue by Burdu** [owncloud/android#2785]
Not sure if this app is supported anymore. I can probably put up a PR for this after digging into it. Creating the ticket anyway.

### Actual behaviour
App crashes when trying to connect to server secured with self signed certificate

### Expected behaviour
App should not crash
 
### Steps to reproduce
1. Have a server secured with self-signed certificate
2. Open the app and try to connect to it

### Environment data
Android version: 9

Device model: OnePlus 5T

Stock or customized system: stock

ownCloud app version: 2.14.1

ownCloud server version: ownCloud 10.0.10 (stable) 

### Logs

``` java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 15785
    java.lang.IllegalArgumentException: The host activity must implement com.owncloud.android.ui.dialog.SslUntrustedCertDialog.OnSslUntrustedCertListener
        at com.owncloud.android.ui.dialog.SslUntrustedCertDialog.onAttach(SslUntrustedCertDialog.java:116)
```

### PRs:
- App: https://github.com/owncloud/android/pull/2795

**Comment by Burdu** [comment]
Not sure if any implementation is needed on `AuthenticatorActivity` for the methods defined in  `OnSslUntrustedCertListener` interface. Adding the interface to  `AuthenticatorActivity` quick fixed the issue for me locally.

**Comment by michaelstingl** [comment]
> Not sure if this app is supported anymore. I can probably put up a PR for this after digging into it. Creating the ticket anyway.

Sure, the app is fully supported and the team works hard to make the app [more reliable and future proof.](https://owncloud.org/news/re-architecting-the-owncloud-app-for-android/) Thank you very much for reporting the issue!

**Comment by jesmrec** [comment]
Reproduced, will fix for the next release.

**Comment by jesmrec** [comment]
Ready to 2.14.2

**Comment by erikman** [comment]
I am a beta user for the android app and just got a new version (2.14.2 beta I guess). The Owncloud app is no longer crashing with a self-signed certificate (I get a dialog box where I can accept the fingerprint).

But after entering my credentials I am stuck at "trying to log in..." with a spinner. Don't know if this is related to the self signed certificate or not, but the app is working on an older phone where I've been logged in "for ages". Please tell me if you want a separate bug report instead.

**Comment by michaelstingl** [comment]
@erikman thank you very much for your valuable feedback. Better open new issue and provide all necessary information
