### ISSUE TITLE
[FEATURE REQUEST] sync trigger to be executed on android tasker to start folder sync

### ISSUE THREAD

**Issue by elschman** [owncloud/android#2789]
**Is your feature request related to a problem? Please describe.**
Currently one of the photo apps on my phone are not able to store the picture on the folder which is used from owncloud client and the other photo app to sync with my server.
Therefore tasker is coping the pictures to the correct folder but a sync is not started.
I would like to tell the client ... do a folder sync .. or .. a new picture is stored. Sync it.

**Describe the solution you'd like**
I would like to have a trigger which can be used from tasker to start a folder sync...
I would like to tell the owncloud client ... do a folder sync .. or .. a new picture is stored. Sync it! ...from tasker

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
With tasker, you mean https://tasker.joaoapps.com/ ? (Paid 3rd party app, similar to [iOS Shortcuts](https://apps.apple.com/app/shortcuts/id915249334))

**Comment by elschman** [comment]
yes nice tool to get things done

**Comment by michaelstingl** [comment]
There are no plans to detect changes on the filesystem. Also accessing the filesystem for apps will be heavily restricted in future Android versions. Does tasker support the Android `DocumentsProvider` / Storage Access Framework (SAF)?

**Comment by elschman** [comment]
I dont think so
 

Immo Wetzel
PGP Fingerprint (GMX) : D894 088D 3CE5 D769 7B89 518B E009 4219 129E 4642
ICQ: 30151767
Skype: immo_we

 
 

Gesendet: Dienstag, 14. Januar 2020 um 13:17 Uhr
Von: "Michael Stingl" <notifications@github.com>
An: owncloud/android <android@noreply.github.com>
Cc: elschman <elschman@wetznet.de>, Author <author@noreply.github.com>
Betreff: Re: [owncloud/android] [FEATURE REQUEST] sync trigger to be executed on android tasker to start folder sync (#2789)


There are no plans to detect changes on the filesystem. Also accessing the filesystem for apps will be heavily restricted in future Android versions. Does tasker support the Android DocumentsProvider / Storage Access Framework (SAF)?

**Comment by michaelstingl** [comment]
Just FYI, Google introduced "Rules" for Android:
https://9to5google.com/2020/03/02/android-rules-google-pixel-rollout/

New ownCloud iOS app has [support for iOS Shortcuts](https://owncloud.org/news/current-state-of-ios-app-version-1-3-0/), so it would be nice if something similar could be added to the Android apps too. (Someday maybe…)

**Comment by jesmrec** [comment]
Scoped storage does not allow to select/update external folders anymore. 

Feel free to reopen
