### ISSUE TITLE
[BUG] Crash when uploading pictures

### ISSUE THREAD

**Issue by xoocoon** [owncloud/android#2811]
### Actual behaviour
owncloud client on Android freezes when uploading pictures from smartphone. The following messages appear in random order:
- Hochladen fehlgeschlagen
- android.process.media wurde beendet
- Medienspeicher wurde beendet
Eventually the entire upload process aborts.

**There is no problem on another device with the same client app version!**
Alternative device is Samsung SM-T113, Android 4.4.4

### Expected behaviour
Upload functioning properly without any error messages, interruptions and abortions.
 
### Steps to reproduce
1. Select 44 photos on the smartphone (either in Samsung Gallery or in the file manager)
2. Choose "share" and select the owncloud app for sharing.
3. Select an arbitrary folder in the owncloud app and start the upload process.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
YES

### Environment data
Android version: 9

Device model: Samsung Galaxy A40 (2019)

Stock or customized system: Stock

ownCloud app version: 2.14.2

ownCloud server version:
version  10.3.2.2
versionstring  10.3.2
edition  Community
productname  ownCloud

#### Client log
[ownCloud_client_upload-Android-9.log](https://github.com/owncloud/android/files/4174447/ownCloud_client_upload-Android-9.log)

#### Web server error log
[ownCloud_server_upload.log](https://github.com/owncloud/android/files/4174519/ownCloud_server_upload.log)

#### ownCloud log (data/owncloud.log)
[owncloud.log](https://github.com/owncloud/android/files/4174515/owncloud.log)

**Comment by davigonz** [comment]
Thanks @xoocoon for reporting this, we'll try to reproduce the issue and see where the crash comes from.

**Comment by jesmrec** [comment]
i was not able to get a crash, but i can reproduce the fact not every of the selected files is uploaded (not always reproducible). I mean, i share 30 files but finally there are not 30 files in the target folder.

Device: Samsung S9 (Android9)

This one deserves a look... very soon we will review and refactor all the synchronization in the app. Seems a good momento to check.

**Comment by jesmrec** [comment]
Not reproducible anymore. Feel free to reopen if still reproducible on your side.
