### ISSUE TITLE
[BUG] Cant click in any button / inputs

### ISSUE THREAD

**Issue by rapz** [owncloud/android#2828]
### Actual behaviour
- I just cant click, so i cant really use the app

### Expected behaviour
- I managed to login even without clicking/touching anything

### Steps to reproduce
1. Install
2. Open
3. Cant click

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:
Android 9
OxygenOS 9.0.10

Device model: 

OnePlus 5T
A-5010_43_191231

Stock or customized system:
OnePlus 5T OxygenOs Stock

ownCloud app version: Cant retrieve, since i cant click

ownCloud server version:
10.3.2
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Do you have any installed app fir light filtering or similar? (like twilight)

**Comment by jesmrec** [comment]
@rapz do you still reproduce the problem?

**Comment by abelgardep** [comment]
Hi @rapz, feel free to re-open this issue if you still have the same problem with version 2.16 👍
