### ISSUE TITLE
[BUG] Czech translation is not correct

### ISSUE THREAD

**Issue by MJ-sys** [owncloud/android#2835]
### Actual behaviour
Czech translation is very poor and sometimes not correct. I am willing to help in translating I just don't know the location of that file. When someone points me to the correct direction, I can submit a pull request.

### Environment data
ownCloud app version: 2.14.2 (fe23fedb4)

**Comment by jesmrec** [comment]
Translations are a community feature to have in the [Transifex](https://www.transifex.com/) platform.

you can sign up and then, translate/review the available strings for your language. Is there any aditional requirement @michaelstingl?

**Comment by michaelstingl** [comment]
Maybe we could improve instructions here:
https://github.com/owncloud/android/blob/master/CONTRIBUTING.md#translations

CZ-Android project:
https://www.transifex.com/owncloud-org/owncloud/viewstrings/#cs_CZ/android/13685867

@ChrisEdS or @DeepDiver1975 need to approve new team members in Transifex.

**Comment by MJ-sys** [comment]
Signed up (user `MJ_sys`). Waiting (probably) for approval.

**Comment by MJ-sys** [comment]
All unclear translations reviewed. Does it automatically appear in the next update or do I have to do something for that?

**Comment by michaelstingl** [comment]
@MJ-sys new Transifex translations should arrive every night in the source code:
https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/values-cs-rCZ/strings.xml

Everything that's in this file will also be included in the beta and in the next release.

Here you can learn how to become a beta tester:
https://owncloud.org/news/be-the-first-to-test-new-android-features-become-an-owncloud-beta-tester-in-just-2-steps/

**Comment by jesmrec** [comment]
Next release (2.15) will include your translations. thanks!

**Comment by DeepDiver1975** [comment]
close? THX

**Comment by MJ-sys** [comment]
You're welcome :-) . I'm a happy user of owncloud for years. I'm glad to be helpfull :-)
