### ISSUE TITLE
Search also in subfolders

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/android#2839]
### Actual behaviour
-Tell us what happens
Only file results in the current directory are displayed.
### Expected behaviour
-Tell us what should happen
 Shows all found files from all subfolders (maybe only from folders you have already shown with the app)
### Steps to reproduce
1. Search a file in one subdirectory
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:
Android 10
Device model: 
Huawei P30
Stock or customized system:

ownCloud app version:
2.14.2 release fe32fedb4
ownCloud server version:
oC. 10.3.2
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
Yeah, current „local search“ is more like filtering the current directory. Real search feature is tracked in https://github.com/owncloud/android/issues/695
