### ISSUE TITLE
[BUG] Cannot enter server address

### ISSUE THREAD

**Issue by Catfriend1** [owncloud/android#2842]
### Actual behaviour
Entering https://mycompany-owncloud/oc and it says invalid character. Omitting https:// does not help either.

### Expected behaviour
It should accept that address and let me go on.
 
### Steps to reproduce
1. Download from fdroid v. 2.14.2
2. Enter an address with "-"
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No.

### Environment data
Android version: 10.0 MIUI 11

Device model: xiaomi mi8

Stock or customized system:

ownCloud app version: 2.14.2

ownCloud server version: Owncloud X

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
why do you think that the problem is the "-" character? any evidence? I have an address with "-" and works for me, by checking with Fdroid 2.14.2 and official release.

Are you sure the URL is correct and reachable?

Which error message is displayed?

Thanks in advance for reporting!

**Comment by Catfriend1** [comment]
Hmm the app crashed multiple times and showed this after auto reopening. Did uninstall and clean install a second time and it worked. Strange.
