### ISSUE TITLE
[FEATURE REQUEST] New account management

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2849]
Next step of #2742 

AC:

- Account management will be moved from drawer to toolbar, on the top right.
- We will see the avatar of the current account
- When we click on that thumbnail, a dialog will appear. 
- We will be able to see all accounts in oC app, lock account, delete account.
- Every account will show the display name and below the username@server
- In case multiaccount is enabled (this is by default), there will be an option to create a new account, that prompts to login view
- An option to edit an account will be available. It will point to login view, sending URL to fill up there. URL must be disabled, only available a password change.

| Old account handling | New account handling |
| ------------- | ------------- |
| ![Old account handling](https://user-images.githubusercontent.com/15261363/74653151-e2756280-5187-11ea-8041-0d2e9ba282f9.png) | ![Account handling](https://user-images.githubusercontent.com/15261363/74652595-aa215480-5186-11ea-9c26-7c5aa7584971.png) |

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
### AC to discuss

1. Will be this thumbnail visible only at root folder? (Related with https://github.com/owncloud/android/issues/2847)
2. What happens with `Uploads` view? Currently there is menu in that position, should that menu be moved to a similar menu in uploads list view? https://github.com/owncloud/android/issues/2848)
3. Should we add something like `app_name` to drawer header? it may feels empty only showing the background image

**Comment by jesmrec** [comment]
> 1. Will be this thumbnail visible only at root folder? (Related with #2847)

What would get the slot in case of non-root folder? a longer search bar?  

> 2. What happens with Uploads view? Currently there is menu in that position, should that menu be moved to a similar menu in uploads list view? #2848)

I'd set two different menus here, splitting the current one: one for cleaning the list, and other one for manually retries. Setting  a bar just above the list  sounds a good option. 

> 3 Should we add something like app_name to drawer header? it may feels empty only showing the background image

But, this is the behaviour right now, isn't it? in the drawer header we are showing the accounts and nothing else. 

> 4. Should we show the Quota of every account in that dialog?

It is also a good option, showing the quota just below the username. But keeping the current place is not bad either. Open to more discussion.

**Comment by ChrSchultz** [comment]
I wish annother possibility to add an account via Url like:
 
   oc:///login/user:<username>&password:<app-passwd>&server<server-url>

**Comment by abelgardep** [comment]
> I wish annother possibility to add an account via Url like:
> 
> ```
> oc://login/user:<username>&password:<app-passwd>&server<server-url>
> ```
There is a problem with that approach. We need to check server status first to check which authentication methods are available. Maybe with basic authentication it would be possible but not with oAuth or OIDC. Thanks for the suggestion anyway 👍

**Comment by ChrSchultz** [comment]
It only works with the app-password, generated with owncloud. So it would be possible to get the url via qrcode from the server...and import the acc direct by scanning the qrcode.--Christoph Schultz Stütensen 229571 Rosche e-mail: ic-schultz@gmx.de 

 
  
  
 
 Am 26.10.20, 09:58 schrieb "Abel García de Prada" <notifications@github.com>:

   
   
   I wish annother possibility to add an account via Url like: 
   oc://login/user:<username>&password:<app-passwd>&server<server-url>

 
   
  There is a problem with that approach. We need to check server status first to check which authentication methods are available. Maybe with basic authentication it would be possible but not with oAuth or OIDC. Thanks for the suggestion anyway 👍

**Comment by jesmrec** [comment]
> It only works with the app-password, generated with owncloud. So it would be possible to get the url via qrcode from the server...and import the acc direct by scanning the qrcode.--Christoph Schultz Stütensen 229571 Rosche e-mail: ic-schultz@gmx.de Am 26.10.20, 09:58 schrieb "Abel García de Prada" <notifications@github.com>: I wish annother possibility to add an account via Url like: oc://login/user:<username>&password:<app-passwd>&server<server-url> There is a problem with that approach. We need to check server status first to check which authentication methods are available. Maybe with basic authentication it would be possible but not with oAuth or OIDC. Thanks for the suggestion anyway 👍 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

Please, open a new ticket with the suggested new feature. In the current ticket, we will discuss about UI/UX. Thanks!!

**Comment by CarolinaCst** [comment]
I) Account Management 

As described in the previous issue, the new account will be located top right in a regular top bar.

-  By clicking on the avatar a new small modal drawer will appear.  
    In this section users would be able to manage their Account and add another account. 

![image](https://user-images.githubusercontent.com/60343863/97481442-1fb80400-1955-11eb-92e8-7d800edbee1f.png)

- Here are different sections like: Home, Personal info, Data & personalisation shown on a extended top bar and 

![image](https://user-images.githubusercontent.com/60343863/97480235-6f95cb80-1953-11eb-9c9d-18db33b33ac9.png)

![image](https://user-images.githubusercontent.com/60343863/97481442-1fb80400-1955-11eb-92e8-7d800edbee1f.png)

**Comment by CarolinaCst** [comment]
After the Meeting of 03.11.2020, here are the following agreements:

1. Account Management design proposal

![image](https://user-images.githubusercontent.com/60343863/98017944-3d2b1900-1e00-11eb-93de-f329b4ebd5b3.png)

2. Properties should be discuss in the future sessions
![image](https://user-images.githubusercontent.com/60343863/98019111-a8c1b600-1e01-11eb-8726-88e35a9bc9e7.png)

**Comment by michaelstingl** [comment]
> 1. Properties should be discuss in the future sessions

No plans to manage account settings in native client UI. It's sufficient for users to do this in the regular web UI.

**Comment by JuancaG05** [comment]
Closing this, more updated issue for the same purpose opened:
- https://github.com/owncloud/android/issues/4312
