### ISSUE TITLE
Sync interval

### ISSUE THREAD

**Issue by ghost** [owncloud/android#285]
In the account settings for Android one can merely enable or disable auto syncing.
What is the (default) sync interval?

Are there any plans to extend this option?
I did not find anything in here: https://github.com/owncloud/design/tree/master/mobile

My thoughts:
The user should be able to set two sync intervals (1h, 4h, 8h, 12h, daily, weekly, ...): One for wifi sync, one for data connection.
Also, it would really be cool to allow individual sync times for specific files. E.g. shopping.list.txt -> 1h, rest weekly sync.

**Comment by leafcutterant** [comment]
@davivel If you don't want to flood regular users with these kinds of options, I can understand that. That's also how many other apps approach this subject and what they do it they collect all the fine-tuning settings under a separate menu called e.g. "Advanced settings". The regular user won't go there (even the name deters them) and the advanced user is happy to have it.
