### ISSUE TITLE
[BUG] App does not accept TLSv1.3 

### ISSUE THREAD

**Issue by mapaongh** [owncloud/android#2855]
### Actual behaviour
- When I switch the webserver to only accept TLSv1.3 Connections and Ciphers I got a SSL Handshake Error in the owncloud app

### Expected behaviour
- Correct connection between device and server
 
### Steps to reproduce
1. Webserver Server Configuration to only accept TLSv1.3

### Environment data
Android version: 9
Device model: Galaxy S8
Stock or customized system: Stock
ownCloud app version: 2.14.2
ownCloud server version: 10.4

**Comment by abelgardep** [comment]
Android 10 introduced support for TLS v1.3 https://developer.android.com/about/versions/10/features#tls-1.3, so this will be tested as part of #2576. @jesmrec

**Comment by jesmrec** [comment]
Targeting Android 10 will be part of the next release. So, TLS 1.3 will be supported as well.

If you have any further comments, regards, or suggestions, feel free to reopen.

**Comment by michaelstingl** [comment]
2.15.1 with support for TLSv1.3 is available in Play Store now!
