### ISSUE TITLE
[BUG] Crash when changing orientation in some operations

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2857]
### Steps to reproduce
1.  Select an item in the file list
2. Select copy or move operation
3. When the folder picker is displayed, change orientation

### Actual behaviour
App crashes

### Expected behaviour
App does not crash

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 10

Device model: Pixel 2

Stock or customized system: Stock

ownCloud app version: 2.14.2

ownCloud server version: 10.4

**Comment by davigonz** [comment]
@jesmrec ready to test
