### ISSUE TITLE
[BUG] Unable to log in with basic authentication

### ISSUE THREAD

**Issue by Vlad8161** [owncloud/android#2878]
### Actual behaviour
After logging in with a basic authentication type server responds 401 on FileDisplayActivity.

### Expected behaviour
After logging in FileDisplayActivity shows root folder correctly.
 
### Steps to reproduce
1. Open app
2. Log in with basic authentication (not OAuth)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

No, this problem can't be reproduced on the official server

### Environment data
Android version: 9
Device model: huawei nova 3i
Stock or customized system: stock
ownCloud app version: 2.15-beta
ownCloud server version: 10.1.0

I made a small research and found out that after refactoring on new architecture LoginBasicAsyncUseCase writes user id to the account name field, but in the last stable release a user name was written in this field. This behavior causes OwnCloudClient sending user id instead of user name in Authorization header. If i change user id to user name everything works perfectly. Is this a mistake or expected behavior of authentication system?

**Comment by abelgardep** [comment]
Thanks for reporting. I'll take a look.

**Comment by jesmrec** [comment]
Did you upgrade from 2.14.2 to the beta or fresh install? are you using any special set up like LDAP  backend?

**Comment by Vlad8161** [comment]
It is a fresh install. Unfortunately I don't have access to server configuration but LDAP backend is highly possible option.

**Comment by abelgardep** [comment]
Hi @Vlad8161, thanks for your feedback! We were able to reproduce it and it will be fixed in a new beta version: https://github.com/owncloud/android/issues/2879

**Comment by Vlad8161** [comment]
Thanks a lot

**Comment by jesmrec** [comment]
@Vlad8161 we have released 2.15-beta2. If you wat to take a look and let us know, it'd be appreciated.

**Comment by Vlad8161** [comment]
New version (2.15-beta2) works fine. Thanks :)

**Comment by abelgardep** [comment]
It's great to hear that, if you have any other problem, tell us!

I close this issue for the moment if it is not reproducible anymore.
