### ISSUE TITLE
[FEATURE REQUEST] Redirection callback from OAuth2

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2883]
When users have two (or more) different oC apps in the device, the OAuth2 redirection is always the same and user is force to select which of the apps should be opened. 

Android system will ask for that, and user can choose if the selection is `Always` or `Just Once`. In case the selection is `Always`, no matter which app triggers the OAuth2 authorization flow, from now on the redirection will point to the same (the chosen one).

![Screenshot 2020-11-18 at 17 17 21](https://user-images.githubusercontent.com/14894746/99556543-f291cb00-29c1-11eb-9bef-69d2fe8ac312.png)

So, the redirection, `oc://android.owncloud.com` should be brandable and code must be adapted for that.

Using appID (unique) as redirection

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App: https://github.com/owncloud/android/pull/3020
- Library (if needed): https://github.com/owncloud/android-library/pull/358

**Comment by michaelstingl** [comment]
Yeah, idea was to use the app ID for this (must be unique)

**Comment by jesmrec** [comment]
In server, the registered client must include the redirection:

![Screenshot 2020-10-02 at 14 40 28](https://user-images.githubusercontent.com/14894746/94924238-7567d080-04bd-11eb-9feb-facabe59fe40.png)

so, it must be included manually or branded somehow in server. Could this be a problem? If we start using `appId` as default for redirection, every server will be forced to do that change in the clients' set up.

Other option is keeping `oc://android.owncloud.com` as default and no mandatory. And in case any customer wants an specific redirection, warning to change also in server.

**Comment by michaelstingl** [comment]
Hm, if admins want to add a new client with new redirect URL, they'll get also new client ID and client secret. Then better make it a branding option.

![CleanShot 2020-10-02 at 16 35 01](https://user-images.githubusercontent.com/214010/94935505-6f79eb80-04cd-11eb-996e-642280a7a0eb.png)

**Comment by jesmrec** [comment]
Regarding this feature:

- Redirection URI is actually a brandable parameter in the app:  https://github.com/owncloud/android/blob/da8e4a7d8f075e2283a9c27915ab71ccfecf302a/owncloudApp/src/main/res/values/setup.xml#L82

- Parameter is available to be branded in oB

So, it is already posible to brand the redirect URI with the following steps:

1. In admin dashboard > User Authentication, add a new client by entering a name and a correct redirection URI. It will return a secret id and a client id
2. in branding system/setup file, input all those parameters: redirection URI, client id and secret id

@michaelstingl please correct me if i'm wrong or i missed something. If those steps are enough, we can close this one.

**Comment by abelgardep** [comment]
I have some news here.

Yes, you are able to create a new client, with name, redirect URI and client ids. At the moment, if you create a new branded version and include those new fields, it won't work since the android app will ask for `oc` at the start of the redirect URI. We have `manifestPlaceholders = [appAuthRedirectScheme: 'oc']` in the build gradle. More info [here](https://github.com/openid/AppAuth-Android#capturing-the-authorization-redirect).

I have tested it creating a new client, and building the app with new redirect URI and clients and adding `manifestPlaceholders = [appAuthRedirectScheme: 'test']` to the build gradle.

AndroidTesting | test://android.owncloud.com
-- | --
