### ISSUE TITLE
[BUG] Edit different account credentials leads to AccountNotTheSameException

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2886]
### Actual behaviour
- When you have some accounts and you edit not the current one credentials, you won't be able to edit them.

### Expected behaviour
- You should be able to edit them.
 
### Steps to reproduce
1. Go to account management
2. Edit credentials for a different account (Not the current one)
3. Enter correct credentials
4. Account not the same exception is shown

![bug-lock-different-account](https://user-images.githubusercontent.com/47524927/83261627-eddf1d80-a1bb-11ea-9673-4cfe1d1fbfea.gif)

Problem remains in OCLocalAuthenticationDataSource, it checks if username differs from current account username.

**Comment by jesmrec** [comment]
Fixed. To be released in 2.15
