### ISSUE TITLE
Disabling oauth leads to NPE (AppAuth)

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#2891]
### Steps to reproduce

1. Login in a OAuth2 account
2. In web UI, as admin go to Settings > Apps > OAuth2, and disable it. Also, OAuth2 can be disabled with the occ command `occ app:disable oauth2`
3. Refresh

Current: app crashes
Expected: Needed re-authentication, will be with basic auth.

Android 9, Samsung S9

_Originally posted by @jesmrec in https://github.com/owncloud/android/pull/2800#issuecomment-585201614_

This crash comes from the AppAuth Library and it was fixed but not released yet.
https://github.com/owncloud/android/pull/2800#issuecomment-585319714

**Comment by jesmrec** [comment]
Not reproducible anymore with the current `master` after replacing AppAuth with our custom implementation. Fix will be available in 2.17.
