### ISSUE TITLE
[SPIKE] Scoped storage

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2894]
- [x] Selectable? brandable?
- [x] Document providers integration
- [x] Migration from old storage
- [x] Android 11 -> MUST. Android 10 selectable. Android < 10 ¿?
- [x] Check the way files are stored. To know if blocks new arch advance.

### Interesting links and documentation
https://developer.android.com/training/data-storage/use-cases
https://developer.android.com/training/data-storage/app-specific
https://www.youtube.com/watch?v=RjyYCUW-9tY

### When Scoped Storage is a must?
It depends on which android version our app targets. Currently oC Android App is moving to Android 10 via #2576, and will use `requestLegacyExternalStorage` since it is not ready to move completely to Scoped Storage yet. [Source](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage)

When an app targets:

- Android < 10 -> Will keep using old storage access.
- Android 10 -> Default to scoped storage, but can request access to legacy storage by adding this flag into the manifest `requestLegacyExternalStorage` and setting it to `true`
- Android > 10 -> Default to scoped storage, and will ignore `requestLegacyExternalStorage`

### How to migrate from legacy to scoped Storage?
A directory is considered a legacy storage location if it isn't an app-specific directory or a public shared directory. Currently oC App is using a 'legacy storage location', so we need to migrate all of those files to an app-specific directory.

We could follow [this instructions to do it](https://developer.android.com/training/data-storage/use-cases#migrate_app_data) taking care when moving to [Android 11](https://developer.android.com/training/data-storage/use-cases#if_your_app_targets) . If we don't migrate those files and we change to scoped storage, [we will lose access to old files](https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage).

### Current behaviour 

oC App uses `Environment.getExternalStorageDirectory()` to get the root folder where every oC file will be downloaded. This return the primary shared/external storage directory. We can access this directory from computer, or almost any files manager since it is a top-level directory. This behaviour let users access oC files using any app that can read/write external storage.

Not only when app is installed, but also after uninstalling it, those files will be there until users remove them. This issue was reported several times in the repository. And with scoped storage, it won't happen anymore. A pro, and a con.

### Scoped storage behaviour

Android App will use `getExternalFilesDir` or `getFilesDir` to generate the root folder where every oC file will be downloaded. Those directories are app-specific storage and have some differences between them, we can check [this](https://developer.android.com/training/data-storage#InternalVsExternalStorage) to know more about them. If we store our app data here, those files will be removed once user uninstall our app. 

Using this approach, apps could access our files using the Documents Provider we developed some time ago and our files will be more secure because not any app could access them.

### Selectable, brandable?
For me, it makes no sense to have a selectable or brandable option to avoid scoped storage. Scoped storage is a reality, and we should adapt it as soon as posible since it will be mandatory in the long-term. Once we decide to move to scoped storage, we should move completely to perform the migration(legacy ->scoped) just one time.

### Providers integration
DocumentsProvider -> Works as expected, files are available through DocumentsProvider, and other apps can access ownCloud files the same way they were accessing before.

### Issues found in ownCloud App when using scoped storage
- Camera Uploads may stop working. Currently we are using a custom implementation to select which folder we want to synchronize automatically. 
We should move to storage access framework to select which folder we want to synchronize. We already moved to that behaviour when uploading files in #2436. We could use a similar implementation but using [this](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE) to get the directory where our photos are stored. -> #2899

- Downloaded files on previous versions (legacy storage) will be shown as downloaded on new version(scoped storage) and each time we want to access to that file, a `java.io.IOException: Permission denied` will reach. Should be fixed on migration.

- Upload files: won't work since we create a temporal folder and store there a copy before uploading to server. Should be fixed when replacing `Environment.getExternalStorageDirectory()` with `getExternalFilesDir` or `getFilesDir`.

- Download files: won't work since we store files in a subdirectory of `Environment.getExternalStorageDirectory()` which is not accessible anymore. Should be fixed when replacing `Environment.getExternalStorageDirectory()` with `getExternalFilesDir` or `getFilesDir`.

### Old issues related with Scoped Storage (Archeology)
- Files remain if deleting account (#125) - Will be fixed if we move to scoped storage and use app-specific directory

**Comment by jesmrec** [comment]
Some questions on my side:

- We keep the condition of blocking the access to document provider via Passcode/Pattern. So, if the app is protected, documents inside will not be reachable. Is that correct?

- Does it affect to `JobScheduler` in any way? for the auto uploads and av. offline stuff

- Will the file structure inside the "sandbox" be the same as the current one?
 
- Is there any flag, or way to access the content inside with, f. ex., testing purposes?

**Comment by abelgardep** [comment]
>     * We keep the condition of blocking the access to document provider via Passcode/Pattern. So, if the app is protected, documents inside will not be reachable. Is that correct?

Yes, you are right. We could add a new preference to enable or disable documents provider in that case.
>     * Does it affect to `JobScheduler` in any way? for the auto uploads and av. offline stuff
It should not affect av offline synchronization but yes, it definitely will affect autouploads
>     * Will the file structure inside the "sandbox" be the same as the current one?
Yes
>     * Is there any flag, or way to access the content inside with, f. ex., testing purposes?
I'm not sure at all, let's wait for the Android 11 beta feedback.

**Comment by abelgardep** [comment]
Spike finished, will be implemented via #2877
