### ISSUE TITLE
[BUG] App never stops loading/syncing; I can't interact with it

### ISSUE THREAD

**Issue by lefherz** [owncloud/android#2900]
### Actual behaviour

Since the upgrade to 2.15, whenever I open the app, I see it loading.

Apparently it tries to synchronize my local folder tree with the server; but even after hours of this, if I open a new folder, it can't show me contents it didn't see before.

If I try to create a public link, it shows a loading bar and never completes (after 5 minutes I was tired of waiting and just closed the app). If I try to share a folder, it doesn't show me autocomplete suggestions, and I can't tap on "ok".

The problematic behavior was present right after the upgrade from 2.14. Then I re-installed the app, but the bug re-appeared a few hours after re-installation.

Another interesting component: instead of my profile picture, I see a default avatar. When the bug was gone directly after re-installation, I saw my profile pictures again. This seems to be related.

I have two accounts. One possible explanation is that the app worked until I added my second account; I have yet to try that out specifically.

### Expected behaviour

The app should be able to connect to the server, show profile pics, synchronize the file tree, share files & folders, and create public links.
 
### Steps to reproduce
1. Install ownCloud Android 2.15
2. Login to the account
3. Do something, e.g. download a folder, which should work, notice the existing profile picture
4. Login to a second account
5. close the app
6. wait one and a half hours

**Can this problem be reproduced with the official owncloud server?** yes, one of the two accounts I used was demo@demo.owncloud.org.

### Environment data
Android version: 9

Device model: SM-G900F Samsung Galaxy S5

Stock or customized system: LineageOS build 20200605

ownCloud app version: 2.15

ownCloud server version: 10.4.1, 10.3.2

#### Web server error log

Exclusively log messages with the Android 2.14.2 user agent in the access log.

**Comment by jesmrec** [comment]
Not sure how can affect the fact of running under LineageOS. Will take a look.

**Comment by abelgardep** [comment]
@lefherz, could you try to reproduce if that problem happens with a single account?

I was able to reproduce a problem with multiaccount that leads to #2626 and it is related with cookies. We send the proper authentication header but cookies are not properly refreshed and response matches with the account we logged before. I performed a quick test removing cookies and it worked as expected.

CC/ @michaelstingl @hosy @jesmrec

**Comment by lefherz** [comment]
This isn't reproducible anymore. Maybe a server migration helped fixing this. Feel free to reopen if anyone else runs into this.
