### ISSUE TITLE
[BUG] Files not downloading - getting "Sync failed" repeatedly

### ISSUE THREAD

**Issue by domestomas** [owncloud/android#2905]
### Actual behaviour
After logging to my account on owncloud.cesnet.cz, i marked some folders available offline, however only few of them were downloaded. After that I got notification "Sync failed". I has been few days and nothing changed, when I open the app, there is still progress bar loading (moving dots) and occasionaly i get "Sync failed" notification, so I don't have access to most of my files. Files which hasn't been downloaded can't be accessed even in online mode - the app just displays "Loading...".

Log file in attachment.
[ownCloud.log](https://github.com/owncloud/android/files/4809547/ownCloud.log)

### Expected behaviour
The files should be downloaded to the device.
 
### Steps to reproduce
1. Add account with about 70 GB data on the storage
2. Set some folders as available offline
3. Wait if the folders download

### Environment data
Android version: 10

Device model: Xiaomi Mi A3

Stock or customized system: Default android with no modifications

ownCloud app version: Version 2.15 release 4984a047c

ownCloud server version: 10.0.10 (stable)

Edit: log file after another 3 days: 
[owncloud.2020-06-21.log](https://github.com/owncloud/android/files/4823939/owncloud.2020-06-21.log)

**Comment by jesmrec** [comment]
Thanks for reporting, we''ll take a look into there.

**Comment by jesmrec** [comment]
I was not able to reproduce this, beyond https://github.com/owncloud/android/issues/2574. Fixes for the current one and https://github.com/owncloud/android/issues/2574 could be related. If you have any other detail or information relevant, please let us know.

**Comment by jesmrec** [comment]
We have just released 2.15.1. Could you take a look if the problem is still reproducible?

**Comment by domestomas** [comment]
Sorry for the delay, I wasn't able to test it during holidays, I had too bad internet connection. Now it works fine, after about 30 hours 14 of 25 GB is downloaded, so thank you for fixing :) I just sometimes get "no internet connection" notification, which is weird, because I have fast stable internet connection (100 Mb/s). Also the download is slower than on desktop app (there i uploaded 25 GB in about 5 hours), although I'm on the same wifi. But these are just weird things, nothing important. Thanky you again for the fix.

**Comment by jesmrec** [comment]
Thanks to you for reporting and checking!!!!
