### ISSUE TITLE
Fatal Exception: Not allowed to start service Intent

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2911]
Does someone understand what's wrong here ?
It happens **very** often

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/3314607/85914327-084cfb00-b83d-11ea-8ca1-0e7b87a410a4.png">

**Comment by abelgardep** [comment]
It could happen because we are trying to start that service in background and since Android O is not allowed. It may be fixed the same way it was solved here: https://github.com/owncloud/android/blob/b9147667bf5115a09db6e519caffd60fa2e24e87/owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java#L91

**Comment by hannesa2** [comment]
I'm happy, when this is the root cause and you solve it.
I guess, there are a lot installations out there, where it happens. Something like [this](https://github.com/owncloud/android/pull/2726) would be very helpful. I use it currently, that's why I see such things

**Comment by abelgardep** [comment]
We opened [this](https://github.com/owncloud/android/issues/2798) issue to speak about this topic. It would be great to have the discussion there.

**Comment by jesmrec** [comment]
Needed a service review here. Moving to current 2.16 milestone.

**Comment by abelgardep** [comment]
We should move every background job to [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) in which we could configure constraints and schedule periodic works.

**Comment by hannesa2** [comment]
I guess because of the revert the error is not eliminated. https://github.com/owncloud/android/pull/2402#issuecomment-462792336

I reintroduced it and it's error free (till now), but as a side-effect a new permanent notification appears 👎
