### ISSUE TITLE
[BUG] add ownCloud url to mobile -> version is lower than 10

### ISSUE THREAD

**Issue by cs35-owncloud** [owncloud/android#2915]
Hello,

since the new android version (2.15), you cannot add the ownCloud URL to your app if the server has the parameter **'version.hide' => true,** in its config.php ...

All our servers are up to date:

```
# occ status
  - installed: true
  - first_install_version: 10.2.1.4
  - version: 10.4.1.3
  - versionstring: 10.4.1
  - edition: Community
```
Once I set the parameter to **'version.hide' => false,** it works again, I can add the URL of the ownCloud in android.

We tried on iOS or with the Desktop Client, none of them has a problem with hiding the version.hide ... why is it different ?

Could you fix this and revert to the previous behavior ? We shouldn't have to leak information for oC to work on android.
Thanks.

**Comment by jesmrec** [comment]
If the parameter is true (version hidden), we must let the request go:

I checked which version `version.hide` exists from:

oC 9.1.8 (latests 9.x version) => `version.hide` not supported, string always visible.
oC 10.0.0 => `version.hide` supported

So, in case the version is hidden, we can assume it is an oC>=10, so requests will be allowed to go. This is the corner case to support.

Should we include in 2.15.1 @michaelstingl ?

**Comment by abelgardep** [comment]
Thanks for the report. It will be included in 2.15.1

**Comment by jesmrec** [comment]
Fixed. Ready to go in 2.15.1.

**Comment by cs35-owncloud** [comment]
Hello,
thanks for your work :)
