### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2920]
[Android 11](https://developer.android.com/preview) version will be release as expected early September 2020

As usual, we should test the current stable version of the app, running under Android 11 beta version.

Also, we can gather here the most interesting features we can include in the app when the target is upgraded to Android 11, like the obligatoriness of [Scoped Storage](https://github.com/owncloud/android/issues/2877) 

Test plan (regresison): https://github.com/owncloud/QA/tree/master/Mobile/Android/Release_2.16/Android11Regression.md

**Comment by abelgardep** [comment]
We have a deadline here. @michaelstingl @jesmrec

 `Starting November 2021, all app updates will be required to target API level 30 (Android 11)`

**Comment by jesmrec** [comment]
Good to know. Will increase priority.

**Comment by theScrabi** [comment]
I checked against compileTarget and targetSdk with version 30. There are some null pointer checks that need to be changed.

**Comment by jesmrec** [comment]
Target is updated in the context of [Scoped Storage](https://github.com/owncloud/android/issues/2877)

No more work to do here
