### ISSUE TITLE
faster releases, even for testing purpose

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2924]
Open source doesn't mean to be slow.

What's about a fast release CI, to test and solve stuff much faster ?
This means
* every commit to `master` release automatic a version to Google Playstore **alpha** channel
* every tag release automatic a version to Google Playstore **beta** channel
* when someone decide, it's good, it will be manual moved to Google Playstore **release** channel

This implicit 
* a change in release versionName, similar like 999454800457b807c Otherwise it will keep the slow current mechanism
* apply a publish gradle plugin https://github.com/Triple-T/gradle-play-publisher
* changes in CI, best with Github actions
* optional a global error catcher (eg  #2726 It's an additional issue) 
* optional change in current git branching behavior, no more continue release branch.
![image](https://user-images.githubusercontent.com/3314607/89131036-532bf380-d50a-11ea-94e4-a0dc26b8c5fe.png)

Benefit
* less release overhead
* ability to test in alpha channel by user
* Google tests every commit too
* More testers (alpha and beta testers), means more error finding
* faster release to user 
* bundle resources to new features, instead of current endless release management 

## I could do this, if you want speed up your development

Go in touch with me, if  you want it @michaelstingl

**Comment by jesmrec** [comment]
Which is your technical proposal? you know, currently oC is using bitrise, not only in Android, also in iOS ... at least form my side, i'm satisfied with the results. Deployment options are also available there.

**Comment by hannesa2** [comment]
> Which is your technical proposal? you know, currently oC is using bitrise, not only in Android, also in iOS ... at least form my side, i'm satisfied with the results. Deployment options are also available there.

What's not clear here ?
I suggest to change this slow, stuck and nontransparent workflow to a faster, transparent and flexible one
