### ISSUE TITLE
Use public preview API

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2926]
Currently (2.15), Android is using only thumbnails as part of the previews. (private API)
Request is  ´api/v1/thumbnail/448/448/<path>´ (private thumbnail API)

It could switch to the the public preview API:
`remote.php/dav/files/[user]/[file]?x=[width]&y=[height]&c=[eTag]&preview=1 `
(but there's no real urgency)

x and y parameters contains `120` in iOS platform (as reference)

- AC (keep legacy behaviour):

  - Thumbnails are correctly fetched, no matter if picture is downloaded or not 
  - Thumbnails are requested once browsing
  - Thumbnails are shown in the uploads view.
  - Thumbnails are shown in the folder picker (copy, move options)

### PR
App: #3017

**Comment by abelgardep** [comment]
I was checking the api and the current implementation, and we can switch to the public preview api in a pretty simple way.

About the public preview api, i think that `Content-Length` header is missing.

> x and y parameters contains 120 in iOS platform (as reference)

About the thumbnails size, currently we retrieve a 448x448 which is much bigger than that reference. I have performed a quick test and for the same image: 
- 120x120 -> 4Kb
- 448x448 -> 35Kb

We have better thumbnails but maybe they are not as much important. Should we decrease thumbnails size? [Admins can limit their size anyway](https://doc.owncloud.com/server/admin_manual/configuration/files/previews_configuration.html#maximum-preview-size)
