### ISSUE TITLE
Request previews for EVERY file type

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#2927]
I assume there's a hardcoded list of filetypes where the Android app requests thumbnails/previews. Depending on the server setup, previews for more file types can be provided. The only way to make sure the Android app shows previews for all files the server supports, is to request previews for EVERY file type. Android app will receive 404 in case there is no preview. (same approach as in new iOS app and in Phoenix web UI)

In the future, server-side could announce in the Capabilities what file types have previews: https://github.com/owncloud/core/issues/31267 (not implemented yet)

### PR Old
App #3017 

### PR New
App #3105

**Comment by jesmrec** [comment]
Need to be re-enabled and re-checked in 2.17
