### ISSUE TITLE
[BUG] OAuth2 + av. offline. Sometimes POST request to renew is not sent

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2929]
This comes from report in[ 2.15.1 ](https://github.com/owncloud/android/pull/2914#issuecomment-658268082)release: 

I'm able to reproduce by following these steps, but it's not straightforward. 

1. Add an OAuth2 account. It is a good idea to decrease the expiration time (i set 120 secs). I set several items as av. offline. I don't know if this will be relevant, just commenting to be more precise.
2. Let the token renew some times (two is enough)
3. Kill the app
4. Leave the device during some time. I did about half an hour
5. Reopen the app. 

At this point, the request is sent, we have a `401` , but the token request to renew is not sent. So, the account is frozen. It is not posible to authenticate against OAuth2 (basic auth accounts work fine)

![Screenshot 2020-07-15 at 11 53 00](https://user-images.githubusercontent.com/14894746/87531377-ed2e1800-c691-11ea-8468-34e533cbea2b.png)

Huawei P20, Android 9
Pixel2, Android10
Nexus 6P, Android7

**Comment by abelgardep** [comment]
When i was able to reproduce it, i got some logs that may help to identify the problem.

I got some invalid_grant errors from appauth trying to refresh the token. 

`D: 2020-08-11 17:06:27:069(AccountAuthenticator.java:360) .refreshToken()Token  Request:{"configuration":{"authorizationEndpoint":"https:\/\/demo.owncloud.com\/index.php\/apps\/oauth2\/authorize","tokenEndpoint":"https:\/\/demo.owncloud.com\/index.php\/apps\/oauth2\/api\/v1\/token"},"clientId":"e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD","grantType":"refresh_token","refreshToken":"JyzLPmwCGFPQeHs28kS2IXlC292toyvR78TsjZYUyuI17vsaYDL3VDONeDAYe0HE","additionalParameters":{}}
E: 2020-08-11 17:06:27:342(AccountAuthenticator.java:401) .lambda$refreshToken$1$AccountAuthenticator()OAuth request to refresh access token failed
AuthorizationException: {"type":2,"code":2002,"error":"invalid_grant","errorUri":""}
	at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:480)
	at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:395)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by jesmrec** [comment]
After [replacing AppAuth for custom implementation](https://github.com/owncloud/android/issues/3038), this one is not reproducible anymore. This will be available in 2.17
