### ISSUE TITLE
release from feature branch ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#2931]
@abelgardep 

You release from feature branch https://github.com/owncloud/android/releases/tag/oc-android-2.15.1 
Wouldn't it be less confusing, when you first merge the feature branch to master as baseground for further development and after this to create a release with a tag form `master` ?

This is a suggestive question

**Comment by jesmrec** [comment]
The fact of signing the release branch does not force us to freeze the release branch during release testing / bugfixing stage.  Signing the release branch keeps the history for the current release after merging, and let other PRs to be merged in `master` at the time. Same is applicable to the `stable` branch. As baseground you can use the signed tag as well. There are many valid ways to do this, like the one you suggest. 

We should upgrade the `CONTRIBUTING`  documentation as is intended here: https://github.com/owncloud/android/issues/2807

We can go there for discussion and close this one as duplicated.
