### ISSUE TITLE
auto-upload on WiFi only enabled

### ISSUE THREAD

**Issue by jesulo** [owncloud/android#2935]
Hi, I don t find this option in app any more, where is? Auto-upload on WiFi only enabled. Regards

**Comment by jesmrec** [comment]
Options "Only Wifi" in auto uploads are only visible in auto uploads are enabled. Could you share an screenshot of your Settings?

**Comment by jesulo** [comment]
Yes I have already configured that option and linked a remote folder to be
able to upload an all taken from the app, but still upload that photo with
my mobile data, only the photos in the local folder await a Wi-Fi
connection, (the image taken should wait for a connection  like the others,
here is a bug or missing that feature) attached

**Comment by jesulo** [comment]
![Uploading Screenshot_20200813-093330_Nextcloud.jpg …]()

**Comment by jesmrec** [comment]
picture is missing.

you mean, with the "Only wifi" option, you take pictures under cellular connection, and the pics are uploaded. The expected behaviour is, that pictures wait (you can check it in "Uploads" tab) till WiFi is again available. Which android version and android app are you using? i can not reproduce the problem.

**Comment by jesulo** [comment]
Yes, that's what I'm talking about, android 10, before there was that wifi
only option, in the left bar in settings and it affected any photo that is
taken, now they changed it in auto upload, and it is selected by folder

**Comment by jesmrec** [comment]
Please, could you resend the picture you tried here? https://github.com/owncloud/android/issues/2935#issuecomment-673486341

Could you post an screenshot with the bottom side of the Settings view??

**Comment by jesulo** [comment]
![Screenshot_20200813-093330_Nextcloud.jpg](https://user-images.githubusercontent.com/40969440/90250966-f9310500-de0a-11ea-96ed-22796c3980c7.jpg)

**Comment by jesulo** [comment]
that of the button was a version in 2018 I can no longer find it now.  But you tell me that it should work the same?  How do you configure it?

**Comment by jesmrec** [comment]
are you sure you wanted to post this here instead of ->https://github.com/nextcloud/android/issues?

**Comment by jesulo** [comment]
Sorry that picture is nextcloud app, I tried too there.
I share owncloud picture. But where is wifi only option? Just find in option for upload folder ![Screenshot_20200814-091108_ownCloud.jpg](https://user-images.githubusercontent.com/40969440/90253940-f7b60b80-de0f-11ea-9a62-fdab24e41bdd.jpg)

**Comment by jesmrec** [comment]
"WiFi only" is in Settings view. You enable "Camera uploads", and you have the option available. But, the "WiFi only" is available for Camera uploads, not for any kind of uploads.

**Comment by jesulo** [comment]
do you have a picture of Only WiFi?

**Comment by jesmrec** [comment]
This is only WiFi:

![Screenshot 2020-08-18 at 08 47 41](https://user-images.githubusercontent.com/14894746/90479788-83d97300-e12f-11ea-8568-1cd3d0b73e3b.png)

This means, that the pictures you will take from your camera folder will be automatically uploaded. If you are not under WiFi, pics will be queued waiting for WiFi connection (check the "Uploads" tab):

![Screenshot 2020-08-18 at 08 53 25](https://user-images.githubusercontent.com/14894746/90480291-5214dc00-e130-11ea-85eb-c262fe2856ce.png)

If you upload something manually by using the upload option, it will be always uploaded no matter if you are under WiFi or not.

I hope this clarify.

**Comment by jesulo** [comment]
In the same way upload the photo

![Screenshot_20200818-081119_ownCloud.jpg](https://user-images.githubusercontent.com/40969440/90511605-b896fb80-e12a-11ea-8d46-2810a8162a88.jpg)
![Screenshot_20200818-081126_ownCloud.jpg](https://user-images.githubusercontent.com/40969440/90511624-bd5baf80-e12a-11ea-9e05-dcde06500d40.jpg)
![Screenshot_20200818-081144_ownCloud.jpg](https://user-images.githubusercontent.com/40969440/90511630-c0ef3680-e12a-11ea-915c-852216f4dc50.jpg)

I have samsung s9 plus android 1o

**Comment by jesmrec** [comment]
How did you upload the photo? please, detail the steps

**Comment by jesulo** [comment]
I enter the application and in the same folder / entered the option to take an image with the camera, it automatically starts uploading it, I am doing this in the demo user, from demo.owncloud.org

**Comment by jesmrec** [comment]
Ok, so you mean this option:

![Screenshot 2020-08-18 at 14 56 12](https://user-images.githubusercontent.com/14894746/90515552-1b0bee00-e163-11ea-8e34-20bf2bb5ac78.png)

such option does not apply the "Only WiFi" setting.

"Only WiFi" applies to the pictures/videos you take with your camera app from outside the ownCloud app.

Probably the wording is confusing there, but the behaviour you described is the expected. Open to be improved, for sure.

Is it clear for you?

**Comment by jesmrec** [comment]
I think everything is clear now. If not, @jesulo please feel free to reopen this issue or create new a new one.
