### ISSUE TITLE
[BUG] filename changed when upload a picture

### ISSUE THREAD

**Issue by IngoBelka** [owncloud/android#2938]
### Actual behaviour
- on xiaomi mi 9t the filename of pictures are changed from img_xxxx.jpg to one consists only of numbers when upload

### Expected behaviour
- the filename should not be changed
 
### Steps to reproduce
1. open gallery
2. mark a picture
3. choose upload
4. choose owncloud
5. file will upload
6. file is changed

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
yes

### Environment data
Android version: 10

Device model: xioami mi 9t

Stock or customized system:

ownCloud app version: 2.15.1

ownCloud server version: 10.5

#### Web server error log
no access

Insert your webserver log here
no acces

#### ownCloud log (data/owncloud.log)
no access

Insert your ownCloud log here
no access

**Comment by jesmrec** [comment]
I can not reproduce the problem. With the steps you described, you are sharing a pic from the gallery app to oC. In that case, is the origin app the responsible of the file name @abelgardep? 

@IngoBelka did the same happen when you share from other different app?

**Comment by IngoBelka** [comment]
It does happen with other apps too. I did try it with the file explorer also. With my Huawei tablet all is working really good, only Xiaomi has such behaviour.

**Comment by IngoBelka** [comment]
In addition: it only happens with pictures, other files are uploaded as they are.

**Comment by IngoBelka** [comment]
I did some more investigation. And I found the reason why it happens. Very deep in the settings of Xiaomi is a section "secure sharing" where one can set, that - while sharing pictures - the information about location and/or metadata will removed. Both where enabled on my system. 

Sorry for the inconveniance I made.

The issue is solved.

**Comment by jesmrec** [comment]
No problem!! thanks for contributing!!
