### ISSUE TITLE
Accept both display-name  and displayname as nodes in user endpoint response

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2954]
From https://github.com/owncloud/product/issues/181#issuecomment-685782818

two user endpoint returns inside its "data" node, different stuff:

/cloud/users/admin 

```
"data": {
      ...
      "displayname": "admin",
      ...
}
```

/cloud/user

```
"data": {
      ...
      "display-name": "admin",
      ...
}
```

App should support both

**Comment by michaelstingl** [comment]
Just checked with @felixboehm and @micbar , this is a bug and needs to be fixed in the backend.
