### ISSUE TITLE
[BUG] App crashes while accessing a WebDAV folder

### ISSUE THREAD

**Issue by candrea21** [owncloud/android#2977]
### Actual behaviour
By accessing a WebDAV folder, the app crashes.

### Expected behaviour
Browsing the folder as it would be a local folder.
 
### Steps to reproduce
1. Share a webdav folder (over https)
2. Open the app and browse to the shared folder

Can this problem be reproduced with the official owncloud server?
I dont want do share my webdav folder.

### Environment data
Android version: 8

Device model: Sony

ownCloud app version: latest

ownCloud server version: latest

#### Web server error log
```
N/A
```

#### ownCloud log (data/owncloud.log)
```
N/A
```

**Comment by jesmrec** [comment]
is your app version 2.15.2? we have fixed a pretty similar problem in such version. You can check the app version in the bottom of the `Settings` view.

Are these the steps you do?:

1. Share a folder with another user (not by link). Are you sharing by using the app, the web or other client?
2. In the Android app, browse through the folder you have shared before

Then, crash.

You wrote that happens with `https`. Does it mean that the same scenario works fine with `http` ?

am i missing something?

**Comment by candrea21** [comment]
Yes, app version is 2.15.2, release b089032be.

1. Add WebDAV storage to owncloud via browser
2. Open this WebDAV folder in the owncloud app
3. App crashes

I have not tried with ```http``` b/c I do not want to send passwords over ```http```.

Thank you.

**Comment by michaelstingl** [comment]
Ah, mounted WebDAV folder on the ownCloud server. (External Storage) Now I get it 💡 

What is the exact server version you're using?

**Comment by abelgardep** [comment]
Hi @candrea21, does it happen with 2.15, release https://github.com/owncloud/android/commit/4984a047c8b0f0ae856609ff9eebf1a056475a80 ? In 2.15.1 we updated the network library, so it would be helpful to know it.

**Comment by michaelstingl** [comment]
Hm, just tried to reproduce with my 10.3.2 server, but app didn't crash.

### Admin mounted WebDAV

![CleanShot 2020-09-30 at 18 54 59](https://user-images.githubusercontent.com/214010/94715988-7e865f80-034e-11eb-9464-e8fce54f9e18.png)

### User mounted WebDAV

![CleanShot 2020-09-30 at 18 55 28](https://user-images.githubusercontent.com/214010/94716023-8f36d580-034e-11eb-8891-69a362cce080.png)

@candrea21 could you send a test account to `apps-<at>-owncloud.com` ?

**Comment by candrea21** [comment]
That are the logs from the app:
```
10-03 10:23:34.627 E: AndroidRuntime( 4447): FATAL EXCEPTION: Thread-7
10-03 10:23:34.627 E: AndroidRuntime( 4447): Process: com.owncloud.android, PID: 4447
10-03 10:23:34.627 E: AndroidRuntime( 4447): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.utils.FileStorageUtils.createOCFileFromRemoteFile(FileStorageUtils.java:108)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.operations.SynchronizeFolderOperation.mergeRemoteFolder(SynchronizeFolderOperation.java:337)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:225)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:240)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:205)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:87)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:143)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:240)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:259)
10-03 10:23:34.627 E: AndroidRuntime( 4447): 	at java.lang.Thread.run(Thread.java:764)
10-03 10:23:36.484 E: (FileDisplayActivity.kt:346) .initFragmentsWithFile()( 5206): Still have a chance to lose the initialization of list fragment >(
10-03 10:23:36.498 E: (FileDisplayActivity.kt:999) .setBackgroundText()( 5206): OCFileListFragment is null
10-03 10:23:36.648 I: Adreno  ( 5206): PFP: 0x005ff087, ME: 0x005ff063
```

**Comment by abelgardep** [comment]
Thanks for adding that log! We have added a fix for that issue today. It will be available in v2.16 https://github.com/owncloud/android/issues/2984

**Comment by jesmrec** [comment]
Related: https://github.com/owncloud/android/issues/2459

**Comment by abelgardep** [comment]
Hi @candrea21, we released yesterday a new version. Could you check if this issue is still reproducible in 2.16?

**Comment by candrea21** [comment]
No, the issue is not reproducible in 2.16. Thank you very much for solving it.

**Comment by abelgardep** [comment]
Thank you for reporting it! We can close this now 👍

**Comment by candrea21** [comment]
The issue #2984 is back again :(

**Comment by jesmrec** [comment]
@candrea21 we'll reopen #2984. Could you track the issue there? Also, if you can provide further info, it will be welcome.
