### ISSUE TITLE
[BUG] Error parsing date from webdav reply

### ISSUE THREAD

**Issue by diocas** [owncloud/android#2999]
We started testing our branded 2.15.2 client with CERNBox and all files started appearing with default modification date (1/1/1970). This is caused by the client not being able to parse the date, which is sent in UTC.

In the logs, I can see the following:
```log
W/dav4jvm: Couldn't parse date: Fri, 16 Oct 2020 11:08:07 UTC, ignoring
W/dav4jvm: Couldn't parse Last-Modified date
```

Our server is returning the following:
```xml
    <d:propstat>
      <d:prop>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:getlastmodified>Fri, 16 Oct 2020 11:08:07 UTC</d:getlastmodified>
        <d:getetag>425ec7:1602846487.740</d:getetag>
        <d:quota-used-bytes>1791891353</d:quota-used-bytes>
        <d:quota-available-bytes>1000000000000</d:quota-available-bytes>
        <oc:permissions>WCKDNVR</oc:permissions>
        <oc:id>home:4349639</oc:id>
        <oc:size>1477887119</oc:size>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
```

Connecting to demo.owncloud.com works and the server returns the date in GMT:
```xml
    <d:propstat>
      <d:prop>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:getlastmodified>Fri, 16 Oct 2020 14:09:57 GMT</d:getlastmodified>
        <d:getetag>&quot;5f89a9b58efd0&quot;</d:getetag>
        <d:quota-used-bytes>9</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <oc:permissions>RDNVCK</oc:permissions>
        <oc:id>00000006ocbqtspi0tpy</oc:id>
        <oc:size>9</oc:size>
        <oc:privatelink>https://demo.owncloud.com/f/6</oc:privatelink>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
```

We could change our standard, but I believe this should be considered a bug.

### Environment data
Android version: 2.15.2
Stock or customized system: Branded CERNBox/Stock OC

**Comment by michaelstingl** [comment]
@diocas I'd say UTC in the date is a violation of the HTTP RFC 2616 which is referenced in the WebDAV RFC 4918.

> All HTTP date/time stamps MUST be represented in Greenwich Mean Time
(GMT), without exception. For the purposes of HTTP, GMT is exactly
equal to UTC (Coordinated Universal Time). This is indicated in the
first two formats by the inclusion of "GMT" as the three-letter
abbreviation for time zone, and MUST be assumed when reading the
asctime format.

(Source: https://tools.ietf.org/html/rfc2616#section-3.3.1)

**Comment by diocas** [comment]
Agree. Will change it on our side and close this ticket.
We need to check wether OCIS takes this into consideration or not (from what I just saw, we are returning "Thu, 24 Sep 2020 09:44:05 +0000", without any reference to GMT).
Thanks
