### ISSUE TITLE
Two-way file sync for specific folders or files.

### ISSUE THREAD

**Issue by untitaker** [owncloud/android#3]
Currently I've been doing this with an app called "Folder Sync".

**Comment by Chris00** [comment]
+1

**Comment by jirkaehm** [comment]
Functionality like dropsync app = full two-way sync of photos and videos taken by phone.

I make a lot of pictures with my phone, and I want simple way to sort them on desktop - with replica back to my phone. Thank you!

**Comment by alexandernst** [comment]
I tried ownCloud v3 (or something really old) back in the old times, that just sucked. Period.
A few days ago a friend of mine told me about how awesome ownCloud v8 is now and how I'd love it and how I'd replace Dropbox and Google Drive and Google Keep for ownCloud. 

I was amazed  from what he was saying, so I decided that, hell yeah, I'd install it on my server.
Got a Debian PPA and a few minutes later it was running! 

"Cool, it's not crashing as it used to do. I think this could end well!" I said to myself.

I dragged a folder full of  music to ownCloud's tab and it uploaded flawlessly. 

"Yeah, yeah, yeah!!" I was thinking.

Then I went to the Android market and downloaded your app. Logged in in my server (without problems!) and ... the bad feelings returned.

No automatic syncing of folders? Can't change the path to where files get downloaded? A "settings" window which won't let you do pretty much anything aside from adding/removing accounts.

I'm sorry to say it, but the first 2 things are no more than 100 lines of code, each one. And you failed to implement it for (judging by the dates of the open issues) more than 2.5 years. What a sorry state this project has.

Also, KUDOS, you made me waste (AGAIN!) 2 hours of my life. See you back when ownCloud v53 or so is released. No hard feelings.

**Comment by derekblankmccoy** [comment]
This should be a simple "auto-sync" feature which most people will want on by default. Could even go as far as a simple auto-sync schedule as well, but its not necessary:
![image](https://cloud.githubusercontent.com/assets/11743619/6952244/776ee832-d8b8-11e4-86e2-9331f0ab1c2f.png)

**Comment by aroquen** [comment]
Now that it's possible to download an entire folder, it should be possible to "download a folder and keep each file in sync". That should be straightforward to implement. At the moment, one still has to go through all the files' details one by one. Of course that won't solve the problem of really keeping a folder in sync, but at least it would get closer to solve this issue. And it would simplify the daily life of people who try to get things done with owncloud for android - and have a hard time now.

**Comment by davivel** [comment]
@aroquen, that's the idea. Trust me, we are the most interested in start working on it.

@alexandernst , I am really sorry for failing your expectations. It's a pity this could take you apart from ownCloud. I'd like to ask you to reconsider it. Maybe you could contribute with those 100 lines that would solve the problem. No hard feelings.

**Comment by aroquen** [comment]
@davivel What I wanted to point out is that "Syncing a folder" is not the same as "Download all files in folder and keep them in sync". The latter means that only the files you download will be kept in sync, not e.g. new files that might appear later on in the folder. This is not the feature we are all waiting for :-) but it would still be a (cheap) improvement.

**Comment by untitaker** [comment]
I think we should only implement "syncing a folder", because

* it doesn't make sense to have two features that do nearly the same
* "syncing a folder" is easier to explain (comparison with Dropbox)
* the added complexity is not much bigger than the one of "download all files and keep them in sync"

**Comment by derekblankmccoy** [comment]
Would it not be easier to just use the same detail info available for a file? Press and hold a folder, select details, it gives you folder size and modified date, and a checkbox for "keep folder up to date"

**Comment by davivel** [comment]
@derekblankmccoy , the difficulty is not in the user interface, but in the synchronization algorithm and process. We need to carefully review the usage of the network in the walk through all the tree of files under the affected folder. Currently, users with tons of files in their accounts already have battery and bandwidth problems when the full synchronization of the account is enabled, and that's only fetching metadata from the files. Imagine how may that grow when we sync full data.

Do not worry. This will be in *sooner than later*. Stay tuned.

**Comment by untitaker** [comment]
@davivel I've found a fairly easy algorithm for synchronizing two sets of "items", based on http://blog.ezyang.com/2012/08/how-offlineimap-works/, and I use that algorithm in [vdirsyncer](https://github.com/untitaker/vdirsyncer/blob/master/vdirsyncer/sync.py).

I'll write a blogpost if you want, but the article about OfflineIMAP is already very informative.

**Comment by derekblankmccoy** [comment]
@davivel Good to hear. Currently, I previously used a webdav client app called "synchronize ultimate" to do the two way sync and the battery hasn't taken that much of an impact. The only problem is that it gives a notification everytime it does a sync, which is set to every 15 minutes, so the notification panel gets filled up. It also doesnt notify what changes happened, so I uninstalled it in the end.

**Comment by davivel** [comment]
Thanks, @untitaker , this will be of great help. 

Just to notice the real problems after what cool Google videos show as something "so simple", in a fast review we can find that the JobScheduler API they recommend to make easier our life while scheduling the synchronizations for "now or later" requires API Level 21 or greater ; this is Android 5. Currenly the app must grant compatibitliy with Android 4 or later. :'( 

In any case, most of the comments in the video and the description of the algorithm of OfflineIMAP are in line with all the ideas we keep in background to implement this feature. Let's see how soon we can book the time do it.

**Comment by paroj** [comment]
you could check the system version at runtime and use the better JobScheduler API when available.

**Comment by kai11** [comment]
https://github.com/evant/JobSchedulerCompat may be worth a look.
Unfortunately JobScheduler not in official library https://developer.android.com/tools/support-library/index.html
Why not start 2.0 branch with 21+ requirement? When it'll be ready for production, Lolipop will be widespread - and ICS-compatible 1.7 branch can wait for official backport.

**Comment by tobiasKaminsky** [comment]
@paroj Developing both versions of a sync (with and without jobScheduler) would be too time intensive. 
@kai11 Same for this idea. Maintaining two branches would in my opinion be too much work for too few devs.

**Comment by untitaker** [comment]
You could simply not support two-way sync (and show an error) if JobScheduler is not available for now. I also don't think that we're at that point yet to decide that...

**Comment by binron** [comment]
I think this is a high priority thing. Now I have to buy Folder Sync for 2.75 CHF instead...

**Comment by michaelkuty** [comment]
:+1: * :100:

**Comment by jknockaert** [comment]
I have been using FolderSync, but it seems that this app is no longer developed.
While using FolderSync I noted that files started to disappear from my account. What actually happened is that random files got deleted from the microsd card in my phone (not sure why), and subsequently the removal was propagated to my owncloud account by two-way sync. I worked around this issue by switching to one-way sync, an option provided by FolderSync that I would highly recommend to consider for the owncloud app as well.

**Comment by davivel** [comment]
@jknockaert , this feature is currently in active development in the OC app. We'll be more careful automatic deletions. Historically, this has not been a problem with our app because, in case of doubt, we don't delete files automatically. We think that running out of local storage is not as bd as losing information.

**Comment by jknockaert** [comment]
@davivel Well I think the main point of automatic syncing is that it goes automatically. So automatic deletions would be part of that. I just wanted to highlight that there are a number of sync-scenarios that ideally should be covered. If you just want to keep a local copy of an online-managed pdf-archive you typically want local copies to be (agressively) deleted when the remotes are gone but not inversely, so strict one-way downstream syncing. But one may even want to set the sync-scenario on a folder-specific base, e.g. one folders one-way (down), another one-way up and still another folder two-way.

**Comment by davivel** [comment]
Another step forward: manual two-way synchronization for folders has just been merged, and will be availabe in release 1.8.1. "Manual" means the user long-clicks on a folder and may select the option "Synchronize" to trigger the two-way synchronization.

Next step: favoirte folder (also known as 'kept-in-sync' folders), to do it automatically.

**Comment by aroquen** [comment]
Happy to hear that! BTW why should synced folders be called "favorite" instead of... ehm... "synced"?

**Comment by derekblankmccoy** [comment]
I agree, "favorite" is the term used in the web console for frequently used files. It will be confusing to use the term "favorite" for 2 different behaviors.

**Comment by davivel** [comment]
I agree with both of you, there is a general agreement on the confussion, indeed. I'm using the word "favorite" because it's the current wording in the app, but will be updated soon. 

That detail is probably best to be discussed in https://github.com/owncloud/android/issues/1136 .

**Comment by rperezb** [comment]
Closed via:https://github.com/owncloud/android/pull/1109
About the wording, I encourage you to comment on #1136 thx!

**Comment by davivel** [comment]
For any of you missing details about this issue, let's follow up the conversation in #1136 .

Thx

**Comment by helmo** [comment]
I'm requesting to bountysource to move to $90 bounty on this issue to #1136

**Comment by brianjmurrell** [comment]
@davivel commented on 11 Aug 2015
> this feature is currently in active development in the OC app

Since it's nearly a year later, just wondering if there is any news on this.
