### ISSUE TITLE
Owncloud Android client can't log in

### ISSUE THREAD

**Issue by djsegfault** [owncloud/android#300]
I have my own Owncloud server running over https.  My Linux desktop client syncs fine.  When I bring up the Owncloud app on my Android phone, I see my folders and files, but once I try to read a file it says the download failed.  Then it brings me to the login page, where I log in with the same ID/password I'm using for the desktop client, but it says "wrong username or password" each time.  This is over SSL.

I get this in my SSL access logs when I attempt to log in: 
10.1.10.111 - david [10/Nov/2013:23:14:15 -0500] "HEAD /owncloud/remote.php/webdav/ HTTP/1.1" 401 1328 "-" "Android-ownCloud"
(Note that I have CalDAV and CardDAV syncing working fine on my phone)

My SSL error logs have:
[Sun Nov 10 23:14:15 2013] [info] [client 10.1.10.111] Connection to child 8 established (server thekramers.net:443)
[Sun Nov 10 23:14:20 2013] [info] [client 10.1.10.111] (70007)The timeout specified has expired: SSL input filter read failed.

but I'm not sure that's an actual problem or not.

In a few weeks I'm giving a talk about syncing data with an Android phone without involving Google, so I'm hoping to have it by then, as Owncloud is a big part of the presentation.

Thanks.

**Comment by davivel** [comment]
@osamak , is this still a problem for you with ownCloud app 1.6.2? 

Thanks in advance,

**Comment by osamak** [comment]
Using ownCloud 1.6.2, I still get:
```[26/Jan/2015:16:45:58 +0000] "HEAD /own/remote.php/webdav/ HTTP/1.1" 401 0 "-" "Android-ownCloud"```
What more test should I preform?

**Comment by davivel** [comment]
@osamak, that log is not an issue itself, it's one of the operations expected when the URL is entered in the login view.

The problem discussed here is about fulfilling the log-in process. Can you successfully set-up an account in your Android device?

**Comment by davivel** [comment]
Closed due to inactivity.
