### ISSUE TITLE
[BUG] Shared by link only shows files/folders from root

### ISSUE THREAD

**Issue by diocas** [owncloud/android#3003]
### Actual behaviour
When opening the Share by Link page, I only see the public links that exist in the root/home folder. If this was consistent with the web ui, then I should see all my public links, including the ones inside other folders.

I'm not sure wether this is on purpose or not... The API only returns the data I'm seeing, because the app calls it with the `path=/` and `subfiles=true` parameters (which I might also argue that should include everything under the path `/`, but that's another question for the core repo..).

I also tried with the CERNBox, which return all my links, but the app still filters them and only shows the root ones. We might be doing something wrong, but I'm not seeing anything in the logs.

### Expected behaviour
The Shared by Links should be consistent with the web ui and show all my links.

### Environment data
Android version: 10

Device model: Emulator

Stock or customized system: Stock

ownCloud app version: 2.15.2

ownCloud server version: 10.5.0 (demo.oc.com)

**Comment by abelgardep** [comment]
First of all, thanks for opening an issue. Yes it is intended that you only see the top shared folder. Same for Av. Offline files. Should we move to another behaviour? @michaelstingl

**Comment by michaelstingl** [comment]
> Should we move to another behaviour? @michaelstingl

Should be similar to the web ui. It lists all links a user generated:

![CleanShot 2020-10-23 at 17 03 45@2x](https://user-images.githubusercontent.com/214010/97020413-d1b89000-1551-11eb-8e40-d252b382a30d.png)

https://demo.owncloud.com/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&include_tags=true

```
{
"ocs": {
"meta": {
"status": "ok",
"statuscode": 100,
"message": null,
"totalitems": "",
"itemsperpage": ""
},
"data": [
{
"id": "9",
"share_type": 3,
"uid_owner": "test",
"displayname_owner": "test",
"permissions": 1,
"stime": 1603465020,
"parent": null,
"expiration": null,
"token": "E9dr4YwuaAJwfiU",
"uid_file_owner": "test",
"displayname_file_owner": "test",
"additional_info_owner": null,
"additional_info_file_owner": null,
"path": "/Parent/Folder1",
"item_type": "folder",
"mimetype": "httpd/unix-directory",
"storage_id": "home::test",
"storage": 4,
"item_source": 321,
"file_source": 321,
"file_parent": 320,
"file_target": "/Folder1",
"name": "Public link",
"url": "https://demo.owncloud.com/s/E9dr4YwuaAJwfiU",
"mail_send": 0,
"attributes": null,
"tags": []
},
{
"id": "10",
"share_type": 3,
"uid_owner": "test",
"displayname_owner": "test",
"permissions": 1,
"stime": 1603465029,
"parent": null,
"expiration": null,
"token": "eN1aj9a6ghz0zKn",
"uid_file_owner": "test",
"displayname_file_owner": "test",
"additional_info_owner": null,
"additional_info_file_owner": null,
"path": "/Parent/Folder2",
"item_type": "folder",
"mimetype": "httpd/unix-directory",
"storage_id": "home::test",
"storage": 4,
"item_source": 322,
"file_source": 322,
"file_parent": 320,
"file_target": "/Folder2",
"name": "Public link",
"url": "https://demo.owncloud.com/s/eN1aj9a6ghz0zKn",
"mail_send": 0,
"attributes": null,
"tags": []
},
{
"id": "11",
"share_type": 3,
"uid_owner": "test",
"displayname_owner": "test",
"permissions": 1,
"stime": 1603465105,
"parent": null,
"expiration": null,
"token": "JSD0cb6VMoepfrH",
"uid_file_owner": "test",
"displayname_file_owner": "test",
"additional_info_owner": null,
"additional_info_file_owner": null,
"path": "/Parent/Folder2/Doc1.txt",
"item_type": "file",
"mimetype": "text/plain",
"storage_id": "home::test",
"storage": 4,
"item_source": 328,
"file_source": 328,
"file_parent": 322,
"file_target": "/Doc1.txt",
"name": "Public link",
"url": "https://demo.owncloud.com/s/JSD0cb6VMoepfrH",
"mail_send": 0,
"attributes": null,
"tags": []
}
]
}
}
```

**Comment by abelgardep** [comment]
I mean, currently if we have a shared folder, and inside it we have another shared folder, we only show the top hierarchy one.

**Comment by michaelstingl** [comment]
> Should we move to another behaviour? @michaelstingl

Yeah, please align with new iOS app and oC web UI:

Android 2.15.3 | iOS 11.4.1 | oC 10.5.0
-- | -- | --
![Screenshot_20201026-150355](https://user-images.githubusercontent.com/214010/97182466-dcb33080-179c-11eb-939e-0b3d7642b587.png) | ![Photo-2020-10-26-15-03-00_0007](https://user-images.githubusercontent.com/214010/97182470-dd4bc700-179c-11eb-9118-d153aebb46df.PNG) | ![CleanShot 2020-10-26 at 15 02 49](https://user-images.githubusercontent.com/214010/97182456-d755e600-179c-11eb-86aa-daef3371a0b6.png)
