### ISSUE TITLE
[New Arch] Uploads

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3004]
Synchronization epic #2818 

ACs:

- New content is uploaded from:
   - Manual uploads (doc provider)
   - Uploads from camera
   - Auto Uploads
   - Share from external app
- Content will be uploaded to the selected location and reflected in uploads view
- Notifications shown with the progress. If the upload successes, notification will be dismissed. If the upload fails, it will remain.
- Cause of errors will be shown in the uploads view as well
- The status of the uploads in the view will be persisted. Only the last 30 correct uploads will be displayed
- Failed uploads because lack of connection will be automatically retried

This AC's correspond with the current status of the app and can be reviewed somewhen. The main target is keeping the current behaviour, moving everything to the new architecture. Improvements also have room. 

Splitting up in different issues:

- Upload a single file: #3424 

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

### QA

Test plan: https://github.com/owncloud/QA/blob/master/Mobile/Android/Sync/Upload.md

**Comment by jesmrec** [comment]
Uploads could be splitted in three different steps (one PR for each):

**1st step: Single upload**

 1. Select the target folder
 2. Select a file using doc provider

file is uploaded and stored in server. No notifications, no error handling. This first step will post the file using the two known methods: NG (oC10) and "full upload" (oCIS). TUS method will be implemented later.


**2nd step: notifications & error handling.** 

- Network lost
- App terminated
- Account removed
- Target folder removed
- Waiting for wifi (same as network lost)
- Maintenance mode
- Lack of permissions
- Lack of quota
- Virus detection

**3rd step: conflicts**

https://github.com/owncloud/android/issues/3005

**Comment by abelgardep** [comment]
A little information about the uploads and what we can expect from them when moved to new arch

| Type                       | Cache file before upload | Origin                            | To do after upload                     | Keep local file in scoped storage |
|----------------------------|--------------------------|-----------------------------------|---------------------------------------------|-----------------------------------|
| Camera Upload              | No                       | StorageAccessFramework            | Keep original or remove original (settings) | no                                |
| (FAB) Picture from camera  | No                       | Picture created in temporal file  | Remove temporal file                        | no                                |
| (FAB) Upload from files    | No                       | StorageAccessFramework            | Keep original                               | no                                |
| Share with oC - Plain Text | No                       | Txt file created in temporal file | Remove temporal file                        | no                                |
| Share with oC - Files      | Yes                      | File -> Cache file                | Remove temporal file                        | no                                |
| Conflicts - Keep both      | No                       | File in scoped storage            | Move file to final location (Rename)        | yes                               |
| Conflicts - Keep local     | No                       | File in scoped storage            | Nothing                                     | yes                               |
| Documents Provider         |                          |                                   |                                             |                                   |
