### ISSUE TITLE
[FEATURE REQUEST] Log remaining HTTP requests

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3009]
With the first solution of #2887 we are able to log every HTTP request performed by our OkHttpClient.

But there are some requests that are performed out of it: AppAuth requests. This issue should take care of it and log the remaining HTTP requests. May be fixed with https://github.com/owncloud/android/issues/2997.

**Comment by jesmrec** [comment]
Pending to check which information must be shown/hidden in the logs.

**Comment by michaelstingl** [comment]
> Pending to check which information must be shown/hidden in the logs.

https://github.com/owncloud/android/issues/3038 should allow us to also log the `POST` for the token exchange

**Comment by abelgardep** [comment]
Yes, I mean if we need to log sensitive information: access token, refresh token, etc

**Comment by michaelstingl** [comment]
> Yes, I mean if we need to log sensitive information: access token, refresh token, etc

In the other platforms, we log them. Can be changed. Would need coordination across platforms…

**Comment by jesmrec** [comment]
Current status (with option `Log HTTP requests and responses`  enabled):

1) Basic Auth: Everything that happens in the app is logged

2) OAuth2 / OIDC: http requests and responses are logged, if they happen inside the app. That means: status.php, capabilites, token, /dav/files are logged, but all the chrome custom tab stuff is not logged (happens in the browser)

I think, nothing else could be logged apart of that, so after [replacing AppAuth](https://github.com/owncloud/android/issues/3038) we are able to login all posible authentication requests and responses.

If nothing else is added from your side, this one can be closed

**Comment by abelgardep** [comment]
Yes, that's it. Everything that is on our hands is logged. So, from my point of view, we can close this.
