### ISSUE TITLE
[BUG] Image is not refreshed when other client modifies it

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3021]
### Steps to reproduce

1. Download an image in the Android app
2. With other client, modify the image
3. In the app, open the image again

### Current behaviour
Image is not updated, you see the old version. Thumbnail is updated.

### Expected behaviour
New version of the image in the server, so in the moment of downloading, the new version must be downloaded and displayed. 
 

### Environment data
Android version: 11 & 7

Device model:  Pixel 2 & Nexus 6P

ownCloud app version: 2.15.3

ownCloud server version: 10.5

**Comment by abelgardep** [comment]
We use glide to show images, and it uses its own cache, so when we update the image, it keeps using its cached image.

**Comment by jesmrec** [comment]
From my pov, this is not a good behaviour because we are not showing the correct content of the downloaded file. It is not a data loss, but points to a lack of sync. We have to look for posible solutions.

**Comment by abelgardep** [comment]
Of course it is not a good behaviour. I just pointed the problem. It should be fixed. Options:
1. Don't let Glide use its cache
2. Try to tell glide when it needs to refresh its cache
