### ISSUE TITLE
Don't auto-guess /owncloud endpoint

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#3029]
Hosting in /owncloud became less and less common. But auto-guessing additional endpoint can cause problems.

Overview-issue: https://github.com/owncloud/product/issues/294

**Comment by jesmrec** [comment]
Are we auto guessing /owncloud? afaik, we don't. Let me know if i'm wrong. Shouldn't it be an apache issue?

CC @abelgardep

**Comment by michaelstingl** [comment]
in previous time, if there was no ownCloud instance found at `example.com`, it automagically tried to find on `example.com/owncloud`

**Comment by jesmrec** [comment]
we'll take a look to check it

**Comment by abelgardep** [comment]
As far as i know, we don't do that in the android App. If we don't find any instance in the url, we return a fail. Do you have any clue that we are doing that?

**Comment by abelgardep** [comment]
Android App does not auto-guess `/owncloud` endpoint. So, nothing to do here.
