### ISSUE TITLE
[BUG] Search does not work when sharing with ownCloud

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3033]
### Actual behaviour
- Search does not filter list of files.

### Expected behaviour
- Search should filter the list of files.
 
### Steps to reproduce
1. Select a file using a file explorer and share with ownCloud
2. ownCloud App is opened
3. Search does not work. You can not filter list of files.

![receive_external_does_not_work](https://user-images.githubusercontent.com/47524927/101639019-18454980-3a2f-11eb-8b9f-1f9d994393a1.gif)

### Environment data
Android version: 11
Device model: Pixel 3XL
ownCloud app version: 2.15.3

**Comment by JohnKal** [comment]
Hello. Can i work on this issue?

**Comment by abelgardep** [comment]
Of course, go ahead 👍 

If you need any help, please tell us.

**Comment by abelgardep** [comment]
Thanks for the contribution @JohnKal. Will be included in 2.16 👍
