### ISSUE TITLE
[FEATURE REQUEST] Use AndroidX Preference

### ISSUE THREAD

**Issue by TacoTheDank** [owncloud/android#3037]
1. It makes the settings look MUCH nicer.
2. PreferenceActivity is ancient and VERY deprecated.

**Additional context**
- https://developer.android.com/guide/topics/ui/settings
- https://medium.com/google-developer-experts/exploring-android-jetpack-preferences-8bcb0b7bdd14
- https://blog.mindorks.com/implementing-android-jetpack-preferences

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by abelgardep** [comment]
Thanks for opening a new issue and adding some interesting resources. Settings are in our scope: https://github.com/owncloud/android/milestone/41

An issue to move to AndroidX Preferences was already created: https://github.com/owncloud/android/issues/2867

**Comment by abelgardep** [comment]
Since this issue was already created, we can close this one to avoid duplicated issues. I have added the resources there.

BTW, contributions are more than welcome 👍

**Comment by TacoTheDank** [comment]
Ah thanks. I had searched for this in the issues, but didn't find anything, so I must've missed it.

**Comment by abelgardep** [comment]
Yes, sorry, i have updated the title to avoid further problems 👍
