### ISSUE TITLE
Replace AppAuth for custom implementation

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3038]
Actually, [AppAuth](https://github.com/openid/AppAuth-Android) library is the responsible to handle the OAuth2 - OIDC authentication flows inside the app. We have faced several issues with the library . The most important of them seems to be the unmaintenance of the repository (two and half years without releases). 

Issues like

https://github.com/owncloud/android/issues/2997
https://github.com/owncloud/android/issues/2929

are also related with that.

In order to be aligned with other client teams, we will go for a custom implementation of OAuth2 and OIDC that will allow us:

- to have control over the authentication feature
- to log everything we need
- not to be pending of external releases

For sure, having an external dependency is nothing bad (we keep several external dependencies), but in this case, the pros are less than the cons.

This is some related stuff, that can be helpful

- OAuth2 implementation PR: https://github.com/owncloud/android/issues/1724
- AppAuth spike: https://github.com/owncloud/android/issues/2755
- AppAuth integration: https://github.com/owncloud/android/pull/2800 (app)  https://github.com/owncloud/android-library/pull/300 (library)
- Chrome Custom Tab implementation: https://github.com/owncloud/android/pull/2157

It could be done in a two-step implementation (what do you think?):

1. Implement OAuth2 ( + automatic tests)
2. QA OAuth2
3. Implement OIDC
4. QA OIDC 
5. I would go for a beta stage 

ACs must be regressive. Keep same behaviour as before, adding as many logs as posible.

-----
### Implementation
app: https://github.com/owncloud/android/pull/3043
library: https://github.com/owncloud/android-library/pull/363

**Comment by abelgardep** [comment]
### Steps to replace AppAuth
- [ ] Create usecase to retrieve oidc discovery information
- [ ] Create usecase to exchange authorization code for tokens
- [ ] Create usecase to refresh token
- [ ] Replace AppAuth UI and implement Custom Tabs
