### ISSUE TITLE
[BUG] ReceiveExternalFilesActivity randomly scrolls to top

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#3041]
### Actual behaviour
When scrolling down a large list of directories in the [`ReceiveExternalFilesActivity`](https://github.com/owncloud/android/blob/f75ad5844e31e1aba17ee484fa26a72cafe25c66/owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java#L109), the scroll view randomly jumps to the top of the list.

### Expected behaviour
Smooth scrolling all the way to the bottom without the list randomly jumping to the top.
 
### Steps to reproduce
1. Crate a directory with a large list of sub directories (>~ 300).
2. Go to another app and share a file
3. Share with ownCloud
4. Select the directory with the large amount of subdirectories
5. scroll to the bottom.

### Environment data
Android version: API 29

ownCloud app version: 2.15.3

**Comment by theScrabi** [comment]
I was not able to find a single reason/bug why ListView behaves like this. However ListView is not the right tool for this purpose either. For lists with lots of items it is highly recommended to use [RecyclerView](https://developer.android.com/guide/topics/ui/layout/recyclerview). Imo this is simple to do for this specific Activity, however requires some time to be done.

**Comment by shashankdaima** [comment]
Is it solved or not?

**Comment by jesmrec** [comment]
Not solved yet

**Comment by theScrabi** [comment]
Fix here: https://github.com/owncloud/android/pull/3117

**Comment by theScrabi** [comment]
@jesmrec I yet found another issue while trying to fix this. It is regarding search in the ReceiveExternalFilesActivity.
Here is a description of what happens on current Master:

#### How to reproduce
1. Share a file with the android app
2. Search for a folder which is not the first one in the list
3. enter it
#### Expected
Selected folder is entered
#### Actual
Folder that would be first in the list without the search filter being applied is entered.

[This](https://github.com/owncloud/android/pull/3117/commits/01696863066fd0b69b19f9dd375f4ee11b05c084) commit fixes it.
