### ISSUE TITLE
ownCloud server update

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3045]
Sorry for cross posting https://github.com/owncloud/core/issues/38253 but I need a solution and when I see 1,5 k open issues my fear is growing and I need some urgent help here.

The question is more how to update ownCloud server ?
Is there somewhere a best best practice wiki ?

**Comment by michaelstingl** [comment]
I'm not aware of any issues following this instructions:
https://doc.owncloud.com/server/10.6/admin_manual/maintenance/manual_upgrade.html
