### ISSUE TITLE
New to owncloud and unable to connect my android to my server

### ISSUE THREAD

**Issue by crhaerich** [owncloud/android#3046]
Hello I am new to owncloud and am having an issue connecting my phone to my server.  I downloaded the app and when I open it up it asks for my server address.  I have tried just the IP address, http://ipaddress, https://ipaddress, http://ipaddress/owncloud, and https://ipaddress/owncloud.  I am on the same network as my server and when I try to go to those listed above in the app I get a :an error occurred while connecting with the server: error and when I try to go to the ip address on my internet browser on my phone I get a error stating that the site can't be reached.  Like I said I am new to owncloud and have downloaded a prebuilt vm of owncloud as my server.  Currently I am using version 10.5.0 of the server and version 2.15.3 on my phone.  If you need me to get you a log or something I can but you will have to walk me through getting it.

**Comment by jesmrec** [comment]
Hi! if you get the problem also in the device browser, the issue is not in the app. Please, check that your server IP is totally reachable (check with other devices in the same network to reach the server) to discard any connection problem. Let us know your findings

**Comment by jesmrec** [comment]
No new feedback from many days. Please reopen if you have additional info about this.

**Comment by IveMalfunctioned** [comment]
ever solved it? @crhaerich
