### ISSUE TITLE
Beginner! Please Help!

### ISSUE THREAD

**Issue by SayanDas92** [owncloud/android#3049]
I'm a beginner. So, please help me. 
I'm trying to load the project on Android Studio but it says:
Gradle sync failed: com.android.tools.idea.gradle.project.sync.idea.issues.SdkPlatformNotFoundException: Module: 'owncloudApp' platform 'android-29' not found. 
What should I do?

**Comment by michaelstingl** [comment]
Please read the setup guide carefully:
https://github.com/owncloud/android/blob/master/SETUP.md

Often `--recursive` option is missing in the `git clone` command. 

Please post the exact steps you performed.

**Comment by abelgardep** [comment]
Hi @SayanDas92 ! Check first if you cloned the repo properly using `--recursive`.

If that's fine, let's check this. Open Android Studio Preferences -> Android SDK.

1. Check if the sdk is properly located
2. At the moment we use api 29 to compile. So, make sure that you have it installed.

![Screenshot 2021-01-14 at 13 59 06](https://user-images.githubusercontent.com/47524927/104594027-dd0ee980-5670-11eb-8598-844ba36525ec.png)

Please, tell us if it fixes the problem!

**Comment by abelgardep** [comment]
Hey @SayanDas92, I close this issue for the moment. If you still have this problem, feel free to reopen it. Thanks!
