### ISSUE TITLE
[BUG] no geo tagging data when uploading via "picture from camera" option

### ISSUE THREAD

**Issue by marvin** [owncloud/android#3056]
### Actual behaviour
If you take a picture with the camera and upload the file via +-button -> Upload File -> Files and inspect the photo or check it in the browser the picture has its geo data included. If I upload a picture via + ->  Upload File -> Picture from Camera and take a picture directly via the owncloud-app the picture gets uploaded but it doesn't include geo data. This way we have to take the extra step to make pictures and then upload them because we require the geo tagging data. The same behavior happens on the iOS App.
In the android camera settings geo tagging is enabled for sure! 

### Expected behaviour
when taking a picture via the +-Button -> Upload File -> Picture from Camera geo data should be included in the uploaded photos
 
### Steps to reproduce
1.  open the app
2. click the + button
3. select upload file
4. select "Picture from camera"
5. take picture and wait till uploaded
6. inspect the image and no geo-tagging information included

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
- YES! 

### Environment data
Android version: Version 8.x till 10.x

Device model: fairphone2, galaxy tab A10, galaxy S10

Stock or customized system: stock

ownCloud app version: 2.15.3 & 2.15.0

ownCloud server version: 10.6.0

**Comment by michaelstingl** [comment]
> The same behavior happens on the iOS App.

Thanks for reporting. Please open individual issue in the iOS repo.

**Comment by marvin** [comment]
> > The same behavior happens on the iOS App.
> 
> Thanks for reporting. Please open individual issue in the iOS repo.

will do.

**Comment by michaelstingl** [comment]
@abelgardep could an upgrade to [`CameraX` (from Android Jetpack)](https://developer.android.com/training/camerax) solve this?

**Comment by abelgardep** [comment]
Ok, I see. I would need to take a deeper look. I'm not sure at the moment.

**Comment by fesave** [comment]
I have been looking into this proposal, and I have news.

First of all, it seems that the use of the CameraX library does not solve the loss of information in the EXIF metadata of the photographs taken after seeing different issues mentioning the same problem.

Also, after testing with different devices, I have found that in most cases, the native camera application of the device does not generate this kind of information.

But if you use a different camera application (in my case I used OpenCamera) the EXIF metadata does include the geolocation, so you could use an alternative camera application as workaround or configure the camera folder to be automatically uploaded to ownCloud.

Regards.

cc @marvin @michaelstingl @abelgardep

**Comment by jesmrec** [comment]
ftm, it is not in our plans to add the location permission in the app. Closing this, if it has to be retried somehow, please, feel free to reopen. 

Thanks for reporting.
