### ISSUE TITLE
[FEATURE REQUEST] Room database everywhere

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3059]
There is a branch `new_arch/migrate_ocfile_newdb` from @abelgardep which I see as a huge step in direction future, because at least I don't want to touch the current manual sqlite database.
This prevents me to add new features at least on my side.

The main purpose of this issue is to tell you, that someone waits for it !
Thank you !

**Comment by abelgardep** [comment]
Hi @hannesa2, we have this milestone in our roadmap: https://github.com/owncloud/android/milestone/43. We migrated the old file list database to Room, but it requires some work yet. I want to have it done as soon as possible too. It will allow us to add new features and increase our test coverage.

**Comment by hannesa2** [comment]
I eager to see it merged 👍 
Btw in the milestone I see no implicit task to convert all to Room (in the headline), but most of them are basing on it.

**Comment by jesmrec** [comment]
Room will be everywhere as soon as the work in the new architecture advances. This is a transversal task, we keep moving everything to the new DB.

For the moment, i think nothing else to be discussed about this. Feel free to reopen if you disagree.
