### ISSUE TITLE
[BUG]2.16.0 can't connect 

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3063]
I tested new 2.16.0 version but I'm unable to connect to server `ownCloud 10.5.0 (stable) `

My server is hosted with https://www.myserver.info/owncloud
and there is definitive no https://www.myserver.info/.well-known/openid-configuration !

![image](https://user-images.githubusercontent.com/3314607/105844650-dcb01000-5fd9-11eb-8199-7b2e328a8428.png)

As an user without `adb logcat` connection you are complete helpless now ! (I at least see the stacktrace)

![image](https://user-images.githubusercontent.com/3314607/105845021-6c55be80-5fda-11eb-93f6-1c9d9a837c43.png)

What I've to do, to make it work ?

**Comment by hannesa2** [comment]
Hiding the root cause to the user is here not very productive

**Comment by abelgardep** [comment]
AFAIK we didn't change anything related to OAuth flow. If OIDC service discovery fails, we try to connect to OAuth. That log is the expected behavior. After that, it should try to connect to OAuth and a browser should be opened.

**Comment by hannesa2** [comment]
Maybe it's not a recent change, I moved from `2.15.1` to `2.16.0`

**Comment by hannesa2** [comment]
> connect to OAuth and a browser should be opened

Ahhh, I use a developer version of Android Emulator, which support Apple Silicon M1, but there is no http support !

**Comment by hannesa2** [comment]
> Hiding the root cause to the user is here not very productive

But this is still valid !

**Comment by abelgardep** [comment]
Well, I agree that hiding error causes to the user is not good. But in this case, I think that showing `OIDC not available, connecting to OAuth 2.0` should be transparent to the user.
