### ISSUE TITLE
[Question] File manipulation

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3065]
Hi, I'm want to build me a image rotate menu option.
To rotate an image from a file is quite easy. But what to do, to sync it to server ?
Do I have to change record in database, or is there anything other required ?

**Comment by jesmrec** [comment]
Options to sync a local-edited oC file:

1. Open the file stored in the device, edit with your external editor and save. It will be automatically uploaded. 
2. Use the SAF to browse, open the file and then, same steps as 1.
3. Set it as available offline. After saving, maximum 15 minutes, it will be sync if oC app is closed (thanks to JobScheduler)

If you notice any problem with these options, please let us know details like: app you used to manipulate, steps you did, android version etc...

thanks in advance.
