### ISSUE TITLE
[BUG] No ringtones on OnePlus after taking new photos with auto-upload enabled

### ISSUE THREAD

**Issue by lvikstro** [owncloud/android#3071]
### Actual behaviour
OnePlus 7T with Oxygen OS 10.0.15.HD65BA loose sound after taking pictures and owncloud triggering a media scan (using a depricated API for android 10. Similar to this:  https://forums.oneplus.com/threads/no-ringtones-and-notification-sound.1117222/page-2#post-21598945 

### Expected behaviour
Scanning for new media shouldn't affect the sound settings on the phone.
 
### Steps to reproduce
1. Enable picture uploads in the owncloud android client
2. Take a picture
3. Wait a while (10-15 minutes) and go into sound settings. Now all three sections of the "Ringtone & vibration" are "None" and nothing is available until the phone has been restarted.

### Environment data
Android version: 10 (Oxygen OS 10.0.15.HD65BA)

Device model: OnePlus 7T

Stock or customized system: Stock

ownCloud app version: 2.16 release 71bc1de44

ownCloud server version: 10.6.0 (stable)

#### Web server error log
```
```

#### ownCloud log (data/owncloud.log)
```

```

**Comment by jesmrec** [comment]
Feel free to reopen if still happens
