### ISSUE TITLE
Download all files in a folder

### ISSUE THREAD

**Issue by laryllian** [owncloud/android#308]
Heyho,
imagine I have an audiobook with 30 files in my owncloud and I will go on a (looong) train ride soon, where I would like to listen to it. How do I download them? Currently this involves 30 click+return-to-folder moves, which is crazy. 

Solution: Add another menu item "Download entire folder", which downloads all files that are either missing locally or are not up to date locally.

Thx for your time
Laryllian

PS. Related: https://github.com/owncloud/android/pull/116

**Comment by masensio** [comment]
This feature will be available in the next version of the app, 1.7.0.
At the moment is in the develop branch.

**Comment by MorrisJobke** [comment]
\o/ 

Is there a rough ETA?

**Comment by davivel** [comment]
@MorrisJobke, in the current week. Cross your fingers ;)

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
