### ISSUE TITLE
JCenter replacement

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3084]
JCenter service ends on February 1st, 2022. We should get rid of it the sooner the better.

```
To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st, 2021.

To clarify, the JCenter repository will keep serving packages for 12 months until February 1st, 2022. Only the JCenter REST API and UI will be sunsetted on May 1st, 2021.
```

More info: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

### PR

- App
- Library (if needed) https://github.com/owncloud/android-library/pull/404

**Comment by abelgardep** [comment]
They have postponed the jcenter service ending to February 1st, 2022.

**Comment by abelgardep** [comment]
Rechecked. Some libraries were moved to mavenCentral. But there are some pending ones.

- Exoplayer: Latest versions can be found in mavenCentral https://maven.google.com/web/index.html?q=exoplayer
- Koin: Latest versions can be found in mavenCentral too https://github.com/InsertKoinIO/koin#maven-central
- PatternLockView: Not available in mavenCentral https://github.com/aritraroy/PatternLockView

**Comment by abelgardep** [comment]
> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

Finally, we can keep using JCenter 🥇

**Comment by abelgardep** [comment]
One step closer thanks to #3255 

Last one: https://github.com/owncloud/android/blob/master/build.gradle#L62

How to remove it: Updating the libraries described in this comment: https://github.com/owncloud/android/issues/3084#issuecomment-828208985

**Comment by hannesa2** [comment]
Here is one more step closer https://github.com/owncloud/android/pull/3264 to remove `jcenter()`

**Comment by hannesa2** [comment]
concerning https://github.com/aritraroy/PatternLockView I recommend to fork, tag and use from `jitpack.io`

**Comment by abelgardep** [comment]
Yes, that was our initial idea!! Thanks for the recommendation, we will do it 👍
