### ISSUE TITLE
[BUG] 301 redirections only work if status.php is in a subfolder

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3096]
### Steps to reproduce
1. In the app, enter ocis.owncloud.works as URL

### Actual behaviour
That URL contains a 301 redirection that can not be followed.

If a 301 server contains a status.php in a subfolder, it works. But this is not a regular case

### Expected behaviour
301 should be followed correctly
 

### Environment data
Android version: 11

Device model: Pixel 2

Stock or customized system: stock

ownCloud app version: 2.16

ownCloud server version: oCIS 1.0

**Comment by michaelstingl** [comment]
I assume Android app checks for `https://ocis.owncloud.works/status.php`

```
% curl -I --http1.1 https://ocis.owncloud.works/status.php
HTTP/1.1 301 Moved Permanently
Date: Thu, 11 Feb 2021 10:06:29 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Thu, 11 Feb 2021 11:06:29 GMT
Location: https://ocis.ocis-traefik.latest.owncloud.works/
cf-request-id: 08322785ca00004c807d92f000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=sd6zVgK1jRp2UgpcX4XWV4L4EgGMRE%2ByREYNSByhI3LwsqzS9vFBlbo8P6P8iz4zQvFkccjO2uFOgAvVTTw07gc9eZcJDsoCwU1mTk5VQ4mYvukw"}],"max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 61fd41e94bc34c80-AMS
```

**Comment by michaelstingl** [comment]
Does the Android app asks for user consent before connecting to the new host?

**Comment by abelgardep** [comment]
Two different situations regarding 301.

### Working in 2.16
1. We perform a request against `a.web.server/status.php`
2. We receive a 301 that redirects to `a.different.one/status.php`

### Not working in 2.16
1. We perform a request against `a.web.server/status.php`
2. We receive a 301 that redirects to `a.different.one`

So, the problem appears when it is not redirected to the same path on new domain

**Comment by jesmrec** [comment]
> Does the Android app asks for user consent before connecting to the new host?

No, afaik. Only asking in case certificate has issues.

**Comment by jesmrec** [comment]
Related: https://github.com/owncloud/android/pull/2970
