### ISSUE TITLE
[FEATURE REQUEST] Calens Changelog

### ISSUE THREAD

**Issue by hosy** [owncloud/android#3124]
Use [Calens](https://github.com/restic/calens) to automatically generate a proper changelog for every release.
Calens is already used other ownCloud repositories.

**Describe the solution you'd like**
Use GitHub Actions to run this task automatically and check, if an changelog update is needed. This iOS repository is already using GitHub Actions for this.

iOS PR: https://github.com/owncloud/ios-app/pull/879

### PR
#3135

**Comment by jesmrec** [comment]
https://github.com/owncloud/android/pull/3135#issue-584666891
