### ISSUE TITLE
App closes just after opening

### ISSUE THREAD

**Issue by HimanshuGirase** [owncloud/android#3137]
I have the issue when I install tha app on my android phone. It install but it closed imdedgtely, without showing any error. Can anyone help me.
Thanks

_Originally posted by @nidasajjad in https://github.com/owncloud/android/issues/2060#issuecomment-585897958_

**Comment by abelgardep** [comment]
Hi @HimanshuGirase, did you installed it from GPlay, or did you installed it via Android Studio?

**Comment by jesmrec** [comment]
No info, no feedback. Closing... please, feel free to reopen in case there is more relevant info.
