### ISSUE TITLE
[FEATURE REQUEST] Scan Documents

### ISSUE THREAD

**Issue by Bables55** [owncloud/android#3145]
**Is your feature request related to a problem? Please describe.**
I would like the Android version to have the "Scan Document" function that the iOS version has.

**Describe the solution you'd like**
Also introduced in Android version

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
Thanks for opening an issue! We already have this feature request in our backlog: https://github.com/owncloud/android/issues/2119 So, I will close this in order not to have duplicates.
