### ISSUE TITLE
[FEATURE REQUEST] Sync action in previews

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3155]
There are four kind of files that are previewed inside the app:

- Images
- Text (.txt)
- Video
- Audio

Actually, the preview mode provides different actions, depending on the kind of file. We should review and unify actions for every kind of file.

This is the current status, that makes sense.

||Sync|Share|Send|Open with|Av. off|Details|Delete|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|Image | ❌ | ✅  | ✅  | ✅  | ✅  | ✅  | ✅  |
|Text | ❌ | ✅  | ✅  | ✅  | ✅  | ✅  | ✅  |
|Video (streaming) | ❌  | ✅  | ❌  | ❌  | ❌  | ✅  | ✅  |
|Video (downloaded) | ❌  | ✅  | ✅   | ✅   | ✅   | ✅  | ✅  |
|Audio | ✅  | ✅  | ✅  | ✅  | ✅  | ✅  | ✅ 

The main difference is that the Audio previews allow to sync the file. 

Should the sync option be removed from audio? or added in the other ones.

In my opinion, i'd remove it from audio. What do you think?

**Comment by michaelstingl** [comment]
> In my opinion, i'd remove it from audio. What do you think?

Syncing action should be sufficient on the file list entry.
