### ISSUE TITLE
[BUG]Still no lint check in CI ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3167]
I guess you still don't run `lint` in CI

<img width="852" alt="image" src="https://user-images.githubusercontent.com/3314607/112296225-fe094180-8c94-11eb-922e-ba0e5d7a00df.png">

**Comment by abelgardep** [comment]
Yes, we have it.

We also have the GET_ACCOUNTS permission in the manifest: https://github.com/owncloud/android/blob/master/owncloudApp/src/main/AndroidManifest.xml#L31

Probably it needs a rebuild 👍

**Comment by hannesa2** [comment]
Right, reopen project solves it
