### ISSUE TITLE
Show thumbnails for pictures

### ISSUE THREAD

**Issue by mbiebl** [owncloud/android#317]
In folder view, it would be nice if the android apps shows thumbnails for pictures much like it is done in OC 6.0 now.

**Comment by kugel-** [comment]
Is there anything I need to to enable the thumbnails? I do have OC8.1 and the latest client release

**Comment by tobiasKaminsky** [comment]
@kugel- There is no need to activate anything - normally.
Do you see previews in the web interface?

**Comment by kugel-** [comment]
Am 10. Juli 2015 18:18:57 MESZ, schrieb tobiasKaminsky <notifications@github.com>:
>@kugel- There is no need to activate anything - normally.
>Do you see previews in the web interface?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/android/issues/317#issuecomment-120449648

Yes, but not in the Android client (v1.7.1)

**Comment by tobiasKaminsky** [comment]
Ah :/ 
Edit was slower than your email system ;)
Can you please open a new issue to keep this one clean ;)

Can you try it with the demo account? 
demo.owncloud.org
test / test

**Comment by kugel-** [comment]
Am 10. Juli 2015 18:28:12 MESZ, schrieb tobiasKaminsky <notifications@github.com>:
>Ah :/ 
>Edit was slower than your email system ;)
>Can you please open a new issue to keep this one clean ;)
>
>Can you try it with the demo account? 
>demo.owncloud.org
>test / test
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/android/issues/317#issuecomment-120451779

Okay, I'll take it back, I do have thumbnails now. It seems my server decided to delete it's thumbnails during the upgrade, and regeneration takes a while (the server is slow, a banana pi board)

**Comment by tobiasKaminsky** [comment]
Great to hear :)
