### ISSUE TITLE
Notification settings shows "File sync" twice

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#3185]
If a user goest to the app settings to change the behaviour of the OwnCloud notification he will see the point "File sync" twice. This should either be only one option or make it clear what is the difference between those two.
However the next steps would be to find out why this option is shown twice.

This was tested on android 10 and 11:
![out](https://user-images.githubusercontent.com/1891273/113304326-3696c400-9302-11eb-98b1-6bed4b6d7aeb.png)

**Comment by jesmrec** [comment]
Needs to be reviewed in the context of the new architecture, when all the notifications are handled in the Sync actions. At this moment, all the stuff will be rewritten/refactored and this one should be avoided in some way.

**Comment by jesmrec** [comment]
Fixed. To be released in 3.0
