### ISSUE TITLE
[BUG] White title on white background in AlertDialogs in Samsung devices

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3192]
### Actual behaviour
In Samsung devices, when you open any AlertDialog in the app, the title is shown white-colored, and since the background is also white, it becomes illegible. A screenshot where we can see the problem:

![device-2021-04-06-155007](https://user-images.githubusercontent.com/57049315/113828239-76d3c780-9784-11eb-8b0a-324a24675463.png)

### Expected behaviour
The title should appear in black so that it is perfectly legible, as it does in any other not-Samsung device.
 
### Steps to reproduce
1. Select with a long tap any folder or file
2. Tap the share button in the Action Bar
3. Tap the "+" button next to "Public links"

This is an example of an AlertDialog with title in the app, we can find more through the different screens.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes it can, it's a bug in the front-end part of the app, so the server is not important here.

### Environment data
It's been checked with 2 different Samsung devices:

Android version: 9
Device model: Samsung Galaxy S9
ownCloud app version: 2.17

Android version: 11
Device model: Samsung Galaxy S10+
ownCloud app version: 2.17

It has also been tested with another devices such as Nexus 5 (Android 10), Nexus 6P (Android 7), Huawei P20 Lite (Android 9) and Pixel 2 (Android 11), and working fine in all of them.

**Comment by jesmrec** [comment]
Some black magic in Samsung devices. It will be checked.
