### ISSUE TITLE
[BUG] android app for files_sharing 0.14.0 can not normal sharing 

### ISSUE THREAD

**Issue by Xipro** [owncloud/android#3195]
-After a day's debugging, I finally found that Android application, the 2.17 version, could not be shared under server 10.6, 10.7 version, but if returned to the 10.5 version, you can share files or directories. How can I set up the server to make the version match.
if i chang the files_sharing to 0.13.0,and the sharing is ok,but use the 0.14.0 ,sharing bug come back.

ownCloud app version:2.17
ownCloud server version:10.7.0.4

![1](https://user-images.githubusercontent.com/60082211/113957602-1b700b00-9852-11eb-9e9e-f16e736ad3e4.gif) | ![2](https://user-images.githubusercontent.com/60082211/113957605-1ca13800-9852-11eb-9557-c33f6c498b05.gif) | ![3](https://user-images.githubusercontent.com/60082211/113957609-1d39ce80-9852-11eb-9b99-c6f23aa097c6.gif)
-- | -- | --

**Comment by jesmrec** [comment]
`- files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing`

with server 

`{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.7.0.4","versionstring":"10.7.0","edition":"Enterprise","productname":"ownCloud"}`

is working fine for me. Please, could you detail which the problem is? recipients don't match? share is not submitted? public share, share with users/groups or both? 

If you could details steps to reproduce, android version, app version, server and sharing version will help a lot in order to reproduce. Thanks for reporting!!

**Comment by Xipro** [comment]
The problem is share is not submitted,both public share and share to users/groups,it is all cant.
app is 2.17 release.
the following log:
04-08 15:45:40.908 W: ActionBarDrawerToggle( 2700): DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
04-08 15:45:40.913 E: (FileDisplayActivity.kt:339) .initFragmentsWithFile()( 2700): Still have a chance to lose the initialization of list fragment >(
04-08 15:45:40.923 E: (FileDisplayActivity.kt:900) .setBackgroundText()( 2700): OCFileListFragment is null
04-08 15:45:40.929 W: Resources( 2700): Drawable com.owncloud.android:drawable/ic_action_create_dir has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
04-08 15:45:40.929 W: Resources( 2700): java.lang.RuntimeException
04-08 15:45:40.929 W: Resources( 2700): 	at android.content.res.Resources.getDrawable(Resources.java:746)
04-08 15:45:40.929 W: Resources( 2700): 	at com.getbase.floatingactionbutton.FloatingActionButton.getIconDrawable(FloatingActionButton.java:273)
04-08 15:45:40.929 W: Resources( 2700): 	at com.getbase.floatingactionbutton.FloatingActionButton.updateBackground(FloatingActionButton.java:239)
04-08 15:45:40.929 W: Resources( 2700): 	at com.getbase.floatingactionbutton.FloatingActionButton.init(FloatingActionButton.java:90)
04-08 15:45:40.929 W: Resources( 2700): 	at com.getbase.floatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:66)
04-08 15:45:40.929 W: Resources( 2700): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-08 15:45:40.929 W: Resources( 2700): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
04-08 15:45:40.929 W: Resources( 2700): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
04-08 15:45:40.929 W: Resources( 2700): 	at com.owncloud.android.ui.fragment.ExtendedListFragment.onCreateView(ExtendedListFragment.java:146)
04-08 15:45:40.929 W: Resources( 2700): 	at com.owncloud.android.ui.fragment.OCFileListFragment.onCreateView(OCFileListFragment.java:213)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2952)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
04-08 15:45:40.929 W: Resources( 2700): 	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:436)
04-08 15:45:40.929 W: Resources( 2700): 	at com.owncloud.android.ui.activity.DrawerActivity.onResume(DrawerActivity.kt:558)
04-08 15:45:40.929 W: Resources( 2700): 	at com.owncloud.android.ui.activity.FileActivity.onResume(FileActivity.java:175)
04-08 15:45:40.929 W: Resources( 2700): 	at com.owncloud.android.ui.activity.FileDisplayActivity.onResume(FileDisplayActivity.kt:697)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.Activity.performResume(Activity.java:6843)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3407)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
04-08 15:45:40.929 W: Resources( 2700): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-08 15:45:40.929 W: Resources( 2700): 	at android.os.Looper.loop(Looper.java:154)
04-08 15:45:40.929 W: Resources( 2700): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
04-08 15:45:40.929 W: Resources( 2700): 	at java.lang.reflect.Method.invoke(Native Method)
04-08 15:45:40.929 W: Resources( 2700): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-08 15:45:40.929 W: Resources( 2700): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-08 15:45:40.932 W: (DrawerActivity.kt:494) .setDrawerMenuItemChecked()( 2700): setDrawerMenuItemChecked has been called with invalid menu-item-ID
04-08 15:45:41.147 W: (GetRemoteUserAvatarOperation.kt:67) .run()( 2700): Not an image, failing with no avatar
04-08 15:45:41.231 W: (GetRemoteUserAvatarOperation.kt:67) .run()( 2700): Not an image, failing with no avatar
04-08 15:45:42.005 W: (GetRemoteUserAvatarOperation.kt:67) .run()( 2700): Not an image, failing with no avatar
04-08 15:45:45.024 W: (DrawerActivity.kt:494) .setDrawerMenuItemChecked()( 2700): setDrawerMenuItemChecked has been called with invalid menu-item-ID
04-08 15:45:51.702 W: IInputConnectionWrapper( 2700): finishComposingText on inactive InputConnection
04-08 15:45:53.046 W: IInputConnectionWrapper( 2700): finishComposingText on inactive InputConnection
04-08 15:45:54.307 W: IInputConnectionWrapper( 2700): finishComposingText on inactive InputConnection
04-08 15:45:55.290 W: (DrawerActivity.kt:494) .setDrawerMenuItemChecked()( 2700): setDrawerMenuItemChecked has been called with invalid menu-item-ID
04-08 15:45:55.448 W: (GetRemoteUserAvatarOperation.kt:67) .run()( 2700): Not an image, failing with no avatar
04-08 15:45:56.418 W: (GetRemoteUserAvatarOperation.kt:67) .run()( 2700): Not an image, failing with no avatar


E: 2021-04-08 15:45:40:913(FileDisplayActivity.kt:339) .initFragmentsWithFile()Still have a chance to lose the initialization of list fragment >(
E: 2021-04-08 15:45:40:923(FileDisplayActivity.kt:900) .setBackgroundText()OCFileListFragment is null
W: 2021-04-08 15:45:40:931(DrawerActivity.kt:494) .setDrawerMenuItemChecked()setDrawerMenuItemChecked has been called with invalid menu-item-ID
W: 2021-04-08 15:45:41:144(GetRemoteUserAvatarOperation.kt:67) .run()Not an image, failing with no avatar
W: 2021-04-08 15:45:41:231(GetRemoteUserAvatarOperation.kt:67) .run()Not an image, failing with no avatar
W: 2021-04-08 15:45:42:004(GetRemoteUserAvatarOperation.kt:67) .run()Not an image, failing with no avatar
W: 2021-04-08 15:45:45:024(DrawerActivity.kt:494) .setDrawerMenuItemChecked()setDrawerMenuItemChecked has been called with invalid menu-item-ID
W: 2021-04-08 15:45:55:289(DrawerActivity.kt:494) .setDrawerMenuItemChecked()setDrawerMenuItemChecked has been called with invalid menu-item-ID
W: 2021-04-08 15:45:55:447(GetRemoteUserAvatarOperation.kt:67) .run()Not an image, failing with no avatar
W: 2021-04-08 15:45:56:416(GetRemoteUserAvatarOperation.kt:67) .run()Not an image, failing with no avatar
W: 2021-04-08 15:47:37:894(DrawerActivity.kt:494) .setDrawerMenuItemChecked()setDrawerMenuItemChecked has been called with invalid menu-item-ID

**Comment by Xipro** [comment]
android version:7.1.2
app version:2.17 release
server version:10.7.0.4
sharing version:0.14.0

**Comment by Xipro** [comment]
server version: 10.7.0.4 Community

**Comment by jesmrec** [comment]
that log is not revealing important info about the problem. Do you have the option `Log HTTP request and responses` enabled in the Settings?  

Could you translate?:

![Screenshot 2021-04-08 at 10 34 21](https://user-images.githubusercontent.com/14894746/113994875-06957680-9856-11eb-8672-8d52530a3947.png)

**Comment by Xipro** [comment]
I try four times,and this error is appear every time.

E: 2021-04-08 17:35:24:952(FileDisplayActivity.kt:339) .initFragmentsWithFile()Still have a chance to lose the initialization of list fragment >(
E: 2021-04-08 17:35:24:967(FileDisplayActivity.kt:900) .setBackgroundText()OCFileListFragment is null
E: 2021-04-08 17:35:30:021(FileDisplayActivity.kt:339) .initFragmentsWithFile()Still have a chance to lose the initialization of list fragment >(
E: 2021-04-08 17:35:30:028(FileDisplayActivity.kt:900) .setBackgroundText()OCFileListFragment is null
E: 2021-04-08 17:37:54:633(FileDisplayActivity.kt:339) .initFragmentsWithFile()Still have a chance to lose the initialization of list fragment >(
E: 2021-04-08 17:37:54:641(FileDisplayActivity.kt:900) .setBackgroundText()OCFileListFragment is null
E: 2021-04-08 17:38:31:040(FileDisplayActivity.kt:339) .initFragmentsWithFile()Still have a chance to lose the initialization of list fragment >(
E: 2021-04-08 17:38:31:046(FileDisplayActivity.kt:900) .setBackgroundText()OCFileListFragment is null

The app notice translate is about:
It was not possible to retrieve the shares from server because malformed server configurations.

**Comment by jesmrec** [comment]
> {"reqId":"30b836e4-34de-431c-a42e-3b8b5dbd0ae2","level":0,"time":"2021-04-08T17:45:53+08:00","remoteAddr":"10.32.75.85","user":"Xipron","app":"OC\Authentication\Token\DefaultTokenProvider::getToken","method":"GET","url":"/index.php/avatar/Xipron/192","message":"token 78b89c6748615ee8d414d500dcb8a5fb92bec0711870df255c1ac779693ac60462dc751e5dca417d70adf433efd45d081bc374ee4af8b6193c6879619b94273d does not exist"}

it seems that something is broken with the token. Are you using OAuth2?

**Comment by michaelstingl** [comment]
@Xipro please make sure you have all the required Apache modules installed:
https://doc.owncloud.com/server/admin_manual/installation/manual_installation.html#additional-apache-configurations
(`mod_rewrite` especially)

**Comment by Xipro** [comment]
I will check the apache tomorrow,thank you.

**Comment by Xipro** [comment]
@michaelstingl I checked my apache configration,all mod is installed,it is not the reason for this issue.

**Comment by jesmrec** [comment]
Could you send us a test account on your server to `android-app@owncloud.com`?

**Comment by Xipro** [comment]
@jesmrec yes,i can ,and i will prepel a test account and a proxy to my servers.
server:https://oc.xipron.f3322.net:8443
account:test,paswd:test.

**Comment by Xipro** [comment]
@jesmrec Can you enter my server for test account?

**Comment by Xipro** [comment]
@jesmrec Because some reason,I close the proxy for my server,if you want enter it ,please tell me about time.

**Comment by jesmrec** [comment]
@xipro let me know when it is available. The proper time for me is 8CEST - 15CEST. I have checked the email, and i saw a couple of mails from you, but they do not include credentials.

**Comment by Xipro** [comment]
@jesmrec I changed my proxy setting,and now the server is openning.
https://oc.xipron.f3322.net:8443
account:test
password:test.
thankyou.

**Comment by Xipro** [comment]
@jesmrec You can use the web version to log in, read oclog in the top left of the page and external website, and view the server log.

**Comment by Xipro** [comment]
@jesmrec Hello, can you check my server configuration tomorrow? Because, my server is deployed in the intranet, to the day after tomorrow, need to open to colleagues for production activities.

**Comment by michaelstingl** [comment]
@Xipro If your issue is critical for you business, please consider professional support (with guaranteed SLA etc) from the ownCloud team:
https://owncloud.com/pricing/

**Comment by Xipro** [comment]
@michaelstingl My server is only used for temporary production activities within the unit. If all problems can be solved later, it may be used for formal production activities.

**Comment by Xipro** [comment]
@jesmrec my server is opening for test account,please help look at it and find the reason of issue.

**Comment by jesmrec** [comment]
@Xipro i've checked your test account. After trying to share a file with a user, i get a 500 error (server error), with the following body:

```
<?xml version="1.0"?>
<ocs>
  <meta>
  <status>failure</status>
  <statuscode>500</statuscode>
  <message>CSRF check failed</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
  </meta>
  <data/>
</ocs>
```

afaik, this is not a problem of the Android app. In fact, i've check with iOS and desktop client, and they returns the same error. As @michaelstingl commented you above, probably you have any problem in your server related with the modules.

**Comment by Xipro** [comment]
@jesmrec thank you for you help ,but i have install all the need modules for apache,and if i made the files_sharing version back to 0.13.0 with the same server,the issue is disappear.
so i think maybe the files_sharing version update is the reason about this bug.

**Comment by Xipro** [comment]
@jesmrec I fix my sever conf and thank you very much.

**Comment by jesmrec** [comment]
you are welcome

**Comment by AubinF** [comment]
HI, I think I have the same issue. How shall I proceed to downgrade files_sharing to 0.13.0? Thanks

**Comment by AubinF** [comment]
up up
