### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by Xipro** [owncloud/android#3196]
I want used 'gradlew clean build' to build a android apk,but:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':owncloudApp:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':owncloudApp:releaseCompileClasspath'.
   > Could not resolve project :owncloud-android-library:owncloudComLibrary.
     Required by:
         project :owncloudApp > project :owncloudData
      > No matching configuration of project :owncloud-android-library:owncloudComLibrary was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

So,what can i do for this problem?

**Comment by hannesa2** [comment]
`git submodule update --init`

**Comment by Xipro** [comment]
I cant understand?what did i miss?

**Comment by abelgardep** [comment]
Hi, did you clone the repository using the `--recursive` clause?

Follow the [setup guide](https://github.com/owncloud/android/blob/master/SETUP.md#1-fork-and-download-the-owncloudandroid-repository) and tell us if something is still wrong.

**Comment by Xipro** [comment]
No,i dont ,so i will try and thankyou!

**Comment by Xipro** [comment]
Unsupported class file major version 60.
i used jdk-16-16-ga.x86_64,is this the reason?

**Comment by abelgardep** [comment]
Yes, that's it. Currently, we use gradle v6.8.1 and it does not support Java 16.
You can take a look at https://github.com/gradle/gradle/issues/13481

**Comment by Xipro** [comment]
I got it and thankyou!
