### ISSUE TITLE
[BUG] app always uses current active account to upload photos to

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android#3199]
The automatic image upload does is not able to remember the account to upload photos and videos to. So the App will upload them to the account that is currently selected. There is a preference field available for depicting the upload account,
however it gets read but never set. Which means that the current active account is always the one to which the photos get uploaded:
https://github.com/owncloud/android/blob/5ee39ab7eed678018120b78da9380bd680a424ba/owncloudApp/src/main/java/com/owncloud/android/db/PreferenceManager.java#L111-L116

This is reflected in the shared preferences, where not upload account can be found:
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="set_biometric" value="false" />
    <string name="camera_picture_uploads_path">/Autoupload/</string>
    <string name="select_oc_account">admin@schabisT14:8080</string>
    <boolean name="set_pattern" value="false" />
    <boolean name="camera_video_uploads" value="true" />
    <string name="camera_uploads_behaviour">NOTHING</string>
    <boolean name="camera_picture_uploads_on_wifi" value="false" />
    <boolean name="camera_picture_uploads" value="true" />
    <boolean name="set_pincode" value="false" />
</map>
```

- We should add a field to the settings where the user can select the account to upload the photos to.
- If the user has not yet selected one, the account that is used during the enabling of the photo upload, should be the one put in this field.
- If the user removes the account to which the photos get uploaded to, photo upload should get disabled and the user should be notified about that.

**Comment by michaelstingl** [comment]
Maybe can be aligned with iOS user flow.

**Comment by abelgardep** [comment]
This is basically the same: https://github.com/owncloud/android/issues/3166

**Comment by jesmrec** [comment]
Two different things:

1. The bug about getting but not setting -> to be done here as first step
2. All the new stuff (selecting account, deselecting when account is removed...) -> described in #3166

**Comment by jesmrec** [comment]
Added to #3166
