### ISSUE TITLE
[BUG] Shows message "Nothing in here. Upload something!" while SMB folder contains dozens of files/folders

### ISSUE THREAD

**Issue by d3ssen** [owncloud/android#3205]
### Actual behaviour
- Using admin-account; mounted SMB share from Windows Server into OwnCloud (PHP)
- Using user-account; Open Android app, browse to mounted share, shows message "Nothing in here...".
- Using same user-account; Open Web-UI, browse to mounted share, shows files/folders.

### Expected behaviour
- Expect Android app to show same files/folders as Web-UI.
 
### Steps to reproduce
1. Mount SMB share from Windows Server using admin-account.
2. Open SMB share using user-account.
3. Get message that no files/folders are in the share.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, demo-server is not using SMB shares from Windows Server, only local files/folders.

### Environment data
Android version: 10
Device model: Motorola Moto G9+
Stock or customized system: Custom build Ubuntu Server with PHP 7.4
ownCloud app version: 2.17 rel. 51dc2abce
ownCloud server version: 10.7.0.4

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
[owncloud.log](https://github.com/owncloud/android/files/6336337/owncloud.log)
```

**Comment by enbrnz** [comment]
Hi @d3ssen,

I have an SMB test server and I haven't been able to reproduce the described behavior:

![Screenshot_20210426_143710](https://user-images.githubusercontent.com/49983818/116084698-566d9d80-a69e-11eb-9c25-2a18d6b3c13b.png)
![photo_2021-04-26_14-42-23](https://user-images.githubusercontent.com/49983818/116084506-2cb47680-a69e-11eb-99bd-9d9bbcb97bff.jpg)
![photo_2021-04-26_14-42-22](https://user-images.githubusercontent.com/49983818/116084511-2e7e3a00-a69e-11eb-9ffd-5b2aa025bfcb.jpg)


Perhaps there is some issue with your server configuration? 
E.g. you have to be aware that the Android app doesn't create a session on the server. Therefore you can't use "Log-in credentials, save in session", change it to "Log-in credentials, save in database" if that is the case.

This is for me currently the only explanation I'd have for SMB working in the WebUI but not in an app or sync-client.

**Comment by d3ssen** [comment]
I've reinstalled OwnCloud PHP on my webserver and somehow the Android version now finds the folders and files of the SMB share. I'm not sure if I did anything different while configuring storage in OwnCloud, but for now it works.
