### ISSUE TITLE
Owncloud Server took too long to respond

### ISSUE THREAD

**Issue by crhaerich** [owncloud/android#3256]
I am having an issue with owncloud taking too long to respond when trying to log in while off my home network.  I use my public IP/owncloud as the server and that is when I get the error message.  When I originally setup the owncloud it worked but here a couple weeks ago it stopped working.  Nothing changed on my server.  I am running server version 10.7.0 (stable) and I have tried to both use the android app as well as going to https://public IP/owncloud and neither work.  I have port 443 forwarded to my server's private IP but still nothing.  I will note that when I went to the https:// public IP/owncloud it didn't give me the took too long message it gave me that it refused the connection.  when I set up the owncloud server I made sure to add my public IP address as a trusted domain.  The android app I am using is version 2.17 release 51dc2abce.  I am still new to owncloud so any help would be appreciated.

**Comment by michaelstingl** [comment]
Can you access the ownCloud web UI from the browser on the same device?

**Comment by crhaerich** [comment]
Yes and when I am on my home network both the web web browser and app work on my phone. It's just when my phone is not on my home network that it doesn't work.

**Comment by jesmrec** [comment]
but the webUI is accesible from your phone outside your home network?

**Comment by crhaerich** [comment]
No if im not on my home network I can't reach my owncloud at all.

**Comment by crhaerich** [comment]
Not sure if it matters but on my laptop I have the same issue with both the Linux app ownCloud 2.7.6 (build 3261) and the web UI when I am not on my home network it doesn't allow me access and when I am on my home network it works just fine.

**Comment by jesmrec** [comment]
Then, you have a problem with your infra setup to make your server accessible form outside, no matter which client you use. Please, check the way in which your firewall rules are banning the access from outside. 

Sorry, but this topic has nothing to do with Android

You can try to get more help in the open forum, just in case the oC server is involved: https://central.owncloud.org/

**Comment by jesmrec** [comment]
Closing. Please, feel free to reopen if you discover any Android relation with the problem.
