### ISSUE TITLE
Make the welcome text setup-able

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3309]
Text for the help link in our login page should be setup-able:

![Screenshot 2021-07-14 at 12 27 06](https://user-images.githubusercontent.com/14894746/125607381-d27d3a58-68a8-4e25-96a2-e3bd3d790cdb.png)

- Link must work in the same way (target is already setup-able:)
- Default will be the current string
- Text will be plain text. Actually, the string contains a parameter with the app name:

`<string name="auth_register">New to %1$s?</string>`

parameter could be lost. This is something to take in account in the code, i guess.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App https://github.com/owncloud/android/pull/3311
- Library (if needed)

**Comment by michaelstingl** [comment]
@NannaBarz FYI

**Comment by abelgardep** [comment]
We would need a different string, at the moment `auth_register`:  `New to ` is translated to different languages.

We would need to add a new non-translatable string that will be branded.
