### ISSUE TITLE
[BUG] Folder selection for camera folder only shows "Downloads" 

### ISSUE THREAD

**Issue by CoolRunnerII** [owncloud/android#3330]
### Actual behaviour
- No other folder than "Downloads" is selectable when choosing camera folder
![Screenshot_20210727_113232_com android documentsui](https://user-images.githubusercontent.com/1972241/127132837-abc43e71-ad4f-4040-8b73-d85dadd164e3.jpg)
![Screenshot_20210727_113220_com android documentsui](https://user-images.githubusercontent.com/1972241/127133002-1a3ca0e5-7692-4804-8df4-3cf29f6876e9.jpg)

### Expected behaviour
- It should show all the folders in the same way as when uploading files manually
![Screenshot_20210727_114340_com android documentsui](https://user-images.githubusercontent.com/1972241/127133363-2d1c1230-077d-4f60-a319-16341d5a2db1.jpg)

 
### Steps to reproduce

1. Select "settings"
2. Select "Auto upload pictures"
3. Select "Camera folder"
- Then only "Downlods" folder is shown and there is no way to navigate out of it.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
N/A

### Environment data
Android version:
EMUI 10.0.0.190(C432E8R1P3patch0)

Device model: 
Huawei P20pro

Stock or customized system:
Stock

ownCloud app version:
2.18.1

ownCloud server version:
N/A

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by CoolRunnerII** [comment]
Selection of Video folder behaves in the same way.

**Comment by jesmrec** [comment]
Which options are available in the three-dot-button, at the right of `Downloads` ?

Probably you'll find something like `Show/Hide internal storage` .

**Comment by abelgardep** [comment]
Hi @CoolRunnerII , you should be able to `show/hide internal storage` as @jesmrec states. Here I show you a little demo:

![show_internal_storage](https://user-images.githubusercontent.com/47524927/127140966-24ec163a-1c4c-452e-994a-53bbd405f3a3.gif)

**Comment by CoolRunnerII** [comment]
Thanks a lot!

After pressing "show internal storage" a new item called "CLT-L29" showed up and in there I could find the camera folder.
