### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by evilchris** [owncloud/android#3343]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when
[First, Seems I cannot automatically upload my old photos, 
and when I copy a photo into the sync folder, 
it cannot be detected. ]
[Second, I found I just can sync my one photo folder like "/DCIM/Camera", but I have many other photos in another folders]
[Third, the sub-folder cannot be sync]

**Describe the solution you'd like**
[First, if the app can let me sync more than 1 picture folder automatically is better]
[Secend, if the app can let me sync the sub-folder automatically is better]
[Third, if the app can let me sync a not picture folder automatically is better.]

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
So, you want to sync old/new stuff in different folders than the camera folder. And, more than one folder to sync.

We have an issue for such feature: https://github.com/owncloud/android/issues/3126

Please, track the issue there. Also, you can add as many comments as you want.

I close this one as duplicated.

Please, don't forget to add a descriptive title when you open new issues

Thanks anyway!!
