### ISSUE TITLE
Document provider edition with 3rd party apps

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3345]
Check these steps out:

1. Open any app that uses SAF (like `Files`), and select the ownCloud provider  
2. Select a file inside the account that can be opened with a 3rd party app that also supports SAF (like MS Word) -> file opened with the 3rd party app
3. Edit the file and save it

Current: The only way to save is creating another file with the new version. No way to save the modifications in the same file that was opened in 2.

Expected/Desired: After modifying the file, changes are saved in the same file.

Pixel2, Android 11

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
Tested it with https://play.google.com/store/apps/details?id=com.byteexperts.texteditor and it worked.

I'll test it with MS Word, not sure why it fails 🤔

**Comment by jesmrec** [comment]
The problem described above is reproducible with MS Word but not with other providers, so, it seems to be a problem of the documents provider implementation of such app

Just an example: the app `Text Editor`  (https://play.google.com/store/apps/details?id=com.byteexperts.texteditor) also implements the document provider and saves the edited file by overwriting the previous version (same as `Open with`)

So, this is not a problem of oC app, this is a feature that depends on the other provider's implementation.

Closing. Feel free to reopen if other ideas or issues related are relevant.
