### ISSUE TITLE
[FEATURE REQUEST] Add APK to huawei appgallery

### ISSUE THREAD

**Issue by Milokita** [owncloud/android#3348]
**Is your feature request related to a problem? Please describe.**
The apk cannot be found in Huawei Appgallery in China, now with Nextcloud official app have reached 130 thousands download. It's time to catch up.  

**Describe the solution you'd like**
Add the official apk to Huawei AppGallery

**Describe alternatives you've considered**
N/A

**Additional context**

### TASKS

- [ ] Register Huawei's Developer Account (if needed)
- [ ] Submit the apk

**Comment by jesmrec** [comment]
Thanks for the suggestion. We'll check.

**Comment by michaelstingl** [comment]
ownCloud.online should work fine:
https://appgallery.huawei.com/#/app/C100861511

…or you use F-Droid.

**Comment by Milokita** [comment]
I have access to Google Play but others who live in China cannot and usually not aware of F-Droid.
May I suggest change the app name? I think "ownCloud.online" sounds misleading and caused the mere 3K download.

**Comment by michaelstingl** [comment]
`*.APK` can be also downloaded for every release:
- https://github.com/owncloud/android/releases
