### ISSUE TITLE
Add access to the changelog in the interface

### ISSUE THREAD

**Issue by jpggithub** [owncloud/android#335]
Hi,

It would be nice to access to the changelog from the interface instead of searching the web or going on the google play store.

Regards,
jpg

**Comment by Dinsmoor** [comment]
@jancborchardt , what about F-Droid users?

**Comment by AndyScherzinger** [comment]
I did implement such a thing for Andlytics three years ago:
https://github.com/AndlyticsProject/andlytics/blob/master/src/com/github/andlyticsproject/util/ChangelogBuilder.java

Basically the app ships a changelog html file which gets loaded a single time for every new version installed/updated by the user. So the store wouldn't matter. The downside for now would be to maintain this changelog before every release else it works like a charm :+1: .

**Comment by LukeOwncloud** [comment]
@AndyScherzinger, I did that already: https://github.com/owncloud/android/pull/368/files
Unfortunately, I had Eclipse's auto format option enabled... So it was never merged.

I think the up-to-date problem for every release (and every target platform!) is not to be neglected. I would plea for a simple web-based changelog like. Just like: https://owncloud.org/changelog/ (And then add a link to Play Store, Android+iOS app).

**Comment by jancborchardt** [comment]
@LukeOwncloud yeah, good call. Web-based changelog seems to be the best option. We can of course just copy the relevant parts to the Play Store, iOS app store and platforms which support that for easier access.
