### ISSUE TITLE
[BUG] Button in Welcome Wizard is oval

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/android#3351]
### Actual behaviour
- At the end of the welcome-wizard, the button is oval
![Screenshot_20210818-134557](https://user-images.githubusercontent.com/26610733/129895170-5596dded-41b1-42ee-bf0b-6c213899726e.png)

### Expected behaviour
- button should be round i guess ;-)
 
### Steps to reproduce
1. fresh install of the app
2. step till the last panel
3. button is oval

### Environment data
Android version: Android 12 Beta

Device model: Pixel 3

Stock or customized system: stock

ownCloud app version: 2.18.1

**Comment by abelgardep** [comment]
I think that the button is oval since the beginning. Anyway, we could update it to a round shape 👍

**Comment by tbsbdr** [comment]
not important, but would make me really happy ;-)
nice to have...

**Comment by sashpawar11** [comment]
Can you assign this to me? I would love to work on it.

**Comment by abelgardep** [comment]
Hey @sashpawar11, feel free to send a PR 💯  

I could help you in case you have any questions 👍

**Comment by sashpawar11** [comment]
Cool, thanks @abelgardep !

**Comment by sashpawar11** [comment]
> Hey @sashpawar11, feel free to send a PR 💯
> 
> I could help you in case you have any questions 👍

Hey I'm unable to find the exact activity for the above screen, could you help me out?

**Comment by abelgardep** [comment]
It's [WhatsNewActivity](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java) and [in this method](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java#L109) the `arrow` is replaced with the `done` icon. So the problem could be in the [done icon](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/res/drawable/round_button.xml)

**Comment by sashpawar11** [comment]
Yep thanks @abelgardep , fixed it, ill make a PR soon

**Comment by sashpawar11** [comment]
So i made the shape as a round Circle which was an oval before but, how do I test the app? It asks for server address  on the startscreen and I don't have one, is there a test IP or anything so I can just try to reach the above screen quickly? @abelgardep

**Comment by michaelstingl** [comment]
> is there a test IP or anything

You can test-drive with demo.owncloud.com

**Comment by abelgardep** [comment]
Well, you won't need to add any server because that screen appears just after performing a fresh installment when we are on release mode.

In the [shouldShow](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java#L139) function we determine if the wizard needs to be shown or not. Just for testing, you can make it return true, and the wizard will appear when the app starts. This change in the `shouldShow` is just for testing. Do not send it in the PR!

If you need something else, feel free to ask @sashpawar11 👍

**Comment by sashpawar11** [comment]
> Well, you won't need to add any server because that screen appears just after performing a fresh installment when we are on release mode.
> 
> In the [shouldShow](https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java#L139) function we determine if the wizard needs to be shown or not. Just for testing, you can make it return true, and the wizard will appear when the app starts. This change in the `shouldShow` is just for testing. Do not send it in the PR!
> 
> If you need something else, feel free to ask @sashpawar11 👍

Cool got it! Thanks a lot , again! @abelgardep
