### ISSUE TITLE
[FEATURE REQUEST] Add a new option to Settings to show What's new?

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3352]
**Is your feature request related to a problem? Please describe.**
It could be useful for some users to have an option to check what was included in the latest version in case they skip the wizard.

**Describe alternatives you've considered**
Maybe a new item in the settings view would be enough. We could also replace the App Version label with a new label to indicate that by clicking on it, the `what's new wizard` will be displayed.

![device-2021-08-18-144601](https://user-images.githubusercontent.com/47524927/129900746-06698b77-acdf-413d-83a6-a6e172726edc.png)

**Additional context**
At the moment, the wizard is brandable and can be disabled. If it is disabled, I suppose that it should not be shown after clicking on it, or not shown the option in case we add a new item

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
> At the moment, the wizard is brandable and can be disabled. If it is disabled, I suppose that it should not be shown after clicking on it, or not shown the option in case we add a new item

Yes, good point!

**Comment by jesmrec** [comment]
That's it

- If the wizard is enabled in `setup.xml`
  - Last update wizard should be displayed
  - If last version did not include wizard, option should be hidden in `Settings`

- If wizard is disabled in `setup.xml`
  - Option should be hidden in `setup.xml`

I think that this feature does not make sense for the welcome wizard.

**Comment by davcres** [comment]
Hello @tbsbdr.

Which icon do you think is better to represent the new option in Settings "What´s new in the latest version?"?
The last one is called "new release" but I think a list icon is a good option too.

| Option 1 | Option 2 | Option 3 |
|:-:|:-:|:-:|
| <img width="300" alt="Captura de Pantalla 2022-04-07 a las 11 22 05" src="https://user-images.githubusercontent.com/78238260/162167953-63a03466-b2db-4875-9e79-4c23050750c4.png"> | <img width="300" alt="Captura de Pantalla 2022-04-07 a las 11 22 51" src="https://user-images.githubusercontent.com/78238260/162168035-f89319de-d0a8-4a90-af8c-2d44f9acf8d6.png"> | <img width="300" alt="Captura de Pantalla 2022-04-07 a las 11 23 10" src="https://user-images.githubusercontent.com/78238260/162168052-2d2a0240-64e8-495c-976f-49307cdc2fb5.png"> |

Thank you.

**Comment by tbsbdr** [comment]
Both - "list" and "!" don't make really want to click it tbh.
I'd suggest to be more bold and use something like
![image](https://user-images.githubusercontent.com/26610733/162176024-8fa845df-d8a6-41c3-8457-91a383af0de8.png)
![image](https://user-images.githubusercontent.com/26610733/162176042-04a70d63-5505-4762-b8c8-e900034fbd04.png)

(I would prefer auto-awesome 🌈 )

**Comment by jesmrec** [comment]
Done!!
