### ISSUE TITLE
PIN input recognition is slow

### ISSUE THREAD

**Issue by zirydy** [owncloud/android#336]
As one reviewer on Google Play store points out, the recognition of PIN input is quite slow. I would type faster than the app can recognize almost every time. I would like to request that the time of delay between the input of each digit be reduced.

**Comment by tobiasKaminsky** [comment]
After a quick search it seems not to be possible to reuse this...
(http://stackoverflow.com/questions/10106837/use-system-pin-dialog-in-android-application)

@zirydy Is your problem with slow recognition solved?
I have tried it on real devices (Nexus 4 and 7) and on Android 2.4.4 (in an emulator) and cannot reproduce it...

**Comment by davivel** [comment]
I cannot reproduce this either.

@zirydy , if still a problem for you, comment back, please.

Thanks.

**Comment by sentaidigital** [comment]
I have this same issue.  If I use example PIN 1234, the keyboard will only recognize 14 when typing at normal speed.  I have to wait about half a second between digits to input the full PIN.  I end up stabbing at each digit until I feel the phone vibrate.

Galaxy S3, 4.4.2.

**Comment by davivel** [comment]
We are reviewing the PIN code right now, so at least we'll have a look into it.

**Comment by sentaidigital** [comment]
If there is something I can do to help, such as installing a test build, please let me know.

**Comment by davivel** [comment]
This should be a bit better now, but probably there is still some room to improve it. Next release, probably named version 1.7.2, will allow to test it.

@sentaidigital , thanks for your offer, but right now we don't have a channel to distribute test builds. Unless you can built it by yourself, I can't help you with that right now.

**Comment by sentaidigital** [comment]
I just bought a Nexus 5 running 5.1.  I don't have the problem there.  I'll test with the S3 when I see 1.7.2 drop.

**Comment by zirydy** [comment]
My apologies for long absence.

While I no longer have the original Samsung device, the input recognition is now working fine for me on a new device. I would deem the bug fixed.

**Comment by tobiasKaminsky** [comment]
Glad to hear

**Comment by davivel** [comment]
:+1:
