### ISSUE TITLE
"filelist" to Room table ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3376]
Are there plans to replace  https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/db/ProviderMeta.java#L44

`public static final String FILE_TABLE_NAME = "filelist";`

with a Room table ?

If yes, is there already a pull request where I can follow ?

**Comment by abelgardep** [comment]
Hi @hannesa2, we are working on that. We are moving everything to room, but it is not available in master yet.

We moved the file list to room via this issue: https://github.com/owncloud/android/issues/2955 and PR: https://github.com/owncloud/android/pull/2995

Once everything related to synchronization is merged: https://github.com/owncloud/android/milestone/43, we will merge https://github.com/owncloud/android/pull/2934 into master.

**Comment by hannesa2** [comment]
Cool, thank you 👍 I will write my wishes there
