### ISSUE TITLE
[SPIKE] First steps about MDM integration

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3399]
### What is MDM?
MDM, which stands for Mobile Device Management, is a kind of software which allows **managing mobile devices from a IT administration platform** or console. A variant is MAM (Mobile Application Management), in which some apps' parameters and configurations can be managed remotely by IT admins. The typical context of use is an enterprise environment, in which the employees use a mobile device for work, and employers are interested in setting some personalised configurations either to the whole device or to an app or group of apps. For example: a server URL, a specific domain for emails, enforcing some security settings such as a pin code to access the app, the visibility of some UI elements...
The aim here is to be able to **manage some parameters of the ownCloud Android app via an administration platform**. A MDM/MAM solution is suitable for this requirement.

### How can we implement MDM?
As they mention in [AppConfig](https://www.appconfig.org/), a community whose aim is to offer easy-to-use EMM (enterprise mobile management) solutions, if we want to include the "app configuration" capability (the one we are interested on), our app must include **Android Enterprise** with its restrictions management to be able to use some of the IT administration platforms belonging to AppConfig.

### What is Android Enterprise?
[Android Enterprise](https://developers.google.com/android/work/overview) is a solution which provides a set of tools and APIs, with the aim to support the use of Android devices in the workplace. We can find [4 different device profiles](https://developers.google.com/android/work/overview#android_devices_enterprise_use_cases) in this context, in function of the ownership of the device and how much control the company wants over it:
- Employee-owned devices with work profile
- Company-owned devices for mixed-use with work profile
- Company-owned devices for work-only, fully-managed
- Dedicated devices, fully-managed

An employee's organization has full management control of the apps, data, and settings in their device's work profile, but has no visibility or access to the device's personal profile. This distinct separation gives enterprises control over corporate data and security without compromising employee privacy.
Android Enterprise offers support for any or all of these approaches, but we'll focus on the 3 first options, as the last one is more addressed to embedded systems.

### How can we implement Android Enterprise?
The main API to work with Android Enterprise is [Android Management API](https://developers.google.com/android/management/introduction). This API uses REST resources to provide apps with different policies or configurations.
The managed devices must install the [Android Device Policy app](https://play.google.com/store/apps/details?id=com.google.android.apps.work.clouddpc) during setup. By installing it, received management policies are automatically applied. This works as shown in the next simplified schema:

![image](https://user-images.githubusercontent.com/57049315/140027264-2e42f563-aabf-482d-9595-117a8d3b5e9d.png)

The four main resources used in Android Management API are:
- [`Enterprises`](https://developers.google.com/android/management/reference/rest/v1/enterprises): REST resource which represents a single organization.
- [`Devices`](https://developers.google.com/android/management/reference/rest/v1/enterprises.devices): REST resource which represents a correctly enrolled device.
- [`EnrollmentTokens`](https://developers.google.com/android/management/reference/rest/v1/enterprises.enrollmentTokens): REST resource used for binding a device to an enterprise.
- [`Policies`](https://developers.google.com/android/management/reference/rest/v1/enterprises.policies): REST resource which represents groups of settings in devices.

When developing the solution, we must stick to a solution set, that is, a minimum set of features the app has to support for the app to be valid following Google's guidelines. There are 3 different kinds of solution sets:

![Captura de pantalla 2021-10-15 a las 11 53 13](https://user-images.githubusercontent.com/57049315/137469426-de0f4d08-f366-4b6a-9cc7-720403290e43.png)

Some more optional and advanced features can be added to the solution, in addition to the basic features. As mentioned before, we'll focus on the 2 first options, as the third one is addressed to embedded systems. Here are the specifications for those 2 different kinds of solution sets:
- [Work profile](https://developers.google.com/android/work/requirements/work-profile)
- [Fully managed device](https://developers.google.com/android/work/requirements/fully-managed-device)

On the app's side, we must define a set of [managed configurations](https://developer.android.com/work/managed-configurations) in a XML resource file, the ones we want to manage via MDM/MAM. The value of these configurations or policies can be read using `RestrictionsManager`, and knowing the value, we can apply the corresponding logic to change the app's behaviour.

### How can we test the app?
As these are configurations that are managed remotely, from an EMM console, this is a bit tricky to test. Fortunately, Google developed an open-source app for this purpose. [Test DPC app](https://play.google.com/store/apps/details?id=com.afwsamples.testdpc&hl=es_419&gl=US) is intended for testing purposes when developing a work profile in an app. It simulates how restrictions or policies are applied by an IT admin, so it can be used to mock the EMM console until we decide which platform among the ones that AppConfig supports we are going to use. But remember: only for developing purposes, **not for production** purposes.
To explain more deeply how to use Test DPC to test the MDM in app step-by-step, we'll create a post in [confluence](https://confluence.owncloud.com/) to document it:

- [ ] Create a post in confluence about "How to test MDM in Android app"

### How do we release the app once it is finished?
To be able to release an app with Android Enterprise, we have to join the [Android Enterprise Partner portal](https://www.androidenterprise.dev/s/). The next step is to send the solution for review, so that Google approves it and makes it available from Play Store in work profiles. A summary for the process we have to follow:

![image](https://user-images.githubusercontent.com/57049315/140060608-d0ea1b2f-553b-4cd5-bf6b-4a1c2a0dfe14.png)

### Useful resources
- AppConfig's Android documentation: https://www.appconfig.org/
- Android Enterprise (Android Management API side): https://developers.google.com/android/work/overview
- Android Enterprise (app's side): https://developer.android.com/work/overview
- Android Device Policy app: https://play.google.com/store/apps/details?id=com.google.android.apps.work.clouddpc
- Test DPC app: https://play.google.com/store/apps/details?id=com.afwsamples.testdpc&hl=es_419&gl=US
- Android Enterprise Partner portal: https://www.androidenterprise.dev/s/
- Playlist with Android official tutorials for Android Enterprise (newer): https://www.youtube.com/playlist?list=PLWz5rJ2EKKc-nnQcMIVqAM9_CNmbGu12O
- Playlist with Android official tutorials for Android Enterprise (older): https://www.youtube.com/playlist?list=PLOU2XLYxmsIKAK2Bhv19H2THwF-22O5WX
- GitHub's repository with Android official examples for Android Enterprise: https://github.com/android/enterprise-samples

**Comment by JuancaG05** [comment]
There are four different kinds of profiles for devices managed by MDM. They are classified in function of the ownership of the device and how much control does the company want over it:
- Work profile for employee-owned devices
- Work profile for mixed-used company-owner devices
- Full management for work-only company-owned devices
- Full management for dedicated devices
https://developers.google.com/android/work/overview#android_devices_enterprise_use_cases

I don't know yet if there are technical implications but, should we focus on all of them or only on some?
Android Enterprise support any or all of those options, so I guess whatever is the decision, there will be no problem.

**Comment by JuancaG05** [comment]
To start developing the Android Enterprise solution, we have to integrate the app with [Android Management API](https://developers.google.com/android/management/introduction). This API connects automatically with Android Device Policy app and enforces the management policies it receives on devices. It seems that with Android Management API we can also have a MAM (mobile application management) solution, is it more suitable for the problem we want to solve?

**Comment by michaelstingl** [comment]
> From my point of view, what we're looking for sticks more to a "Work profile" solution.

Then let's target this as a first approach.

**Comment by michaelstingl** [comment]
> I think individuals, in case you refer to the final users (employees)

Individual developers need to register in the portal to access the information

**Comment by fesave** [comment]
A repository that contains a set of individual Android Studio projects to help us get started writing/understanding Android Enterprise features: https://github.com/android/enterprise-samples
