### ISSUE TITLE
Upload Failed, no retry option

### ISSUE THREAD

**Issue by rnveach** [owncloud/android#340]
I am using owncloud android 1.5.2 on android 4.3.1.
When I try to upload a image from the camera using instant upload, or for any upload for that matter, and it fails to upload for whatever reason, there is no option to retry the upload. When you click on the fail notification, it just shows you the name of the file that failed and a dismiss.
There should be an option for retrying the upload that the user can opt to do. This would allow them to retry the upload without having them go and hunt down the file manually.

![screenshot_2013-12-28-11-16-02](https://f.cloud.github.com/assets/5427943/1818071/0cec57b4-6fdd-11e3-8eb2-195477bc8046.png)

**Comment by davivel** [comment]
Sorry, I know we are very late with this one, we'll see it ASAP. I tried to look fast past week but there are tons on changes in that branch.

Let's see if this week is possible. Stay tuned.

**Comment by ole-tange** [comment]
My failing uploads are due to the hotel's wifi having a captive portal: The internet connection only works normally after I entered username and password.

I would be in favour of a menu called 're-sync everything now' that would also take care of the InstantUploads. I imagine that would be fairly easy to do, and making that will make it less critical to get an actual fix for this issue (which seems to be hard given that this bug is more than 18 months old).

**Comment by strugee** [comment]
> I imagine that would be fairly easy to do

It's not. That would require having infrastructure available to determine what had failed, which is what this issue is about. If you're suggesting that we just upload everything, we're talking about many megabytes of data (e.g. my InstantUpload folder is 800+ MB).

**Comment by ole-tange** [comment]
> If you're suggesting that we just upload everything, 

Are you not using some sort of rsync or similar that only transfers changes - no matter what has changed in either end? If not, why not?

**Comment by strugee** [comment]
> If not, why not?

Lack of time, mostly. At least AFAICT; I'm not a core contributor.

**Comment by cmonteroluque** [comment]
@MTRichards we need a prioritization call on this

**Comment by jancborchardt** [comment]
What’s the status here @MTRichards @rperezb? See the comment on the Facebook post of the new version: https://m.facebook.com/story.php?story_fbid=10153118538416359&id=366301826358

**Comment by davivel** [comment]
If I'm not wrong, PR #919 aims to provide retry of uploads (and many other things). #919 is currently scheduled for release 1.8, as shown in https://github.com/owncloud/android/milestones/1.8-current

**Comment by synthead** [comment]
Just got situated with ownCloud.  This is a deal-breaker for me.

**Comment by rperezb** [comment]
Thanks for the call, this is included on the current milestone.

**Comment by synthead** [comment]
When is the current milestone expected to be available? Thanks!

**Comment by jancborchardt** [comment]
@rperezb please add the current milestone here on Github as milestone and assign it to the issues in that milestone. ;)

**Comment by davivel** [comment]
The current milestone is https://github.com/owncloud/android/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.8-current .

**Comment by jancborchardt** [comment]
So is this part of the current milestone then, or not? ;) I don’t see a milestone set on this issue.

**Comment by masensio** [comment]
@jancborchardt, the PR https://github.com/owncloud/android/pull/919 is in the current milestone https://github.com/owncloud/android/milestones/1.8-current.

PR #919 contains the fix for this issue.

**Comment by MTRichards** [comment]
there. I set it now.

**Comment by LukeOwncloud** [comment]
Is here any progress?

I know that it is part of milestone 1.8.1 but I am worried that it might be delayed again. To me a working upload seems much more important than being able to share files.

**Comment by strugee** [comment]
@LukeOwncloud I feel the same, but the ownCloud people have stated that the sharing thing is a paid support contract thing, so it needs to be done soon.

**Comment by davivel** [comment]
With the current schedule there is no way we can have this done for https://github.com/owncloud/android/milestones/1.9-current .

Moving to next release.

cc @rperezb , @MTRichards , @cmonteroluque 


I'm really sorry, @LukeOwncloud . I'd also like the progress of the app was different. Anyway, let's keep some optimism, we'll need it to keep pushing forward in the right way.

**Comment by MTRichards** [comment]
Hey team! As an update, we are hoping to finish the internal sharing for the next release, and then clean up a few bugs and jump on to folder sync and this. The milestone is set for the 1.9.1 release, and the next release will be 1.9.0 in under 10 days. I apologize for the delay, but we are prioritizing this next for review.

**Comment by strugee** [comment]
@MTRichards thanks for the update. It's really nice to hear from you guys once in a while; personally I feel _way_ more engaged with the community that way.

Keep up the great work and good luck with the 1.9.0 release :)

**Comment by davivel** [comment]
I'm really sorry, but this need to be delayed once again.

**Comment by mcronce** [comment]
What do we need to do to make it happen?  Is there more code work that needs to be done?

**Comment by rperezb** [comment]
Thx for your interest @mcronce 
As @davivel has said https://github.com/owncloud/android/pull/919#issuecomment-176660199 we are currently working on it, yes, more core it´s needed, latest changes on the UI and then test it, 

we do appreciate your help testing it. either you may compile the app using the branch: https://github.com/owncloud/android/tree/reliable_uploads_actions_uploads_view
Or perhaps, @tobiasKaminsky may include this on the beta app, once the development is done,  

Thx!

**Comment by tobiasKaminsky** [comment]
Just give me a ping when the developement is ready and I am happy to include it in beta.

**Comment by mcronce** [comment]
@rperezb I'm not much of a tester but I can give it a shot ;) I'd be more helpful writing code if you need a hand on that one

**Comment by tobiasKaminsky** [comment]
@mcronce I think the whole "reliable upload" thing is too much for devs that use their spare time for it.
That is, at least for me, the reason why I did not tried to update @LukeOwncloud branch.

But there are many others open feature requests and bug reports where you can help.
The best way is to choose one issue/bug and discuss it first here on github and then implement it.

**Comment by rperezb** [comment]
@mcronce yes, your willingness is appreciated!
We have a label "contributions are welcome" https://github.com/owncloud/android/issues?q=is%3Aopen+is%3Aissue+label%3A%22contributions+are+welcome%22 please check any of them.
YEs, reliable uploads implies several changes, we are working on it on parts, first part is on the branch: https://github.com/owncloud/android/tree/reliable_uploads_actions_uploads_view we plan to go back to work on this branch after releasing the new version, today!

**Comment by enoch85** [comment]
Now when the "reliable upload" branch is merged, this is an "easy fix" right?

**Comment by davivel** [comment]
@enoch85 , I would even say that it's done :)

Click on error notification now leads to uploads view. There you can tap on any failed upload to retry it. 

:tada:
