### ISSUE TITLE
[BUG]cannot show all picture thumbnails in owncloud android client

### ISSUE THREAD

**Issue by leapyear1969** [owncloud/android#3459]
### Actual behaviour
I have about 18.3GB photo stored in owncloud server.
-I can see all picture thumbnails from web browser.
-i can see all picture thumbnails from IOS client. 
-i CANNOT see all picture thumbnails from Android client

### Expected behaviour
-should see all the thumbnails in android. 
 
### Steps to reproduce
some picture are showing thumbnais, however, the rest of them do not display photo thumbnails. 
If i donwload it from web server, the thumbnais will showing up. and i free up the space from my phone, the thumbnails will living for a few hours, then became the default picture icon.

![som](https://user-images.githubusercontent.com/18607988/143213701-c101d190-641f-4af0-926f-3968edf944b7.jpg)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
No, i tested in the official server, it works well. 

### Environment data
Android version:
Harmony OS

Device model: 
Huawei Mate 20X

Stock or customized system:
Harmony OS

ownCloud app version:
2.19

ownCloud server version:
ownCloud 10.8.0 (stable)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
installed	1
maintenance	
needsDbUpgrade	
version	10.8.0.4
versionstring	10.8.0
edition	Community
productname	ownCloud
hostname	raspberrypi

**Comment by jesmrec** [comment]
Thanks for reporting. 

The point here are the thumbnails for non-downloaded items. The way they work is progressive. You have a folder (or many folders) with a bunch of images. So, when you enter in the folder, the thumbnails of the images in the screen are fetched from the server. Only that ones. Then, when you scroll down, new displayed items in the list ask for the thumbnail to the server at that moment. In this way, we avoid flooding the server with thumbnail requests in case the number of pictures is too big. Sometimes, the thumbnail is not refreshed at the moment in the device screen, but, the next time you scroll to it, it should.

Did you try to scroll up/down to let the thumbnails being refreshed?

**Comment by leapyear1969** [comment]
> Thanks for reporting.
> 
> The point here are the thumbnails for non-downloaded items. The way they work is progressive. You have a folder (or many folders) with a bunch of images. So, when you enter in the folder, the thumbnails of the images in the screen are fetched from the server. Only that ones. Then, when you scroll down, new displayed items in the list ask for the thumbnail to the server at that moment. In this way, we avoid flooding the server with thumbnail requests in case the number of pictures is too big. Sometimes, the thumbnail is not refreshed at the moment in the device screen, but, the next time you scroll to it, it should.
> 
> Did you try to scroll up/down to let the thumbnails being refreshed?

Hi Recio, thank you for your detailed explanation, i tested on my another Android phone with same system version, it works as expected. 
I believe it's a problem with my specfic phone, i'll work on it later if i have time. Thanks for your help again, close with this comment.  :)
