### ISSUE TITLE
Uploading files create an copy in the /owncloud folder of the device

### ISSUE THREAD

**Issue by schiessle** [owncloud/android#346]
If I upload some files from my mobile device to ownCloud than the Android App creates a copy of each files in the /owncloud folder of the mobile device.

This means that if I upload many large files my mobile device can run out of memory. Uploading files to ownCloud should not create a additional local copies of the files. Same is true for images uploaded by the instant upload functionality.

**Comment by drsavoye** [comment]
Has any progress been made on this? I just purchased the ownCloud app and this bug/feature unfortunately makes it unusable for me -- the app itself functions great, but I simply don't have the storage space to keep two copies of everything I upload, and removing the local copy one-by-one is tedious. I think rickatnight11's idea of letting the user choose how to store the data is great.

**Comment by tobiasKaminsky** [comment]
@drsavoye Please see #819 which will solve this problem once it is implemented.
Also, you do not need to delete the local copy one by one. Simply choose a folder in the owncloud app and delete it completely on the device. This will lead to an existing but empty folder on the device.

**Comment by ag14774** [comment]
So what was the conclusion? I am using the latest version and I am still getting the same behavior when doing instant upload. Owncloud is duplicating my files on my phone
