### ISSUE TITLE
include state parameter in oidc call to prevent CSRF

### ISSUE THREAD

**Issue by mortbauer** [owncloud/android#3465]
**oauth2 without state parameter vulnerable to CSRF.**
currently the oauth2 calls do not include the state parameter, therefore it is vulnerable to CSRF attacks
read for example:
*  [RFC6819-4.4.1.8](https://datatracker.ietf.org/doc/html/rfc6819#section-4.4.1.8) 
* [Prevent Attacks and Redirect Users with OAuth 2.0 State Parameters](https://auth0.com/docs/configure/attack-protection/state-parameters)

**ory hydra doesn't even allow state parameters<8 characters**
The reason I found out is that I recently set up [ocis](https://owncloud.dev/ocis) with [ory hydra](https://www.ory.sh/hydra/) as oauth2 provider and it fails because no state parameter is included.

**I think the state parameter should definitely be included**

**Comment by abelgardep** [comment]
Thanks for the contribution @mortbauer, it will be available in the next release 👍

**Comment by mortbauer** [comment]
Great, thank you for owncloud!
