### ISSUE TITLE
The upgrade to scoped storage broke uploading of edited files

### ISSUE THREAD

**Issue by sorenstoutner** [owncloud/android#3472]
After switching to scoped storage (release 2.19.0), when files are edited locally they are not synced back to the server.

Steps to reproduce:

1. Create an OpenDocument file on the ownCloud server.
2. Set the file to be offline in the ownCloud client.
3. Install the Collabora OpenOffice Android app if it isn't already installed.
4. Tap on the OpenDocument file in the ownCloud client.  Select Collabora from the suggested list of apps to open the file.
5. Edit the file and save it.
6. ownCloud will not upload the edits to the server.  Pulling down to refresh also does not initiate a transfer.
7. Opening the file again shows that the edits were saved, indicating that the updated file exists locally.

This functionality used to work with prior versions of ownCloud, and there is nothing inherent in scoped storage and the Storage Access Framework that should prevent this from working now.  Rather, it probably represents an unintended bug introduced in the refactoring of the code for scoped storage that now no longer checks for uploading modified files.

**Comment by abelgardep** [comment]
Previously it worked, but not the intended way, not using the SAF.

The behavior of opening a file in the ownCloud app is only for VIEW. This is something that we have in our scope and we want to modify it to enable editing.

We can use Collabora to edit the files but using the Documents Provider. This means that we need to open the file within the Collabora app.

1. Open Collabora app
2. Click top-right icon to open the file selector
3. Select ownCloud in the drawer menu
4. Browse and select the file we want to edit
5. Edit the file and save

File will be uploaded to our cloud as expected.

**Comment by sorenstoutner** [comment]
Thanks for the workaround.  I can confirm it does work.

**Comment by abelgardep** [comment]
I have added a new issue to track this new feature: https://github.com/owncloud/android/issues/3475
