### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by mstojanovic** [owncloud/android#3488]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
when i select a file to share from the android app i want a manager to pop out to ask me with which app i want to share the file.

**Describe alternatives you've considered**
all major cloud providers support the above feature, e.g. 'send as copy' on gdrive

**Additional context**
i want to share a picture from my owncloud with a friend on signal/telegram. i want the option to choose the app i want that file to be sent with. now i can only provide a link

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
Long-press the file to select, then tab the vertical-three-dot-menu on the top-right. There you can choose "Send" to use the file in 3rd party apps.

**Comment by mstojanovic** [comment]
ty for the info
