### ISSUE TITLE
[FEATURE REQUEST] desktop shortcut / file link to offline available files

### ISSUE THREAD

**Issue by MartinEderAT** [owncloud/android#3489]
**Is your feature request related to a problem? Please describe.**
To open offline available files at the moment you have to open the owncloud app and open the file via the owncloud app. If the file is quite deep in the foler structure, it takes some time to open the file. I am using Keepass on my owncloud server, and it is not possible to open the offline avalaible KeePass Datenbase file quickly through the owncloud app. 

**Describe the solution you'd like**
A shortcut / file/folder link on the android desktop (like total commander can provide it to every file on your android) to offline available files from the owncloud app

**Describe alternatives you've considered**
Offline avalaible files are visible in the download folder of android (which is for many other users a security issue)

**Additional context**

**Comment by abelgardep** [comment]
Thanks for opening a new feature request!

At the moment, we have a shortcut for av. Offline files in the bottom navigation bar. You can access av. Offline and shared files pretty easily with those tabs.

Please help me to understand your needs. I think I'm missing something. 🤔

**Comment by jesmrec** [comment]
Available offline shortcuts already exist. Please, feel free to reopen if any other issue about it has to be commented.
