### ISSUE TITLE
Automatic retry of instant uploads captured while offline when appropriate network is recovered

### ISSUE THREAD

**Issue by a-schild** [owncloud/android#349]
Hello,

ownCloud client 1.5.2 on KitKat

When I have setup the ownlocud client to do a instant upload, but only when on WIFI,
this works fine so long I'm on wifi when taking the picture(s).

When I am out of any wifi connection and take fotos, then I expect the instant upload to start as soon as I have a wifi connection.

Currently these fotos are never uploaded to the owncloud server

**Comment by tobiasKaminsky** [comment]
This is working for me.
Please, somebody also verify that it is working, then we can close the issue.

**Comment by davivel** [comment]
This is currently working (with some bugs), but will have an overall review (hopefull soon) after the uploads view is released (almost there). Let's keep it open to track it.

**Comment by davigonz** [comment]
This is being currently addressed on **new Camera uploads feature**, which is going to replace the previous Instant uploads feature, follow up: https://github.com/owncloud/android/issues/2028

**Comment by davigonz** [comment]
This feature is already implemented and working as expected in new **Camera uploads** feature, which will be included in 2.6.1 release, so I think that we can close this issue

CC @jesmrec
