### ISSUE TITLE
[FEATURE REQUEST] add folders not only files to upload to the owncloud server

### ISSUE THREAD

**Issue by MartinEderAT** [owncloud/android#3490]
**Is your feature request related to a problem? Please describe.**
At the moment only files can be uploaded / added by the owncloud app to the server

**Describe the solution you'd like**
Not only files also folders can be selected to be uploaded to the server

**Describe alternatives you've considered**
The recent alternative is to mark several files to upload them. If you have f.e. a photo folder with more than 50 photos the current solution ist quite unconfortable.

**Comment by abelgardep** [comment]
Hi! Thanks for opening a new feature request!

We will take it into account, it could make sense to allow the folder selection.

Anyway, the current workaround is not that long, just need to long-press within the folder, and use the `select all` option. It's not that straightforward but it does the job too.

**Comment by jesmrec** [comment]
Duplicated -> https://github.com/owncloud/android/issues/645
