### ISSUE TITLE
[FEATURE REQUEST] Enable "Send" functionality for file multiselect as well

### ISSUE THREAD

**Issue by Slackliner** [owncloud/android#3491]
**Is your feature request related to a problem? Please describe.**
I manage more and more pictures on my owncloud and share them with my family. In order to reduce management of duplicate data I delete the pictures locally on my phone after they were move to the cloud. However, when I want to share a couple of pictures or files via Email or Messenger (Threema, Signal, Whatsapp...) on my phone I have to single select them and then share via the "send" functionality in the "three dot" menu. It is quite frustrating that the "Send" disappears when selecting more than one file. 

**Describe the solution you'd like**
Have the "send" functionality also available when multiple files are selected. 

**Describe alternatives you've considered**
Accessing my owncloud via the file manager doesn't give me a proper thumbnail/preview (at least in a reasonable time) and I am not aware of a method to make data available offline via the file manager.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App #3638 
- Library (if needed)

**Comment by abelgardep** [comment]
Hi, thanks for opening a new feature request!

You are absolutely right! It's kind of tedious to share several files at the moment. The only way to do it is via Documents Provider and I think that sending multiple files within the app would be a good addition.

We will check it. Anyway, contributions are welcome!
