### ISSUE TITLE
[BUG] Available offline has no files

### ISSUE THREAD

**Issue by logbaseaofn** [owncloud/android#3506]
### Actual behaviour
- I upload a photo from my phone, and I expect it to appear in the list of available offline files.

### Expected behaviour
- There are no items in the available offline tab. 
 
### Steps to reproduce
1. Upload a photo from your phone
2. Observe the "available offline" checkbox next to the item
3. Click on the available offline tab
4. Observe no items in that list. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 12

Device model: Samsung S20+ 5G

Stock or customized system: Stock

ownCloud app version: 2.19

ownCloud server version: 10.8.0

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

Don't have my logs available at the moment. Will append with I get the chance (ping me if I haven't).

**Comment by abelgardep** [comment]
Hi @logbaseaofn, thanks for opening an issue.

When you upload a photo, a green icon is shown next to the thumbnail, right? That green icon means that the photo is "Downloaded" - so yeah, it's available and you can open it without connection when you are offline, or the server is under maintenance, and so on.

But the "Available offline" concept is a little bit more powerful. You can set a file as "Available offline" by long-pressing a file, clicking on the 3-dot menu, and using the "Set as available offline" option. With that, the file will be synced automatically with the server periodically. So you will likely have the latest version on your device. It is useful when you have key files that you want to keep synced automatically.

Once you set a file as Available Offline, it should appear in the Available Offline tab. Let me know if that solves the issue 👍

**Comment by logbaseaofn** [comment]
@abelgardep Oh wow, I had no idea there was a difference. This worked great. Closing!
