### ISSUE TITLE
[FEATURE REQUEST] "Open with" downloading files

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3507]
Check the following steps out:

1. Open the account
2. Open actions menu of any file

Current:

`Open with` action is not available unless the file is already dowloaded

Expected:

As well as the `Send` option, or the `Open In` option in the iOS app, if the file is not downloaded, the `Open with` action should download it before opening with the 3rd party app.

**Comment by abelgardep** [comment]
Open with is not available in the 3-dot menu, that's true.

But it is there in an implicit way. When you click on any file, it is supposed to be opened. And it does. It downloads the file and then we try to show it to the user. If we can not, it automatically triggers an open with.

**Comment by jesmrec** [comment]
> Open with is not available in the 3-dot menu, that's true.
> 
> But it is there in an implicit way. When you click on any file, it is supposed to be opened. And it does. It downloads the file and then we try to show it to the user. If we can not, it automatically triggers an open with.

if the file is not "openable", `Open with` is triggered, right.

But, if the file is openable, there is no way to "Open with" without downloading. This is not dramatic, for sure, but could be confusing because not having downloaded file is not a condition to prevent "open with", imho.

Tiny improvement.
