### ISSUE TITLE
[BUG] Switching users in OAuth2 auth flow ends with unsuccessful authorization

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3509]
### Steps to reproduce
1. Open OAuth2 server session
2. Open drawer -> manage accounts 
3. Click on the key icon to edit the account auth info
4. `Log In` to start web authorization
5. Select `Switch users`
6. Enter correct credentials (same account as 1.)
7. `Authorize`

### Actual behaviour
`Unsuccessful authorization`

https://user-images.githubusercontent.com/14894746/150169682-2b535673-37ae-44d3-9789-abb5f04b7bae.mp4

Error is a 400 after requesting `POST http://192.168.1.20:39000/index.php/apps/oauth2/api/v1/token`:

```
{
    "error": "invalid_grant",
    "error_description": "code verifier invalid"
}
```

### Expected behaviour
As the correct credentials, file list should be displayed instead of error

Nexus 6P Android7
Pixel2 Android11
HuaweiP20L Android9

**Comment by michaelstingl** [comment]
Known limitation, after oC10 OAuth 2.0 app learned PKCE with 5.0. See https://github.com/owncloud/oauth2/issues/309

**Comment by jesmrec** [comment]
Expected behaviour then. Reopen if behaviour changes.
