### ISSUE TITLE
[BUG] Thumbnails in grid view

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3525]
Comes from https://central.owncloud.org/t/androip-app-2-19-shows-photos-not-correct/36067

### Steps to reproduce
1. Upload more than 5-10 photos
2. Try to view

### Actual behaviour
Only some photos are displayed, not the whole grid. Not always the same number.

### Expected behaviour
The whole grid is full of image previews

Reproducible with Pixel2 Android11

**Comment by Warlock667** [comment]
Same here.
Please note, that the missing preview both happens with pictures that are only the server and pictures that have already been downloaded to the smartphone

ownCloud for Android 2.19
ownCloud Server 10.9.0
Android 11 (Oxygen OS 11.0.5.1.GM57BA)
Oneplus 7 (GM1903)

![oc](https://user-images.githubusercontent.com/52013314/151433828-77369c13-af90-4556-a444-2d75cbe648c1.jpg)

**Comment by Sacerdoss** [comment]
Same here. App is pretty much unusable for Image folders rn. One currently has to download all images and use a external gallery. App will eventually generate/load thumbnails if you keep entering and leaving the folder. 
Would love to see this bug getting fixed so thumbnails will load dynamically after entering a folder.

**Comment by aleksandrpro** [comment]
Same here.
Thumbnails are not dynamically loaded if folder is open. App shows some images after refresh (those for which thumbnails requested from server before), but images at the end of folder are never shown.

This is not grid view problem, list view also affected.

**Comment by jesmrec** [comment]
we'll post here as soon as we have news about this.

**Comment by abelgardep** [comment]
Should be fixed within 3.0 release. Feel free to reopen it if still reproducible 👍

**Comment by benedictgoodman5** [comment]
I still have the same issue in version 4.3.1. It's almost random which image previews are displayed, although it's usually blocks of images, and they don't come back once they've disappeared. No problem with previews (image and movies) on the server. Is it possible to re-open this?
