### ISSUE TITLE
Logging is disabled by default during debug

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3526]
What's the point to enable debug logging only on manual action in settings ?
In earlier days, this was done by default

![image](https://user-images.githubusercontent.com/3314607/151501936-a071f9bc-799e-45a9-8d0c-732692f6ac9e.png)

**Comment by hannesa2** [comment]
Isn't it smarter to do it that way ?

<img width="819" alt="image" src="https://user-images.githubusercontent.com/3314607/151502269-3be004f4-1cb2-478b-bc20-26c20cfb85fe.png">

**Comment by abelgardep** [comment]
We modified it some time ago to allow enable/disable which was not possible.

Anyway, we can introduce a flag to make lt start logging by default if we are on DEBUG. Sounds good to me.
