### ISSUE TITLE
[BUG] MissingQuantity for French

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#3534]
I tried Android BumbleBee and run into this
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/3314607/151753891-f3da1682-8b6b-496a-be8d-0e2a00c5a149.png">

Translation fixes should be done by someone else

**Comment by hannesa2** [comment]
I've no clue what's wrong here 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/3314607/151754430-53be1595-7c7e-4c49-b173-dd19e869aa27.png">

**Comment by jesmrec** [comment]
Documentation about this: https://developer.android.com/guide/topics/resources/string-resource.html#Plurals

```
many When the language requires special treatment of "large" numbers (as with numbers ending 11-99 in Maltese).

other When the language does not require special treatment of the given quantity (as with all numbers in Chinese, or 42 in English).
```

checking how the french language works in this regard, there is no special treatment for numbers beyond the singular and plural. In order not to break existing translations, the optimal fix is adding the missing `many` entry, that will match the existing `other`. Sending PR...

**Comment by jesmrec** [comment]
Done! thanks for reporting!
