### ISSUE TITLE
[BUG] - Auto Upload of videos 

### ISSUE THREAD

**Issue by brunofcat** [owncloud/android#3579]
Hi,

The auto upload of videos not work correctly on my device.
After take a vídeo, the owcloud detect the vídeo, put on the pull but not load the video.
For pictures works.

![Screenshot_2022-03-10-21-48-03-401_com owncloud android](https://user-images.githubusercontent.com/9000957/157760289-dfbb6f4d-4e81-4a0f-87ec-7208c17bf466.jpg)

The progress bar not move.
If I drop and add manualy, works.
I'm using the same destination for pictures and movies.

Android app version:
2.20

Server version:
10.9.0/10.9.1(I updated today and still with the same issue)

Device:
Poco F3

Os version:
MiUi Global 12.5.8 (Android 11)

**Comment by fesave** [comment]
Hi @brunofcat! Thank you very much for reporting this problem, we will work on it and give you an answer as soon as possible. Stay tuned for updates! have a nice day and take care 😉

**Comment by jesmrec** [comment]
@brunofcat could you post a screenshot of the "Auto upload videos" screen into `Settings`? just to know your setup  to try to reproduce. With a single auto upload, it worked for me. If you can get logs, it'd be also very useful. Thanks a lot!

**Comment by brunofcat** [comment]
Hi @jesmrec,

![Screenshot_2022-03-16-19-42-10-393_com owncloud android](https://user-images.githubusercontent.com/9000957/158676706-16700415-a8fe-48b5-8df5-1511d0edb433.jpg)
![Screenshot_2022-03-16-19-42-22-928_com owncloud android](https://user-images.githubusercontent.com/9000957/158676713-3c04791a-db01-4408-8910-f94f8ae3bcb8.jpg)
[owncloud.2022-03-15.log](https://github.com/owncloud/android/files/8270593/owncloud.2022-03-15.log)

**Comment by brunofcat** [comment]
In the my last commet I sad "Small vídeos are Uploaded" I think only happens before a big video.

**Comment by brunofcat** [comment]
Hi,

I changed the hardware and now it appears to be working properly.
