### ISSUE TITLE
Feature Request: 'fork' for connection data

### ISSUE THREAD

**Issue by lebochequirit** [owncloud/android#358]
I thought about that for a while and have seen it now in the tt-rss app available on f-droid:

The happ has "normal" connection data - let's say via https://owncloud.mydomain.tld

And for a certain Wifi connection (identified by SSID and one or more MACs) I have another connection via https://192.168.xxx.yyy.

The idea is not to route data via internet while I'm at home and can connect via LAN.

**Comment by zatricky** [comment]
@michaelstingl Please put a reason for it being closed - for example inactivity/implemented/duplicate/wontfix/etc
Thank you

**Comment by michaelstingl** [comment]
@zatricky Thanks for asking. I don't see a realistic chance to get this implemented from the ownCloud team in the near or mid-future. In case of a contribution, we can always re-open it. Nobody contributed to it in the last years and there are also no bounties for it:
https://www.bountysource.com/issues/1386463-feature-request-fork-for-connection-data

Please also check my comment about `dnsmasq` : https://github.com/owncloud/client/issues/203#issuecomment-408426284
