### ISSUE TITLE
Android app fails to connect to TLSv1.1 or TLSv1.2 based servers

### ISSUE THREAD

**Issue by deveth0** [owncloud/android#362]
I currently use an nginx based owncloud server which is restricted to TLS 1.1 and 1.2. The android app can't connect to a server like this but complains with "SSL initialization failed".

TLS 1.1 and 1.2 are supported in (at least) all android versions >4.1.

**Comment by TheGrave** [comment]
Actually, TLSv1.2 cipher suites (e.g. those with either SHA256 or SHA384) are supported from API level 20 onwards (Android 4.4) so do not expect to get a TLSv1.2 connection on an earlier OS. Just confirmed with Android 4.2.
