### ISSUE TITLE
Managed-Configs

### ISSUE THREAD

**Issue by Zusel** [owncloud/android#3621]
Hey,
Is it possible to add a managed-config for Android-Enterprise? Not many configurations are needed. Username, server url and (optional) password.
Is it possible to do this?

Thanks

**Comment by michaelstingl** [comment]
Team is working on it. Her you can find some related issues:
https://github.com/owncloud/android/issues?q=is%3Aissue+MDM+in%3Atitle+

**Comment by jesmrec** [comment]
Here you have the last version of the (not-merged-yet) restrictions file:

https://github.com/owncloud/android/blob/feature/mdm/owncloudApp/src/main/res/xml/managed_configurations.xml

Next one -> https://github.com/owncloud/android/issues/3596

**Comment by Zusel** [comment]
Hey,
yes that looks great. But I think a username is needed.
The password is in most cases not known to the administrators.

**Comment by michaelstingl** [comment]
> But I think a username is needed.

Low priority, because SSO is used in professional environments. There we use the web UI to login to your ownCloud. (OAuth 2.0 & OpenID Connect)

**Comment by jesmrec** [comment]
Feature done and merged. New features and parameters will be included in the future for a complete support.

PD: Not available in GooglePlay, needed Android Enterprise suscription after building MDM variant
