### ISSUE TITLE
Does Android app rely on .ocs.data.version from the capabilities?

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#3623]
@abelgardep @jesmrec could you check if this is used?

```
% curl 'https://demo.owncloud.org/ocs/v1.php/cloud/capabilities?format=json' \
  -u demo:demo | jq '.ocs.data.version'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2117  100  2117    0     0   9974      0 --:--:-- --:--:-- --:--:-- 10377
{
  "major": 10,
  "minor": 9,
  "micro": 1,
  "string": "10.9.1",
  "edition": "Community"
}
```

(not the `status.php`)

What is expected? What would happen if it changes to this this? https://github.com/owncloud/ocis/pull/2918#issuecomment-1004744700

**Comment by michaelstingl** [comment]
> I'd say we are not using such capability. To check versions, we are using the code itself, like:

But we check version only from `status.php`, not from the capabilities endpoint?

**Comment by jesmrec** [comment]
Yes, because capabilities request is authenticated. Login view checks URL version against `status.php`.

**Comment by abelgardep** [comment]
Exactly what @jesmrec said. We use the version in `status.php` to verify that the server version is newer than 10.

Also, we use the capabilities version to verify that the already logged account is from a supported server.

**Comment by jesmrec** [comment]
`status.php` keep in ocis server with backwards compatibility. Related: https://github.com/owncloud/android/issues/3671
