### ISSUE TITLE
[MDM] Prevent taking screenshots

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3625]
Create new MDM parameter as `allow_screenshots` in https://github.com/owncloud/android/issues/3596

Type: boolean
name: allow_screenshots_configuration
defaultValue: true

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
Merged, will be available as soon as #3419 is merged
