### ISSUE TITLE
[FEATURE REQUEST] Prevent taking screenshots in Dialogs (Android 12)

### ISSUE THREAD

**Issue by davcres** [owncloud/android#3637]
In #3615 the screenshots was prevented, but in Android 12 if you take a screenshot of a dialog, it will be taken.

The idea is to prevent the screenshots also in dialogs for Android 12. In Android 11 or below there is no problem, it doesn´t allow to take screenshots if the flag `allow_screenshots`is set to false.

||| 
|:-|:-:|
|![Screenshot_20220412-170534](https://user-images.githubusercontent.com/14894746/162994686-9699b158-bd6c-474e-89e0-150ae5321c75.png)|![Screenshot_20220412-170423](https://user-images.githubusercontent.com/14894746/162994713-62c9bae1-76fe-4ccc-a014-6d8450cfdc74.png)|

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Could be a solution to prevent this dialog specifically? as well as the passcode, pattern or login view? Only for Android 12

**Comment by davcres** [comment]
`dialog.window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)` works to prevent screenshots in the dialogs.
There are too many, maybe we can do a dialog to inherit from it with the option.
