### ISSUE TITLE
[BUG] Incorrectly invoking exported Activity crashes the app

### ISSUE THREAD

**Issue by C0rby** [owncloud/android#3673]
When starting an exported activity incorrectly the Android app will crash.
E.g. using adb `adb shell am start -n com.owncloud.android/.ui.activity.ReceiveExternalFilesActivity`
If a malicious app would be doing that in a loop it would prevent the user from using the app.

Can this somehow be prevented?

**Comment by jesmrec** [comment]
I can't reproduce the crash with such command. Were you able to reproduce it? it's the only thing we could do... check why it crashes and try to fix it.

**Comment by C0rby** [comment]
Huh, you're right... it doesn't really crash. When I tried it yesterday, it would end up at the Android dialog "ownCloud App stopped working" but I can't reproduce it anymore...

**Comment by jesmrec** [comment]
should we close this?

**Comment by C0rby** [comment]
Sure. I'll open it again if I manage to reproduce it again.
