### ISSUE TITLE
[BUG] - No longer able to connect to my local server via wi-fi

### ISSUE THREAD

**Issue by brunofcat** [owncloud/android#3674]
Hi,

### Actual behavior
With the new version of the application (2.21-beta.1), I am no longer able to connect to my local server via wi-fi. Via mobile network works.

### Expected behavior
The previous version works fine both ways.
 
### Steps to reproduce
1. Run a NAS in your local network (home); 
2. On your mobile device (Android with owncloud version 2.21-beta.1) create a new connection.

Can this problem be reproduced with the official owncloud server? No
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
ownCloud app version:
2.21-beta.1

ownCloud server version:
10.9.1.2

### Logs
[owncloud.2022-05-23.log](https://github.com/owncloud/android/files/8764119/owncloud.2022-05-23.log)

**Comment by jesmrec** [comment]
First of all, thanks for checking the beta. It's really appreciated.

Unfortunately, i can't reproduce the problem locally. Also, you don't reproduce the problem with the test instance. Checking the logs, problem is like `isConnected failed: EHOSTUNREACH (No route to host)`. Could it be a problem to access to the server inside the network (ports banned or something similar)? the app's network library is able to connect a reachable URL, no matter if it runs under wifi or mobile network.

We can do another try, checking connection to your server. Could you provide a test account? if you want to, please, address it to `android-app@owncloud.com`

**Comment by brunofcat** [comment]
Hi Jesús,

From external network is working and my wife has the previous version and works.

I've been looking at the error file, and now, I think it's an IPv6 request forwarding problem within my network.
the previous version of the app possibly uses IPv4.

I will look for my rooter to check if I can find the cat :)

**Comment by brunofcat** [comment]
I was able to understand and solve the problem.

My DDNS provider (dynu.com) did not have the correct IPv6 value. I set the IPv6 address of my NAS and it started working correctly.

I did an extra test to understand why it works over the external network (mobile network) (I stopped my apache server).
![image](https://user-images.githubusercontent.com/9000957/170252653-053191f9-c63f-4fa5-b9f0-0549d67d28a0.png)

 Probably the application uses different libraries according to the connection type, wifi vs mobile network, for the mobile network is using IPv4 and for wifi is using IPv6.

Probably the previous version uses IPv4 in both scenarios and for that reason only i was having connection failure when connected by wifi.

Will this make sense?

**Comment by jesmrec** [comment]
Makes sense, handling IPv4 at the moment.

**Comment by brunofcat** [comment]
Thanks,

**Comment by jesmrec** [comment]
thanks to you for your engagement.
