### ISSUE TITLE
[New arch]  Folder Synchronization

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3707]
Sync the folder's content recursively.

Base case: click on the circle arrow over a folder.
Other case: If file is downloaded/av,offline (also folder), a sync is triggered to assure local changes are pushed to the server.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App #3714 
- Library (if needed)

**Comment by abelgardep** [comment]
Will be tested within https://github.com/owncloud/android/issues/2818
