### ISSUE TITLE
F-droid version

### ISSUE THREAD

**Issue by wzv** [owncloud/android#373]
The version on f-droid repo is still 1.5.2. Is there a reason ? On play store it's 1.5.3.

**Comment by LukeOwncloud** [comment]
Just a reminder for the future:

Releases need to be added manually to F-Droid: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.owncloud.android.txt (just issue a pull request)

Automatic builds are not possible/wanted, refer to discussion: https://gitlab.com/fdroid/fdroiddata/merge_requests/1366
