### ISSUE TITLE
redirect_uri error with keycloak 18 IDP on android

### ISSUE THREAD

**Issue by thommierother** [owncloud/android#3734]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Keycloak 18 changed the handling of redirects, see:

- https://github.com/mauriciovigolo/keycloak-angular/issues/396
- https://www.keycloak.org/2022/04/keycloak-1800-released (> OpenID Connect Logout)

In the android mobile client this leads to an error with "invalid parameter: redirect_uri" when the client is doing the OAuth redirection to the IDP. While there is a workaround for backwards compatibility of the keycloak IDP server (see the github link and the release notes) this should be reflected somehow in the desktop app.

### Expected behavior

compatibility with keycloak 18 IDP

### Steps to reproduce the issue

- OC 10.10 server
- Keycloak 18 quarkus IDP
- latest Android client

### Client version number

android client 2.21.1

**Comment by michaelstingl** [comment]
> Note: I am posting this issue for the client and not only for android as this change on the IDP side may affect the clients behaviour in general

I moved the issue to the Android repo, and we can create additional issues in the individual repos.

**Comment by thommierother** [comment]
I dont' know how other IDPs handle this.

We should at least add a note to any docs concerning keycloak as IDP with the info about the current workaround (backwads comp. switch for KC 18).

**Comment by abelgardep** [comment]
Not sure how could it affect the Android App when the OIDC logout is not implemented yet.

We send the `redirect_uri` in the authentication request and [it is required](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).

**Comment by thommierother** [comment]
I think this is a misunderstanding. redirect_uri is not removed generally, but the behaviour for special logout use cases has changed, in favor of the support of "OpenID Connect RP-Initiated Logout", see https://openid.net/specs/openid-connect-rpinitiated-1_0.html:

> The new version has better support for logout based on the OpenID Connect RP-Initiated Logout specification. The parameter redirect_uri is no longer supported; also, in the new version, the user needs to confirm the logout. It is possible to omit the confirmation and do automatic redirect to the application when you include parameter post_logout_redirect_uri together with the parameter id_token_hint with the ID Token used for login

My problem with the keycloak redirect presumably comes form an open misconfiguration on my side ;-(  Aside from this, I don't know if the change in KC 18 affects the OC clients somehow, maybe one of the OIDC gurus can comment on this ....

**Comment by thommierother** [comment]
I would suggest to change the label from "bug" to "info"

**Comment by michaelstingl** [comment]
ownCloud desktop and mobile apps didn't implement any OICD-logout features yet, so the Keycloak change doesn't cause problems.

**Comment by thommierother** [comment]
ok, in this case we can close this
