### ISSUE TITLE
App forgets login data

### ISSUE THREAD

**Issue by mdimjasevic** [owncloud/android#374]
### Expected behaviour
I expect the login data/credentials to be stored in the app so that every time I start the app, I can simply use the app.

### Actual behaviour
Login credentials get forgotten and I need to re-enter them once the app is started again (i.e. when the app is not running on Android).

I've also noticed this happening with an older version of the app (about a year ago) with ownCloud server version 4.

Another user reported the same issue at an ownCloud forum: http://forum.owncloud.org/viewtopic.php?f=24&t=19283

### Steps to reproduce
1. Install the app, start it, enter login data, use the app
2. Reboot the device the app is installed on
3. Start the app and observe the login credentials have been forgotten 

### Environment data
Android version: 2.3.7

Device model: HTC Desire

Stock or customized system: CyanogenMod 7.2

ownCloud app version: 1.5.2

ownCloud server version: 6.0.1

#### Web server error log

2014/02/01 09:29:17 [error] 2303#0: *1141 access forbidden by rule, client: SERVER_IP, server: cloud.example.org, request: "GET /data/htaccesstest.txt HTTP/1.0", host: "cloud.example.org"
2014/02/01 09:30:04 [error] 2301#0: *1168 access forbidden by rule, client: SERVER_IP, server: cloud.example.org, request: "GET /data/htaccesstest.txt HTTP/1.0", host: "cloud.example.org"

#### ownCloud log (data/owncloud.log)

{"app":"OCP\\Share","message":"Sharing backend OCA\\Contacts\\Share\\Addressbook not registered, OCA\\Contacts\\Share\\Addressbook is already registered for addressbook","level":2,"time":"2014-02-01T17:31:47+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OCA\\Contacts\\Share\\Addressbook not registered, OCA\\Contacts\\Share\\Addressbook is already registered for addressbook","level":2,"time":"2014-02-01T17:31:48+00:00"}
{"app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone (\/freeassociation.sourceforge.net\/Tzfile\/America\/Denver) at \/var\/www\/owncloud\/3rdparty\/Sabre\/VObject\/TimeZoneUtil.php#307","level":3,"time":"2014-02-01T17:31:48+00:00"}
{"app":"OCP\\Share","message":"Sharing backend OCA\\Contacts\\Share\\Addressbook not registered, OCA\\Contacts\\Share\\Addressbook is already registered for addressbook","level":2,"time":"2014-02-01T17:31:49+00:00"}

**Comment by davivel** [comment]
@jancborchardt , there is no sure way to know if the workaround app is needed or not. Google fixed it in version 4.2, but manufacturers with their own modifications do not show a clear pattern in versions. Some Samsung devices with 4.3 still have the issue, some Samsung devices with 4.2 do not.

There's no easy way either to check programatically if the problem exists or not.

**Comment by davivel** [comment]
@mdimjasevic , is this still a problem for you. Do you continue using your Android 2,x device?

Thanks in advance.

**Comment by mdimjasevic** [comment]
On Mon, 2015-01-26 at 06:25 -0800, David A. Velasco wrote:
> @mdimjasevic , is this still a problem for you. Do you continue using
> your Android 2,x device?

Yes, and the issue is still there.

**Comment by davivel** [comment]
OK, Unfortunately, we are not supporting Android 2.x anymore. Unless any volunteer wants to deal with it, it won't be fixed.

My apologies,

**Comment by tobiasKaminsky** [comment]
Closing as android 2.x is not supported any longer.
