### ISSUE TITLE
InstantUpload files duplicated in ownCloud folder

### ISSUE THREAD

**Issue by codeling** [owncloud/android#375]
After enabling the InstantUpload feature, all photo files seem to be duplicated by the client - they exist once in their original location in the DCIM folder, and once in the /owncloud/user@ochost/(Instant|Sofort)Upload folder.
This seems redundant to me - I don't see any use in having those duplicate files? The only thing I can think of which such a copy could achieve would be marking which files are successfully uploaded? But there surely is a simpler way of doing that than to just copy the file? Maybe store a file with the same name as the image plus e.g. .hash suffix, containing a hash of the uploaded file?
Those copies just wastes a lot of space on my (non-extensible) internal storage.

Using the latest version available in Market (1.4.3).
Server version is 6.0.1 (but is going on since 5.0.13 at least).

**Comment by Bugsbane** [comment]
Might be helped by pull https://github.com/owncloud/android/issues/346 Not sure.

**Comment by Bugsbane** [comment]
Might be helped by pull https://github.com/owncloud/android/pull/919 Not sure.
