### ISSUE TITLE
[BUG] Can't download any file

### ISSUE THREAD

**Issue by danbowkley** [owncloud/android#3751]
### Actual behaviour
Says file is downloaded, but the file does not exist on the device's filesystem. I have to share the file to my Google Drive and then download it from there to be able to use the file in any other app.

### Expected behaviour
File is downloaded to device and can be accessed with other apps. I shouldn't need to use my other cloud service to download a file from this cloud service.
 
### Steps to reproduce
1.  download any file
2.  try to find it using any other app
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test) I don't know; there are no files already there to download and it gives me a connection error when I try to upload something to test it with.

### Environment data
Android version: 12

Device model: Oneplus IN2017, SW ver IN2017_11_C.41

Stock or customized system: bone stock except ADW. not rooted.

ownCloud app version: 2.21.1 (53e4dee38)

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Google forces apps to use Scoped Storage to save data. It's a matter of security and confidentially. 

To open ownCloud files in another apps:

- Use the `Open with` option, available for every file. If you modify the file with the external app, modification will be synced by browsing in the file containing's folder.

- Document provider: Apps that implement document provider have access to all files in the oC account. For example, some file explorers like [Files](https://play.google.com/store/apps/details?id=com.marc.files&hl=en) gives access to all files in the app. 

Just to be clear, these are platform restrictions, not our restrictions. You can find more info about Scoped Storage in [this forum topic](https://central.owncloud.org/t/owncloud-2-19-for-android/34952)

**Comment by jesmrec** [comment]
Please, keep tunned for new features that could be included in future releases. No much stuff to do at this moment.

Closing... feel free to reopen if any other issue about this topic should be discussed.
