### ISSUE TITLE
[FEATURE REQUEST] fallback to static client id when OIDC DCR fails

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#3755]
**Is your feature request related to a problem? Please describe.**

Insights from @micbar

> I see no possible way to deactivate "Dynamic Client registration" (DCR) on Keycloak. So it seems we always have the registration endpoint available. Keycloak has policies, which clients, origins and redirect urls it accepts. So it is very likely that the registration request can fail.

**Describe the solution you'd like**

The client should be graceful when the registration attempt fails and try to connect with the public client ID

**Additional context**

iOS implementation:
- https://github.com/owncloud/ios-app/issues/1006
- https://github.com/owncloud/ios-app/pull/1068

Desktop client issue:
- https://github.com/owncloud/client/issues/10097

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
It is already done in the Android App since [2.17](https://github.com/owncloud/android/blob/master/CHANGELOG.md#217-march-2021)

When registration fails, we try to authenticate with the public client id 

https://github.com/owncloud/android/blob/master/owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt#L432

**Comment by michaelstingl** [comment]
> It is already done in the Android App since [2.17](https://github.com/owncloud/android/blob/master/CHANGELOG.md#217-march-2021)
> 
> When registration fails, we try to authenticate with the public client id

Perfect, then it's only missing in the desktop. 👍
