### ISSUE TITLE
[BUG] - The picture preview not load

### ISSUE THREAD

**Issue by brunofcat** [owncloud/android#3758]
### Actual behaviour
Hi, the picture preview (at least in grid mode) does not load, I need to interact with the app to be able to see the downloaded thumbnails.

### Expected behaviour
Progressive thumbnail rendering without interaction of my side.
 
### Steps to reproduce
1. On the device, sync the pictures and change the view mode to grid;
2. Via browser, delete the pictures;
3. On the device, pull to refresh (to clean);
4. Via browser, upload new pictures;
5. On the device, pull to refresh;

Can this problem be reproduced with the official owncloud server?
yes

### Environment data
Android version: MIUI Global 13.0.7 (Android base: 12 SKQ1.211006.001)

Device model: POCO F3

ownCloud app version: 2.21.2

ownCloud server version: 10.10.0

https://user-images.githubusercontent.com/9000957/190467990-e7fa1318-fd67-418b-8487-d82fe5be6d15.mp4

**Comment by jesmrec** [comment]
3.0 should fix this one.

**Comment by brunofcat** [comment]
Ok, thanks 👍
