### ISSUE TITLE
[FEATURE REQUEST] Webfinger

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3759]
Some documentation about this

https://github.com/owncloud/lookup-webfinger-sciebo
https://datatracker.ietf.org/doc/html/rfc7033
[iOS_flow.zip](https://github.com/owncloud/android/files/9581460/iOS_flow.zip)

Enterprise issue: https://github.com/owncloud/enterprise/issues/5021

Basically, after opening the app the webfinger url is checked, then username enter and server returns the server URL to work with.

Needed a new branding option, called `<webfinger_url>` or similar. If the parameter is empty, webfinger ignored, otherwise, webfinger starts its flow.

**1. Initial point.**

App looks like:

<img width="287" alt="Screenshot 2022-09-16 at 09 01 36" src="https://user-images.githubusercontent.com/14894746/190576806-b1c2e7c0-6e05-4548-a7c1-1be08e68c1b4.png">

Webfinger UI needs

- ownCloud icon (clickable?, it checks the server URL, but it's unknown at this moment)
- Webfinger URL hidden
- URL text filed hidden (or visible and using for username with a different tip?)
- Username displayed (or hidden?)
- Password hidden
- Log in button displayed. Should this be a new button? label and action could differ

**2. User enters the username**

- Lookup URL request sent with the username:
- If returns 200
    - Server URL received. It should be persisted somehow (same as usual, i guess)
    - Password field and Log in button displayed in case of basic auth. Login button displayed in case of browser auth.

Other auth related features and issues like:

- Token renewals in case of browser auth
- Edit session
- Sessions finished by admin (user disabled or token revoked, f. ex)
- System in maintenance mode or out of order

don't change its behaviour.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App https://github.com/owncloud/android/pull/3632
- Library (if needed) https://github.com/owncloud/android-library/pull/481

**Comment by JuancaG05** [comment]
@jesmrec login flow with webfinger was improved to make it more similar to iOS, you can check it now
