### ISSUE TITLE
As an user I would like to open audio, video and image files in other applications from the OC app, even though they can be previewed into it. (BEFORE: How to add MP3 to a playlist without using the Android file manager?)

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/android#376]
Not sure if this is the right place. Among many other folders I am syncing one with MP3s. When I click on one, I can play and hear it. But I cannot load it into the music player nor to a playlist.

I want to avoid copying files from the OwnCloud directory to the music folder with the default Android FileManager. This goes against the idea of syncing.

Any ideas?

**Comment by davivel** [comment]
@binarykitchen , right now the 'Open with' action is available also in the context menu shown with a long click on any file, even for those that are previewed in the app. Does this cover your necessities?

Thanks.

**Comment by binarykitchen** [comment]
yes, that worked, thanks @davivel
