### ISSUE TITLE
[QA] cannot connect multiple accounts of same server with android client

### ISSUE THREAD

**Issue by jnweiger** [owncloud/android#3769]
Seen with openidconnect 2.1.1-rc1 on oc10.9.1 and android client 2.2.0 and kopano IDP

* Connect mobile client with one of the demo accounts in kopano, e.g. aaliyah_abernathy.
* Try to add another connection to the same server.
   - The previous account (aaliyah_abernathy) is automatically selected
   - The mobile user is presented witht the consent page imediately.
   - There is no way in the mobile UI to select a different account.
* Remove the previous account from the mobile client.
* Try to connect again to the same server. 
  - The same account is still used without any choice. BAD.
  - Trying again later does not help. As shown below, the account is set to "Dauerhafter Zugriff (Läuft nicht ab)"  - 'never expires' -- the user is not allowed to remove that checkmark. BAD - "You can logout any time you like, but you can never leave"

![image](https://user-images.githubusercontent.com/1108546/156603389-115160c3-484b-4c19-ba8d-b41affda92a2.png)

(Cannot test android with Azure, due to unclear connect errors in my setup)

**Comment by abelgardep** [comment]
`prompt` parameter was added to the OIDC flow and the android App sends `select_account` (for the moment) so we can select the account we want to connect to.

Will be available in 4.0 release

https://github.com/owncloud/android/pull/4011

So I think we can close this issue as done in upcoming releases 👍

**Comment by DeepDiver1975** [comment]
The prompt parameter is not supported by all Idps. This has to be a branding option. Done the same way on desktop client afaik.

**Comment by abelgardep** [comment]
@DeepDiver1975 In case the Idp does not support the prompt parameter, it will be ignored, right? 

Desktop and iOS sends `consent select_account` https://github.com/owncloud/docs-server/issues/938

**Comment by DeepDiver1975** [comment]
Afak Azure is pretty strict and denies access @d7oc was facing this if I recall correctlly.

**Comment by michaelstingl** [comment]
Azure needs branded clients anyway, and there you can customise it for your needs.

**Comment by jesmrec** [comment]
For customers/branding is not a problem since it will be brandable. For Google Play? do we get the less restrictive option? @michaelstingl

**Comment by michaelstingl** [comment]
Google Play version should come with the default (`select_account consent`), same as iOS App Store version, or vanilla desktop app.

**Comment by jesmrec** [comment]
done and merged via https://github.com/owncloud/android/pull/4011 and https://github.com/owncloud/android/pull/4018. Will be available in 4.0 soon.
