### ISSUE TITLE
no connection in 1.5.3 

### ISSUE THREAD

**Issue by audiophiel** [owncloud/android#378]
Hi,
I have a problem, since i move to my fairphone and updated my OwnCloud to 6.0.1 (from 6.0.0) Its impossible to establish a connection from the Android App (version 1.5.3). Because i dont have ssh, i cant install a SSL cert.
Before changing the Phone and before the Update, it was possible to force https anyway, and conect with the Android app.

But now nothing works. Neither with forced https, nor without.
the message means "Could not set up a connection" (resp. "Konnte keine Verbindung aufbauen." because i use the app in german)

I hope im at the right place for help. here the corresponing post at the OwnCloud Forum.
http://forum.owncloud.org/viewtopic.php?f=24&t=19521

**Comment by davivel** [comment]
Really closing now ;).

@audiophiel , if this is just a problem for you, just comment back.

Thanks
