### ISSUE TITLE
[FEATURE REQUEST] Deal with 425 from "Open in Web" endpoint

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/android#3781]
@jesmrec @JuancaG05 @abelgardep please handle 425 reponses from the "Open in Web" endpoint (file still in processing)

Related:
- https://github.com/owncloud/android/issues/3672
- https://github.com/owncloud/android/pull/3773

/cc @micbar @kobergj

**Comment by jesmrec** [comment]
1. File is uploaded (no matter if android client or other client)
2. File is processing -> returns 425
3. In Android, select `Open in web` while processing
4. Show proper error message

is this ok? 

for sure, this behaviour has room for improvement, but, with the current status this will be the best approach.

feasible @abelgardep @JuancaG05?

**Comment by michaelstingl** [comment]
> 4\. Show proper error message
> 
> is this ok?

Sure, perfectly fine 👍 We just need to avoid that users get stuck.

**Comment by JuancaG05** [comment]
@michaelstingl this is the solution I developed according to what was discussed here. Is it ok?

https://user-images.githubusercontent.com/57049315/197826218-2707cea8-605f-4f71-a9bb-74479a32c3b0.mp4

We can see that when a file is being postprocessed and you tap "Open in web", a snackbar appears. Once the postprocessing is finished, the open in web flow is the normal one.

**Comment by michaelstingl** [comment]
@micbar @fschade is this the requested behaviour? ⬆️ 

@jesmrec @felix-schwarz mostly aligned with iOS?

**Comment by felix-schwarz** [comment]
Here's the flow on iOS:

1) The 425 status of the item is indicated by showing it in a disabled-like state and the message "Processing on the server"
2) When tapping the dot menu on the right side of the item, one can choose "Open in OnlyOffice (web)"
3) Choosing that option then shows the error `This file is currently being processed and is not yet available for use. Please try again shortly.` (as provided by @pmaier1 and also used by the web client AFAIK)

File showing as "Processing on the server" | Select "Open in OnlyOffice (web)" | Error message
--|--|--
![Simulator Screen Shot - iPhone 13 mini - 2022-10-26 at 15 18 39](https://user-images.githubusercontent.com/639669/198036547-057fe442-b858-40c4-ae15-60bdfba93b8a.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-10-26 at 15 19 18](https://user-images.githubusercontent.com/639669/198036587-e1eeed0f-07e5-4767-827d-b5a9b9eb3c34.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-10-26 at 15 18 56](https://user-images.githubusercontent.com/639669/198036611-cdbfe4fd-d73d-491f-848a-c8b7005b0407.png)

**Comment by jesmrec** [comment]
With the current status of Android app, the difference is the error message definition

> `This file is currently being processed and is not yet available for use. Please try again shortly`

**Comment by JuancaG05** [comment]
Error message already changed

**Comment by jesmrec** [comment]
`open-with-web` endpoint returns an slightly different error:

```
{
    "code": "TOO_EARLY",
    "message": "The requested file is not yet available, please try again later"
}
```

should all clients be aligned with server side?

**Comment by jesmrec** [comment]
Using that message. This is OK from my side.

Current behaviour:

- `Open in web` option always available in `Details` view
- `open-with-web` endpoint requested with the fileid:
   - If returns `200` -> returned url thrown to the browser
   - If returns `TOO EARLY` -> error message 
   - If returns `500 - SERVER ERROR ("Error contacting the requested application, please use a different one or try again later")`-> file not supported, error message

It will be the expected behaviour till the app's list of files is reworked.

**Comment by JuancaG05** [comment]
This was merged to the main 425 handling branch. Further discussion in its corresponding issue: https://github.com/owncloud/android-library/issues/513.
