### ISSUE TITLE
[BUG] The button for login in disappears

### ISSUE THREAD

**Issue by UnfriendlyKoala** [owncloud/android#3797]
### Actual behavior
The button for login in disappears.

### Expected behavior
The login button continues to be present in the application
 
### Steps to reproduce
1. Introduce URL
2. Introduce username
3. Introduce wrong password
4. Click repeatedly the login button

Can this problem be reproduced with the official owncloud server?
The problem was reproduced with an official owncloud server

### Environment data
Android version: Android 7.0

Device model: Motorola G5 Plus

**Comment by jesmrec** [comment]
I'm not able to reproduce this. Clicking many times, login button does not disappear. Do you mean something like this?:

https://user-images.githubusercontent.com/14894746/204232572-1ae890cc-e65a-4e0e-ae09-070a8258e019.mp4

**Comment by jesmrec** [comment]
Not able to reproduce. Please, reopen if the problem persists and add extra info about. Thanks a lot
