### ISSUE TITLE
[QA] openidconnect token refresh is not automatic

### ISSUE THREAD

**Issue by jnweiger** [owncloud/android#3873]
See with android App version ownCloud release Version 3.0.1 (5e553f078)

### Actual behaviour
- I have an owncloud server that requires login via keycloak idp (using the server openidconnect app version 2.2.0-rc.1)
- Connect android app with the server, the IDP broweser window opens, I can choose a user and log in. OK
- While logged in, wait 5 Minutes.
- Continue browsing through the app, try download or upload a files.
- A message appears saying my token is expired, I need to log in. BAD
![grafik](https://user-images.githubusercontent.com/1108546/214376835-c31ef6d6-9040-43c2-a191-08c6e6326414.png)

### Tell us what should happen.
- Token refresh with the IDP should be automatic.
- E.g. automatic camera upload cannot work with this limitation.

**Comment by michaelstingl** [comment]
@jnweiger where's the log? (HTTP included)

**Comment by abelgardep** [comment]
We released 3.0.2 last week, could you check with that version, please?

**Comment by abelgardep** [comment]
We added some logic to fix this behavior at 3.0.2.

Feel free to reopen if still reproducible with 3.0.4 or 4.0-beta1 👍
