### ISSUE TITLE
[SPACES] Thumbnails in spaces

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3878]
Thumbnails of supported mimetypes are not displayed in the app. At least, pictures should show the proper thumbnail. 

oCIS endpoint (got from iOS app)

/dav/spaces/`<space-id>`/`<path_to_file>`?y=120&preview=1&scalingup=0&x=120&a=1&c=...

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
> Thumbnails of supported mimetypes are not displayed in the app.

"supported mimetypes"? Latest behaviour of the Android app was, to request thumbnails for EVERY mimetype.

Related:
- https://github.com/owncloud/android/issues/2927

**Comment by jesmrec** [comment]
Sure, not a mimetype issue ftm.

**Comment by abelgardep** [comment]
oCIS base url: `https://server.url/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/file.txt`

oC10 base url: `https://server.url/remote.php/dav/files/admin/file.txt`

**Comment by jesmrec** [comment]
Done!!
