### ISSUE TITLE
[SPACES] Refresh spaces list in document provider  

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3888]
Spaces are listed in document provider, including personal space.

If any modification is done in the list (new space, space removed, space renamed...), such modification is not reflected in document provider till the app fetches the changes from server.

The idea is: refreshing the list of spaces in document provider without switching to the oC app. Same behaviour as the list of files in document provider.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
Done
