### ISSUE TITLE
[FEATURE REQUEST] Show upload progress

### ISSUE THREAD

**Issue by IveMalfunctioned** [owncloud/android#3894]
**Is your feature request related to a problem? Please describe.**
The upload functionality does not show progress on the upload which is especially bad for if you're uploading many files or large files. This results in decreased reliability.

**Describe the solution you'd like**
Show upload progress and information, whether in the form of a notification or in the app itself.

**Comment by jesmrec** [comment]
Upload view shows a progress bar, but the % completed.
