### ISSUE TITLE
[SPACES] oCIS account detection

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3906]
When updating from 3.x, we have to detect oCIS legacy accounts (a flag) to be able to communicate in a future the user to login again to get the spaces feature.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by abelgardep** [comment]
Spaces will be available only for fresh accounts.

If user already had an account on oCIS, the user need to remove the account and add the account again in order to use spaces within the android app.

No files migration needed.
