### ISSUE TITLE
[SPACES] Use personal as a regular space

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3919]
At the moment, the personal space still uses the old webdav endpoint.

In the app, we could use the `Links`  shortcut in the bottom bar to add shares there.  The current icon could be modified for the web/clients icon for sharing in oCIS (use the same for oC10?):

<img width="36" alt="Screenshot 2023-02-16 at 10 45 56" src="https://user-images.githubusercontent.com/14894746/219329267-6195cece-9d71-4a47-96d3-408390d73da2.png">

icons will be retrieved from branding endpoint at some point in the future. As first implementation, it could be hardcoded in the Android project

For the first iteration will be enough to show the accepted shares in the proper tab in bottom bar, as it was before.

## Current behavior
- Uploads endpoint is different
- Webdav endpoint still using the legacy one with a shares folder
- Copy operation does not work properly since we are using different endpoints https://github.com/owncloud/android/issues/3863#issuecomment-1429562735
- Personal files still stored on the legacy hierarchy

## Expected behavior
- Use space webdav endpoint to perform any operation
- Store files on the new hierarchy under the personal space id
- Accepted shares with me should be shown on the shares tab. We lose the shared-by-link shortcuts, but it's pending on full implementation #3917 

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App #3920 
- Library (if needed)

**Comment by abelgardep** [comment]
Now that we use personal as a regular space, the Shares folder is not retrieved within the regular propfind on the new WebDav endpoint. With this change, we wouldn't have access to those files.

So, as an alternative, when the account uses spaces, I think that displaying a shares tab makes more sense than showing the files with active links (at the moment, because the final idea is to show both when full implementation is done ->  https://github.com/owncloud/android/issues/3917 but it requires some time to have it, so as an intermediate step, we can display the Accepted shares)

Taking this into account, and the fact that Shares will be shown differently in the future, we can reposition the shares within the bottom navigation bar to the second position (same as other clients).

This would affect also the position of the links in oC10 accounts, as we can see in the next table.

| oC10 pos1 | oCIS pos1 | oC10 pos2 | oCIS pos2 |
| --- | --- | --- | --- |
| ![links_oc10_position1](https://user-images.githubusercontent.com/47524927/219660274-ce0bc01a-dbfa-46f5-87ab-61ba6f08f4cd.png) | ![shares_ocis_position_1](https://user-images.githubusercontent.com/47524927/219660340-37ffcac3-dbb6-46dd-a0f1-f79df776a3f9.png) | ![links_oc10_position2](https://user-images.githubusercontent.com/47524927/219660381-14310a15-195d-41c7-91e2-8e51e0db4338.png) | ![shares_ocis_position2](https://user-images.githubusercontent.com/47524927/219660488-b28fb69e-1125-4d04-9726-d6c9929d880b.png) |

Personally, I would go with the second option, with Shares/Links in the second position. This can cause some confusion for users the first time, but I think it's easy to get used to the new positioning.

What do u think @tbsbdr @michaelstingl @jesmrec @JuancaG05?

**Comment by JuancaG05** [comment]
I also like the second option, so that we are consistent with the other clients as well 👍

**Comment by jesmrec** [comment]
2 is OK for me too
