### ISSUE TITLE
[FEATURE REQUEST] Folder with "Local only" remove option

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3936]
### Steps to reproduce

Select any folder, no matter if empty or not, no matter if content is downloaded or not.

### Actual behaviour

Option `Local only` available

### Expected behaviour

Option `Local only` only available if folder does contain downloaded files.
 
This is not a bad behaviour (nothing is broken) but let users decide with less options, avoiding one meaningless option.

`oc-android_3.0.3`

**Comment by RohanTemgire** [comment]
is this task done or has been fixed yet? should I move forward with this ?

**Comment by jesmrec** [comment]
@RohanTemgire go ahead! it's asigned no one.

**Comment by parneet-guraya** [comment]
Hi, @jesmrec I would like to take this.

I want to ask a question as well (hoping it's not assigned to anyone) -->

First of all I believe by `local-only` option you mean the option we get when we're removing the folder right? I'm taking this assumption. So this is how we want the logic to behave.

- If a folder has `>=1` local file then the local-only option should show.
- upon clicking `local-only` option the only local files should be removed and non-local will still be kept.
- If folder does not have any local file then it should not show `local-only` and clicking on it obviously remove the folder along with it's contents.

I'm also wondering about the case when folder inside a folder has some local files. Following above approach would need us to iterate through sub-directories. Before going in not sure how resource intensive the task would be in a case like this if the tree of directories is very deep. But do let me know if we also want to handle this case same way as above or if you have some other approach
