### ISSUE TITLE
[SPACES] Hide "Share" option out of Personal space

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3937]
Comes from https://github.com/owncloud/android/pull/3920#issuecomment-1441706395

### Steps to reproduce
1.  User1 shares file with User2 (oCIS account)
2. User2 accepts shares in web
3. User2 opens app and `Shares` 
4. User2 selects an accepted file and open share option

### Actual behaviour
`It was not posible to retrieve the shares from sever because it was not found`

### Expected behaviour
No error

Samsung A51, Android12

___

## UPDATE:
Shares will be reworked in the future since they are not totally stable and consistent in the backend. So, for the moment, we'll hide the sharing option out of the Personal space as it only works here.

**Comment by abelgardep** [comment]
- User can access "shared with me" accepted Shares within the "Shares" option on the bottom navigation bar
- User can access "shared with others" files and folders on the original location
- User needs to accept or reject Shares in the web UI


At the moment, creating `public links` and `share files with people` is tricky out of personal space
So, for the first iteration, we can hide the share option out of personal space till [new sharing endpoint](https://github.com/owncloud/ocis/issues/4848)
- User needs to use web UI to create `public links` and `share files with people` out of personal space

**Comment by michaelstingl** [comment]
Hide Sharing if capability `"sharing_roles": true,`

- https://github.com/owncloud/ocis/issues/4847

Hide public link creation if capability `public > enabled = false`

- https://github.com/owncloud/enterprise/issues/5626#issuecomment-1448677667

**Comment by abelgardep** [comment]
> Hide public link creation if capability `public > enabled = false`
> 
> * [[BaySchoolCloud] [Desktop] Creating link via Desktop App no settings enterprise#5626 (comment)](https://github.com/owncloud/enterprise/issues/5626#issuecomment-1448677667)

Already hidden in that case

> Hide Sharing if capability `"sharing_roles": true,`
> 
> * [[Sharing] Announce new, roles-based sharing with a new capability for better client support ocis#4847](https://github.com/owncloud/ocis/issues/4847)
> 

This means we lose functionality from previous versions. v3.0 already supports sharing in personal space.
I think that supporting sharing in personal space as in v3.0 but hiding shares outside of personal could be a good option too

**Comment by michaelstingl** [comment]
> I think that supporting sharing in personal space as in v3.0 but hiding shares outside of personal could be a good option too

Accepting the oC10-style permissions in oCIS is legacy mode. Will be deprecated one day maybe… But it can stay for a few more versions…

**Comment by abelgardep** [comment]
Shares will be hidden outside of personal space for the moment 👍
