### ISSUE TITLE
failed file upload from android client

### ISSUE THREAD

**Issue by ghost** [owncloud/android#3938]
Hello,

ocis is running from docker and proxyed by HTTPS nginx .

From latest android owncloud client could not upload any file. In container log I have found

```
{"level":"info","service":"proxy","proto":"HTTP/1.0","request-id":"12691b0b-df84-41d4-82d2-8729c36cc714","remote-addr":"37.45.196.46","method":"PROPFIND","status":404,"path":"/remote.php/dav/files/admin/F-Droid.apk","duration":17.308469,"bytes":201,"time":"2023-02-26T15:42:41.482786002Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:28","message":"access-log"}
```

in android UI I see the messafe of failed error.

Can someone help - suggest the solution?

I can upload via web UI.

**Comment by jesmrec** [comment]
@ghost still reproducible?
