### ISSUE TITLE
Android Cleint SSL Cert Window popup looses focus.

### ISSUE THREAD

**Issue by EugeneNine** [owncloud/android#396]
I was asked to file a bug report on the forum.  It seems the test as you type the server address causes an issue if you have an invalid SSL cert which many of us will have running home based servers.  While typing in the server address the client tests it and and invalid SSL Cert dialog pops up but then the next character I had already started typing brings focus back to the client so the SSL Cert Dialog is moved to the background and the connection can't be completed because its waiting on the dialog to be closed.

**Comment by tobiasKaminsky** [comment]
I cannot reproduce it on real devices (Nexus 4 and 7) and emulator (android 2.3.3).
Also the popup prevents entering something in the mainapp.
Can you try it with the latest version?
And if it still occurs, please reopen and provide more infos about your mobile device.
