### ISSUE TITLE
[BUG] Sync fails for certain folders due to NumberFormatException of Quota

### ISSUE THREAD

**Issue by stefanvanherwijnen** [owncloud/android#3961]
### Actual behaviour
This is with the latest Android beta and OCIS 2.0. With a large (30 GB) folder of photos and videos, the sync in the app fails. Other folders and files work fine and also the web client works fine. I am using the s3ng storage driver.

### Expected behaviour
Synchronization in the app should work.
 
### Steps to reproduce
I am not sure what causes it or where the value `18446744064423632409` which causes the exception comes from...
My guess is that it is caused by a S3 backend which has a very large storage volume. However, this should not cause an app exception.

~~Can this problem be reproduced with the official owncloud server?~~

### Environment data
Android version: 12

Device model: Nokia G21

Stock or customized system: Stock

ownCloud app version: 3.0.4

ownCloud server version: OCIS 2.0.0

#### Web server error log
No errors, debug log:
https://paste.ee/p/tYdWg

#### ownCloud log (data/owncloud.log)
https://paste.ee/p/FHiK4

**Comment by abelgardep** [comment]
Thanks a lot for the report!

We will take a look 👍

**Comment by stefanvanherwijnen** [comment]
Apparently there was a directory which OCIS reported as 1.8 EB (while the parent directory is 30 GB), which explains where the number comes from.

I deleted and reuploaded the directory and the problem disappeared. However, this shouldn't cause an exception but it might be a problem in the webdav library that is used instead of the OwnCloud app itself.

**Comment by abelgardep** [comment]
For the upcoming beta we are removing that property from the request since we were not using it anyway..

It will be released early next week, feel free to check it 👍 

It will include support for Spaces and more! Feedback is always welcome!!

**Comment by stefanvanherwijnen** [comment]
Thanks, I'll check it out 👍
