### ISSUE TITLE
Introduce owncloud-library as module

### ISSUE THREAD

**Issue by abelgardep** [owncloud/android#3962]
**Is your feature request related to a problem? Please describe.**
At the moment, the android library is exported as a project and included in the app as a submodule.
https://github.com/owncloud/android-library

The android-library is kind of coupled to android code and accounts from AccountManager and it is not easy to work with it outside of the android app.

Dependencies need to be maintained in both projects, PR on both projects...

**Describe the solution you'd like**
The library could be included as an additional module same as `owncloudDomain` or `owncloudData`.

Could be called `owncloudNetwork` since it takes care of every single network request

![Screenshot 2023-03-10 at 12 40 21](https://user-images.githubusercontent.com/47524927/224307215-3c590ccd-2e5f-48d9-a0ff-0274ddb6fb42.png)

**Additional context**
There is not much interest in the android-library project https://github.com/owncloud/android-library/forks

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by abelgardep** [comment]
Hi @hannesa2, what do you think about this change?

Have u worked with the library outside of the android app?

**Comment by hannesa2** [comment]
No, I never used it outside. And to be honest, if I would use it outside, it would make no pain to use it from inside of main repo as well

**Comment by hannesa2** [comment]
Thanks for asking. You have my bless 😉

**Comment by abelgardep** [comment]
There are some facade classes that could be removed as soon as the `owncloud-library` is introduced as a module. 

All the Services could be removed and the remote datasource would call the remote operation directly instead of using this facade https://github.com/owncloud/android-library/blob/master/owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/Service.kt

Also, there are some intermediary classes like RemoteShare and RemoteCapability that are redundant and could be removed too. The response classes from Moshi could be mapped directly to model instead of the current `CapabilityResponse` -> `RemoteCapability` -> `OCCapability`

**Comment by hannesa2** [comment]
If you want, I can do this **without loosing the history**

**Comment by JuancaG05** [comment]
> If you want, I can do this without loosing the history

Hi @hannesa2! That would be great! We need to do a quick revision of the whole `owncloud-library`, and when we're ready, I'll ping you for you to work on this if you want 👍

**Comment by jesmrec** [comment]
@hannesa2 are you still interested/available to do this one?

**Comment by jesmrec** [comment]
> Yes, I could do this with ease

that'd be fantastic.

**Comment by hannesa2** [comment]
Is now the right time ?
I want to avoid a long running pull request, which causes a lot of maintenance

**Comment by jesmrec** [comment]
> Is now the right time ?
I want to avoid a long running pull request, which causes a lot of maintenance

you're right. Team is now working full-time on new release. We can wait till release is done to review the PR as soon as it is ready. I will ping you at this point.

**Comment by jesmrec** [comment]
@hannesa2 all the team is now available for reviewing as soon as you send the code (if you are still interested in).

**Comment by hannesa2** [comment]
@jesmrec https://github.com/owncloud/android/pull/4183

**Comment by jesmrec** [comment]
so fast, thanks, reviewing by the team
