### ISSUE TITLE
[BUG] Can't connect

### ISSUE THREAD

**Issue by Yoyo2A** [owncloud/android#3989]
### Actual behaviour
-I can't connect to my owncloud, I've got an error when loging (Erreur inconnue / Unknow error)

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
-No it works fine with the test server !

### Environment data
Android version: 12

Device model: OnePlus 10 Pro

Stock or customized system: Stock

ownCloud app version: 3.0.4

ownCloud server version: I don't know, i am using Owncloud via Useed (https://www.useed.fr/)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by abelgardep** [comment]
Hi @Yoyo2A thanks for opening an issue!

But unfortunately, there is nothing we can do at all if there is a redirection to a nextCloud instance 
`Location: https://server.url/nextcloud/status.php`

If the expected instance is nextCloud, then open an issue there.
If the expected instance is ownCloud, there is something wrong with the redirections.

Let us know if u find something else!

**Comment by Yoyo2A** [comment]
OK thanks, I'll check !

**Comment by Yoyo2A** [comment]
Ah it works with Nextcloud ! Sorry for disturbing !
