### ISSUE TITLE
[BUG] Thumbnails not shown in 3.0.4

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#3991]
### Actual behaviour
A user reported that file thumbnails are not shown in the app

### Expected behaviour
Thumbnails should be shown properly
 
### Steps to reproduce
1. Enter the app
2. See any file, they have no thumbnail

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
User didn't specify

### Environment data
Android version: 13

Device model: Pixel 7

Stock or customized system: User didn't specify, so let's say no?

ownCloud app version: 3.0.4

ownCloud server version: 10.12.0

#### Web server error log
```
No logs
```

#### ownCloud log (data/owncloud.log)
See the attached file with sensitive data censored:
[owncloud.2023-03-24.log](https://github.com/owncloud/android/files/11062435/owncloud.2023-03-24.log)

**Comment by AasheeshLikePanner** [comment]
Hi, I am new To open source contribution. I find that in` preview_image_fragment .xml` There was a bug in ImageView It was showing Insufficient text color contrast ratio I think this could be the reason for thumbnail not showing properly.

Also in `preview_image_activity `it was showing `fragmentPager <com.owncloud.android.ui.preview.ViewPagerWorkAround>: No speakable text present`. I think This is the could reason of thumbnails are not showing properly.

**Comment by jesmrec** [comment]
still reprodicible?

**Comment by JuancaG05** [comment]
I don't really know, the communication thread with this user finished at that point. Let's close this since we are working on some improvements for thumbnails and if needed, we'll open a new issue 👍
