### ISSUE TITLE
[FEATURE REQUEST] Fix endpoint for "Open in web"

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4008]
Comes from https://github.com/owncloud/android/pull/3990#issuecomment-1488893551.

When implementing "Open in web" for specific providers, we realised that a server instance (https://ocis.ocis-wopi.latest.owncloud.works) couldn't open files, and this could be due to not using the correct endpoint.

The idea here is changing the open-in-web endpoint from `https://ocis.ocis-wopi.latest.owncloud.works/app/open-with-web` (the one we use currently) to `https://ocis.ocis-wopi.latest.owncloud.works/app/open` to align also with the iOS client.

Doc: https://github.com/owncloud/ocis/blob/7ef7a60d710f2ac582a64417c03b0f0f4336261d/docs/services/app-registry/apps.md#open-a-file-with-the-owncloud-web

**Comment by JuancaG05** [comment]
Finally, the endpoint is NOT going to be changed. The problem was a server-related bug, whose fix was not deployed yet. After deploying it, everything seems to work with the `open-with-web` endpoint.

More info: https://github.com/owncloud/web/issues/8773

**Comment by jesmrec** [comment]
Then, it's done. Will do another round in regression stage
