### ISSUE TITLE
Avoid error when empty item name

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4045]
Two ways to reproduce this

1. Create a new folder
2. Empty text field
3. Click `OK` -> error message in snackbar

___

1. Rename any item
2. Empty text field
3. Click `OK` -> error message in snackbar

Proposal:

With empty text field, `OK` not clickable

**Comment by parneet-guraya** [comment]
I want to work on this. As I am new to this I might need some help

**Comment by JuancaG05** [comment]
Nice @parneet-guraya! Go ahead! You can ask whatever you want and I'll try to help you 🚀 
You can start reading the [CONTRIBUTING.md](https://github.com/owncloud/android/blob/master/CONTRIBUTING.md) document to make the first steps 😀

**Comment by parneet-guraya** [comment]
> Nice @parneet-guraya! Go ahead! You can ask whatever you want and I'll try to help you 🚀 
> You can start reading the [CONTRIBUTING.md](https://github.com/owncloud/android/blob/master/CONTRIBUTING.md) document to make the first steps 😀 

Working on it!!

**Comment by parneet-guraya** [comment]
I have made some changes and got it working. But, I first want to show it that I'm going in right direction or not. Should I share my code over here or make a commit and link that?

**Comment by JuancaG05** [comment]
> I have made some changes and got it working. But, I first want to show it that I'm going in right direction or not. Should I share my code over here or make a commit and link that?

If the changes you want to show are visual, you can upload a screenshot here. If it's about code, you can wait until the code review I will do once you finish the development and your PR is ready, or if you think it's necessary to review it before going on, you can create the PR and tell me what to review 😁

**Comment by parneet-guraya** [comment]
#4046 @JuancaG05 Hi, I have created my first draft of the solution to check i'm going right. Have a look at it. Thanks
