### ISSUE TITLE
Nasty releases

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android#4056]
Hi, I tried to start with https://github.com/owncloud/android/pull/3188#issuecomment-1568681933
Doing so I looked around the current state, but I see you created releases on unknown SHA1, that's nasty !
Even you don't tag a release.

![image](https://github.com/owncloud/android/assets/3314607/868150fb-ec5d-40aa-b6c2-6b374fb273c6)

Even to modify a changelog manually is as modern as sending a FAX in 2023

![image](https://github.com/owncloud/android/assets/3314607/8c425206-13c2-4008-a9f4-2e4ae4a73d6e)

I made already a pull request to automate this ci/release/pullrequest with automated changelogs. Related to your feedback, I gave up here. That's why I only see this mess. -sorry, I've to say this-

Please avoid this releases on unknown SHA1 and please tag every release.

**Comment by jesmrec** [comment]
All releases are not only tagged, also verified with the GitHub green tick:

![Screenshot 2023-06-05 at 08 17 06](https://github.com/owncloud/android/assets/14894746/0ec677d4-337b-4d45-a3e7-4c4a987cba00)

![Screenshot 2023-06-05 at 08 17 12](https://github.com/owncloud/android/assets/14894746/64142c4a-ff10-4b40-80a0-6f3576cc8836)

Please use the tagged commit like `oc-android-4.0 , `oc-android-3.0.4` to checkout to the proper commit. Or, checkout to the `stable` branch to get the latest stable. It's so easy.

Will check why the GitHub warning or how to avoid it. Thanks for reporting.

**Comment by hannesa2** [comment]
Ahh, sorry my fault.
I assumed a `git fetch --all `does the job, but I need `git fetch upstream --tags`
<img width="628" alt="image" src="https://github.com/owncloud/android/assets/3314607/335b3a58-a702-4b33-8080-67c63457a48c">
