### ISSUE TITLE
Ability to filter downloaded / offline available files

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#407]
We already have this cool indicator which shows you if a file has been downloaded or not. Now in addition we should have a dedicated entry »Offline« (or some similar word) so people can quickly access these files.

Google Drive for example has an entry called »On device« for that.

___

Edited by @davigonz 

| New available option | Available offline list | 
| ------------- |:-------------:| 
| ![new_available_option](https://user-images.githubusercontent.com/15261363/39619818-63491800-4f89-11e8-8d21-e2afa482f6c2.png) | ![available_offline_list](https://user-images.githubusercontent.com/15261363/39619816-60039382-4f89-11e8-9e16-49cb950c4f16.png) |

## ACs
1. How to show available files and folders in the root view after pressing available offline option in side menu:
   - [ ] Av. offline files: do not show parent folders, show them directly with the path below the file name, instead of the date.
   - [ ] Av. offline folders: only show folders set as available offline, not folders that are available offline because the parent folder is av. offline.

2. Actions to perform on available offline files and folders shown in available offline view:
   - [ ] Av. offline files: 
      - Open when tapping it. 
      - Keep long press to show more options for every file: disable av.offline, open with, details, select all and select inverse.
   - [ ] Av. offline folders:
      - Allow navigation
      - Keep long press to show more options for every file: disable av.offline, select all and select inverse.

3. Change toolbar name to Av. offline files.

**Comment by jancborchardt** [comment]
New corresponding iOS issue: https://github.com/owncloud/ios/issues/79

**Comment by tobiasKaminsky** [comment]
I remember that there was a discussion to not distinguish between local/remote files?
So is this issue still valid?
@davivel @jancborchardt

**Comment by jancborchardt** [comment]
Well, there should definitely be a way to see which files I downloaded to my device. Two use cases:
* I’m without connection and want to work with files I have locally
* I want to clean up space on my device and remove downloaded files selectively

**Comment by tobiasKaminsky** [comment]
From @LukeOwncloud (https://github.com/owncloud/android/issues/1231#issue-114220541):
> When choosing "On device" from the side drawer I expect all folders which do not contain any downloaded files to disappear. Instead I still see the whole folder structure. This is confusing to me as a user.
Further, there is no indication that currently only files "on device" are shown. Looking at a folder which I know has content but which says "Nothing in here. Upload something!" (string file_list_empty), is even more confusing. Note: Also string local_file_list_empty "There are no files in this folder." would not help much, either.

**Comment by LukeOwncloud** [comment]
After having tested this feature in the beta version, I am doubting the usefulness. Following issues I noticed:

- If all folders are shown, there are folders which are empty. This is confusing as one does not know where the files actually are.
- If only folders with content are shown, there is no way to upload data into an empty folder (-> https://github.com/owncloud/android/issues/1231).
- `I’m without connection and want to work with files I have locally` but I do not see the file I am looking for, I am wondering whether the file has a diferent name, was moved, was not uploaded... So I switch back to the other view to make sure that the file is on the server (but just not available on the device).
- `I want to clean up space on my device and remove downloaded files selectively` but then I do no see where the large files and directories actually are.

My suggestion for this offline mode:
- a switch in the side drawer `offline mode`
- offline mode uses same outline as while being online
- when activating offline mode all favorite files are synced one last time, then no more connection is made to the server
- that is, no auto refresh when browsing into folder
- further, when user tries to perform online operation, display dialog "You are working offline. Do you want to go online."
- show indication that offline mode is active (e.g. by changing the app icon)
- This is pretty much as done by Thunderbird's offline mode

For helping users to clean up offline files:
- create a new view (e.g. clean up manager)
- it again show all files and folders, sorted by size
- visualize size e.g. like this http://www.tweaknow.com/images/HDAnalyzer/DirTreeView.png
- for each item add button or menu action: clean up (which removes all local files within this folder)

**Comment by tobiasKaminsky** [comment]
The offline modus is in my opinion a very different thing (and of course more useful than the filter) and should be handled/implemented in a new issue.

This currently is more like a "view" that shows only some files, like if we had a filter that will filter by a search string (only local and only in the current folder).

So I would leave it this way and implement "your" offline idea in a new issue/pr.

**Comment by LukeOwncloud** [comment]
Agreed, offline mode is another issue.

But my question remains: What is a useful use-case of this "view"? If it really is about helping the user to clean up offline files, I'd suggest to integrate my ideas from above (visualize size)

**Comment by tobiasKaminsky** [comment]
@jancborchardt this is in beta a long time.
But the user cannot see if he is in "all files" or "on device" mode. 
Do you have an idea how we can show this to the user?

**Comment by tobiasKaminsky** [comment]
@jancborchardt this is solved by #1205 
can you have a look at https://github.com/owncloud/android/issues/407#issuecomment-152805657 and decide what to do?

**Comment by jancborchardt** [comment]
I agree that offline mode is entirely different here. Offline files should be a flat list of the files and folders (the highest offline available parent is shown), just like favorites and shares.

@davivel @masensio is reviewing this something for the team week? ;D

**Comment by tobiasKaminsky** [comment]
Can you explain the "offline files" a bit more?
I would expect to have the same hierarchical folder structure as the server but only show those folders that have a downloaded file in its folder or in its children folder.
Mainly this is like browsing the device owncloud folder with an external file manager.

A flat view that does not keep the structured folders is, at least for me, very unintuitive.
(But is ok for me for favorites and shares).

**Comment by jancborchardt** [comment]
Let’s say I have a downloaded file »icon-upload.svg« in the folder »owncloud/core/img/actions«. Now to access it from the downloaded files, I need to navigate down _3_ otherwise empty folders to reach it.

That doesn’t make a lot of sense and is also the reason why we don’t keep any hierarchy for the Favorites and Shares view. :) The whole point of the separate views is to filter and make it quicker to find these files.

**Comment by rperezb** [comment]
yes, I am with @jancborchardt within the offline view, files will be shown on the "root"
I'm curious about "available offline" folders, I will show the folder and make it possible to browse around it, instead of showing each file store on it

**Comment by davigonz** [comment]
Done, to be included in 2.11
