### ISSUE TITLE
[BUG] unneccessary or wrong call ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/android#4074]
### Actual behaviour
Android app tries to connect to a folder named after the hostname
![image](https://github.com/owncloud/android/assets/1005065/cd503a14-30f1-4277-95c6-dafee9734d8e)

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. connect to a server `http://foobar:8088` (related to http or being a local dns name or because of the port)
2. see a strange PROPFIND on the server `[Thu Jun 15 16:01:11 2023] 192.168.178.185:46748 [401]: PROPFIND /remote.php/dav/files//http%3A//foobar%3A8088
`

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Is this in first instance? (first request of the flow). Android app does a  `PROPFIND` expecting 401 to check response authentication headers (`Basic` , `Bearer`, or both). Indeed, iOS app behaves so too. 

In this way, app decides whether showing credentials in app (basic auth) or moving to browser (OAuth2 / OIDC)

**Comment by DeepDiver1975** [comment]
This is on setup after entering the server url before the credentials

**Comment by jesmrec** [comment]
> This is on setup after entering the server url before the credentials

that's it. URL is checked via `PROPFIND` assuming 401 response, to get response headers. No other way to check this atm.

**Comment by michaelstingl** [comment]
The check is needed and documented here:
https://github.com/owncloud/oauth2/wiki/OAuth-code-Flow-Sequence-Diagram

But it shouldn't have the `/http%3A//foobar%3A8088` at the end?

**Comment by DeepDiver1975** [comment]
> But it shouldn't have the `/http%3A//foobar%3A8088` at the end?

this is exactly what I am referring to .....

**Comment by jesmrec** [comment]
will check, thanks.
