### ISSUE TITLE
[FEATURE REQUEST] OCIS: "Share to" allows only upload to personal "space"

### ISSUE THREAD

**Issue by rmk-ch** [owncloud/android#4088]
### Actual behaviour
With Owncloud Infinite Scale server:
If I want to share a file from another android app and selecting owncloud I am asked for which account I would like to upload (I have two, an OCIS and a classic OC). Selecting the OCIS, I can only upload to my personal space (or a subfolder of that).

### Expected behaviour
After asking for which account I should be able to select where to upload the file, either to personal space, a shared folder or to a space. This selection never appears, only the personal space appears.

Currently a killer for me for OCIS.
 
### Steps to reproduce
1. Open some android app (e.g. gallery), and share this with own
2.  Select one or many files
3. Using the share button, select owncloud
4. Owncloud opens the personal space directly

Can this problem be reproduced with the official owncloud server? --> no, classic owncloud has a different concept of spaces and shares
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 13

Device model: Samsung Galaxy A51

Stock or customized system: Stock

ownCloud app version: 4.0 (26ccad5af)

ownCloud server version: 
ownCloud | Infinite Scale
Community
3.1.0-next.1+4ac9df17a

### Logs
n/a

**Comment by JuancaG05** [comment]
Hi @rmk-ch! Thanks for opening a new issue!
In this case, we're not talking about a bug but about a known restriction we currently have for oCIS accounts. Shares are not totally stable on the backend yet, so at the moment we only allow sharing within personal space from other apps. Of course, we have this in mind for future versions 😁.

**Comment by rmk-ch** [comment]
Hi @JuancaG05 Thanks a lot for the response. Good to hear it's on the roadmap (although I thought ocis was already more stable ;) ).
Nevertheless, looking forward for more features - keep up the good work!

**Comment by rmk-ch** [comment]
@JuancaG05 Is there a roadmap with some target date? I only find outdated roadmaps saying that OCIS 2.0 will be stable. We're approaching OCIS 3.1 now and I have no clue what's still on the plan and whatnot (incl. the android client).
Due to the EOL of PHP 7.4 and some hosting companies not allowing outdated PHP versions we need to take a decision whether my new instance will be owncloud, OCIS or even nextcloud.

**Comment by tbsbdr** [comment]
Hi @rmk-ch we have a public roadmap that shows major milestones for Infinite Scale: https://owncloud.com/roadmap

**Comment by jesmrec** [comment]
This is the current status and the new expected behaviour (dev team)

Current:

1. Select from 3rd party
2. Select account if more than one are attached to the device
3. Select destination folder
4. Submit

New:

1. Select from 3rd party
2. Select account if more than one are attached to the device
3. If selected account is oCIS, show the list of spaces including `Personal`
4. Select destination folder inside the chosen space
5. Submit

**Comment by michaelstingl** [comment]
> * If selected account is oCIS, show the list of spaces including `Personal`

Could look like the Space selector when using the "Copy" feature:

![Screenshot_20230808-140507](https://github.com/owncloud/android/assets/214010/d1021c3c-503d-4095-b6a9-f1462a42f750) | ![Screenshot_20230808-135110](https://github.com/owncloud/android/assets/214010/a7f475ae-ba89-4c04-a289-79b9bf1574ce) | ![Screenshot_20230808-135655](https://github.com/owncloud/android/assets/214010/b6183b59-5065-41f2-a1cc-9d0b048c1012)
-- | -- | --
2️⃣ Select account if more than one are attached to the device | 3️⃣ If selected account is oCIS, show the list of spaces including Personal | 4️⃣ Select destination folder inside the chosen space

**Comment by rmk-ch** [comment]
> Hi @rmk-ch we have a public roadmap that shows major milestones for Infinite Scale: https://owncloud.com/roadmap

Thanks a lot. That is a much better link than the official docs: https://owncloud.dev/ocis/release_roadmap/

**Comment by rmk-ch** [comment]
Thanks @michaelstingl and @jesmrec! Would this also work with a shared folder? My understanding is that shared folders are neither in the personal nor in another space.

**Comment by jesmrec** [comment]
> Thanks @michaelstingl and @jesmrec! Would this also work with a shared folder? My understanding is that shared folders are neither in the personal nor in another space.

if the folder is shared by you, you can put inside as many items as you wish.
if the folder is shared with you, it depends on the permission level you are granted by the owner.

**Comment by rmk-ch** [comment]
>  if the folder is shared by you, you can put inside as many items as you wish.
Agreed, this works.

>  if the folder is shared with you, it depends on the permission level you are granted by the owner.
This folder does not appear in the personal space (in the webapp and in the android app) but in its own category (shared). Therefore, in my opinion the android app should also show the shared folders as an option to where to upload the selected files (number 4 in the proposal https://github.com/owncloud/android/issues/4088#issuecomment-1663829492).
