### ISSUE TITLE
SSL initialisation failed - can't login to oCIS server

### ISSUE THREAD

**Issue by allan2** [owncloud/android#4140]
I have an oCIS server that is working when logging in through the web portal, the desktop app, and the iOS app.
My SSL is setup properly (ratings of A on SSL Labs online tool).

I cannot get it working on Android. I am unable to add an account in the Android app.

### Steps to reproduce

I put in the server address, `ocis.mydomain.com`, and click on the arrow.
I get an error message: "SSL initialisation failed".

### Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

It works with the test server and credentials.
When I input `demo.owncloud.org`, I get "Connection established". I can then input the test credentials and authenticate successfully.

### Environment data
Device details: Samsung Galaxy Note 8 SM-N950W, stock Android 9
ownCloud Anroid app version: 4.0 (`26ccad5af`)
ownCloud server version: oCIS 3.1.0-rc.1

#### Server log

Server log does not change. No hit from client.

#### Android app log
```
D: 2023-08-23 10:27:40:342(ClientManager.kt:93) .getClientForAnonymousCredentials()Reusing anonymous client for https://ocis.mydomain.com
D: 2023-08-23 10:27:40:344(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id 09254216-b286-4e34-992b-b4a6502f172a
E: 2023-08-23 10:27:40:443(GetInstancesViaWebFingerOperation.kt:99) .run()Requesting WebFinger info failed
javax.net.ssl.SSLHandshakeException: Handshake failed
```

[Full Android app log](https://github.com/owncloud/android/files/12420440/owncloud.2023-08-23.log)

May be related to #3868 because of the same error message.

Thank you!

**Comment by jesmrec** [comment]
seems to be something related with the webfinger validation. App checks some endpoints at the beginning to choose which authentication flow to follow. 

I'd ask you to get more logs in the app, checking the `Log HTTP requests and responses` option in the `Logging` menu located inside of `Setitngs`. So, we can check how the request flow runs. It may help.

**Comment by allan2** [comment]
The HTTP request setting was already checked and included in my previous log.

I have attached a new log just in case.
[owncloud.2023-08-23_http_req_checked.log](https://github.com/owncloud/android/files/12421249/owncloud.2023-08-23_http_req_checked.log)

**Comment by jesmrec** [comment]
will need to research a little bit here. any way to get a test account in your server? in case it is, forward to android-app@owncloud.com

**Comment by allan2** [comment]
I tried again today with Android client 4.1.0. It worked! I'm not sure if it's a a client update or due to a change to my server.

**Comment by jesmrec** [comment]
4.1 was released yesterday but it did not include changes in authentication features. Anyway, good news :)
