### ISSUE TITLE
[FEATURE REQUEST] Log file in debug mode, accesible out of ScSt

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4146]
**Problem/Context:**

When the app crashes in the beginning, it's not posible to open `Settings` to reach logs and check what's going on. 

**Suggested solution:**

Some way to store the logs file outside of the Scoped Storage, so it's accesible without using Android Studio. Only available in `DEBUG` variant. Current location:

![Screenshot 2023-08-30 at 18 44 05](https://github.com/owncloud/android/assets/14894746/f707b9e1-8b3c-4b7d-9f8e-d6a69dafeace)

Is this feasible?? (needs research)

As idea, a new brandable option to create file in a different location (f.ex. `Downloads`). 

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
> Some way to store the logs file outside of the Scoped Storage, so it's accesible without using Android Studio. Only available in `DEBUG` variant. Current location:
> 
> ![Screenshot 2023-08-30 at 18 44 05](https://user-images.githubusercontent.com/14894746/264414847-f707b9e1-8b3c-4b7d-9f8e-d6a69dafeace.png)
> 
> Is this feasible?? (needs research)

Regular device, not connected to Android Studio, but a special debug APK we can provide when requested?

**Comment by jesmrec** [comment]
> Regular device, not connected to Android Studio, but a special debug APK we can provide when requested?

oB provides debug builds. In case this feature is feasible, it will be available for every debug build. But, needs research first.

**Comment by jesmrec** [comment]
Follow up: https://github.com/owncloud/android/issues/4155

**Comment by jesmrec** [comment]
Proposal: make logs folder visible in doc. provider through a branding variable. Will work on it

**Comment by LisaHue** [comment]
@DeepDiver1975 this was never realized. Is this planed?

**Comment by LisaHue** [comment]
Hello, was this ever realized, or was there no decission made until now?

**Comment by jesmrec** [comment]
ftm no decision, no prioritized yet.

**Comment by LisaHue** [comment]
@DeepDiver1975 do we have a decision here?

**Comment by DeepDiver1975** [comment]
Crash reporting is done via google play console - why is this not an option here?

**Comment by NannaBarz** [comment]
Because the app is provided via the customers Play Store.

**Comment by JuancaG05** [comment]
> Because the app is provided via the customers Play Store.

In any case, their IT admin could get these crash logs from their Play Console account and send them to us, that would help us a lot and make this issue (reachable logs out of scoped storage) less prior

**Comment by NannaBarz** [comment]
I think their IT Admin is another legal department... Not sure if we can get this
