### ISSUE TITLE
[BUG] can't log in on Android ("malformed server configuration")

### ISSUE THREAD

**Issue by swhalemwo** [owncloud/android#4169]
### Actual behaviour
I can't log in my android devices from networks that are not the home network.

### Expected behaviour
I am able to log into owncloud on my android devices.
 
### Steps to reproduce
recently started trying out ownCloud, which runs on a raspberry pi. I followed [this tutorial](https://pimylifeup.com/raspberry-pi-owncloud). when I try to connect my phone, I get the error message of "Malformed server configuration". This only occurs when trying to log in through a network that is not the home network (e.g. mobile data), on the home network (using the local IP) my android devices can log in as expected (my main computer can also log in properly over a non-home network connection). My problem is almost identical to #509.

<details>
  <summary>my config.php</summary>

```
<?php
$CONFIG = array (
  'instanceid' => myinstanceid',
  'passwordsalt' => 'mypasswordsalt',
  'secret' => mysecret',
  'trusted_domains' => 
  array (
    0 => 'my.local.ip',
    1 => 'my.global.ip,
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://my.global.ip,
  'dbtype' => 'mysql',
  'version' => '10.13.1.3',
  'dbname' => 'ownclouddb',
  'dbconnectionstring' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'ownclouduser',
  'dbpassword' => mydbpassword',
  'allow_user_to_change_mail_address' => '',
  'logtimezone' => 'UTC',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'loglevel' => 1,
  'maintenance' => false,
);
```
</details>

Can this problem be reproduced with the official owncloud server?
No, I can log into the demo server (as well as other owncloud servers) with my android devices.

### Environment data
Android version: 11

Device model: Unihertz Atom L

Stock or customized system: Stock

ownCloud app version: 4.1.0

ownCloud server version: 10.13.1.3

Logs: login attempts do not produce events in the logs.

**Comment by JuancaG05** [comment]
Hi @swhalemwo! Thanks for opening a new issue.
Although it's kinda old, looking at the similar issue you found I can suggest 2 things:
1) Did you try to change `installed` to `1` instead of `true`?
2) Did you take a look into the `status.php` file of your server with the current configuration? It could be that the `installed` key is equal to `false` somehow?

Also, if you say you can log into the demo server, it could be useful to compare the configuration you have in your server with the configuration in the demo server to see if any of those differences is affecting this process.

You'll let us know about this 😃

**Comment by swhalemwo** [comment]
thanks for your ideas! I've now switched to `apache2` (the tutorial I followed used `nginx`) and no longer encounter this particular problem, so it probably was indeed some server configuration issue (also since I could connect to other servers).
