### ISSUE TITLE
Upload queue can't complete post account details changed

### ISSUE THREAD

**Issue by michaelgwood** [owncloud/android#419]
### Expected behaviour
The upload queue is cleared. If there are pending files ask if the files should be uploaded using the new account ?

### Actual behaviour
The file is stuck. If you change your account details and there are currently files in a queue to be uploaded the account details that were present at the time of the upload being queued will be used causing AccountNotFound exception or other access related errors.

### Steps to reproduce
1. Queue up a bunch of files to be synced
2. Change account details

### Environment data
Android version: 4.4.2
Device model: Nexus 5

Stock or customized system:

ownCloud app version: 1.5.3 
ownCloud server version: 4.5.13

#### ownCloud log (data/owncloud.log)

03-03 15:17:50.473: E/FileUploader(13865): Error while trying to get autorization for user@ip
03-03 15:17:50.473: E/FileUploader(13865): com.owncloud.android.lib.accounts.AccountUtils$AccountNotFoundException: Account not found
03-03 15:17:50.473: E/FileUploader(13865): 	at com.owncloud.android.lib.accounts.AccountUtils.constructFullURLForAccount(AccountUtils.java:90)
03-03 15:17:50.473: E/FileUploader(13865): 	at com.owncloud.android.lib.network.OwnCloudClientFactory.createOwnCloudClient(OwnCloudClientFactory.java:73)
03-03 15:17:50.473: E/FileUploader(13865): 	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:488)
03-03 15:17:50.473: E/FileUploader(13865): 	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:458)
03-03 15:17:50.473: E/FileUploader(13865): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-03 15:17:50.473: E/FileUploader(13865): 	at android.os.Looper.loop(Looper.java:136)
03-03 15:17:50.473: E/FileUploader(13865): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by enoch85** [comment]
Will this be in https://github.com/owncloud/android/pull/1493?

**Comment by davivel** [comment]
I'm not sure. I don't fully understand what ```you change your account details```means.

@michaelgwood , could you explain the steps to reproduce the problem with some more detail? Thanks.

**Comment by tobiasKaminsky** [comment]
I think he means changing url or username of the account.

**Comment by davivel** [comment]
But there is no way in the app to change the url or username of an account. You need to create a different account. Is that the use case, @michaelgwood ? Do you want to transfer pending uploads from an OC account to a different OC account?

**Comment by jancborchardt** [comment]
What I think he means by »change your account details« is to switch the account to another one. As instant upload will always upload to the current account, it’s likely that the pending/errored images will upload to the new one. This should not happen though.

**Comment by davivel** [comment]
>  it’s likely that the pending/errored images will upload to the new one.

Fortunately that's not happening :-)  . Pending or failed uploads will go on or be retried to the account that was current when they were triggered first. With the uploads view too.

@michaelgwood , still would be good to have your comments here :-)

**Comment by tobiasKaminsky** [comment]
@michaelgwood is this still happening with the latest version?

**Comment by rperezb** [comment]
@michaelgwood @tobiasKaminsky I think we may close this issue, due to inactivity
If this is still reproduceble, please reopen
