### ISSUE TITLE
[QA] New calens version 0.4.0 available (changelog)

### ISSUE THREAD

**Issue by mmattel** [owncloud/android#4245]
There is an updated calens (changelog generation) version available (0.4.0) that is capable showing pre-releases (many thanks to Michael Barz). ocis and core already use this latest version. Can someone from the team check this repo for using the updated calens version? To show prereleases in the changelog if required, pls get in touch with mbarz for a how to. To see it live, have a look at our [homepage](https://owncloud.com/changelog/infinite-scale/)

@michaelstingl fyi

**Comment by michaelstingl** [comment]
Android app repo uses:
https://github.com/owncloud/android/blob/a8534ba880bee3b406d4c32455a0e9548a28a264/.github/workflows/calens.yml#L27

It should already use `restic/calens v0.4.0`
- https://github.com/toolhippie/calens
- https://hub.docker.com/r/toolhippie/calens/tags/
