### ISSUE TITLE
[FEATURE REQUEST] `Auto-uploads` string in  Settings

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4252]
Opening the `Settings` view:

![Screenshot 2023-12-11 at 09 44 21](https://github.com/owncloud/android/assets/14894746/ee45ec03-2a1f-4002-ad3a-6bd8f63e8a7b)

i don't get the point of `Auto-uploads` instead of `Auto uploads` 

I would get rid of the dash inbetween.

Any reason for this???

Checking the git-blame, @EParzefall is the author. 

Could you clarify the reason? thanks

**Comment by EParzefall** [comment]
"auto" alone is ambiguous, but of course nobody would think you could upload automobiles from your Android phone to ownCloud. Still, "auto" as short form of automatic is usually directly attached to the word it refers (as in autobiography)  to or used with a hyphen if the combination is not so common yet as in auto-suggest or auto-complete.
Check out the definition in Webster: https://www.merriam-webster.com/dictionary/aut-

**Comment by jesmrec** [comment]
would it be a good option to call them `Automatic uploads` instead of `Auto uploads`? 

In the past, we used to call them `Instant uploads` because pictures from camera were uploaded straight from the camera to the cloud. With the Android restrictions starting in Android6, the 15 minutes gap forced us to change the wording.

CC @michaelstingl @Aitorbp @JuancaG05 @TheOneRing

**Comment by EParzefall** [comment]
> would it be a good option to call them `Automatic uploads` instead of `Auto uploads`?

Absolutely!

**Comment by JuancaG05** [comment]
Whatever is the option taken, I think we should align with the iOS app, which is the other client that has the automatic uploads feature. AFAIK, in the iOS app it's `Auto Uploads` currently.

**Comment by michaelstingl** [comment]
> Whatever is the option taken, I think we should align with the iOS app, which is the other client that has the automatic uploads feature. AFAIK, in the iOS app it's `Auto Uploads` currently.

@hosy could you help align this?

/cc @tbsbdr

**Comment by jesmrec** [comment]
Options to mind:

- Auto uploads
- Autouploads
- Automatic uploads
- Auto-upload
- Other ... ¿?

**Comment by mmattel** [comment]
From a doc pov and for translations, I propose to use `Automatic uploads`.

**Comment by mmattel** [comment]
@jesmrec Note, as the text is now more precise about what it is for...

`Automatic upload pictures` --> `Automatic picture upload`
`Automatic upload videos` --> `Automatic video upload`

Sorrry for being nit picking 😅

**Comment by jesmrec** [comment]
No problem @mmattel, feedback is always welcome. In fact, the strings you are suggesting sound even better.

**Comment by jesmrec** [comment]
@mmattel @JuancaG05 @joragua silly question:

`Automatic picture upload`
or
`Automatic picture uploads`

**Comment by mmattel** [comment]
You are right, plural `Automatic picture uploads` 😄
