### ISSUE TITLE
Action on multiple Files

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/android#426]
Current behaviour:

I can only select one file (for example to delete, rename or share it).

Expected behaviour:

I want to be able to select many files and folders. An "action bar" should appear (compare to android browser on text-selecting) with some actions, for example: delete, share, move, ...

Mockup:

![mockup](https://f.cloud.github.com/assets/4741199/2367967/a92a9196-a78b-11e3-94fa-91d21f69c069.png)

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/owncloud/android/issues/899 which is more specific about the long-press. @stefan-niedermann thanks for reminding me about this issue! :)
