### ISSUE TITLE
Handle error 423 (locked file)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4282]
Comes from: https://github.com/owncloud/android/pull/4270#issuecomment-1882626155

The app has the [423](https://http.dev/423) error defined 

https://github.com/owncloud/android/blob/c4c2ac624b5ec4209848b6b157b88f779881c0c7/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java#L187

but not handled. In case it happens, `Unknown error`  is displayed.

Expected: if 423 is retrieved from the server in any situation, `Locked file` or similar should be displayed.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by parneet-guraya** [comment]
I want to work on this

**Comment by jesmrec** [comment]
go ahead!!
