### ISSUE TITLE
[BUG] Opening details of image in folder causes app reset when server is oCIS

### ISSUE THREAD

**Issue by 000yesnt** [owncloud/android#4290]
### Actual behaviour
When opening an image and checking its details from the 3 dots menu, if the server is oCIS and the image is inside a folder, the app will reset to the top of the home folder.

https://github.com/owncloud/android/assets/49329895/a9eeb8d5-590c-47e3-a004-15db1c72aba2

This doesn't happen if the image isn't inside a folder, if the server is oC10 or if accessing details through the 3 dots menu on the file list.

### Expected behaviour
Details show normally.

https://github.com/owncloud/android/assets/49329895/cc9a736b-724d-4efa-952b-c67fc7ed7ce2

 
### Steps to reproduce
1. Log into oCIS demo server
2. Create a folder and upload an image inside it
3. Open the image, tap the 3 dots on the top right then tap Details

Can this problem be reproduced with the official owncloud server? 
(url: https://demo.owncloud.org, user: test, password: test)
On the oCIS demo server.

### Environment data
Android version: 13

Device model: Samsung Galaxy M52 5G (SM-M526B/DS)

Stock or customized system: Stock

ownCloud app version: 4.1.1 (cde9bb841)

ownCloud server version: Whatever the official server is using at this time

#### ownCloud log (data/owncloud.log)
[owncloud.2024-01-22.log](https://github.com/owncloud/android/files/14004551/owncloud.2024-01-22.log)

**Comment by jesmrec** [comment]
This problem is already fixed for the incoming 4.2 release.

Anyway, thanks for reporting.

**Comment by JuancaG05** [comment]
Hi @000yesnt! Thanks for opening a issue!

That's right, we currently have that bug in the stable version (the one in Play Store), but as @jesmrec said, it was already solved and the incoming 4.2.0 version will come with a fix (releasing in the next weeks) 😎. Or you can also install the `master` branch manually in your device and get the fix right now. You can check the original issue here:

- https://github.com/owncloud/android/issues/4188

Closing this issue then. If you have any other problem don't hesitate opening a new one! 🍻

**Comment by michaelstingl** [comment]
You can also test with the 4.2 public beta:
- https://owncloud.com/beta-testing/#android
