### ISSUE TITLE
implement  Android Backup Service so that you can have own backups of apps settings

### ISSUE THREAD

**Issue by gdamjan** [owncloud/android#43]
http://developer.android.com/guide/topics/data/backup.html#BackupKey

**Comment by HAS-BANNED-YOU** [comment]
**Of course** this is possible. But what do you expect from PHP *and* ”cloud” ”developers”? lol.

A proper solution would be, to use **rsync** over **sshfs**. A Linux/BSD server will usually have those tools pre-installed or very much readily available. Android has rsync apps in the app store, and they should be able to use secure connections, and preferably even have an automatic schedule. Problem solved.
If you use a dynamic DNS service (like freedns.afraid.org), and make sure your client checks your server’s certificate, you can even have the server in your personal home, and still do it when you’re far away from said home.
