### ISSUE TITLE
[BUG] Lens icon in folder picker

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4311]
### Steps to reproduce

1.  In a oCIS account, select any item and select `Copy`

1. Open a 3rd party app and share with oCIS account with spaces

1. Open Settings > Auto Uploads > Picture/Video uploads path

### Actual behaviour

All of those options shows the list of spaces including the lens icon

![Screenshot 2024-02-13 at 13 52 21](https://github.com/owncloud/android/assets/14894746/c2dbbefa-9710-42ca-8c29-ac4f631f5ac5)

### Expected behaviour

Lens icon hidden till https://github.com/owncloud/android/issues/3865 is implemented.
 
Pixel2 Android11
`v4.2.0`

**Comment by Aditya13s** [comment]
can i start working on it? @jesmrec

**Comment by JuancaG05** [comment]
Hi @Aditya13s! Sure! Go for it 🚀

**Comment by jesmrec** [comment]
> can i start working on it? @jesmrec

yes, go ahead

**Comment by Aditya13s** [comment]
@jesmrec do i need to create a new server or is there any other way to test the app?

**Comment by jesmrec** [comment]
server [ocis.owncloud.works](https://ocis.owncloud.works) is always available. You can use it

**Comment by JuancaG05** [comment]
Hi @Aditya13s! It's been a while since you don't reply, so we've assigned this issue to other person in the team as we want to include it in the next release. In any case, feel free to take any other issue that is not assigned! 😃🍻
