### ISSUE TITLE
[a11y] 11.1.3.1d Info and relationships (form elements)

### ISSUE THREAD

**Issue by tschiebel** [owncloud/android#4363]
audit: https://infinite.owncloud.com/s/QtwuiGHikwFjozV

https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf
https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de

### Edit shared link

- [x] Neither the input field nor the two switches are programmatically linked to the corresponding labels.
linked to the corresponding labels. When operating with swipe gestures
and activated screen reader, form elements and labels should ideally only
should ideally only represent one focus point. The screen reader would then
automatically read out the associated caption when the form element is focused
which should either be highlighted or linked.

**Comment by jesmrec** [comment]
- Check first if XML-feasible? -> may need jetpack compose. As alternative: add in alternative text in the switch, same as the label... not ideal. 

- Text field -> not feasible in XML the link name. Other option... remove label and just the text field with a hint (compose style)

"add screenshot"

**Comment by jesmrec** [comment]
Check if switches have any property to indicate a label/name. It could replace the existing label, indeed.

**Comment by Aitorbp** [comment]
> audit: https://infinite.owncloud.com/s/QtwuiGHikwFjozV
> 
> https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de
> 
> ### Edit shared link
> * [ ]  Neither the input field nor the two switches are programmatically linked to the corresponding labels.
>   linked to the corresponding labels. When operating with swipe gestures
>   and activated screen reader, form elements and labels should ideally only
>   should ideally only represent one focus point. The screen reader would then
>   automatically read out the associated caption when the form element is focused
>   which should either be highlighted or linked.

the input field and the switches have been linked to the corresponding labels.
