### ISSUE TITLE
[a11y] 11.2.1.2 No keyboard trap

### ISSUE THREAD

**Issue by tschiebel** [owncloud/android#4367]
audit: https://infinite.owncloud.com/s/QtwuiGHikwFjozV

https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf
https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de

### Personal Space and Menu

- [x] See comment on Personal Pace (test step 11.2.1.1)
https://github.com/owncloud/android/issues/4366

### Share

- [x] If you navigate forwards using the TAB key, the entire element under "Users and groups" is focused and you can no longer navigate any further. 
![image](https://github.com/owncloud/android/assets/132444655/79c27a15-026f-4f1a-bb76-d965d95c3266)

**Comment by JuancaG05** [comment]
> - See comment on Personal Pace (test step 11.2.1.1)
https://github.com/owncloud/android/issues/4366

Solved with the new keyboard navigation model (explained in https://github.com/owncloud/android/issues/4368#issuecomment-2231256774)
