### ISSUE TITLE
[a11y] 11.3.1.1 Language of the software

### ISSUE THREAD

**Issue by tschiebel** [owncloud/android#4372]
audit: https://infinite.owncloud.com/s/QtwuiGHikwFjozV

https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf
https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de

### Personal Space, Menu, Share, Edit shared Link, Spaces, Manage Account, Image Viewer

- [x] In some cases, content on the page is not read out in German but in English, such as the
English, such as the "Personal" tab.

**Comment by jesmrec** [comment]
Check non-translatable string list. Is it OK?

**Comment by jesmrec** [comment]
Words not-translatable:

- Space
- Markdown

is this OK? @tbsbdr . Any other string to be translated in transifex, not it app itself.

**Comment by Aitorbp** [comment]
We close this issue because string is already translated.
