### ISSUE TITLE
Share link

### ISSUE THREAD

**Issue by nedimhx** [owncloud/android#440]
Hello, when I long tap on some file or folder, I get 4 selections, Share link, Rename, Remove, Details

when I click Share link on any file or folder I get this Error:
"Sorry, sharing is not enabled on your server. Please contact your administrator"

In my owncloud admin settings sharing API is enabled and I can share files trought web browser, but I need that funciton on android app too.

Regards

**Comment by davivel** [comment]
@nedimhx , thanks for your feedback about your state.

@stormbyte , thanks a lot for your deep research in this problem. It is really helpful.

We have in the backlog several improvements about the usability of the "sharing link" action, including not showing it when the server does not support it. But we don't have an estimated date to work in it.

@DPTJKKVH , @ERamseth , is this still a problem for you? Could you try to disable and then enable again the Share API in the admin settings? Thanks in advance.

**Comment by nedimhx** [comment]
After I have installed owncloud 7, problem was solved. Thats report from me :)

**Comment by DPTJKKVH** [comment]
Unfortunately I have still the problem with the app saying: "Sorry, you
have no permission to share this file." I disabled and reenabled the
share api like you suggested but no luck with that.

**Comment by tobiasKaminsky** [comment]
@DPTJKKVH I also get this message, but only if I have enabled "require password"

**Comment by DPTJKKVH** [comment]
Actually the root of this bug has been identified long ago: If you enable public uploading sharing from the Android app works. I tried it myself after several reports it working and it's true. It's some problem with the sharing api checking share rules one after another and for some reason failing if public upload ist set to false.

I don't know why core doesn't fix it. :\

**Comment by davivel** [comment]
A fix for this bug will be available with next release of the OC app, version 1.7.1. There is no estimation time for the release, but should not take to long.

If the problem persists or reappears, please, reopen.
