### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by jayok1234** [owncloud/android#4424]
### Actual behaviour
My device is suddenly not receiving calls or text to my apps and Google number. I'm trying to confirm if there's clouds or something restricting. I do not appreciate this. Please assist 

### Expected behaviour
-Tell us what should happen
 
### Steps to reproduce
1. 
2. 
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by JuancaG05** [comment]
Hi @jayok1234, seems this issue has nothing to do with the ownCloud Android app, so closing this. If you think it could be related with our app, just open a new issue giving a more detailed description on how ownCloud affects or is affected by your problem, and set a descriptive title 👍
