### ISSUE TITLE
[BUG] "Remove local storage" observer is not working properly

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4427]
### Actual behaviour
Currently, when getting to the "Remove local storage" dialog through the "Manage accounts" dialog, the "Clean data" button has the correct effect but we can't see the loading indicator while it is being executed, as we specified on the code.

### Expected behaviour
When the work of removing the local storage of an account is being executed, show the loading indicator until it is finished.
 
### Steps to reproduce
1. Press the avatar to get to the "Manage accounts" dialog
2. Press the broom icon of one of the accounts there
3. Press "Clean data"

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
Yes, server doesn't mind in this case

### Environment data
Android version: 9

Device model: Samsung Galaxy S9

Stock or customized system: Stock

ownCloud app version: 4.2.2 (`8ec7a7009`)

ownCloud server version: Doesn't mind

### Additional context
All of this should happen in the `subscribeToViewModels` function inside `ManageAccountsDialogFragment`, but it seems that the `event` that arrives here is always null. We need to check why `cleanAccountLocalStorageFlow` is not updated properly (maybe threads issue), and if `MutableStateFlow<Event<UIResult<Unit>>?>` is the suitable type for this Flow.

**Comment by lakshay6907** [comment]
Can I get the credentials for login?

**Comment by JuancaG05** [comment]
Hi @lakshay6907!
The demo server is [demo.owncloud.com](https://demo.owncloud.com) and as you can see there, test credentials are:
User: `katherine`
Password: `gemini`

But this issue needs to be tested first, it's possible that it's already solved 😬. Let me check it and I'll post here ASAP 👍

**Comment by lakshay6907** [comment]
Okay, let me know. In the meantime, I will search for some other issues.

**Comment by jesmrec** [comment]
After releasing 4.3.0 and fixing some bugs, this is OK:

https://github.com/user-attachments/assets/00f8c2ac-d2b7-4def-9be6-e3b983905d34

So, closing... 

feel free to reopen if you reproduce it again.
