### ISSUE TITLE
[BUG] Shares in non-root are not displayed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4432]
### Steps to reproduce

1. In any item that is not in root folder, create a public link 

### Actual behaviour

Item is not listed in the shares view. By closing the shares view and opening again, it is listed

https://github.com/owncloud/android/assets/14894746/aca5f28f-b653-44fc-a9e5-234dde27bed1

### Expected behaviour

Item is listed just after being created.

NOTE: same problem with edition, and with "share with users and groups"

Could be related: https://github.com/owncloud/android/issues/3016

Pixel 2, Android 11

**Comment by parneet-guraya** [comment]
Can I work on it :hand:

**Comment by JuancaG05** [comment]
Hi @parneet-guraya! 👋  Nice to see you again!

Of course! Go for it 🚀

**Comment by parneet-guraya** [comment]
Hi @JuancaG05 I pushed the PR  #4435 have a look.

**Comment by JuancaG05** [comment]
Hi @parneet-guraya! Cool! I'll have a look whenever I can, since right now we have other priorities, but I hope I can do it ASAP 😀
