### ISSUE TITLE
[TECHNICAL] Bump target SDK to Android 14

### ISSUE THREAD

**Issue by JuancaG05** [owncloud/android#4434]
We need to update our target SDK to Android 14 (API 34) before **August 31 2024**.

Source: https://support.google.com/googleplay/android-developer/answer/11926878

Android 14 overview: https://developer.android.com/about/versions/14

Behavior changes for all apps: https://developer.android.com/about/versions/14/behavior-changes-all
Behavior changes for apps targeting Android 14 or higher: https://developer.android.com/about/versions/14/behavior-changes-14

**Comment by Aitorbp** [comment]
This issue will be resolved in the [[RELEASE] 4.3.1](https://github.com/owncloud/android/pull/4440)
