### ISSUE TITLE
[BUG] List filtering not working after rotating device

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4441]
### Steps to reproduce

1. Open list of files  in portrait orientation
2. Rotate device to landscape
3. Click on lens icon
4. Type something to filter the list

### Actual behaviour

Filter does not work. When rotating the device again, filter does not work either. Required to kill the app an reopening to make it come to life again.

### Expected behaviour
Filter works after  (and before) rotating device

Pixel 2, Android 11
v4.3.0

**Comment by AwaisKhan128** [comment]
Is there someone already working on this bug? or may I start contributing into it?

**Comment by jesmrec** [comment]
@AwaisKhan128 go ahead!!

Take a look to our [CONTRIBUTING](https://github.com/owncloud/android/blob/master/CONTRIBUTING.md) file, where you'll find guidelines about our development process (branch names, commit names...), so that your contribution will be aligned with the product itself.

Let us know any question or help you need!

**Comment by jesmrec** [comment]
@AwaisKhan128 did you take a look? something we can help you?

**Comment by jesmrec** [comment]
> Actually, I did try. First of all, gradle build failed due to its not recognizing the kotlin syntax in the gradle script.
Well, definitely, I will start over again on the weekend because, due to full-time commitment, I am unable to spare some time. @jesmrec

No worries, take your time! just for you to know that we are happy to help.

**Comment by AwaisKhan128** [comment]
@jesmrec Could you tell me which server url used to continue in app?

**Comment by jesmrec** [comment]
> @jesmrec Could you tell me which server url used to continue in app?

You can use the production one: https://ocis.ocis.production.owncloud.works/

or the rolling one (latest master): https://ocis.ocis.master.owncloud.works/

with credentials: katherine/gemini

**Comment by AwaisKhan128** [comment]
> > @jesmrec Could you tell me which server url used to continue in app?
> 
> You can use the production one: https://ocis.ocis.production.owncloud.works/
> 
> or the rolling one (latest master): https://ocis.ocis.master.owncloud.works/
> 
> with credentials: katherine/gemini

Thanks. I do have a look on it

**Comment by AwaisKhan128** [comment]
Issue fixed. Soon creating a PR.
