### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by STUQUIENG** [owncloud/android#4453]
Good afternoon,

Our owncloud account is not working. How do we regain access?

Yours sincerely

Can this problem be reproduced with the official owncloud server?
(url: https://ocis.ocis.master.owncloud.works, user: einstein, password: relativity)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Please, contact your server admin to regain access to your server. Nothing to do with Android app. Closing.
