### ISSUE TITLE
[FEATURE REQUEST] Add text labels to bottom nav bar

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/android#4484]
**Problem**
Icons without text labels can be unclear. see also https://www.nngroup.com/articles/icon-usability/
(I suspect especially the `Spaces` and `Shares` icon to be not 100% at first glance)

**Proposed solution**
- Add text labels to the bottom nav bar
- Add active state (eg. "icon background pill")
- tbd: in order to reduce noise, we could discuss to remove a navitem eg. the `offline` item - to be discussed

![android bottom nav bar](https://github.com/user-attachments/assets/08eab73e-9030-4fc6-b4ab-c5ae1c8f8432)
 
@JuancaG05  @jesmrec would you say that the proposal is an improvement compared to the current implementation?

**Comment by JuancaG05** [comment]
Hi @tbsbdr! Cool! Yes, this could be a nice improvement. We'd follow Material Design guidelines by adding the labels (https://m3.material.io/components/navigation-bar/guidelines#be759d91-d920-4779-9856-44869ad25091) and the active indicator (https://m3.material.io/components/navigation-bar/guidelines#935d4e62-b4e8-4d5e-8b87-6a39ec479c85), so it's a big yes from my side 💯
