### ISSUE TITLE
[BUG] After upgrade to 4.4.0 cannot change URL and username on login screen

### ISSUE THREAD

**Issue by rterenche** [owncloud/android#4493]
### Actual behaviour
-Tell us what happens
The Android app has been updated automatically by the Play Store to 4.4.0. At that moment there is no way to change the values already entered in the fileds for URL and username. The password field seems to be working fine.
### Expected behaviour
-Tell us what should happen
As a user, I should be able to change the values from URL and username fields anytime I consider it necessary.
### Steps to reproduce
1.  Install a version previous to 4.4.0 (I don't know what was the previous version I had before the upgrade)
2. Successfully log in using a valid URL, username and password
3. Change the password on the server (in a later step you get an authentication error on the Android client side)
4. Upgrade to Android client to version 4.4.0
5. Start the Android client and the client will show the list of files and directories
6. The Android client will display a message like Authentication Failure (don't know the exact wording in English as my app is in a different language). The message is at the bottom of the screen on top of the button bar containing Files, Links, Upload and Offline icons (again, wording is extrapolated from my own language).  
7. Press on the Login link found on the message above.
8. The login screen is displayed.
9. Here URL, Username and password fields are prefilled with the values from step 2.
10. Try to change URL and username and the fields don't accept any input. Password is the only field that can be modified.

Can this problem be reproduced with the official owncloud server?
(url: https://ocis.ocis.master.owncloud.works, user: einstein, password: relativity)
As, mentioned above, URL and user cannot be changed so there is no way for me to try the official owncloud server.

### Environment data
Android version:
14
Device model: 
Samsung Galaxy S23
Stock or customized system:
Stock
ownCloud app version:
4.4.0
ownCloud server version:
10.15.0.2
#### Web server error log
``` I doubt is relevant in anyway, considering the nature of the bug.
Insert your webserver log here
``` I doubt is relevant in anyway, considering the nature of the bug.

#### ownCloud log (data/owncloud.log)
``` I doubt is relevant in anyway, considering the nature of the bug. 
Insert your ownCloud log here
``` I doubt is relevant in anyway, considering the nature of the bug.

**Comment by jesmrec** [comment]
This is the expected behaviour. You are just allowed to enter a new password. The account is defined as server-username pair, so, same account could be re-authenticated with the new password but server and username are not changeable. You could add another account to other server or to the same but with a different username.

**Comment by rterenche** [comment]
Thanks for the quick response, Jesus!
I understand. So for the username it makes sense since you are not allowed to change the username on the server, either. 

But OwnCloud offers the possibility to install the server on premise, privately.  Then it makes sense to allow to change the URL. in case I want to move the server instance to a different URL for various reasons. Then I don't see why I should create a new account on the client...

But this is more of a philosophical matter than a bug. So closing it. 
Thanks again!
