### ISSUE TITLE
[BUG] Version 4.4.0 kills text notes both in the cloud and locally !danger of data loss!

### ISSUE THREAD

**Issue by hman2** [owncloud/android#4503]
### Actual behaviour
- After saving an edit to a text file, the file gets truncated to 0 bytes length. The file in question is important, so it is marked "available offline". At first I thought it would be due to bad cell phone receiption, but I can reproduce connected to my WiFi and excellent receiption as well...

### Expected behaviour
- The new file version should be orderly stored in the cloud and locally.
 
### Steps to reproduce
1. Connect to the cloud (here: With 2FA), edit a note/a text file (here: with Amaze text editor)
2. Save
3. See your file gets immediately erased every time.

This did not happen with the previous versions.

There is a feature (sadly ONLY in the Web version! not in the app) to restore the file. After doing so, the app displays the original size in 3 out of 4 tries. On the 4th, the file size immediately switches back to 0 bytes, so a second restore gets necessary.

I will open a feature request to implement the versioning GUI into the app, so this kind of mis-sync could be corrected with the app itself, now it is very cumbersome: I have to go to a PC, log in to the cloud, browse to the damaged file and restore it etc...

Can this problem be reproduced with the official owncloud server?
(url: https://ocis.ocis.master.owncloud.works, user: einstein, password: relativity)
Haven't tested so far. But I can reproduce this on the server in my employer's data center (version number unknown, I must ask the admins tomorrow).

### Environment data
Android version:
10

Device model: 
Fair Phone 2 with Open OS 23.02.0-rel.0 (the latest), image fp2_sibon-userdebug 10 23.02.0-rel.0 sibon-9bba2609
Stock or customized system:
Fairphone Open OS is something you install yourself, it is a AOSP version (Android Open Source) and very reliable. It is an official (!) operating system of the manufacturer Fairphone, with full support. I have used OwnCloud with it for years without problems, also MyOwnNotes (but the latter no longer works with our new 2FA, but OwnCloud does).

ownCloud app version:
2.4.0 (latest on F-Droid)

ownCloud server version:
Unknown, must ask tomorrow

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
(I do not have access to server logs, and I doubt the admins will send me copies, but I'll ask tomorrow.

**Comment by JuancaG05** [comment]
Hi @hman2!! Thanks for opening a new issue! 🍻

This problem was already reported: https://github.com/owncloud/android/issues/4495, and we're releasing a hotfix for it in a 4.4.1 version, very likely at the beginning of next week.

Thanks for reporting anyway! 💯

**Comment by joragua** [comment]
Hello @hman2! Version 4.4.1, which includes a fix for the bug that you reported here, is already available in Play Store 😄 

Thanks a lot for your feedback! It's always useful for us 🚀
