### ISSUE TITLE
Instant Upload - Option "Upload all" (upload existing pictures / photos)

### ISSUE THREAD

**Issue by webwude** [owncloud/android#454]
Dear devs,

from my point of view the current android client already works quite well - congratulation for that :)

A very handy and convenient option of Instant Upload would be the "upload all" option, meaning to take to all existing photos (e.g. in the DCIM folder) into account and when this function is triggered, upload all of them to the "instant upload" folder of owncloud (best would be to only upload the missing one in the cloud). With this method a user could easily complete his cloud picture archieve, due to failed uploads or prior to installation of the owncloud client. 

P.S. A similar option is available with Google Plus and their instant upload funtctionality.

**Comment by sp00kie** [comment]
Can I vote for this too?

**Comment by twiztedindian** [comment]
This, in my opinion, is a major feature that is missing and needs some attention. 

I just set this up on my home server, which I might add went smooth as butter... PROPS for that!, but after setup and purchasing the app for Android I've found that the app is missing some things like mass upload of existing files or the option to upload folders.

So.. +1 vote from me...

**Comment by bonswouar** [comment]
It's been more than one year since that suggestion, are you still planning on implementing it ?

I don't really see the point of the "instant upload" functionality if you can't easily upload old (or missing) pictures (except when you have a new phone I guess).

**Comment by tobiasKaminsky** [comment]
With #1168 there will be the possibility to move the files from a folder on the device to the owncloud folder.
So this should solve this issue.

**Comment by bonswouar** [comment]
I guess it would be a good enough workaround yes, thanks @tobiasKaminsky.

**Comment by tobiasKaminsky** [comment]
#1342 and #1168 should solve this issue.
