### ISSUE TITLE
notice the support language for feedback

### ISSUE THREAD

**Issue by lub** [owncloud/android#459]
Hello together,

I just asked a question (non-english) using the feedback button and got the answer, that I'd write in English.

In my opinion the support's (main?) language should be mentioned in the app. This would save time and support expenses.

Best regards
lub

**Comment by rperezb** [comment]
well... if we´d use @jancborchardt  approach...it will take time for support and it will lead to missunderstandings, sometimes, translations are great, but, not always useful. 
Other approach is welcome

**Comment by jancborchardt** [comment]
How often did we receive non-English feedback that was unintelligble so far? If it’s not much, I’d prefer to keep it like it is now instead of outright shutting out non-English users from feedback.

For questions we really don’t understand, we could say:

> We mainly handle requests in English, other languages we put through automatic translation. We didn’t fully understand your feedback/question – it would be cool if you can write it again in English. :)

**Comment by tobiasKaminsky** [comment]
So...Nothing to code her?
Therefore closing?
@jancborchardt ?
