### ISSUE TITLE
Upload file dialog: hidden files/folders are shown first

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#460]
Currently when I want to upload a file, the dialog shows the hidden files and folders before the other ones. This is very distracting since the hidden files

Four possible solutions:
1. Don’t show hidden folders or files (I don’t think that’s good because you might want to upload them)
2. Have a switch to show hidden files (Might be good, but a bit more work and it would be a prominent switch.)
3. Sort hidden files and folders after normal files and folders (Not very elegant and just shifts the problem)
4. Sort hdiden files and folders among normal files and folders, alphabetically. Basically just omit the dot when sorting.

I think option 4 is the most elegant and easy one. What do you think @rperezb @davivel?

**Comment by tobiasKaminsky** [comment]
How does popular file browser (dolphin, gnome(?), mac, windows, ...) handle this?

**Comment by jancborchardt** [comment]
They do not show hidden files. They do have a setting for showing them, but Dropbox etc don’t do that. So the minimum fix here is to just hide hidden files.

**Comment by tobiasKaminsky** [comment]
Hm.
I think this is an additional feature (Shall I create one?). But when the files are shown, we should decide how to show them.
For me it is acceptable that they are shown first.

**Comment by jancborchardt** [comment]
Well, I think it’s a bug that hidden files are shown. ;) Having a means to show them would then be a new feature.

And if they are shown, they should be shown alphabetically in the flow. That is, the dot in front should be ignored for sorting.

**Comment by tobiasKaminsky** [comment]
Hiding hidden files should be done in every file view?
- uploader
- local file browse
- owncloud file browse

**Comment by jancborchardt** [comment]
Yes please :)

**Comment by tobiasKaminsky** [comment]
Closing in favour of
#1115 (toggle view, sort alphbetically)
#1116 (hide)
