### ISSUE TITLE
Update shares in clent

### ISSUE THREAD

**Issue by PtY1968** [owncloud/android#461]
When I share something in my Android client, then the sharing will be shown in the webapp correctly.
But, if I unshare it in the webapp, and refresh the Android client, the share still live on Android until I unshare it on the phone.
The share link is not working anymore, but the Android client shows the object as shared...

I need to log out then log in again to see the sharing correctly, the refresh is not enough.

**Comment by tobiasKaminsky** [comment]
Is this still valid?

**Comment by rullzer** [comment]
Just FYI there now is a nice webdav property to get the shares status of a file... so you can update it at the same time the file list is updated... if the property returns a 404 then you have to fall back to the old behaviour... CC: @PVince81 was that property documented already?
