### ISSUE TITLE
1.5.5 drains battery and data plan

### ISSUE THREAD

**Issue by fromCologne** [owncloud/android#462]
Problem started with second last version (1.5.4?).
Automatic ownCloud sync is activated on the smartphone. One file ist in state "keep up-to-date".
Syncing drains the battery and my data plan.

**Comment by davivel** [comment]
OK, added instant uploads as a key point for battery issues.

Thanks for the extra reports.

**Comment by tobiasKaminsky** [comment]
@davivel Is there some way how I can debug it?

@all is this issue still existing in the latest version?

**Comment by smarek** [comment]
@tobiasKaminsky from my experience it was fixed in next version (February probably)

**Comment by tobiasKaminsky** [comment]
Thank you.
So closing, please reopen or comment if still exists.
