### ISSUE TITLE
Instant upload only when charging

### ISSUE THREAD

**Issue by fduraibi** [owncloud/android#465]
I would like if there is an option for the instant upload to only upload when the phone is charging. Similar to what e.g MEGA is doing (see photo)

This saves battery when you don't have charger around. also stops it from syncing when connected to slow wifis at public places and coffee shops.

![screenshot_2014-04-14-12-42-53](https://cloud.githubusercontent.com/assets/432460/2698045/5ffed370-c3f5-11e3-974c-02cc30ebac35.png)

_______________

EDIT (July 2021):

An interesting feature to include in the app, taking advantage of the current WorkManager implementation.

Related #3315 

ACs:

- New check in Camera upload photos/videos called `Upload pictures/videos only when charging`
- If it is checked, all new stuff will be enqueued till device is charging. Proper message to show in the uploads view (`Waiting for charging` or similar) depending¿?
- If it is unchecked, nothing different will happen. Stuff will be uploaded depending other conditions but not this one
- Pictures and videos will behave separately
- It will be visible only if `Only wifi` is enabled. Otherwise, it will be hidden
- If camera upload section is switched off, check becomes disabled (same as wifi only)

(open to discussion)

**Comment by davivel** [comment]
@KurtLopes, sorry, no estimation for this.

@tobiasKaminsky, about the appropiate set of sync options, it's something that needs to be discussed in a wide scope, probably in its own issue.

**Comment by rperezb** [comment]
@jancborchardt I'd like to have your input on this one.

**Comment by MTRichards** [comment]
@jancborchardt wanted to see your view on the settings complexity vs. feature.

**Comment by tobiasKaminsky** [comment]
We are discussing it in the PR #745

**Comment by davigonz** [comment]
Changing the label from Instant uploads to Camera uploads since instant uploads feature doesn't longer exist...
