### ISSUE TITLE
Removing associated ownCloud account should cease all activity in the app

### ISSUE THREAD

**Issue by PartisanEntity** [owncloud/android#466]
**Current situation:**

*Prerequisite: have pending files that need to be uploaded to the ownCloud server. For example new images from the camera that should be automatically uploaded through InstantUpload folder.*

In Android go to Settings > Accounts > and delete the associated ownCloud account

the Android ownCloud app will continue to try to upload the files and display error messages in the notification bar (File xyz could not be uploaded to the server).

**Expected behavior:**

Delete the associated ownCloud account.

The ownCloud app will not attempt to sync, upload or download as there is no account associated.

**Comment by masensio** [comment]
We are working on cancel transferences (upload and downloads) when the associated ownCloud account is removed.

**Comment by masensio** [comment]
This fix will be available in the next version of the app.
It will be released in a short time.
