### ISSUE TITLE
Uploads view 

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#471]
AC:
- There must be a new option ~~on the action bar~~ in the navigation drawer called **Uploads** ~~should it be on the bar or under the menu botton as they are the settign or sync options?~~
- Those files that have been uploaded recently must be shown on the uploads screen
- No matter if the app is closed or the process killed, the files must be shown too
- Only the info of the active account will be shown 
- There will be 3 sections:

  + **Current**: uploads in progress,  the progress bar will be shown, and on the right the cancel button so that it will be possible to cancel the upload
   Besides, those uploads failed because of a network error will be shown too (such
as offline uploads); to distinguish these ones from those that are in
progress, a message under the file name: "waiting for server connection" will be shown instead of the progress bar.

 + **Failed uploads**: these are uploads that have failed and need the user attention
       * Credentials error: in case the password has changed, by clicking on the file, the login view will be shown so that the user can update the password and the uploads goes on
       * Folder do not exist: in case the folder where it was expected to upload the file does not exist; by clicking on this file, the folder tree will be shown so that the user can select a new destination
       * Conflict error: in the long run, by clicking on the file  it will be shown the 3 options, overwritte, rename or cancel (ftm it is still not implemented)
       * Permission error: in case the user does not have permissions to upload any file to that folder, by clicking on it, the folder tree will be shown so that a new folder may be selected

  + **Uploaded**
   Where succesful uploads will be shown
   The number of successful uploaded files shown will be limited to 30 max

   Files will be displayed deppending on its upload time, the latest the first shown.
   Besides the file name, the size, when it was uploaded (relative dates), and path will be displayed too.

**Comment by tobiasKaminsky** [comment]
ref #919

**Comment by davivel** [comment]
Reviewed acceptance criteria; not sure if all the details are still up to date. Please, @rperezb, @ggdiez, @nasli, @javiergonzper , have a look to them to compare with the iOS app.

**Comment by davivel** [comment]
Work on this issue should continue in branch ```reliable_uploads_action_uploads_view```, based on contribution #919

**Comment by davivel** [comment]
For @all interest, we are reviewing the current state of this topic. It's near to receive top priority.

**Comment by AndyScherzinger** [comment]
Nice! looking forward to furthers details and I would be more than happy to support any UI work necessary :)

**Comment by masensio** [comment]
Hi @all!
We are working for merging PR #919 into master. The first part is on ```reliable_uploads_action_uploads_view``` branch.

This is the current status of the uploads view:
Screenshot with Current and Completed Uploads:
![screenshot_2016-01-28-10-18-04](https://cloud.githubusercontent.com/assets/3862330/12640535/a882af46-c5aa-11e5-99a1-181d635935b3.png)

Screenshot with some Failed Uploads:
![screenshot_2016-01-28-10-22-57](https://cloud.githubusercontent.com/assets/3862330/12640548/baeeee10-c5aa-11e5-9607-5e2b32bd6dab.png)

I have a doubt about how to fix the failed uploads and how to launch the actions for fixing them. 
On iOS side, there is a delete option on the swipe and if you click on the item you can fix the problem.

At the moment, we have the retry option on the right, but we can't delete a failed upload if we want. 
Maybe, we need to offer the delete option in any way and the fix action too. I think there are two options for that:
- Show retry button and delete button on the right (maybe there are too much buttons)
![image](https://cloud.githubusercontent.com/assets/3862330/12640994/524e7864-c5ad-11e5-9d88-a260563b108b.png)
- Show delete button on the right and click on the item to fix and retry the upload.
But maybe the user doesn't know what need to do to fix the problem.
What do you think about that? @jancborchardt , @davivel , @rperezb, @LukeOwncloud , @AndyScherzinger , @tobiasKaminsky and anyone else that wants to give an opinion about this topic.

FYI: At the moment, in case of Credentials Error, if we click on the item the app shows the login view to introduce the new credentials, but you need to click on retry button to retry the upload.

Thanks

**Comment by rperezb** [comment]
Thanks @masensio 
I'd vote for a similar approach to the iOS app behavior, talking about those failed uploads that need the user action (credentials error: update password, folder error: select another folder...)

- If the user tab over the file name: it's shown the needed view to fix the error
- Once the error is fixed: the upload is launched, automatically

So, with this approach, it´s only needed one button: delete

**Comment by AndyScherzinger** [comment]
@masensio looks awesome!  I think it is okay to offer both actions (delete/retry) to let the user decide. But if we can implement the same behavior as being in place in iOS that woudl probably be best simply for consistency reasons and having a system behavior like "problem fixed - auto restart upload" sound like the best option :)

Things I would change from a UI perspective (probably @jancborchardt would mention them anyways :smile: ):
* The screen is basically a list so the design should match the file list (margins within the list items, not the list): divider should not have a margin/padding for left/right. This also gives you a bit more space.
* The item's icon should be aligned with the drawer icon in the action and the text with the headline (basically the list item design from the file list again)
* The progress bar uses the standard color not the theme's color definition (this needs to be handled by code for pre lollipop). Helper method to be called is here: https://github.com/owncloud/android/blob/master/src/com/owncloud/android/utils/DisplayUtils.java#L256 ```DisplayUtils.colorPreLollipopHorizontalProgressBar(ProgressBar progressBar)```
* The reload icon isn't anti-aliased, I would rather go for the standard Google Material Design one: https://github.com/google/material-design-icons/releases/tag/1.0.2b --> navigation\drawable-xxhdpi\ic_refresh_grey600_24dp.png (see also https://design.google.com/icons/#ic_refresh)

**Comment by jancborchardt** [comment]
Yeah, of course @AndyScherzinger’s UI input is correct. :)

**Comment by masensio** [comment]
Hi @all,
as conclusion:
- use the same approach as on iOS.
- some enhacements for UI.

I'll put on the list of task to complete this issue.

Thanks for your suggestions.

**Comment by joeplus** [comment]
Just a quick question:
Lets say the a user is uploading multiple files and there is on notification in the notification bar.
Will the entry be reset (disappears when the upload for one file has finished and appear again for the next file) or just refreshed (showing the overall progress for all files combined and only the file name is updated based on which file is currently uploaded)?

**Comment by tobiasKaminsky** [comment]
@joeplus I think the notification is a different issue.
But the plan should be to show only one notification with changing content. See also #1468

**Comment by AndyScherzinger** [comment]
@masensio I just committed the refresh icon work :) https://github.com/owncloud/android/commit/3fa2d292bb70139ae00d0f9f9ab7209ba381b70e

**Comment by AndyScherzinger** [comment]
@davivel @rperezb imho done by #1493 as far as I understand the requirements from the top post in this issue.

**Comment by davivel** [comment]
So true... :D

**Comment by rperezb** [comment]
:dancer:
