### ISSUE TITLE
Favorite files behavior

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#472]
Some questions about the favorite feature:

- At the moment, version 1.5.5 it is only possible to set a file as favorite from the details view of the file. Will it make sense to add this option to the long press menu as well? So that it will be possible to set the file as favorite from the file list.

- On the other hand, on the current version (1.5.5) it is only used one icon, the grey arrow, should we change it to the yellow one and the grey one? Deppending whether the file is updated or pending to be updated?

- It is possible to delete a file and it remains being a favorite file, however, we have desinged a different behavior on the iOS side, https://github.com/owncloud/ios-issues/issues/26, I guess that we will follow the same behavior, don´t we

**Comment by jab416171** [comment]
I believe this issue can be closed.

**Comment by davivel** [comment]
True, this is all done or obsolete.

Thanks, @jab416171
