### ISSUE TITLE
Animations for switching folders / folder switching should be more apparent

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#474]
Currently when switching folders, there is no animation at all, the new folder just flashes in.

This is very confusing as to what happens. Instead, there should be a left/right animation, much like on iOS. Deeper subfolders should move in from the right, and going back should move the parent folder in from the left.

cc @rperezb @davivel @masensio

**Comment by davigonz** [comment]
This will be included in 2.7.0. version as well, great job @theScrabi
