### ISSUE TITLE
Delete File on swiping ;)?

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/android#477]
Swiping over a file from left to right / right to left would be the expected behaviour.
This is wellknown from hangouts, gmail, and android native mail client since 4.4.
Ideally it would delete the file with possibility to recover (compare to the mentioned apps).
![gmail-4_2-new-features-3](https://cloud.githubusercontent.com/assets/4741199/2799928/85a39d1e-cc69-11e3-86ab-066831ebf2b9.png)
A first step could be, to just display the normal delete-dialog:
![image](https://cloud.githubusercontent.com/assets/4741199/2799918/41bf38d8-cc69-11e3-965b-f541a7ee4493.png)

**Comment by jesmrec** [comment]
will not do it
