### ISSUE TITLE
no complete sync between app and server (Database Problem)

### ISSUE THREAD

**Issue by RobTranquillo** [owncloud/android#485]
for English, pleas scroll down!

Und zwar fiel mir heute auf, das mein Handy (Galaxy S3 / CyanogenMod / Android 4.3.1) schon mindestens seit Wochen keine Textdateien zum Server synct. Nur lokal liegt immer die akuellste Version richtig vor.

Aktualisiere ich einen Dateiinhalt am Telefon erscheint zwar die
Meldung, dass die Datei erfolgreich hoch geladen wurde und auf dem Server
wird das Datum des Elternverzeichnisses aktualisiert. Aber beim öffnen
über den Browser der wird weiterhin der veraltete Textinhalt angezeigt. Ich hab
mit allen Mitteln versucht den Sync zu erzwingen. Manuell in der App das Verz und das ganze Konto, ab-/anmelden auf beiden Geräten usw.. Leider ohne erkennbaren Erfolg.

------------

The app does not sync completely textfiles with the server. If in the in the app the content of an file will be updated, the notice "file uploaded successfully" occurs and the date of the directory on the server gets the correct new update-time. But the content of the file will not be updated. I tried everything i know to force the sync. Manually in the app the folder and the whole account and to log-in/-out on the device and the browser. But nothing changes.

greetz,
Rob

**Comment by davivel** [comment]
@RobTranquillo , is this still a problem for you? Thanks in advance.

**Comment by RobTranquillo** [comment]
@davivel no, not longer. With Android 6 and the newer client everything works fine. Thx

**Comment by davivel** [comment]
Thank you for your feedback :)
