### ISSUE TITLE
Sabre_DAV_Exception_NotFound error logging in owncloud.log due to the Android client

### ISSUE THREAD

**Issue by enoch85** [owncloud/android#488]
I just confirmed that the Android client (I have 1.5.5) is somehow logging an error in the owncloud.log every time I upload a photo with the Android Client.

It also gives me a error message for folders that don´t even exist. I´m a Swedish user and the Instantupload folder in Swedish is called "DirektUppladdning" but still I get error messages for the /Instantupload folder in the log. So the Android client sometimes seems to query for the photo file in "InstantUpload" instead of "DirektUppladdning".

It´s not just pictures but also other files, like the client keep trying to sync the file that don´t exist.

I have tracked it down in a issue here: https://github.com/owncloud/core/issues/7541

**Comment by davivel** [comment]
Coming back, sorry for being so late.

@enoch85 , is this bug still alife for you? Please, let's focus this issue in your last comment; is the you pasted still appearing? :

```Debug webdav Sabre_DAV_Exception_NotFound: File with name DirektUppladdning/IMG_20140522_183252.jpg could not be located 2014-05-22T16:32:53+00:00
Debug OC\Files\Cache\Scanner !!! Path 'files/DirektUppladdning/IMG_20140522_183252.jpg' is not readable !!! 2014-05-22T16:32:53+00:00 ```


@Happyfeet01 , what do you exactly mean by

> Hello, I have the same issue.

Do you see in your server side the same log message?

**Comment by enoch85** [comment]
@davivel  Yes, that took some time ;) 

No, the error seems to be gone actually.

**Comment by enoch85** [comment]
Have not tested, but got the log emailed to me every day.

**Comment by enoch85** [comment]
This is gone as far as I know. Please feel free to reopen if it still exists.

**Server 8.1.1**
