### ISSUE TITLE
android client crashes when listing lots of folders

### ISSUE THREAD

**Issue by quamis** [owncloud/android#506]
I have a folder with 380 folders and 4 files. When i try to enter that folder from the mobile app, it crashes after some time, while loading.

system log at http://pastebin.com/a0AbCsuf, system info at http://pastebin.com/7ueBfLpm

**Comment by tobiasKaminsky** [comment]
Does this issue still exist?
I have a folder with 1200 images and it works fine on my nexus 4.

**Comment by tobiasKaminsky** [comment]
As there is no feedback, I am closing it.
If the problem still exists, please comment.

**Comment by quamis** [comment]
I doesn't  seem to crash on large folders. I don't have folders that large
anymore, but it works ok on folders with 100 photos
