### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Tha-Fox** [owncloud/android#509]
### Expected behaviour
I should be able to login to ownCloud using Android app

### Actual behaviour
When entering server URL, I get error "malformed server configuration"

### Steps to reproduce
1. Install ownCloud app from F-Droid
2. Enter server URL

### Environment data
Android version: 4.3 (S3), 4.1.2 (Xcover 2)

Device model: Samsung Galaxy S3 & Samsung Galaxy Xcover 2

Stock or customized system: Both stock

ownCloud app version: Both 1.5.5

ownCloud server version: 6.0.3

#### Web server error log
The only line that comes up when entering the URL in the mobile app

```
GET /status.php HTTP/1.1" 200 89 "-" "Android-ownCloud
```

#### ownCloud log (data/owncloud.log)
I have perused the whole log. Even the most recent lines are about two months old so they shouldn't have anything to do with this. I also read through all the lines from this year and none of them seemed to have any relationship with this issue.
```

```

I have two phones, Samsung Galaxy S3 with Android 4.3 and Samsung Galaxy Xcover 2 with Android 4.1.2. Both had ownCloud app installed from F-Droid and they worked. I had to reinstall Xcover and when adding URL to the app, it said there is "malformed server configuration" and I can't click "connect" as it stays greyed out. I checked that the app still works on Galaxy S3 but if I add there a new account, I get the same error. I am using self-signed certificate and I have accepted it on both devices.

Here are some details of my server:

OS: Arch Linux
Web server: nginx 1.6.0

nginx configuration:

 # owncloud (ssl/tls)
server {
  listen 443 ssl;
  ssl_certificate /etc/nginx/certs/server.crt;
  ssl_certificate_key /etc/nginx/certs/server.key;
  server_name example.com;
  root /srv/http/owncloud;
  index index.php;
  client_max_body_size 10G; # set maximum upload size
  error_page 403 = /core/templates/403.php;
  error_page 404 = /core/templates/404.php;

  # deny direct access
  location ~ ^/(data|config|\.ht|db_structure\.xml|README) {
    deny all;
  }

  # default try order
  location / {
    try_files $uri $uri/ @webdav;
  }

  location ~ ^(?<script_name>.+?\.php)(?<path_info>/.*)?$ {
                    try_files $script_name = 404;

                    include fastcgi.conf;
                    fastcgi_param PATH_INFO $path_info;
                    fastcgi_param HTTPS on;
                    fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
  }

  # owncloud WebDAV
  location @webdav {
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    #fastcgi_pass 127.0.0.1:9000; # or use php-fpm with: "unix:/var/run/php-fpm/php-fpm.sock;"
    fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param HTTPS on;
    include fastcgi_params;
  }

  # enable php
  location ~ \.php$ {
    try_files $uri = 404;
    #fastcgi_pass 127.0.0.1:9000; # or use php-fpm with: "unix:/var/run/php-fpm/php-fpm.sock;"
    fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param HTTPS on;
    include fastcgi_params;
  }
}

Desktop application has been working all the time from Linux and Windows.

While gathering this information my Galaxy S3 microphone broke. So now I don't have a phone with working configuration anymore. Any help would be appreciated! The only function that I need is to upload the photos to the ownCloud as they tend to be forgotten and they come to mind only after the phone breaks or has to be reset.

I think this issue is quite similar to this: https://github.com/owncloud/android/issues/179 The only difference seems to be that I don't get that PROPFIND line to my nginx logs.

**Comment by ip6li** [comment]
Problem occurs if server does not support weak protocols. If server allows TLSv1.2 only (which is recommended for Owncloud) this app is not able to connect. This is an security issue.

**Comment by davivel** [comment]
@ip6li , the TLS support in the app depends on your smartphone model and Android version; the app uses the SSL implementation in the device, not its own. In general, devices with Android 4.1 or later should support TLS 1.2 according to http://developer.android.com/reference/javax/net/ssl/SSLSocket.html ; but that may change depending on the manufacturer of your device (they customize the system) and the additional cryptographic options your server side requests (that may or may not be supported by the device, not matter the Android version).

In any case, this issue is not related to TLS problem, but to a specific missconfiguration on the server side. Please, search for a better issue to track the state of your problem or open a new one if needed.

@Tha-Fox , from your previous comments I guess this is not a problem for you anymore, so I'll close the issue. Please, reopen if I'm wrong.
