### ISSUE TITLE
[1.5.6] No upload of video (Samsung Note 2 and 8)

### ISSUE THREAD

**Issue by ghost** [owncloud/android#510]
Hi,

Just wanted to inform you that automatic upload of video does not work with my 2 devices running Android 4.1.2. Saw that this feature needs a compatible camera app, is there a list of camera apps that have been confirmed? I'm using the stock camera app)

#### Expected behaviour
Automatic upload of video.

#### Actual behaviour
No upload is being triggered.

#### Environment data for Samsung Galaxy Note 2

**Android version:** 4.1.2

**Device model**: Samsung Galaxy Note II

**Stock or customized system**: Stock

**ownCloud app version**: 1.5.6
<br><br>

#### Environment data for Samsung Galaxy Note 8.0

**Android version:** 4.1.2

**Device model**: Samsung Galaxy Note 8.0

**Stock or customized system**: Stock

**ownCloud app version**: 1.5.6
<br><br>
Server runs 6.0.3

**Comment by jcharaoui** [comment]
Video upload is not triggered on Cyanogenmod 10.1 and 11 M12 on a Nexus S device.

**Comment by tobiasKaminsky** [comment]
This could be solved by #1059

**Comment by jcharaoui** [comment]
Upgrading to version 1.8 fixed the problem for me on Cyanogenmod 11 M12+, video are now uploaded automatically like photos.

**Comment by enoch85** [comment]
Close?

**Comment by tobiasKaminsky** [comment]
When the problem still occurs for somebody, please comment.
