### ISSUE TITLE
[1.5.6] client ==> server updates do not work any more: a text file updated on my android is now never synchronized

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/android#513]
I have a small text on my Android (which I often update with Jota Editor), and which is flagged as "to be synchronized" with its server version.

However this automatic update mechanism (client ==> server) does not work any more in the 1.5.6 version.

What has been changed?

**Comment by davivel** [comment]
@Wikinaut , is this still a problem for you? Thanks.

**Comment by tobiasKaminsky** [comment]
Closed as no feedback.
If the problem still exists, please comment.

**Comment by Wikinaut** [comment]
ok!
