### ISSUE TITLE
301 Redirect on subdomain doesn't forward in Android App

### ISSUE THREAD

**Issue by kucksdorfs** [owncloud/android#514]
I have a generic website hosted by godaddy. From there I added a subdomain to point to an ip address such that owncloud6.mydomain.com points to https://192.168.0.1/owncloud6 (that is not the real ip address). The web browser successfully forwards (showing https://192.168.0.1/owncloud6 in the address bar).

### Expected behaviour
The client should be able to handle 301 redirects.

### Actual behaviour
The app lets me go through the authentication/authorization process. But when I get to the screen where I should see my remote files/folders I do not see anything and I get a notirication Synchronization Failed.

### Steps to reproduce
1. Create an account on your android device
2. Input a sub domain URL that forwards to the owncloud instance
3. Get an infinite spinner when trying to fetch files from owncloud.

### Environment data
Android version: 4.4

Device model: Galaxy S4 and Nexus 7(2012)

Stock or customized system: No

ownCloud app version: 1.5.6

ownCloud server version: 6.0

#Server Log

{my WAN IP address} - - [05/Jun/2014:23:11:11 +0000] "GET /owncloud6/status.php HTTP/1.1" 200 1441 "-" "Android-ownCloud"
{my WAN IP address} - "" [05/Jun/2014:23:11:12 +0000] "HEAD /owncloud6/remote.php/webdav// HTTP/1.1" 401 431 "-" "Android-ownCloud"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:16 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 998 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:16 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 19814 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:18 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 998 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorf [05/Jun/2014:23:11:25 +0000] "HEAD /owncloud6/remote.php/webdav/ HTTP/1.1" 401 644 "-" "Android-ownCloud"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:29 +0000] "HEAD /owncloud6/remote.php/webdav/ HTTP/1.1" 401 511 "-" "Android-ownCloud"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:41 +0000] "HEAD /owncloud6/remote.php/webdav/ HTTP/1.1" 200 609 "-" "Android-ownCloud"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:45 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 19814 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:46 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 998 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:46 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 19814 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:11:48 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 998 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:12:16 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 19814 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:12:16 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 2556 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"
{my WAN IP address} - kucksdorfs [05/Jun/2014:23:12:18 +0000] "PROPFIND /owncloud6/remote.php/webdav/ HTTP/1.1" 207 998 "-" "Mozilla/5.0 (Linux) mirall/1.6.0"

**Comment by davivel** [comment]
Happy to read it!

Thanks for coming to report back.
