### ISSUE TITLE
Android App on Samsung S3 (Android 4.3)

### ISSUE THREAD

**Issue by mediumbuddha** [owncloud/android#517]
Hello,

I recently downloaded the Android App and I received an error message right after entering the Server URL. The message was "Cannot authenticate against this server".

There was an update a couple days ago, which just translated the error message into German.

For info: the iOS App is running well with the same server. So I really imagine the problem is on client side. Also web login and desktop clients work fine as well.

I hope it is ok to post this (blocking) issue here, as it looks like the Xing Group is not the right place to post.

Best regards,
Matthias

**Comment by davivel** [comment]
This was fixed time ago according to contents of owncloud/core#8845 .
