### ISSUE TITLE
More HTTP BASIC auth woes

### ISSUE THREAD

**Issue by towo** [owncloud/android#519]
Hey there,

currently, when trying to log in to our OC setup with the official Android client, I get this nasty bug:

```
/AdvancedSslSocketFactory(25867): Creating SSL Socket with remote owncloud.intern.b1-systems.de:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@41eaaa80
D/AdvancedSslSocketFactory(25867):  ... with connection timeout 10000 and socket timeout 10000
I/ServerNameIndicator(25867): SNI done, hostname: owncloud.intern.b1-systems.de
D/ExistenceCheckRemoteOperation(25867): Existence check for https://owncloud.intern.b1-systems.de/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
D/AuthenticatorActivity(25867): Access failed: Operation finished with HTTP status code 401 (fail)
```

The interface itself just says "wrong password", which definitely isn't the case. (Rechecked password a lot etc.pp.)

We have made `/status.php` available without HTTP BASIC auth, but the rest is still protected.

This happens from the screen where you enter your owncloud instance address and credentials.

**Comment by davivel** [comment]
Hi, @towo. Sorry for coming back so late.

Is this still a problem for you? Did you update 'til  version 1.6.2?

Thanks.

**Comment by towo** [comment]
Sorry for the late reply, seems to be resolved with current versions.

**Comment by davivel** [comment]
NIce, thanks for the feedback!
