### ISSUE TITLE
[Feature Request] Instant Upload in Subdirectories

### ISSUE THREAD

**Issue by mheindl** [owncloud/android#520]
Hey Guys, 

I was instructed to open a Ticket for my Feature Request, so here we go. 

When using the automatic Upload of Photos it's normal, that after some time there are some thousand Photos inside one Directory. This causes a Problem, when I want to enter this Directory via WebInterface or Mobile. It takes horribly long Time to load and I don't find anything. 
So, wouldn't it be nice, if I could set some kind of Folder-Pattern like Year/Month/ ? It would be less Data Usage when browsing the Directory, less timeouts and I find my Photos faster. 

Greets, 
Matthias

**Comment by tobiasKaminsky** [comment]
The instant upload directory is now chooseable.
@mheindl @jancborchardt do you think it is still necessary to implement this in a automatic way?

**Comment by tobiasKaminsky** [comment]
@jancborchardt @mheindl still valid?
If so this must be toggleable as I want to have my photos stored by year and not by year-month.

**Comment by jancborchardt** [comment]
@tobiasKaminsky can you check what others like Google Drive and Dropbox do? Just so we know what people are used to and what’s out there.

**Comment by davigonz** [comment]
Changing the label here to Camera uploads, instant uploads feature doesn't longer exist

**Comment by dolenec** [comment]
So, will this be developed?
\\MYSTATIC_FOLDER\%YearModified%\%MonthModified%
So that files (pictures) would be uploaded to folder like:
\\MYSTATIC_FOLDER\2020\01
\\MYSTATIC_FOLDER\2020\02
