### ISSUE TITLE
As an OC user I want to send text content to the ownCloud app so that new text files are created with that content

### ISSUE THREAD

**Issue by flansch** [owncloud/android#527]
### Expected behaviour
When I share a note with the ownCloud app from the Google Keep app it should be uploaded to the ownCloud datastore.

### Actual behaviour
If it's a text only note, the message _No content was received. Nothing to upload._ is shown.
If the note contains an image, I'm asked for a target folder. But after clicking _Upload_ nothing happens.

### Steps to reproduce
1. Compose a note in Google Keep.
2. Choose _Menu_ > _Share_.
3. Choose _ownCloud_ and submit using _Just once_.

### Environment data
Android version:4.4.2

Device model: Google Nexus 5

Stock or customized system: Stock

ownCloud app version: 1.5.6

ownCloud server version:6.0.2 (stable)

UPDATE by @davivel: the sequence should be valid for any Android app that sends text to the Android app; for instance, the case is the same for Evernote in issue #568

**Comment by davivel** [comment]
@strugee , totally right. This is duplicating #104. Please, @flansch, let's track the state there.

Thanks!
