### ISSUE TITLE
[1.5.7] Automatic upload over Wi-FI jumped to cellular

### ISSUE THREAD

**Issue by ghost** [owncloud/android#529]
Traveled abroad yesterday and noticed something strange with the automatic upload of pictures. My default setting is to only upload when connected to Wi-Fi. All was well until I connected my phone to the airport network that requires me too start the browser and accept the TOS. Only after that do I get a connection to the Internet.

What happened was that before I had a chance to accept the TOS, ownCloud started to try and upload 400 images (3-400MB in total) that I took during my visit. And of course the upload failed. But after accepting the TOS, the upload worked. And then it was time for me to board my flight and I switched off Wi-Fi and expected the upload to stop, but no, instead the upload jumped over to the cellular network and started to eat away my precious 20 MB/day quota when I’m abroad. Managed to switch off the cellular network and the uploads started to fail, after killing the app in the Android settings did the madness stop.

Android did notify me when I connected to the airport Wi-Fi that I needed to sign in/accept the TOS. Is it possible to get the ownCloud app to halt the upload until there actually is a working connection to the Internet and not just a connection to a local Wi-Fi/AP network? It should try to “ping” the server and see if it gets a valid response back before starting the automatic upload.

#### Expected behaviour
Upload should have stopped when the Wi-Fi connection was turned off. 
#### Actual behaviour
When Wi-Fi was turned off, the ownCloud resumed the automatic upload over the cellular network instead of just stop the upload and wait for a Wi-Fi connection.

#### Environment data for Samsung Galaxy Note 2

**Android version:** 4.1.2

**Device model**: Samsung Galaxy Note II

**Stock or customized system**: Stock

**ownCloud app version**: 1.5.7
<br><br>Server runs 6.0.3

**Comment by tobiasKaminsky** [comment]
Implemented in #1191

**Comment by davivel** [comment]
The fix has been merged and will be released with version 1.9.2.

Thanks, @tobiasKaminsky
