### ISSUE TITLE
InstantUpload Videos auto retry

### ISSUE THREAD

**Issue by onelight17** [owncloud/android#532]
Hello,

I am using 1.5.6 on Nexus 5. The auto retry for photos works fine where if a picture doesn't get uploaded the first time it tries again when it has a connection. 

However for vidoes it doesn't seem to do the same. When a video failed it never tried again.

Can you look into it? Thanks.

EDIT: Thanks for all the work! I love this app and ownCloud

**Comment by davivel** [comment]
@all, let's close this one and track the progress both for video (addition) and pictures (review) in #349 .

Thanks
