### ISSUE TITLE
Improve error message when download failed due to storage is unmounted

### ISSUE THREAD

**Issue by mrfesol** [owncloud/android#533]
Hi,

I'm new, sorry for any mistakes.

I realized that when SD Card is not mounted to device downloading any file is failed without any specific information. Should we add prompt about it or allow users to select their own path for file?

Greetings,
Tomek

**Comment by davigonz** [comment]
Hi @mrfesol, thank you for your comment. Are you having the same problem yet? We have not been able to reproduce the issue,  could you please specify your ownCloud app version, device and Android version?
Just so you know, the Android app doesn't support SD Card, it only works with internal device storage, so you probably refer to some situations in which the internal storage is unmounted.

**Comment by davigonz** [comment]
I'm going to close this issue, if you want to add something else, please reopen it
