### ISSUE TITLE
top bar menu

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#54]
There are multiple problems with the top bar menu which are all kind of related:

When you start the app or are in the base folder of your ownCloud, the top bar menu shows a slash. This is not understood by most people as »root folder«, except maybe Linux users. Especially here it seems the slash and dropdown doesn’t need to be there at all, because clicking the slash only exposes a menu with the slash being the only entry. When you’re in the root folder, the menu should simply not be there.

This brings up a general issue – the dropdown always also shows the current folder as first entry, which doesn’t make sense because you’re already in it and clicking it does nothing anyway.

Then when you are in a sub-subfolder we of course need to label the base folder as something in the dropdown. Here we should put the username of the current user

When you open a file then, suddenly the top bar says »ownCloud« and it’s not possible to get to the dropdown anymore. Instead of »ownCloud«, it should display the name of the file, as well as enable the path dropdown.

cc @davivel (btw who else is working on the app?)

UPDATE -  pending tasks:

- [ ] remove the dropdown menu
- [ ] prevent the  »ownCloud« title seems tappable (changes background color) in the root folder

**Comment by davivel** [comment]
This is extremely easy to complete. Probably all the work is to be done in ```FileDisplayActivity.java```. Ideal for newcomers.

**Comment by jancborchardt** [comment]
It seems that with the new Material design it has become more standard to have a path dropdown in the title, and the button for the lateral menu on the icon to the left of it. So we should rather update the style here to fit Material design, then we can keep the functionality.

**Comment by Kernald** [comment]
To be precise, the icon in the action bar should be gone.

**Comment by tobiasKaminsky** [comment]
Is this not something we are doing in #757?
At least there we could replace the icon with the hamburger...

**Comment by davivel** [comment]
I think there is no reason to have this still open. Let's move the stuff about the action bar to #757 as @tobiasKaminsky said.
