### ISSUE TITLE
app crashes after log in if the server version is < 4.5

### ISSUE THREAD

**Issue by techjunkie91** [owncloud/android#546]
Hi guys,

I have set up my own owncloud when I go to log in using the app. i can put my server name user name and password click log in it logs me in starts to load then crashes. I do currently not have any files on the server.  

I do only have server version 4.04 and am trying to connect with adrioid app version 1.5.7. Would that even matter?

**Comment by tobiasKaminsky** [comment]
OC Server version < 4.5 has end of life since 7/2013, therefore closing this issue.
