### ISSUE TITLE
InstantUpload - continuous retry but file exists on server

### ISSUE THREAD

**Issue by nlaplante** [owncloud/android#554]
I have a problem with one photo which always gets "Upload failed". It retries continuously. But, looking at the server, the file is there, and many other duplicates.

Let's call the file PANO_123.JPG. On the server, I have multiple copies of the file:

   * PANO_123.JPG
   * PANO_123(1).JPG
   *  PANO_123(2).JPG
   * and so on...

So, the upload is indeed successful, but for some reason the client marks it as failed and it retries later.

I have to clean the InstantUpload folder on my owncloud to prevent taking too much disk space.

**Comment by tobiasKaminsky** [comment]
@nlaplante @modstone still valid?

**Comment by modstone** [comment]
Working fine on owncloud Android app 2.0.1 and server 8.2.6
