### ISSUE TITLE
Long filenames get truncated

### ISSUE THREAD

**Issue by diggy128** [owncloud/android#559]
Hi.
Thank you for a wonderful app.
What I would like added if possible, is the ability to change font size in file lists.
The reason is simple: long filenames get truncated and thus makes it harder to know which file is which, especially in similarly named files.

Adding a "change font size" setting would allow viewing full names without eclipses.

A workaround would be to allow long names spanning multiple rows.

**Comment by rperezb** [comment]
In order to be possible to read the full name, we have though that the solution is to include the file/folder full name in the long press menu. 
The file/folder name will be the first item shown.
The font size is expected to be slightly smaller than the size use for the other options (rename, move...)

**Comment by cdamken** [comment]
@MorrisJobke @bboule @felixboehm 

Resolves-blue-ticket in which milestone?

**Comment by cdamken** [comment]
@rperezb Is this in a milestone?

**Comment by rperezb** [comment]
@cdamken this is still not planned because of that it has not a milestone.

Perhaps, @AndyScherzinger or @tobiasKaminsky may help us 

Thx

**Comment by AndyScherzinger** [comment]
@rperezb what is the proposed solution to be implemented? I am unsure which of the solutions should be implemented, probably like it has been done for ios? --> https://github.com/owncloud/ios/issues/129

**Comment by rperezb** [comment]
@AndyScherzinger yes that issue on iOS fix the same.

The use case is that in case that the file/folder name is very long, it´s truncated and sometimes, it´s difficut to distinguish between files that follow the same name pattern.

To fix it we have though about adding the full name (or at least increase noticiable the lenght of the file name shown) anyhow. The idea is to show the full name on the menu, on the iOS side the menu is shown after swipe over the file and select more and on the Android app on the long press menu. 
thx

**Comment by MorrisJobke** [comment]
> @rperezb what is the proposed solution to be implemented? I am unsure which of the solutions should be implemented, probably like it has been done for ios? --> owncloud/ios#129

![bildschirmfoto am 2015-09-07 um 09 55 10](https://cloud.githubusercontent.com/assets/245432/9711777/9a1a33ae-5546-11e5-906c-4303021002ca.png)

**Comment by AndyScherzinger** [comment]
@rperezb @davivel @jancborchardt @MorrisJobke @masensio please see PR #1141 for screenshots and implementation for Android :)

**Comment by cdamken** [comment]
> please see PR #1141 for screenshots and implementation for Android :)

Nice :+1:

**Comment by davivel** [comment]
@cdamken , this is merged, and planned for https://github.com/owncloud/android/milestones/1.8-current .

But I don't think we hit the original date. September 23rd would be more realistic. What do you think, @cmonteroluque , @MTRichards ?

**Comment by cdamken** [comment]
@davivel  Thanks a lot!, I'll tell the good news.

**Comment by diggy128** [comment]
@cdamken Good news, travel fast.
@AndyScherzinger Thanks again.

**Comment by AndyScherzinger** [comment]
Should we close the issue then?

**Comment by masensio** [comment]
Yes, we should close this issue. 
This feature will be availabel in the next release 1.8.0

**Comment by cdamken** [comment]
Yeah!!
