### ISSUE TITLE
Missing a handle on the scrollbar in the upload dialog

### ISSUE THREAD

**Issue by flansch** [owncloud/android#565]
I've got more than 1000 pictures in my camera folder of which I regularly want to upload a few to the cloud. New images are near the end of the list and scrolling to the bottom is a hassle because the scrollbar doesn't have a handle that can be dragged down. I attached an example from the app ES File Explorer that allows fast scrolling:
![_scrollbaresfileexplorer](https://cloud.githubusercontent.com/assets/3717998/3642943/f39a7018-10ca-11e4-9fae-796739ffe149.png)
![_scrollbarowncloud](https://cloud.githubusercontent.com/assets/3717998/3642942/f3995084-10ca-11e4-9fab-f075edc971c8.png)

**Comment by tobiasKaminsky** [comment]
cross ref: #1036

**Comment by jesmrec** [comment]
Now, using native picker to select stuff to upload. So, nothing to implement.
