### ISSUE TITLE
Display "secure connection" when HTTPS server redirects to HTTP

### ISSUE THREAD

**Issue by nerdoc** [owncloud/android#569]
### Expected behaviour
When I connect to an unsecured (HTTP) owncloud server, the app should net tell me that there is a secure connection.

### Actual behaviour
I have bought NO (!) SSL certificate on my account at All-inkl.com, but when I enter the server & credentials into the owncloud android app (without http(s), the app figures this out autimatically, the app asks me that the certificate cannot be trusted, because of a not-fitting cert. If I accept this, the app tells me that I now have a secure connection.

### Steps to reproduce
I have added a test user so that you can test your connection.
1. open the android app and add a new owncloud account, use <removed> as server. After entering the server, (before username/pw) the app directly tries to connect to this server.
2. The app tells you that there is a wrong certificate (it is using the generic cert of All-inkl for *.kasserver.com - this seems to be weird routing, but anyway - accept the certificate.
I think that all-inkl then redirects you to the HTTP version of the site silently.
3. The OC app tells you now that there is a secure connection, which is frankly impossible.

Just try <removed URL> in your browser, you get the same issue with the cert, if you accept it, you end with http instead of https.
So finally I think the OC app can be tricked into telling me there is a secure connection when there is none.
What astouns me are the logs of "adb logcat" (below).

Actually, the connection and sync works. If you want I can give you a test account on my server.
I think the logs only write out cached URLs as well, and the app, once told that there is HTTPS available, never checks again that the *real* connection (after redirect?) is *really* HTTPS.

### Environment data
Android version: 4.4.4
Device model: Samsung Galaxy S2 (i9100)
Stock or customized system: actual omniROM
ownCloud app version: 1.5.7
ownCloud server version: 7.0.0
### Logs
```
I/ServerNameIndicator( 2954): SNI done, hostname: <removed>
I/GetRemoteStatusOperation( 2954): Connection check at <removed>: Operation finished with HTTP status code -1 (success)
D/GetServerInfoOperation( 2954): Trying empty authorization to detect authentication method
D/RemoteOperationResult( 2954): RemoteOperationResult has processed UNHANDLED_HTTP_CODE: 301
D/ExistenceCheckRemoteOperation( 2954): Existence check for <removed> targeting for  existence finished with HTTP status 301(FAIL)
D/ExistenceCheckRemoteOperation( 2954): Existence check for <removed> targeting for  existence finished with HTTP status 401(FAIL)
D/DetectAuthenticationMethodOperation( 2954): Authentication method found: BASIC_HTTP_AUTH
D/OperationsService( 2954): Called 1 listeners
```
#### ownCloud log (data/owncloud.log)
```
could not find that file...
```

**Comment by davivel** [comment]
This was fixed with version 1.6.0. If I'm wrong, please, reopen.
