### ISSUE TITLE
connection being reset by app

### ISSUE THREAD

**Issue by CoolCold** [owncloud/android#571]
I believe there is bug in application somewhere - while large file being uploaded (let's say 90MB) there are random glitches.

I've tryed the same file several times and as result I upload stalled on 24%, 29%, 36%.
One of the series inside nginx access logs:
89.179.240.194 - - [27/Jul/2014:02:19:12 +0400] "HEAD /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4 HTTP/1.1" 404 0 "-" "Android-ownCloud" "owncloud.coolcold.org"
89.179.240.194 - - [27/Jul/2014:02:19:34 +0400] "PUT /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4-chunking-2768-92-0 HTTP/1.1" 201 0 "-" "Android-ownCloud" "owncloud.coolcold.org"
89.179.240.194 - - [27/Jul/2014:02:19:39 +0400] "PUT /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4-chunking-2768-92-1 HTTP/1.1" 201 0 "-" "Android-ownCloud" "owncloud.coolcold.org"
89.179.240.194 - - [27/Jul/2014:02:19:44 +0400] "PUT /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4-chunking-2768-92-2 HTTP/1.1" 201 0 "-" "Android-ownCloud" "owncloud.coolcold.org"
89.179.240.194 - - [27/Jul/2014:02:19:48 +0400] "PUT /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4-chunking-2768-92-3 HTTP/1.1" 201 0 "-" "Android-ownCloud" "owncloud.coolcold.org"
89.179.240.194 - - [27/Jul/2014:02:19:50 +0400] "PUT /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4-chunking-2768-92-4 HTTP/1.1" 400 0 "-" "Android-ownCloud" "owncloud.coolcold.org"

so as you can see there are 201, 201... and then 400 (bad request) code. Error log with debug enabled shows

2014/07/27 02:05:24 [debug] 12982#0: *3610783 event timer: 13, old: 1958078187, new: 1958078332
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http request empty handler
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http read client request body
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_read: -1
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_get_error: 2
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body recv -2
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body rest 98304
2014/07/27 02:05:24 [debug] 12982#0: *3610783 event timer: 13, old: 1958078187, new: 1958078332
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http request empty handler
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http read client request body
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_read: 4096
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_read: -1
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_get_error: 2
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body recv 4096
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body rest 94208
2014/07/27 02:05:24 [debug] 12982#0: *3610783 event timer: 13, old: 1958078187, new: 1958078333
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http request empty handler
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http read client request body
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_read: -1
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_get_error: 2
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body recv -2
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body rest 94208
2014/07/27 02:05:24 [debug] 12982#0: *3610783 event timer: 13, old: 1958078187, new: 1958078359
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http request empty handler
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http read client request body
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_read: -1
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_get_error: 2
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body recv -2
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body rest 94208
2014/07/27 02:05:24 [debug] 12982#0: *3610783 event timer: 13, old: 1958078187, new: 1958078360
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http request empty handler
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http run request: "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http read client request body
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_read: 0
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_get_error: 5
2014/07/27 02:05:24 [debug] 12982#0: *3610783 peer shutdown SSL cleanly
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http client request body recv 0
2014/07/27 02:05:24 [info] 12982#0: *3610783 client closed prematurely connection, client: 89.179.240.194, server: owncloud.coolcold.org, request: "PUT /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4-chunking-5014-92-32 HTTP/1.1", host: "owncloud.coolcold.org"
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http finalize request: 400, "/owncloud/remote.php/webdav/pics/hudzon bar 2014.07.25/20140726_025903.mp4-chunking-5014-92-32?" 1
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http close request
2014/07/27 02:05:24 [debug] 12982#0: *3610783 http log handler
2014/07/27 02:05:24 [debug] 12982#0: *3610783 run cleanup: 089C5260
2014/07/27 02:05:24 [debug] 12982#0: *3610783 file cleanup: fd:14
2014/07/27 02:05:24 [debug] 12982#0: *3610783 free: 089E3160
2014/07/27 02:05:24 [debug] 12982#0: *3610783 free: 089C48A8, unused: 1350
2014/07/27 02:05:24 [debug] 12982#0: *3610783 close http connection: 13
2014/07/27 02:05:24 [debug] 12982#0: *3610783 SSL_shutdown: 1
2014/07/27 02:05:24 [debug] 12982#0: *3610783 event timer del: 13: 1958078187

note on 
2014/07/27 02:05:24 [info] 12982#0: *3610783 client closed prematurely connection, client: 89.179.240.194, server: owncloud.coolcold.org, request: "PUT /owncloud/remote.php/webdav/pics/hudzon%20bar%202014.07.25/20140726_025903.mp4-chunking-5014-92-32 HTTP/1.1", host: "owncloud.coolcold.org"

So I believe this is android application bug. Uploading from browser works, but I believe it's not webdav based.

App version 1.5.7, server version 7.0, android 4.4.2 on LG G2 , nginx 0.7.67 .

**Comment by davivel** [comment]
Hi, @CoolCold . Sorry for coming back so late.

Is this still a problem for you with version 1.6.2? In that case, could you check the Nginx recommended configuration in http://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html ?

Thanks in advance.

**Comment by CoolCold** [comment]
Hi, @davivel !
I've upgraded kernel, goint to test soon, but just for info - testing on windows mounts with webdav shows it works okay..

**Comment by tobiasKaminsky** [comment]
Closing as no feedback given.
If problem still exists, please comment.
