### ISSUE TITLE
Upload failed when server scanning via clamscan

### ISSUE THREAD

**Issue by Crasha** [owncloud/android#576]
Just experienced an issue with the app when an instant upload of an image (and possibly a video too) is being uploaded with Antivirus enabled on the server end of Owncloud. It appears that the upload is successful and the file is indeed uploaded, but since ClamAv (Clamscan) is scanning the file which might take a while on slow systems, the android app says it has failed. This is probably a timeout issue in my opinion.

**Comment by tobiasKaminsky** [comment]
@stixpunk @Crasha is this issue still valid?

**Comment by stixpunk** [comment]
@tobiasKaminsky from version 8 it is ok for me

**Comment by tobiasKaminsky** [comment]
So closing it.
If @Crasha experiences this issue, please comment.
