### ISSUE TITLE
Non-viewable file types

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#585]
Some simple file types are not viewable in the app – see iOS issue for more info:
https://github.com/owncloud/ios-issues/issues/68

@davivel EDITs:
- [ ] plain text documents without extension
- [ ] SVG files
- [ ] others …?

**Comment by davigonz** [comment]
We are currently using [Glide](https://github.com/bumptech/glide) library but it does not support SVG afak, I will close this, follow up https://github.com/owncloud/android/issues/1033
