### ISSUE TITLE
[Feature request] Share "ownCloud" - Remember last destination upload directory

### ISSUE THREAD

**Issue by cmotika** [owncloud/android#594]
Scenario: Being in the Android Gallery and uploading single pictures, you 1. open the image, 2. tab the image, 3. select "Share", 4. select "ownCloud", 5. navigate to the desired destination directory, and 6. select "Upload".

Problem: If you do this multiple times, you always need to navigate (5.) AGAIN to the desired directory even if you have multiple files going to the same directory (which is a very common case).

Request: Owncloud App should remember the last directory you've uploaded something in using the "Share" functionality and present this directory first (not the root directory).

**Comment by orzel** [comment]
I agree :-)

**Comment by jancborchardt** [comment]
@davivel this can’t be that difficult, right? ;) Or is it already in?

**Comment by tobiasKaminsky** [comment]
The last folder is remembered, so closing.
