### ISSUE TITLE
[Feature request]  Multiselect for Img-Gallery-Upload (Android >= 4.3)

### ISSUE THREAD

**Issue by cmotika** [owncloud/android#596]
Scenario: You have shot a lot of pictures and want to upload all or most of them at once.

When selecting UPLOAD in an ownCloud directory  the user can choose
1. Files, or
2. Content from other apps

When selecting 2. and choosing "Gallery", one cannot select multiple files for upload. This is annoying when you have shot a lot of pictures and want to upload most of them at once.
Currently you are forced to select Upload->Content from other apps->Gallery->Camera shots->Picture, for EVERY single picture. And you have to remember which picture you just uploaded and where to continue. Dropbox allows multiselection for uploading from the Gallery.

Request: It would be nice to have the possibility to select multiple files from other apps like from the Gallery.

**Comment by nacef-labidi** [comment]
FYI I have found a workaround for this usability inconvenience. One can go directly to his Gallery, long press, select as much pictures as wanted, then click on the share button and select ownCloud from the list. It will open an ownCloud window allowing you to select the destination folder. Hope this helps while we have this feature implemented into the app itself

**Comment by davivel** [comment]
This is available in the currently published version 2.0.1 of the app.

Conditions: Android 4.3 or later is required and the gallery app has to support it following official Android API. 

If you met these conditions but doesn't work for you, please, comment after me.
