### ISSUE TITLE
Stream Picture/Video/Audio instead of Downloading

### ISSUE THREAD

**Issue by owenashurst** [owncloud/android#597]
I think the App should have the ability to stream the content instead of downloading it to the device. And for those who wish to download, then there should be an option in the settings to dictate whether or not the user wants to download files to the device or stream it instead. If so, there could even be a download option when long-pressing on the content.

**Comment by kiyayi** [comment]
OwnCloud i fantastic. But am of the opinion that there should be an option in either streaming a file or downloading it first.
