### ISSUE TITLE
[Enhancement] Share with user / group

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/android#600]
Basically, the same ability to share with a user / group sans link, that the webapp has, but in the Android app. Possibly via Long press > Share with user / group > Choose user/group > choose folder to store in

**Comment by rperezb** [comment]
WIP https://github.com/owncloud/android/tree/share_with_users

**Comment by rperezb** [comment]
Just noticed that this is a duplicated of: https://github.com/owncloud/android/issues/880, let´s follow its status on that one since there are more people involved
