### ISSUE TITLE
Password stored as plain text in the "accounts.db" file

### ISSUE THREAD

**Issue by utack** [owncloud/android#605]
In the database found under "/data/system/users/0/accounts.db" the owncloud password is stored as plain text.
This means anyone with root access on the phone, probablly including closed source apps that need root, can aquire the password.
This might lead to the discussion that a rooted phone is always a risk, however it would still be nice to add an additional layer of security here.

**Comment by davivel** [comment]
Sorry, but we need to drop issues from milestone 2.4.0 to get it out next to OC 10 server.

This time we'll move topics to ```backlog``` instead of directly to next release, so that we can schedule 2.5.0 properly.

**Comment by utack** [comment]
This changed on newer android versions, accounts.db no more

**Comment by davigonz** [comment]
Hi @utack , could you detail what has it exactly changed and from which Android version? Thanks
