### ISSUE TITLE
After a manually accepted certificate on an owncloud server is updated, the android app stops communicating with the server

### ISSUE THREAD

**Issue by eriktews** [owncloud/android#609]
I am running the android app version 1.5.8. I am running an SSL-enabled owncloud server supported by a CA, that is not in the trusted CA list of my android device, so I had to manually accept the certificate in my owncloud client.

I recently updated the certificate on my server to a new certificate by the same CA. I noticed that the file listing on my android client wasn't updated anymore. When trying to manually update the list, I get a busy icon for less than a second, but my file list doesn't update. No warning message was shown in the user interface. After I set the password for this account again (which wasn't changed), I got a certificate warning message again. After having accepted the new certificate here, I could again use my owncloud account.

I assume that if the server certificate doesn't match, the connection is silently dropped and no warning is shown to the user. I suggest to show the certificate warning dialog here again instead of silently dropping the connection.

@eriktews I (@rperezb) edit your issue to have a better tracking of the scope and expectations:

STEPS:
- Having a ssl self signed cert installed on the ownCloud server
- Install the Android app and log in accepting the cert
- From the server side, change the cert
- Do any action on the Android app such as refresh

CURRENT STATUS:
- The app stop working, every request to the server fails

EXPECTED BEHAVIOUR:
- When this change is detected, we will show a similar popup to the one shown when you accept the cert for the first time
- This is detected when the current folder is refreshed, similar behavior to the case when the credentials have changed
- if any upload fails due to the change of the certificate the error shown will be: connection error

NOTE:
It has been reported on  #1420  #1463 and #1515

**Comment by malkomich** [comment]
This is currently ready for deploy in the upcoming release
