### ISSUE TITLE
"Unknown error occured ..." when trying to connect through a VPN

### ISSUE THREAD

**Issue by wattgo** [owncloud/android#612]
Hi,
My owncloud server is only reachable through a VPN.
On my phone, my VPN client is working well, and so im able to connect to my owncloud server using the standard android browser.
However when using the official owncloud client app, it fails.

I guess the app is using the default (wrong in my case) net interface.

Any ideas ?

**Comment by michaelstingl** [comment]
In version 2.9, the ownCloud Android app [switched to a new networking library](https://owncloud.org/news/android-app-release-2-9-1-usability-improvements-new-network-library/). I'd assume this issue is gone. In case this happens again, please open a new issue.  (too many things changed)
