### ISSUE TITLE
Restricted_Access app causes problems in displaying root folder

### ISSUE THREAD

**Issue by Shamim-Capgemini** [owncloud/android#617]
When the Restricted_Access app is installed and active, users that are restricted from uploading to the root folder see none of the shared folders in ownCloud 7 when using the official ownCloud mobile client. 

When using the non-official ownCloud client, restircted users are able to see the root folder with the items that have been shared with them even when the root folder is not writeable (restricted). This is the correct behavior.

**Comment by michaelstingl** [comment]
deprecated server app
