### ISSUE TITLE
Develop version: Cannot create new connection to server

### ISSUE THREAD

**Issue by ghost** [owncloud/android#621]
I just re-installed the app.

After entering the URL it said:
"Cannot authenticate against this server"
but did not ask for a password.

I tracked the problem here:

line 257 in AuthentivatorActivity.java:
boolean samlWebSsoSupported = AUTH_ON.equals(getString(R.string.auth_method_saml_web_sso));
returns true

When setting it to false, it works alright.

**Comment by brunno18** [comment]
I have a similar problem. 

The mAuthToken variable  in AuthenticatorActivity class is definied for "owncloud.password", but the authentication method identified is SAML_WEB_SSO. So the authSupported method (in line 1065) returns false, generating the message "auth_can_not_auth_against_server". 

Apparently the mAuthTokenType value is definied during startup(line 219) and is no longer modified.

When the auth_method_saml_web_sso(in steup.xml) is definied to "on", the mAuthTokenType value is definied to "owncloud.saml.web_sso.session_cookie". Thus the app shows only the server url field, and when I input the url, a webView dialog is shown, loading the page to the IDP choosing page.  But when I interact with it, it crashes and the application returns to the initial screen.
