### ISSUE TITLE
Support OTP authentication with user_otp extension installed in the OC server

### ISSUE THREAD

**Issue by goodvikings** [owncloud/android#622]
I am experiencing the issue that was reported under bug 412 (https://github.com/owncloud/android/issues/412) and although the fix is to remove the user_otp extension, I would think that enabling the use of the otp app on the android client would be preferable, for what I assume are obvious reasons. 

Cheers

Ramo

**Comment by michaelstingl** [comment]
2FA/TOTP works fine with [OAuth 2.0](https://marketplace.owncloud.com/apps/oauth2) enabled on the ownCloud server.
