### ISSUE TITLE
Unable to Share in Android

### ISSUE THREAD

**Issue by dahamsta** [owncloud/android#633]
Running 7.0.2, neither the official nor the 3rd party OwnCloud apps will allow me to share, I get *"An error occurred while trying to share this file or folder."* Didn't work in v7.0.0 either.

I had this problem before, I believe when I was trying to share using an older version that didn't support it, but I'm fully up to date now and getting frustrated. :)

Nothing in the log, even at debug level.

CentOS 6.5, Apache 2.2.15, PHP 5.5.16, MySQL 5.1.73. The handset is a Sony Xperia Z2 running 4.4.2.

**Comment by dgeo** [comment]
Reason is here: https://github.com/owncloud/core/blob/master/apps/files_sharing/api/local.php#L267
The bug is that android app should not send publicUpload parameter at all (unless willing to open a share for uploading, but it doesn't AFAIK…

**Comment by dgeo** [comment]
Maybe just remove publicUpload from blob/master/src/com/owncloud/android/operations/CreateShareOperation.java#L79 ?

**Comment by michaelstingl** [comment]
@rperezb will this be fixed with next release? /cc @MorrisJobke 

00003242

**Comment by davivel** [comment]
I can confirm now: this will be fixed in the next release, 1.7.2. Thanks for your infinite patience.

**Comment by MrFly** [comment]
Thanks for your work on this :-)

Am 18. Juni 2015 18:33:52 MESZ, schrieb "David A. Velasco" <notifications@github.com>:
>I can confirm now: this will be fixed in the next release, 1.7.2.
>Thanks for your infinite patience.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/android/issues/633#issuecomment-113211553

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by dahamsta** [comment]
Excellent, thanks. So we can just disable publicUpload then?

**Comment by masensio** [comment]
@dahamsta, this is our intention.

**Comment by dahamsta** [comment]
Excellent, thanks.

**Comment by masensio** [comment]
Hi @dahamsta, @MrFly, @michaelstingl, @dgeo, @weipah, @simonbuehler,

this is fixed in our develop branch. It would be released in the next release (1.7.2)

So, I'll close the issue.

**Comment by weipah** [comment]
@masensio thanks for the update, will test when released.

**Comment by dahamsta** [comment]
Thanks masensio.
