### ISSUE TITLE
please add sort options

### ISSUE THREAD

**Issue by ferdiga** [owncloud/android#639]
please add
sort by asc/desc
- [x] date 
- [x] name
- [x] size

example: "Sofort Upload" Immediate upload 
to see the last pic it is necessary to scroll down to the very end of a long list

**Comment by tobiasKaminsky** [comment]
@davivel Is there an issue addressing the missing server-side folder calculation?

**Comment by tobiasKaminsky** [comment]
@davivel Any update on this on the server-side?

**Comment by tobiasKaminsky** [comment]
This is done by #1655

**Comment by davivel** [comment]
Mmm, I think this should be kept open 'til the PR is merged. 

Besides, are you sure that PR is doing the job?

**Comment by tobiasKaminsky** [comment]
At least for me in beta it is working without modifying the core.

**Comment by davivel** [comment]
Yes, you are right, I was totally missing the point.

**Comment by davivel** [comment]
Size is added, will be released with version 2.2.0.

Thank to all.
