### ISSUE TITLE
Instant upload is too "instant"

### ISSUE THREAD

**Issue by fduraibi** [owncloud/android#643]
Trying to take good clear pictures of kids with phone cameras are mostly painful since they won't wait for the camera sensor to fully capture the scene so you end up with many blurry pictures that you want to delete, however, InstantUpload won't wait and will immediately upload the photo when there is a wifi connection (i have "upload on wifi only" enabled).
With videos and since they are big I will swipe to the taken video and delete it before OC finishes uploading so it will fail and the file will not be uploaded to the server (i assume and hope this is what is happening and not leaving some incomplete temp file on the server) while for photos they would finish uploading before i get to delete them.

I cannot think of a way to solve this other than adding a delay between detecting the new file and the actual upload to give the user sometime to delete the file if needed. it could be an option with fixed delay (5 seconds?) or an option with maybe a slide bar to set the delay in seconds with zero as default for no delays.

**Comment by Bugsbane** [comment]
What about syncing when the user switches apps away from the current camera app?

**Comment by jancborchardt** [comment]
@dgsiegel for reference since you always mention this to me. ;) In case you have any specific ideas on the implementation or how it could behave since it’s a tough nut to crack to balance it with the upload being perceived as instant.

**Comment by fduraibi** [comment]
@Bugsbane +1 i like that but not sure if it is possible.

There is a feature that I like to have which will solve this for me, "Upload when charging only" https://github.com/owncloud/android/issues/465

**Comment by jab416171** [comment]
An option as simple as "Only upload while charging and on wifi" would also work. There should definitely be a "Upload all pictures now (if settings allow)" button that uploads all pictures/videos that don't exist on the server already.

**Comment by Bugsbane** [comment]
@fduraibi 
> i like that but not sure if it is possible.

You can poll the camera and see if it's being used. If it is, don't upload yet. Simple.

**Comment by tobiasKaminsky** [comment]
Let us keep this as simple as possible: Just wait 10s (or maybe 30s) and then upload the file if it still exists.
All other ideas are possible but have their drawbacks. E.g. if you poll the camera: What happens when the user opens the gallery and deletes the freshly taken image? Then the image would still get uploaded, although the user does not want it.

**Comment by jancborchardt** [comment]
However, this might get us reports of »Instant upload being not instant«. ;) Maybe after all this calls for a setting?

How do Dropbox and Google Drive solve this?

**Comment by jab416171** [comment]
@jancborchardt Here's some screenshots on how Google Drive handles it:
https://github.com/owncloud/android/issues/1038#issuecomment-116303193

I believe Dropbox works like ownCloud does, uploading as soon as the picture is taken.

**Comment by tobiasKaminsky** [comment]
I also think that a "delay setting" would be the best.
Then we can fit all needs.

**Comment by jancborchardt** [comment]
I’m not sure a setting is the best call here as this is likely a case-by-case decision. Sometimes you just do one snap and want to have it instantly synced. Sometimes you do multiple ones.

Then again – when the default is »instant« and you change it to »Delay upload« with explanatory »30 seconds so you can modify pictures« (or other time frame, but we should set it fixed) – seems to be fine.

**Comment by enoch85** [comment]
@tobiasKaminsky @jancborchardt I agree that the delay option is the best solution here. 

As an addition what about making it a setting? I know that @jancborchardt aren't found of settings ;) but some users take their time to look at the pictures before deleting them, like when my wife takes selfies i.e :) And also, a setting woule make users aware of that the instant upload is delayed - no bug reports.

Setting should be:
- Instant
- 10 sec
- 1 minute

**Comment by jancborchardt** [comment]
Yeah, maybe a dropdown like that is best. What do you think @owncloud/designers @dgsiegel?

**Comment by dgsiegel** [comment]
tbh i don't even want to think about configuring such a thing. afaik you can easily check if a camera program or photo editing app is running and poll until the user exits those apps. that would probably be the time when she stopped taking/editing photos. alternatively checking for the lock screen or when the display turns off would be the poor man's solution to this.

**Comment by tobiasKaminsky** [comment]
Just checking for leaving the camera app is not enougg, I think.
At least in my case I take photos, go to gallery+ and delete the unwanted images. So with your proposed solution I still would get uploaded the wrong pictures...

But you are right that the average user does not want do configure this and therefore the settings should suit most of the user out of the box.
Therefore I think 30s is a good default setting.

**Comment by enoch85** [comment]
@dgsiegel, I have the same user case as @tobiasKaminsky - I use a different apps to remove pictures.

I still prefer a setting with at least 2 options, 30 sec, or longer. Or, is it possible to do the upload when then screen gets locked? Then you don't have to set a delay in seconds or minutes. Question remains, should there be 2 options or only one default?

I think the same as @jancborchardt when it comes to issue reports. Users will post new issues before they really understand that the pictures are not uploaded instantly, and then think that something is wrong. And also, why so "afraid" of settings? Just hide them in the settings menu?

**Comment by stefan-niedermann** [comment]
what about enabling swiping on the upload notification to cancel it?

**Comment by gallardo** [comment]
Sorry for the interruption, but I don't get why @fduraibi statement has been taken for granted:

> "*I will swipe to the taken video and delete it before OC finishes uploading so it will fail [...] I cannot think of a way to solve this other than adding a delay*"

Just out of curiosity, why cannot this problem be solved with e.g. some kind of 'validator' for the list of completed uploads that checks if files have been deleted during upload?

Disclaimer: I don't have programming experience in Android. I guess it's all about API limitations?

**Comment by fduraibi** [comment]
@gallardo big videos are not the problem since you can delete them before they are fully uploaded, yes OC will show a failed message but that is not a big deal for me. However, my problem is with photos, since they are small in size and usually get uploaded before I can delete them.

**Comment by gallardo** [comment]
@fduraibi Ah, thanks, I understand. So an alternative solution would be to have the DCIM folder synchronized? But please, happily ignore my suggestion if you wish. I'm a very inexperienced OC user yet.

**Comment by tobiasKaminsky** [comment]
@stefan-niedermann Starting the upload and force the user to manual cancelling it is nothing that is meaningful. This can be additionally to the existing uploads, but should not be the solution for this issue.

@gallardo Same here. I do not think it is user friendly to first start the upload and then just cancel it as the source file vanishes.
Synchronizing the dcim folder would result in exact the same problem: The upload would start as soon as there is a file. If the user does not want the file it still would have uploaded some parts and that is not wanted.

**Comment by gallardo** [comment]
@tobiasKaminsky sorry for the noise, but I still don't see the problem: "*it still would have uploaded some parts and that is not wanted*"...  as long as those "parts" are deleted and the remote folder is consistently sync'ed with the local, why wouldn't I want that? Personally, if uploading Wi-Fi, I don't care about data transfer, do I? Or are we talking mobile data transfers?

**Comment by tobiasKaminsky** [comment]
You cannot assume that all use the instant uploader only on wifi.
And even if all would do this, it is still not meaningful to start an upload where the user knows that he does not want to have it...

**Comment by gallardo** [comment]
@tobiasKaminsky Thanks. I see your point

**Comment by cmonteroluque** [comment]
@MTRichards we should plan a priority for this. A "quasi-instant" setting (say 30 secs delay) plus a "sync when I tell you" setting seem to deal with most issues?

**Comment by tobiasKaminsky** [comment]
@cmonteroluque and "instant" to keep the same functionality at is is now.

**Comment by Bugsbane** [comment]
You know what, thinking about how I personally would use all of these settings, I think I'd just rather have the option to only sync when plugged in to the power. This way sync will happen without me having to think about doing it manually, yet it's unlikely to ever happen while I'm taking photos. Only sync on WiFi gets close, however it falls down in the circumstances where I'm taking pictures of my kids at home.

**Comment by tobiasKaminsky** [comment]
@Bugsbane I think this is an additional option that is also useful but should not replace the options defined in this thread.
But good that you have pointed out this option, as I doubt that many users in this thread are aware of it. (I also had it nearly forgotten ;) )

**Comment by Bugsbane** [comment]
Sure. I can see that it's a different option. That said, I would have initially said that I want this feature. Through all of this discussion of how the feature would work though, I've come to realize that another feature would actually serve my needs better. This was my main point.

**Comment by enoch85** [comment]
Just an advice: https://play.google.com/store/apps/details?id=com.alensw.PicFolder&hl Supports ownCloud, and keeps the data folder in sync. I tried it the other day, and it works (have some error outputs in the log) as expected.

**Comment by cmonteroluque** [comment]
@MTRichards ping

**Comment by MTRichards** [comment]
>@MTRichards we should plan a priority for this. A "quasi-instant" setting (say 30 secs delay) plus a "sync when I tell you" setting seem to deal with most issues?

I like the concept of adding upload options. My caution is they often bite back, since setting get overly complicated for the casual user (lots above on this). @jancborchardt 's comment above, I like the dropdown option to keep it as simple as possible. As an example, I don't want a delay for my photos, so I won't set one. 

I think the default should be instant, and then the user that uses apps on their device to manage and store photos (and this user group is growing rapidly - the "involved user") is more likely to want to change the setting, which they can do once somewhere. The casual (majority) user would not want to be that involved, so I think the instant default makes sense, with an option for a 30 second delay. and then one long delay (5 min) for the video use case.

**Comment by jancborchardt** [comment]
@davivel why is this closed? Is it fixed? If so, can you link the pull request?

**Comment by davivel** [comment]
Sorry, wrong button.

**Comment by davigonz** [comment]
Since camera uploads are not instant anymore and now there's a delay of 15 minutes because some background restrictions in Android, this issue can be closed
