### ISSUE TITLE
Client does not always upload pdf files upon modification

### ISSUE THREAD

**Issue by aroquen** [owncloud/android#648]
I am using the android client (v.1.5.8 from f-droid) on a Samsung Note 8 (android v. 4.2.2) and I am trying to keep some pdf files in sync. Since I tick on the "Keep file up to date" option for every file, I expect files to automatically syncronize to the server after I add annotations or highlights, i.e. files should be uploaded soon after they are modified. However, this does not happen, not even if I force a sync tapping on "Refresh account". When I check the modification time of the pdfs using a file browser, I can see the modification time is older than the one shown in the client.

The only workaround I found is
(1) to manually force a sync by long tapping the file and then choosing "Refresh file"
or
(2) to force the sync of *another* file in the same folder as in (1), then the other files are uploaded after I modified them (this seems to work consistently, at least as far as I could test)

I don't have similar problems with other types of files, for instance text files are uploaded immediately after modification. Also there is nothing suspicious in owncloud.log on the server.

**Comment by davivel** [comment]
Do you mean without wifi, or without network at all?

**Comment by aroquen** [comment]
I only have internet connection via wifi on my tablet. Thus "without wifi" means no network at all. I still experience lack of syncronization when modifications are done while offline.

**Comment by tobiasKaminsky** [comment]
@aroquen is this issue still valid?

**Comment by aroquen** [comment]
I haven't used that app for quite a while so I can't tell. Should I experience problems again, I will report them here.

**Comment by tobiasKaminsky** [comment]
Ok. Then for now we will close it, but please feel free to reopen, if the problem occurs again.
