### ISSUE TITLE
feature request: auto-rename for Photo-upload

### ISSUE THREAD

**Issue by marlboro2k** [owncloud/android#649]
I think it would be a good improvement if automaticly uploaded photos get renamed like: yyyy_mm_dd_time or something like this.

**Comment by davivel** [comment]
After carefully considering all the points, this will not be done. Reasons are:
 - it does not add an important value with respect to sorting by date;
 - it adds complexity to the mapping between local and remote names;

What we really need is fixing the setting of modification time in server side to gran that dates match the moment the picture was taken, and not the moment is was uploaded. That's already somewhere in the repo.

Thanks everybody.
