### ISSUE TITLE
Improve upload design

### ISSUE THREAD

**Issue by strugee** [owncloud/android#665]
The UI for the upload location prompt looks like it was designed for Gingerbread-era phones. It should be redesigned with some nice animations and maybe resized so that it looks like an overlay window, not a separate app. (From a UX standpoint, this makes sense, because you are still contextually interacting with the thing you're sharing, not with ownCloud. So it makes sense to show part of the original context.)

**Comment by tobiasKaminsky** [comment]
@strugee is this still valid?

**Comment by strugee** [comment]
@tobiasKaminsky it's certainly much better. I still think the upload view should be an overlay, not a full-screen view, but I think we need @jancborchardt's opinion on that

**Comment by jancborchardt** [comment]
@strugee I totally agree and have been saying that from the start. ;) The upload view should be like 95% of width and height just to give users a sense of place, instead of replacing the view.

**Comment by AndyScherzinger** [comment]
This is a tricky one... There are two entry paths 
* via upload wihtin the oC app
* via a share with from an external app then launching the oC upload view

Besides with functionality being defined on this screen like probably sorting and grid/list view options via a menu (currently in the action bar) the screen doesn't behave like a dialog and thus shouldn't or even couldn't look like a dialog imho

**Comment by jancborchardt** [comment]
Did you check out Dropbox? At least for the upload inside the app they do it via an overlay. Not sure about upload from other apps.

**Comment by AndyScherzinger** [comment]
@jancborchardt Do you have any screenshots? Because I do have the latest version on my phone and they do the exakt oposite meaning they to fullscreen activities (!) from within the app and for external share call into dropbox... :wink:

**Comment by jancborchardt** [comment]
Huh, interesting. It has been a few weeks or months since I last tested it, strange they changed it. :O

**Comment by AndyScherzinger** [comment]
Not sure when they did, but they now also look way more material designed (same for twitter since their latest update)

**Comment by jancborchardt** [comment]
Well, time for us to pick up the pace :)
