### ISSUE TITLE
PIN prompt: Pressing back on the keyboard doesn't work very well

### ISSUE THREAD

**Issue by strugee** [owncloud/android#668]
The PIN prompt experience is not exactly great.
- [ ] Pressing back on the keyboard doesn't work very well
- [x] By tapping on an already filled out box, you can input multiple numbers into one box

~~The Android keyboard number pad (at least, the AOSP number pad) displays irrelevant characters, like ",", "-" and " ", along with done (which is irrelevant because the app is automatically unlocked when the final number is input).~~ MOVED to #830

These problems should be fixed.

**Comment by strugee** [comment]
> Number 3 cannot be resolved as this is limited to the layouts built in android.

Of course. I should have been clearer as to what I'm suggesting: we may want to implement our own number pad, without the extraneous controls. FWIW, this is what Dropbox does in their app.

**Comment by strugee** [comment]
I have the latest version from F-Droid. Number 2 seems to be fixed, but number 1 doesn't. I can file a separate issue for that, if you want.

**Comment by tobiasKaminsky** [comment]
Can you please describe what is not working on number 1?

**Comment by strugee** [comment]
Sure. If you have your PIN partially typed in, but you made a mistake, you should be able to press back and have the selection jump back a box. Instead, it does nothing.

**Comment by tobiasKaminsky** [comment]
Which device do you use? And which android version?
I have tested it with Nexus 4 and 7 (real devices) and 2.3.3 in an emulator.

**Comment by strugee** [comment]
> Which device do you use? And which android version?

I'm on a Galaxy Nexus running OmniROM (based on 4.4.4 KitKat; nightly image built 1/1/15). I have the latest version of the app installed from F-Droid (1.6.2).

**Comment by strugee** [comment]
Also, I'm running the stock AOSP keyboard shipped with OmniROM.

**Comment by tobiasKaminsky** [comment]
Can you try swiftkey for example? It is an alternate keyboard

**Comment by tobiasKaminsky** [comment]
Apparently it also does not work on my nexus 4 with AOSP keyboard...

**Comment by strugee** [comment]
> Apparently it also does not work on my nexus 4 with AOSP keyboard...

Do you still want me to reproduce with SwiftKey?

**Comment by tobiasKaminsky** [comment]
If it is no big deal for you.
This would be a second confirmation.

**Comment by strugee** [comment]
I can confirm that the app has the expected behavior with SwiftKey enabled.

**Comment by davivel** [comment]
OK, this is more than real. The method we are using to capture the press on the 'DELETE' button is totally discouraged by Google, and is not working with devices from Android 4.2 (at least) and soft keyboards following IME guidelines. 

Need to dig deeper in this, documentation exists, but it's not precisely the best documentation I read from Google...

**Comment by michaelstingl** [comment]
Will be solved with https://github.com/owncloud/android/issues/830
