### ISSUE TITLE
Show a preview of directory contents in the upload window

### ISSUE THREAD

**Issue by strugee** [owncloud/android#674]
The app should show a list of already-existing files in the upload window. This will provide additional context for where the user is in the directory hierarchy, reducing the complexity of the required mental model. It may also help the user decide if they want to upload the file or not (e.g. if they see that there will be a conflict).

I should point out that Dropbox and (IIRC) Google Drive do this.

**Comment by davivel** [comment]
Sorry, needs to wait for 1.8.1

**Comment by davivel** [comment]
With the current schedule there is no way we can have this done for https://github.com/owncloud/android/milestones/1.9-current .

Moving to next release.

cc @rperezb , @MTRichards , @cmonteroluque

**Comment by davivel** [comment]
Sorry, but this need to be delayed to next release.

**Comment by AndyScherzinger** [comment]
For documentation/referencing: implementation can be found in PR #1399

**Comment by davivel** [comment]
Ready to go on next release 1.9.2.

**Comment by rperezb** [comment]
:clap:
