### ISSUE TITLE
Save scroll position

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#677]
Having a lot of files in a folder scrolling down takes some time. It would be nice if the last scrolling position for each (or only folders with many files) would be saved and restored next time I open the folder.

**Comment by masensio** [comment]
Scroll position is saved with the PR https://github.com/owncloud/android/pull/463.
@LukeOwncloud Is this what you are asking for?

**Comment by LukeOwncloud** [comment]
Can't test right now, but judging from comments and a glimpse of the code, yes, this seems to be it.
