### ISSUE TITLE
No warning if update failed

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#688]
When opening owncloud it automatically starts updating the current folder (turning circle in actionbar). If update fails there is no warning that something went wrong.

How about updating the turning circle and showing a red cross or something instead (until re-sync)?

**Comment by davivel** [comment]
Yes, something should be shown. Just need to be sure that it's something subtle.

We need to consider that every time the user browses into a folder, a request to check if that folder changed is triggered. If the user browses fast through several folders up & down when the server is not available and we show a toast for every folder failing to be refreshed, she will eventually throw the smartphone to the toilet. Or even worse, she will uninstall ownCloud.

Maybe we could combine some error message shown not with every error, but for the first in a row refresh errors with the same cause, and combine it with a permanent badge signaling that the app is working in offline mode when that is the reason of not getting to the server.

cc @jancborchardt

**Comment by LukeOwncloud** [comment]
I have already provided a patch providing subtle feedback to the user: https://github.com/owncloud/android/pull/796

The app icon is used as online/offline status indicator. (I think it was a red cross drawn on top.)

**Comment by jesmrec** [comment]
Actually, handled in uploads view. Please, feel free to reopen if new ideas about it are incoming.
