### ISSUE TITLE
Support animated GiF-Images

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#702]
Add functionality to show animated gif files in slideshow (image preview)
___

TASKS

- [X] [GIT] Create branch gif_support.
- [x] [RESEARCH] Search a gif library. 
- [x] [DEV] Include library dependency, adding the required attributions.
- [x] [DEV] Implement GIF support.
- [X] [QA] Design test plan @jesmrec
- [X] [QA] Execute test plan @jesmrec 
- [ ] [GIT] Merge branch gif_support into master.

**Comment by tobiasKaminsky** [comment]
see #1111 "Schnappszahl " ;)

**Comment by jancborchardt** [comment]
Animated GIF support is quite a high priority! :D (Not joking)

@tobiasKaminsky @Kernald @LukeOwncloud @AndyScherzinger anyone of you want to take a stab at this, or know someone who wants to join development and would like to take this on? :)

**Comment by Kernald** [comment]
Doesn't #1111 fixes it already?

**Comment by jancborchardt** [comment]
Haha, how did I miss that? :D In that case can you folks please review #1111?

**Comment by sd1998** [comment]
@davigonz  Is this issue fixed? If not I would like to work on it.

**Comment by jesmrec** [comment]
To be included in 2.7.0
