### ISSUE TITLE
instantupload does Not really work

### ISSUE THREAD

**Issue by highcurrent** [owncloud/android#704]
My instant upload does not correct work. If i take a picture owncloud starts to upload but stops uploading. If i open the app sometimes the upload goes on or not. After 5 or 6 trys it could be finished or completly failed.
what can i do that it works correct?
now i have about 40 pictures which are not sync whith my cloud

**Comment by tobiasKaminsky** [comment]
Closing due to lack of feedback.
If problem still exists, please comment.
