### ISSUE TITLE
Show ownCloud in native Android file manager

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#709]
(Screenshot from issue #596 courtesy of @tobiasKaminsky)
![](https://cloud.githubusercontent.com/assets/5836855/4689604/ea542930-56c1-11e4-84f3-07fcd4e80f24.png)

In that list to the left, how can we make ownCloud show up there so it’s browsable? Seems we should be in there.

@davivel @tobiasKaminsky any idea?

**Comment by strugee** [comment]
Duplicate of #296

**Comment by jancborchardt** [comment]
Is it? @davivel – also when can we fix this? ;)

**Comment by davivel** [comment]
True: duplicate of #296.
