### ISSUE TITLE
Style of file/image detail download needs improvement

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#710]
Currently when you swipe through the images, you often see this ugly download view (as noted by @enoch85):
![screenshot_2014-11-06-14-07-28](https://cloud.githubusercontent.com/assets/925062/4936196/48c6cc68-65b6-11e4-938e-ab59c9741b02.png)

* [ ] the background should be black, as it is for the pictures for the rest of the background
* [x] the loading bar should have a nice native Android look
* [x] the cancel button should look better and have a native Android look
* [ ] the text »Download in progress …« should be centered and say simply »Downloading …«, and be light grey on the black background.

@kernald @lukeowncloud @tobiasKaminsky @Stoyicker anyone of you wants to take this up?

**Comment by jancborchardt** [comment]
From @tobiaskaminsky's comment in #1032:

http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

The first one "determinate"

**Comment by AndyScherzinger** [comment]
I'll cover this if you want me too :)

**Comment by AndyScherzinger** [comment]
Going in the right direction?

![screenshot_2015-07-23-15-03-21](https://cloud.githubusercontent.com/assets/1315170/8851258/a0331b64-314e-11e5-8003-5e169efc0431.png)

**Comment by jancborchardt** [comment]
@AndyScherzinger yeah, most definitely! :) For images, it should only be the downloading bar and the x, with a dark background. :)

**Comment by tobiasKaminsky** [comment]
@jancborchardt 
Why? :) I would keep the design the same, whether is is a file or an image.
And then the thumbnail could be displayed instead of the mimetype icon. (there is already a PR that is doing this for the "file detail" view).

**Comment by AndyScherzinger** [comment]
How would we proceed on this matter since my PR also contains a fix for this except for images :)

**Comment by jancborchardt** [comment]
> Why? :) I would keep the design the same, whether is is a file or an image.

Cause images never had the detail view shown, and they have a dark background when shown. When you swipe through a folder of images, the flash of bright and technical info will always look strange. A good point though is showing the thumbnail above the loading bar so it’s alread visible what will load – the rest of the info is not necessary though.

**Comment by tobiasKaminsky** [comment]
Ah. Of course you are right.
(This would slightly be outdated when #982 will be merged as then the download of the resized image should be done within a sec).

**Comment by AndyScherzinger** [comment]
@jancborchardt changed it to the dark background as discussed :)

**Comment by masensio** [comment]
Fixed in master branch. 
@AndyScherzinger thanks!!

**Comment by AndyScherzinger** [comment]
@masensio it has only been merged against develop!!!!!

**Comment by masensio** [comment]
@AndyScherzinger, master is updated also with develop!!
