### ISSUE TITLE
Unable to share file with password protection enabled

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#711]
If "enforce password protection" is enabled I cannot share a file with our app.
It fails with (owncloud.log):
{"reqId":"545b80ed4a35c","app":"OCP\\Share","message":"You need to provide a password to create a public link, only protected links are allowed","level":3,"time":"2014-11-06T14:08:45+00:00","method":"POST","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares"}

So i guess this is "just" a feature missing, right?

**Comment by masensio** [comment]
Now this feature is in our develop branch https://github.com/owncloud/android/pull/918.
Also, in a short time it will be in the next release of the app (1.7.1). :relaxed:
