### ISSUE TITLE
Same server same username

### ISSUE THREAD

**Issue by vgezer** [owncloud/android#715]
Currently we can add multiple accounts to android app, but assuming we have two instances of ownCloud as follows:

ipaddress/oc

ipaddress/owncloud

if we have the same username on both instances, it does not let us set up an account and shows a warning of "same username on same server". However, they are different instances.

It would be good if this could be enabled.

**Comment by masensio** [comment]
Hi @all,

this bug will be released in the Android ownCloud version 1.7.2
it was fixed in the PR https://github.com/owncloud/android/pull/951.

**Comment by davivel** [comment]
@Kernald, and about existing accounts, they will be migrated to the new name-scheme when the app is upgraded.
