### ISSUE TITLE
Files upload fails if Encryption App is enabled

### ISSUE THREAD

**Issue by harley0** [owncloud/android#72]
All file uploads fail if I enable the Encryption app in my owncloud instance. 

I realize that the current  Encryption app is deprecated and is scheduled to be replaced in owncloud 5, but I'm not sure what effect that should have, as the encryption is all done on the server side anyway.

EDITED by @davivel: still failing with OC6 + Encryption app

**Comment by davivel** [comment]
@Happyfeet01 , is this still failing for you now? Did you upgrade to OC7?

**Comment by davivel** [comment]
Closed due to lack of activity.
