### ISSUE TITLE
Upload from android share menu fails

### ISSUE THREAD

**Issue by lgasp** [owncloud/android#723]
I'm new to Owncloud, I looked for thi bug in the issues but didn't find it. Hope not to generate a duplicate.
When I try to upload to Owncloud a file from a different app (like Ghost commander or Download), it doesn't work, no error is generated. The correct sequence is this:
- I select the file in the other app
- I tap the share button
- I choose to share to owncloud app
- A pop up tree of the ownclud directory appears, I choose the directory where I want to upload the file
- I tap on the "upload button"
- nothing happens.
If I look in the owncloud web app, the log doesn't show anything, so I suppose is something happening in android, not regarding the server.
On the other side, uploading a file directly through the owncloud app, works.

**Comment by lgasp** [comment]
After updating from owncloud 1.6.1 to1.6.2 uploading from share menu works. Apparently the bug has been solved. Thank you

**Comment by jabarros** [comment]
Ok @Igasp,
Thanks for the update.
