### ISSUE TITLE
Automatically sync favorited file on Wifi-connection events

### ISSUE THREAD

**Issue by Faldrian** [owncloud/android#726]
### Expected behaviour
I select a file to be my "favorite" and it gets stored on my android device.
When I update the file from within android, it is updated on server (working good).
When I update the file from within the server, it is updated on the client at next Network-Connect-Event or periodically when connection exists.

### Actual behaviour
When I update the file from within the server, it is not automatically updated on the android-client (unless I open the owncloud app manually).

### Steps to reproduce
1. set file as favorite and close owncloud app
2. edit file on server
3. disconnect and reconnect Wifi

### Environment data
Android version: 4.4.4

Device model: Nexus 5

Stock or customized system: Android Stock

ownCloud app version: 1.6.1

ownCloud server version: 7.0.3

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/owncloud/android/issues/1093 because we have more info there.
