### ISSUE TITLE
Login Failed under Android 5

### ISSUE THREAD

**Issue by OliverTempel** [owncloud/android#727]
I had updated my nexus 5 to android 5 lollipop,
since this update i cannot login to my owncloud server.
Logfile says, login failed for ...

running latest app and oc version.

**Comment by davivel** [comment]
@flasheater, is this still failing for you?

**Comment by flasheater** [comment]
Still no joy ;)

```Warning	core	Login failed: 'test' (Remote IP: '109.201.154.139', X-Forwarded-For: '')```

password was _ÄÄÄ_.

Login from the web interface was succesfull.

Tested on Nexus 5 with CM12.

**Comment by LukasReschke** [comment]
@davivel How are you encoding the password? – UTF8 or some ISO stuff? – From a server PoV we expect the UTF8 encoding.

UTF8: w4TDhMOE
ISO-8859-1: xMTE

**Comment by LukasReschke** [comment]
Easy way to test the encoding: https://www.base64encode.org/

**Comment by sicjay** [comment]
same problem here, there was an offending umlaut in the password.

**Comment by pierrejochem** [comment]
We had the same problem with "Umlaute" in the Password

**Comment by tobiasKaminsky** [comment]
Then this can be closed.

**Comment by davivel** [comment]
This is not fixed, but now there is a newer issue about it in #1322. Let's track it there. Writing here to have a link to the comment from @LukasReschke
