### ISSUE TITLE
Option "Sync account" makes owncloud very slow

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#734]
When choosing "Sync account" from the drop down menu syncing makes the owncloud app respond very slow. Same is true when syncing is active under Android -> settings -> account -> owncloud (is probably just the same?)

Once I could not open a folder at all when sync was in progress (could not reproduce though). Usually switching directories is just veeery slow.

Device: Nexus 4
"develop" branch

Logcat is full of entries showing which files are updated. Like this:

    11-19 08:31:35.320: D/FileSyncAdapter(13843): Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
    11-19 08:31:35.320: D/SynchronizeFolderOperation(13843): Checking changes in [...]
    11-19 08:31:35.320: D/FileDisplayActivity(13843): Received broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
    11-19 08:31:35.320: D/OwnCloudClient #64(13843): REQUEST PROPFIND [...]
    11-19 08:31:35.590: D/FileDisplayActivity(13843): Setting progress visibility to true

**Comment by LukeOwncloud** [comment]
Cannot reproduce anymore. Closing.

**Comment by davivel** [comment]
Thanks for checking! :)
