### ISSUE TITLE
4.2.2 - looses login data / SQlite db when rebooted

### ISSUE THREAD

**Issue by cdr8H** [owncloud/android#743]
rooted ACER V370, 4.2.2 - no matter if owncloud is installed at internal or sd card memory, it looses login data / SQlite db when the device is rebooted.

Could the "Android Jellybean Workaround APK" help? If so, is there an alternate download of the apk, instead of da****d google play, available?

**Comment by davivel** [comment]
@cdr8H , is this still a problem for you? 

I see a strange point here. The bug solved by the OC JB workaround app is bound to the installation of the OC app from Play Store. Otherwise, the bug should not happen (yours could be different).

Where did you install the OC app from?

**Comment by hodyroff** [comment]
Does not seem to be an issue anymore. Closing.
