### ISSUE TITLE
Change "Remote and local" delete prompt to "On ownCloud"

### ISSUE THREAD

**Issue by strugee** [owncloud/android#748]
This dialog:

!["Cancel", "Local only", and "Remote and local" in the file deletion dialog](https://cloud.githubusercontent.com/assets/911174/5160243/4d3ce664-733b-11e4-9cac-e460a89d543a.png)

has strings that don't make sense to users. "Local only" should be replaced by "On device", and "Remote and local" should be replaced by "On ownCloud".

I'd like to try my hand at making this change myself (I've already forked the repo), but I'm not sure where it should go - on GitHub or on Transifex. I poked around in `res/` but couldn't find any resources for en-US, so I'm not sure which one is considered canonical (and also whether or not I have to invalidate previous translations or whether Transifex does that automagically).

**Comment by jab416171** [comment]
Making either of these any longer than they already are causes nasty wrapping. Do we really need the "Delete from device" option? If the user wants to delete it from the device, they can just go to the details page and uncheck "Keep this file up to date".
![device-2015-06-27-143208](https://cloud.githubusercontent.com/assets/345752/8393717/60012bfa-1cd9-11e5-98b1-65e2baf8981d.png)

**Comment by tobiasKaminsky** [comment]
The option "keep this file up to date" is syncing the content of the file in order to have always the newest version. This has nothing to do with deletion.
So we need this option.
Maybe the three options can be arranged vertical and not horizontal (although this is not common).

**Comment by jab416171** [comment]
As I mentioned in #756, if there was a distinction between a cached file and a locally stored file, we wouldn't need this option. If the user wants to clear a cached file, he would just clear the cache of the app. And if he wants to clear a locally stored file, he would uncheck "Keep file up to date".

**Comment by jancborchardt** [comment]
All three options are needed. However the only ugly wrapping is the »Cancel«, wrapping inside the word even though it could be fully shown.

**Comment by sudhirkhanger** [comment]
The dialog has already been updated. Will someone close this bug?

![4 march 2016 81319 pm ist](https://cloud.githubusercontent.com/assets/841656/13530096/a256c924-e245-11e5-9155-965c3e8260bc.png)

**Comment by jancborchardt** [comment]
Thanks for the notice @sudhirkhanger! :)
