### ISSUE TITLE
Update Description AppStore: Highlight Issue System on Github

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#753]
I have read the description of this app in the offical android app store.
There is only the forum at forum.owncloud.org mentioned.

I think there should be a link to the issue tracker system of GitHub as on Github the developer are reading it. And the text should encourage people to report issues and not just downvote it.

**Comment by malkomich** [comment]
Currently there's a link to the issue tracker in description as you said @tobiasKaminsky , so I guess we can close this old issue.

**Comment by tobiasKaminsky** [comment]
Yeah :+1:
