### ISSUE TITLE
Reliable uploads

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#762]
@davivel and @jabarros 

I finished my proposal first reliable uploads -> https://github.com/owncloud/android/tree/reliable_uploads

I find it works quite reliably. Unfortunately, the changes are substantial. Please review and add to backlog (conflicts are expected with each new commit).

Details:

I renamed FileUploader to FileUploaderService because it is now much more than a simple uploader but a real service; this should be reflected in the name, I think.

I reused the DbHandler and called it UploadDbHandler (the old name was a little misleading).

Further I replaced some Intent KEYS which where ints with enums (e.g., LocalBehaviour in FileUploadService). This avoids using untyped KEYS and will help avoiding mistakes.

OCFiles is now serializable as it is stored persistently.

ConnectivityActionReceiver is now responsible for detecting connectivity changes. It calls FileUploaderService.

Due to these changes, the branch reliable_uploads is a little bloated. But actually there is not much new there.

**Comment by vip9** [comment]
As I see, there are two problems 
1) on both, develop and reliable_uploads, the upload process sometimes returns (ssl) Socket timeout exception, but, sometimes the file is uploaded just fine (sometimes not).
The situation exists when uploading videos and also small images (~5MB), over mobile connection. 
There is no way to distinguish "real" failure other than checking in the app.
Apache access/error logs are clear and fine.
2) on reliable_uploads, the success (i suppose) notification shows and dissapeares, there's no ability to read it; the failed notification shows correctly

**Comment by LukeOwncloud** [comment]
@vip9 
1) Yes, I noticed the same problem. Also when uploading via wifi. However, the return value is provided by code from the owncloud library. Check function ```uploadFile()``` in ```FileUploadService.java```.
2) Yes, the notification have to be reworked. They are still as they were before when uploads could fail. Now it would probably better to have a single notification showing # of pending and failed uploads, as well as the status of the current upload (if any). On click, the upload list should open.

Unfortunately, I won't have time to work on this in the next couple of months for private reasons. I also would be also reluctant to invest more time if I had any, since there is hardly any feedback from the oc guys. I am beginning to wonder whether my proposal will be included/accepted/adapted at all. Small changes seem to be prioritized which will make merging of this big commit difficult.

**Comment by LukeOwncloud** [comment]
Fixed. Closing.
