### ISSUE TITLE
Fix GPU overdraw

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#764]
I noticed that there is a slight GPU overdraw in the main files view. I took this screenshot with GPU overdraw visible (from developer settings):

![screenshot_2014-11-26-19-18-52](https://cloud.githubusercontent.com/assets/2737900/5206483/2528ec90-75a2-11e4-8dca-6bcc674642b3.png)

Green indicates an overdraw of 2x (red even more). That means every pixel of this view was painted three times.

This can be improved! For more details see http://www.curious-creature.com/docs/android-performance-case-study-1.html

**Comment by jesmrec** [comment]
I will take a look

**Comment by abelgardep** [comment]
3.0 should fix the problem. The main file list has been refactored, let us know if you still reproduce it 👍
