### ISSUE TITLE
Layout for upload list (part of reliable uploads)

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#765]
As part of the reliable uploads enhancement (cf. https://github.com/owncloud/android/issues/762) I introduced a list showing all uploads (scheduled, active, done, failed_retry, failed_give_up, paused)

Currently it looks like this (just a draft):
![screenshot_2014-11-26-19-38-11](https://cloud.githubusercontent.com/assets/2737900/5207076/3740bd68-75a7-11e4-9d81-1c63b3d1b1fd.png)

Now, how should it look like? In detail,

1) What file/upload details should be visible? (currently: local path, upload state, time of upload request [missing: file size, preview icon])
2) What main menu items do we need? (currently: Clear list and retry uploads)
3) What file menu options are required? (currently none)
4) What should a click on an upload item do? (currently: if DONE: open details, if FAILED or SCHEDULED: retry)

@jancborchardt A penny for your thoughts!

**Comment by vip9** [comment]
I would also leave (or rather make) "retry all" button only. BTW, clear failed uploads seems does not work (reliable_uploads branch)

**Comment by LukeOwncloud** [comment]
@vip "Retry all" buttons are already prepared (check ```upload_list_group.xml```). "Clear failed uploads" only removes all elements from group ```FAILED UPLOADS```. Works for me. Maybe you expected it to also delete temporarily failed uploads from ```CURRENT UPLOADS```? This is not done on purpose, but it is a little confusing I admit. It'll be more intuitive if the groups buttons are used instead of the menu and item buttons (just as you suggested).
Unfortunately, I won't have time to work on this in the next couple of months for private reasons.

**Comment by enoch85** [comment]
Any new updated screenshot on this?

**Comment by Bugsbane** [comment]
Hey @LukeOwncloud 

Thanks so much for your work on this. Looking forward to using it. As a user, the only thing that's unclear to me from the last screenshot is what a recycle icon stands for in the context of already uploaded files. If it's supposed to stand for delete, then I don't understand why it doesn't use the trash can icon we use everywhere else in ownCloud, and I would expect to see here. If it's some kind of "upload again" then I would expect it to be the same "retry" icon used next to the failed uploads above.

**Comment by tobiasKaminsky** [comment]
@Bugsbane I think clicking this icon will just remove the entry from the list.

**Comment by jancborchardt** [comment]
@LukasReschke @Bugsbane @tobiasKaminsky since it’s just a history, I wouldn’t even have that icon there. As noted the icon is confusing, and the function is not really necessary anyway.

**Comment by LukasReschke** [comment]
@LukeOwncloud is not @LukasReschke :speak_no_evil:

**Comment by tobiasKaminsky** [comment]
@jancborchardt But how is the history being cleared? It cannot show all entries. Should it always show just the latest (10/20/50) entries?

**Comment by Bugsbane** [comment]
@tobiasKaminsky if it's just "remove this entry" wouldn't the X icon make more sense than "recycle" which implies turning the file into somehing new or at least retrieving it from deleted (such as the Windows file explorer recycle bin)?

**Comment by jancborchardt** [comment]
@tobiasKaminsky just show the latest 20 entries or so, and lazy load more on scrolling down. Just like the ownCloud Activity app in the web interface (or like Twitter, Facebook, etc ;).

**Comment by tobiasKaminsky** [comment]
I have never used lazy loading before, but I guess that it is possible with android.
Maybe @LukeOwncloud wants to resume his developer skills and help here?

**Comment by LukeOwncloud** [comment]
I'd say the discussion about the layout is mainly over, isn't it? For improvements like lazy loading we should open a new issue. So I better close this issue.

**Comment by davivel** [comment]
Totally right, @LukeOwncloud ; thanks for closing.
