### ISSUE TITLE
Show previews in the right pane of tablet landscape mode

### ISSUE THREAD

**Issue by strugee** [owncloud/android#771]
This screen:

![Screenshot of ownCloud app on a tablet in landscape orientation, showing a folder view with many images](https://cloud.githubusercontent.com/assets/911174/5236973/dacb4a78-7815-11e4-8e1c-d969e1133112.png)

has a lot of open space to the right. Context from other apps implies that the behavior here will be that selecting something in the left pane will open a preview on the right, but instead what happens is that the image is opened full-screen.

Instead, a preview should be shown in the right pane and if tapped, then the image should be opened full-screen as we currently do it.

**Comment by masensio** [comment]
Hi @strugee,

I think this issue is related with https://github.com/owncloud/android/issues/242, or maybe it is the same.

Please track it there.
