### ISSUE TITLE
Show avatar in account list

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/android#778]
In the account list in the setttings, to the left of each account the avatar of that account should be shown. Same for iOS.

PR: https://github.com/owncloud/android/pull/1559

cc @rperezb @tobiasKaminsky @LukeOwncloud

**Comment by tobiasKaminsky** [comment]
The problem is, that there is no public avatar route in /core as far as I know.

**Comment by tobiasKaminsky** [comment]
https://github.com/owncloud/core/issues/17305

**Comment by tobiasKaminsky** [comment]
Can be imlemented when https://github.com/owncloud/core/pull/14856 is merged.

**Comment by tobiasKaminsky** [comment]
Done by @AndyScherzinger in ...? (do not know the PR)

**Comment by rperezb** [comment]
@tobiasKaminsky i'd say that this is better to keep it open till the pr is merged
https://github.com/owncloud/android/pull/1559

**Comment by tobiasKaminsky** [comment]
ok. maybe we should have a label "PR exists" or something like to show that this is in progress?

**Comment by rperezb** [comment]
i added the pr on the issue description + to review label

let's see whether this helps, otherwise, a new label, label 🎉  ☺️

**Comment by tobiasKaminsky** [comment]
PR in issue description is a good idea to have a cross reference.
Using the 1-5... labels for PR is doubtable as this has to be kept in sync with the PR.

**Comment by rperezb** [comment]
@tobiasKaminsky yes, anyhow, both issue and pr has to be kept in sync

**Comment by davigonz** [comment]
This is already implemented, see https://github.com/owncloud/android/pull/1559
