### ISSUE TITLE
InstantUpload Path should include the account

### ISSUE THREAD

**Issue by smessmer** [owncloud/android#78]
I'm using two owncloud servers, one for business and one privately. Both are synced to my mobile phone. I'd like to use instant upload to upload my photos to the private cloud and not to the business cloud.
But if I activate the setting and I was logged in to the business cloud before, they of course are uploaded there.
So I'd like to have a setting "upload to" for instant upload. At least it should select the server, if possible it would also be nice to select the folder to upload to.

**Comment by davivel** [comment]
Mmm, I am not sure that the best option is extending the current path selector to include the account. How would we do the UI? Adding an extra input field in the dialog to select it?

We were thinking in diving the settings view in 'settings per app' and 'settings per account'. Not just for the instant upload, but first for it. That would allow the user even upload the new pictures taken to more than a single account.

@jancborchardt , your opinion here?

**Comment by jancborchardt** [comment]
What do you mean by »settings per app«? We only need to divide the settings per account really.

> That would allow the user even upload the new pictures taken to more than a single account.

That doesn’t really seem needed. At least it seems an edge case that we shouldn’t build on for now.

**Comment by davivel** [comment]
Thinking in a general sense, I consider could be features that make no sense per account; for instance, the PIN-code.

**Comment by davivel** [comment]
And sure that multiple accounts to upload pictures is a corner case, but the option should be available per-account in any case - in terms of what would be the settings layout there is no difference.

A different story would be that we'd rather prevent that more than an account may receive the pictures.

**Comment by jancborchardt** [comment]
Ah ok – you mean general settings. I was just confused by the wording. :)

**Comment by davivel** [comment]
You know, here we use to invent words if needed :D .

Maybe we could deal with this issue after the changes in #757, since layout for settings and accounts is  also involved there.

**Comment by tobiasKaminsky** [comment]
In #757 I am currently only displaying the accounts in the navigation drawer. Of course the account can be changed there. But creating, deleting is not something that should be done there, I guess.
So this will still be in Settings. Therefore, if @jancborchardt agrees, you can discuss it here and now...

**Comment by davivel** [comment]
Good point, you are right, not all the administration of accounts needs to be in the drawer.

**Comment by jancborchardt** [comment]
Yeah, we should move step by step here. Administration of accounts can stay in settings for now.

**Comment by davivel** [comment]
Duplicated in #827, let's track it there, seems there is some info.
