### ISSUE TITLE
Select/move/swich owncloud-folder

### ISSUE THREAD

**Issue by blackcrack** [owncloud/android#780]
Hi,
i have an Galaxy-tablet and there be 2 sd-cards on it and an Systempartition.
i have extern an 64Gig SD-Card on it and i want move/swich from the internal sd-card to the
external sd-card where i have easy more place, maybe it is well, if it is enable to select
the folder or the drive where should be the owncloud-folder on which sd-card or which folder
to be variable and use the best place for it :)
best regards
Blacky

**Comment by wlhoyenga** [comment]
+1
I would love this feature for the same reason -- I have either a USB or microSD slot which has much more room than what is internal to my phone and would make more sense to be able to place this folder there.

**Comment by gjanssens** [comment]
This gets my vote too !

**Comment by gjanssens** [comment]
While browsing the other issues, I found issue #10. It looks like this one is asking for the same thing.

**Comment by blackcrack** [comment]
humm, it's still open.. have they are it forgotten ? *bg*
so, may still help this issue as reminder on this point ;)
Heeey Dev's, make my day *g*

best regards
Blacky

**Comment by llucax** [comment]
Looks like a dupe of #10

**Comment by davivel** [comment]
True, this is duplicated. Please, let's track any progress in #10.
