### ISSUE TITLE
Unable to open encrypted files from Android App

### ISSUE THREAD

**Issue by ATinYGitHub** [owncloud/android#782]
After upgrading to 7.0.3, neither the official nor the 3rd party OwnCloud apps will not open files that were stored in OC before the upgrade. (e.g. txt file content show: HBEGIN:cipher:AES-256-CFB:HEND------------------) Web login works fine. 

Tried disable encryption plugin and decrypt all files, app has no problem opening the files. However, once the encryption is reactivated and files re-encrypted, files downloaded from the OC apps will not open properly.

**Comment by zisuu** [comment]
Same Problem here.

I work with ownCloud 9.0.1 and enabled encryption (OC_DEFAULT_MODULE). Since I enabled the encryption i am unable to sync Files with the Android App. Is that a Bug or do I make a mistake?

**Comment by jesmrec** [comment]
Encryption is a server feature. Nothing to do with Android.

In case of issue please open server issue  with details -> https://github.com/owncloud/core
