### ISSUE TITLE
Android-client wastes insane amounts of bandwidth and time

### ISSUE THREAD

**Issue by WereCatf** [owncloud/android#785]
On Android if I have background data sync enabled for ownCloud it periodically starts a scan to refresh stats on files, but it goes through every file, not just those that have been tagged in the client as ones that should be kept up-to-date. In addition to this, it insists on querying every single god damn file and folder individually, using enormous amounts of data. Since I have thousands of files on my ownCloud-account this takes a long, long time, it keeps the connection open for hours and it consumes several megabytes every single refresh.

It should obviously only refresh stats on the files that have been tagged, and even then, it should just send a single request to the server with all the files listed that it wants stats on and the server should just reply with a single response similarly with all the stats for the requested files.

**Comment by LukeOwncloud** [comment]
A discussing about replacing WebDAV was already going on here: https://github.com/owncloud/core/issues/12504 Bottom line there: WebDAV is good enough if used correctly.
However they did not talk about a full sync. 

I just want to point out that a core plugin could be used for speeding up a full sync.
It would provided the etags of all files and folders with a single request.
