### ISSUE TITLE
Media player: Error when clicking

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#787]
### Expected behaviour
When I click a video which is played with the movie player nothing should happen.

### Actual behaviour
Screen goes black and a popup window displays: ```Media file cannot be played with the stock media player``` (Without clicking movie plays just fine.)
After clicking OK (the only button) the screen stays black. Then back and the movie starts playing from beginning.

### Steps to reproduce
1. Click on movie file (mp4 in my case)
2. Click on playing movie

### Environment data
Android version: 4.2.2.
Device model: Nexus 4
ownCloud app version: 1.6.2 (from master branch)

**Comment by davivel** [comment]
Fixed in https://github.com/owncloud/android/pull/1269
