### ISSUE TITLE
Media player: Movie stop when turning device

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#788]
### Expected behaviour

When playing a movie and turning the device, movie (with sound) should continue playing nicely. (Just like VLC does it and it is done by oC app when playing audio.)
### Actual behaviour

Screen goes black and audio stops for a moment before it is resumed. Also the progress bar goes back to 0 for a moment.
### Steps to reproduce
1. Play movie (mp4 in my case)
2. Turn device (turning must be enabled of course)
### Environment data

Android version: 4.2.2.
Device model: Nexus 4
ownCloud app version: 1.6.2 (from master branch)

**Comment by rishabh7m** [comment]
@LukeOwncloud @jabarros can I start on this if anyone is not working on this issue?
