### ISSUE TITLE
Media player: White background is distracting

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/android#789]
### Expected behaviour

When playing a movie the background (not covered by the movie image) should be dark/black.
### Actual behaviour

Background is white.
### Steps to reproduce
1. Play movie (mp4 in my case)
### Environment data

Android version: 4.2.2.
Device model: Nexus 4
ownCloud app version: 1.6.2 (from master branch)

**Comment by michaelstingl** [comment]
Replaced with new media play implementation. Please check with current version.
