### ISSUE TITLE
Media player: Feature request: Fullscreen

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#790]
### Expected behaviour
When playing a movie the whole display should be used. Video should maximize (hide control buttons, title bar, and everything else) either when clicking the movie or automatically. Clicking again should show them again and reduce the size of the video.

### Actual behaviour
When playing a movie a large portion of the display is not used. No option to maximize to full screen.

### Steps to reproduce
1. Play movie (mp4 in my case)

### Environment data
Android version: 4.2.2.
Device model: Nexus 4
ownCloud app version: 1.6.2 (from master branch)

**Comment by LukeOwncloud** [comment]
@jabarros (Double) Clicking causes an error message as I described here: https://github.com/owncloud/android/issues/787

**Comment by davivel** [comment]
Fixed in https://github.com/owncloud/android/pull/1269 ; full screen video is back.
