### ISSUE TITLE
Upload failed, you need to relogin

### ISSUE THREAD

**Issue by User0815** [owncloud/android#792]
I just bought the Android ownCloud app (v1.6.2) for my HTC Desire 200 (Android version 4.1.2) and I have an issue. I can seemingly login, meaning that I don't get an error message on my phone. But no files show up and when I try to upload something, I get the error "Upload failed, you need to relogin". Then I get to login screen, where logging in doesn't help. I just see the empty file list again. The log file of ownCloud (v7.0.3+dfsg-1 on Debian Jessie) shows errors:

    {"app":"core","message":"Login failed: 'adrian' (Remote IP: '192.168.2.149', X-Forwarded-For: '')","level":2,"time":"2014-12-09T11:37:40+00:00"}

This line appears multiple times. Sometimes four times, sometimes eight times.

**Comment by tobiasKaminsky** [comment]
@User0815 Is this still happening?

**Comment by enoch85** [comment]
@User0815 Please test with the latest version 1.9.1, and Close this issue if it's not happening. Thank you!

**Comment by davivel** [comment]
Closing due to lack of response. @User0815, comment again if still not working, and we'll reopen.

Thanks.
