### ISSUE TITLE
Upload fails in android v.5.0

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#804]
### Steps to reproduce
1. Select to upload a file
2. Select from another apps
3. Select gallery
4. Upload more than one file at the same time, but the uploads fail

### Expected behaviour
Files are uploaded

### Actual behaviour
Files are not uploaded

### Device
 It happens using nexus 9 android 5.0
 It works using nexus 5 android 5.0
 It works fine in android 4.4

### Logs
12-12 10:54:00.983: E/FileDisplayActivity(12695): Initializing Fragments in onAccountChanged..
12-12 10:54:00.994: D/footer(12695): 1418378040994
12-12 10:54:01.008: D/footer(12695): 1418378041008
12-12 10:54:01.014: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.016: D/OwnCloudClient #161(12695): Creating OwnCloudClient
12-12 10:54:01.020: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.022: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 945271653}
12-12 10:54:01.023: D/SynchronizeFolderOperation(12695): Checking changes in puri@va-vmowncloud:8060/qwerouyt/qarf/ñññññ/
12-12 10:54:01.027: D/OwnCloudClient #161(12695): REQUEST PROPFIND /remote.php/webdav/qwerouyt/qarf/%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1/
12-12 10:54:01.029: W/HttpMethodDirector(12695): Required proxy credentials not available for BASIC <any realm>@10.40.10.254:3128
12-12 10:54:01.029: W/HttpMethodDirector(12695): Preemptive authentication requested but no default proxy credentials available
12-12 10:54:01.060: D/cache_test_DISK_(12695): image read from disk 1534811605
12-12 10:54:01.068: D/cache_test_DISK_(12695): image read from disk -1105815458
12-12 10:54:01.078: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.081: D/OwnCloudClient #162(12695): Creating OwnCloudClient
12-12 10:54:01.087: E/FileDisplayActivity(12695): onResume() start
12-12 10:54:01.093: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.097: D/footer(12695): 1418378041097
12-12 10:54:01.104: D/footer(12695): 1418378041104
12-12 10:54:01.109: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 454973498}
12-12 10:54:01.111: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.114: D/FileDisplayActivity(12695): onResume() end
12-12 10:54:01.122: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.127: D/cache_test_DISK_(12695): image read from disk 1534811605
12-12 10:54:01.130: D/cache_test_DISK_(12695): image read from disk -1105815458
12-12 10:54:01.145: D/OwnCloudClient #163(12695): Creating OwnCloudClient
12-12 10:54:01.148: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.153: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 780779014}
12-12 10:54:01.163: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.194: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.198: D/SynchronizeFolderOperation(12695): Send broadcast com.owncloud.android.operations.SynchronizeFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
12-12 10:54:01.211: D/OwnCloudClient #161(12695): REQUEST GET /ocs/v1.php/apps/files_sharing/api/v1/shares
12-12 10:54:01.213: D/FileDisplayActivity(12695): Received broadcast com.owncloud.android.operations.SynchronizeFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
12-12 10:54:01.223: W/HttpMethodDirector(12695): Required proxy credentials not available for BASIC <any realm>@10.40.10.254:3128
12-12 10:54:01.226: W/HttpMethodDirector(12695): Preemptive authentication requested but no default proxy credentials available
12-12 10:54:01.245: D/footer(12695): 1418378041245
12-12 10:54:01.260: D/footer(12695): 1418378041260
12-12 10:54:01.265: D/FileDisplayActivity(12695): Setting progress visibility to true
12-12 10:54:01.278: D/cache_test_DISK_(12695): image read from disk 1534811605
12-12 10:54:01.290: D/cache_test_DISK_(12695): image read from disk -1105815458
12-12 10:54:01.282: D/OwnCloudClient #164(12695): Creating OwnCloudClient
12-12 10:54:01.308: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.311: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 981904212}
12-12 10:54:01.315: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.321: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.325: D/OwnCloudClient #165(12695): Creating OwnCloudClient
12-12 10:54:01.329: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.331: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 176339709}
12-12 10:54:01.335: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.342: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.345: D/OwnCloudClient #166(12695): Creating OwnCloudClient
12-12 10:54:01.348: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.351: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 726721522}
12-12 10:54:01.355: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.364: W/HttpMethodBase(12695): Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
12-12 10:54:01.365: D/GetRemoteSharesForFileOperation(12695): Got 0 shares
12-12 10:54:01.397: D/FileDataStorageManager(12695): Sending 5 operations to FileContentProvider
12-12 10:54:01.406: D/FileContentProvider(12695): applying batch in provider com.owncloud.android.providers.FileContentProvider@dc0d4f7 (temporary: false)
12-12 10:54:01.425: D/FileContentProvider(12695): applied batch in provider com.owncloud.android.providers.FileContentProvider@dc0d4f7
12-12 10:54:01.431: D/SynchronizeFolderOperation(12695): Send broadcast com.owncloud.android.operations.SynchronizeFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
12-12 10:54:01.443: D/FileDisplayActivity(12695): Received broadcast com.owncloud.android.operations.SynchronizeFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED
12-12 10:54:01.472: D/footer(12695): 1418378041472
12-12 10:54:01.480: D/footer(12695): 1418378041480
12-12 10:54:01.484: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.485: D/OwnCloudClient #167(12695): Creating OwnCloudClient
12-12 10:54:01.487: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.489: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 405339953}
12-12 10:54:01.494: D/OwnCloudClient #167(12695): REQUEST HEAD /remote.php/webdav/qwerouyt/qarf/%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1/
12-12 10:54:01.504: W/HttpMethodDirector(12695): Required proxy credentials not available for BASIC <any realm>@10.40.10.254:3128
12-12 10:54:01.504: W/HttpMethodDirector(12695): Preemptive authentication requested but no default proxy credentials available
12-12 10:54:01.596: D/ExistenceCheckRemoteOperation(12695): Existence check for http://va-vmowncloud:8060/remote.php/webdav/qwerouyt/qarf/%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1/ targeting for  existence finished with HTTP status 200
12-12 10:54:01.602: D/OwnCloudClient #167(12695): REQUEST HEAD /remote.php/webdav/qwerouyt/qarf/%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1/1bH79ljToOFQwzejwsl2vrF_NXEjhcg1ZHmIHgsCwGc%3Ds0-d
12-12 10:54:01.603: W/HttpMethodDirector(12695): Required proxy credentials not available for BASIC <any realm>@10.40.10.254:3128
12-12 10:54:01.604: W/HttpMethodDirector(12695): Preemptive authentication requested but no default proxy credentials available
12-12 10:54:01.625: D/FileDisplayActivity(12695): Setting progress visibility to false
12-12 10:54:01.640: D/cache_test_DISK_(12695): image read from disk 1534811605
12-12 10:54:01.645: D/cache_test_DISK_(12695): image read from disk -1105815458
12-12 10:54:01.663: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.667: D/OwnCloudClient #168(12695): Creating OwnCloudClient
12-12 10:54:01.672: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.675: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 404473366}
12-12 10:54:01.677: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.680: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.680: D/OwnCloudClient #169(12695): Creating OwnCloudClient
12-12 10:54:01.681: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.682: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 87178135}
12-12 10:54:01.683: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.730: D/ExistenceCheckRemoteOperation(12695): Existence check for http://va-vmowncloud:8060/remote.php/webdav/qwerouyt/qarf/%C3%B1%C3%B1%C3%B1%C3%B1%C3%B1/1bH79ljToOFQwzejwsl2vrF_NXEjhcg1ZHmIHgsCwGc%3Ds0-d targeting for  existence finished with HTTP status 404(FAIL)
12-12 10:54:01.732: E/UploadFileOperation(12695): Upload of https://lh6.googleusercontent.com/1bH79ljToOFQwzejwsl2vrF_NXEjhcg1ZHmIHgsCwGc=s0-d to /qwerouyt/qarf/ñññññ/1bH79ljToOFQwzejwsl2vrF_NXEjhcg1ZHmIHgsCwGc=s0-d: Operation finished with HTTP status code -1 (fail)
12-12 10:54:01.733: D/FileUploader(12695): NotifyUploadResult with resultCode: LOCAL_STORAGE_NOT_COPIED
12-12 10:54:01.745: D/footer(12695): 1418378041745
12-12 10:54:01.750: D/footer(12695): 1418378041750
12-12 10:54:01.757: D/cache_test_DISK_(12695): image read from disk 1534811605
12-12 10:54:01.762: D/cache_test_DISK_(12695): image read from disk -1105815458
12-12 10:54:01.778: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.783: D/OwnCloudClient #170(12695): Creating OwnCloudClient
12-12 10:54:01.787: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.790: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 268840354}
12-12 10:54:01.793: D/ThumbnailsCacheManager(12695): Server too old
12-12 10:54:01.797: D/SimpleFactoryManager(12695): getClientFor(OwnCloudAccount ... : 
12-12 10:54:01.800: D/OwnCloudClient #171(12695): Creating OwnCloudClient
12-12 10:54:01.800: D/OwnCloudClient(12695): Proxy settings: 10.40.10.254:3128
12-12 10:54:01.802: D/SimpleFactoryManager(12695):     new client {puri@va-vmowncloud:8060, 567605811}
12-12 10:54:01.804: D/ThumbnailsCacheManager(12695): Server too old

**Comment by Bugsbane** [comment]
DId this ever get sorted? When I use InstantUpload, occasionally some files will fail to upload and I haven't managed to figure out why.

I'm wondering if this bug could still be to blame. I'm on Android 5 on a Moto E with ownCloud 7.0.4

**Comment by tobiasKaminsky** [comment]
@purigarcia Is this issue still valid?
With my nexus4, android 5.1.1 could not select multiple images in gallery to send them to owncloud.

**Comment by purigarcia** [comment]
You are right, @tobiasKaminsky .
This issue can be closed. Thank you.
