### ISSUE TITLE
OwnCloud-ToolBox

### ISSUE THREAD

**Issue by blackcrack** [owncloud/android#807]
Hi,

Why do you are not programming an OwnCloude-ToolBox for Android.
Playing Videos/Sounds as direct streaming, without download...
Documents -Viewer & PDF-viewer & Galerie who connects direct on the files on the cloud ..
maybe an ToolBox with Plugins for wrinting addons for the OC-ToolBox via 
plugin/snapin-api or some .. and on the Cloud-apps-page also an Android-OC-Tool-box-addon page.
And using for OC-Toolbox-download, f-droid, why: 
Free Open Source and without download-registering Android-marked  (it means, no Google-login )
an there it is generally no login required .. by F-Droid .

want be Cool if in the future an OC-ToolBox exist :)

best regards
Blacky

**Comment by tobiasKaminsky** [comment]
Closing as this meta issue is just to complex to do it and it is not a real enhancement of our app but a more generic approach/lib for other apps as far as I understand it.
