### ISSUE TITLE
open keyboard automatically with PIN screen in devices with hardware keyboard

### ISSUE THREAD

**Issue by tbeitter** [owncloud/android#81]
Everytime I open the oc client I have to tap on the screen to get the keyboard.
What about doing this instantly after opening the PIN entry screen?

**Comment by davivel** [comment]
Thanks for checking, @tobiasKaminsky .

For the record: in the future there is no need to keep checking in Android 2.x ; we won't keep granting backwards continuity to that point. Android 4.x is the new starting point.

**Comment by hodyroff** [comment]
As we have no idea how to do this, its not a bug. Please do a new feature request when there is a technical idea how to do it ...
