### ISSUE TITLE
Duplicate Files problem  (_conflict+date) on owncloud client. 

### ISSUE THREAD

**Issue by SAROEURN-Ritha** [owncloud/android#815]
Hello All, 
I have a problems when i upload file on owncloud client it show the duplicate file that create automatic  (_conflict+date). on owncloud client it have this  file but on the server it don't have.
* One more i have two user that the same group
UserA and userB : userA shear one file to userB when userA edit on this file userB  see the update on this file but when userB update on this file userA don't  see what is userB update. 

I hope that all of you have any solution to shear me about this problem.

**Comment by purigarcia** [comment]
Thanks for reporting.
Sorry, @SAROEURN-Ritha , I do not understand the first issue.
Could you give us more detail? Which are the steps to reproduce the problem?
Could you use this template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

About the second issue, we will check it

**Comment by davivel** [comment]
And, please, @SAROEURN-Ritha , open two separate issues for different problems.

Thanks.

**Comment by enoch85** [comment]
Duplicate files error is fixed, and merged. https://github.com/owncloud/android/pull/1168 Could we close this issue?

**Comment by tobiasKaminsky** [comment]
Thanks for pointing out @enoch85
