### ISSUE TITLE
InstantUpload: sync only on specific WiFi

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#826]
From #41:
A possibility to add black and white wifi network lists may be usable.
Like sync only in home and work wifi.
Or don't automatically sync via payed wifi at hotel.

**Comment by SMillerDev** [comment]
This could work with Androids mobile hotspot list for wifi. This stops apps like Google play from syncing over a mobile hotspot and might be something owncloud could check?

**Comment by fduraibi** [comment]
Yes please, such feature is great, not only for payed wifi, but also for slow wifi when in places like coffee shops and such. I have many failed video uploads because of slow wifi networks which will cause it to fail and never try again. (i have to run rsync every now and then to sync my phone with my server)

**Comment by tobiasKaminsky** [comment]
@SMillerDev Do you have any informations if there is a service we can query?

**Comment by SMillerDev** [comment]
isActiveConnectionMetered from here
developer.android.com/reference/android/net/ConnectivityManager.html should do
the trick I think.


On Wed, Aug 26, 2015 at 8:39 AM, tobiasKaminsky < notifications@github.com [notifications@github.com] > wrote:
@SMillerDev [https://github.com/SMillerDev] Do you have any informations if there is a service we can query?

—
Reply to this email directly or view it on GitHub
[https://github.com/owncloud/android/issues/826#issuecomment-134859484] .[https://github.com/notifications/beacon/ABamzsZmyzrYku89soKV4edugjmEvBDpks5orVaLgaJpZM4DNHwl.gif]

**Comment by tobiasKaminsky** [comment]
Ah. Great.
But this is an android built-in feature.
The user cannot select a single wifi and disallow the usage of this for owncloud?
I think this is what the issue reporter wants.

But this is also a good idea!
Description of the function:
Returns if the currently active data network is metered. A network is classified as metered when the user is sensitive to heavy data usage on that connection due to monetary costs, data limitations or battery/performance issues. You should check this before doing large data transfers, and warn the user or delay the operation until another network is available.
 @return true if large transfers should be avoided, otherwise false.

**Comment by Kernald** [comment]
[This SO answer](http://stackoverflow.com/a/15976165/775894) gives every information we need to achieve that:
 - get the current SSID
 - get a list of known SSIDs to propose a list of SSID to include/exclude.

**Comment by keithf4** [comment]
Just glancing through issues so I don't make a dupe request. I would really like this feature as well.

**Comment by jesmrec** [comment]
No plans to implement this.
