### ISSUE TITLE
User menu only visible in landscape mode

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/android#832]
Hello good owncloud peoples! While I was testing the Android app for writing up the manual page, I encountered this issue: the user menu only appears in landscape mode on my tablet. This is what I see in portrait mode:

![android-app](https://cloud.githubusercontent.com/assets/8388387/5622695/2a693484-94fc-11e4-8a09-cc73b93f6638.jpg)

No matter how I I swipe or poke the user menu does not drop down in portrait mode. However, in landscape mode it appears automatically:

![android-app-2](https://cloud.githubusercontent.com/assets/8388387/5622699/41cdf1aa-94fc-11e4-86c2-8d67c90e1c73.jpg)

This behaves the same way in the Dolphin and Firefox Web browsers. I don't know if it does this on other Android devices because I only have one.

ASUS Memopad 8, K00L
Android version 4.2.2
kernel version 3.0.36

**Comment by tobiasKaminsky** [comment]
This belongs to owncloud/core as it is a problem of the server displaying the files module not correctly.
Owncloud/android is only for the android app.

**Comment by carlaschroder** [comment]
Of course, sorry!
