### ISSUE TITLE
App just displays "Loading..."

### ISSUE THREAD

**Issue by rickglyn** [owncloud/android#833]
Just upgraded phone, running 4.4.4, OC 1.6.2. The "Loading..." message is all I get. 
No problem with desktop.

**Comment by tobiasKaminsky** [comment]
What web server do you use?
Do you have a self signed ssl certificate?
Is there something in LogCat?
Can you try it with http://demo.owncloud.org and test/test as username/password?

**Comment by rickglyn** [comment]
Thanks for the reply. Sorry about delay in getting back. I tried the  demo account and I get exactly the same behaviour.

**Comment by rickglyn** [comment]
Yes I do have self-signed certificate.

**Comment by tobiasKaminsky** [comment]
Have you tried to delete the complete owncloud app? Go to settings -> apps -> owncloud -> clear all data. Then uninstall it and please reinstall it.
Normally there is "just" a problem with the web server and not with the app, therefore it is strange that the test with the demo account does not work.
If this still does not work, please try to figure out if there is something in LogCat while accessing the demo server.

**Comment by rickglyn** [comment]
Hi, thanks for your help. 

Cleared all data and cache,  then noticed that I had loaded my new phone running KitKat with the Jellybean Workaround from my old phone! Uninstalled just the Workaround, and hey presto all is working fine now including the test site account. 

Cheers,

Richard.

**Comment by tobiasKaminsky** [comment]
Great.
Then this is solved :)
