### ISSUE TITLE
git https issue + fix for setup_env.sh

### ISSUE THREAD

**Issue by railrest** [owncloud/android#834]
need to add the following line at the beginning of the script to allow submodules to be downloaded

 **git config --global url."https://".insteadOf git://**

**Comment by masensio** [comment]
Hi @railrest,

sorry for the delay.

We've made some changes in the setup_env.sh to adapt to the new requirements of the project. You can see in develop branch and soon in master branch too.

I think with this change your fix is unnecessary. So I'll close this issue.

Thanks for your feedback.
