### ISSUE TITLE
DAVdroid Sync Issue (Contact Name Problem)

### ISSUE THREAD

**Issue by HarlekinSimplex** [owncloud/android#835]
Hi,
actually I encountered a problem using DAVdroid to sync my Contacts.
Though Firstname and Surname is filled and indicated correctly on my Z3 as well as using the Web client, the Contact Name is schown as 'Firstname Surname Surname Firstname'.
Any Idea what is going wrong here?

Best
Stephan

**Comment by tobiasKaminsky** [comment]
This issue tracker is only for the android app, which sync files and folders.
Please open a new issue on https://github.com/owncloud/contacts
