### ISSUE TITLE
Update OpenSSL to provide EC-based ciphers

### ISSUE THREAD

**Issue by leonardomarino** [owncloud/android#838]
Hi, I am using the ownCloud Android App version 1.6.2 and I would like to know if you could include support for EC-based ciphers, I am particularly interested in stop supporting SHA1. See closed issue for mirall (https://github.com/owncloud/client/issues/764) implemented in 1.7.1.

I am running apache and I have the following directives:

SSLProtocol All -SSLv2 -SSLv3
SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES+SHA384:ECDH+AES+SHA256:DH+AES:!RSA+AES256:!ADH:!AECDH:!MD5:!DSS:!aNULL:!eNULL:!LOW:!EXP
SSLHonorCipherOrder on

These directives allow you to use cyphers that support forward secrecy and work with a wide range of clients. In my apache log using Android-ownCloud 1.6.2 I get:

[15/Jan/2015:12:18:46 -0500] 192.168.1.16 - TLSv1.2 DHE-RSA-AES256-SHA

However, I would like to avoid using SHA1, and when I include the following directive in the SSLCipherSuite :!SHA1 the Android-ownCloud stops working.

This is a paid app and the new ciphers have been implemented in the Windows and Mac clients for sure. I would greatly appreciate it if you could update the Android-ownCloud as well.

**Comment by leonardomarino** [comment]
@davivel, I have noticed that you are one of the most active developers for the owncloud android app and I would like to know if this is the best place to post this request. Thanks! Leonardo

**Comment by masensio** [comment]
Hi @leonardomarino,

Currently, we are using the SSL provided by the device. Our app ask for all available ciphers on the device, instead of implement its own ciphers. 
So, maybe your Android device doesn't support this cipher. 

Sorry if it isn't a good news for you. :worried:

**Comment by leonardomarino** [comment]
Hi @masensio,

I am running Android 4.4.4 but hopefully in a few days I will be upgraded to lollipop. I have a new user that has Android 5.0.2 and the cipher that I see in the logs is:

TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384

Thanks for the update, I am going to close the ticket.
