### ISSUE TITLE
Android client available via http://owncloud.org/support/android/ is crashing

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/android#84]
Not sure if this is the correct place to report this, hopefully it will reach the right people...

I don't really know where to get the latest apk version of the owncloud client for android; I thought it was http://owncloud.org/support/android/ (at least that's the first hit on the search words "owncloud android client"), but the one from there is crashing on my phone (Galaxy Nexus running 4.2.1) - at least it shows a "App crashed" message box every time when the app starts; after some waiting the app still shows up, but will keep on crashing every minute or so - that's unacceptable for me, and I have seen this behavior before, I'm pretty sure it was fixed in the meantime. When going to the page linked there (http://alefzero.eu/a/) I see "Last modified: October 10 2012 23:20.", and it also still links to gitorious...

That can't be the current app, can it? If it isn't please at least remove the reference from http://owncloud.org/support/android/ (or point it to wherever the new version is available!

**Comment by mckaygerhard** [comment]
now again "opps page not found"!

**Comment by rperezb** [comment]
@jospoortvliet can you please check tthe url:  http://owncloud.org/support/android/ 
thx

**Comment by jospoortvliet** [comment]
https://github.com/owncloud/owncloud.org/pull/694 - that should solve it once and for all...

**Comment by jospoortvliet** [comment]
will be live on the next deploy (that would be next week at the latest)

**Comment by jospoortvliet** [comment]
Preview on https://staging.owncloud.org/support/android/

**Comment by mckaygerhard** [comment]
that not solves at all!, there's a free alternative? that redirects to the gplay store and must pay, there's a free download alternative as post prevously in this topic?

**Comment by untitaker** [comment]
No, unless you build it yourself you have to pay I think.

**Comment by AndyScherzinger** [comment]
Nope, like mentioned before, there is the F-Droid variant: https://f-droid.org/repository/browse/?fdfilter=owncloud&fdid=com.owncloud.android

**Comment by mckaygerhard** [comment]
ok thanks @AndyScherzinger and a important question: what the diference between a fdroit variant and the gplay version?

**Comment by tobiasKaminsky** [comment]
There is no difference, they are the same.
It is only in both stores to provide the app to as many users as possible.
