### ISSUE TITLE
Feature request: Sort files by on-device-status

### ISSUE THREAD

**Issue by benedetto** [owncloud/android#840]
This kind of a follow-up on #639:

I have some folders on my owncloud that contain a bunch (>100) media files. Some (far less than 50 %) of them are also downloaded to my mobile phone. In some situations where I don't have any or not sufficient internet connectivity or don't want to waste data volume but want to watch a video or listen to some audio file I browse through those folders on my device to find something suitable. At the moment, I have to scroll through the file list and keep track of the small green arrows that indicate that the file was downloaded.

As I can only access the files on the device in that situation, it would be convenient if I could just sort the files by their status, i.e. files that are stored on the device before those that aren't and therefore have all the available files in one bunch.

**Comment by tobiasKaminsky** [comment]
With #757 there will be the possibility to switch between "on device" and "all files" view.

**Comment by benedetto** [comment]
Thanks for the hint, in that case I'll close this one as a (more or less) duplicate.
