### ISSUE TITLE
Instant upload incorrectly thinks it has failed for some directories

### ISSUE THREAD

**Issue by bonuswavepilot** [owncloud/android#841]
Running on a Samsung Galaxy Express (GT-I8730) running Android 4.4.4, with v1.6.2 of OwnCloud app, and connecting to latest version of Owncloud 7, with encryption plugin active.

I find that if I set the instant upload directory to an ordinary (ie local) directory then it works ok, but on an external share, it continually tells me the upload has failed, then tries again later.  In fact, the upload is not failing - I end up with multiple copies of the image in the selected directory with an incrementing number in brackets after the file name.  (The files all seem to be the same size, and to open correctly, so I am assuming that they do in fact contain all data.)

The external directory is an Amazon S3 bucket.  It may be relevant that rather than using Owncloud's external share setup, I have the bucket mounted as part of the local filesystem using the s3 fuse driver (I was not able to get the S3 external storage working through Owncloud's interface).

**Comment by jabarros** [comment]
Thanks for reporting this wrong behaviour.
We will take it into account in order to check it.

**Comment by NiksNeues** [comment]
I have the same issue with instant upload to external directories only (Dropbox, Google Drive). Internal folders are working.

HTC M7, Android 4.4.3, OwnCloud App 1.6.2, Server 7.0.4, Encryption enabled

**Comment by davivel** [comment]
Hi, @bonuswavepilot and @NiksNeues .

Sorry for joining so late.

Is this still an issue for any of you?

**Comment by davivel** [comment]
Please, add a comment if this is still a problem, I will reopen.

Thanks.

**Comment by bonuswavepilot** [comment]
Sorry for the delay - am not currently using external directories, so I can't test I'm afraid.  Can confirm instant upload working well on normal dirs.

**Comment by davivel** [comment]
Thank you for answering, @bonuswavepilot .

**Comment by NiksNeues** [comment]
Just saw your request - instant upload to dropbox works fine now.

**Comment by davivel** [comment]
Really good to know, @NiksNeues ; thank you.
