### ISSUE TITLE
can't find "..." menu in the right hand corner (Kitkat on Galaxy Note III)

### ISSUE THREAD

**Issue by syndrael** [owncloud/android#845]
Hello,
On Android 4.2.2 Owncloud 1.6.2 (Sony Xperia S2) i can access Settings menu via "..." (3 dots vertically aligned). But in my Galaxy Note III Lite (Kitkat 4.4.2) i don't see the menu.
Could you help me ?
Best regards

**Comment by tobiasKaminsky** [comment]
Can you make a screenshot of it?
Does this device has a hardware menu button?

**Comment by jabarros** [comment]
The "Galaxy Note 3 Lite" seems to have a hardware menu button, so you will be able to access Settings using it.

**Comment by masensio** [comment]
Hi @syndrael,

Have you access to Settings using the hardware menu button? I hope so.

I'll close the issue, if you have problems accessing in this way, please reopen it.

Thanks for using ownCloud.
