### ISSUE TITLE
Adding the same account on repeat

### ISSUE THREAD

**Issue by offlinehoster** [owncloud/android#847]
Everytime, i would like to use my owncloud client on my android phone, i have to re-enter all the account credentials, because the client don't save the credentials.

Android: 4.4.2
Device Samsung S4
ownCloud Client version: 1.6.2

This happens after an client update too.

**Comment by rperezb** [comment]
A known bug exists in Android 4  affecting apps and associated user account data, leading to account credential deletion on restart of the device. We have developed a small additional work around app that resolves this bug.

Can you please install it and confirm us that your problem has been fixed? It is available at:
https://play.google.com/store/apps/details?id=com.owncloud.android.workaround.accounts&hl=en_GB

If this didn´t fix your issue, please reopen

thx

**Comment by offlinehoster** [comment]
Note that this bug is in Android 4.1.x, not in ownCloud. If you are not using ownCloud on Android 4.1.x you do not need this app.

I'm running 4.4.2

**Comment by davivel** [comment]
@offlinehoster , the bug is in vanilla versions of Android 4.1.x, but for some manufacturers (including Samsung), the bug still exists in versions after 4.2. Please, try the JB workaround and tell us if it helps.

**Comment by tobiasKaminsky** [comment]
@offlinehoster Has the workaround app fixed your problem?
If not please comment and/or reopen.

**Comment by offlinehoster** [comment]
It seems to work now.

**Comment by tobiasKaminsky** [comment]
@offlinehoster Glad to hear :)
