### ISSUE TITLE
Some message disappear from list view as “loading” and “nothing in here. Upload something!”

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#848]
### Steps to reproduce
1. Select to access to an empty folder
2. Message “nothing in here. Upload something!” is not shown

### Expected behaviour
While is checking if there is something, message “loading” should be shown.
Once checking is  finished, message “nothing in here. Upload something!” is shown.

### Actual behaviour
Message “nothing in here. Upload something!” is not shown

### Device
Nexus 9 v.5.1

**Comment by jabarros** [comment]
I am on it

**Comment by jabarros** [comment]
Fixed. Ready to test @purigarcia

**Comment by purigarcia** [comment]
Working
