### ISSUE TITLE
Footer message should be showed in the list view mode

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#849]
### Steps to reproduce
1. Select to access to a folder where there is not images
2. Footer is not shown

### Expected behaviour
When accessing to a folder where there is not image, footer is shown

### Actual behaviour
When accessing to a folder where there is not image, footer not is shown

### Device
Nexus 9 v.5.1

**Comment by jabarros** [comment]
I am on it.

**Comment by jabarros** [comment]
Fixed

**Comment by jabarros** [comment]
Ready to test @purigarcia

**Comment by purigarcia** [comment]
Working
