### ISSUE TITLE
Uploads view is not shown correctly

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#852]
### Steps to reproduce
1. Select to upload a file
2. Select files
3. The upload view is not correct

### Expected behaviour
Upload view is as before

### Actual behaviour
Upload view is not shown correct
![device-2015-01-20-133726](https://cloud.githubusercontent.com/assets/4538201/5817194/906a25b4-a0a9-11e4-8923-10b397438ada.png)

### Device
Nexus 9 v.5

**Comment by jabarros** [comment]
I am on it :)

**Comment by jabarros** [comment]
Fixed.

**Comment by jabarros** [comment]
Ready to test @purigarcia

**Comment by purigarcia** [comment]
Working
