### ISSUE TITLE
“Upload pictures via WIFI only” is hidden when going to files and come back to settings

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#853]
### Steps to reproduce
1. Go to settings
2. Enable instant upload, and “Upload pictures via WIFI only” is shown
3. Go to the list of files
4. Go to settings, and “Upload pictures via WIFI only” is not shown when it should

### Expected behaviour
“Upload pictures via WIFI only” is shown

### Actual behaviour
“Upload pictures via WIFI only” is not shown

### Device
Nexus 9 v.5.1

**Comment by jabarros** [comment]
I am on it.

**Comment by jabarros** [comment]
Fixed. Ready to test @purigarcia

**Comment by tobiasKaminsky** [comment]
@purigarcia Please test and close it. 
It works for me.

**Comment by AndyScherzinger** [comment]
@purigarcia @tobiasKaminsky works for me too, Android 5.1.1, Nexus5, oC 8.1.1
