### ISSUE TITLE
Checkboxes - Selecting Folders for holding real sync in Android.

### ISSUE THREAD

**Issue by blackcrack** [owncloud/android#854]
Hi,
i have an Galaxy 10.1 with 2 SD-Cards one internal and one external.
Both have enough space for syncing some folders from my server 
with Sound's from Jamendo, so CC-Music who you can download 
for free and i have some folders where i love to hear not alone at home, 
where i can sync my Galaxy over WLan or by my frend's on the net.
I want hear at all also on my Car or anywhere else , 
therefor i mus have some files directly synced, 
if i check an checkbox for have it directly synced and the files on my device.
Therefor it is maybe not bad, if we have checkboxes, 
which files hold it directly synced and actually if i go out of home .. or even away from net.
Therefor it is maby an Checkbox for the Folders recommendable which all synced, what is is changed or all 15, 30, 45,60 minutes just after settings in the android/Client .. 
maybe an real syncing .... to hold all selecting folders or files actually on the device.

Sync algorithm with checkboxes on the folders/files because if you work 
on an LOffice-Document (what it is now comes, Libre Office on android) ,
should hold sync also.. if you be on an playe where have you an idea or 
something flash of genius/brainstorm ;) .. textfiles or photos also ..
for have really all directly synced .. what you really need :)

and the 2nd idea/suggestion, if you hold longer the files for selecting an action, maybe remove from Android-Space, you know, for freeing space what not more like to have directly your / our / the android, but selectable for use or syncing again .

best regards
Blacky

**Comment by malkomich** [comment]
@blackcrack  You are talking about the feature of favorite folders I guess, which will allow having folders synced with the server as we do already with the files. Am I wrong?

**Comment by jesmrec** [comment]
Scoped storage makes this not to go on.
