### ISSUE TITLE
App crashes when accessing to some folders in upload view

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#855]
### Steps to reproduce
1. Select to upload a file
2. Access to folder where there are files inside
3. app crashes

### Expected behaviour
It is possible to see and select the files inside the folder

### Actual behaviour
App crashes

### Device
Nexus 9 v.5.1

**Comment by jabarros** [comment]
Fixed

**Comment by jabarros** [comment]
Ready to test @purigarcia

**Comment by purigarcia** [comment]
Working
