### ISSUE TITLE
Size of the folders is shown in the file list when it should not

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#856]
### Steps to reproduce
1. Login owncloud
2. Size of the folder is shown

### Expected behaviour
Size of the folders is not shown

### Actual behaviour
Size of the folder is shown

### Device
Nexus 9 v.5.1

**Comment by jabarros** [comment]
I am on it.

**Comment by jabarros** [comment]
Fixed

**Comment by jabarros** [comment]
Ready to test @purigarcia

**Comment by purigarcia** [comment]
Working
