### ISSUE TITLE
Size of the folders is shown  and a line behind the folder is not shown in the upload view

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#857]
### Steps to reproduce
1. Login owncloud
2. Select to upload a file
3. Size of the folders is shown and there is no line behind each folder

### Expected behaviour
Size of the folders is not shown and a line is shown behind each folder. As the image attached 
![device-2015-01-21-093834](https://cloud.githubusercontent.com/assets/4538201/5833289/e65e8c1e-a151-11e4-9417-450ab6d88c96.png)

### Actual behaviour
Size of the folders is shown and there is no line behind each folder

### Device
Nexus 9 v.5.1

**Comment by jabarros** [comment]
I am on it.

**Comment by jabarros** [comment]
Fixed

**Comment by jabarros** [comment]
Ready to test @purigarcia

**Comment by purigarcia** [comment]
Working
