### ISSUE TITLE
The controls of the video are not shown in htc one

### ISSUE THREAD

**Issue by purigarcia** [owncloud/android#859]
### Steps to reproduce
1. Download a video
2. Reproduce it and it is not possible to see the controls
### Expected behaviour

Controls are shown
### Actual behaviour

Controls are not shown
### Device

htc one v.4.2.2

**Comment by davivel** [comment]
Problem source is white color of buttons in HTC theme; other devices / manufacturers might be equally affected. Solution should explore options via support libraries about backwards-compatible media buttons.

**Comment by davivel** [comment]
@jesmrec, could we add this bug to the test cases of video streaming? I think we have a side fix here.

@purigarcia, hellooooo :D

**Comment by jesmrec** [comment]
Of course.

**Comment by jesmrec** [comment]
Fixed in https://github.com/owncloud/android/issues/592

**Comment by purigarcia** [comment]
@davivel @jesmrec Thank you
