### ISSUE TITLE
Instant upload duplicates files on filesystem 

### ISSUE THREAD

**Issue by ovidiub13** [owncloud/android#861]
When uploading a photo or video, the OC app, stores that photo as "downloaded" in its cache directory instead of linking the existing file, thus obtaining file duplications: original photo and OC "downloaded" photo. 

Also if upload fails several times, it gives up uploading it. Especially if the file is large (over 100 MB). 

I recommend the OC app should sync the camera folder instead of the current behavior.

**Comment by masensio** [comment]
This issue is an special case of #346 and #819.

**Comment by ovidiub13** [comment]
Duplicate of #819
