### ISSUE TITLE
Instant Upload Notification missing

### ISSUE THREAD

**Issue by wungad** [owncloud/android#862]
Using Android 4.3 ... sometimes when a photo is taken there is no notification that it's beeing uploaded or has finished uploaded. The upload finishes successfully.

**Comment by ovidiub13** [comment]
The notification disappears once the upload has finished. 

Is it possible that the upload finishes very fast?

**Comment by wungad** [comment]
Yap, you're correct. Happens on LTE and WiFi only. My bad. Close the bug please.
