### ISSUE TITLE
Home WiFi issue

### ISSUE THREAD

**Issue by DoNck** [owncloud/android#865]
Hi, I encounter a bug... which I think indeed comes from my Internet box ! So this is not a bug report for OC.
However, other users seem to encounter this issue (see http://forum.owncloud.org/viewtopic.php?f=24&t=25185&p=78127#p78127). Thus it could make sense bringing support for this particular situation.

So here is the problem:
I can perfectly sync my android device with my home OC server through friends WiFi and mobile data network.
BUT, it doesnt work with my WiFi at home.
It seems my Internet box doesnt let my android device access https://mydomain.tld/owncloud from the WiFi. On the android device, mydomain.tld resolves in 192.16.1.1 which is my box's IP instead of 192.168.1.46 which is the IP of my server.

Here is a workaround I found to enable using the OC app on your local WiFi: add an account to the OC app specifying the adress on my LAN: https://192.168.1.46/owncloud

It is clearly not a very convenient solution, but at least, it seems to work !

May be OC could have an option like an alternative address. Or just enable the user to specify multiple adresses separated by comas so the GUI does not get messy for basic usage.

PS: I'm using OC Android client 1.6.2 from f-droid and OC 7.0.0 server.

**Comment by fluffy88** [comment]
Most likely your problem is with your router at home.
It is probably either caching an old DNS record for mydomain.tld that points to 192.16.1.1, or it has it's own DNS record for the same.

Either way you should be able to clear your DNS cache on your router or remove the DNS entry for mydomain.tld and all should work :)

**Comment by DoNck** [comment]
You're absolutely right, the problem comes from the router behaving in a weird way.
FYI, the router is a Livebox from Orange, which is (one of ?) the main French ISPs. May be the router configuration can be fixed with some trick, but in my opinion, it makes sense to enable trying alternative hostnames in case the first one completly fails at resolving. Don't you think ?

**Comment by tobiasKaminsky** [comment]
https://github.com/owncloud/core/issues/13039
This sounds similar to the wish in /core.

What should be done: 
- allowing multiple addresses for one account with priority order
- if the first address cannot be resolved: try next one
- remember the one that works until it does not work, then start from beginning

**Comment by DoNck** [comment]
Thanks, I Didnt notice this one.
BTW I added a comment in https://github.com/owncloud/client/issues/203.
I agree with what you proposed, but I think it could be a good idea to close the connection and reconnect, trying from the first URL in the list, in case of network configuration changes. This should make the app try to find the server on the LAN first and would also adress issue https://github.com/owncloud/android/issues/529

**Comment by danimo** [comment]
Check if you can enable [Hairpinning](http://en.wikipedia.org/wiki/Hairpinning) in your router. This solves most problem. The feature often also goes by the name Hairpin NAT or Loopback NAT.

**Comment by DoNck** [comment]
It looks like it can't :(

**Comment by DoNck** [comment]
OOPS, ERRATUM! "On the android device, mydomain.tld resolves in 192.16.1.1 which is my box's IP instead of 192.168.1.46 which is the IP of my server."
-> That's what I thought looking at the page whithin Android Firefox, but my assumption was wrong. Actually, I checked from a terminal emulator and it returns my public IP. I get a 404 which is not served from my OC server. Probably the port is not forwarded as expected and I talk to the http server of my ISP's. That would match the Hairpinning thing.

**Comment by niklas88** [comment]
Some routers can't access their own public IP, a friend of mine has one of those and it's a pain but nothing you can do besides getting a proper router and complaining to your ISP that that router is broken by design.

**Comment by Netzweberei** [comment]
Hi, I have the same issue here. I can connect to my ownCloud with android only if mobile-networking is enabled (I then had to confirm the self-signed certificate of my web-hoster), but not through my wifi. But I can connect with the desktop-client and with iOS-client (mobile and wifi).
This is what I could find in my router's log: 

26.06.2015 08:46:01DNSv6-Fehler: Der angegebene Domainname kann nicht von 2003:180:2:9000:0:1:0:53 aufgelöst werden. Fehler: Non Existent Domain (P008)

26.06.2015 08:38:58DHCP ist aktiv: 26.06.2015 08:38:58 WLAN android-8be89d5d51f70a2e 84:00:D2:B4:7F:FA 192.168.2.100 255.255.255.0 192.168.2.1; 192.168.2.1 86400 (H001)

I think, the error appeared after I updated to the latest android-client.

**Comment by stb2015** [comment]
I have the same problem. And I do not think that it a problem of the router because other apps like foldersync work perfectly with webdav. When looking into logcat I found this line

XXXXX.dyndns.org/2a02:8109:8000:58:1df3:5109:e419:bcc7 (port 443) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)

The ipv6-adress is from my router, but why it is used? Other apps do not do this...

I cannot disable IPv6 in my router (rented FritzBox).

Using owncloud client with openvpn-connection from inside to outside and then inside works :-(

**Comment by LukeOwncloud** [comment]
So this seems to be an IPv6 problem. Please track here: https://github.com/owncloud/android/issues/616

Thanks!
