### ISSUE TITLE
Recommend CalDAV and CardDAV

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/android#870]
Many users want Calendar and Contacts syncing. Upon installation of the Android app, we could simply recommend these apps and offer to install them (link to the app store) and save ourselves from hundreds of feature requests and repeated questions about this missing feature ;-)

**Comment by jnweiger** [comment]
Browsing comments on google play store, it appears, that most disappointment comes from the expectation, that owncloud would do calender and contacts syncing.

@rperezb

**Comment by LukeOwncloud** [comment]
@jnweiger To avoid that it was agreed that the app should be renamed to "owncloud files" --> https://github.com/owncloud/android/issues/328

**Comment by jospoortvliet** [comment]
@LukeOwncloud ha, that is a helpful step forward indeed. Still this might make sense to add as well... @MTRichards what do you think?

**Comment by davivel** [comment]
About explicitly recommending other apps, I don't think there is a good reason for we make an official recommendation in the official ownCloud app to any concrete app for Calendar or Contacts. 

About users confused, well, this has been discussed other times in the past. Meeting expectations of users is very important, but not all the user expectations are equally important. The first sentence in the app description says:

```Welcome to the ownCloud Android App – Add an ownCloud server, and have your private file sync and share cloud up and running in no time.```

File sync and share is there. No mention to contacts or calendar; not in that line, not in any other point of the app. However, "sync" is there, and there are many points about "syncing" that are not covered yet, and that should be prioritized before than discussing the name of the app or what to do with contacts and calendar, in my humble opinion.

Nevertheless, if somebody really wants to talk about this issue further, let me invite you to open it in https://central.owncloud.org, where everybody is welcome to join and discuss anything related to ownCloud. :)

About this repository, let's dedicate it to issues already prioritized or in active development. That's the new way we would like to use there two tools from now.

Thanks :)
