### ISSUE TITLE
Renaming a directory will hide its original content

### ISSUE THREAD

**Issue by gjanssens** [owncloud/android#873]
I used the Android app to rename a directory from "Photo's" to "Afbeeldingen".

After I did this all subdirectories and images in that directory were gone. At least they are no longer visible in the android app. They are still present in the webinterface and the native client on linux also has no issues seeing the images. This was a scary moment !

I managed to force the android app to rescan the renamed directory by adding another image to it via the owncloud directory on my linux  box. When the android app got notified of this new image it also rediscovered my other images and subdirectories.

Android app version 1.6.2
Owncloud server installation: 7.0.2 on Centos 6

**Comment by masensio** [comment]
Hi @gjanssens,

sorry for the delay.

I've check this issue with the Android app version 1.7.1 and everything works fine.
I've rename a folder from "Photo's" to "Afbeeldingen" and the content of the folder is present in the app.

Have you updated to the last version? Do you still have this problem?

Thanks for your feedback.

**Comment by tobiasKaminsky** [comment]
@gjanssens Any update?
With "android app" you mean our owncloud app and not, for instance, the android gallery app (as you say "rescan")

**Comment by tobiasKaminsky** [comment]
Closing due to no response.
If it still occurs, please reopen and provide more feedback.
