### ISSUE TITLE
Custom Agent String for Android Client

### ISSUE THREAD

**Issue by MTRichards** [owncloud/android#875]
As an admin I want to be able to prevent standard ownCloud apps from connecting to my ownCloud server, I want my users to use the custom ownCloud apps I have branded.

The concept here is that a quick fix with a custom user agent string through ownBrander would enable a filter on "non-authorized" clients.

Not perfectly secure for a determined user, but ok as a quick fix.

**Comment by masensio** [comment]
This issue is implemented in https://github.com/owncloud/android-library/pull/56 and https://github.com/owncloud/android/pull/924.
This changes are in our develop branch now.
