### ISSUE TITLE
Local modifications are not marked.

### ISSUE THREAD

**Issue by joede** [owncloud/android#876]
I have a personal use case where I have to edit some file on my Nexus7 tablet. Since this is not that often the same set of file, I _don't want_ to to enable "keep in sync" for these files. 

So I just click on the file, download it and use the editor on Android to make my changes. After storing the file, it is _locally modified_.

The client only shows with a small icon that the file is downloaded. It doesn't show that it is locally modified! Even the _details dialog_ of the file does _not_ indicate that situation!

I think the Android client should at least add a small icon the indicate this situation.

In a second step, the client should allow the upload of all modified files within a directory (from it's global menu). It isn't funny to manually sync / upload  a couple of files by opening the context menu of each modified file. ;-)

**Comment by tobiasKaminsky** [comment]
There is something like that being considered in #819 
But you are right: if the local file is newer than the file on the server this should be indicated somehow.
@jancborchardt Do you have a suggestion? Maybe some kind of colored arrow? 

@joede Please make a new issue for your second step and refer to this one.

**Comment by strugee** [comment]
This seems like something that we should just automatically detect and upload in the background.I'm not familiar with the code that handles downloading, but it seems like we could probably inherit from the "keep in sync" logic, but mark the file somehow as not permanent (so that it could be purged when caches are cleared, etc.).

**Comment by joede** [comment]
@tobiasKaminsky I've seen your issue #819 and I think my report goes in the same direction. The current behaviour could lead to conflicts.
I don't know the code of the client and I don't know how the metadata of files is handled by the code. I would store the metadata of the (1) the local file (2) of the remote file **and** the (3) the metadata at the time of the download / last sync. This way the client could display small icons for "local modifications" and "possible conflicts" if the remote file is changed since the last download/sync.

**Comment by jospoortvliet** [comment]
I think my comment on https://github.com/owncloud/android/issues/819 should take care of this issue, as well as #877  - it would at least make that problem go away ;-)

**Comment by davivel** [comment]
I like this idea a lot.

No matter how sophisticated we make our synchronization process, in mobile there will always be situations where the network is just no available. 

Maybe it's not appropriate for every kind of user, but sure there is a set of advanced users who appreciate having the most accurate info about the files and it's sync state.

**Comment by jancborchardt** [comment]
@davivel just like on the desktop client we should use the blue circular arrows for files still to be synced. :)

**Comment by jesmrec** [comment]
current document provider implementation makes this posible.
