### ISSUE TITLE
If login fails, android app should show the error message of status.php

### ISSUE THREAD

**Issue by guettli** [owncloud/android#878]
If there is a login problem, the android app should display the error message of https://example.com/status.php

I guess this would avoid a lot of confusion and false bug reports.

**Comment by tobiasKaminsky** [comment]
Just as I am curious:
- example.com should be replaced by the owncloud server address?
- What is the benefit of this message? I just get {"installed":"true","version":"7.0.2.1","versionstring":"7.0.2","edition":""}. What will be displayed if there is a problem with the server?

**Comment by masensio** [comment]
Hi @guettli, 

as @tobiasKaminsky said, this address provides the server version data. 
What is the information that you are expecting?

Thanks

**Comment by guettli** [comment]
In my case the status.php page told me something like "PostgreSQL Verions >= N" needed. But the android client just told me something like "unknown error".

**Comment by tobiasKaminsky** [comment]
@davivel 
Maybe it is enough to present a generated link to the status.php with something like "The following url can provide further details on this error."

**Comment by guettli** [comment]
@tobiasKaminsky a link to more info would be enough (my opinion).

**Comment by davivel** [comment]
The values in /status.php are useful for administrators and tech-savvy users, but they are meaningless for an average user - and probably confusing.

We can increase the number of specific error messages handled in the login Activity, or improve the fallback message in some cases (for instance, using the HTTP status line). But printing the info in status.php or a link to it doesn't seem UX-wise, IMHO.

**Comment by guettli** [comment]
> ... but they are meaningless for an average user - and probably confusing.

My son is thirteen. He speaks only german. He does not understand english error messages.

**But** he can take a screen shot and send it to the admin :-)

Verbose error messages are not confusing at all if you know somebody who can understand them.

Please don't hide information which can help to get to the root of the problem fast.

**Comment by davivel** [comment]
Sorry, there is something here that I don't get to understand. /status.php does not show any kind of error message, verbose or not, it is, literally, a JSON dictionary with 5 values. Example:

![captura de pantalla 2017-02-02 a las 17 17 50](https://cloud.githubusercontent.com/assets/2225614/22557791/e01f6fbc-e96b-11e6-826e-e8d927d7cd98.png)


I don't know how your ownCloud server shows a web page in that path. It should not.

Did you customize your server to replace the JSON object with an error message? 

Is your OC server maintained by a service provider that could have done that customization? Which is your service provider?

**Comment by michaelstingl** [comment]
Is this about error messages generated from ownCloud, or is this about crazy PHP/webserver errors that were displayed instead of status.php output when someone broke the ownCloud?

**Comment by guettli** [comment]
> In my case the status.php page told me something like "PostgreSQL Verions >= N" needed. But the 
> android client just told me something like "unknown error".

This message was created from owncloud. The php environment worked well.

**Comment by davigonz** [comment]
I've finally opted for @davivel solution, increasing the number of specific error messages handled in the authentication by moving part of the error handling from the login activity to a common error message adapter.

**Comment by jesmrec** [comment]
approved

**Comment by guettli** [comment]
thank you for solving this!
