### ISSUE TITLE
Simple screen to share with users / groups

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/android#880]
Currently, my main usecase that I want ownCloud for is to share photos and videos with family overseas quickly, as I take them. If I want to share a photo just after I take it with my phone though, I need to:

1. Go to the gallery
2. Click share
3. Choose a pre-existing folder (no new ones!)
4. Upload
5. Log in to ownCloud via the browser
6. Navigate to the folder where it is
7. Find the individual file
8. Click share
9. Select / type the appropriate user(s) / groups or public link
10. If I'm sharing with someone who isn't a user on my ownCloud, copy the link
11. Switch to the email / sms app
12. Send a message with the public link

This is just to share a file, surely one of the core use cases of the ownCloud app. Accordingly, I rarely actually bother to share, and if I do, it's not until way later when I'm at home at my computer, with the full ownCloud interface.

Instead, I propose that we have a "Share" screen, described below. This would be accessible from 2 places. First, in the menu where the user long tap and holds a file / folder while browsing. Second, via a second button next to the "Upload" button when using Android's share feature. The second button would be "Upload and share" which would, obviously, upload as it does now, and then open the share options page.

The share page would have the following 3 radio button options:

1. A list of users / group names with checkboxes to choose who to share with. If there are more than, say 10, it would show the 10 users / groups most recently shared with and a search / filter field for the user to find a pre-existing person on that ownCloud instance (limited to people in the same groups if "Limit sharing to the same groups" is active, unless the user is an admin)..

2. Generate a public link, only.

3. An email field to share with non users (generate a public link and send that email address a message with it).

"Generate public link only" would be the default the first time, but the chosen options would be remembered when the user shares next time.

**Comment by masensio** [comment]
Hi @Bugsbane,

thanks for sharing with us your ideas about sharing feature. We will take them into account for the future improvements of the sharing .

At the moment, Android app provides you a way to share your files by link. You can copy the link or select an app to share with link with others.

**Comment by Bugsbane** [comment]
Thanks @masensio 

Yes, I understand the ability to create a public link, however my main reason for using ownCloud is precisely because I don't want to make my private data available to the rest of the world in the way that using a public link would.

Anyway, thanks for the reply.

**Comment by masensio** [comment]
Hi @Bugsbane.
I understand your problem, but don't worry.
In the near future we will implement other features about sharing as: share with password protection, share with groups ... as in the browser.

I hope this is a good news for you :)

**Comment by Bugsbane** [comment]
Thanks. That was the main purpose of filing this ticket, ie. to make it known that it's generally needed and to give somewhere for that discussion to happen.

Cheers.

**Comment by fxshpac** [comment]
I second this idea in general. Waited for the feature of sharing files/folders to users/groups in particular for a long time. Together with the Copy files feature and Image/Video thumbnails feature, I can handle the photo/video sharing to private users/groups all on my phone. And that completes my use case completely.

**Comment by Bugsbane** [comment]
I've come up with a wireframe, which is also simplified a bit from my description above. For example, it's not really necessary to have fields to enter email addresses for people to send the public link to. Really, all that's needed there is just to generate the link and copy it to the clipboard.

Anyway, here's my UI suggestion, which would appear after choosing the folder, with the final "Upload" button in the top right:
![share-dialogue](https://cloud.githubusercontent.com/assets/401733/8149547/98d03308-1294-11e5-8c65-22716282571e.png)

**Comment by Bugsbane** [comment]
If there are more users / groups than fit the screen, it could just be scrolled by dragging.

**Comment by tobiasKaminsky** [comment]
I like it.
And as I really miss this feature I would like to implement it.

@jancborchardt Is the wireframe/mockup good? Then I would start looking how this can be done...

**Comment by davivel** [comment]
Is there an entry point in the server side to get the lists of users and groups?

cc @rperezb @cmonteroluque @MTRichards

**Comment by rperezb** [comment]
@davivel @tobiasKaminsky we have just started a issue to discuss the UI for the iOS app, https://github.com/owncloud/ios/issues/425
Once we have defined it, we may take it as reference for the Android app (adapting it to the Android style)
Time expectation, we expect to start working on the iOS side on this feature this Thursday, 30 July.  
@davivel about the entry point to retry the list of userst, maybe helpful: https://doc.owncloud.org/server/8.0/admin_manual/configuration_user/user_provisioning_api.html

**Comment by jancborchardt** [comment]
For both iOS and Android it should basically look like the current share dropdown. With the exception that we need the file thumbnail and title above.

**Comment by rperezb** [comment]
@davitol @tobiasKaminsky WIP the Server API: https://github.com/owncloud/core/issues/16646

**Comment by rperezb** [comment]
related to the desktop client: https://github.com/owncloud/client/issues/3537 and iOS https://github.com/owncloud/ios/issues/425

**Comment by rperezb** [comment]
WIP https://github.com/owncloud/android/tree/share_with_users

**Comment by tobiasKaminsky** [comment]
![share](https://cloud.githubusercontent.com/assets/5836855/10465065/4184b3a4-71ed-11e5-9c82-375b0e023152.jpg)
I like it :+1: 
But I think that the folder icon is unnecessary big. This image is taken from a nexus 5 and I doubt that two sharees can be shown.
But it is great to see progress :)

**Comment by davivel** [comment]
@tobiasKaminsky , right, icons / thumbnails are too big. We'll improve that.

Still progressing on this one.

**Comment by jancborchardt** [comment]
Sorry I haven’t come around to a design review on this one – it’s up on my list as I have some remarks! :) (Same for iOS)

**Comment by davivel** [comment]
Don't worry, still working on it. Maybe we can make an overall review after covering the fundamental operation.

**Comment by rperezb** [comment]
@jancborchardt it would be great if you may check it, asap.
Would it work if I provide to you an apk?

**Comment by Bugsbane** [comment]
Just going off the screenshot, is it actually necessary to have users click the button labeled "Add a user or group" when they're presumably already at the share screen? Maybe I'm missing something by not seeing the interaction flow, but from the photo alone, it seems redundant.

**Comment by tobiasKaminsky** [comment]
@Bugsbane It is also for editing the existing sharees. 
But you are right if there is no existing sharee, then it is one more step.

**Comment by rperezb** [comment]
@Bugsbane the screenshot shown is the first one, 
In case that the data has been already shared with any user/group there it's listed this information. If you want to share from the mobile app, then you click on the add button and a search view is implemented.

**Comment by masensio** [comment]
Hi @all,
there are some screenshots with the appereance of "Share with users" dialog.
(Made with Nexus 5, Android 6)
![screenshot_20151026-142957](https://cloud.githubusercontent.com/assets/3862330/10730209/e0a7b4d0-7bee-11e5-8efc-74a66c1cafaf.png)

When you click on "Add User or Group" button, it is shown:

![screenshot_20151026-143001](https://cloud.githubusercontent.com/assets/3862330/10730241/0c12be26-7bef-11e5-93c4-351043520ef3.png)

We can unshare with a user or group using the cross button.

The appereance of of those dialogs on tablet are: (Nexus 7 with Android 4.3)
![screenshot_2015-10-26-14-03-08](https://cloud.githubusercontent.com/assets/3862330/10730300/74d273f2-7bef-11e5-8bd0-710c50186a83.png)
![screenshot_2015-10-26-14-04-31](https://cloud.githubusercontent.com/assets/3862330/10730303/783a8f52-7bef-11e5-956b-5d86c4dc93da.png)
![screenshot_2015-10-26-14-04-41](https://cloud.githubusercontent.com/assets/3862330/10730308/7e9b9ad0-7bef-11e5-9aba-3aedbe83f936.png)

At the moment, we have implemented these screens as dialogs both mobile and tablet, but we are thinking about showing as dialog on tablet and fullscreen on mobile.
What is your opinion about this?
@jancborchardt, @MTRichards, @rperezb, @davivel, @tobiasKaminsky, @AndyScherzinger

**Comment by AndyScherzinger** [comment]
I don't have a preference in this case for dialogs over fragments/activities. Though I wondered how I would close the dialogs since they don't seem to have a "closing action". So maybe that is an aspect which would argue for fragments.

**Comment by tobiasKaminsky** [comment]
For maintaining reason I prefer to have both in the same way. 
I think I remember that @jancborchardt said once that such non-permanend things should be dialogs an contrast to "new views (like show only offline files)" to better show the user that this is only for few actions visible.

**Comment by davivel** [comment]
In this case they are only dialogs in appearance, the implementation is an Activity themed as a dialog. We get this way the non-permament feeling that @tobiasKaminsky comments, but moving between different fragments is easier.

@Bugsbane, besides the editing mode, it's planned to join in this view another "section" below for "share via link", and remove the separeted option from the context menu in the list of files. Something similar to the "Sharing" panel in web interface in OC 8.2.

**Comment by davivel** [comment]
The view continues evolving to hold "share link" and its new options. Let's continue the dialog about the UI in #1178

**Comment by davivel** [comment]
Share with users ready to go in next release, 1.8.1.
