### ISSUE TITLE
[DEPRECATED] ActionBarSherlock

### ISSUE THREAD

**Issue by hateum** [owncloud/android#881]
Why you still use the deprecated library ActionBarSherlock instead of the current android support library V7 ?

**Comment by masensio** [comment]
@hateum 
thanks for your suggestion.

We also want to stop using deprecated code but we need to do carefully. Also we need to find the appropiate moment.

**Comment by hateum** [comment]
Tell me if I can help you, I'm a Senior Android Developer

**Comment by joeplus** [comment]
I think we were talking about a new drawer in #757. Coming with that a switch to v7 but I think @tobiasKaminsky is busy at the moment and therefore can't continue right now.

**Comment by masensio** [comment]
Hi @hateum @joeplus,

we are working to replace ActionBarSherlock by the current android support library V7. It is the first step to add the new drawer and Material Design in the app.

This change coming soon in develop branch. And it will be available in the next release (1.7.2)

**Comment by tobiasKaminsky** [comment]
After that I can try to update my navigation drawer branch and make it public, so that all devs can work on it.

**Comment by davivel** [comment]
@tobiasKaminsky , sounds cool. Indeed, we had between our targets for the current sprint a first version of the navigation drawer. But we are not going to do it twice. Let's resume the dialog about the drawer in #757 .

**Comment by masensio** [comment]
Hi @all,

Now ActionBarSherlock library is removed from Android Owncloud project. This change is in our develop branch. :smile: 

So, I'll close this issue.
