### ISSUE TITLE
Instant upload deletes thumbnail cache on server

### ISSUE THREAD

**Issue by jmit79** [owncloud/android#882]
### Expected behaviour
Succesful instant upload of a photo.

### Actual behaviour
Mobile client says upload failed, but upload was succesful. After the upload the thumbnail cache dir of the user gets deleted (owncloud/data/user/thumbnails)

### Steps to reproduce
1. Take a picture with your mobile
2. Wait for "Upload failed" message
3. Check thumbnail dir on server

### Environment data
Android version: 4.4.4 CM11

Device model: 
Samsung Galaxy S4

ownCloud app version:
1.6.2 (Play Store version)

ownCloud server version:
8.0.0

#### ownCloud log (data/owncloud.log)

{"reqId":"b4705bad3176f1af0a37a85bf24ac6b4","remoteAddr":"89.15.80.247","app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks\\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params [\"N\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'","level":3,"time":"2015-02-18T00:29:45+01:00"}

Could be a core related error but it's only reproducible on my smartphone. Upload via browser works as expected. direct upload via mobile client also works, only instant upload fails and destroys the whole thumbnail cache

**Comment by masensio** [comment]
Hi @jmit79,

this is very strange. There is no difference between uploads and instant uploads. 
Are you uploading the same photo with instant upload and manual upload?
Is the file size of manual upload more than 1MB?

**Comment by jmit79** [comment]
You're right. The file size makes the difference. I instantly uploaded a picture with the front camera on my smartphone (size ~250KB) without problems. Only images >1MB seem to trigger the deletion of the thumbnail cache (instant and normal upload). That's definitely not a problem within the android client. The core calls the function deleteAllPreviews() but my php knowledge is too bad to traceback the reason for this :(

**Comment by jmit79** [comment]
Closing, as it really is a core problem. I've raised an issue over there...
