### ISSUE TITLE
feature: copy-paste text

### ISSUE THREAD

**Issue by unhammer** [owncloud/android#883]
Someone mentioned an app that could quickly copy-paste text between your computer and your phone. Wouldn't it be neat if you could click "Enable shared clipboard" on the desktop client and the mobile client and it automagically synced anything that was plain-text?

**Comment by masensio** [comment]
@unhammer 
I think this is duplicating #104.  Please, let's track the state there.

Thanks!

**Comment by unhammer** [comment]
Okidoke :)
