### ISSUE TITLE
Owncloud app logs me out while sharing via link

### ISSUE THREAD

**Issue by BoBeR182** [owncloud/android#884]
When I try to share a file via link via textsecure owncloud logs me out and forces me to relog in.

Confirming owncloud app logs me out for sharing any file via any app. Running latest owncloud from f-droid and latest owncloud server 8.0.1 from ubuntu repos.

**Comment by masensio** [comment]
Hi @BoBeR182 
thanks for your feedback.

It's the first notice about this bug. I tried to reproduce it but I haven't gotten.

Could you provide us the description with the following format  https://github.com/owncloud/android/blob/master/issue_template.md?

Thanks

**Comment by BoBeR182** [comment]
### Expected behaviour 
I should tap share link and get the owncloud link to the file into my clipboard or the app I select
### Actual behaviour 
I click the share link I choose any app, it idles a bit then logs me out with a small popup server could not share file or folder
### Steps to reproduce
1. Select a file
2. Click share link
3. Choose any app
4. Watch you get logged out
### Environment data
Android version: 4.4.4 
Device model: Sony Xperia Z1
Stock system: stock running latest update
ownCloud app version: 1.6.2 fdroid
ownCloud server version: 8.0.1 Latest, OS ubuntu 14.04, repo via opensuse build
### Logs 
#### Web server error log
 ``` Insert your webserver log here ``` 
#### ownCloud log (data/owncloud.log) 
``` Insert your ownCloud log here ```

**Comment by BoBeR182** [comment]
Updated to 1.7.0 mobile client via owncloud bug still exists.

**Comment by davivel** [comment]
Hi, @BoBeR182 . Do you still suffer this bug? What versions of app and server do you use right now?

I'm not sure what you mean with "log me out". When does the app request you to log-in, right

Can you tell us what 'Sharing' options are enabled and disabled in your server? You will find them in the 'Admin' panel.

Thanks in advance.

**Comment by michaelstingl** [comment]
This will no longer happen with the [new sharing architecture](https://github.com/owncloud/android/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3AArchitecture+):
