### ISSUE TITLE
Send requested properties in PROPFIND, do not use allprops

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#887]
SabreDAV only allows these properties to be returned:
https://github.com/fruux/sabre-dav/blob/master/lib/DAV/PropFind.php#L50

In past OC versions we hacked Sabre to also include "oc:permissions", "oc:size", etc.

We are now upgrading to Sabre 2.1 (https://github.com/owncloud/core/issues/12876) and would like to remove the hack (which is actually not possible to use any more due to code changes in SabreDAV).

Please update the mobile client to explicitly request the properties.
A PROPFIND request could send a body that looks like this:
```
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
<a:prop><a:getcontenttype/></a:prop>
<a:prop><a:getetag/></a:prop>
<a:prop><oc:permissions/></a:prop>
<a:prop><oc:size/></a:prop>
...
</a:propfind>
```

As an added bonus: note that if you only want the mtime, then just request "a:getlastmodified". This way the server doesn't need to do extra work for properties that you don't want :smile: 

CC @davivel as discussed

**Comment by PVince81** [comment]
Note that this change is backward compatible with older OC versions

**Comment by karlitschek** [comment]
@dragotin @rperezb does this change break anything in the clients? If yes then we have to discuss a proper migration and upgrade strategy

**Comment by PVince81** [comment]
For the desktop client no changes needed, see https://github.com/owncloud/client/issues/2865#issuecomment-76162134 (it was sending all requested properties already)

**Comment by masensio** [comment]
We've modified the PROPFIND requests to not use ALLPROP requests.
https://github.com/owncloud/android/pull/913
https://github.com/owncloud/android-library/pull/55

This change works  with old server versions too.
It will be available in the next release of ownCloud  Android Client.
