### ISSUE TITLE
1.7 build failed on F-Droid

### ISSUE THREAD

**Issue by thedd** [owncloud/android#890]
@mvdan
The owncloud 1.7 client build fails on F-Droid.
https://f-droid.org/wiki/page/com.owncloud.android/lastbuild_10700000

**Comment by mvdan** [comment]
This seems to be an issue on our end, no reason to open an issue here (upstream)

**Comment by thedd** [comment]
"our" end?

**Comment by mvdan** [comment]
https://gitlab.com/fdroid/fdroiddata/issues

No need to open an issue there either though, since failing builds are already tracked:

https://f-droid.org/wiki/page/Category:Apps_with_failing_builds

**Comment by RealRancor** [comment]
Fixed and should be available tomorrow: https://gitlab.com/fdroid/fdroiddata/commit/ccdc01161a18a4a5bdc952dbd3040cc352e9ff34
