### ISSUE TITLE
Enhance issue.template

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#893]
Hi,

in order to distinguish between an real app problem or "just" a server side problem we should include a new question in the issue_template.md:
Can this problem be reproduced with the official owncloud server? Please log in with:
User: test / password: test / url: https://demo.owncloud.org

Also we (or maybe /core) should try to write a test script that checks if the server is working fine.
So many bad ratings on the play store would vanish as they are not related to the app but to the mis-configured server. (Apart to e.g. dropbox this is a problem as the user does not distinguish between server or app failures. But we cannot be made responsible for wrong servers... Maybe this should also be mentioned somewhere...)

**Comment by tobiasKaminsky** [comment]
@davivel Can you add the question regarding the test on the official demo server to issue_template.md?

**Comment by davivel** [comment]
Added Jr Job about the addition in issue_template.md.

About the test script on server side, well, too hard. There are tons of possible variables in a server setup to just talk about "right" and "wrong" servers. Right now the app already makes some very basic tests when a URL is entered in the log-in view - mainly, checking status.php and the value of the "installed" parameter in it. Sound to me like and ideal automatic tests that could be a whole project itself.

**Comment by tobiasKaminsky** [comment]
PR for the issue_template.md: #1539

**Comment by davivel** [comment]
Done, thanks @tobiasKaminsky
