### ISSUE TITLE
1.7.0: Grid view for pics should be optional / additional!

### ISSUE THREAD

**Issue by deMattin** [owncloud/android#894]
The new grid view in 1.7.0 might be a great feature if you are able to select it like gallery in the owncloud web-app.
But it should not be the forced AND ONLY view in a file-client like the android app.

In my opinion the new grid view of 1.7.0. is very problematic and mostly a step backwards because you are not able to see the name of the file in this or another view.
Further more this view is forced automatic active in all folders with only pictures in it and mostly only shows "placeholders" for the pics (on a Owncloud 7.x Server) and no additional filenames.

Is there any chance to switch off this view generally and get back the old view with mini thumbnail and the name of the file?
With the mini-thumbnails it is not essential, if there exists a thumbnail or if there's only a placehoder for it.

In the google store you see some (many) other comments claiming the "broken" view.
But even if the previews will work, a gallery style view should be an ADDITIONAL option and not the only possibility to view this type of files in a list and to decide, if you want to download the whole file on your android.

**Comment by rperezb** [comment]
thanks for your comment,

@jancborchardt what do you think?
FYI @MTRichards

**Comment by rensgr** [comment]
agree fully.  this stupid interface looks like this: 
![stupid-view](https://cloud.githubusercontent.com/assets/4196449/6326621/ed1e78fe-bb53-11e4-88cd-6816f0e0e578.jpg)

**Comment by LukasReschke** [comment]
@jancborchardt

**Comment by rensgr** [comment]
while it should have looked like this:::  (yes, that is your competition......)
![proper-view](https://cloud.githubusercontent.com/assets/4196449/6326645/20d89b2a-bb54-11e4-8846-e3a0a3df325e.jpg)

**Comment by jancborchardt** [comment]
The first question is why the placeholders are shown and not the thumbnails of the actual images. @rperezb @davivel?

Secondly yes – after the feedback we received through the Play Store, via email and here, it is indeed better to have a view setting in the options dropdown top right. That should remember its setting per folder. @MTRichards @rperezb @davivel ok?

**Comment by MTRichards** [comment]
yep.

**Comment by zebtom** [comment]
I would like to add that the app became unstable on my device (samsung galaxy S4). In a typical photo gallery (200 pics, 2-3Mo each), scrolling up/down lags and the app crashes when scrolling too fast in a gallery view.

**Comment by nickvergessen** [comment]
(how is an "empty"/unusable file list an enhancement?!)

**Comment by LukasReschke** [comment]
Agreed… – Tagging as bug.

**Comment by LukasReschke** [comment]
> The first question is why the placeholders are shown and not the thumbnails of the actual images. @rperezb @davivel?

Because the thumbnails are generated on the server and that API only exists in ownCloud 8 and newer. Which means that this will fail hard for ownCloud 5-7.

**Comment by tobiasKaminsky** [comment]
But when there will be a switch between file and grid view, there should still be the automatically way:
<50% images: file view
>50% images: grid view

**Comment by rensgr** [comment]
All,

NO automatics please !

the detail of thumbnails is not always good enough to distinguish whats 
on them,  and certainly not when

there is just a little difference (e.g, I changed the b/w balance 
slightly or so). Especially for phones and tablets, with much smaller 
screens.

Such differences can only be determined by the meaningful filename I 
gave them.

I.m.o,  it needs to behave the old way (filename plus mini-thumbnail) 
and if someone wants it differently,
it should be setted per folder and remembered as a preference

Met vriendelijke groet / Best regards,
Rens




Rens Groenewegen
mob +31 (0)6 2183.6903
mail: rensg@xs4all.nl

http://nl.linkedin.com/in/rensgroenewegen/

**Comment by tobiasKaminsky** [comment]
@rensgr you have misunderstood me.
I wanted to introduce a switch:
- always image view
- always grid view
- based on threshold (50%)

With that all users should be satisfied, or?

**Comment by rensgr** [comment]
Ah, sorry, yes,  that would be fine :-) 

met vriendelijke groet,

Rens

Rens Groenewegen
mob  :     +31 (0)6 2183.6903
email:     rens.groenewegen@xs4all.nl

linkedIN : http://nl.linkedin.com/in/rensgroenewegen/

**Comment by zebtom** [comment]
Whatever the images/files ratio is, I'm not sure that anyone wants grid view in a professional setting. Gallery view is great for viewing vacation pictures.

**Comment by joeplus** [comment]
I guess there are some people who would like to replace dropbox or other services which all have a gallery view with owncloud this feature is a must in my opinion, especially for those vacation pics...

We could add a separate "gallery view" to the new drawer, when this feature is ready. Basically this would to remove the need to add another "option" to the top right menu.

**Comment by tobiasKaminsky** [comment]
I think this is an option that can be placed in "settings" as this is a basic decision: whether to have always a file list, always a grid view (i doubt that someone will use this) or let the app choose the "best" view.
Something like a setting per folder is too much overhead.
And putting this to the new drawer is also not very good as it then would have to be enabled every time one wants to use it.
So, just put an option in settings which enables the user to get to the well known view and everything should be fine?

**Comment by joeplus** [comment]
I don't have anything against the "option setting". With the drawer i was just referring to dropbox's dedicated gallery view where only images are shown.

**Comment by rensgr** [comment]
app-wide setting works for me.

the dropbox argument is valid, though.

I just dont know how many owncloud users are
keeping their recreational pictures in their owncloud......

And even then, if you have a 400 picture holiday folder, do you want to 
download them all ?
because you cant see the filenames ? (which usually contain some 
date/time information.....)

400x 3-4 mbyte = 1.2 Gbyte, ( avg size of a pic for a 12 mpix camera) is 
more than my monthly data-subscription.........



Met vriendelijke groet / Best regards,
Rens




Rens Groenewegen
mob +31 (0)6 2183.6903
mail: rensg@xs4all.nl

http://nl.linkedin.com/in/rensgroenewegen/

**Comment by tobiasKaminsky** [comment]
You still can long press on a file and see the file details.
Also...for just vacation photos or a best of 2014 the small thumbnails are more than enough as the images are mostly complete different (remember, vacation or something like that).

**Comment by deMattin** [comment]
I like the suggestion of "joeplus" most:
<i>"We could add a separate "gallery view" to the new drawer, when this feature is ready. Basically this would to remove the need to add another "option" to the top right menu""</i>

This way the app behaves like the owncloud webapp and you have both: A grid view with server generated thumbnails (with oc>8.0) for all pics (and only the pics) and a useable file view with mini-thumbnails in normal folder view.

But until gallery view is available, there should be a fast update with the old view to make the app useable as a file app again and benefit from the other updated and fixed features in 1.7.0.

**Comment by jancborchardt** [comment]
@tobiasKaminsky @rensgr 

> Something like a setting per folder is too much overhead.

There needs to be a per-folder-setting. This is not something which makes sense as a global setting since for some folders it needs to be gallery view, for some list. If it’s a global setting, it will result in people needing to switch the setting constantly.

So instead, it should be a per-folder setting which is remembered for the folder.

**Comment by jancborchardt** [comment]
Additionally we could go for a very very conservative default of _only_ enabling the gallery view by default if _100%_ of the folder contents are images. If it’s switched to list, the preference is remembered of course.

**Comment by fxshpac** [comment]
One thing related that I want to report, in gallery view, the thumbnails for videos are still not supported on this version of the app, even after I enabled in on server side running version 8.0.0-5. The web interface can display them just fine. Therefore I suspect it's the Android app which is not taking advantage of the API to retrieve these thumbnails for videos.

**Comment by tobiasKaminsky** [comment]
@fxshpac this is a new issue. Can you please open a new one and describe the problem there?

@jancborchardt But there still should be the possible to change it to "based on threshold". Even if it is in the settings... So maybe:
Settings: Switch list/image view:
- always list view
- always image view
- based on threshold (adjustable?)
- per folder setting
--> for the last one there must then be a switch entry behind the three dots, right? ("change view")

**Comment by rensgr** [comment]
@tobiasKaminsky : long press to find your information... and then in a 400 image folder, I need to do that  on average 200 times to find the one I am looking for ? 
that does not sound to me as a good idea......

I prefer just the filenames, please, and an option for gallery mode in the dropdown....
or vice versa, as long as the app remembers it I am fine with either.

**Comment by tobiasKaminsky** [comment]
@rensgr There soon will be the possible to switch back to the file list view. The solution is being discussed right now, as you can see.

But meanwhile it is possible to long press an image to view the filename. And... you cannot really say that you have 400 images that have the same thumbnail? Maybe your main problem is that the thumbnails are not downloaded from the server? This requires owncloud server 8.0 which is stated in the release notes.

**Comment by fxshpac** [comment]
@tobiasKaminsky Opened https://github.com/owncloud/android/issues/897, thx

**Comment by rensgr** [comment]
@tobiasKaminsky , 
yes, I get 400 same placeholders.
even if I did get thumbnails (who says i want to spend bandwidth / data on that ? )
they are way to small for making the distinction between them for quite a few use cases.
which happens to me often, since I am taking sequences of pictures under difficult light cirumstances etcetera.

**Comment by jancborchardt** [comment]
@tobiasKaminsky so many settings are overkill. ;)

Firstly, we need to check if the ownCloud server is version 8 minimum. If it’s 7 or lower, the grid view needs to be disabled anyhow since thumbnails will not load for all images.

Then, when we know it’s ownCloud 8 at least:
* The default is list view. Unless 100% of the files in the folder are images (not counting subfolders of course) – then the gallery view is used.
* Behind the three-dots there is a toggle to change between »List view« and »Gallery view«. That is remembered _per-folder_.

That’s the minimum which makes sense now. Introducing a bunch of settings for this would be an overreaction and confuse people as well.

**Comment by jancborchardt** [comment]
@davivel @rperezb @MTRichards ^ to note.

**Comment by MTRichards** [comment]
thanks.

**Comment by rensgr** [comment]
sounds good to me.... :-)

**Comment by rperezb** [comment]
@jancborchardt about the check of the server version, if we like this, we are loosing thumbnails for downloaded files on server versions without the api, is this the expected?

**Comment by jancborchardt** [comment]
@rperezb no, the check is only for deciding whether to use the grid view or not. When the server is ownCloud 7, the normal list view should be used. But thumbnails for downloaded files should still be shown.

**Comment by tobiasKaminsky** [comment]
@jancborchardt Is this https://github.com/owncloud/android/issues/894#issuecomment-75954806 still valid?
> Behind the three-dots there is a toggle to change between »List view« and »Gallery view«. That is remembered per-folder.

**Comment by tobiasKaminsky** [comment]
I close this in favour of #1081 as there is described how this will be fixed.
