### ISSUE TITLE
Add "sort by size"

### ISSUE THREAD

**Issue by q00d0** [owncloud/android#895]
Hello,

in the Webinterface there are a few methods of displaying your files sorted.

Examples: Name (up and down; A-Z & Z-A), Size (up and down; large>small & small>large)

Can you please add these sorting methods into your android client?

Thanks!

_____

BUGS & IMPROVEMENTS

- [X] Some devices does not display the "Biggest - Smallest" option https://github.com/owncloud/android/issues/895#issuecomment-240672370 [FIXED]

**Comment by masensio** [comment]
Hi  @q00d0,

the sorting methosd into android client are the result of a large discussion about them. You can see it in  https://github.com/owncloud/android/pull/624.

Thanks for your opinion, we will keep it in mind for future improvements.

**Comment by tobiasKaminsky** [comment]
Still sorting by size is missing.
--> Changing title.

**Comment by tobiasKaminsky** [comment]
--> PR: #1655

**Comment by jesmrec** [comment]
I have noticed that in several real devices the option "Biggest - Smallest" is not displayed. The trace related is the following:

`com.owncloud.android I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's`

Devices and Android versions in which the option is not displayed:

Nexus5, v5.0.1
Nexus9 tablet, v6
Samsung Galaxy S3, v4.1.2
Samsung Galaxy Note 4, v6
Galaxy Nexus, v4.2.1

Devices and Android versions that the option is displayed:

HTC One v4.3
Nexus10 tablet v5.0.2 

Emulated terminals show the option

cc @davivel

**Comment by davivel** [comment]
Seen, I'll have a look.

**Comment by davivel** [comment]
Bug ready to test.

**Comment by jesmrec** [comment]
Approved

**Comment by davivel** [comment]
Last agreed option was added. Will be available with version 2.2.0
