### ISSUE TITLE
Search Function for the Android App

### ISSUE THREAD

**Issue by mhtalpha** [owncloud/android#896]
Dear, 

I am trying to develop my own application from open source owncloud

im trying to deply a search function.
This function allows you to search the files either in the application or on the server.

does anyone was able to work on such a feature?

thank you

**Comment by mahermeg17** [comment]
Hi,
can refer here : <a href="https://github.com/owncloud/android/issues/695" >#695</a>

**Comment by PVince81** [comment]
Closing as duplicate
