### ISSUE TITLE
Not displaying server side video thumbnails

### ISSUE THREAD

**Issue by fxshpac** [owncloud/android#897]
Running owncloud core version 8.0.0-5 and android version 1.7.0, I want to report that, in gallery view, the thumbnails for videos are still showing default icon, even after I enabled OC/Preview/Movie on server side. The web interface displays them just fine. Therefore I suspect it's the Android app which is not taking advantage of the API to retrieve these thumbnails for videos.

PR: ~~https://github.com/owncloud/android/pull/1035~~ https://github.com/owncloud/android/pull/1780

**Comment by masensio** [comment]
Hi @fxshpac,
sorry but ownCloud server doesn't provide thumbnails for videos.

Show thumbnails for videos is an improvment for our app. 
What do you think @jancborchardt about this?

**Comment by jancborchardt** [comment]
Yeah, video thumbnails would be very good. @DeepDiver1975 anything that needs to be added to the server to enable this?

**Comment by tobiasKaminsky** [comment]
I have installed ffmpeg and ffmpegthumbnailer.
After that the server can generate thumbnails.
With one very little change the app can also display these thumbnails.
A PR for this is coming soon.

**Comment by tobiasKaminsky** [comment]
PR is currently not possible as I ave committed it directly.
Sorry for this :/

**Comment by tobiasKaminsky** [comment]
PR: #1035

**Comment by tobiasKaminsky** [comment]
Remaining problem is that in gridView the user cannot distinguish between image and video if both have a thumbnail.
@jancborchardt Do you have an idea? Maybe display a film strip like this http://www.vorlagendrucken.de/wp-content/uploads/2014/01/Einladung-Gutschein-Filmstreifen_1.jpg

**Comment by jancborchardt** [comment]
The thumbnail for videos should have a play button overlayed: https://github.com/owncloud/core/blob/master/core/img/actions/view-play.png (SVG in the same folder), that’s the common way to distinguish videos from images.

**Comment by tobiasKaminsky** [comment]
Ok. I will add this.
Is really better than film strips.
Any suggestion about the size? Half of the size, centered?

**Comment by jancborchardt** [comment]
Yeah, half the size and centered sounds good.

**Comment by jancborchardt** [comment]
Maybe third the size – experiment and see what looks good.

**Comment by tobiasKaminsky** [comment]
![video_overlay_big](https://cloud.githubusercontent.com/assets/5836855/8878835/b3104cf4-322d-11e5-8050-2c2bf1394a2d.jpg)
![video_overlay_listview](https://cloud.githubusercontent.com/assets/5836855/8878845/c8426508-322d-11e5-95ca-e88ffd5a4d0f.jpg)

@jancborchardt What do you think?
I need a bigger/better version of the play button.

**Comment by jancborchardt** [comment]
Nice, looking great! It’s also good that in the thumbnail view the title is still below the video. Maybe it makes sense to omit the file extension though? Just a thought :)

The better version of the play button is the scalable SVG: https://github.com/owncloud/core/blob/master/core/img/actions/view-play.svg as mentioned in the same folder as the PNG. Does that work? :)

**Comment by jancborchardt** [comment]
Ah just a detail: The play button is visually not in the center because it has more weight to the left. It needs to be moved to the right a bit.

Instead of aligning the image file itself in the center, imagine a circle around the play button touching all the corners, and align that. See https://medium.com/@erqiudao/the-play-button-is-not-optical-alignment-4cea11bda175

**Comment by tobiasKaminsky** [comment]
SVG does not work. But I can save it as a better scaled png and use this.
About the centering: I have to figure out how to do this.
But maybe I can trick a little bit and move the play button on the png canvas a bit to the right ;)

**Comment by jancborchardt** [comment]
Yup, both sounds good. ;)

**Comment by tobiasKaminsky** [comment]
@jancborchardt
I have computed it now exactly as I hope:
I have used the three points of the triangle of the play button to compute the middle point of the circle.
From this I have computed an offset to set the overlay.

Please see if this version is better than the last one. (For me it is not...)
You can compare it to https://github.com/owncloud/android/issues/897#issuecomment-124566735 as there is one video that is on both screenshots.

![video_overlay](https://cloud.githubusercontent.com/assets/5836855/9012214/6c22cafc-37b3-11e5-87d0-9a86ac9b2166.jpg)

**Comment by tobiasKaminsky** [comment]
Ok it was still a bit wrong.
Please see now:
![video_overlay final](https://cloud.githubusercontent.com/assets/5836855/9025048/49ad9a0c-38f2-11e5-9d3a-45e5a5acdf41.jpg)

**Comment by tobiasKaminsky** [comment]
ups :/

**Comment by jancborchardt** [comment]
Last screenshot looks great! :) :+1: from me.

**Comment by tobiasKaminsky** [comment]
Then it is ready to test? @davivel

**Comment by davivel** [comment]
PR commented.

**Comment by davivel** [comment]
From #1181:  Video thumbnails should not show file name below.

**Comment by jesmrec** [comment]
Every file type is checked. If server provides video thumbnails, client will show. Solved.
