### ISSUE TITLE
android chunked upload: missing OC-Total-Length header

### ISSUE THREAD

**Issue by moscicki** [owncloud/android#900]
Android client does not respect the same protocol as the desktop client for chunked uploads.

For chunked PUT the client should send the OC-Total-Length header specifying the total file size (like the desktop sync client does). This gives a server a possibility, for example, to check the final file size as an integrity check. You may check with @dragotin and @DeepDiver1975 for details.

BWT, we started drafting the spec. It is not yet finalized: https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md

You may also check if issues with failing 1MB+ uploads (e.g. https://github.com/owncloud/android/issues/402) are not related.

**Comment by moscicki** [comment]
Ref: https://github.com/owncloud/android-library/blob/d7097983594347167b5bde3fa5b2b4ad1d843392/src/com/owncloud/android/lib/resources/files/ChunkedUploadRemoteFileOperation.java#L77

**Comment by davivel** [comment]
Seen, Thanks a lot, seems promising.

**Comment by cdamken** [comment]
@MorrisJobke 

00002767

**Comment by MorrisJobke** [comment]
@rperezb ;)

**Comment by rperezb** [comment]
Thanks for reporting this, we will take this into account

**Comment by davivel** [comment]
@DeepDiver1975 , @MorrisJobke , @dragotin : should this header be in all the chunks of a file or just in the first one?

Thanks.

**Comment by davivel** [comment]
Seems that desktop client sends it in every chunk, and also in non-chunked uploads; is it needed in non-chunked uploads too?

**Comment by moscicki** [comment]
@davivel, @DeepDiver1975, @MorrisJobke, @dragotin:

I am attempting to make you all guys a favour and document your own protocol ;-)

Have a look here: https://github.com/cernbox/smashbox/blob/master/protocol/protocol.py

chunk_file_upload()
file_upload()

This is my best description of the protocol between the desktop sync client and the server, including the emulation of Android 900 issue (this one as we speak).

**Comment by davivel** [comment]
@moscicki , you are my hero XD 

According to a comment in your own code, server OC 7 seems to ignore the header; that's a pity, maybe this fix does not have a so big impact on the tricky bugs in uploads that we expected.

**Comment by moscicki** [comment]
Note that in this issue we are fixing the chunk_file_upload() for which this header is clearly missing. As for the plain upload I think you should include it. There should be no harm in doing this (this is my "sensible" guess).

Glad to be the hero! On the other hand, it would be appreciated to get some contribution to an effort, that someone like me who is not paid to do the work for your company does, in order to help you out with the basics such as documenting your own protocol and coding according to clearly documented protocol specification. I don't mean to be nasty, I am just sad about this.

The text description of this part is missing: https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md

**Comment by masensio** [comment]
We've added the OC-Total-Length header in the PR https://github.com/owncloud/android-library/pull/59

**Comment by masensio** [comment]
This change is also in our develop branch.
