### ISSUE TITLE
Statistic table of biggest files and directories

### ISSUE THREAD

**Issue by guettli** [owncloud/android#901]
Storage is limited. Sooner or later the space on the android device gets low.

The user needs help for the desicision: 

`Which parts should not be synchronized in the future, to save disk space?`

On the unix shell I use this: `du -a | sort -rn | less`

Example output of above command on the unix shell:
```
root@pc> du -ax /etc/ | sort -rn | head
36156	/etc/
18724	/etc/X11
18156	/etc/X11/core
3972	/etc/brltty
1700	/etc/apparmor.d
```

This lists the biggest entries first.

If you have a list like this, it's easy to find the stuff to delete/stop-to-sync.

I think the best place would be in the context dialog of a directory.

For example "Show disk usage statistic" could be the heading of this new feature.

I can't help you to implent this by writing code. 

But if you need feedback on usability: just contact me. I love to help you.

**Comment by tobiasKaminsky** [comment]
Hmm.
If you have limited storage you can simply just delete a directory as it is synchronized to the server.
But there will be (when the server supports it) a size property of the directory. So then one can sort the list by size. 
This should help you?

**Comment by guettli** [comment]
Yes, it helps a bit: I can use the web interface and use the sort  by size feature. The size of directories seems to include all subdirectories (recursive). That's nice, have not seen it before.

But a list like from `du -a | sort -rn | less` would still be very nice:

```
36156   /etc/
18724   /etc/X11
18156   /etc/X11/core
3972    /etc/brltty
1700    /etc/apparmor.d
```

But you are right. Maybe it is much less work for you, if you implement this in the web interface. But it would be nice to have for the android client, too.

In the android app I can only sort by name and age.

**Comment by tobiasKaminsky** [comment]
No, no. You have misunterstood me. 
The feature to sort the list by the file/folder size, which it has and which it has on the server, will come sooner or later, depending on the prework of /core.
Sou you then can sort by "size on device" and "size on server".

**Comment by guettli** [comment]
Yes, very cool. "size on device" and "size on server" (recursive) is exactly what I was searching for.

Could you please post a link to this feature in core?

**Comment by tobiasKaminsky** [comment]
@jancborchardt we have with #1655 only the folder size on the server and not locally on the device.
How to deal with this?

**Comment by jancborchardt** [comment]
Well then from the folder size one can deduct what should be deleted, if really necessary.

Android has its own storage usage statistics, so no need to implement something inside the ownCloud app as well I'd say.

**Comment by tobiasKaminsky** [comment]
Then I close this.
