### ISSUE TITLE
UX: switching image grid <-> image preview is too slow

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#902]
Hello,

I have a folder with 800 images that all have thumbnails, either remote or local. When I open an image I can see the preview very fast, but switching back to the image grid takes 2-3s.
I guess that the complete folder is synchronized again with the server.
This should be done only when entering the folder via clicking on the folder. Resuming the folder list should be possible immediately. If there is a change it could either loaded in the background or manually triggered via swipe down.

**Comment by davivel** [comment]
Is this still a problem? Not sure if that the problem is in the refresh folder, but maybe in the load of the images.

**Comment by davivel** [comment]
What model is your device?

**Comment by tobiasKaminsky** [comment]
It is still the same.
Android 6 with Moto X Play, but also with Nexus4 on Android 5.
I think it is a problem of loading the file list/refreshing the folder, as scrolling is working very fast (either if there are thumbnails or placesholders)

**Comment by davivel** [comment]
I'd bet for the load of the data and or refresh of the view, better than for the folder refresh (with the server side) itself. Handling of Fragments in FileDisplayActivity is... too complex, being generous.

**Comment by AndyScherzinger** [comment]
This should be solvable moving on to recyclerview since it only renders the visible area while the list view renders all 800 images (the complete list) at once. So that might also bring some performance improvement :)

**Comment by davivel** [comment]
Recyclerview more than probably will help with performance, but I suspect that the main reason for the problem here is in the level of Fragmens management.

**Comment by tobiasKaminsky** [comment]
FileListListAdapter:396 gives me this times if I enter a directory with ~4000 images:
03-11 18:03:29.524 4340-4340/? D/FileListListAdapter: swap Directory time: 2121
03-11 18:03:41.557 4340-4340/? D/FileListListAdapter: swap Directory time: 3792
03-11 18:03:46.349 4340-4340/? D/FileListListAdapter: swap Directory time: 2850

Please note that I only enter it one time, but I get three executions of the function swapDirectory.

**Comment by tobiasKaminsky** [comment]
Maybe the app should store the content of the folder locally and only get the modification time of the folder: if this is the same all content is still valid and therefore no update must be done...?
