### ISSUE TITLE
Delay time for Photo/Video-Upload

### ISSUE THREAD

**Issue by q00d0** [owncloud/android#903]
Hey Guys,

I've got a suggestion for another feature.

If you take a photo and you have instant upload on, than the photo gets uploaded immediately. If the picture is blurred it gets uploaded anyway and wastes your limited mobile internet access.

So if there is an option to delay the upload maybe one or two minutes, you have enough time to check the picture, delete it and take a new needle-sharp one and you save a lot of traffic.

**Comment by tobiasKaminsky** [comment]
There is a similar issue, but I cannot find it.
Meanwhile I think it is the best to enable "instant upload only via wi-fi".

**Comment by q00d0** [comment]
Hey Tobias,

it's not like that I don't want to spend my mobile data traffic for uploading my pictures.
But I want to upload them efficiently and not unnecessarily.

**Comment by jospoortvliet** [comment]
@q00d0 thing is, I would bet that if we would do this, delay by two minutes, people would go like "why is it so slow?" while adding another option for this - it seems overload of features. I would personally vote against this. If bandwidth is a issue, use "instant upload only via wi-fi", if it isn't - then don't. Covers 98% of the situations, I would say.

**Comment by dhsc19** [comment]
I think this is a good suggestion, but as an opt-in feature.  So, InstantUpload should, by default happen instantly, but maybe have a sub-option to delay.  I want to be able to have my photos be backed up while on mobile network, but I think it would be great to have a period of time to review the photo before leaving it to be backed up.  It's not a bandwidth issue as much as it is a way to help not end up with a bunch of useless snapshots and still maintain active backups while on mobile.  Sometimes I'm not in a position to be on WiFi for long periods of time and I depend on mobile backups for work.  I have to quickly review my photo's view the phone's photo gallery, but if I want to delete it as well as delete the backup on owncloud, I have to switch over to the owncloud app and delete both remote and local.  It's kind of a waste of time needing to switch apps like that just to keep organized.

**Comment by jospoortvliet** [comment]
I'd submit that if you want time to review the pics you took, no single standard delay time is sufficient. Sometimes you review the pics immediately, another time there are so many it takes too long, or you can only review them an hour later.

What you want is upload-after-review. Only the ones you deemed good enough.

Luckily, this exists: it's the upload function in ownCloud. Absent mind control over your phone, the choice between upload-them-all (instant-upload) for those who review the photo's later and manual upload for those who wish to review them before uploading is the best there is. A configurable time for auto-upload might occasionally satisfy a handful of users in some situations (and annoy them in others) but the costs of developing, adding a option and maintaining the code is, in my opinion, absolutely not worth the benefit. It's not my call but I'd close this as a won't fix.

Of course, if that happens, anybody is free to make a fork of this (open source!) app and add this function (and perhaps others deemed not useful for general public), making it available to ppl who want it.

**Comment by Bugsbane** [comment]
What about some kind of "Upload new" window in the app, which isn't part of instant upload, but basically:
1. Shows thumbnails of all new photos and videos since the last upload
2. Allows users to preview each
3. Allows easy multi-selection and
4. Uploads all selected with a single click.

**Comment by jospoortvliet** [comment]
@Bugsbane that sounds like a pretty clever thing. Perhaps you can even just take the current upload dialog and let it hide things (behind a 'previously uploaded' button) which are already on the ownCloud server...

**Comment by Bugsbane** [comment]
Even better. Maybe a "Hide previously uploaded" checkbox or something.

**Comment by fduraibi** [comment]
Similar to https://github.com/owncloud/android/issues/643

**Comment by tobiasKaminsky** [comment]
There are good ideas how to improve the uploader, like @Bugsbane has suggested.
But this issue is about the delay of instant upload. 
So please keep only one topic per issue.
I close this issue in favor of #643.

@Bugsbane I have added your ideas as a new issue: #1038
