### ISSUE TITLE
Internal music player does not stop playing when file is deleted

### ISSUE THREAD

**Issue by smu** [owncloud/android#906]
### Steps to reproduce:

1. Download a sound file 
2. the internal player starts to play the track
3. return to file list
4. player continues to play in the background
5. delete the file (locally and remote)

### Expected behaviour
The player should stop.

### Actual behaviour
Instead the player is still playing and the only possibility to stop it is to kill the owncloud app. At least I could not find another solution.

### Environment data
owncloud server: 8.0.0.7
owncloud-app: 1.7.0

**Comment by masensio** [comment]
Hi @smu 

thanks for your feedback and for details of this bug.

We will take into account in future bugfixing about media files, but I don't know when exactly. 
Any volunteer?

**Comment by davivel** [comment]
Fixed, will be released in version 2.2.0
