### ISSUE TITLE
JPG upload seems to be corrupted

### ISSUE THREAD

**Issue by Erik8219** [owncloud/android#91]
Hey

uploaded jpg per ownCloud-client on a Android device seems to be damaged. Pictures are not readable on other devices. 

Tested:
Samsung Galaxy 3 mini -> Ubuntu 12 -> file damaged
Samsung Galaxy Tab (GT1000) -> Ubuntu 12-> file damaged
Samsung Galaxy 3 mini -> Samsung Galaxy Tab (GT1000) -> file damaged
Ubuntu -> Samsung Galaxy Tab (GT1000) -> file ok
Ubuntu -> Samsung Galaxy 3 mini -> file ok

Versions:
ownCloud 4.5.6
Linux ownCloud-client 1.2.0
Android ownCloud client  1.3.20

**Comment by davivel** [comment]
Closing this due to lack of response; please, reopen if needed.

Thanks.

**Comment by ocdtrekkie** [comment]
I also experience this using client 1.9.1 with the Davros server (server is not ownCloud, client is). I suspect this is a client issue, as other DAV clients do not have the same behavior.
