### ISSUE TITLE
Conflict dialog wording confusing

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#915]
#### Steps
1. Upload file "test.txt" directly to server
2. Open Android client
3. Pick "Keep in sync" for that file and wait for download
4. Go offline (airplane mode)
5. In the web UI, change "test.txt" and save
6 On mobile (still offline), edit "test.txt" too and save
7. Go back online
8. Long press on "test.txt" and pick "Refresh file"

At this point you get a dialog that says:
"Remote file "test.txt" is not synchronized with local file. Continuing will replace content of file on server" with three buttons: "Don't upload", "Keep both" and "Overwrite".

I want to overwrite the local file, so should I pick "Don't upload" or "Overwrite" ? Does "Overwrite" mean "Overwrite server file" or "Overwrite local file" ?
"Don't upload" could also mean "Do not overwrite server version but overwrite local version".

This is very confusing and even scary as I'm afraid to lose the wrong changes.

Also the dialog mentions "continuing" but there is no "continue" button.

How about changing the labels to "Use local version", " Use server version" and "Keep both" or something more explicit ?

To be discussed with @owncloud/designers

**Comment by PVince81** [comment]
I just tried "Don't upload" and it seems to just cancel ?
The local content is still there, it was not overwritten by the server content

I'm still too scares to tap "Overwrite" because it is not clear whether it will overwrite the local content or the remote content... Also this means there is a missing option. If one overwrites the local file, where is the option to overwrite the remote file ?

**Comment by PVince81** [comment]
Any update on this ? I recently deleted the wrong file because I misunderstood the options.

A short term fix would just to fix the wording of the labels.
@jancborchardt what do you think ?

**Comment by jancborchardt** [comment]
Good call @PVince81. The three buttons should be:
* Use local version
* Use server version
* Keep both

@rperezb @davivel

**Comment by tobiasKaminsky** [comment]
+1
This should be very easy done via transifex?

**Comment by jancborchardt** [comment]
No, the original text needs to be changed here in the source code, right?

**Comment by tobiasKaminsky** [comment]
Ah yes.
You are right.
Shall I do this? Or do we wait for approval by @rperezb and @davivel ?

**Comment by jancborchardt** [comment]
@tobiasKaminsky I’d say do it, with the text I suggested above and then we can discuss in the PR. Pretty sure it’s better than it is now.

**Comment by masensio** [comment]
Fixed in develop.
