### ISSUE TITLE
"Conflicts found" notification should link to folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/android#916]
Whenever I use "Refresh account" there is a notification "Conflicts found" that appears in the notification bar of Android.
Tapping it doesn't do anything.

I still have no idea what file is causing the conflict.

Some suggested changes:
1) Add the name of the file in the notification (but could be a problem if many files)
2) Tapping the notification should open the client in the folder with the conflicts, scrolled down to the file in question

I realize that this might not work when more than a single file has conflicts. But redirecting to the first one would already help a lot. I could then solve it then refresh again, then tap the notification to go to the next conflict. (that would be the quick fix)

That or... a special dialog/list with the conflict files ?

I hope one day I'll discover which one of my files is the one with conflict. I checked all folders and there is no file with "(2)" so I cannot find where it is...

@owncloud/designers

**Comment by davivel** [comment]
Hopefully

> That or... a special dialog/list with the conflict files ?

someday.

**Comment by rperezb** [comment]
Ey @PVince81 the idea is to create a new view uploads, as it is on the iOS app. 
In this view uploads are handled, those in progress, recents and failures one, you may check the thread on https://github.com/owncloud/android/pull/821

**Comment by davivel** [comment]
> as it is on the iOS app. 

Or even better.

:P

**Comment by ares** [comment]
+1, long standing issue

**Comment by LudovicRousseau** [comment]
+1, I am not sure I can trust an application that tells me something bad happened but I have no idea what nor how to solve it.
I am using ownCloud Android client version 1.8.0 from F-Droid.

**Comment by PVince81** [comment]
Just had a conflict again and the new Android client shows a red arrow icon to mark conflicted files. Then upon synchronizing the dialog had greatly improved wording.

I think this ticket can be closed as fixed.

Thanks a lot!

**Comment by PVince81** [comment]
#1068 seems to be the wording fix

**Comment by PVince81** [comment]
To clarify, the red arrow also appears on parent folders, so it's easy to see in which folder there are conflict files

**Comment by tobiasKaminsky** [comment]
Oh man, this is sooo long ago, I even did not know that I have implemented this :/
