### ISSUE TITLE
Dependecies error while building project using gradle

### ISSUE THREAD

**Issue by ananthula-ravali** [owncloud/android#922]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android-master'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:19.1.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/19.1.0/support-v4-19.1.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/19.1.0/support-v4-19.1.0.jar
         file:/..~/android-master/libs/support-v4-19.1.0.jar
         file:/..~/android-master/libs/support-v4.jar
     Required by:
         :android-master:unspecified

**Comment by masensio** [comment]
Hi @ananthula-ravali,

How are you using gradle, directly in command line or through Android Studio? 
We are using gradle Android Studio, and we don't have any problems with the compilation process.

**Comment by ananthula-ravali** [comment]
i am it from command line...

**Comment by ananthula-ravali** [comment]
i am doing it from command line..

**Comment by davivel** [comment]
Duplicated. Please, join to #829 to follow the topic
