### ISSUE TITLE
Move files to owncloud

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#925]
Hello,

I would like to add a new option: Instead of copying files during upload it should also be possible to move them.
Imagine this scenario: I have a lot of old images I would like to get off my phone to owncloud.
Currently:
- open owncloud
- add photos
- in gallery: select the same photos and delete them

With the new option these photos will be moved from e.g. DCIM to the owncloud folder (and as we have the update of media library they are still accessible by gallery. So there is no change for the user. After the successful upload the user can select the folder and delete it locally.

Optional there should also be a setting to delete the files directly after successful upload.
This will simplify the steps again.

What do you think? @davivel @masensio @jancborchardt

**Comment by masensio** [comment]
I think this is an interesting idea.
Although I don't know if the users will be confused with two options to add files to OC (from the app) or the idea will be clear for them. Maybe, as in other apps, "Move to" will be clear enough because this action cuts and pastes the files and doesn't copy them.

**Comment by jancborchardt** [comment]
Yeah, I’m also not quite sure about this. :\ Even though it’s kind of a strawman argument I would say there’s lots other more important stuff which has to come first.

**Comment by tobiasKaminsky** [comment]
@jancborchardt I know that there are more important things to do. But for my girlfriend this is an important feature. So I will implement it anyway. Therefore I thought it is a good idea to have this included in upstream. (and of course we can discuss about improvements)

**Comment by Morganlej** [comment]
I really would like this.  We sometimes take photos at work in field, but the phones are to small and weak even to browse and delete bad photos - so all need to go to another computer somehow in an easy way.  All photos and video are leaving the phone this way.  Still the quickest and easiest way is to umont and move the sd card to computer physically.  But i see a more modern way is coming here, thanks  :)

If i can wish, i would like to be able to set which directories owncloud should synk with server (automatically or when i trig it), and which of those it should only upload from, and in which of those it should delete originals (*after checking they are safe on the server of course*)

**Comment by vDorst** [comment]
+1

**Comment by tobiasKaminsky** [comment]
@Morganlej This feature idea has nothing to do with sync. 
Regarding your first paragraph: Why not use instant upload folder? When the upload is done you can delete the images on the device.

**Comment by Morganlej** [comment]
1) It would be great if it is automated so i do not need to check if all files are uploaded and then delete manually.  Currently it is much easier to connect USB cable and have phone in storage device mode, or move sd card and use a dual pane file manager to move files.
2) Instant upload folder: do you mean what is trigged by taking a photo?  Do not work on my device, at least not with original camera.  Besides most often we are not at office when taking photos, and do not want to expose owncloud to internet so upload must go via local wifi.
2b) Or is there another type of instant upload i have missed?  I must admit i never found a good documentation of this app...
* I whish we could define some folders owncloud would sync when it is in reach, and some of then it should it empty after upload.

**Comment by benoiton** [comment]
AFAIK:
* photo app put photos in camera folder
* photos are uploaded to owncloud server *and* copied in local owncloud folder
* therefore photos are presents twice on smartphone

Was there any change? It seems to me they were not copied in local owncloud folder in previous versions of owncloud app?

It would be great to choose between:
* do not send photos
* send photos to owncloud server and keep them only in camera folder
* send photos to owncloud server and remove them from the smartphone
* send photos to owncloud server, copy them in owncloud folder and keep them in camera folder
* send photos to owncloud server, copy them in owncloud folder and remove them from camera folder

**Comment by Zenopheus** [comment]
Please implement this! I found this post while looking for this feature.
@jancborchardt As a user, there is nothing more practical and important than this.
Don't get me wrong it's cool to sync images with my home. Although I have 100 times more images than I could ever fit on my phone and no time to organize them. Syncing is nice but impractical.
I would much rather have some automated service *move* my wife's pictures off of her phone so I have the time to enjoy cool features. I would like something like this:
   Move images/videos when free space is less than:   [num]%

The user can enter a value between 0-100.

**Comment by tobiasKaminsky** [comment]
let us do this step by step.
Currently I have implemented two option:
- move the files from origin location to the owncloud folder on the device
- upload the file and delete it on original location and do not create a copy in owncloud folder. 

I will add an PR soon.

All other suggestions like moving them automatically should be discussed in a new issue.

**Comment by tobiasKaminsky** [comment]
PR: #1069

**Comment by enoch85** [comment]
This is fixed in https://github.com/owncloud/android/pull/1168 --> Close. cc @tobiasKaminsky
