### ISSUE TITLE
mass-select files and folders to be synced now

### ISSUE THREAD

**Issue by janklostermann** [owncloud/android#926]
I am missing the possibility to mass-select files and folders to be synced

User Story:
to be able to simply sync a whole folder structure at home with broadband before I go out where I have weak or no connection

**Comment by masensio** [comment]
Hi @janklostermann,

thanks for your ideas. 
The multi-selection option is a pending task in our app. Also we have folder sync in our minds (https://github.com/owncloud/android/issues/3)
We will have this improvements for future versions of the app.

**Comment by mase76** [comment]
I would suggest to select whole folders to keep in sync, or even
the option to keep everything in sync. Marking single files to be
kept in sync or download them to the oc folder is very awkward.

**Comment by malkomich** [comment]
The multi selection is a Work In Progress PR, you can track it here: https://github.com/owncloud/android/pull/1176

I invite you to review it also :smile: 

@mase76 I guess this current issue (https://github.com/owncloud/android/issues/1136) is more related with your purpose
