### ISSUE TITLE
Auto-Sync big files (>= defineable_size) only with Broadband (WiFi)

### ISSUE THREAD

**Issue by janklostermann** [owncloud/android#927]
have a **general setting** to auto-sync big files (from a defineable size on?) only with broadband Wi-Fi, not with MobileData (3G, etc.)

Additionally in settings:
for foto and video (and even music/audio recordings?) upload split setting into:
    + immediate automatic upload
      + not via Mobile Data

**Connected with this:** 
Having the option of a warning with a Cancel-Button for a manually started mass sync (as described in #926 ).

Example for the Warning message:
'You are on Mobil Data. You really want to sync all big files (>= `definable_size`) as well?
Button 1: All
Button 2: only smaller (DEFAULT)

**Comment by masensio** [comment]
Hi @janklostermann,

thanks for your ideas.
I think these settings are interestings to limit the file size to sync on mobil data.

We will take into account for future improvements.

**Comment by zeckrich** [comment]
Hi,

any news on this enhancement?
We would be very interested in only sync big file on wifi! ;)

**Comment by davigonz** [comment]
Hello @zeckrich, there is no news to implement this enhancement at the moment. Thank you for your comment, we will take it into account and update this issue when we start to work on it.

**Comment by jesmrec** [comment]
Not planed ftm
