### ISSUE TITLE
Auto-Upload file additions in OC folders by other apps

### ISSUE THREAD

**Issue by janklostermann** [owncloud/android#928]
To add new files/folders automatically to Owncloud as soon as I copy/create them in the respective Owncloud folder in the Android file structure. (same behaviour as with the Windows client) 
#### Today

I can only create a new folder in the OC client. (Not a new file, e.g. a text file as in the web interface.)
To integrate a new file I have to explicitly upload it, by searching it in the android file tree and select it manually (one by one).
#### Wanted:
1. If I edit a OC file with my prefered text editor (or whatever) and then create a new file with the text editor saved just beside the existing file (in the android OC file tree), I want this file/folder to be automatically added to the sync with this OC folder as well. (*_needed_)
2. The option of creating a file (not just a folder) from the OC android client (**nice-to-have**, as you probably would need to limit it to .txt anyway, which limits the value of this feature significantly.)

**Comment by masensio** [comment]
Hi @janklostermann,

thanks for your ideas.
There are other issues about creating and editing text file:
https://github.com/owncloud/android/issues/88
https://github.com/owncloud/android/pull/707

**Comment by jesmrec** [comment]
Document provider is here to help with this.
