### ISSUE TITLE
Android studio build problem

### ISSUE THREAD

**Issue by vsvankhede** [owncloud/android#931]
I am using android studio. Trying to build the project.
But it's giving following error. when I am trying to build.

/build.gradle

Gradle 'android-develop' project refresh failed
Error:Configuration with name 'default' not found.

Error at line: artifacts.add("default", file('libs/actionbarsherlock.aar'))

What is the problem?

**Comment by masensio** [comment]
Hi @vsvankhede,

we are also using Android Studio to build the project, but we don't have this problem.
Do you have actionbarsherlock_lib in the libs project folder?

**Comment by vsvankhede** [comment]
Hi @masensio ,

Yes actionbarsherlock_lib is in the libs project folder.

**Comment by vsvankhede** [comment]
Should I need any plugin installed in android studio?

**Comment by masensio** [comment]
I don't think that I didn't install extra plugins to compile this project. Just in case, this image shows the plugings which I have installed
![image](https://cloud.githubusercontent.com/assets/3862330/7066305/9cc8d778-dec1-11e4-96b3-68c109dfedf8.png)

**Comment by davivel** [comment]
@vsvankhede , ActionBarSherlock is not a dependency of the project anymore.

Would you like to try again and tell us if you can build the project?

Thanks

**Comment by vsvankhede** [comment]
@davivel Yes I would like to try it again. I will send you details after testing it. 

Thanks

**Comment by tobiasKaminsky** [comment]
@vsvankhede is this still valid?

**Comment by AndyScherzinger** [comment]
@vsvankhede if you use the latest master simply:
* call ```git submodule init``` (on command line)
* call ```git submodule update``` (on command line)
* import in Android Studio

That should be it. The latest master now only supports the gradle build system.

**Comment by davivel** [comment]
@vsvankhede , do you still have problems to build the project?

Thanks in advence.

**Comment by kigero** [comment]
I had the same issue, but running `git submodule init` and `git submodule update` fixed it for me - just in case that helps close this issue.

**Comment by davivel** [comment]
Thanks!
