### ISSUE TITLE
Cannot Download files with Android Client

### ISSUE THREAD

**Issue by castanley** [owncloud/android#945]
It would appear that when using ownCloud Android client version 1.7.1 when trying to download files that were uploaded with the web interface I get a "Download failed" every time. However, if I use the URL in a mobile browser and log in and download, it works fine. I have no errors in the log files on the server. This leads me to believe it is an application problem.

I would love to provide more information, if someone can give me an idea of what to provide.

**Comment by EtienneBruines** [comment]
It might be related to #940, but I'm not sure.

**Comment by tobiasKaminsky** [comment]
Can you test this with the demo account of owncloud.org to eliminate the server as cause of the problem?

**Comment by castanley** [comment]
When testing on the Demo it works fine - Interesting. What can I do to debug the problem? What is weird is images and videos download fine - but files that don't have extensions (my ssh public and private keys) fail and PDF's say "2147483647% Downloading <filename>" and hangs at that crazy percentage amount, then says failed after a minute or two.

Like I said, images and videos work fine in the app - Everything works fine from the web interface. Any suggestions?

**Comment by masensio** [comment]
Hi @castanley,

sorry for the delay. I've tried to reproduce the problem, but I download files properly.
Did you have this problem with the previous version?

Could you give us more details about the issue? Some extra details such as Android version, device, server version are welcomed. It is interesting for knowing something more about the problem if your server has configured some external storage.
Please, send us this information using the template: https://github.com/owncloud/android/blob/master/issue_template.md

Thanks for your feedback.

**Comment by tobiasKaminsky** [comment]
No feedback, therefore closing it.
If it still occurs please reopen with more feedback.
