### ISSUE TITLE
Fix camera instant-upload (suggestion inside)

### ISSUE THREAD

**Issue by MichaelHeimann** [owncloud/android#948]
Hi,

I've just moved from my Samsung S4 with stock camera to oneplus one with several camera Apps: "Kamera", Focal Google "Kamera". Only the Google Kamera App seems to trigger an owncloud upload. 

But all trigger a Google Picture Backup-Upload.

I understand that the apps might not send the correct broadcast (as in issue #760), but could you *please* think about an option in owncloud to enable something like a Poll of the Camera Folder to check for new files? (any file, don't be smart and ignore files you don't think are worth it)
Like in Issue #6 the FolderObserver class could be a way.

This is really the whole purpose why I bought the official app - please improve it!

Thanks,
Michael

**Comment by vDorst** [comment]
This is also an issue on BlackBerry OS 10.
BlackBerry doesn't send a broadcast in to Android shell.
So select folder for manual syncing is fine for me.

**Comment by tobiasKaminsky** [comment]
This could be handled with #744 
But this needs some more attention until it will be merged.

**Comment by tobiasKaminsky** [comment]
PR is #1650

**Comment by davivel** [comment]
@MichaelHeimann , please, follow any updates on this topic in #6 and #744. This is issue duplicates them.

Thanks for your patience.
