### ISSUE TITLE
Background sync

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/android#949]
Does the Android app support background sync? 
If not, is there any plan to incorporate such a feature in the near future?
Thanks!

**Comment by masensio** [comment]
Hi @fossxplorer,

you can enable background sync from Account Manager. But background sync could drain your battery if you have a lot of folders. (We know that other users have this problem #953)
We need to improve the sync process to avoid this feature doesn't waste so much battery, but I can say you when we will do it.

Thanks

**Comment by leafcutterant** [comment]
Background sync option is no longer available (I'm on 2.5.0 but this was removed probably much earlier).

I see the tendency that you guys don't want to complicate the settings sections, but you also kill off options that were already implemented. This makes the app very non-useful. If you are so determined to keep thing out of the sight of the non-technical user, at least make these thing available in an "Advanced settings" menu or via some secret menu that can be accessed e.g. by tapping five times on the version line.

**Comment by jesmrec** [comment]
Currently, background feature syncs files in max 15 minutes.
