### ISSUE TITLE
move operation does not work

### ISSUE THREAD

**Issue by zhangjindou** [owncloud/android#950]
Hi,
I find the MOVE operation does not work well on my phone.
When I move one file in one folder to another,it will delete the file in source folder and the file shows up in one sec in destination folder,then it disappears.Also,I cannot find the file at my account in website.
My owncloud android version is 1.7.1 and owncloud server version is 8.0.2.
I use Openstack Swift as back end storage.

Looking forward to your solution! Thanks!

**Comment by tobiasKaminsky** [comment]
Can you verify this problem with the demo account?
demo.owncloud.org
user: test / password: test

A quick test did not show this behaviour for me.

**Comment by zhangjindou** [comment]
@tobiasKaminsky Thank you for your reply!
I use Swift as my owncloud primary back-end storage while demo account uses Database.
I test it works when using Database.

**Comment by tobiasKaminsky** [comment]
@zhangjindou is this still valid?

**Comment by davivel** [comment]
Closing. @zhangjindou , add a comment if this is still an issue for you.
