### ISSUE TITLE
[Feature Request] "Pin" a directory — make changes being made to it remotely be automagically downloaded

### ISSUE THREAD

**Issue by Cysioland** [owncloud/android#952]
As in title.

For example, I have a photo folder, which I want to have always handy to show someone. So I pin the "Photos" folder, and, when on WiFi, it periodically syncs that folder.

**Comment by akrob** [comment]
+1

**Comment by masensio** [comment]
Hi @Cysioland,

I think the feature you are requested is keep-in-sync folder, isn't it?
In this case, this request is duplicated. You can see in #3.
So  I'll close it. If you think it isn't included in #3, please reopen it.

We have it in our roadmap "Keep in sync" option for folders also.
I hope it will be available in a near future.
