### ISSUE TITLE
Android Sync API

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/android#958]
Are there any plans to create a sync API that can be used by other apps (similar to the [dropbox API[(https://www.dropbox.com/developers/sync)), or is there maybe such a thing already for Android?
What I would like to achieve is being able to upload files from another app to ownCloud.
Do you maybe have any tips/recommendations on how to best achieve this?
From a quick research on the source code here and a search for WebDAV libraries for Java I doubt it, but is there maybe a simple way to do this generically for WebDAV via some library?

I know this is not really an issue with the app, but I think this is still the best place to ask this question (considering that the [android devel mailing list](https://mailman.owncloud.org/pipermail/android-devel/) appears to be empty).
Sorry if this is not the right venue to ask this, and thanks in advance for any pointers!

**Comment by masensio** [comment]
Hi @RandolfCarter,

thanks for using OwnCloud.

OwnCloud have a library to do the operation with ownCloud files. 
https://github.com/owncloud/android-library
You can communicate easily with ownCloud servers using this library.

I hope this library helps you. Enjoy using it! :smile:

**Comment by RandolfCarter** [comment]
Thanks a lot! Not sure how I could miss that ;).
