### ISSUE TITLE
Blacloud.de client for Android sync with owncloud. Instant upload photos in Android

### ISSUE THREAD

**Issue by cga** [owncloud/android#961]
A new feature I would suggest:

I use in Android Blacloud.de to sync my photos to my owncloud
 
I would prefer if Instant upload folder doesn't get created in Android phone with photos taken by the camera.  This create duplicated photos in my phone.  Then I have the same photos in the gallery and in the Instant upload folder created by Blacloud.de 

Rather is the client for android sync all photos taken by my phone from the phone gallery to the Owncloud 

Please no  "Instant upload folder"

**Comment by davivel** [comment]
This is subsumed by #819.
