### ISSUE TITLE
Share with owncloud : possibility to create a directory

### ISSUE THREAD

**Issue by orzel** [owncloud/android#965]
Quite often i want to share a bunch of images from my phone. For that i select (say) 10 photos using my viewer application, and then 'share' with owncloud. Typically i would create a new directory there to put my photo in.
This seems (to me) a pretty common way of doing. Currently it is not possible. You have to first (using the phone or the browser on your desktop compuer) create the directory, then goes back to the image viewer and upload them (and usually you're hit by #198 , but it's another issue)

**Comment by tobiasKaminsky** [comment]
This is done in #923 and should be available in the next version.

**Comment by masensio** [comment]
This feature is available in the current version (1.7.1)

**Comment by tobiasKaminsky** [comment]
My fault. As I am using branch dev I did not know that it is already available. :)
