### ISSUE TITLE
Syncing existing photos/files?

### ISSUE THREAD

**Issue by rkarlsba** [owncloud/android#968]
I just installed opencloud8 and the android app and I find it works well, but… I can't find a good way to synchronise existing pictures without uploading them manually, either one by one or with file upload, meaning I have to select each file manually. It would be nice if the client could sync the entire gallery. Is this behaviour planned?
Best regards
roy

**Comment by davivel** [comment]
Hi, @rkarlsba . 

This has been already requested in #454. It was difficult to find, I'll update the name of the issue.

Unfortunately, we still have no estimated time of arrival for this.

Closing this issue as duplicated.
