### ISSUE TITLE
CHANGELOG.md hasn't been updated for 1.9

### ISSUE THREAD

**Issue by JohnVeness** [owncloud/android#971]
File CHANGELOG.md hasn't been changed when 1.7.1 was released, and still refers to 1.7.0. This matters because users who download Owncloud from F-Droid (https://f-droid.org/repository/browse/?fdid=com.owncloud.android) are linked to https://github.com/owncloud/android/blob/HEAD/CHANGELOG.md which is currently out of date.

**Comment by masensio** [comment]
Hi @JohnVeness,

sorry for the delay.
Changelog is updated now.
https://github.com/owncloud/android/blob/HEAD/CHANGELOG.md

**Comment by JohnVeness** [comment]
Same problem with 1.9.0

**Comment by tobiasKaminsky** [comment]
cc @masensio

**Comment by masensio** [comment]
Ups, sorry I forgot to update the changelog here

**Comment by masensio** [comment]
Changelog updated again :smile: 
You can see at:
https://github.com/owncloud/android/blob/HEAD/CHANGELOG.md
