### ISSUE TITLE
How to avoid entering login information when testing?

### ISSUE THREAD

**Issue by donniezazen** [owncloud/android#972]
How do you guys avoid adding site-url, username, and password when testing?

**Comment by davivel** [comment]
We don't avoid it. We enter it.

Maybe I'm not fully understanding your context. What do you exactly mean "when testing?" Are you manually testing in your device, or are you talking about triggering automatic tests, such as those in the OC library?

**Comment by donniezazen** [comment]
@davivel Yeah, manually testing on the device or emulator. So when you are not concerned about the server related stuff and want to see how one of your changes look in the app on device. For example, I am working on ActionBar logo and I just want to see how that image looks there. In this case I just have to enter the site-url, login and password ones but I thought maybe there is a way to skip login page.

**Comment by davivel** [comment]
If you keep open the emulator the app should just be reinstalled (upgraded), and the account be valid after that. You should not need to reenter the server data. Same for the device.

**Comment by donniezazen** [comment]
That works.

**Comment by davivel** [comment]
Happy to read it :)
