### ISSUE TITLE
Android.bat not recognized when Running setup_env.bat

### ISSUE THREAD

**Issue by shayr1** [owncloud/android#976]
I ran setup_env.bat and all goes well until I get a few times this message:
This is the output:

"Executing Gradle setup..."
'android.bat' is not recognized as an internal or external command,
operable program or batch file.
'android.bat' is not recognized as an internal or external command,
operable program or batch file.
'android.bat' is not recognized as an internal or external command,
operable program or batch file.
'android.bat' is not recognized as an internal or external command,
operable program or batch file.
"...setup complete."

After that Build "succeeds", but the APK is not parseable on my android phone.

Any help would be appreciated.

**Comment by masensio** [comment]
Hi @shayr1,

thanks for using owncloud.

I have compiled the project using Eclipse and Android Studio without problem.
How are you generating your apk file? Are you using Eclipse, Android Studio or another tool?

**Comment by shayr1** [comment]
Hi @masensio 
Thanks for the fast reply

My problem begins when I run the file "setup_env.bat", which I should do before running the build according to the instructions.

I am using Android Studio for the build itself. I can get an APK, but then on my phone it fails to parse when I try to install it.

**Comment by tobiasKaminsky** [comment]
But the file is accessible for your user in the right place?

**Comment by davivel** [comment]
@shayr1 , you need to include the full path to the folder 'tools/' in your Android SDK installation in the PATH variable. You should be able to execute 'android.bat' in the Windows command prompt after that, and the script will work fine then.

**Comment by w7virtual** [comment]
I have same problem!

**Comment by davivel** [comment]
@shayr1 , @w7virtual, did you check the content of your PATH variable?

Please, open a terminal and type

```echo %PATH%``` in Windows , or

```echo $PATH``` in Linux / Mac OS.

Can you see included the path to the 'tools' folder in your Android SDK installation?

**Comment by davivel** [comment]
@shayr1 , @w7virtual , any answer?

**Comment by jesmrec** [comment]
Outdated. Feel free to reopen if you have any other issue.
