### ISSUE TITLE
Auto-Upload duplicating files, why?

### ISSUE THREAD

**Issue by masterdam79** [owncloud/android#977]
When my camera app snaps a picture it ends up in the DCIM folder and the Owncloud app uploads it which is all fine and dandy but why on earth does the owncloud app copy the photo to SD/owncloud/user@host/InstantUpload before it gets copied to the owncloud server?

Having duplicates of all my photos takes up valuable storage.

**Comment by masensio** [comment]
Hi @masterdam79, 

thanks for using owncloud.
Sorry, but the app duplicates files in the upload process. 

This issue is included in https://github.com/owncloud/android/issues/819, please track it there.
