### ISSUE TITLE
Share links not working

### ISSUE THREAD

**Issue by MrFly** [owncloud/android#979]
Hi,

first of all: I already wrote an email to the developers, but for tracing, I'm opening this issue.

What I have:
- OwnCloud 8.0.3 on Linux
- Android app v1.7.1
- Android 5.0.2
- Nexus 6

Owncloud settings (sharing, number of checkbox order in braces):
- allow share api (1)
- allow to share links (2)
- NOT force password (3)
- NOT allow public upload (4)
- allow users to send email notifications (5)
- set default date (6): 1 day -> do NOT force date
- allow re-sharing (7)
- do NOT restrict to groups (8)
- allow users to send email notifications (9)
- do NOT restrict to groups (10)

What I did (app):

- choose account: one user, one admin
- browse to a folder or file
- select "share link"
- select app to share (tried with email and others)

What then happens:

- sometimes message appears "you have no permissions to share this file"
- sometimes a password input dialog appears
- if the dialog appears: Can't leave the pw blank -> fails (you have to enter a password)
- if I select "cancel" -> nothing happens
- if I enter a password -> you do not have permissions to share this file

What I expected:

- because of the settings at oc I awaited the email app to be opened to share the link: with and/or without password

If I can provide you further informations, please let me know. Also it would be possible to provide you a "test" user account at this server instance.

Please notice: My app and server is located to germany, so there's a great chance the given messages I provided does not match 1:1 to the orginal messages. I simply tried to translate by myself.

Thanks!

**Comment by masensio** [comment]
Hi @MrFly,

thanks for your feedback. 
I've tried to share a folder with a server with your sharing configuration and I've obtained the same result as you.

This bug is reported in https://github.com/owncloud/android/issues/633. Please track it there.

For sharing files/folders using Android app you must enable the option "Allow public uploads" . You can use this option as a workaround.

Sorry for the incovenience.
