### ISSUE TITLE
MATERIAL DESIGN: add a floating action button to create folders and upload files

### ISSUE THREAD

**Issue by davivel** [owncloud/android#983]
Floating action button is the all-new all-different widget provided in Material Design to place the primary action available for the user in a screen. I think it fits nicely for adding files to OC, instead of having the icons in the top bar.

A bit more about floating action buttons in http://www.google.com/design/spec/components/buttons-floating-action-button.html .

I can see it in Gmail right now, even in Android 4.x devices, so I expect it's included in the Android Support Library. In this case, we should use it for all the Android versions. If not, my take would be add it only for Android 5.0+.

I doubt about how many options should be shown when clicked. My first instinct is to group together 'create folder', 'upload file', 'upload from other apps'; but maybe it's too much, and 'create folder' could stay in the action bar. Opinions here, please!

cc: @jancborchardt , @tobiasKaminsky, @masensio

**Comment by Kernald** [comment]
On the technical side: the floating action button is not included in the support library. Neither it's a standard component in the SDK (even in 21). While there are third-party implementations, Google provides nothing (and its applications are not consistent at all in this regard).

**Comment by davivel** [comment]
Thank for the tips. We'll require some further research, then,

**Comment by jancborchardt** [comment]
If we use the button:
> My first instinct is to group together 'create folder', 'upload file', 'upload from other apps'

I totally agree with that.

**Comment by tobiasKaminsky** [comment]
I also think that these three should be accessible when clicking the FAB.
Is there some cool fancy overlay menu that we can use to present the three options?

**Comment by davivel** [comment]
Nothing new & fancy that I watched. But a dialog with the new style should do the work.

**Comment by tobiasKaminsky** [comment]
Yeah. This was also my intention. But I thought that there would be a new dialog type that could easily be updated and is from material design.

**Comment by Kernald** [comment]
There is. Take a look at the Toolbar and Speed dial sections here: http://www.google.com/design/spec/components/buttons-floating-action-button.html

**Comment by tobiasKaminsky** [comment]
@Kernald this is it!! :) :) :+1: 
@jancborchardt now we need some meaningful icons for
- create folder
- upload file
- upload from other apps
The first two already exist. The problem could be to distinguish between 2 and 3?

**Comment by davivel** [comment]
@Kernald, sorry, I cannot find the Speed dials. Is there a more precise link to it? Thanks.

**Comment by tobiasKaminsky** [comment]
@davivel Just search for "speed dial" or look at this video:
http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B6Okdz75tqQsVks0N1MxQ1JpOTg/components-buttons-fab-transition_speeddial_01_xhdpi_002.webm

![components_fab_flyouts_do](https://cloud.githubusercontent.com/assets/5836855/7793371/673cfcee-02be-11e5-84a9-5e2d6ca90e27.png)

**Comment by davivel** [comment]
Thanks, @tobiasKaminsky . Seems pretty cool.

**Comment by AndyScherzinger** [comment]
UNfortunately you have to implement it yourself. There is no google implementation for the speed dial...

**Comment by AndyScherzinger** [comment]
Erm, I would (like) to work on this, but won't find the time to work on this before begining/mid September though...

**Comment by AndyScherzinger** [comment]
I added a branch to work on it :smile: https://github.com/owncloud/android/tree/material_fab

**Comment by AndyScherzinger** [comment]
First implementation can be found on #1100

**Comment by davivel** [comment]
Ready to go in release 1.9.2.
