### ISSUE TITLE
Make App compatible with remotes e.g. for amazon fire tv and fire tv stick

### ISSUE THREAD

**Issue by kaystrobach** [owncloud/android#985]
1. Please add a focus indicator for the file and folder list view. This allows easier usage on non touch screen devices or with remotes.
2. Please declare, that the app is fire TV and fire TV stick compatible once point 1 is solved, which is true then.

**Comment by tobiasKaminsky** [comment]
Regarding 1. do you have some more informations? Is this only a visual thing or does this need more implementation? A tutorial or something like that would be great.
Or at least a screenshot, to see this in action.

**Comment by tobiasKaminsky** [comment]
https://developer.android.com/training/tv/index.html
Found something.

**Comment by kaystrobach** [comment]
1. is just a visual thing, using the remote does not make clear, which icon is selected.

maybe you can simply use the same hovering effect you use, when an element is clicked ;)

**Comment by tobiasKaminsky** [comment]
Yeah. I will look into it, when I have time.
The hovering effect is currently done via the built-in listView function.

**Comment by kaystrobach** [comment]
any news on that?

**Comment by davivel** [comment]
Sorry, no.
