### ISSUE TITLE
Can you please clearify the kind of sync this app does on info pages in general?

### ISSUE THREAD

**Issue by gerroon** [owncloud/android#989]
Hi

I use this app on Android. Well it says it is a sync app but as far as I can tell there is no syncing happening. I can browse my repo just fine but I see no syncing done. Therefor it would be nice if the sync features are outlined properly for the end users.

thanks

**Comment by davivel** [comment]
Hi, @gerroon.

What do you mean with "info pages"?

Thanks.

**Comment by gerroon** [comment]
@davivel 

I meant the gplay page or the main github page etc

**Comment by davivel** [comment]
OK, thanks. We'll have a look.

Currently the app offers next option to synchronize:

 - Fetch the list of files & folders of the account; manually, with the 'Refresh account' option in the action bar; or automatically, enabling the automatic synchronization of the account in the system settings, 'Accounts' section. This automatic synchronization is triggered by the system "whenever it wants".

 - File that are marked as kept-in-sync are synchronized (including their contents) when a 'refresh account' is done (manually or automatically), when the user browses into the folder containing them, or when an update on the local copy of the file is done by other app.

More complete sync' options will come when we have a chance.

**Comment by gerroon** [comment]
'@davivel

Thanks for the follow up. Do not get me wrong this is a great app and I use it daily. However I as a user feel like the sync portion is a bit on the crippled side which I can see why, time and resources do not come cheap. However I am glad to hear this app might get more advanced features at some point.

Keep up the good work.

**Comment by pascalBokBok** [comment]
So enabling "Sync files" in accounts will sync all files in your account to your phone?
I had no idea this even existed - it still doesn't say on the google play page and the app doesn't seem to hint it anywhere.
Why is this bug closed?

**Comment by gerroon** [comment]
@pascalBokBok 

I do not think it works that way. I tried it and it does not sync anything the way we want as far as I can tell.

**Comment by pascalBokBok** [comment]
@gerroon 
So what does the Sync do? It was disabled on my phone. (it still is because my owncloud has 230GB and my phone doesn't :smile: )

**Comment by gerroon** [comment]
@pascalBokBok 

That is the whole confusion around this app. It is not a sync app, it only syncs the files you tag in the app.

**Comment by pascalBokBok** [comment]
So then I don't understand why you closed this issue. Should it not be reopened?

**Comment by gerroon** [comment]
I closed it because it was clear that the confusion will be there for quite sometime. The devs do not seem to be much interested in turning this app into a real sync app for the time being. I am guessing that because there is not enough man power and time available.
