### ISSUE TITLE
Djvu files are shown as pic icons

### ISSUE THREAD

**Issue by gerroon** [owncloud/android#990]
Hi

I have bunc of Djvu files and OC client insists on showing them as icons with no names, therefor makes it hard to download and select the right file.

**Comment by rperezb** [comment]
Thanks for your comment. 
This will be changed in future versions, the idea is to offer between:
- Files view
- Grid view
Lets follow it status on: https://github.com/owncloud/android/issues/894
thx

**Comment by tobiasKaminsky** [comment]
Maybe it is possible to generate a thumbnail for this file type?
@gerroon would this help you?

**Comment by gerroon** [comment]
@tobiasKaminsky 
I am not sure. I am fine with names only as well. The issue is that in the thumbnail view, there are no names listed.
