### ISSUE TITLE
android client should retry automatically if no data is transferred after a while

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/android#991]
Expected behaviour

Tell us what should happen
I use a owncloud server over an ADSL connection with dynamic ip and accessible through a dynamic dns hostname. If during some file transfer, my adsl connections drops and reconnect , after a while owncloud client should detect that no data is being transfered, times out and retries. 

Actual behaviour
Client will hang forever in the same progress.

Server configuration

Operating system: Ubuntu 14.04 LTS

Web server: apache 2.4
Database: mysql
PHP version: 5.5.9-1ubuntu4.9
ownCloud version: 8.0.2-8
Storage backend: disk

Client version = 1.7.1

**Comment by tobiasKaminsky** [comment]
This should be fixed when #919 is committed
