### ISSUE TITLE
Constant looping trying to sync dropbox folder?

### ISSUE THREAD

**Issue by jas4711** [owncloud/android#992]
I added a dropbox share into my owncloud some time ago, and today I noticed why my battery has been drained from my phone recently.  The ownCloud app appears to sync the Dropbox folder over and over again, resulting in a high network utilization and battery usage.  I suspect this is not intentional.

Looking at 'adb logcat' output I see this pattern over and over again (this is just a snippet):

```
D/FileSyncAdapter( 3212): Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
D/RefreshFolderOperation( 3212): Checking changes in jas@moln.sjd.se/Dropbox/Possedo/Possedo - Grafiskt/
D/OwnCloudClient #358( 3212): REQUEST PROPFIND /owncloud/remote.php/webdav/Dropbox/Possedo/Possedo%20-%20Grafiskt/
D/FileSyncAdapter( 3212): Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
D/RefreshFolderOperation( 3212): Checking changes in jas@moln.sjd.se/Dropbox/Possedo/Possedo - Grafiskt/Logotyp/
D/OwnCloudClient #358( 3212): REQUEST PROPFIND /owncloud/remote.php/webdav/Dropbox/Possedo/Possedo%20-%20Grafiskt/Logotyp/
D/FileSyncAdapter( 3212): Send broadcast com.owncloud.android.syncadapter.FileSyncAdapter.EVENT_FULL_SYNC_FOLDER_CONTENTS_SYNCED
D/RefreshFolderOperation( 3212): Checking changes in jas@moln.sjd.se/Dropbox/Possedo/Possedo - Grafiskt/Mallar/
D/OwnCloudClient #358( 3212): REQUEST PROPFIND /owncloud/remote.php/webdav/Dropbox/Possedo/Possedo%20-%20Grafiskt/Mallar/
```

Ideas?

**Comment by jas4711** [comment]
Sorry, I forgot to mention: I'm running ownCloud Andriod App 1.7.1 from f-droid.

**Comment by davivel** [comment]
Integration of external storage some times results in unexpected problems in clients. I'm not sure how good is the manteinance state of the Dropbox app in ownCloud app in include. In any case, we'll have a look.

Thanks.

**Comment by michaelstingl** [comment]
There's is a new Dropbox API and a new ownCloud Dropbox integration. I'd assume this issue is gone. In case this happens again, please open a new issue. (too many things changed)
