### ISSUE TITLE
Cannot send files

### ISSUE THREAD

**Issue by the-username** [owncloud/android#994]
### Expected behaviour
The application is able to send a file to another application when pressing the send button of a downloaded file.

### Actual behaviour
At the moment, sending downloaded files directly from the owncloud application does not work.

When I press the send Button, for example while viewing a picture in owncloud and choose an e-mail client, the application opens without the picture. It is simply not there. There is just an empty e-mail without any attachments. 
The same happens when I select WhatsApp or any other application.

### Steps to reproduce:
1. Select a file
2. Press send
3. Select a random application

### Environment data
Android version: 5.1.1 and 5.0.2
Device model: Nexus 4 and LG L90
Stock or customized system: CM and Stock

ownCloud app version: 1.7.1
ownCloud server version: 8.0.3

#### ownCloud log
W/PackageManager(2316): Failure retrieving resources for com.owncloud.android: Resource ID 0x0

**Comment by tobiasKaminsky** [comment]
Is there a difference if the file is already downloaded or not?
Can you try it with the demo account:
demo.owncloud.org
test 
pw: test

For me with 1.7.1 and OC 8.0.3 it is working.

**Comment by the-username** [comment]
There is no difference if the file is already downloaded.

I discovered the reason, why my account is not working properly while the demo account is:
If the server you want to access is available at a different port (*[IP or domain]:[port]*) the application stores the files in the following directory: 
*owncloud/[username]@[IP or domain]%3A[port]/path*

However, the application which receives the file tries to access it using the following path:
*owncloud/[username]@[IP or domain]:[port]/path*
This is of course not possible because this directory does not exist.

If you change the directory after downloading some files manually to *owncloud/[username]@[IP or domain]:[port]/* you can send files, which you have downloaded earlier. However, sending new files does not work.


I think this is causing the issue and explains why not everybody is experiencing it.

**Comment by masensio** [comment]
Hi @the-username,

thanks for your feedback.
I've check this issue and we have a bug when trying to recover the file, as you said.

I'll fix it as soon as possible.

**Comment by davivel** [comment]
This is fixed and merged. Will be released with version 1.8
