### ISSUE TITLE
Show latest changes after update / fresh install

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#996]
After each update of the app there should be a dialog which informs about the latest changes:
**v.1.7.1**
- xy
- yz

**v.17.0**
- xx
- yy

This should include a brief description and show the latest 5 versions.
Also this dialog  should be displayed after a fresh installation.

**Comment by masensio** [comment]
Hi @tobiasKaminsky,

in the past, we had opened an issue related to have the changelog in the app: #335 
But the conclusion was https://github.com/owncloud/android/issues/335#issuecomment-35500601

@jancborchardt Are you thinking the same about showing the changelog in the app? 
What do you think about showing the latest changes into a dialog after a fresh installation?

**Comment by tobiasKaminsky** [comment]
I think that most of the user do not read the changelog in the app store but instead just have auto-update enabled.
Maybe it is sufficient to just mention big changes. 
As an example: Reading the comments in the google app store I think it would have been better to describe the new thumbnail/grid view there and mention, that it needs owncloud 7.x.

**Comment by jancborchardt** [comment]
I would not show a changelog. I always get annoyed when other apps (mostly open source ones tend to do that …) shove the updates in my face.

We should only show it if it's something really important. Like completed Material design rework where things might be different, or full sharing (with others on the instance) is possible from the mobile app. And then it should be a bit more attractive than just text.

**Comment by pierrejochem** [comment]
what about a message dialog with the hint: "New Version is installed! Show change log?" => YES/NO

**Comment by jancborchardt** [comment]
No – there will be no dialog. What we could do is have a changelog entry in the About dialog or whatnot. But really if people want to know what’s new, then they can just look at the changelog in the play store.

**Comment by tobiasKaminsky** [comment]
As I said: If we had mentioned that the thumbnails are only generated when they are downloaded or if the server is recent enough, I bet that there would not be so many negative entries in play store regarding thumbnails.
So my intention was only to highlight and describe/explain big changes...

**Comment by jancborchardt** [comment]
No, that was not the problem. The problem was that we didn’ŧ properly test all cases. Non-downloaded images should have never only shown the filetype icon in giant – but also with the filename below like all the other files. And since it doesn’t work with older servers, the app should know when it’s connected to an older server and just not show the grid view.

cc @davivel @rperezb I believe I also already stated that elsewhere.

**Comment by davivel** [comment]
Sorry, this was dismissed long time ago, and not only by @jancborchardt , but from higher levels. Won't be done.

About the negative reviews, please, get calm. The average rank is still higher than ever before in the history of the app. With the incoming 1.7.2 we provide a first step to control the problems with the automatic grid view. And we'll more improvements later. So, bad reviews will end, and should be considered with perspective as a punctual issue.

Won't be done.
